/* ============================================================
   ARABIC — ar.js
   ============================================================ */
Idiomas.registrar('ar', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "تم حذف الإشارة المرجعية.",
    "excluir_marcador": "حذف الإشارة",
    "o_marcador_sera_removido_permanentemen": "ستُحذف الإشارة نهائيًا.",
    "excluir_marcador_2": "حذف الإشارة؟",
    "pagina_salva": "تم حفظ الصفحة",
    "anotacoes": "ملاحظات",
    "citacoes": "اقتباسات",
    "item_excluido": "تم حذف العنصر.",
    "este_registro_sera_removido_permanente": "سيُحذف هذا السجل من المكتبة نهائيًا.",
    "configuracoes_padrao_restauradas": "تمت استعادة الإعدادات الافتراضية.",
    "leitura_da_esquerda_para_a_direita": "القراءة من اليسار إلى اليمين.",
    "leitura_da_direita_para_a_esquerda_man": "القراءة من اليمين إلى اليسار (مانغا).",
    "a_pagina_inteira_passa_a_caber_na_tela": "الصفحة كاملة تتسع الآن على الشاشة.",
    "a_pagina_passa_a_ocupar_toda_a_largura": "الصفحة تملأ الآن عرض الشاشة.",
    "virada_sem_animacao_ativada": "تقليب الصفحة بدون حركة الآن.",
    "virada_deslizante_ativada": "تقليب الصفحة المنزلق مفعّل.",
    "virada_em_folha_real_ativada": "تقليب الصفحة كورق حقيقي مفعّل.",
    "padrao_automatico_cada_formato_abre_no": "تلقائي: كل صيغة تُفتح بالطريقة التي تناسبها.",
    "mudando_durante_a_leitura_o_ajuste_fic": "إذا غيّرته أثناء القراءة، يبقى التغيير لهذا الكتاب وحده.",
    "automatico_usa_rolagem_horizontal_para": "تلقائي يستخدم تقليبًا أفقيًا لـ EPUB وMOBI وTXT وMD والقصص المصورة، وتمريرًا عموديًا لـ PDF وDOCX.",
    "este_livro": "هذا الكتاب",
    "armazenamento_local_indisponivel_neste": "التخزين المحلي غير متاح في هذا المتصفح.",
    "o_aplicativo_pode_procurar_os_livros_q": "يمكن للتطبيق البحث عن الكتب الموجودة بالفعل على جهازك.",
    "vamos_montar_sua_estante": "هل نملأ رفّك؟",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "بدون موافقتك، لا يمكن استخدام التطبيق.",
    "precisamos_do_seu_aceite": "نحتاج موافقتك",
    "antes_de_comecar_leia_e_aceite_os_docu": "قبل البدء، يرجى قراءة المستندات أدناه والموافقة عليها.",
    "selecionar_todos": "تحديد الكل",
    "limpar_selecao": "مسح التحديد",
    "todos_parecem_ja_estar_na_sua_estante": "يبدو أنها كلها موجودة على رفّك بالفعل.",
    "lendo_a_pasta_escolhida": "جارٍ قراءة المجلد الذي اخترته…",
    "procurando_livros": "جارٍ البحث عن الكتب",
    "nao_foi_possivel_concluir_a_busca_no_d": "لم يكتمل البحث على هذا الجهاز.",
    "tente_outra_pasta_do_aparelho": "جرّب مجلدًا آخر على جهازك.",
    "nenhum_livro_encontrado": "لم يُعثر على كتب",
    "use_o_botao_para_escolher_os_arquivos": "استخدم زر + لاختيار الملفات يدويًا. على هواتف أندرويد، يسمح Chrome عادةً باختيار مجلد كامل.",
    "seu_navegador_nao_permite_ler_pastas": "متصفحك لا يقرأ المجلدات",
    "busca_automatica_indisponivel": "البحث التلقائي غير متاح",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB وMOBI وCBZ وCBR وM4B",
    "termos_de_uso": "شروط الاستخدام",
    "politica_de_privacidade": "سياسة الخصوصية",
    "um_minuto_agora_evita_perder_o_progres": "دقيقة الآن توفّر عليك لاحقًا فقدان التقدّم والعلامات.",
    "ver_estante": "عرض الرف",
    "modo_juntar": "وضع الدمج",
    "modo_substituir": "وضع الاستبدال",
    "restauracao_concluida": "اكتملت الاستعادة",
    "tente_de_novo_com_o_arquivo_original": "حاول مرة أخرى بالملف الأصلي.",
    "a_restauracao_nao_pode_ser_concluida": "تعذّر إكمال الاستعادة",
    "devolvendo_o_seu_progresso_e_as_suas_m": "جارٍ إعادة تقدّمك وعلاماتك...",
    "restaurar_este_backup": "استعادة هذا النسخ الاحتياطي؟",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "اختر ملف .zip الذي حفظه Veredas، أو ملف .txt الذي تلقيته بالمشاركة.",
    "nao_foi_possivel_ler_este_arquivo": "تعذّر قراءة هذا الملف",
    "lendo_o_backup": "جارٍ قراءة النسخ الاحتياطي",
    "backup_do_veredas_reader": "نسخ Veredas Reader الاحتياطي",
    "arquivo_de_transporte_txt_contendo_os": "نسخة .txt من النسخة الاحتياطية، بالمحتوى نفسه الموجود في ملف ZIP",
    "nao_foi_possivel_montar_o_arquivo_de_b": "تعذّر إنشاء ملف النسخ الاحتياطي.",
    "escolher_o_app": "اختر التطبيق",
    "vale_conferir_o_que_vai_no_arquivo": "يستحق التحقق مما سيُدرج في الملف",
    "enviar_para_outro_app": "أرسل إلى تطبيق آخر",
    "salvar_o_arquivo": "احفظ الملف",
    "o_navegador_aqui_nao_oferece_o_compart": "المتصفح هنا لا يوفّر المشاركة المباشرة. يمكنك حفظ الملف وإرساله لاحقًا عبر التطبيق الذي تريد.",
    "este_aparelho_nao_abre_a_lista_de_apli": "هذا الجهاز لا يفتح قائمة التطبيقات",
    "importe_pelo_menos_um_livro_antes_de_f": "استورد كتابًا واحدًا على الأقل قبل إنشاء نسخة احتياطية.",
    "estante_vazia": "رف فارغ",
    "nao_deu_para_copiar": "تعذّر النسخ",
    "copiar_detalhes": "انسخ التفاصيل",
    "o_backup_foi_salvo_assim_mesmo": "تم حفظ النسخة الاحتياطية على أي حال",
    "o_aparelho_recusou_abrir_a_lista": "تعذّر فتح قائمة المشاركة",
    "sem_detalhes_do_navegador": "لا تفاصيل من المتصفح",
    "o_sistema_nao_aceitou_receber_o_arquiv": "تعذّر على نظام الجهاز استلام الملف.",
    "o_navegador_considerou_a_situacao_inse": "حجب المتصفح المشاركة بسبب إحدى قواعد الأمان الخاصة به. احفظ الملف وأرسله عبر التطبيق الذي تفضّله.",
    "o_compartilhamento_so_funciona_em_ende": "المشاركة تعمل فقط على عناوين آمنة. هذا التطبيق مفتوح من عنوان http:// عادي، وفي هذه الحالة يمنع المتصفح الإرسال إلى تطبيقات أخرى.",
    "este_navegador_nao_conseguiu_iniciar_o": "لم يتمكن هذا المتصفح من فتح المشاركة. احفظ الملف وأرسله عبر التطبيق الذي تفضّله.",
    "o_navegador_recebeu_um_arquivo_em_form": "لم يفتح المتصفح قائمة التطبيقات للمشاركة. المس الزر مرة أخرى، أو احفظ الملف وأرسله عبر التطبيق الذي تفضّله.",
    "nao_foi_possivel_gerar_o_backup": "تعذّر إنشاء النسخة الاحتياطية.",
    "reunindo_a_sua_estante": "جارٍ جمع رفّك...",
    "preparando_o_backup": "جارٍ تحضير النسخة الاحتياطية",
    "pronto_nada_mais_esta_esperando": "انتهى — لم يبقَ شيء في الانتظار.",
    "o_progresso_e_as_marcacoes_desses_livr": "سيُمحى تقدّم هذه الكتب وعلاماتها. إذا استوردت الملفات لاحقًا، ستعود الكتب بلا تقدّم ولا علامات.",
    "descartar_o_que_esta_esperando": "أتريد حذف البيانات التي في الانتظار؟",
    "lembretes_de_backup_religados": "تم إعادة تفعيل تذكيرات النسخ الاحتياطي.",
    "sem_titulo": "بلا عنوان",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "التذكيرات مغلقة.",
    "manter_ligado": "أبقِها مفعّلة",
    "desligar_assim_mesmo": "أغلقها على أي حال",
    "o_botao_de_salvar_continua_onde_sempre": "زر الحفظ في مكانه المعتاد، في النسخ الاحتياطي والاستعادة.",
    "o_lembrete_e_o_unico_aviso_que_existe": "التذكير هو التحذير الوحيد. من دونه، سيكون عليك أن تتذكّر النسخ الاحتياطي بنفسك.\n\n",
    "limpar_os_dados_do_navegador_desinstal": "إذا مُسحت بيانات المتصفح، أو أُزيل التطبيق، أو غيّرت هاتفك، أو تعطّل الجهاز، فلن يكون من الممكن استعادة التقدّم والتظليل والاقتباسات والملاحظات والإشارات.\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "رفّك موجود على هذا الجهاز وحده. لا نسخة على أي خادم، لذا لا سبيل لاستعادته لك.\n\n",
    "leia_antes_de_confirmar": "اقرأ قبل التأكيد",
    "desligar_os_lembretes_de_backup": "إغلاق تذكيرات النسخ الاحتياطي؟",
    "progresso_de_leitura_restaurado_neste": "تمت استعادة تقدّم القراءة لهذا الكتاب.",
    "pronto": "تم.",
    "aplicando_as_suas_preferencias": "جارٍ تطبيق تفضيلاتك...",
    "atualize_o_veredas_reader_e_tente_de_n": "حدّث Veredas Reader وحاول مرة أخرى.",
    "este_backup_foi_feito_numa_versao_mais": "أُخذت هذه النسخة الاحتياطية بإصدار أحدث من التطبيق.",
    "este_arquivo_nao_e_um_backup_de_biblio": "هذا الملف ليس نسخة احتياطية لمكتبة Veredas.",
    "o_conteudo_interno_nao_pode_ser_lido": "تعذّر قراءة المحتوى الداخلي.",
    "o_backup_esta_corrompido": "النسخة الاحتياطية تالفة.",
    "falta_o_arquivo_biblioteca_json_la_den": "ينقص ملف biblioteca.json في الداخل.",
    "este_arquivo_nao_parece_ser_um_backup": "هذا الملف لا يبدو نسخة احتياطية لـ Veredas.",
    "compactando": "جارٍ الضغط...",
    "para_restaurar_menu_lateral_backup_e_r": "للاستعادة: القائمة الجانبية > النسخ الاحتياطي والاستعادة > استعادة نسخة احتياطية.",
    "o_veredas_devolve_sozinho_as_marcacoes": "يستعيد Veredas تلقائيًا العلامات والموضع الذي توقفت عنده.",
    "importe_os_livros_normalmente_no_aplic": "استورد الكتب عادةً في التطبيق: عند التعرّف على كل ملف،",
    "ele_nao_contem_os_arquivos_dos_livros": "لا يحتوي ملفات الكتب. للاستعادة الكاملة،",
    "as_notas_os_marcadores_e_a_organizacao": "ملاحظاتك وإشاراتك وتنظيم رفّك.",
    "este_arquivo_guarda_o_seu_progresso_de": "هذا الملف يحفظ تقدّم قراءتك وتظليلك واقتباساتك،",
    "verificando_se_sao_partes_do_mesmo_aud": "جارٍ التحقق إن كانت هذه أجزاءً من الكتاب الصوتي نفسه...",
    "analisando_os_arquivos": "جارٍ قراءة الملفات",
    "nao_foi_possivel_salvar_o_audiolivro": "تعذّر حفظ الكتاب الصوتي.",
    "audiolivros_grandes_podem_levar_alguns": "قد تستغرق الكتب الصوتية الكبيرة بعض الوقت...",
    "salvando_na_sua_estante": "جارٍ الحفظ على رفّك",
    "falha_ao_processar_os_arquivos": "فشل معالجة الملفات.",
    "falha_ao_processar_o_arquivo": "فشل معالجة الملف.",
    "nao_foi_possivel_salvar_o_quadrinho": "تعذّر حفظ القصة المصورة.",
    "quase_la": "اقتربنا...",
    "falha_ao_processar_o_quadrinho": "فشل معالجة القصة المصورة.",
    "autor_desconhecido": "مؤلف مجهول",
    "lendo_o_quadrinho": "جارٍ قراءة القصة المصورة...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "تعذّر حفظ الكتاب في المكتبة.",
    "nao_foi_possivel_ler_o_pdf": "تعذّر قراءة PDF.",
    "lendo_o_pdf": "جارٍ قراءة PDF...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "إذا كان .doc قديمًا، افتحه في Word واحفظه بصيغة .docx قبل الاستيراد.",
    "este_arquivo_nao_e_um_docx_valido": "هذا الملف ليس .docx صالحًا.",
    "livros_com_protecao_da_amazon_nao_pode": "الكتب المحمية من Amazon لا يمكن فتحها هنا. استخدم نسخة بلا DRM أو حوّل الكتاب إلى EPUB.",
    "este_arquivo_esta_protegido_por_drm": "هذا الملف محمي بـ DRM.",
    "confira_se_a_extensao_corresponde_ao_c": "تحقق من أن الامتداد يطابق المحتوى، أو حوّل الكتاب إلى EPUB.",
    "este_arquivo_nao_e_um_mobi_valido": "هذا الملف ليس MOBI صالحًا.",
    "nao_foi_possivel_ler_o_arquivo": "تعذّر قراءة الملف.",
    "formato_nao_suportado": "صيغة غير مدعومة.",
    "falha_ao_salvar_o_livro_na_biblioteca": "فشل حفظ الكتاب في المكتبة.",
    "livro_importado_e_salvo_no_dispositivo": "تم استيراد الكتاب وحفظه على هذا الجهاز.",
    "audiolivro_importado_e_salvo_no_dispos": "تم استيراد الكتاب الصوتي وحفظه على هذا الجهاز.",
    "quadrinho_importado_e_salvo_no_disposi": "تم استيراد القصة المصورة وحفظها على هذا الجهاز.",
    "salvando_na_sua_estante_2": "جارٍ الحفظ على رفّك...",
    "importando_livro": "جارٍ استيراد الكتاب",
    "importar_mesmo_assim": "استورد على أي حال",
    "parece_que_este_livro_ja_esta_na_estan": "يبدو أن هذا الكتاب على رفّك بالفعل",
    "este_livro_ja_esta_na_estante": "هذا الكتاب على الرف بالفعل",
    "video_importado_e_salvo_no_dispositivo": "تم استيراد الفيديو وحفظه على هذا الجهاز.",
    "importacao_cancelada": "أُلغي الاستيراد.",
    "preparando_o_arquivo": "جارٍ تحضير الملف",
    "importando_audiolivro": "جارٍ استيراد الكتاب الصوتي",
    "importacao_concluida": "اكتمل الاستيراد",
    "importacao_interrompida": "توقف الاستيراد",
    "a_importacao_foi_interrompida_o_que_ja": "توقف الاستيراد؛ ما دخل بالفعل يبقى على رفّك.",
    "finalizando": "جارٍ الإنهاء…",
    "nao_foi_possivel_ler_o_arquivo_2": "تعذّر قراءة الملف",
    "importando_livros": "جارٍ استيراد الكتب",
    "livros_quadrinhos_documentos_audiolivr": "كتب وقصص مصورة ومستندات وكتب صوتية وفيديو",
    "series": "سلاسل",
    "colecoes": "مجموعات",
    "organizacao_salva": "تم حفظ التنظيم.",
    "informe_um_nome_para_o_livro_antes_de": "أعطِ الكتاب اسمًا قبل الحفظ.",
    "nome_do_livro_obrigatorio": "اسم الكتاب مطلوب",
    "importe_um_livro_primeiro": "استورد كتابًا أولًا.",
    "citacao": "اقتباس",
    "anotacao": "ملاحظة",
    "citacao_2": "اقتباس",
    "anotacao_2": "ملاحظة",
    "uma_citacao": "اقتباس",
    "uma_anotacao": "ملاحظة",
    "o_marcador_sera_removido_da_biblioteca": "ستُزال الإشارة من المكتبة، لكن ملف الكتاب يبقى سليمًا.",
    "marcador_de_audio": "إشارة صوتية",
    "marcador_de_video": "إشارة فيديو",
    "nao_foi_possivel_excluir_o_livro": "تعذّر حذف الكتاب.",
    "livro_excluido_da_biblioteca": "حُذف الكتاب من المكتبة.",
    "excluir_livro": "حذف الكتاب",
    "isso_remove_apenas_a_copia_armazenada": "هذا يحذف فقط النسخة التي تحفظها المكتبة، مع التقدّم والإشارات والملاحظات. الملف الأصلي في مجلدك لن يُحذف.",
    "excluir_livro_2": "حذف الكتاب؟",
    "ordem_personalizada_salva": "تم حفظ الترتيب المخصّص.",
    "ordem_manual_da_sua_estante": "رفّك، بالترتيب الذي وضعته.",
    "agrupamento_alterado_para_minha_ordem": "تم تغيير التجميع إلى \"ترتيبي\".",
    "nova_ordem_salva": "تم حفظ الترتيب الجديد.",
    "nao_foi_possivel_salvar_a_nova_ordem": "تعذّر حفظ الترتيب الجديد.",
    "baixar_automaticamente": "تنزيل تلقائي",
    "escolha_livremente_onde_o_arquivo_sera": "اختر بحرية أين سيُكتب الملف.",
    "salvar_epub": "حفظ EPUB",
    "livro_epub": "كتاب EPUB",
    "erro_desconhecido": "خطأ غير معروف",
    "a_permissao_para_salvar_o_arquivo_foi": "أُلغيت إذن حفظ الملف. لم يتغير شيء في المكتبة.",
    "conversao_cancelada_o_pdf_original_per": "أُلغيت التحويل. يبقى PDF الأصلي في المكتبة.",
    "preparando_salvamento": "جارٍ التحضير للحفظ…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "نسخة PDF غير متوفرة في المكتبة.",
    "reconstruindo_o_livro_localmente": "جارٍ إعادة بناء الكتاب على جهازك.",
    "convertendo_pdf": "جارٍ تحويل PDF",
    "nao_foi_possivel_compartilhar_o_livro": "تعذّرت مشاركة الكتاب.",
    "o_arquivo_foi_preparado_para_voce_comp": "الملف جاهز لتشاركه في تطبيق آخر.",
    "livro_compartilhado": "تمت مشاركة الكتاب.",
    "a_copia_deste_livro_nao_esta_disponive": "نسخة هذا الكتاب غير متوفرة في المكتبة.",
    "para_manter_a_politica_de_compartilham": "للالتزام بسياسة المشاركة في المكتبة، لا يمكن مشاركة ملفات EPUB وMOBI من هذا التطبيق.",
    "quadrinhos_ficam_guardados_somente_no": "القصص المصورة تُحفظ على جهازك فقط ولا يمكن مشاركتها من هذا التطبيق.",
    "audiolivros_e_videos_ficam_guardados_s": "الكتب الصوتية والفيديو تُحفظ على جهازك فقط ولا يمكن مشاركتها من هذا التطبيق.",
    "formato_protegido": "صيغة محمية",
    "compartilhamento_indisponivel": "المشاركة غير متاحة",
    "concluido": "مكتمل",
    "ainda_nao_comecado": "لم يبدأ بعد",
    "continue_lendo": "تابع القراءة",
    "continue_ouvindo": "تابع الاستماع",
    "continue_assistindo": "تابع المشاهدة",
    "comece_por_aqui": "ابدأ من هنا",
    "comece_a_ouvir": "ابدأ الاستماع",
    "comece_a_assistir": "ابدأ المشاهدة",
    "no_total": "الإجمالي",
    "para_ler": "للقراءة",
    "sua_estante": "رفّك",
    "livros_organizados_pela_opcao_selecion": "الكتب مرتبة حسب الخيار الذي اخترته.",
    "uma_prateleira_para_cada_tipo_de_arqui": "رفّ لكل نوع من الملفات.",
    "autores_agrupados_em_ordem_alfabetica": "المؤلفون مجمّعون أبجديًا.",
    "toque_para_continuar_de_onde_parou": "المس لتتابع من حيث توقفت.",
    "para_ler_2": "للقراءة",
    "lendo_agora": "جارٍ القراءة الآن",
    "audio_e_video": "صوت وفيديو",
    "trechos_salvos_separadamente_dos_marca": "مقاطع محفوظة منفصلة عن الإشارات.",
    "comentarios_vinculados_a_trechos_selec": "تعليقات مرتبطة بمقاطع اخترتها.",
    "paginas_salvas_para_voltar_rapidamente": "صفحات محفوظة للعودة سريعًا.",
    "do_maior_para_o_menor_progresso_de_lei": "من أكبر تقدّم قراءة إلى أقلّه.",
    "livros_adicionados_ou_lidos_mais_recen": "كتب أُضيفت أو قُرئت حديثًا.",
    "ordem_alfabetica_pelo_titulo": "أبجديًا حسب العنوان.",
    "separa_em_prateleiras_de_epub_pdf_docx": "يفصل في رفوف EPUB وPDF وDOCX والكتب الصوتية والفيديو…",
    "tipo_de_arquivo": "نوع الملف",
    "organiza_e_separa_os_livros_por_autor": "ينظّم الكتب ويفصلها حسب المؤلف.",
    "agrupar_por_autor": "تجميع حسب المؤلف",
    "pressione_o_livro_e_mova_o": "اضغط الكتاب مطوّلًا وحرّكه.",
    "minha_ordem": "ترتيبي",
    "epub_pronto": "EPUB جاهز",
    "conversao_concluida": "اكتمل التحويل",
    "necessario_para_salvar_o_epub_ao_lado": "مطلوب لحفظ EPUB بجانب الأصل",
    "escolha_a_pasta_do_pdf": "اختر مجلد PDF",
    "processando": "جارٍ المعالجة…",
    "processamento_local_no_navegador": "المعالجة على جهازك، في المتصفح",
    "convertendo_livro": "جارٍ تحويل الكتاب",
    "livro_em_pdf": "كتاب PDF",
    "recalculando_paginas": "جارٍ إعادة حساب الصفحات...",
    "ajustando_leitura": "جارٍ ضبط التخطيط",
    "abrir_comentario": "افتح التعليق",
    "anotacao_salva": "تم حفظ الملاحظة.",
    "anotacao_atualizada": "تم تحديث الملاحظة.",
    "escreva_uma_nota_antes_de_salvar": "اكتب ملاحظة قبل الحفظ.",
    "nao_foi_possivel_compartilhar": "تعذّرت المشاركة.",
    "compartilhamento_indisponivel_2": "المشاركة غير متاحة.",
    "trecho_copiado": "تم نسخ المقطع.",
    "trecho_compartilhado": "تمت مشاركة المقطع.",
    "citacao_salva": "تم حفظ الاقتباس.",
    "trecho_grifado": "تم تظليل المقطع.",
    "grifo_removido": "أُزيل التظليل.",
    "comentario_apagado": "حُذف التعليق.",
    "remover_grifo": "أزل التظليل",
    "apagar_comentario": "احذف التعليق",
    "remover_grifo_2": "إزالة التظليل؟",
    "apagar_comentario_2": "حذف التعليق؟",
    "remover_este_grifo": "إزالة هذا التظليل؟",
    "apagar_este_comentario": "حذف هذا التعليق؟",
    "sem_comentario": "بلا تعليق",
    "comentario": "تعليق",
    "marcador_removido_desta_pagina": "أُزيلت الإشارة من هذه الصفحة.",
    "pagina_adicionada_aos_marcadores": "أُضيفت الصفحة إلى إشاراتك.",
    "este_e_o_inicio_do_livro": "هذه بداية الكتاب.",
    "esta_e_a_primeira_pagina": "هذه الصفحة الأولى.",
    "voce_chegou_ao_fim_do_livro": "وصلت إلى نهاية الكتاب.",
    "voce_chegou_ao_fim_do_quadrinho": "وصلت إلى نهاية القصة المصورة.",
    "agora_em_revista_aberta_duas_paginas_l": "الآن بصفحتين متجاورتين: صفحتان جنبًا إلى جنب، والغلاف منفرد.",
    "leitura_horizontal_ativada_neste_livro": "القراءة الأفقية مفعّلة لهذا الكتاب.",
    "rolagem_vertical_ativada_neste_livro": "التمرير العمودي مفعّل لهذا الكتاب.",
    "leitura_pagina_a_pagina_ativada_neste": "قراءة صفحة بصفحة مفعّلة لهذه القصة.",
    "rolagem_continua_ativada_neste_quadrin": "التمرير المتواصل مفعّل لهذه القصة.",
    "mudar_para_rolagem_vertical": "التبديل إلى التمرير العمودي",
    "mudar_para_leitura_horizontal": "التبديل إلى القراءة الأفقية",
    "rolagem_continua_estilo_webtoon": "تمرير متواصل (بأسلوب الويبتون)",
    "voltar_para_pagina_a_pagina": "العودة إلى صفحة بصفحة",
    "separando_os_capitulos": "جارٍ فصل الفصول...",
    "lendo_o_livro": "جارٍ قراءة الكتاب",
    "lendo_o_markdown": "جارٍ قراءة Markdown",
    "lendo_o_documento": "جارٍ قراءة المستند",
    "pagina_indisponivel": "الصفحة غير متوفرة.",
    "isto_acontece_so_desta_vez": "يحدث هذا مرة واحدة فقط.",
    "preparando_o_quadrinho": "جارٍ تحضير القصة المصورة",
    "abrindo_o_quadrinho": "جارٍ فتح القصة المصورة...",
    "montando_as_paginas": "جارٍ بناء الصفحات...",
    "nao_foi_possivel_abrir_este_livro": "تعذّر فتح هذا الكتاب.",
    "abertura_cancelada": "أُلغي الفتح.",
    "o_livro_demorou_demais_para_abrir_e_fo": "استغرق الكتاب وقتًا طويلًا للفتح فتم إيقافه.",
    "importe_o_arquivo_novamente_para_conti": "استورد الملف مجددًا لمتابعة القراءة.",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "لم يعد ملف هذا الكتاب محفوظًا على جهازك.",
    "preparando_sua_leitura": "جارٍ تحضير كتابك...",
    "abrindo_livro": "جارٍ فتح الكتاب",
    "leitura_concluida": "اكتملت القراءة.",
    "a_voz_foi_interrompida_pelo_navegador": "قاطع المتصفح الصوت.",
    "nao_foi_possivel_preparar_este_trecho": "تعذّر تحضير هذا المقطع للصوت.",
    "a_leitura_em_voz_alta_nao_e_suportada": "القراءة بصوت عالٍ غير مدعومة في هذا المتصفح.",
    "pausar_leitura": "أوقف القراءة",
    "em_pausa": "موقوف",
    "leitura_em_voz_alta_nao_disponivel_nes": "القراءة بصوت عالٍ غير متاحة في هذا المتصفح",
    "nome_do_marcador": "اسم الإشارة",
    "o_marcador_sera_removido_deste_audioli": "ستُزال الإشارة من هذا الكتاب الصوتي.",
    "nao_foi_possivel_salvar_o_marcador": "تعذّر حفظ الإشارة.",
    "ja_existe_um_marcador_neste_ponto": "توجد إشارة بالفعل في هذا الموضع.",
    "timer_de_sono_encerrado": "انتهى مؤقّت النوم.",
    "fim_do_cap": "نهاية الفصل",
    "timer_desativado": "أُغلق المؤقّت.",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "سيتوقف الصوت في نهاية الفصل.",
    "este_audiolivro_nao_tem_capitulos": "هذا الكتاب الصوتي بلا فصول.",
    "ao_fim_do_capitulo": "في نهاية الفصل",
    "desativar_timer": "أغلق المؤقّت",
    "mais_10_minutos_no_timer": "10 دقائق إضافية على المؤقّت.",
    "somar_10_minutos": "أضف 10 دقائق",
    "pausa_ao_fim_do_capitulo": "توقف في نهاية الفصل",
    "no_livro_todo": "في الكتاب كله",
    "video": "فيديو",
    "audiolivro_concluido": "اكتمل الكتاب الصوتي.",
    "video_concluido": "اكتمل الفيديو.",
    "video_2": "فيديو",
    "audio": "صوت",
    "toque_em_reproduzir_para_comecar": "المس تشغيل للبدء.",
    "falha_ao_carregar_o_audio": "فشل تحميل الصوت.",
    "exclua_o_da_biblioteca_e_importe_o_arq": "احذفه من المكتبة واستورد الملف مجددًا.",
    "os_nomes_dos_arquivos_seguem_uma_seque": "أسماء الملفات متسلسلة، لذا تبدو كفصول لكتاب صوتي واحد.",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "الملفات تحمل الألبوم نفسه في وسومها، لذا تبدو كفصول لكتاب صوتي واحد.",
    "libere_espaco_ou_exclua_livros_da_bibl": "وفّر مساحة أو احذف كتبًا من المكتبة ثم حاول مجددًا.",
    "o_armazenamento_do_aparelho_esta_cheio": "مساحة تخزين جهازك ممتلئة.",
    "preparando_a_capa": "جارٍ تحضير الغلاف...",
    "remova_esse_arquivo_da_selecao_e_tente": "أزل ذلك الملف من الاختيار وحاول مجددًا.",
    "sequencia": "تسلسل",
    "o_arquivo_pode_estar_incompleto_tente": "قد يكون الملف غير مكتمل. حاول تنزيله مجددًا.",
    "conferindo_se_o_audio_pode_ser_reprodu": "جارٍ التحقق إن كان الصوت قابلًا للتشغيل...",
    "conferindo_se_o_video_pode_ser_reprodu": "جارٍ التحقق إن كان الفيديو قابلًا للتشغيل...",
    "lendo_titulo_capitulos_e_capa": "جارٍ قراءة العنوان والفصول والغلاف...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "قد يكون الملف تالفًا أو بصيغة صوتية لا يستطيع المتصفح تشغيلها. جرّب تحويله إلى MP3 أو M4B (AAC).",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "قد يكون الملف تالفًا أو بصيغة فيديو لا يستطيع المتصفح تشغيلها. جرّب تحويله إلى MP4 بفيديو H.264 وصوت AAC.",
    "converta_o_audiolivro_para_m4b_com_aud": "حوّل الكتاب الصوتي إلى M4B بصوت AAC (أو إلى MP3) واستورده مجددًا.",
    "converta_o_video_para_mp4_com_audio_aa": "حوّل الفيديو إلى MP4 بصوت AAC وفيديو H.264 واستورده مجددًا.",
    "o_navegador_nao_reproduz_o_formato_de": "المتصفح لا يشغّل صيغة الصوت لهذا الملف.",
    "arquivos_com_protecao_nao_podem_ser_re": "الملفات المحمية لا يمكن تشغيلها هنا. استخدم نسخة بلا DRM.",
    "nao_ha_espaco_suficiente_no_aparelho_p": "لا توجد مساحة كافية على جهازك لهذا الكتاب الصوتي.",
    "confira_se_a_extensao_corresponde_ao_c_2": "تحقق من أن الامتداد يطابق المحتوى، أو حوّل الصوت إلى MP3 أو M4B (AAC).",
    "imagem_invalida": "صورة غير صالحة",
    "imagem_demorou_demais": "استغرق تحميل الصورة وقتًا طويلًا جدًا",
    "imagem_vazia": "صورة فارغة",
    "inicio": "البداية",
    "mp4_moov_nao_encontrado": "يبدو أن الفيديو ناقص أو تالف.",
    "pagina": "صفحة",
    "esta_pagina_nao_esta_disponivel": "هذه الصفحة غير متاحة.",
    "esta_pagina_nao_pode_ser_descompactada": "تعذّر فك ضغط هذه الصفحة.",
    "quadrinho_fechado": "أُغلقت القصة المصورة.",
    "ele_pode_estar_incompleto_dividido_em": "قد يكون غير مكتمل، أو مقسّمًا إلى عدة أجزاء، أو بصيغة RAR لا يعرفها التطبيق. تحويله إلى CBZ يصلحه عادةً.",
    "remova_a_senha_do_arquivo_e_importe_de": "أزل كلمة المرور من الملف واستورده مجددًا.",
    "nao_foi_possivel_ler_este_arquivo_de_q": "تعذّر قراءة ملف القصة المصورة هذا.",
    "este_quadrinho_esta_protegido_por_senh": "هذه القصة المصورة محمية بكلمة مرور.",
    "lendo_o_indice_do_quadrinho": "جارٍ قراءة فهرس القصة المصورة...",
    "o_arquivo_pode_ser_grande_demais_para": "قد يكون الملف كبيرًا جدًا على ذاكرة هذا الجهاز. تقسيم القصة إلى أجزاء أصغر يصلحه عادةً.",
    "nao_foi_possivel_abrir_este_quadrinho": "تعذّر فتح هذه القصة المصورة.",
    "lendo_o_arquivo": "جارٍ قراءة الملف...",
    "preparando_o_leitor_de_cbr": "جارٍ تحضير قارئ CBR...",
    "o_arquivo_pode_estar_incompleto_proteg": "قد يكون الملف غير مكتمل أو محميًا بكلمة مرور أو تالفًا.",
    "nao_foi_possivel_ler_este_quadrinho": "تعذّر قراءة هذه القصة المصورة.",
    "o_arquivo_precisa_conter_imagens_jpg_p": "يجب أن يحتوي الملف على صور (JPG أو PNG أو WEBP أو GIF).",
    "nao_encontramos_paginas_dentro_deste_q": "لم نجد صفحات داخل هذه القصة المصورة.",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "لا توجد مساحة كافية على جهازك لهذه القصة المصورة.",
    "cabecalho_de_item_invalido": "جزء من الملف تالف.",
    "a_pasta_vendor_libarchive_precisa_esta": "ينقص التطبيقَ مكوّنٌ لازم لفتح هذه القصة المصورة. حوّلها إلى CBZ أو أعد تثبيت التطبيق.",
    "o_leitor_de_cbr_nao_foi_encontrado": "لم يُعثر على قارئ CBR.",
    "converta_o_quadrinho_para_cbz_zip_e_im": "حوّل القصة المصورة إلى CBZ (ZIP) واستوردها مجددًا.",
    "este_navegador_nao_consegue_abrir_arqu": "هذا المتصفح لا يفتح ملفات CBR.",
    "convertendo_o_markdown": "جارٍ تحويل Markdown",
    "lendo_o_texto": "جارٍ قراءة النص",
    "pdf_indisponivel": "PDF غير متوفر.",
    "epub_invalido_nenhum_capitulo_no_spine": "ملف EPUB هذا تالف: لم نعثر على فصول الكتاب.",
    "livro_sem_titulo": "كتاب بلا عنوان",
    "epub_invalido_arquivo_opf_nao_encontra": "ملف EPUB هذا ناقص أو تالف ولا يمكن فتحه.",
    "epub_invalido_container_xml_nao_encont": "ملف EPUB هذا ناقص أو تالف ولا يمكن فتحه.",
    "organizando_o_texto": "جارٍ تنسيق النص",
    "descompactando_o_livro": "جارٍ فك ضغط الكتاب",
    "nao_encontramos_conteudo_para_exibir_n": "لم نجد محتوى لعرضه في هذا الملف.",
    "livro_sem_texto_legivel": "كتاب بلا نص قابل للقراءة",
    "o_arquivo_pode_estar_corrompido_tente": "قد يكون الملف تالفًا. جرّب تحويله إلى EPUB.",
    "nao_foi_possivel_extrair_o_texto_deste": "تعذّر استخراج النص من هذا MOBI.",
    "nenhum_registro_de_conteudo_foi_encont": "لم نعثر على نص الكتاب في هذا الملف.",
    "arquivo_mobi_sem_texto": "ملف MOBI بلا نص.",
    "o_dicionario_de_compressao_esta_vazio": "جزء من محتوى ملف MOBI هذا مفقود.",
    "arquivo_mobi_incompleto": "ملف MOBI غير مكتمل.",
    "as_tabelas_de_compressao_nao_foram_enc": "جزء من محتوى ملف MOBI هذا مفقود.",
    "converta_o_arquivo_para_epub_em_um_pro": "حوّل الملف إلى EPUB في برنامج مثل Calibre واستورده مجددًا.",
    "compressao_mobi_nao_reconhecida": "يستخدم ملف MOBI هذا صيغة داخلية لا يتعرّف عليها التطبيق.",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "تعذّرت قراءة ترويسة الكتاب.",
    "arquivo_mobi_corrompido": "ملف MOBI تالف.",
    "a_lista_interna_de_registros_esta_inco": "الملف ناقص. جرّب تنزيله أو تحويله من جديد.",
    "o_download_parece_ter_sido_interrompid": "يبدو أن التنزيل قُوطِع. نزّل الملف مجددًا.",
    "tabela_de_compressao_mobi_corrompida": "جزء من ملف MOBI هذا تالف.",
    "tabela_de_compressao_mobi_incompleta": "ملف MOBI هذا ناقص.",
    "tabela_de_compressao_mobi_invalida": "جزء من ملف MOBI هذا تالف.",
    "este_arquivo_docx_nao_tem_conteudo_de": "هذا الملف .docx لا يحتوي نصًا يمكن عرضه.",
    "documento_sem_texto": "مستند بلا نص",
    "o_arquivo_pode_estar_corrompido_proteg": "قد يكون الملف تالفًا أو محميًا بكلمة مرور أو .doc قديمًا. احفظه مجددًا بصيغة .docx واستورده مرة أخرى.",
    "nao_foi_possivel_ler_este_arquivo_docx": "تعذّر قراءة ملف DOCX هذا.",
    "convertendo_o_documento": "جارٍ تحويل المستند",
    "conecte_se_a_internet_uma_vez_para_bai": "اتصل بالإنترنت مرة واحدة لتنزيل المكوّن، ثم افتح الكتاب مجددًا.",
    "o_conversor_de_docx_nao_carregou": "لم يُحمَّل محوّل DOCX.",
    "video_mp4": "فيديو (MP4)",
    "audiolivro_m4b": "كتاب صوتي (M4B)",
    "audiolivro_mp3": "كتاب صوتي (MP3)",
    "quadrinho_cbt": "قصة مصورة (CBT)",
    "quadrinho_cb7": "قصة مصورة (CB7)",
    "quadrinho_cbr": "قصة مصورة (CBR)",
    "quadrinho_cbz": "قصة مصورة (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "نص (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "أُلغي الحفظ.",
    "o_arquivo_esta_vindo_do_armazenamento": "الملف ينزل من التخزين السحابي إلى جهازك.",
    "baixando_o_arquivo": "جارٍ تنزيل الملف",
    "cancelando": "جارٍ الإلغاء...",
    "use_grifar_citacao_anotar_ou_marcador": "استخدم التظليل أو الاقتباس أو الملاحظة أو الإشارة أثناء القراءة.",
    "nenhuma_marcacao_ainda": "لا علامات بعد",
    "trecho_original": "المقطع الأصلي",
    "procurar_meus_livros": "ابحث عن كتبي",
    "a_busca_fica_sempre_disponivel_no_menu": "البحث موجود دائمًا في القائمة الجانبية، تحت النظام.",
    "da_para_fazer_depois": "يمكن فعله لاحقًا",
    "nada_entra_na_estante_sem_a_sua_confir": "لا شيء يدخل الرف بدون تأكيدك: ترى القائمة وتختار ما تريد استيراده.",
    "voce_revisa_antes": "أنت تراجع أولًا",
    "escolha_uma_pasta_downloads_e_um_bom_c": "اختر مجلدًا (Downloads بداية جيدة) وسيبحث التطبيق فيه وفي كل المجلدات الفرعية.",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "يبحث عن EPUB وMOBI وCBZ وCBR وM4B",
    "voltar_e_revisar": "ارجع وراجع",
    "ler_os_termos": "اقرأ الشروط",
    "ler_a_politica": "اقرأ السياسة",
    "os_dois_documentos_ficam_sempre_dispon": "المستندان موجودان دائمًا في القائمة الجانبية، تحت حول.",
    "leia_com_calma": "اقرأ على راحتك",
    "a_politica_e_os_termos_explicam_como_o": "السياسة والشروط تشرحان كيف يحفظ التطبيق كتبك وما يمكنك فعله بها. لاستخدام المكتبة، يلزم الموافقة عليهما.",
    "nada_acontece_sem_o_aceite": "للبدء، يُرجى الموافقة على الشروط",
    "aceitar_e_continuar": "أوافق وتابع",
    "nao_aceito": "لا أوافق",
    "termos_de_uso_2": "شروط الاستخدام",
    "politica_de_privacidade_2": "سياسة الخصوصية",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "التطبيق يصل فقط إلى الملفات والمجلدات التي تختارها، عندما تختارها.",
    "voce_no_controle": "أنت المتحكم",
    "depois_de_importar_um_livro_voce_le_se": "بعد استيراد كتاب، تقرأه بلا إنترنت.",
    "funciona_offline": "يعمل دون اتصال",
    "livros_marcacoes_e_progresso_sao_guard": "الكتب والعلامات والتقدّم تُحفظ على جهازك. لا شيء يُرسل إلى خوادمنا.",
    "tudo_fica_no_seu_aparelho": "كل شيء يبقى على جهازك",
    "escolha_o_que_deseja_adicionar_a_bibli": "اختر ما تريد إضافته إلى المكتبة. الملفات المطابقة لما هو موجود على رفّك تُتجاوز تلقائيًا.",
    "voce_pode_tentar_outra_pasta_ou_import": "يمكنك تجربة مجلد آخر، أو استيراد الملفات بزر +.",
    "a_leitura_acontece_so_no_seu_dispositi": "تتم القراءة على جهازك فقط.",
    "voce_escolhe_a_pasta": "أنت تختار المجلد",
    "tema_tipografia_margens_modo_de_virada": "السمة والخط والهوامش وطريقة التقليب وإعدادات الصوت.",
    "restaurar_minhas_preferencias": "استعد تفضيلاتي",
    "o_backup_manda_as_marcacoes_atuais_dos": "الأولوية للنسخة الاحتياطية. علامات أي كتاب موجود في الملف ستُستبدل بعلامات النسخة الاحتياطية.",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "لا شيء يُمحى. علامات الجانبين تُضاف معًا والتقدّم الأحدث يفوز.",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "ماذا نفعل بما هو على الرف بالفعل",
    "grifos_citacoes_e_notas": "التظليل والاقتباسات والملاحظات",
    "preparando_o_arquivo_2": "جارٍ تحضير الملف...",
    "os_livros_em_si_nem_as_capas_por_isso": "لا الكتب نفسها ولا أغلفتها مُضمَّنة — ولهذا لا يتجاوز حجم الملف بضعة KB. يحتاج مَن يستلمه إلى ملفات الكتب لكي تعود العلامات إلى مواضعها، أما الأغلفة فتعود تلقائيًا عند استيراد الكتب.",
    "nao_vai_no_arquivo": "لا يدخل في الملف",
    "o_seu_progresso_de_leitura_os_grifos_a": "تقدّم قراءتك وتظليلك واقتباساتك وملاحظاتك وإشاراتك وتنظيم رفّك — الحالة والمفضّلة والمجموعات والسلاسل والوسوم.",
    "vai_no_arquivo": "يدخل في الملف",
    "descartar_o_que_esta_esperando_2": "احذف البيانات التي في الانتظار",
    "esperando_o_arquivo": "في انتظار الملف",
    "avisar_quando_fizer_tempo_sem_backup": "ذكّرني عندما يمر وقت طويل دون نسخ احتياطي",
    "livros_que_ainda_nao_estiverem_na_esta": "الكتب التي ليست على رفّك بعد تبقى في الانتظار: عند استيراد ملفاتها، تعود العلامات تلقائيًا.",
    "restaurar_backup": "استعد النسخة الاحتياطية",
    "salvar_backup": "احفظ النسخة الاحتياطية",
    "ainda_nao_ha_itens": "لا شيء هنا بعد",
    "arraste_um_livro_para_outra_posicao_na": "اسحب كتابًا إلى موضع آخر على الرف لحفظ ترتيب خاص بك. يصبح الترتيب اليدوي مقدّمًا على التجميع حسب المؤلف.",
    "separe_por_virgulas": "افصل بفواصل",
    "ex_estudos_ficcao": "مثل: دراسات، خيال...",
    "pasta_estante": "مجلد / رف",
    "ex_trilogia": "مثل: ثلاثية...",
    "serie": "سلسلة",
    "aparece_em_favoritos": "يظهر في المفضّلة.",
    "nome_do_livro": "اسم الكتاب",
    "nenhum_registro_ainda": "لا سجل بعد",
    "no_leitor_toque_no_icone_de_marcador_p": "في القارئ، المس أيقونة الإشارة لحفظ الصفحة.",
    "nenhum_marcador_ainda": "لا إشارات بعد",
    "a_gravacao_e_independente_da_localizac": "الحفظ مستقل عن مكان PDF ولا يغيّر الملف الأصلي.",
    "o_pdf_original_nao_precisa_estar_nessa": "لا حاجة أن يكون PDF الأصلي في ذلك المجلد",
    "excluir_da_biblioteca": "احذف من المكتبة",
    "adicionar_livro": "أضف كتابًا",
    "adicione_livros_e_acompanhe_o_que_esta": "أضف كتبًا وتابع ما ينتظر، وما يجرى، وإلى أين وصلت.",
    "tudo_pronto_para_a_proxima_leitura": "كل شيء جاهز للقراءة التالية.",
    "sua_biblioteca": "مكتبتك",
    "arraste_um_livro_para_reposiciona_lo_a": "اسحب كتابًا لنقله: يتحوّل الرف إلى \"ترتيبي\" ويحفظ التسلسل.",
    "importe_um_livro_ou_ajuste_seus_filtro": "استورد كتابًا، أو اضبط مرشّحاتك.",
    "nada_por_aqui_ainda": "لا شيء هنا بعد",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "المس + واختر ملفات MP3 أو M4B أو MP4. عدة فصول MP3 يمكن أن تصبح كتابًا صوتيًا واحدًا.",
    "nada_para_ouvir_ou_assistir_ainda": "لا شيء للاستماع أو المشاهدة بعد",
    "o_pdf_original_permanece_intacto_na_pa": "يبقى PDF الأصلي سليمًا في مجلدك.",
    "paginas_como_imagem": "صفحات كصور",
    "paginas_do_pdf": "صفحات PDF",
    "em_navegadores_sem_suporte_a_acesso_di": "في متصفحات لا تدعم الوصول المباشر إلى نظام الملفات، سيُتنزّل EPUB بدلًا من ذلك.",
    "essa_permissao_e_dada_somente_a_esta_a": "هذا الإذن يُمنح لهذا التطبيق وحده ويمنع تعديل الملف الأصلي.",
    "selecione_a_pasta_que_contem_o_pdf": "اختر المجلد الذي يحتوي PDF",
    "preparando": "جارٍ التحضير…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "يجري قراءة الملف وإعادة بنائه. الكتب الكبيرة قد تستغرق بعض الوقت.",
    "revistas_apostilas_complexas_formulari": "المجلات والمناهج المعقّدة والنماذج والمستندات الكثيرة الجداول أو PDF الممسوحة قد تفقد جزءًا من تخطيطها الأصلي.",
    "funcionalidade_indicada_apenas_para_li": "وظيفة موصى بها للكتب فقط",
    "o_epub_e_melhor_para_livros_com_texto": "EPUB أفضل للكتب ذات النص القابل للتحديد، لأنه يسمح بضبط الخط والحجم والهوامش ووضع القراءة.",
    "trecho_selecionado": "المقطع المحدّد",
    "trecho_comentado": "المقطع مع تعليق",
    "aplicando_zoom": "جارٍ التكبير...",
    "nao_foi_possivel_carregar_esta_pagina": "تعذّر تحميل هذه الصفحة.",
    "nomear_marcador": "سمِّ الإشارة",
    "toque_em_marcar_agora_para_guardar_est": "المس \"علّم الآن\" لحفظ هذه النقطة والعودة إليها متى أردت.",
    "timer_ativo": "المؤقّت مفعّل",
    "trecho_ausente_ou_corrompido_no_arquiv": "[المقطع مفقود أو تالف في الملف الأصلي]",
    "novos_livros_vao_abrir_em_leitura_v": "الكتب الجديدة ستُفتح بقراءة {v}.",
    "leitura_efetivo_aplicada_a_este_livro": "طُبّقت قراءة {efetivo} على هذا الكتاب.",
    "automatico_neste_livro_leitura_efetivo": "تلقائي في هذا الكتاب: قراءة {efetivo}.",
    "agora_esta_em_efetivo_no_automatico_fo": "الآن على {efetivo}؛ في التلقائي، {format} يُفتح بـ {padrao}.",
    "esta_escolha_vale_so_para_v_cada_livro": "هذا الاختيار يخص \"{v}\" وحده. كل كتاب يحفظ اتجاه تمريره.",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} ليست على رفّك بعد.",
    "escolha_uma_pasta_para_procurar_label": "اختر مجلدًا للبحث عن {label}.",
    "subtitle_versao_build": "{subtitle} · إصدار {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "تعذّرت قراءة {path}؛ يُستخدم النص المدمج.",
    "seu_ultimo_backup_foi_ha_dias_dias": "آخر نسخة احتياطية لك كانت قبل {dias} يومًا",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "{aguardando} كتاب من النسخة الاحتياطية ليس هنا بعد. حُفظ تقدّمه وعلاماته: بمجرد استيراد الملف، سيعود كل شيء إلى مكانه تلقائيًا.",
      "other": "{aguardando} كتاب من النسخة الاحتياطية ليست هنا بعد. حُفظ تقدّمها وعلاماتها: بمجرد استيراد كل ملف، سيعود كل شيء إلى مكانه تلقائيًا.",
      "two": "كتابان من النسخة الاحتياطية ليسا هنا بعد. حُفظ تقدّمهما وعلاماتهما: بمجرد استيراد كل ملف، سيعود كل شيء إلى مكانه تلقائيًا.",
      "few": "{aguardando} كتب من النسخة الاحتياطية ليست هنا بعد. حُفظ تقدّمها وعلاماتها: بمجرد استيراد كل ملف، سيعود كل شيء إلى مكانه تلقائيًا.",
      "many": "{aguardando} كتابًا من النسخة الاحتياطية ليست هنا بعد. حُفظ تقدّمها وعلاماتها: بمجرد استيراد كل ملف، سيعود كل شيء إلى مكانه تلقائيًا.",
      "zero": "{aguardando} كتب من النسخة الاحتياطية ليست هنا بعد. حُفظ تقدّمها وعلاماتها: بمجرد استيراد كل ملف، سيعود كل شيء إلى مكانه تلقائيًا."
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "تم تحديث {atualizados} كتاب على رفّك.",
      "other": "تم تحديث {atualizados} كتاب على رفّك.",
      "two": "تم تحديث كتابين على رفّك.",
      "few": "تم تحديث {atualizados} كتب على رفّك.",
      "many": "تم تحديث {atualizados} كتابًا على رفّك.",
      "zero": "تم تحديث {atualizados} كتب على رفّك."
    },
    "criado_em_quando": "أُنشئ في {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "النسخة الاحتياطية جاهزة: {livros} كتاب و{marcacoes} علامة.",
    "endereco_seguro_seguro": "عنوان آمن: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "استُعيد التقدّم و{marcas} علامة لهذا الكتاب.",
      "other": "استُعيد التقدّم و{marcas} علامة لهذا الكتاب.",
      "zero": "استُعيد التقدّم لهذا الكتاب.",
      "two": "استُعيد التقدّم وعلامتان لهذا الكتاب.",
      "few": "استُعيد التقدّم و{marcas} علامات لهذا الكتاب.",
      "many": "استُعيد التقدّم و{marcas} علامةً لهذا الكتاب."
    },
    "restaurando_v_de_length": "جارٍ الاستعادة ({v} من {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} كتاب · {marcacoes} علامة",
    "criado_em_v": "أُنشئ في {v}",
    "reunindo_a_sua_estante_v_de_length": "جارٍ جمع رفّك ({v} من {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "\"{titulo}\" استُورد سابقًا ولا يزال في مكتبتك. لم تُنشأ نسخة جديدة.",
    "length_arquivos_de_audio": "{length} ملف صوتي...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "تعذّرت قراءة {falhas} ملف.",
      "other": "تعذّرت قراءة {falhas} ملف.",
      "two": "تعذّرت قراءة ملفين.",
      "few": "تعذّرت قراءة {falhas} ملفات.",
      "many": "تعذّرت قراءة {falhas} ملفًا.",
      "zero": "تعذّرت قراءة {falhas} ملفات."
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} كانت في المكتبة سابقًا وتُجوهلت.",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "أُضيف {importados} كتاب إلى رفّك.",
      "other": "أُضيف {importados} كتاب إلى رفّك.",
      "two": "أُضيف كتابان إلى رفّك.",
      "few": "أُضيفت {importados} كتب إلى رفّك.",
      "many": "أُضيف {importados} كتابًا إلى رفّك.",
      "zero": "أُضيفت {importados} كتب إلى رفّك."
    },
    "epub_salvo_em_filename": "EPUB محفوظ في {fileName}.",
    "falha_ao_converter_o_pdf_v": "فشل تحويل PDF: {v}",
    "pagina_page_de_totalpages": "صفحة {page} من {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} صفحة",
      "other": "{totalPages} صفحة",
      "two": "صفحتان",
      "few": "{totalPages} صفحات",
      "many": "{totalPages} صفحةً",
      "zero": "{totalPages} صفحات"
    },
    "length_resultado_s_para_search": {
      "one": "نتيجة واحدة لـ \"{search}\"",
      "other": "{length} نتيجة لـ \"{search}\"",
      "zero": "لا نتائج لـ \"{search}\"",
      "two": "نتيجتان لـ \"{search}\"",
      "few": "{length} نتائج لـ \"{search}\"",
      "many": "{length} نتيجةً لـ \"{search}\""
    },
    "capitulo_v": "الفصل {v}",
    "organizando_capitulo_v_de_totalchapter": "جارٍ تنسيق الفصل {v} من {totalChapters}",
    "pagina_v": "الصفحة {v}",
    "paginas_v_v2": "الصفحات {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} صفحة جاهزة",
      "other": "{length} صفحة جاهزة",
      "two": "صفحتان جاهزتان",
      "few": "{length} صفحات جاهزة",
      "many": "{length} صفحةً جاهزة",
      "zero": "{length} صفحات جاهزة"
    },
    "montando_as_paginas_pagessofar_prontas": "جارٍ بناء الصفحات — {pagesSoFar} جاهزة",
    "lendo_pagina_v_de_length": "جارٍ قراءة الصفحة {v} من {length}",
    "marcador_salvo_em_t": "حُفظت الإشارة عند {t}.",
    "o_audio_vai_pausar_em_minutes_minutos": "سيتوقف الصوت بعد {minutes} دقيقة.",
    "length_capitulos_toque_para_ir_direto": "{length} فصول · المس للذهاب مباشرةً إلى هناك.",
    "narrado_por_narrator": "بصوت {narrator}",
    "velocidade_de_reproducao_rate": "سرعة التشغيل: {rate}",
    "avancar_f_segundos": "تقدّم {f} ثانية",
    "nao_foi_possivel_abrir_este_v": "تعذّر فتح هذا {v}.",
    "nao_foi_possivel_ler_o_arquivo_de_v": "تعذّرت قراءة ملف {v}.",
    "o_v_esta_danificado_neste_ponto": "{v} تالف في هذه النقطة.",
    "o_navegador_nao_consegue_reproduzir_es": "المتصفح لا يستطيع تشغيل ملف {v} هذا.",
    "nao_foi_possivel_reproduzir_este_v": "تعذّر تشغيل هذا {v}.",
    "os_dados_deste_noun_estao_incompletos": "بيانات هذا {noun} غير مكتملة.",
    "importe_o_arquivo_novamente_para_conti_2": "استورد الملف مجددًا لمتابعة {v}.",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "لم يعد ملف هذا {noun} محفوظًا على جهازك.",
    "nao_foi_possivel_descobrir_a_duracao_d": "تعذّر معرفة مدة \"{name}\".",
    "lendo_faixa_v_de_length": "جارٍ قراءة المسار {v} من {length}...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "تعذّر معرفة مدة هذا {v}.",
    "este_format_nao_pode_ser_reproduzido_n": "لا يمكن تشغيل {format} هذا في هذا المتصفح.",
    "este_format_esta_protegido_por_drm": "{format} هذا محمي بـ DRM.",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "الملف بحجم {bytes} ويتبقى نحو {v}. وفّر مساحة أو احذف كتبًا من المكتبة.",
    "este_arquivo_nao_e_um_format_valido": "هذا الملف ليس {format} صالحًا.",
    "preparando_as_paginas_vistas_de_total": "جارٍ تحضير الصفحات ({vistas} من {total})...",
    "preparando_total_pagina_s": {
      "one": "جارٍ تحضير {total} صفحة...",
      "other": "جارٍ تحضير {total} صفحة...",
      "two": "جارٍ تحضير صفحتين...",
      "few": "جارٍ تحضير {total} صفحات...",
      "many": "جارٍ تحضير {total} صفحةً...",
      "zero": "جارٍ تحضير {total} صفحات..."
    },
    "preparando_as_paginas_v_de_total": "جارٍ تحضير الصفحات ({v} من {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "يشغل نحو {bytes} ويتبقى حوالي {v}. وفّر مساحة أو احذف كتبًا من المكتبة.",
    "envio_direto_exige_endereco_seguro": "الإرسال المباشر إلى تطبيق آخر غير متاح لأن هذه الصفحة لم تُفتح من عنوان آمن. احفظ الملف وأرسله عبر التطبيق الذي تفضّله.",
    "na_estante": "على الرف",
    "nao_foi_possivel_montar_o_arquivo": "تعذّر إنشاء الملف.",
    "este_navegador_nao_oferece_o_envio_dir": "هذا المتصفح لا يوفّر الإرسال المباشر إلى تطبيق آخر. احفظ الملف وأرفقه بالتطبيق الذي تفضّله.",
    "voce_ainda_nao_fez_nenhum_backup": "لم تُنشئ أي نسخة احتياطية بعد.",
    "converter_para_epub": "حوّل إلى EPUB",
    "esta_pagina_nao_pode_ser_exibida": "تعذّر عرض هذه الصفحة.",
    "na_ordem_em_que_serao_tocados": "بالترتيب الذي ستُشغّل به",
    "este_capitulo_nao_pode_ser_exibido": "تعذّر عرض هذا الفصل.",
    "livro": "كتاب",
    "restantes": " متبقٍ",
    "como_seus_dados_sao_tratados": "كيف تُعالج بياناتك",
    "condicoes_de_uso_do_aplicativo": "شروط استخدام التطبيق",
    "audiolivro": "كتاب صوتي",
    "sobre_o_aplicativo": "حول التطبيق",
    "o_que_e_o_veredas_reader": "ما هو Veredas Reader",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(هذا الجهاز لا يدعم مشاركة هذا النوع من الملفات)",
    "livros": "كتب",
    "lendo": "قيد القراءة",
    "lidos": "مقروء",
    "compartilhar_livro": "شارك الكتاب",
    "n_livros": {
      "one": "{n} كتاب",
      "other": "{n} كتاب",
      "two": "كتابان",
      "few": "{n} كتب",
      "many": "{n} كتابًا",
      "zero": "{n} كتب"
    },
    "livros_unidade": {
      "one": "كتاب",
      "other": "كتاب",
      "zero": "كتاب",
      "two": "كتاب",
      "few": "كتب",
      "many": "كتابًا"
    },
    "uma_faixa_discreta_depois_de_n_dias": "شريط هادئ على الرف بعد {n} يومًا بدون نسخة احتياطية. لا يقطع قراءتك أبدًا.",
    "scanned_arquivos_verificados_livros_enc": "{scanned} ملفًا تم فحصه · {encontrados} كتابًا تم إيجاده",
    "v_de_total": "{v} من {total}",
    "voltar_n_segundos": "ارجع {n} ثانية",
    "cancelado": "أُلغي",
    "arquivo": "ملف",
    "outro": "آخر",
    "outros": "أخرى",
    "audiolivro_2": "كتاب صوتي",
    "pausar": "إيقاف مؤقت",
    "marcador": "إشارة",
    "leitura": "قراءة",
    "grifo": "تظليل",
    "editar": "تعديل",
    "apagar": "حذف",
    "concluir": "إنهاء",
    "recentes": "الأحدث",
    "progresso": "تقدّم",
    "entendi": "فهمت",
    "aviso": "تنبيه",
    "descartar": "حذف",
    "copiado": "منسوخ",
    "restaurar": "استعادة",
    "restaurando": "جارٍ الاستعادة",
    "excluir": "حذف",
    "grifos": "تظليل",
    "arquivo_vazio": "ملف فارغ.",
    "e_mais_n_arquivos": {
      "one": "وملف آخر، بالترتيب الذي ستُشغّل به",
      "other": "و{n} ملف آخر، بالترتيب الذي ستُشغّل به",
      "two": "وملفان آخران، بالترتيب الذي ستُشغّل به",
      "few": "و{n} ملفات أخرى، بالترتيب الذي ستُشغّل به",
      "many": "و{n} ملفًا آخر، بالترتيب الذي ستُشغّل به"
    },
    "n_arquivos_mp3": {
      "one": "ملف MP3 واحد",
      "other": "{n} ملف MP3",
      "two": "ملفا MP3",
      "few": "{n} ملفات MP3",
      "many": "{n} ملفًا MP3"
    },
    "pct_restam": "{pct}% · متبقٍ {tempo}",
    "n_minutos": {
      "one": "دقيقة واحدة",
      "other": "{n} دقيقة",
      "two": "دقيقتان",
      "few": "{n} دقائق",
      "many": "{n} دقيقة"
    },
    "ir_para_tempo": "انتقل إلى {tempo}",
    "nomear": "تسمية",
    "parte_n": "الجزء {n}",
    "carregando_pagina_n": "جارٍ تحميل الصفحة {n}...",
    "selecionar_pasta_e_continuar": "اختر المجلد وتابع",
    "ler_agora": "اقرأ الآن",
    "agrupamento_v": "التجميع: {v}.",
    "tempo_restante": "متبقٍ {tempo}",
    "abrir_titulo": "افتح {titulo}",
    "continuar_lendo_titulo": "تابع قراءة {titulo}",
    "continuar_ouvindo_titulo": "تابع الاستماع إلى {titulo}",
    "continuar_assistindo_titulo": "تابع مشاهدة {titulo}",
    "lido": "مقروء",
    "pausado": "متوقف مؤقتًا",
    "status": "الحالة",
    "favorito": "مفضّل",
    "escolher_local": "اختر الموقع",
    "epub_baixado_como": "نُزّل ملف EPUB باسم {nome}.",
    "ouvir_a_partir_de": "استمع من {tempo}",
    "assistir_a_partir_de": "شاهد من {tempo}",
    "pagina_n_minuscula": "الصفحة {n}",
    "selecione_trecho_para_criar": "حدّد مقطعًا أثناء القراءة لإنشاء {oque}.",
    "excluir_oque_pergunta": "حذف {oque}؟",
    "excluir_oque": "حذف {oque}",
    "excluir_item_pergunta": "حذف هذا العنصر؟",
    "use_organizar_para_criar": "استخدم «{botao}» في أي كتاب لإنشاء {oque}.",
    "n_arquivos_processados": {
      "one": "عولج ملف واحد",
      "other": "عولج {n} ملف",
      "two": "عولج ملفان",
      "few": "عولجت {n} ملفات",
      "many": "عولج {n} ملفًا"
    },
    "voce_ja_tem_titulo_de_autor": "لديك بالفعل «{titulo}» لـ {autor} في المكتبة، مع أن الملف مختلف. هل تريد استيراده على أي حال؟",
    "voce_ja_tem_titulo": "لديك بالفعل «{titulo}» في المكتبة، مع أن الملف مختلف. هل تريد استيراده على أي حال؟",
    "marcadores_unidade": {
      "one": "إشارة",
      "other": "إشارة",
      "zero": "إشارات",
      "two": "إشارتان",
      "few": "إشارات",
      "many": "إشارة"
    },
    "ultimo_backup_em": "آخر نسخة احتياطية في <strong>{data}</strong>.",
    "guardar": "الحفظ",
    "lembretes": "التذكيرات",
    "juntar": "دمج",
    "recomendado": "موصى به",
    "substituir": "استبدال",
    "n_capas_recuperadas": {
      "one": "استُعيد غلاف واحد.",
      "other": "استُعيد {n} غلاف.",
      "two": "استُعيد غلافان.",
      "few": "استُعيدت {n} أغلفة.",
      "many": "استُعيد {n} غلافًا."
    },
    "nao_encontramos_arquivos_tipo": "لم نعثر على ملفات {tipo} في هذا المجلد.",
    "tentar_outra_pasta": "جرّب مجلدًا آخر",
    "n_livros_encontrados": {
      "one": "عُثر على كتاب واحد",
      "other": "عُثر على {n} كتاب",
      "two": "عُثر على كتابين",
      "few": "عُثر على {n} كتب",
      "many": "عُثر على {n} كتابًا"
    },
    "n_de_total_selecionados": {
      "one": "تم تحديد {n} من {total}",
      "other": "تم تحديد {n} من {total}"
    },
    "importar": "استيراد",
    "importar_n": "استيراد {n}",
    "aceite_frase": "قرأت {politica} و{termos} الخاصة بـ Veredas Reader وأوافق عليها.",
    "pdf_preservado": "ملف PDF الأصلي <strong>لن يُحذف من مجلدك</strong>. لن تُزال من المكتبة إلا نسخة ملف PDF هذا، وذلك بعد حفظ ملف EPUB بنجاح.",
    "gravar_epub_mesma_pasta": "لحفظ ملف EPUB <strong>في المجلد نفسه الذي فيه ملف PDF</strong>، يحتاج المتصفح إذنًا للوصول إلى ذلك المجلد.",
    "epub_pronto_qualquer_pasta": "تم تحويل EPUB. يمكنك الآن اختيار <strong>أي مجلد على الحاسوب</strong> لحفظ الملف.",
    "backup_explicacao": "النسخة الاحتياطية الأصلية ملف ZIP أو TXT. عند استلامها على جهاز آخر، استوردها عبر <strong>استعد النسخة الاحتياطية</strong>، وسيتعرّف Veredas على المحتوى ويستعيده كالمعتاد. يحفظ الملف تقدّمك وتظليلاتك واقتباساتك وملاحظاتك وإشاراتك وتنظيم رفّك — <strong>لا الكتب نفسها</strong>، ولا الأغلفة.",
    "lembretes_desligados_frase": "التذكيرات <strong>مغلقة</strong>. تذكّر إنشاء نسخة احتياطية من حين لآخر.",
    "backup_salvo_nos_downloads": "<strong>حُفظ ملف النسخ الاحتياطي على هذا الجهاز</strong>، في التنزيلات. يمكنك إرساله الآن: افتح WhatsApp أو البريد أو Drive أو ما تريد، المس «إرفاق» واختر الملف.",
    "arquivo_pronto_tamanho": "الملف جاهز — <strong>{tamanho}</strong>.",
    "scan_intro_frase": "يستطيع التطبيق البحث داخل مجلد على جهازك، بما في ذلك المجلدات الفرعية، عن كتب بصيغتي <strong>EPUB</strong> و<strong>MOBI</strong>، وقصص مصوّرة بصيغتي <strong>CBZ</strong> و<strong>CBR</strong>، وكتب صوتية بصيغة <strong>M4B</strong>.",
    "scan_intro_auto_frase": "لملء رفّك بسرعة، يستطيع التطبيق البحث داخل مجلد على جهازك، بما في ذلك المجلدات الفرعية، عن كتب بصيغتي <strong>EPUB</strong> و<strong>MOBI</strong>، وقصص مصوّرة بصيغتي <strong>CBZ</strong> و<strong>CBR</strong>، وكتب صوتية بصيغة <strong>M4B</strong>.",
    "n_livros_aguardando": {
      "zero": "<strong>{n} كتب</strong> محفوظة التقدّم والعلامات، في انتظار استيرادها مرة أخرى.",
      "one": "<strong>كتاب واحد</strong> محفوظ التقدّم والعلامات، في انتظار استيراده مرة أخرى.",
      "two": "<strong>كتابان</strong> محفوظا التقدّم والعلامات، في انتظار استيرادهما مرة أخرى.",
      "few": "<strong>{n} كتب</strong> محفوظة التقدّم والعلامات، في انتظار استيرادها مرة أخرى.",
      "many": "<strong>{n} كتابًا</strong> محفوظ التقدّم والعلامات، في انتظار استيرادها مرة أخرى.",
      "other": "<strong>{n} كتاب</strong> محفوظ التقدّم والعلامات، في انتظار استيرادها مرة أخرى."
    },
    "fora_da_busca_titulo": "لا نستورد تلقائيًا ملفات PDF وTXT وDOCX (Word) وMD وMP3 وMP4",
    "fora_da_busca_texto": "تُستخدم هذه الصيغ لكل أنواع المستندات، لا للكتب وحدها. استبعادها يُبقي رفّك مرتّبًا. <strong>يمكنك استيراد كل ملف منها بنفسك عبر زر +.</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "مكتبتك المحلية",
    "biblioteca": "مكتبة",
    "organizacao": "تنظيم",
    "minhas_marcacoes": "علاماتي",
    "sistema": "النظام",
    "sua_biblioteca": "مكتبتك",
    "toque_em_um_livro_para_comecar_a_ler": "المس كتابًا لتبدأ القراءة.",
    "agrupar": "تجميع",
    "sua_estante_nao_tem_copia_de_seguranca": "رفّك بلا نسخة احتياطية",
    "se_este_aparelho_se_perder_o_progresso": "إذا حدث شيء لهذا الجهاز، فقد يضيع تقدّمك وعلاماتك.",
    "agora_nao": "ليس الآن",
    "nao_avisar_mais": "لا تذكّرني مجددًا",
    "carregando": "جارٍ التحميل...",
    "estante": "الرف",
    "lendo": "قيد القراءة",
    "favoritos": "المفضّلة",
    "marcas": "علامات",
    "mais": "المزيد",
    "neste_capitulo": "في هذا الفصل",
    "velocidade": "سرعة",
    "timer": "مؤقّت",
    "marcar": "علّم",
    "marcadores": "إشارات",
    "personalizar_leitura": "خصّص القراءة",
    "as_preferencias_ficam_salvas_para_as_p": "التفضيلات تُحفظ للقراءات القادمة.",
    "tema": "سمة",
    "claro": "فاتح",
    "sepia": "بُنّي",
    "escuro": "داكن",
    "oceano": "محيط",
    "tipografia": "الخط",
    "texto": "نص",
    "tamanho": "حجم",
    "espacamento": "تباعد الأسطر",
    "margens": "هوامش",
    "cores_personalizadas_opcional": "ألوان مخصّصة (اختياري)",
    "fundo": "خلفية",
    "fonte": "لون النص",
    "brilho": "سطوع",
    "orientacao": "اتجاه",
    "auto": "تلقائي",
    "retrato": "عمودي",
    "paisagem": "أفقي",
    "modo_de_leitura": "وضع القراءة",
    "automatico": "تلقائي",
    "horizontal": "أفقي",
    "vertical": "عمودي",
    "automatico_usa_rolagem_horizontal_para": "تلقائي يستخدم تقليبًا أفقيًا لـ EPUB وMOBI وTXT وMD، وتمريرًا عموديًا لـ PDF وDOCX. إذا غيّرته أثناء القراءة، يبقى التغيير لهذا الكتاب وحده.",
    "quadrinhos": "قصص مصورة",
    "como_a_pagina_aparece": "كيف تتسع الصفحة",
    "pagina_inteira": "الصفحة كاملة",
    "largura_da_tela": "عرض الشاشة",
    "sentido_da_leitura": "اتجاه القراءة",
    "normal": "عادي →",
    "manga": "← مانغا",
    "revista_aberta_na_horizontal": "صفحتان متجاورتان في الأفقي",
    "com_o_aparelho_deitado_mostra_duas_pag": "عند الإمساك به جانبيًا، تظهر صفحتان جنبًا إلى جنب — الغلاف منفرد، كما تُفتح قصة مصورة حقيقية.",
    "normal_vira_da_esquerda_para_a_direita": "العادي يقلب من اليسار إلى اليمين. المانغا تعكس كل شيء: السحب واللمس على الحافات وترتيب الصفحتين في العرض المزدوج.",
    "gire_o_aparelho_para_a_horizontal_para": "أدر الجهاز جانبيًا لترى صفحتين معًا.",
    "dois_toques_ampliam_no_ponto_tocado_co": "النقر المزدوج يكبّر عند موضع اللمس؛ بعد التكبير، اسحب للتنقل في الصفحة. القرص بإصبعين يعمل أيضًا.",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "زر التمرير في أعلى القارئ يبدّل بين صفحة بصفحة والتمرير المتواصل (بأسلوب الويبتون). في التمرير المتواصل تتصل الصفحات ببعضها، والتكبير يوسّع الصفحة: تتنقل عليها بالتمرير جانبيًا.",
    "virada_de_pagina": "تقليب الصفحة",
    "folha_real": "ورق حقيقي",
    "deslizar": "انزلاق",
    "sem_animacao": "بلا حركة",
    "na_leitura_horizontal_arraste_a_pagina": "في القراءة الأفقية، اسحب الصفحة من حافتها لثنيها بإصبعك. اترك في منتصف الطريق لإلغاء التقليب.",
    "ouvir_leitura": "استمع",
    "continue_de_onde_parou_no_seu_ritmo": "تابع من حيث توقفت، بإيقاعك.",
    "livro": "كتاب",
    "pronto_para_comecar": "جاهز للبدء",
    "voz": "صوت",
    "escolha_uma_voz_disponivel_no_disposit": "اختر صوتًا متوفرًا على هذا الجهاز",
    "voz_padrao_do_sistema": "صوت النظام الافتراضي",
    "durante_a_reproducao": "أثناء التشغيل",
    "a_leitura_avanca_pagina_a_pagina_os_co": "القراءة تتقدّم صفحة بصفحة. تظهر عناصر التحكم بالنظام عندما يدعمها المتصفح.",
    "organizar_livro": "نظّم الكتاب",
    "estantes_colecoes_tags_e_status": "رفوف ومجموعات ووسوم وحالة.",
    "cancelar": "إلغاء",
    "salvar": "حفظ",
    "grifos_citacoes_notas_e_marcadores_des": "تظليل هذا الكتاب واقتباساته وملاحظاته وإشاراته.",
    "sumario": "المحتويات",
    "toque_em_um_capitulo_para_ir_direto_ao": "المس فصلًا للذهاب مباشرةً إليه.",
    "sua_anotacao": "ملاحظتك",
    "edite_ou_adicione_comentarios_ao_seu_t": "عدّل أو أضف تعليقات إلى مقطعك.",
    "trecho": "مقطع",
    "sua_nota": "ملاحظتك",
    "salvar_nota": "احفظ الملاحظة",
    "agrupar_biblioteca": "جمّع المكتبة",
    "escolha_como_os_livros_serao_organizad": "اختر كيف تُرتّب الكتب على الرف.",
    "ao_arrastar_um_livro_para_outra_posica": "عند سحب كتاب إلى موضع آخر، يتحوّل الرف تلقائيًا إلى \"ترتيبي\" ويحفظ التسلسل الذي رتّبته.",
    "backup_e_restauracao": "نسخ احتياطي واستعادة",
    "sua_estante_seu_progresso_e_suas_marca": "رفّك وتقدّمك وعلاماتك في ملف واحد.",
    "escolha_uma_dimensao_para_explorar_sua": "اختر طريقة لاستكشاف مكتبتك.",
    "capitulos": "فصول",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "الصوت لا يصبح أخفض ولا أحدّ. ينطبق هذا على هذا الكتاب والكتب القادمة.",
    "ajuste_fino": "ضبط دقيق",
    "timer_de_sono": "مؤقّت النوم",
    "o_audio_diminui_de_volume_aos_poucos_e": "يخفت الصوت تدريجيًا ثم يتوقف مؤقتًا تلقائيًا.",
    "pontos_que_voce_guardou_neste_audioliv": "نقاط حفظتها في هذا الكتاب الصوتي.",
    "ajustes_do_audio": "إعدادات الصوت",
    "as_preferencias_ficam_salvas_para_todo": "هذه التفضيلات تُحفظ لكل الكتب الصوتية.",
    "botao_de_voltar": "زر الرجوع",
    "botao_de_avancar": "زر التقدّم",
    "recuar_ao_retomar": "ارجع عند الاستئناف",
    "depois_de_uma_pausa_longa_volta_alguns": "بعد توقف طويل، يعود ثوانٍ قليلة لتجد خيط الحكاية.",
    "tocar_ao_abrir": "شغّل عند الفتح",
    "ao_tocar_em_um_audiolivro_na_estante_a": "عند لمس كتاب صوتي على الرف، يبدأ التشغيل فورًا.",
    "no_computador_espaco_toca_e_pausa_pula": "على الحاسوب: space يشغّل ويوقف · ← → يتخطيان · Shift + ← → يبدّلان الفصل · ↑ ↓ الصوت · B الإشارات · [ ] السرعة.",
    "converter_pdf_para_epub": "حوّل PDF إلى EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "هيّئ الكتاب لقراءة سلسة وقابلة للضبط.",
    "confirmacao": "تأكيد",
    "confirmar": "أكّد",
    "processando": "جارٍ المعالجة",
    "documento": "مستند",
    "buscar_livros_no_dispositivo": "ابحث عن كتب على هذا الجهاز",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "ابحث عن ملفات EPUB وMOBI وCBZ وCBR وM4B المحفوظة أصلًا على جهازك.",
    "juntar_em_um_unico_audiolivro": "تدمج في كتاب صوتي واحد؟",
    "titulo": "عنوان",
    "autor": "مؤلف",
    "importar_separados": "استورد منفصلة",
    "bem_vindo_ao_veredas_reader": "مرحبًا بك في Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "مكتبتك للقراءة، بالكامل على جهازك.",
    "buscar": "ابحث",
    "importar_livro": "استورد كتابًا",
    "buscar_titulo_autor_tag": "ابحث عن عنوان أو مؤلف أو وسم...",
    "fechar_busca": "أغلق البحث",
    "navegacao_da_biblioteca": "تنقّل المكتبة",
    "fechar_menu": "أغلق القائمة",
    "agrupar_livros": "جمّع الكتب",
    "voltar": "رجوع",
    "marcar_pagina": "علّم الصفحة",
    "personalizar": "تخصيص",
    "navegacao_principal": "التنقّل الرئيسي",
    "acoes_do_trecho": "إجراءات المقطع",
    "amarelo": "أصفر",
    "verde": "أخضر",
    "rosa": "وردي",
    "azul": "أزرق",
    "player_de_audiolivro": "مشغّل الكتاب الصوتي",
    "minimizar_player": "صغّر المشغّل",
    "minimizar": "تصغير",
    "video_em_reproducao": "الفيديو قيد التشغيل",
    "abrir_a_lista_de_capitulos": "افتح قائمة الفصول",
    "posicao_no_audio": "الموضع في الصوت",
    "alternar_entre_o_progresso_do_capitulo": "بدّل بين تقدّم الفصل وتقدّم الكتاب كله",
    "capitulo_anterior": "الفصل السابق",
    "voltar_15_segundos": "ارجع 15 ثانية",
    "reproduzir": "تشغيل",
    "avancar_30_segundos": "تقدّم 30 ثانية",
    "proximo_capitulo": "الفصل التالي",
    "velocidade_de_reproducao": "سرعة التشغيل",
    "marcar_este_ponto": "علّم هذه النقطة",
    "ver_marcadores": "اعرض الإشارات",
    "silenciar": "اكتم",
    "volume": "مستوى الصوت",
    "audiolivro_em_reproducao": "الكتاب الصوتي قيد التشغيل",
    "abrir_o_player": "افتح المشغّل",
    "fechar_o_player": "أغلق المشغّل",
    "fechar": "إغلاق",
    "trecho_anterior": "المقطع السابق",
    "iniciar_leitura": "ابدأ القراءة بصوت عالٍ",
    "proximo_trecho": "المقطع التالي",
    "escreva_seu_comentario_interpretacao_o": "اكتب تعليقك أو قراءتك أو تذكيرك...",
    "cancelar_importacao": "ألغِ الاستيراد",
    "nome_do_audiolivro": "اسم الكتاب الصوتي",
    "nome_do_autor": "اسم المؤلف",
    "idioma": "اللغة",
    "idioma_do_aplicativo": "لغة التطبيق",
    "o_aplicativo_segue_o_idioma_do_apare": "يتبع التطبيق لغة جهازك. إذا لم تكن لغتك موجودة هنا بعد، يُفتح بالإنجليزية.",
    "seguir_o_aparelho": "اتبع الجهاز",
    "fazer_backup": "انسخ احتياطيًا الآن",
    "todos": "الكل",
    "lidos": "مقروء",
    "pausados": "متوقفة مؤقتًا",
    "autores": "المؤلفون",
    "tags": "وسوم",
    "grifar": "ظلّل",
    "anotar": "دوّن",
    "enviar": "أرسل",
    "restaurar_padroes": "استعد الإعدادات الافتراضية",
    "voltar_para_1": "العودة إلى 1×",
    "marcar_agora": "علّم الآن",
    "escolher_pasta": "اختر مجلدًا",
    "juntar_em_um_audiolivro": "ادمج في كتاب صوتي واحد",
    "sobre": "حول",
    "licencas_de_codigo_aberto": "تراخيص المصادر المفتوحة",
    "configuracoes": "الإعدادات",
    "temas_e_idioma": "السمات واللغة"
  },
  "aviso": {
    "idioma_trocado": "تم تغيير اللغة."
  },
  "vn": {
    "quem_le": "مَن يقرأ",
    "natural": "طبيعي",
    "do_sistema": "النظام",
    "nota_sistema": "يستخدم الأصوات المثبّتة على جهازك. لقراءة أقرب إلى الصوت البشري، اختر «طبيعي».",
    "nota_sistema_com_natural": "الصوت الطبيعي لا يزال مُنزّلًا. عُد إلى «طبيعي» متى شئت.",
    "voz_do_sistema": "صوت النظام",
    "lendo_com_a_voz_do_sistema": "تتم القراءة بصوت النظام.",
    "voz_natural": "الصوت الطبيعي",
    "gerada_no_aparelho": "صوت أقرب بكثير إلى الصوت البشري، يُنشأ على جهازك مباشرةً.",
    "progresso_download": "تقدّم التنزيل",
    "x_de_y": "{x} من {y}",
    "aviso_arquivo": "يحتاج الصوت الطبيعي إلى فتح Veredas من عنوان التطبيق، لا كملف على الحاسوب. وإلى ذلك الحين، تتم القراءة بصوت النظام.",
    "aviso_navegador": "هذا المتصفح لا يوفّر الميزات التي يحتاجها الصوت الطبيعي. تستمر القراءة بصوت النظام.",
    "verificando": "جارٍ التحقق من الصوت الطبيعي…",
    "fato_download": "تنزيل لمرة واحدة بحجم {tamanho}. بعدها يعمل دون اتصال بالإنترنت.",
    "fato_wifi": "يُفضّل استخدام Wi-Fi. يمكنك الإيقاف المؤقت والمتابعة لاحقًا.",
    "fato_privacidade": "نص الكتاب لا يغادر جهازك أبدًا.",
    "fato_idiomas": "يتحدث 31 لغة، منها العربية والإنجليزية والبرتغالية. أما اللغات الأخرى فتبقى بصوت النظام.",
    "baixar_voz_natural": "تنزيل الصوت الطبيعي ({tamanho})",
    "licenca_curta": "نموذج Supertonic 3 من Supertone، بموجب ترخيص OpenRAIL-M. التفاصيل في حول > تراخيص المصادر المفتوحة.",
    "pode_continuar_usando": "يمكنك مواصلة القراءة أثناء التنزيل. وإذا انقطع الاتصال، يُستأنف التنزيل من حيث توقف.",
    "pausar_download": "إيقاف التنزيل مؤقتًا",
    "erro_espaco": "لا توجد مساحة كافية على الجهاز لإكمال التنزيل. وفّر بعض المساحة ثم حاول مجددًا.",
    "erro_offline": "لا يوجد اتصال بالإنترنت حاليًا. ما نُزّل حتى الآن محفوظ.",
    "erro_rede": "انقطع الاتصال أثناء التنزيل. ما نُزّل حتى الآن محفوظ.",
    "download_pausado": "التنزيل متوقف مؤقتًا. ما نُزّل حتى الآن محفوظ.",
    "continuar_download": "متابعة",
    "descartar": "حذف",
    "voz_feminina": "أنثوي",
    "voz_feminina_desc": "ناعم وهادئ",
    "voz_masculina": "ذكوري",
    "voz_masculina_desc": "دافئ ورزين",
    "parar_amostra": "إيقاف العيّنة",
    "ouvir_amostra_de": "استمع إلى عيّنة: {voz}",
    "escolha_a_voz": "اختر الصوت",
    "qualidade": "الجودة",
    "q_auto": "تلقائية",
    "q_rapida": "سريعة",
    "q_maxima": "الأفضل",
    "q_auto_desc": "تتكيّف مع أداء جهازك لتجري القراءة دون توقّف.",
    "q_rapida_desc": "تُنشئ الصوت بسرعة أكبر. مناسبة للأجهزة البسيطة.",
    "q_maxima_desc": "أجود صوت. قد تسبب على الأجهزة البسيطة توقّفات بين الجمل.",
    "ocupa": "يشغل {tamanho} على هذا الجهاز",
    "remover": "إزالة",
    "baixar_pelos_dados": "التنزيل عبر بيانات الجوال؟",
    "baixar_pelos_dados_msg": "يبدو أن جهازك غير متصل بشبكة Wi-Fi. حجم التنزيل {tamanho} وقد يستهلك من باقة بياناتك.",
    "baixar_agora": "تنزيل على أي حال",
    "pronta": "الصوت الطبيعي جاهز.",
    "download_interrompido": "توقف التنزيل. المس «متابعة» متى شئت.",
    "remover_titulo": "إزالة الصوت الطبيعي؟",
    "descartar_titulo": "حذف التنزيل؟",
    "remover_msg": "سيُحرّر ذلك {tamanho}. تعود القراءة إلى صوت النظام، ويمكنك تنزيله مجددًا متى شئت.",
    "descartar_msg": "سيُحذف ما نُزّل حتى الآن.",
    "removida": "أُزيل الصوت الطبيعي من هذا الجهاز.",
    "amostra_falhou": "تعذّر تشغيل العيّنة على هذا الجهاز.",
    "amostra": "مرحبًا! هكذا ستبدو كتبك بالصوت الطبيعي.",
    "gerando_voz": "جارٍ تجهيز الصوت…",
    "automatico_idioma": "تلقائي ({idioma})",
    "automatico": "تلقائي",
    "so_voz_do_sistema": "صوت النظام",
    "aviso_idioma": "لغة النص: {idioma}. لا يتحدث الصوت الطبيعي هذه اللغة بعد، لذا سيُقرأ الكتاب بصوت النظام.",
    "aviso_idioma_desconhecido": "تعذّر التعرّف على لغة هذا النص. اختر اللغة أدناه لاستخدام الصوت الطبيعي.",
    "aviso_falha": "تعذّر تشغيل الصوت الطبيعي على هذا الجهاز الآن. تستمر القراءة بصوت النظام.",
    "nao_carregou_usando_sistema": "لم يُحمَّل الصوت الطبيعي على هذا الجهاز. تتم القراءة بصوت النظام.",
    "parou_usando_sistema": "توقف الصوت الطبيعي. نتابع بصوت النظام.",
    "aparelho_lento": "يُنشئ هذا الجهاز الصوت ببطء. اختر الجودة «سريعة» لتجنّب التوقّفات.",
    "idioma_do_texto": "لغة النص",
    "idioma_do_texto_dica": "تم التعرّف عليها من النص نفسه. غيّرها إذا بدا النطق خاطئًا.",
    "leitura_em_voz_alta": "القراءة بصوت عالٍ",
    "lento_usando_sistema": "الصوت الطبيعي بطيء جدًا على هذا الجهاز. ستستمر القراءة بصوت النظام.",
    "aviso_lento": "لا يستطيع هذا الجهاز توليد الصوت الطبيعي بسرعة القراءة، لذلك يقرأ صوت النظام في الوقت الحالي.",
    "sem_memoria_usando_sistema": "لم تتّسع ذاكرة هذا الجهاز للصوت الطبيعي. ستتم القراءة بصوت النظام.",
    "aviso_falha_memoria": "لم تكن الذاكرة كافية للصوت الطبيعي على هذا الجهاز. غالبًا ما يساعد إغلاق التطبيقات الأخرى وإعادة المحاولة؛ وفي هذه الأثناء تتم القراءة بصوت النظام.",
    "copiar_detalhe": "نسخ التفاصيل",
    "copiado": "تم نسخ التفاصيل.",
    "falhou_titulo": "لم يتم تحميل الصوت الطبيعي على هذا الجهاز.",
    "falhou_texto": "لم يتمكن الجهاز من تجهيز الصوت الطبيعي. تستمر القراءة بصوت النظام. للمساعدة في حل المشكلة، انسخ التفاصيل أدناه وأرسلها إلى الدعم.",
    "falhou_memoria_texto": "لم تكن الذاكرة كافية للصوت الطبيعي على هذا الجهاز. غالبًا ما يساعد إغلاق التطبيقات الأخرى وإعادة المحاولة.",
    "tentar_de_novo": "إعادة المحاولة",
    "tentando": "جارٍ التحميل…",
    "sondando": "جارٍ اختبار ذاكرة هذا الجهاز…",
    "sonda_explica": "يحجز الاختبار لثوانٍ الذاكرة التي سيحتاجها الصوت الطبيعي ثم يعيدها فورًا. هكذا تعرف النتيجة الآن، لا بعد التنزيل.",
    "aviso_aparelho_justo": "ذاكرة هذا الجهاز قليلة بالنسبة إلى الصوت الطبيعي. قد لا يتم تحميله؛ عندها يكفي حذفه لاستعادة المساحة.",
    "preparando_demora": "يجري تجهيز الصوت. قد يستغرق ذلك بضع دقائق.",
    "incompativel_titulo": "الصوت الطبيعي لا يعمل على هذا الجهاز.",
    "incompativel_memoria": "لم تكن الذاكرة كافية لتجهيزه. تبقى القراءة بصوت النظام، وخياراته في الأسفل. إن أردت، أغلق التطبيقات الأخرى واضغط على «اختبر مجددًا».",
    "incompativel_lento": "كان أبطأ من أن يواكب القراءة. تبقى القراءة بصوت النظام، وخياراته في الأسفل.",
    "incompativel_queda": "أُغلق التطبيق أثناء تحميله. تبقى القراءة بصوت النظام، وخياراته في الأسفل.",
    "incompativel_falha": "لم يتمكن من التحميل هنا. تبقى القراءة بصوت النظام، وخياراته في الأسفل.",
    "testar_de_novo": "إعادة الاختبار",
    "remover_e_liberar": "الحذف وتحرير {tamanho}",
    "tela_durante_a_leitura": "الشاشة أثناء القراءة",
    "manter_tela_ligada": "إبقاء الشاشة مضاءة",
    "manter_tela_ligada_dica": "ما دام الكتاب مفتوحًا، لا تنطفئ الشاشة من تلقاء نفسها. وعند إغلاق الكتاب يعود كل شيء كما كان."
  }
});