/* ============================================================
   ENGLISH (US) — and the safety net for every other language
   ------------------------------------------------------------
   This file has two jobs. It is the English translation, and it
   is the last stop of the fallback chain: when a line is missing
   from any other language file, the app shows the English one
   rather than a blank space or a raw key. That is why this file
   must always be complete.

   Spelling here is US English. Regional files (en-GB.js,
   en-AU.js, en-CA.js, en-IN.js) sit on top of this one and only
   carry the lines that differ — a few dozen, not all of them.

   See idioma.js for why these files are .js and not .json.
   ============================================================ */
Idiomas.registrar('en', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "Bookmark deleted.",
    "excluir_marcador": "Delete bookmark",
    "o_marcador_sera_removido_permanentemen": "The bookmark will be removed for good.",
    "excluir_marcador_2": "Delete bookmark?",
    "pagina_salva": "Page saved",
    "anotacoes": "Notes",
    "citacoes": "Quotes",
    "item_excluido": "Item deleted.",
    "este_registro_sera_removido_permanente": "This entry will be removed from the library for good.",
    "configuracoes_padrao_restauradas": "Default settings restored.",
    "leitura_da_esquerda_para_a_direita": "Reading left to right.",
    "leitura_da_direita_para_a_esquerda_man": "Reading right to left (manga).",
    "a_pagina_inteira_passa_a_caber_na_tela": "The whole page now fits on screen.",
    "a_pagina_passa_a_ocupar_toda_a_largura": "The page now fills the width of the screen.",
    "virada_sem_animacao_ativada": "Page turns without animation now.",
    "virada_deslizante_ativada": "Sliding page turn is on.",
    "virada_em_folha_real_ativada": "Real-paper page turn is on.",
    "padrao_automatico_cada_formato_abre_no": "Automatic: each format opens the way that suits it.",
    "mudando_durante_a_leitura_o_ajuste_fic": "If you change it while reading, the change is kept for that book only.",
    "automatico_usa_rolagem_horizontal_para": "Automatic uses horizontal paging for EPUB, MOBI, TXT, MD and comics, and vertical scrolling for PDF and DOCX.",
    "este_livro": "this book",
    "armazenamento_local_indisponivel_neste": "Local storage is not available in this browser.",
    "o_aplicativo_pode_procurar_os_livros_q": "The app can look for books already on your device.",
    "vamos_montar_sua_estante": "Shall we fill your shelf?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "Without your agreement, the app cannot be used.",
    "precisamos_do_seu_aceite": "We need your agreement",
    "antes_de_comecar_leia_e_aceite_os_docu": "Before you start, please read and accept the documents below.",
    "selecionar_todos": "Select all",
    "limpar_selecao": "Clear selection",
    "todos_parecem_ja_estar_na_sua_estante": "They all seem to be on your shelf already.",
    "lendo_a_pasta_escolhida": "Reading the folder you chose…",
    "procurando_livros": "Looking for books",
    "nao_foi_possivel_concluir_a_busca_no_d": "The search on this device could not be finished.",
    "tente_outra_pasta_do_aparelho": "Try another folder on your device.",
    "nenhum_livro_encontrado": "No books found",
    "use_o_botao_para_escolher_os_arquivos": "Use the + button to pick files by hand. On Android phones, Chrome usually lets you choose a whole folder.",
    "seu_navegador_nao_permite_ler_pastas": "Your browser will not read folders",
    "busca_automatica_indisponivel": "Automatic search unavailable",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR and M4B",
    "termos_de_uso": "Terms of use",
    "politica_de_privacidade": "Privacy policy",
    "um_minuto_agora_evita_perder_o_progres": "A minute now saves your progress and marks later.",
    "ver_estante": "See shelf",
    "modo_juntar": "Merge mode",
    "modo_substituir": "Replace mode",
    "restauracao_concluida": "Restore finished",
    "tente_de_novo_com_o_arquivo_original": "Try again with the original file.",
    "a_restauracao_nao_pode_ser_concluida": "The restore could not be finished",
    "devolvendo_o_seu_progresso_e_as_suas_m": "Bringing back your progress and your marks...",
    "restaurar_este_backup": "Restore this backup?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Pick the .zip Veredas saved, or the .txt you received through sharing.",
    "nao_foi_possivel_ler_este_arquivo": "This file could not be read",
    "lendo_o_backup": "Reading the backup",
    "backup_do_veredas_reader": "Veredas Reader backup",
    "arquivo_de_transporte_txt_contendo_os": "a .txt copy of the backup, with the same content as the ZIP",
    "nao_foi_possivel_montar_o_arquivo_de_b": "The backup file could not be built.",
    "escolher_o_app": "Choose the app",
    "vale_conferir_o_que_vai_no_arquivo": "Worth checking what goes in the file",
    "enviar_para_outro_app": "Send to another app",
    "salvar_o_arquivo": "Save the file",
    "o_navegador_aqui_nao_oferece_o_compart": "This browser does not offer direct sharing. You can save the file and send it later through whichever app you like.",
    "este_aparelho_nao_abre_a_lista_de_apli": "This device will not open the app list",
    "importe_pelo_menos_um_livro_antes_de_f": "Import at least one book before making a backup.",
    "estante_vazia": "Empty shelf",
    "nao_deu_para_copiar": "Could not copy",
    "copiar_detalhes": "Copy details",
    "o_backup_foi_salvo_assim_mesmo": "The backup was saved anyway",
    "o_aparelho_recusou_abrir_a_lista": "Couldn't open the share list",
    "sem_detalhes_do_navegador": "no details from the browser",
    "o_sistema_nao_aceitou_receber_o_arquiv": "The device's system couldn't receive the file.",
    "o_navegador_considerou_a_situacao_inse": "The browser blocked sharing because of one of its own security rules. Save the file and send it with any app you like.",
    "o_compartilhamento_so_funciona_em_ende": "Sharing only works on secure addresses. This app is being opened from a plain http:// address, and in that case the browser blocks sending to other apps.",
    "este_navegador_nao_conseguiu_iniciar_o": "This browser couldn't open sharing. Save the file and send it with any app you like.",
    "o_navegador_recebeu_um_arquivo_em_form": "The browser didn't open the list of apps to share with. Tap the button again, or save the file and send it with any app you like.",
    "nao_foi_possivel_gerar_o_backup": "The backup could not be created.",
    "reunindo_a_sua_estante": "Gathering your shelf...",
    "preparando_o_backup": "Preparing the backup",
    "pronto_nada_mais_esta_esperando": "Done — nothing is waiting any more.",
    "o_progresso_e_as_marcacoes_desses_livr": "The progress and marks of those books will be erased. If you import the files later, they will come back blank.",
    "descartar_o_que_esta_esperando": "Delete the pending data?",
    "lembretes_de_backup_religados": "Backup reminders turned back on.",
    "sem_titulo": "Untitled",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "Reminders turned off.",
    "manter_ligado": "Keep them on",
    "desligar_assim_mesmo": "Turn off anyway",
    "o_botao_de_salvar_continua_onde_sempre": "The save button stays where it has always been, in Backup and restore.",
    "o_lembrete_e_o_unico_aviso_que_existe": "The reminder is the only warning there is. Without it, you'll need to remember to back up on your own.\n\n",
    "limpar_os_dados_do_navegador_desinstal": "If the browser data is cleared, the app is uninstalled, you switch phones or the device fails, your progress, highlights, quotes, notes and bookmarks can't be recovered.\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "Your shelf exists on this device alone. There is no copy on any server, so there is no way to recover it for you.\n\n",
    "leia_antes_de_confirmar": "Read before confirming",
    "desligar_os_lembretes_de_backup": "Turn off backup reminders?",
    "progresso_de_leitura_restaurado_neste": "Reading progress restored for this book.",
    "pronto": "Done.",
    "aplicando_as_suas_preferencias": "Applying your preferences...",
    "atualize_o_veredas_reader_e_tente_de_n": "Update Veredas Reader and try again.",
    "este_backup_foi_feito_numa_versao_mais": "This backup was made with a newer version of the app.",
    "este_arquivo_nao_e_um_backup_de_biblio": "This file is not a Veredas library backup.",
    "o_conteudo_interno_nao_pode_ser_lido": "The contents inside could not be read.",
    "o_backup_esta_corrompido": "The backup is damaged.",
    "falta_o_arquivo_biblioteca_json_la_den": "The biblioteca.json file is missing inside it.",
    "este_arquivo_nao_parece_ser_um_backup": "This file does not look like a Veredas backup.",
    "compactando": "Compressing...",
    "para_restaurar_menu_lateral_backup_e_r": "To restore: side menu > Backup and restore > Restore backup.",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas automatically restores the marks and the spot where you stopped.",
    "importe_os_livros_normalmente_no_aplic": "import the books normally in the app: as it recognises each file,",
    "ele_nao_contem_os_arquivos_dos_livros": "It does NOT contain the book files. To restore in full,",
    "as_notas_os_marcadores_e_a_organizacao": "your notes, your bookmarks and how your shelf is organised.",
    "este_arquivo_guarda_o_seu_progresso_de": "This file holds your reading progress, your highlights, your quotes,",
    "verificando_se_sao_partes_do_mesmo_aud": "Checking whether these are parts of the same audiobook...",
    "analisando_os_arquivos": "Reading the files",
    "nao_foi_possivel_salvar_o_audiolivro": "The audiobook could not be saved.",
    "audiolivros_grandes_podem_levar_alguns": "Large audiobooks may take a moment...",
    "salvando_na_sua_estante": "Saving to your shelf",
    "falha_ao_processar_os_arquivos": "The files could not be processed.",
    "falha_ao_processar_o_arquivo": "The file could not be processed.",
    "nao_foi_possivel_salvar_o_quadrinho": "The comic could not be saved.",
    "quase_la": "Almost there...",
    "falha_ao_processar_o_quadrinho": "The comic could not be processed.",
    "autor_desconhecido": "Unknown author",
    "lendo_o_quadrinho": "Reading the comic...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "The book could not be saved to the library.",
    "nao_foi_possivel_ler_o_pdf": "The PDF could not be read.",
    "lendo_o_pdf": "Reading the PDF...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "If it is an old .doc, open it in Word and save it as .docx before importing.",
    "este_arquivo_nao_e_um_docx_valido": "This file is not a valid .docx.",
    "livros_com_protecao_da_amazon_nao_pode": "Books with Amazon protection cannot be opened here. Use a DRM-free copy or convert the book to EPUB.",
    "este_arquivo_esta_protegido_por_drm": "This file is protected by DRM.",
    "confira_se_a_extensao_corresponde_ao_c": "Check that the extension matches the contents, or convert the book to EPUB.",
    "este_arquivo_nao_e_um_mobi_valido": "This file is not a valid MOBI.",
    "nao_foi_possivel_ler_o_arquivo": "The file could not be read.",
    "formato_nao_suportado": "Format not supported.",
    "falha_ao_salvar_o_livro_na_biblioteca": "The book could not be saved to the library.",
    "livro_importado_e_salvo_no_dispositivo": "Book imported and saved on this device.",
    "audiolivro_importado_e_salvo_no_dispos": "Audiobook imported and saved on this device.",
    "quadrinho_importado_e_salvo_no_disposi": "Comic imported and saved on this device.",
    "salvando_na_sua_estante_2": "Saving to your shelf...",
    "importando_livro": "Importing book",
    "importar_mesmo_assim": "Import anyway",
    "parece_que_este_livro_ja_esta_na_estan": "It looks like this book is already on your shelf",
    "este_livro_ja_esta_na_estante": "This book is already on your shelf",
    "video_importado_e_salvo_no_dispositivo": "Video imported and saved on this device.",
    "importacao_cancelada": "Import cancelled.",
    "preparando_o_arquivo": "Preparing the file",
    "importando_audiolivro": "Importing audiobook",
    "importacao_concluida": "Import finished",
    "importacao_interrompida": "Import stopped",
    "a_importacao_foi_interrompida_o_que_ja": "The import was stopped; whatever had already come in stays on your shelf.",
    "finalizando": "Finishing up…",
    "nao_foi_possivel_ler_o_arquivo_2": "the file could not be read",
    "importando_livros": "Importing books",
    "livros_quadrinhos_documentos_audiolivr": "Books, comics, documents, audiobooks and videos",
    "series": "Series",
    "colecoes": "Collections",
    "organizacao_salva": "Organization saved.",
    "informe_um_nome_para_o_livro_antes_de": "Give the book a name before saving.",
    "nome_do_livro_obrigatorio": "The book needs a name",
    "importe_um_livro_primeiro": "Import a book first.",
    "citacao": "quote",
    "anotacao": "note",
    "citacao_2": "Quote",
    "anotacao_2": "Note",
    "uma_citacao": "a quote",
    "uma_anotacao": "a note",
    "o_marcador_sera_removido_da_biblioteca": "The bookmark will be removed from the library, but the book file stays untouched.",
    "marcador_de_audio": "Audio bookmark",
    "marcador_de_video": "Video bookmark",
    "nao_foi_possivel_excluir_o_livro": "The book could not be deleted.",
    "livro_excluido_da_biblioteca": "Book deleted from the library.",
    "excluir_livro": "Delete book",
    "isso_remove_apenas_a_copia_armazenada": "This removes only the copy the library keeps, along with progress, bookmarks and notes. The original file in your own folder will not be deleted.",
    "excluir_livro_2": "Delete book?",
    "ordem_personalizada_salva": "Custom order saved.",
    "ordem_manual_da_sua_estante": "Your shelf, in the order you set.",
    "agrupamento_alterado_para_minha_ordem": "Grouping switched to My Order.",
    "nova_ordem_salva": "New order saved.",
    "nao_foi_possivel_salvar_a_nova_ordem": "The new order could not be saved.",
    "baixar_automaticamente": "Download automatically",
    "escolha_livremente_onde_o_arquivo_sera": "Choose freely where the file is written.",
    "salvar_epub": "Save EPUB",
    "livro_epub": "EPUB book",
    "erro_desconhecido": "unknown error",
    "a_permissao_para_salvar_o_arquivo_foi": "Permission to save the file was cancelled. Nothing in the library was changed.",
    "conversao_cancelada_o_pdf_original_per": "Conversion cancelled. The original PDF stays in the library.",
    "preparando_salvamento": "Getting ready to save…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "The copy of the PDF is not available in the library.",
    "reconstruindo_o_livro_localmente": "Rebuilding the book on your device.",
    "convertendo_pdf": "Converting PDF",
    "nao_foi_possivel_compartilhar_o_livro": "The book could not be shared.",
    "o_arquivo_foi_preparado_para_voce_comp": "The file is ready for you to share in another app.",
    "livro_compartilhado": "Book shared.",
    "a_copia_deste_livro_nao_esta_disponive": "The copy of this book is not available in the library.",
    "para_manter_a_politica_de_compartilham": "To keep the library's sharing policy, EPUB and MOBI files cannot be shared by this app.",
    "quadrinhos_ficam_guardados_somente_no": "Comics are kept on your device only and cannot be shared by this app.",
    "audiolivros_e_videos_ficam_guardados_s": "Audiobooks and videos are kept on your device only and cannot be shared by this app.",
    "formato_protegido": "Protected format",
    "compartilhamento_indisponivel": "Sharing unavailable",
    "concluido": "Finished",
    "ainda_nao_comecado": "Not started yet",
    "continue_lendo": "Continue reading",
    "continue_ouvindo": "Continue listening",
    "continue_assistindo": "Continue watching",
    "comece_por_aqui": "Start here",
    "comece_a_ouvir": "Start listening",
    "comece_a_assistir": "Start watching",
    "no_total": "overall",
    "para_ler": "to read",
    "sua_estante": "Your shelf",
    "livros_organizados_pela_opcao_selecion": "Books arranged by the option you picked.",
    "uma_prateleira_para_cada_tipo_de_arqui": "One shelf for each kind of file.",
    "autores_agrupados_em_ordem_alfabetica": "Authors grouped alphabetically.",
    "toque_para_continuar_de_onde_parou": "Tap to pick up where you left off.",
    "para_ler_2": "To read",
    "lendo_agora": "Reading now",
    "audio_e_video": "Audio and video",
    "trechos_salvos_separadamente_dos_marca": "Passages saved apart from bookmarks.",
    "comentarios_vinculados_a_trechos_selec": "Comments tied to passages you selected.",
    "paginas_salvas_para_voltar_rapidamente": "Pages saved so you can come back quickly.",
    "do_maior_para_o_menor_progresso_de_lei": "From most to least reading progress.",
    "livros_adicionados_ou_lidos_mais_recen": "Books added or read most recently.",
    "ordem_alfabetica_pelo_titulo": "Alphabetical by title.",
    "separa_em_prateleiras_de_epub_pdf_docx": "Splits into shelves of EPUB, PDF, DOCX, audiobooks, videos…",
    "tipo_de_arquivo": "File type",
    "organiza_e_separa_os_livros_por_autor": "Arranges and separates books by author.",
    "agrupar_por_autor": "Group by Author",
    "pressione_o_livro_e_mova_o": "Press and hold a book, then move it.",
    "minha_ordem": "My Order",
    "epub_pronto": "EPUB ready",
    "conversao_concluida": "Conversion finished",
    "necessario_para_salvar_o_epub_ao_lado": "Needed to save the EPUB next to the original",
    "escolha_a_pasta_do_pdf": "Choose the PDF's folder",
    "processando": "Working…",
    "processamento_local_no_navegador": "Processed on your device, in the browser",
    "convertendo_livro": "Converting book",
    "livro_em_pdf": "PDF book",
    "recalculando_paginas": "Recalculating pages...",
    "ajustando_leitura": "Adjusting the layout",
    "abrir_comentario": "Open comment",
    "anotacao_salva": "Note saved.",
    "anotacao_atualizada": "Note updated.",
    "escreva_uma_nota_antes_de_salvar": "Write a note before saving.",
    "nao_foi_possivel_compartilhar": "Could not share.",
    "compartilhamento_indisponivel_2": "Sharing unavailable.",
    "trecho_copiado": "Passage copied.",
    "trecho_compartilhado": "Passage shared.",
    "citacao_salva": "Quote saved.",
    "trecho_grifado": "Passage highlighted.",
    "grifo_removido": "Highlight removed.",
    "comentario_apagado": "Comment deleted.",
    "remover_grifo": "Remove highlight",
    "apagar_comentario": "Delete comment",
    "remover_grifo_2": "Remove highlight?",
    "apagar_comentario_2": "Delete comment?",
    "remover_este_grifo": "Remove this highlight?",
    "apagar_este_comentario": "Delete this comment?",
    "sem_comentario": "No comment",
    "comentario": "Comment",
    "marcador_removido_desta_pagina": "Bookmark removed from this page.",
    "pagina_adicionada_aos_marcadores": "Page added to your bookmarks.",
    "este_e_o_inicio_do_livro": "This is the start of the book.",
    "esta_e_a_primeira_pagina": "This is the first page.",
    "voce_chegou_ao_fim_do_livro": "You have reached the end of the book.",
    "voce_chegou_ao_fim_do_quadrinho": "You have reached the end of the comic.",
    "agora_em_revista_aberta_duas_paginas_l": "Now as a spread: two pages side by side, with the cover on its own.",
    "leitura_horizontal_ativada_neste_livro": "Horizontal reading is on for this book.",
    "rolagem_vertical_ativada_neste_livro": "Vertical scrolling is on for this book.",
    "leitura_pagina_a_pagina_ativada_neste": "Page-by-page reading is on for this comic.",
    "rolagem_continua_ativada_neste_quadrin": "Continuous scrolling is on for this comic.",
    "mudar_para_rolagem_vertical": "Switch to vertical scrolling",
    "mudar_para_leitura_horizontal": "Switch to horizontal reading",
    "rolagem_continua_estilo_webtoon": "Continuous scrolling (webtoon style)",
    "voltar_para_pagina_a_pagina": "Back to page by page",
    "separando_os_capitulos": "Separating the chapters...",
    "lendo_o_livro": "Reading the book",
    "lendo_o_markdown": "Reading the Markdown",
    "lendo_o_documento": "Reading the document",
    "pagina_indisponivel": "Page unavailable.",
    "isto_acontece_so_desta_vez": "This only happens this once.",
    "preparando_o_quadrinho": "Preparing the comic",
    "abrindo_o_quadrinho": "Opening the comic...",
    "montando_as_paginas": "Building the pages...",
    "nao_foi_possivel_abrir_este_livro": "This book could not be opened.",
    "abertura_cancelada": "Opening cancelled.",
    "o_livro_demorou_demais_para_abrir_e_fo": "The book took too long to open and was stopped.",
    "importe_o_arquivo_novamente_para_conti": "Import the file again to carry on reading.",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "This book's file is no longer saved on your device.",
    "preparando_sua_leitura": "Getting your book ready...",
    "abrindo_livro": "Opening book",
    "leitura_concluida": "Reading finished.",
    "a_voz_foi_interrompida_pelo_navegador": "The browser stopped the voice.",
    "nao_foi_possivel_preparar_este_trecho": "This passage could not be prepared for audio.",
    "a_leitura_em_voz_alta_nao_e_suportada": "Reading aloud is not supported in this browser.",
    "pausar_leitura": "Pause reading",
    "em_pausa": "Paused",
    "leitura_em_voz_alta_nao_disponivel_nes": "Reading aloud is not available in this browser",
    "nome_do_marcador": "Bookmark name",
    "o_marcador_sera_removido_deste_audioli": "The bookmark will be removed from this audiobook.",
    "nao_foi_possivel_salvar_o_marcador": "The bookmark could not be saved.",
    "ja_existe_um_marcador_neste_ponto": "There is already a bookmark at this spot.",
    "timer_de_sono_encerrado": "Sleep timer finished.",
    "fim_do_cap": "End of ch.",
    "timer_desativado": "Timer turned off.",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "The audio will pause at the end of the chapter.",
    "este_audiolivro_nao_tem_capitulos": "This audiobook has no chapters.",
    "ao_fim_do_capitulo": "At the end of the chapter",
    "desativar_timer": "Turn off timer",
    "mais_10_minutos_no_timer": "10 more minutes on the timer.",
    "somar_10_minutos": "Add 10 minutes",
    "pausa_ao_fim_do_capitulo": "Pause at the end of the chapter",
    "no_livro_todo": "Across the whole book",
    "video": "Video",
    "audiolivro_concluido": "Audiobook finished.",
    "video_concluido": "Video finished.",
    "video_2": "video",
    "audio": "audio",
    "toque_em_reproduzir_para_comecar": "Tap play to start.",
    "falha_ao_carregar_o_audio": "The audio could not be loaded.",
    "exclua_o_da_biblioteca_e_importe_o_arq": "Delete it from the library and import the file again.",
    "os_nomes_dos_arquivos_seguem_uma_seque": "The file names follow a sequence, so they look like chapters of one audiobook.",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "The files share the same album in their tags, so they look like chapters of one audiobook.",
    "libere_espaco_ou_exclua_livros_da_bibl": "Free up space or delete books from the library and try again.",
    "o_armazenamento_do_aparelho_esta_cheio": "Your device's storage is full.",
    "preparando_a_capa": "Preparing the cover...",
    "remova_esse_arquivo_da_selecao_e_tente": "Remove that file from the selection and try again.",
    "sequencia": "sequence",
    "o_arquivo_pode_estar_incompleto_tente": "The file may be incomplete. Try downloading it again.",
    "conferindo_se_o_audio_pode_ser_reprodu": "Checking whether the audio can be played...",
    "conferindo_se_o_video_pode_ser_reprodu": "Checking whether the video can be played...",
    "lendo_titulo_capitulos_e_capa": "Reading title, chapters and cover...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "The file may be damaged or in an audio format the browser can't play. Try converting it to MP3 or M4B (AAC).",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "The file may be damaged or in a video format the browser can't play. Try converting it to MP4 with H.264 video and AAC audio.",
    "converta_o_audiolivro_para_m4b_com_aud": "Convert the audiobook to M4B with AAC audio (or to MP3) and import it again.",
    "converta_o_video_para_mp4_com_audio_aa": "Convert the video to MP4 with AAC audio and H.264 video and import it again.",
    "o_navegador_nao_reproduz_o_formato_de": "The browser will not play this file's audio format.",
    "arquivos_com_protecao_nao_podem_ser_re": "Protected files cannot be played here. Use a DRM-free copy.",
    "nao_ha_espaco_suficiente_no_aparelho_p": "There is not enough room on your device for this audiobook.",
    "confira_se_a_extensao_corresponde_ao_c_2": "Check that the extension matches the contents, or convert the audio to MP3 or M4B (AAC).",
    "imagem_invalida": "invalid image",
    "imagem_demorou_demais": "the image took too long to load",
    "imagem_vazia": "empty image",
    "inicio": "Start",
    "mp4_moov_nao_encontrado": "The video seems to be incomplete or damaged.",
    "pagina": "Page",
    "esta_pagina_nao_esta_disponivel": "This page is not available.",
    "esta_pagina_nao_pode_ser_descompactada": "This page could not be unpacked.",
    "quadrinho_fechado": "Comic closed.",
    "ele_pode_estar_incompleto_dividido_em": "It may be incomplete, split into several parts, or in a RAR variant the app does not recognise. Converting it to CBZ usually fixes it.",
    "remova_a_senha_do_arquivo_e_importe_de": "Remove the password from the file and import it again.",
    "nao_foi_possivel_ler_este_arquivo_de_q": "This comic file could not be read.",
    "este_quadrinho_esta_protegido_por_senh": "This comic is password protected.",
    "lendo_o_indice_do_quadrinho": "Reading the comic's index...",
    "o_arquivo_pode_ser_grande_demais_para": "The file may be too large for this device's memory. Splitting the comic into smaller parts usually fixes it.",
    "nao_foi_possivel_abrir_este_quadrinho": "This comic could not be opened.",
    "lendo_o_arquivo": "Reading the file...",
    "preparando_o_leitor_de_cbr": "Preparing the CBR reader...",
    "o_arquivo_pode_estar_incompleto_proteg": "The file may be incomplete, password protected or damaged.",
    "nao_foi_possivel_ler_este_quadrinho": "This comic could not be read.",
    "o_arquivo_precisa_conter_imagens_jpg_p": "The file needs to contain images (JPG, PNG, WEBP or GIF).",
    "nao_encontramos_paginas_dentro_deste_q": "We found no pages inside this comic.",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "There is not enough room on your device for this comic.",
    "cabecalho_de_item_invalido": "Part of the file is damaged.",
    "a_pasta_vendor_libarchive_precisa_esta": "A component the app needs to open this comic is missing. Convert it to CBZ or reinstall the app.",
    "o_leitor_de_cbr_nao_foi_encontrado": "The CBR reader was not found.",
    "converta_o_quadrinho_para_cbz_zip_e_im": "Convert the comic to CBZ (ZIP) and import it again.",
    "este_navegador_nao_consegue_abrir_arqu": "This browser cannot open CBR files.",
    "convertendo_o_markdown": "Converting the Markdown",
    "lendo_o_texto": "Reading the text",
    "pdf_indisponivel": "PDF unavailable.",
    "epub_invalido_nenhum_capitulo_no_spine": "This EPUB is damaged: the book's chapters could not be found.",
    "livro_sem_titulo": "Untitled Book",
    "epub_invalido_arquivo_opf_nao_encontra": "This EPUB is incomplete or damaged and cannot be opened.",
    "epub_invalido_container_xml_nao_encont": "This EPUB is incomplete or damaged and cannot be opened.",
    "organizando_o_texto": "Laying out the text",
    "descompactando_o_livro": "Unpacking the book",
    "nao_encontramos_conteudo_para_exibir_n": "We found nothing to show in this file.",
    "livro_sem_texto_legivel": "Book with no readable text",
    "o_arquivo_pode_estar_corrompido_tente": "The file may be damaged. Try converting it to EPUB.",
    "nao_foi_possivel_extrair_o_texto_deste": "The text could not be pulled out of this MOBI.",
    "nenhum_registro_de_conteudo_foi_encont": "The book's text could not be found in this file.",
    "arquivo_mobi_sem_texto": "MOBI file with no text.",
    "o_dicionario_de_compressao_esta_vazio": "Part of this MOBI's content is missing.",
    "arquivo_mobi_incompleto": "Incomplete MOBI file.",
    "as_tabelas_de_compressao_nao_foram_enc": "Part of this MOBI's content is missing.",
    "converta_o_arquivo_para_epub_em_um_pro": "Convert the file to EPUB in a program such as Calibre and import it again.",
    "compressao_mobi_nao_reconhecida": "This MOBI uses an internal format the app doesn't recognise.",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "The book's header could not be read.",
    "arquivo_mobi_corrompido": "Damaged MOBI file.",
    "a_lista_interna_de_registros_esta_inco": "The file is incomplete. Try downloading or converting it again.",
    "o_download_parece_ter_sido_interrompid": "The download looks like it was interrupted. Download the file again.",
    "tabela_de_compressao_mobi_corrompida": "Part of this MOBI file is damaged.",
    "tabela_de_compressao_mobi_incompleta": "This MOBI file is incomplete.",
    "tabela_de_compressao_mobi_invalida": "Part of this MOBI file is damaged.",
    "este_arquivo_docx_nao_tem_conteudo_de": "This .docx file has no text content that can be shown.",
    "documento_sem_texto": "Document with no text",
    "o_arquivo_pode_estar_corrompido_proteg": "The file may be damaged, password protected, or an old .doc. Save it again as .docx and import it once more.",
    "nao_foi_possivel_ler_este_arquivo_docx": "This DOCX file could not be read.",
    "convertendo_o_documento": "Converting the document",
    "conecte_se_a_internet_uma_vez_para_bai": "Go online once to download the component, then open the book again.",
    "o_conversor_de_docx_nao_carregou": "The DOCX converter did not load.",
    "video_mp4": "Video (MP4)",
    "audiolivro_m4b": "Audiobook (M4B)",
    "audiolivro_mp3": "Audiobook (MP3)",
    "quadrinho_cbt": "Comic (CBT)",
    "quadrinho_cb7": "Comic (CB7)",
    "quadrinho_cbr": "Comic (CBR)",
    "quadrinho_cbz": "Comic (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "Text (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "Saving cancelled.",
    "o_arquivo_esta_vindo_do_armazenamento": "The file is coming down from cloud storage to your device.",
    "baixando_o_arquivo": "Downloading the file",
    "cancelando": "Cancelling...",
    "use_grifar_citacao_anotar_ou_marcador": "Use Highlight, Quote, Note or Bookmark while you read.",
    "nenhuma_marcacao_ainda": "No marks yet",
    "trecho_original": "Original passage",
    "procurar_meus_livros": "Find my books",
    "a_busca_fica_sempre_disponivel_no_menu": "The search is always there in the side menu, under System.",
    "da_para_fazer_depois": "You can do this later",
    "nada_entra_na_estante_sem_a_sua_confir": "Nothing reaches your shelf without your say-so: you see the list and tick what you want to import.",
    "voce_revisa_antes": "You review first",
    "escolha_uma_pasta_downloads_e_um_bom_c": "Pick a folder (Downloads is a good start) and the app searches it and every subfolder.",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "Searches for EPUB, MOBI, CBZ, CBR and M4B",
    "voltar_e_revisar": "Go back and review",
    "ler_os_termos": "Read the terms",
    "ler_a_politica": "Read the policy",
    "os_dois_documentos_ficam_sempre_dispon": "Both documents are always there in the side menu, under About.",
    "leia_com_calma": "Take your time",
    "a_politica_e_os_termos_explicam_como_o": "The policy and the terms explain how the app keeps your books and what you may do with them. You'll need to agree to them to use the library.",
    "nada_acontece_sem_o_aceite": "To get started, please accept the terms",
    "aceitar_e_continuar": "Accept and continue",
    "nao_aceito": "I do not accept",
    "termos_de_uso_2": "Terms of Use",
    "politica_de_privacidade_2": "Privacy Policy",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "The app only touches the files and folders you choose, when you choose them.",
    "voce_no_controle": "You are in control",
    "depois_de_importar_um_livro_voce_le_se": "Once a book is imported, you read it without internet.",
    "funciona_offline": "Works offline",
    "livros_marcacoes_e_progresso_sao_guard": "Books, marks and progress are kept on your device. Nothing is sent to our servers or anyone else's.",
    "tudo_fica_no_seu_aparelho": "Everything stays on your device",
    "escolha_o_que_deseja_adicionar_a_bibli": "Choose what you want to add to the library. Files identical to ones already on your shelf are skipped on their own.",
    "voce_pode_tentar_outra_pasta_ou_import": "You can try another folder, or import files with the + button.",
    "a_leitura_acontece_so_no_seu_dispositi": "Reading happens on your device only.",
    "voce_escolhe_a_pasta": "You pick the folder",
    "tema_tipografia_margens_modo_de_virada": "Theme, typeface, margins, page-turn style and audio settings.",
    "restaurar_minhas_preferencias": "Restore my preferences",
    "o_backup_manda_as_marcacoes_atuais_dos": "The backup wins. The current marks of any book in the file will be replaced by the ones from the backup.",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "Nothing is erased. Marks from both sides are added together and the more recent progress wins.",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "What to do with what is already on your shelf",
    "grifos_citacoes_e_notas": "highlights, quotes and notes",
    "preparando_o_arquivo_2": "Preparing the file...",
    "os_livros_em_si_nem_as_capas_por_isso": "Neither the books themselves nor the covers — which is why the file is only a few KB. Whoever receives it needs the book files for the marks to land back in place, and the covers come back automatically when the books are imported.",
    "nao_vai_no_arquivo": "Not in the file",
    "o_seu_progresso_de_leitura_os_grifos_a": "Your reading progress, your highlights, your quotes, your notes, your bookmarks and how your shelf is organized — status, favorites, collections, series and tags.",
    "vai_no_arquivo": "In the file",
    "descartar_o_que_esta_esperando_2": "Delete pending data",
    "esperando_o_arquivo": "Waiting for the file",
    "avisar_quando_fizer_tempo_sem_backup": "Remind me when it has been a while without a backup",
    "livros_que_ainda_nao_estiverem_na_esta": "Books not yet on your shelf are kept on hold: once you import their file, the marks come back automatically.",
    "restaurar_backup": "Restore backup",
    "salvar_backup": "Save backup",
    "ainda_nao_ha_itens": "Nothing here yet",
    "arraste_um_livro_para_outra_posicao_na": "Drag a book somewhere else on the shelf to save an order of your own. That manual order then takes priority over grouping by author.",
    "separe_por_virgulas": "Separate with commas",
    "ex_estudos_ficcao": "e.g. Studies, Fiction...",
    "pasta_estante": "Folder / shelf",
    "ex_trilogia": "e.g. Trilogy...",
    "serie": "Series",
    "aparece_em_favoritos": "Appears in Favorites.",
    "nome_do_livro": "Book name",
    "nenhum_registro_ainda": "Nothing recorded yet",
    "no_leitor_toque_no_icone_de_marcador_p": "In the reader, tap the bookmark icon to save the page.",
    "nenhum_marcador_ainda": "No bookmarks yet",
    "a_gravacao_e_independente_da_localizac": "Saving is independent of where the PDF lives and does not change the original file.",
    "o_pdf_original_nao_precisa_estar_nessa": "The original PDF does not have to be in that folder",
    "excluir_da_biblioteca": "Delete from library",
    "adicionar_livro": "Add book",
    "adicione_livros_e_acompanhe_o_que_esta": "Add books and keep track of what is waiting, what is under way and how far you have got.",
    "tudo_pronto_para_a_proxima_leitura": "All set for your next read.",
    "sua_biblioteca": "Your library",
    "arraste_um_livro_para_reposiciona_lo_a": "Drag a book to move it: the shelf switches to My Order and keeps the sequence.",
    "importe_um_livro_ou_ajuste_seus_filtro": "Import a book, or adjust your filters.",
    "nada_por_aqui_ainda": "Nothing here yet",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "Tap + and pick MP3, M4B or MP4 files. Several chapter MP3s can become a single audiobook.",
    "nada_para_ouvir_ou_assistir_ainda": "Nothing to listen to or watch yet",
    "o_pdf_original_permanece_intacto_na_pa": "The original PDF stays untouched in your own folder.",
    "paginas_como_imagem": "Pages as images",
    "paginas_do_pdf": "PDF pages",
    "em_navegadores_sem_suporte_a_acesso_di": "In browsers without direct file system access, the EPUB will be downloaded instead.",
    "essa_permissao_e_dada_somente_a_esta_a": "That permission is given to this app alone and keeps the original file from being changed.",
    "selecione_a_pasta_que_contem_o_pdf": "Select the folder that holds the PDF",
    "preparando": "Getting ready…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "The file is being read and rebuilt. Large books may take a moment.",
    "revistas_apostilas_complexas_formulari": "Magazines, complex workbooks, forms, documents with many tables or scanned PDFs may lose part of their original layout.",
    "funcionalidade_indicada_apenas_para_li": "Meant for books",
    "o_epub_e_melhor_para_livros_com_texto": "EPUB is better for books with selectable text, because it lets you adjust the typeface, size, margins and reading mode.",
    "trecho_selecionado": "Selected passage",
    "trecho_comentado": "Passage with a comment",
    "aplicando_zoom": "Zooming...",
    "nao_foi_possivel_carregar_esta_pagina": "This page could not be loaded.",
    "nomear_marcador": "Name bookmark",
    "toque_em_marcar_agora_para_guardar_est": "Tap “Mark now” to save this spot and come back to it whenever you like.",
    "timer_ativo": "Timer on",
    "trecho_ausente_ou_corrompido_no_arquiv": "[Passage missing or damaged in the original file]",
    "novos_livros_vao_abrir_em_leitura_v": "New books will open in {v} reading.",
    "leitura_efetivo_aplicada_a_este_livro": "{efetivo} reading applied to this book.",
    "automatico_neste_livro_leitura_efetivo": "Automatic for this book: {efetivo} reading.",
    "agora_esta_em_efetivo_no_automatico_fo": "Now set to {efetivo}; on automatic, {format} opens in {padrao}.",
    "esta_escolha_vale_so_para_v_cada_livro": "This choice applies to “{v}” only. Each book keeps its own scrolling direction.",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} are not on your shelf yet.",
    "escolha_uma_pasta_para_procurar_label": "Choose a folder to search for {label}.",
    "subtitle_versao_build": "{subtitle} · version {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "Could not read {path}; using the built-in text.",
    "seu_ultimo_backup_foi_ha_dias_dias": "Your last backup was {dias} days ago",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "{aguardando} book from the backup is not here yet. Its progress and marks were kept: as soon as you import the file, everything falls back into place automatically.",
      "other": "{aguardando} books from the backup are not here yet. Their progress and marks were kept: as soon as you import each file, everything falls back into place automatically."
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "{atualizados} book on your shelf was updated.",
      "other": "{atualizados} books on your shelf were updated."
    },
    "criado_em_quando": "Created on {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "Backup ready: {livros} books and {marcacoes} marks.",
    "endereco_seguro_seguro": "secure address: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "Progress and {marcas} mark restored for this book.",
      "other": "Progress and {marcas} marks restored for this book."
    },
    "restaurando_v_de_length": "Restoring ({v} of {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} books · {marcacoes} marks",
    "criado_em_v": "Created on {v}",
    "reunindo_a_sua_estante_v_de_length": "Gathering your shelf ({v} of {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "“{titulo}” was imported before and is still in your library. No new copy was made.",
    "length_arquivos_de_audio": "{length} audio files...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "{falhas} file could not be read.",
      "other": "{falhas} files could not be read."
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} were already in the library and were skipped.",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "{importados} book added to your shelf.",
      "other": "{importados} books added to your shelf."
    },
    "epub_salvo_em_filename": "EPUB saved to {fileName}.",
    "falha_ao_converter_o_pdf_v": "Could not convert the PDF: {v}",
    "pagina_page_de_totalpages": "Page {page} of {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} page",
      "other": "{totalPages} pages"
    },
    "length_resultado_s_para_search": {
      "one": "{length} result for “{search}”",
      "other": "{length} results for “{search}”"
    },
    "capitulo_v": "Chapter {v}",
    "organizando_capitulo_v_de_totalchapter": "Laying out chapter {v} of {totalChapters}",
    "pagina_v": "Page {v}",
    "paginas_v_v2": "Pages {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} page ready",
      "other": "{length} pages ready"
    },
    "montando_as_paginas_pagessofar_prontas": "Building the pages — {pagesSoFar} done",
    "lendo_pagina_v_de_length": "Reading page {v} of {length}",
    "marcador_salvo_em_t": "Bookmark saved at {t}.",
    "o_audio_vai_pausar_em_minutes_minutos": "The audio will pause in {minutes} minutes.",
    "length_capitulos_toque_para_ir_direto": "{length} chapters · tap to jump straight there.",
    "narrado_por_narrator": "Narrated by {narrator}",
    "velocidade_de_reproducao_rate": "Playback speed: {rate}",
    "avancar_f_segundos": "Forward {f} seconds",
    "nao_foi_possivel_abrir_este_v": "This {v} could not be opened.",
    "nao_foi_possivel_ler_o_arquivo_de_v": "The {v} file could not be read.",
    "o_v_esta_danificado_neste_ponto": "The {v} is damaged at this point.",
    "o_navegador_nao_consegue_reproduzir_es": "The browser cannot play this {v} file.",
    "nao_foi_possivel_reproduzir_este_v": "This {v} could not be played.",
    "os_dados_deste_noun_estao_incompletos": "This {noun}'s data is incomplete.",
    "importe_o_arquivo_novamente_para_conti_2": "Import the file again to carry on {v}.",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "This {noun}'s file is no longer saved on your device.",
    "nao_foi_possivel_descobrir_a_duracao_d": "Could not work out the length of “{name}”.",
    "lendo_faixa_v_de_length": "Reading track {v} of {length}...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "Could not work out the length of this {v}.",
    "este_format_nao_pode_ser_reproduzido_n": "This {format} cannot be played in this browser.",
    "este_format_esta_protegido_por_drm": "This {format} is protected by DRM.",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "The file is {bytes} and about {v} is left. Free up space or delete books from the library.",
    "este_arquivo_nao_e_um_format_valido": "This file is not a valid {format}.",
    "preparando_as_paginas_vistas_de_total": "Preparing the pages ({vistas} of {total})...",
    "preparando_total_pagina_s": {
      "one": "Preparing {total} page...",
      "other": "Preparing {total} pages..."
    },
    "preparando_as_paginas_v_de_total": "Preparing the pages ({v} of {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "It takes about {bytes} and roughly {v} is left. Free up space or delete books from the library.",
    "envio_direto_exige_endereco_seguro": "Sending straight to another app isn't available because this page wasn't opened from a secure address. Save the file and send it with any app you like.",
    "na_estante": "on the shelf",
    "nao_foi_possivel_montar_o_arquivo": "The file could not be built.",
    "este_navegador_nao_oferece_o_envio_dir": "This browser does not offer sending straight to another app. Save the file and attach it through whichever app you prefer.",
    "voce_ainda_nao_fez_nenhum_backup": "You have not made a backup yet.",
    "converter_para_epub": "Convert to EPUB",
    "esta_pagina_nao_pode_ser_exibida": "This page could not be shown.",
    "na_ordem_em_que_serao_tocados": "In the order they will play",
    "este_capitulo_nao_pode_ser_exibido": "This chapter could not be shown.",
    "livro": "Book",
    "restantes": " left",
    "como_seus_dados_sao_tratados": "How your data is handled",
    "condicoes_de_uso_do_aplicativo": "Conditions for using the app",
    "audiolivro": "audiobook",
    "sobre_o_aplicativo": "About the app",
    "o_que_e_o_veredas_reader": "What Veredas Reader is",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(this device doesn't support sharing this file type)",
    "livros": "books",
    "lendo": "reading",
    "lidos": "finished",
    "compartilhar_livro": "Share book",
    "n_livros": {
      "one": "{n} book",
      "other": "{n} books"
    },
    "livros_unidade": {
      "one": "book",
      "other": "books"
    },
    "uma_faixa_discreta_depois_de_n_dias": "A quiet strip on the shelf after {n} days without a backup. It never interrupts your reading.",
    "scanned_arquivos_verificados_livros_enc": "{scanned} files checked · {encontrados} books found",
    "v_de_total": "{v} of {total}",
    "voltar_n_segundos": "Back {n} seconds",
    "cancelado": "Cancelled",
    "arquivo": "File",
    "outro": "Other",
    "outros": "Others",
    "audiolivro_2": "Audiobook",
    "pausar": "Pause",
    "marcador": "Bookmark",
    "leitura": "Reading",
    "grifo": "Highlight",
    "editar": "Edit",
    "apagar": "Delete",
    "concluir": "Finish",
    "recentes": "Recent",
    "progresso": "Progress",
    "entendi": "Got it",
    "aviso": "Notice",
    "descartar": "Delete",
    "copiado": "Copied",
    "restaurar": "Restore",
    "restaurando": "Restoring",
    "excluir": "Delete",
    "grifos": "Highlights",
    "arquivo_vazio": "Empty file.",
    "e_mais_n_arquivos": {
      "one": "and {n} more file, in the order they will play",
      "other": "and {n} more files, in the order they will play"
    },
    "n_arquivos_mp3": {
      "one": "{n} MP3 file",
      "other": "{n} MP3 files"
    },
    "pct_restam": "{pct}% · {tempo} left",
    "n_minutos": {
      "one": "{n} minute",
      "other": "{n} minutes"
    },
    "ir_para_tempo": "Go to {tempo}",
    "nomear": "Rename",
    "parte_n": "Part {n}",
    "carregando_pagina_n": "Loading page {n}...",
    "selecionar_pasta_e_continuar": "Select folder and continue",
    "ler_agora": "Read now",
    "agrupamento_v": "Grouping: {v}.",
    "tempo_restante": "{tempo} left",
    "abrir_titulo": "Open {titulo}",
    "continuar_lendo_titulo": "Continue reading {titulo}",
    "continuar_ouvindo_titulo": "Continue listening to {titulo}",
    "continuar_assistindo_titulo": "Continue watching {titulo}",
    "lido": "Finished",
    "pausado": "Paused",
    "status": "Status",
    "favorito": "Favorite",
    "escolher_local": "Choose location",
    "epub_baixado_como": "EPUB downloaded as {nome}.",
    "ouvir_a_partir_de": "listen from {tempo}",
    "assistir_a_partir_de": "watch from {tempo}",
    "pagina_n_minuscula": "page {n}",
    "selecione_trecho_para_criar": "Select a passage while reading to create {oque}.",
    "excluir_oque_pergunta": "Delete {oque}?",
    "excluir_oque": "Delete {oque}",
    "excluir_item_pergunta": "Delete this item?",
    "use_organizar_para_criar": "Use “{botao}” on a book to create {oque}.",
    "n_arquivos_processados": {
      "one": "{n} file processed",
      "other": "{n} files processed"
    },
    "voce_ja_tem_titulo_de_autor": "You already have “{titulo}” by {autor} in your library, although the file is different. Import it anyway?",
    "voce_ja_tem_titulo": "You already have “{titulo}” in your library, although the file is different. Import it anyway?",
    "marcadores_unidade": {
      "one": "bookmark",
      "other": "bookmarks"
    },
    "ultimo_backup_em": "Last backup on <strong>{data}</strong>.",
    "guardar": "Save",
    "lembretes": "Reminders",
    "juntar": "Merge",
    "recomendado": "recommended",
    "substituir": "Replace",
    "n_capas_recuperadas": {
      "one": "{n} cover recovered.",
      "other": "{n} covers recovered."
    },
    "nao_encontramos_arquivos_tipo": "We found no {tipo} files in this folder.",
    "tentar_outra_pasta": "Try another folder",
    "n_livros_encontrados": {
      "one": "{n} book found",
      "other": "{n} books found"
    },
    "n_de_total_selecionados": {
      "one": "{n} of {total} selected",
      "other": "{n} of {total} selected"
    },
    "importar": "Import",
    "importar_n": "Import {n}",
    "aceite_frase": "I have read and accept the Veredas Reader {politica} and {termos}.",
    "pdf_preservado": "The original PDF <strong>will not be deleted from your own folder</strong>. Only the library copy of this PDF will be removed, and only after the EPUB has been saved successfully.",
    "gravar_epub_mesma_pasta": "To save the EPUB <strong>in the same folder as the PDF</strong>, the browser needs permission to reach that folder.",
    "epub_pronto_qualquer_pasta": "The EPUB is converted. Now you can choose <strong>any folder on the computer</strong> to save the file.",
    "backup_explicacao": "The original backup is a ZIP or TXT file. When you receive it on another device, import it through <strong>Restore backup</strong>: Veredas recognizes the contents and restores it normally. The file holds your progress, your highlights, your quotes, your notes, your bookmarks and how your shelf is organized — <strong>not the books themselves</strong>, nor the covers.",
    "lembretes_desligados_frase": "Reminders are <strong>off</strong>. Remember to back up every now and then.",
    "backup_salvo_nos_downloads": "<strong>The backup file was saved on this device</strong>, in your downloads. You can send it right now: open WhatsApp, email, Drive or whatever you like, tap attach and pick the file.",
    "arquivo_pronto_tamanho": "File ready — <strong>{tamanho}</strong>.",
    "scan_intro_frase": "The app can look for books in <strong>EPUB</strong> and <strong>MOBI</strong>, comics in <strong>CBZ</strong> and <strong>CBR</strong> and audiobooks in <strong>M4B</strong> inside a folder on your device, subfolders included.",
    "scan_intro_auto_frase": "To fill your shelf quickly, the app can look for books in <strong>EPUB</strong> and <strong>MOBI</strong>, comics in <strong>CBZ</strong> and <strong>CBR</strong> and audiobooks in <strong>M4B</strong> inside a folder on your device, subfolders included.",
    "n_livros_aguardando": {
      "one": "<strong>{n} book</strong> with progress and marks kept, waiting to be imported again.",
      "other": "<strong>{n} books</strong> with progress and marks kept, waiting to be imported again."
    },
    "fora_da_busca_titulo": "We don’t automatically import PDF, TXT, DOCX (Word), MD, MP3 or MP4 files",
    "fora_da_busca_texto": "These formats are used for all kinds of documents, not just books. Leaving them out keeps your shelf organized. <strong>You can import each one yourself with the + button.</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "Your local library",
    "biblioteca": "Library",
    "organizacao": "Organization",
    "minhas_marcacoes": "My marks",
    "sistema": "System",
    "sua_biblioteca": "Your Library",
    "toque_em_um_livro_para_comecar_a_ler": "Tap a book to start reading.",
    "agrupar": "Group",
    "sua_estante_nao_tem_copia_de_seguranca": "Your shelf has no backup",
    "se_este_aparelho_se_perder_o_progresso": "If something happens to this device, your progress and marks could be lost.",
    "agora_nao": "Not now",
    "nao_avisar_mais": "Stop reminding me",
    "carregando": "Loading...",
    "estante": "Shelf",
    "lendo": "Reading",
    "favoritos": "Favorites",
    "marcas": "Marks",
    "mais": "More",
    "neste_capitulo": "This chapter",
    "velocidade": "Speed",
    "timer": "Timer",
    "marcar": "Mark",
    "marcadores": "Bookmarks",
    "personalizar_leitura": "Reading preferences",
    "as_preferencias_ficam_salvas_para_as_p": "Your preferences are kept for future reading sessions.",
    "tema": "Theme",
    "claro": "Light",
    "sepia": "Sepia",
    "escuro": "Dark",
    "oceano": "Ocean",
    "tipografia": "Typeface",
    "texto": "Text",
    "tamanho": "Size",
    "espacamento": "Line spacing",
    "margens": "Margins",
    "cores_personalizadas_opcional": "Custom colors (optional)",
    "fundo": "Background",
    "fonte": "Text color",
    "brilho": "Brightness",
    "orientacao": "Orientation",
    "auto": "Auto",
    "retrato": "Portrait",
    "paisagem": "Landscape",
    "modo_de_leitura": "Reading mode",
    "automatico": "Automatic",
    "horizontal": "Horizontal",
    "vertical": "Vertical",
    "automatico_usa_rolagem_horizontal_para": "Automatic uses horizontal paging for EPUB, MOBI, TXT and MD, and vertical scrolling for PDF and DOCX. If you change it while reading, the change is kept for that book only.",
    "quadrinhos": "Comics",
    "como_a_pagina_aparece": "How the page fits",
    "pagina_inteira": "Whole page",
    "largura_da_tela": "Screen width",
    "sentido_da_leitura": "Reading direction",
    "normal": "Normal →",
    "manga": "← Manga",
    "revista_aberta_na_horizontal": "Two-page spread in landscape",
    "com_o_aparelho_deitado_mostra_duas_pag": "Held sideways, it shows two pages side by side — the cover stands alone, the way a real comic opens.",
    "normal_vira_da_esquerda_para_a_direita": "Normal turns left to right. Manga reverses everything: the swipe, the edge taps and the order of the two pages in a spread.",
    "gire_o_aparelho_para_a_horizontal_para": "Turn the device sideways to see two pages at once.",
    "dois_toques_ampliam_no_ponto_tocado_co": "Double-tap to zoom where you tapped; once zoomed, drag to move around the page. Pinching with two fingers works too.",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "The scrolling button at the top of the reader switches between page-by-page and continuous scrolling (webtoon style). In continuous scrolling the pages run into one another, and zooming widens the page: you move across it by scrolling sideways.",
    "virada_de_pagina": "Page turn",
    "folha_real": "Real paper",
    "deslizar": "Slide",
    "sem_animacao": "No animation",
    "na_leitura_horizontal_arraste_a_pagina": "In horizontal reading, drag the page from its edge to fold it with your finger. Let go halfway to call the turn off.",
    "ouvir_leitura": "Listen",
    "continue_de_onde_parou_no_seu_ritmo": "Pick up where you left off, at your own pace.",
    "livro": "Book",
    "pronto_para_comecar": "Ready to start",
    "voz": "Voice",
    "escolha_uma_voz_disponivel_no_disposit": "Choose a voice available on this device",
    "voz_padrao_do_sistema": "System default voice",
    "durante_a_reproducao": "While playing",
    "a_leitura_avanca_pagina_a_pagina_os_co": "Reading moves page by page. System controls appear when the browser supports them.",
    "organizar_livro": "Organize book",
    "estantes_colecoes_tags_e_status": "Shelves, collections, tags and status.",
    "cancelar": "Cancel",
    "salvar": "Save",
    "grifos_citacoes_notas_e_marcadores_des": "Highlights, quotes, notes and bookmarks from this book.",
    "sumario": "Contents",
    "toque_em_um_capitulo_para_ir_direto_ao": "Tap a chapter to jump straight there.",
    "sua_anotacao": "Your note",
    "edite_ou_adicione_comentarios_ao_seu_t": "Edit or add comments to your passage.",
    "trecho": "Passage",
    "sua_nota": "Your note",
    "salvar_nota": "Save note",
    "agrupar_biblioteca": "Group library",
    "escolha_como_os_livros_serao_organizad": "Choose how books are arranged on the shelf.",
    "ao_arrastar_um_livro_para_outra_posica": "When you drag a book somewhere else, the shelf automatically switches to My Order and keeps the sequence you built.",
    "backup_e_restauracao": "Backup and restore",
    "sua_estante_seu_progresso_e_suas_marca": "Your shelf, your progress and your marks in a single file.",
    "escolha_uma_dimensao_para_explorar_sua": "Pick a way to explore your library.",
    "capitulos": "Chapters",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "The voice keeps its pitch. This applies to this book and the next ones.",
    "ajuste_fino": "Fine tuning",
    "timer_de_sono": "Sleep timer",
    "o_audio_diminui_de_volume_aos_poucos_e": "The audio fades out gradually and pauses automatically.",
    "pontos_que_voce_guardou_neste_audioliv": "Spots you saved in this audiobook.",
    "ajustes_do_audio": "Audio settings",
    "as_preferencias_ficam_salvas_para_todo": "These preferences are kept for every audiobook.",
    "botao_de_voltar": "Rewind button",
    "botao_de_avancar": "Forward button",
    "recuar_ao_retomar": "Rewind on resume",
    "depois_de_uma_pausa_longa_volta_alguns": "After a long pause, it goes back a few seconds so you can pick up the thread.",
    "tocar_ao_abrir": "Play on open",
    "ao_tocar_em_um_audiolivro_na_estante_a": "Tapping an audiobook on the shelf starts playback right away.",
    "no_computador_espaco_toca_e_pausa_pula": "On a computer: space plays and pauses · ← → skip · Shift + ← → change chapter · ↑ ↓ volume · B bookmarks · [ ] speed.",
    "converter_pdf_para_epub": "Convert PDF to EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "Prepare the book for flowing, adjustable reading.",
    "confirmacao": "Confirm",
    "confirmar": "Confirm",
    "processando": "Working",
    "documento": "Document",
    "buscar_livros_no_dispositivo": "Find books on this device",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "Find EPUB, MOBI, CBZ, CBR and M4B files already saved on your device.",
    "juntar_em_um_unico_audiolivro": "Join into a single audiobook?",
    "titulo": "Title",
    "autor": "Author",
    "importar_separados": "Import separately",
    "bem_vindo_ao_veredas_reader": "Welcome to Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "Your reading library, entirely on your own device.",
    "buscar": "Search",
    "importar_livro": "Import book",
    "buscar_titulo_autor_tag": "Search title, author, tag...",
    "fechar_busca": "Close search",
    "navegacao_da_biblioteca": "Library navigation",
    "fechar_menu": "Close menu",
    "agrupar_livros": "Group books",
    "voltar": "Back",
    "marcar_pagina": "Bookmark page",
    "personalizar": "Preferences",
    "navegacao_principal": "Main navigation",
    "acoes_do_trecho": "Passage actions",
    "amarelo": "Yellow",
    "verde": "Green",
    "rosa": "Pink",
    "azul": "Blue",
    "player_de_audiolivro": "Audiobook player",
    "minimizar_player": "Minimize player",
    "minimizar": "Minimize",
    "video_em_reproducao": "Video playing",
    "abrir_a_lista_de_capitulos": "Open the chapter list",
    "posicao_no_audio": "Position in audio",
    "alternar_entre_o_progresso_do_capitulo": "Switch between chapter progress and whole-book progress",
    "capitulo_anterior": "Previous chapter",
    "voltar_15_segundos": "Back 15 seconds",
    "reproduzir": "Play",
    "avancar_30_segundos": "Forward 30 seconds",
    "proximo_capitulo": "Next chapter",
    "velocidade_de_reproducao": "Playback speed",
    "marcar_este_ponto": "Bookmark this spot",
    "ver_marcadores": "See bookmarks",
    "silenciar": "Mute",
    "volume": "Volume",
    "audiolivro_em_reproducao": "Audiobook playing",
    "abrir_o_player": "Open the player",
    "fechar_o_player": "Close the player",
    "fechar": "Close",
    "trecho_anterior": "Previous passage",
    "iniciar_leitura": "Start reading aloud",
    "proximo_trecho": "Next passage",
    "escreva_seu_comentario_interpretacao_o": "Write your comment, reading or reminder...",
    "cancelar_importacao": "Cancel import",
    "nome_do_audiolivro": "Audiobook name",
    "nome_do_autor": "Author name",
    "idioma": "Language",
    "idioma_do_aplicativo": "App language",
    "o_aplicativo_segue_o_idioma_do_apare": "The app follows your device's language. If yours isn't here yet, it opens in English.",
    "seguir_o_aparelho": "Follow the device",
    "fazer_backup": "Back up now",
    "todos": "All",
    "lidos": "Finished",
    "pausados": "Paused",
    "autores": "Authors",
    "tags": "Tags",
    "grifar": "Highlight",
    "anotar": "Note",
    "enviar": "Send",
    "restaurar_padroes": "Restore defaults",
    "voltar_para_1": "Back to 1×",
    "marcar_agora": "Mark now",
    "escolher_pasta": "Choose folder",
    "juntar_em_um_audiolivro": "Join into one audiobook",
    "sobre": "About",
    "licencas_de_codigo_aberto": "Open-source licenses",
    "configuracoes": "Settings",
    "temas_e_idioma": "Themes and language"
  },
  "aviso": {
    "idioma_trocado": "Language changed."
  },
  "vn": {
    "quem_le": "Who reads",
    "natural": "Natural",
    "do_sistema": "System",
    "nota_sistema": "Uses the voices installed on your device. For a more human-sounding reading, choose Natural.",
    "nota_sistema_com_natural": "The natural voice is still downloaded. Switch back to Natural any time.",
    "voz_natural": "Natural voice",
    "gerada_no_aparelho": "A far more human voice, created right on your device.",
    "progresso_download": "Download progress",
    "x_de_y": "{x} of {y}",
    "aviso_arquivo": "The natural voice needs Veredas to be opened from the app’s address, not as a file on your computer. Until then, reading uses the system voice.",
    "aviso_navegador": "This browser lacks the features the natural voice needs. Reading continues with the system voice.",
    "verificando": "Checking the natural voice…",
    "fato_download": "One-time download of {tamanho}. After that, it works offline.",
    "fato_wifi": "Wi-Fi is best. You can pause and resume later.",
    "fato_privacidade": "The book’s text never leaves your device.",
    "fato_idiomas": "Speaks 31 languages, including English, Portuguese and Spanish. Other languages keep using the system voice.",
    "baixar_voz_natural": "Download natural voice ({tamanho})",
    "licenca_curta": "Supertonic 3 model by Supertone, under the OpenRAIL-M license. Details in About > Open-source licenses.",
    "pode_continuar_usando": "You can keep reading while it downloads. If the connection drops, the download resumes where it stopped.",
    "pausar_download": "Pause download",
    "erro_espaco": "Not enough space on the device to finish the download. Free up some space and try again.",
    "erro_offline": "No internet right now. What has already been downloaded is kept.",
    "erro_rede": "The connection dropped during the download. What has already been downloaded is kept.",
    "download_pausado": "Download paused. What has already been downloaded is kept.",
    "continuar_download": "Resume",
    "descartar": "Discard",
    "voz_feminina": "Female",
    "voz_feminina_desc": "Soft and calm",
    "voz_masculina": "Male",
    "voz_masculina_desc": "Warm and serene",
    "parar_amostra": "Stop sample",
    "ouvir_amostra_de": "Play sample: {voz}",
    "escolha_a_voz": "Choose the voice",
    "qualidade": "Quality",
    "q_auto": "Automatic",
    "q_rapida": "Fast",
    "q_maxima": "Best",
    "q_auto_desc": "Adapts to your device’s performance so reading flows without pauses.",
    "q_rapida_desc": "Generates the voice faster. Good for simpler devices.",
    "q_maxima_desc": "The most polished sound. On simpler devices, it may cause pauses between sentences.",
    "ocupa": "Uses {tamanho} on this device",
    "remover": "Remove",
    "baixar_pelos_dados": "Download over mobile data?",
    "baixar_pelos_dados_msg": "Your device doesn’t seem to be on Wi-Fi. The download is {tamanho} and may use up your data plan.",
    "baixar_agora": "Download anyway",
    "pronta": "The natural voice is ready.",
    "download_interrompido": "The download stopped. Tap Resume whenever you like.",
    "remover_titulo": "Remove the natural voice?",
    "descartar_titulo": "Discard the download?",
    "remover_msg": "This frees up {tamanho}. Reading goes back to the system voice, and you can download it again any time.",
    "descartar_msg": "What has already been downloaded will be deleted.",
    "removida": "Natural voice removed from this device.",
    "amostra_falhou": "Couldn’t play the sample on this device.",
    "amostra": "Hello! This is how your books will sound with the natural voice.",
    "gerando_voz": "Preparing the voice…",
    "automatico_idioma": "Automatic ({idioma})",
    "automatico": "Automatic",
    "so_voz_do_sistema": "system voice",
    "aviso_idioma": "Text language: {idioma}. The natural voice doesn’t speak this language yet, so the book will be read by the system voice.",
    "aviso_idioma_desconhecido": "Couldn’t recognize the language of this text. Choose the language below to use the natural voice.",
    "aviso_falha": "The natural voice couldn’t run on this device right now. Reading continues with the system voice.",
    "nao_carregou_usando_sistema": "The natural voice didn’t load on this device. Reading with the system voice.",
    "parou_usando_sistema": "The natural voice stopped. Continuing with the system voice.",
    "aparelho_lento": "This device is generating the voice slowly. Choose Fast quality to avoid pauses.",
    "idioma_do_texto": "Text language",
    "idioma_do_texto_dica": "Recognized from the text itself. Change it if the pronunciation sounds wrong.",
    "leitura_em_voz_alta": "Read aloud",
    "lento_usando_sistema": "The natural voice is too slow on this device. Continuing with the system voice.",
    "aviso_lento": "This device can’t generate the natural voice as fast as it reads, so the system voice has taken over for now.",
    "sem_memoria_usando_sistema": "The natural voice didn’t fit in this device’s memory. Reading with the system voice.",
    "aviso_falha_memoria": "There wasn’t enough memory for the natural voice on this device. Closing other apps and trying again usually helps; meanwhile, reading uses the system voice."
  }
});
