/* ============================================================
   ESPAÑOL — traducción completa
   ------------------------------------------------------------
   Las claves son idénticas a pt-BR.js y en.js.
   ============================================================ */
Idiomas.registrar('es', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "Marcador eliminado.",
    "excluir_marcador": "Eliminar marcador",
    "o_marcador_sera_removido_permanentemen": "El marcador se eliminará definitivamente.",
    "excluir_marcador_2": "¿Eliminar marcador?",
    "pagina_salva": "Página guardada",
    "anotacoes": "Notas",
    "citacoes": "Citas",
    "item_excluido": "Elemento eliminado.",
    "este_registro_sera_removido_permanente": "Esta entrada se eliminará definitivamente de la biblioteca.",
    "configuracoes_padrao_restauradas": "Configuración predeterminada restaurada.",
    "leitura_da_esquerda_para_a_direita": "Lectura de izquierda a derecha.",
    "leitura_da_direita_para_a_esquerda_man": "Lectura de derecha a izquierda (manga).",
    "a_pagina_inteira_passa_a_caber_na_tela": "La página completa cabe ahora en la pantalla.",
    "a_pagina_passa_a_ocupar_toda_a_largura": "La página ahora ocupa todo el ancho de la pantalla.",
    "virada_sem_animacao_ativada": "La página cambia sin animación.",
    "virada_deslizante_ativada": "El cambio de página deslizante está activado.",
    "virada_em_folha_real_ativada": "El cambio de página de hoja real está activado.",
    "padrao_automatico_cada_formato_abre_no": "Automático: cada formato se abre en el sentido que le corresponde.",
    "mudando_durante_a_leitura_o_ajuste_fic": "Si lo cambias mientras lees, el cambio se guarda solo para ese libro.",
    "automatico_usa_rolagem_horizontal_para": "Automático usa paginación horizontal para EPUB, MOBI, TXT, MD y cómics, y desplazamiento vertical para PDF y DOCX.",
    "este_livro": "este libro",
    "armazenamento_local_indisponivel_neste": "El almacenamiento local no está disponible en este navegador.",
    "o_aplicativo_pode_procurar_os_livros_q": "La aplicación puede buscar libros que ya están en tu dispositivo.",
    "vamos_montar_sua_estante": "¿Empezamos a llenar tu estantería?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "Sin tu consentimiento, no se puede usar la aplicación.",
    "precisamos_do_seu_aceite": "Necesitamos tu consentimiento",
    "antes_de_comecar_leia_e_aceite_os_docu": "Antes de empezar, lee y acepta los documentos siguientes.",
    "selecionar_todos": "Seleccionar todo",
    "limpar_selecao": "Borrar selección",
    "todos_parecem_ja_estar_na_sua_estante": "Parece que todos ya están en tu estantería.",
    "lendo_a_pasta_escolhida": "Leyendo la carpeta que elegiste…",
    "procurando_livros": "Buscando libros",
    "nao_foi_possivel_concluir_a_busca_no_d": "No se pudo completar la búsqueda en este dispositivo.",
    "tente_outra_pasta_do_aparelho": "Prueba otra carpeta de tu dispositivo.",
    "nenhum_livro_encontrado": "No se encontraron libros",
    "use_o_botao_para_escolher_os_arquivos": "Usa el botón + para elegir los archivos manualmente. En teléfonos Android, Chrome normalmente permite elegir una carpeta completa.",
    "seu_navegador_nao_permite_ler_pastas": "Tu navegador no puede leer carpetas",
    "busca_automatica_indisponivel": "Búsqueda automática no disponible",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR y M4B",
    "termos_de_uso": "Términos de uso",
    "politica_de_privacidade": "Política de privacidad",
    "um_minuto_agora_evita_perder_o_progres": "Un minuto ahora evita perder después tu progreso y tus marcas.",
    "ver_estante": "Ver estantería",
    "modo_juntar": "Modo combinar",
    "modo_substituir": "Modo reemplazar",
    "restauracao_concluida": "Restauración completada",
    "tente_de_novo_com_o_arquivo_original": "Inténtalo de nuevo con el archivo original.",
    "a_restauracao_nao_pode_ser_concluida": "No se pudo completar la restauración",
    "devolvendo_o_seu_progresso_e_as_suas_m": "Recuperando tu progreso y tus marcas...",
    "restaurar_este_backup": "¿Restaurar esta copia de seguridad?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Elige el .zip guardado por Veredas o el .txt que recibiste mediante el uso compartido.",
    "nao_foi_possivel_ler_este_arquivo": "No se pudo leer este archivo",
    "lendo_o_backup": "Leyendo la copia de seguridad",
    "backup_do_veredas_reader": "Copia de seguridad de Veredas Reader",
    "arquivo_de_transporte_txt_contendo_os": "copia de seguridad en formato .txt, con el mismo contenido que el ZIP",
    "nao_foi_possivel_montar_o_arquivo_de_b": "No se pudo crear el archivo de copia de seguridad.",
    "escolher_o_app": "Elegir aplicación",
    "vale_conferir_o_que_vai_no_arquivo": "Conviene comprobar qué contiene el archivo",
    "enviar_para_outro_app": "Enviar a otra aplicación",
    "salvar_o_arquivo": "Guardar el archivo",
    "o_navegador_aqui_nao_oferece_o_compart": "Este navegador no permite compartir directamente. Puedes guardar el archivo y enviarlo después con la aplicación que quieras.",
    "este_aparelho_nao_abre_a_lista_de_apli": "Este dispositivo no abre la lista de aplicaciones",
    "importe_pelo_menos_um_livro_antes_de_f": "Importa al menos un libro antes de hacer una copia de seguridad.",
    "estante_vazia": "Estantería vacía",
    "nao_deu_para_copiar": "No se pudo copiar",
    "copiar_detalhes": "Copiar detalles",
    "o_backup_foi_salvo_assim_mesmo": "La copia de seguridad se guardó de todos modos",
    "o_aparelho_recusou_abrir_a_lista": "No se pudo abrir la lista para compartir",
    "sem_detalhes_do_navegador": "sin detalles del navegador",
    "o_sistema_nao_aceitou_receber_o_arquiv": "El sistema del dispositivo no pudo recibir el archivo.",
    "o_navegador_considerou_a_situacao_inse": "El navegador bloqueó el uso compartido por una regla de seguridad propia. Guarda el archivo y envíalo con la aplicación que prefieras.",
    "o_compartilhamento_so_funciona_em_ende": "El uso compartido solo funciona con direcciones seguras. Esta aplicación se está abriendo desde una dirección http:// normal y, en ese caso, el navegador bloquea el envío a otras aplicaciones.",
    "este_navegador_nao_conseguiu_iniciar_o": "Este navegador no pudo abrir el uso compartido. Guarda el archivo y envíalo con la aplicación que prefieras.",
    "o_navegador_recebeu_um_arquivo_em_form": "El navegador no abrió la lista de aplicaciones para compartir. Vuelve a tocar el botón o guarda el archivo y envíalo con la aplicación que prefieras.",
    "nao_foi_possivel_gerar_o_backup": "No se pudo crear la copia de seguridad.",
    "reunindo_a_sua_estante": "Reuniendo tu estantería...",
    "preparando_o_backup": "Preparando la copia de seguridad",
    "pronto_nada_mais_esta_esperando": "Listo: ya no queda nada pendiente.",
    "o_progresso_e_as_marcacoes_desses_livr": "El progreso y las marcas de esos libros se borrarán. Si importas los archivos más tarde, volverán sin marcas.",
    "descartar_o_que_esta_esperando": "¿Eliminar los datos pendientes?",
    "lembretes_de_backup_religados": "Recordatorios de copia de seguridad activados de nuevo.",
    "sem_titulo": "Sin título",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "Recordatorios desactivados.",
    "manter_ligado": "Mantener activados",
    "desligar_assim_mesmo": "Desactivarlos de todos modos",
    "o_botao_de_salvar_continua_onde_sempre": "El botón de guardar sigue donde siempre, en Copia de seguridad y restauración.",
    "o_lembrete_e_o_unico_aviso_que_existe": "El recordatorio es el único aviso que existe. Sin él, tendrás que acordarte tú de hacer copias de seguridad.\n\n",
    "limpar_os_dados_do_navegador_desinstal": "Si se borran los datos del navegador, se desinstala la aplicación, cambias de teléfono o el dispositivo se avería, no será posible recuperar el progreso, los resaltados, las citas, las notas ni los marcadores.\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "Tu estantería existe solo en este dispositivo. No hay ninguna copia en un servidor, así que no hay forma de recuperarla por ti.\n\n",
    "leia_antes_de_confirmar": "Lee antes de confirmar",
    "desligar_os_lembretes_de_backup": "¿Desactivar los recordatorios de copia de seguridad?",
    "progresso_de_leitura_restaurado_neste": "Progreso de lectura restaurado para este libro.",
    "pronto": "Listo.",
    "aplicando_as_suas_preferencias": "Aplicando tus preferencias...",
    "atualize_o_veredas_reader_e_tente_de_n": "Actualiza Veredas Reader y vuelve a intentarlo.",
    "este_backup_foi_feito_numa_versao_mais": "Esta copia de seguridad se hizo con una versión más reciente de la aplicación.",
    "este_arquivo_nao_e_um_backup_de_biblio": "Este archivo no es una copia de seguridad de la biblioteca de Veredas.",
    "o_conteudo_interno_nao_pode_ser_lido": "No se pudo leer el contenido interno.",
    "o_backup_esta_corrompido": "La copia de seguridad está dañada.",
    "falta_o_arquivo_biblioteca_json_la_den": "Falta el archivo biblioteca.json en su interior.",
    "este_arquivo_nao_parece_ser_um_backup": "Este archivo no parece ser una copia de seguridad de Veredas.",
    "compactando": "Comprimiendo...",
    "para_restaurar_menu_lateral_backup_e_r": "Para restaurar: menú lateral > Copia de seguridad y restauración > Restaurar copia de seguridad.",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas restaura automáticamente las marcas y el punto en el que te quedaste.",
    "importe_os_livros_normalmente_no_aplic": "importa los libros normalmente en la aplicación: al reconocer cada archivo,",
    "ele_nao_contem_os_arquivos_dos_livros": "NO contiene los archivos de los libros. Para restaurarlo por completo,",
    "as_notas_os_marcadores_e_a_organizacao": "tus notas, tus marcadores y la organización de tu estantería.",
    "este_arquivo_guarda_o_seu_progresso_de": "Este archivo guarda tu progreso de lectura, tus resaltados, tus citas,",
    "verificando_se_sao_partes_do_mesmo_aud": "Comprobando si son partes del mismo audiolibro...",
    "analisando_os_arquivos": "Analizando los archivos",
    "nao_foi_possivel_salvar_o_audiolivro": "No se pudo guardar el audiolibro.",
    "audiolivros_grandes_podem_levar_alguns": "Los audiolibros grandes pueden tardar unos instantes...",
    "salvando_na_sua_estante": "Guardando en tu estantería",
    "falha_ao_processar_os_arquivos": "No se pudieron procesar los archivos.",
    "falha_ao_processar_o_arquivo": "No se pudo procesar el archivo.",
    "nao_foi_possivel_salvar_o_quadrinho": "No se pudo guardar el cómic.",
    "quase_la": "Casi está...",
    "falha_ao_processar_o_quadrinho": "No se pudo procesar el cómic.",
    "autor_desconhecido": "Autor desconocido",
    "lendo_o_quadrinho": "Leyendo el cómic...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "No se pudo guardar el libro en la biblioteca.",
    "nao_foi_possivel_ler_o_pdf": "No se pudo leer el PDF.",
    "lendo_o_pdf": "Leyendo el PDF...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "Si es un .doc antiguo, ábrelo en Word y guárdalo como .docx antes de importarlo.",
    "este_arquivo_nao_e_um_docx_valido": "Este archivo no es un .docx válido.",
    "livros_com_protecao_da_amazon_nao_pode": "Los libros con protección de Amazon no se pueden abrir aquí. Usa una copia sin DRM o convierte el libro a EPUB.",
    "este_arquivo_esta_protegido_por_drm": "Este archivo está protegido por DRM.",
    "confira_se_a_extensao_corresponde_ao_c": "Comprueba que la extensión coincida con el contenido o convierte el libro a EPUB.",
    "este_arquivo_nao_e_um_mobi_valido": "Este archivo no es un MOBI válido.",
    "nao_foi_possivel_ler_o_arquivo": "No se pudo leer el archivo.",
    "formato_nao_suportado": "Formato no compatible.",
    "falha_ao_salvar_o_livro_na_biblioteca": "No se pudo guardar el libro en la biblioteca.",
    "livro_importado_e_salvo_no_dispositivo": "Libro importado y guardado en este dispositivo.",
    "audiolivro_importado_e_salvo_no_dispos": "Audiolibro importado y guardado en este dispositivo.",
    "quadrinho_importado_e_salvo_no_disposi": "Cómic importado y guardado en este dispositivo.",
    "salvando_na_sua_estante_2": "Guardando en tu estantería...",
    "importando_livro": "Importando libro",
    "importar_mesmo_assim": "Importar de todos modos",
    "parece_que_este_livro_ja_esta_na_estan": "Parece que este libro ya está en tu estantería",
    "este_livro_ja_esta_na_estante": "Este libro ya está en tu estantería",
    "video_importado_e_salvo_no_dispositivo": "Vídeo importado y guardado en este dispositivo.",
    "importacao_cancelada": "Importación cancelada.",
    "preparando_o_arquivo": "Preparando el archivo",
    "importando_audiolivro": "Importando audiolibro",
    "importacao_concluida": "Importación completada",
    "importacao_interrompida": "Importación detenida",
    "a_importacao_foi_interrompida_o_que_ja": "La importación se detuvo; lo que ya había entrado permanece en tu estantería.",
    "finalizando": "Finalizando…",
    "nao_foi_possivel_ler_o_arquivo_2": "no se pudo leer el archivo",
    "importando_livros": "Importando libros",
    "livros_quadrinhos_documentos_audiolivr": "Libros, cómics, documentos, audiolibros y vídeos",
    "series": "Series",
    "colecoes": "Colecciones",
    "organizacao_salva": "Organización guardada.",
    "informe_um_nome_para_o_livro_antes_de": "Asigna un nombre al libro antes de guardarlo.",
    "nome_do_livro_obrigatorio": "El libro necesita un nombre",
    "importe_um_livro_primeiro": "Importa primero un libro.",
    "citacao": "cita",
    "anotacao": "nota",
    "citacao_2": "Cita",
    "anotacao_2": "Nota",
    "uma_citacao": "una cita",
    "uma_anotacao": "una nota",
    "o_marcador_sera_removido_da_biblioteca": "El marcador se eliminará de la biblioteca, pero el archivo del libro permanecerá intacto.",
    "marcador_de_audio": "Marcador de audio",
    "marcador_de_video": "Marcador de vídeo",
    "nao_foi_possivel_excluir_o_livro": "No se pudo eliminar el libro.",
    "livro_excluido_da_biblioteca": "Libro eliminado de la biblioteca.",
    "excluir_livro": "Eliminar libro",
    "isso_remove_apenas_a_copia_armazenada": "Esto elimina solo la copia que conserva la biblioteca, junto con el progreso, los marcadores y las notas. El archivo original de tu propia carpeta no se eliminará.",
    "excluir_livro_2": "¿Eliminar libro?",
    "ordem_personalizada_salva": "Orden personalizada guardada.",
    "ordem_manual_da_sua_estante": "Tu estantería, en el orden que has establecido.",
    "agrupamento_alterado_para_minha_ordem": "La agrupación cambió a Mi orden.",
    "nova_ordem_salva": "Nuevo orden guardado.",
    "nao_foi_possivel_salvar_a_nova_ordem": "No se pudo guardar el nuevo orden.",
    "baixar_automaticamente": "Descargar automáticamente",
    "escolha_livremente_onde_o_arquivo_sera": "Elige libremente dónde se guardará el archivo.",
    "salvar_epub": "Guardar EPUB",
    "livro_epub": "Libro EPUB",
    "erro_desconhecido": "error desconocido",
    "a_permissao_para_salvar_o_arquivo_foi": "Se canceló el permiso para guardar el archivo. No se modificó nada en la biblioteca.",
    "conversao_cancelada_o_pdf_original_per": "Conversión cancelada. El PDF original permanece en la biblioteca.",
    "preparando_salvamento": "Preparando para guardar…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "La copia del PDF no está disponible en la biblioteca.",
    "reconstruindo_o_livro_localmente": "Reconstruyendo el libro en tu dispositivo.",
    "convertendo_pdf": "Convirtiendo PDF",
    "nao_foi_possivel_compartilhar_o_livro": "No se pudo compartir el libro.",
    "o_arquivo_foi_preparado_para_voce_comp": "El archivo está listo para compartirlo en otra aplicación.",
    "livro_compartilhado": "Libro compartido.",
    "a_copia_deste_livro_nao_esta_disponive": "La copia de este libro no está disponible en la biblioteca.",
    "para_manter_a_politica_de_compartilham": "Para mantener la política de uso compartido de la biblioteca, esta aplicación no permite compartir archivos EPUB ni MOBI.",
    "quadrinhos_ficam_guardados_somente_no": "Los cómics se guardan solo en tu dispositivo y esta aplicación no permite compartirlos.",
    "audiolivros_e_videos_ficam_guardados_s": "Los audiolibros y vídeos se guardan solo en tu dispositivo y esta aplicación no permite compartirlos.",
    "formato_protegido": "Formato protegido",
    "compartilhamento_indisponivel": "Uso compartido no disponible",
    "concluido": "Finalizado",
    "ainda_nao_comecado": "Aún no iniciado",
    "continue_lendo": "Continuar leyendo",
    "continue_ouvindo": "Continuar escuchando",
    "continue_assistindo": "Continuar viendo",
    "comece_por_aqui": "Empezar aquí",
    "comece_a_ouvir": "Empezar a escuchar",
    "comece_a_assistir": "Empezar a ver",
    "no_total": "en total",
    "para_ler": "por leer",
    "sua_estante": "Tu estantería",
    "livros_organizados_pela_opcao_selecion": "Libros organizados según la opción que elegiste.",
    "uma_prateleira_para_cada_tipo_de_arqui": "Una estantería para cada tipo de archivo.",
    "autores_agrupados_em_ordem_alfabetica": "Autores agrupados alfabéticamente.",
    "toque_para_continuar_de_onde_parou": "Toca para continuar desde donde lo dejaste.",
    "para_ler_2": "Para leer",
    "lendo_agora": "Leyendo ahora",
    "audio_e_video": "Audio y vídeo",
    "trechos_salvos_separadamente_dos_marca": "Pasajes guardados por separado de los marcadores.",
    "comentarios_vinculados_a_trechos_selec": "Comentarios vinculados a los pasajes que seleccionaste.",
    "paginas_salvas_para_voltar_rapidamente": "Páginas guardadas para volver rápidamente.",
    "do_maior_para_o_menor_progresso_de_lei": "Del mayor al menor progreso de lectura.",
    "livros_adicionados_ou_lidos_mais_recen": "Libros añadidos o leídos más recientemente.",
    "ordem_alfabetica_pelo_titulo": "En orden alfabético por título.",
    "separa_em_prateleiras_de_epub_pdf_docx": "Separa en estanterías de EPUB, PDF, DOCX, audiolibros, vídeos…",
    "tipo_de_arquivo": "Tipo de archivo",
    "organiza_e_separa_os_livros_por_autor": "Organiza y separa los libros por autor.",
    "agrupar_por_autor": "Agrupar por autor",
    "pressione_o_livro_e_mova_o": "Mantén pulsado un libro y muévelo.",
    "minha_ordem": "Mi orden",
    "epub_pronto": "EPUB listo",
    "conversao_concluida": "Conversión finalizada",
    "necessario_para_salvar_o_epub_ao_lado": "Necesario para guardar el EPUB junto al original",
    "escolha_a_pasta_do_pdf": "Elegir la carpeta del PDF",
    "processando": "Procesando…",
    "processamento_local_no_navegador": "Procesado en tu dispositivo, en el navegador",
    "convertendo_livro": "Convirtiendo libro",
    "livro_em_pdf": "Libro PDF",
    "recalculando_paginas": "Recalculando páginas...",
    "ajustando_leitura": "Ajustando el diseño",
    "abrir_comentario": "Abrir comentario",
    "anotacao_salva": "Nota guardada.",
    "anotacao_atualizada": "Nota actualizada.",
    "escreva_uma_nota_antes_de_salvar": "Escribe una nota antes de guardar.",
    "nao_foi_possivel_compartilhar": "No se pudo compartir.",
    "compartilhamento_indisponivel_2": "Uso compartido no disponible.",
    "trecho_copiado": "Pasaje copiado.",
    "trecho_compartilhado": "Pasaje compartido.",
    "citacao_salva": "Cita guardada.",
    "trecho_grifado": "Pasaje resaltado.",
    "grifo_removido": "Resaltado eliminado.",
    "comentario_apagado": "Comentario eliminado.",
    "remover_grifo": "Eliminar resaltado",
    "apagar_comentario": "Eliminar comentario",
    "remover_grifo_2": "¿Eliminar resaltado?",
    "apagar_comentario_2": "¿Eliminar comentario?",
    "remover_este_grifo": "¿Eliminar este resaltado?",
    "apagar_este_comentario": "¿Eliminar este comentario?",
    "sem_comentario": "Sin comentario",
    "comentario": "Comentario",
    "marcador_removido_desta_pagina": "Marcador eliminado de esta página.",
    "pagina_adicionada_aos_marcadores": "Página añadida a tus marcadores.",
    "este_e_o_inicio_do_livro": "Este es el principio del libro.",
    "esta_e_a_primeira_pagina": "Esta es la primera página.",
    "voce_chegou_ao_fim_do_livro": "Has llegado al final del libro.",
    "voce_chegou_ao_fim_do_quadrinho": "Has llegado al final del cómic.",
    "agora_em_revista_aberta_duas_paginas_l": "Ahora en doble página: dos páginas una al lado de la otra, con la portada sola.",
    "leitura_horizontal_ativada_neste_livro": "La lectura horizontal está activada para este libro.",
    "rolagem_vertical_ativada_neste_livro": "El desplazamiento vertical está activado para este libro.",
    "leitura_pagina_a_pagina_ativada_neste": "La lectura página a página está activada para este cómic.",
    "rolagem_continua_ativada_neste_quadrin": "El desplazamiento continuo está activado para este cómic.",
    "mudar_para_rolagem_vertical": "Cambiar al desplazamiento vertical",
    "mudar_para_leitura_horizontal": "Cambiar a lectura horizontal",
    "rolagem_continua_estilo_webtoon": "Desplazamiento continuo (estilo webtoon)",
    "voltar_para_pagina_a_pagina": "Volver a página por página",
    "separando_os_capitulos": "Separando los capítulos...",
    "lendo_o_livro": "Leyendo el libro",
    "lendo_o_markdown": "Leyendo el Markdown",
    "lendo_o_documento": "Leyendo el documento",
    "pagina_indisponivel": "Página no disponible.",
    "isto_acontece_so_desta_vez": "Esto solo ocurre esta vez.",
    "preparando_o_quadrinho": "Preparando el cómic",
    "abrindo_o_quadrinho": "Abriendo el cómic...",
    "montando_as_paginas": "Creando las páginas...",
    "nao_foi_possivel_abrir_este_livro": "No se pudo abrir este libro.",
    "abertura_cancelada": "Apertura cancelada.",
    "o_livro_demorou_demais_para_abrir_e_fo": "El libro tardó demasiado en abrirse y se detuvo.",
    "importe_o_arquivo_novamente_para_conti": "Importa de nuevo el archivo para continuar leyendo.",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "El archivo de este libro ya no está guardado en tu dispositivo.",
    "preparando_sua_leitura": "Preparando tu lectura...",
    "abrindo_livro": "Abriendo libro",
    "leitura_concluida": "Lectura finalizada.",
    "a_voz_foi_interrompida_pelo_navegador": "El navegador detuvo la voz.",
    "nao_foi_possivel_preparar_este_trecho": "No se pudo preparar este pasaje para audio.",
    "a_leitura_em_voz_alta_nao_e_suportada": "La lectura en voz alta no es compatible con este navegador.",
    "pausar_leitura": "Pausar lectura",
    "em_pausa": "En pausa",
    "leitura_em_voz_alta_nao_disponivel_nes": "La lectura en voz alta no está disponible en este navegador",
    "nome_do_marcador": "Nombre del marcador",
    "o_marcador_sera_removido_deste_audioli": "El marcador se eliminará de este audiolibro.",
    "nao_foi_possivel_salvar_o_marcador": "No se pudo guardar el marcador.",
    "ja_existe_um_marcador_neste_ponto": "Ya existe un marcador en este punto.",
    "timer_de_sono_encerrado": "El temporizador de sueño ha terminado.",
    "fim_do_cap": "Fin del cap.",
    "timer_desativado": "Temporizador desactivado.",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "El audio se pausará al final del capítulo.",
    "este_audiolivro_nao_tem_capitulos": "Este audiolibro no tiene capítulos.",
    "ao_fim_do_capitulo": "Al final del capítulo",
    "desativar_timer": "Desactivar temporizador",
    "mais_10_minutos_no_timer": "10 minutos más en el temporizador.",
    "somar_10_minutos": "Añadir 10 minutos",
    "pausa_ao_fim_do_capitulo": "Pausar al final del capítulo",
    "no_livro_todo": "En todo el libro",
    "video": "Vídeo",
    "audiolivro_concluido": "Audiolibro finalizado.",
    "video_concluido": "Vídeo finalizado.",
    "video_2": "vídeo",
    "audio": "audio",
    "toque_em_reproduzir_para_comecar": "Toca reproducir para comenzar.",
    "falha_ao_carregar_o_audio": "No se pudo cargar el audio.",
    "exclua_o_da_biblioteca_e_importe_o_arq": "Elimínalo de la biblioteca e importa de nuevo el archivo.",
    "os_nomes_dos_arquivos_seguem_uma_seque": "Los nombres de los archivos siguen una secuencia, por lo que parecen capítulos de un mismo audiolibro.",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "Los archivos comparten el mismo álbum en sus etiquetas, por lo que parecen capítulos de un mismo audiolibro.",
    "libere_espaco_ou_exclua_livros_da_bibl": "Libera espacio o elimina libros de la biblioteca e inténtalo de nuevo.",
    "o_armazenamento_do_aparelho_esta_cheio": "El almacenamiento de tu dispositivo está lleno.",
    "preparando_a_capa": "Preparando la portada...",
    "remova_esse_arquivo_da_selecao_e_tente": "Elimina ese archivo de la selección e inténtalo de nuevo.",
    "sequencia": "secuencia",
    "o_arquivo_pode_estar_incompleto_tente": "El archivo puede estar incompleto. Intenta descargarlo de nuevo.",
    "conferindo_se_o_audio_pode_ser_reprodu": "Comprobando si el audio puede reproducirse...",
    "conferindo_se_o_video_pode_ser_reprodu": "Comprobando si el vídeo puede reproducirse...",
    "lendo_titulo_capitulos_e_capa": "Leyendo título, capítulos y portada...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "Puede que el archivo esté dañado o en un formato de audio que el navegador no reproduce. Prueba a convertirlo a MP3 o M4B (AAC).",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "Puede que el archivo esté dañado o en un formato de vídeo que el navegador no reproduce. Prueba a convertirlo a MP4 con vídeo H.264 y audio AAC.",
    "converta_o_audiolivro_para_m4b_com_aud": "Convierte el audiolibro a M4B con audio AAC (o a MP3) e impórtalo de nuevo.",
    "converta_o_video_para_mp4_com_audio_aa": "Convierte el vídeo a MP4 con audio AAC y vídeo H.264 e impórtalo de nuevo.",
    "o_navegador_nao_reproduz_o_formato_de": "El navegador no reproducirá el formato de audio de este archivo.",
    "arquivos_com_protecao_nao_podem_ser_re": "Los archivos protegidos no se pueden reproducir aquí. Usa una copia sin DRM.",
    "nao_ha_espaco_suficiente_no_aparelho_p": "No hay suficiente espacio en tu dispositivo para este audiolibro.",
    "confira_se_a_extensao_corresponde_ao_c_2": "Comprueba que la extensión coincida con el contenido o convierte el audio a MP3 o M4B (AAC).",
    "imagem_invalida": "imagen no válida",
    "imagem_demorou_demais": "la imagen tardó demasiado en cargar",
    "imagem_vazia": "imagen vacía",
    "inicio": "Inicio",
    "mp4_moov_nao_encontrado": "Parece que el vídeo está incompleto o dañado.",
    "pagina": "Página",
    "esta_pagina_nao_esta_disponivel": "Esta página no está disponible.",
    "esta_pagina_nao_pode_ser_descompactada": "No se pudo descomprimir esta página.",
    "quadrinho_fechado": "Cómic cerrado.",
    "ele_pode_estar_incompleto_dividido_em": "Puede estar incompleto, dividido en varias partes o usar una variante de RAR que la aplicación no reconoce. Convertirlo a CBZ suele solucionarlo.",
    "remova_a_senha_do_arquivo_e_importe_de": "Elimina la contraseña del archivo e impórtalo de nuevo.",
    "nao_foi_possivel_ler_este_arquivo_de_q": "No se pudo leer este archivo de cómic.",
    "este_quadrinho_esta_protegido_por_senh": "Este cómic está protegido con contraseña.",
    "lendo_o_indice_do_quadrinho": "Leyendo el índice del cómic...",
    "o_arquivo_pode_ser_grande_demais_para": "El archivo puede ser demasiado grande para la memoria de este dispositivo. Dividir el cómic en partes más pequeñas suele solucionarlo.",
    "nao_foi_possivel_abrir_este_quadrinho": "No se pudo abrir este cómic.",
    "lendo_o_arquivo": "Leyendo el archivo...",
    "preparando_o_leitor_de_cbr": "Preparando el lector de CBR...",
    "o_arquivo_pode_estar_incompleto_proteg": "El archivo puede estar incompleto, protegido con contraseña o dañado.",
    "nao_foi_possivel_ler_este_quadrinho": "No se pudo leer este cómic.",
    "o_arquivo_precisa_conter_imagens_jpg_p": "El archivo debe contener imágenes (JPG, PNG, WEBP o GIF).",
    "nao_encontramos_paginas_dentro_deste_q": "No encontramos páginas dentro de este cómic.",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "No hay suficiente espacio en tu dispositivo para este cómic.",
    "cabecalho_de_item_invalido": "Parte del archivo está dañada.",
    "a_pasta_vendor_libarchive_precisa_esta": "Falta un componente de la aplicación para abrir este cómic. Conviértelo a CBZ o vuelve a instalar la aplicación.",
    "o_leitor_de_cbr_nao_foi_encontrado": "No se encontró el lector de CBR.",
    "converta_o_quadrinho_para_cbz_zip_e_im": "Convierte el cómic a CBZ (ZIP) e impórtalo de nuevo.",
    "este_navegador_nao_consegue_abrir_arqu": "Este navegador no puede abrir archivos CBR.",
    "convertendo_o_markdown": "Convirtiendo el Markdown",
    "lendo_o_texto": "Leyendo el texto",
    "pdf_indisponivel": "PDF no disponible.",
    "epub_invalido_nenhum_capitulo_no_spine": "Este EPUB está dañado: no se encontraron los capítulos del libro.",
    "livro_sem_titulo": "Libro sin título",
    "epub_invalido_arquivo_opf_nao_encontra": "Este EPUB está incompleto o dañado y no se puede abrir.",
    "epub_invalido_container_xml_nao_encont": "Este EPUB está incompleto o dañado y no se puede abrir.",
    "organizando_o_texto": "Organizando el texto",
    "descompactando_o_livro": "Descomprimiendo el libro",
    "nao_encontramos_conteudo_para_exibir_n": "No encontramos nada que mostrar en este archivo.",
    "livro_sem_texto_legivel": "Libro sin texto legible",
    "o_arquivo_pode_estar_corrompido_tente": "El archivo puede estar dañado. Intenta convertirlo a EPUB.",
    "nao_foi_possivel_extrair_o_texto_deste": "No se pudo extraer el texto de este MOBI.",
    "nenhum_registro_de_conteudo_foi_encont": "No se encontró el texto del libro en este archivo.",
    "arquivo_mobi_sem_texto": "Archivo MOBI sin texto.",
    "o_dicionario_de_compressao_esta_vazio": "Falta parte del contenido de este MOBI.",
    "arquivo_mobi_incompleto": "Archivo MOBI incompleto.",
    "as_tabelas_de_compressao_nao_foram_enc": "Falta parte del contenido de este MOBI.",
    "converta_o_arquivo_para_epub_em_um_pro": "Convierte el archivo a EPUB en un programa como Calibre e impórtalo de nuevo.",
    "compressao_mobi_nao_reconhecida": "Este MOBI usa un formato interno que la aplicación no reconoce.",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "No se pudo leer el encabezado del libro.",
    "arquivo_mobi_corrompido": "Archivo MOBI dañado.",
    "a_lista_interna_de_registros_esta_inco": "El archivo está incompleto. Prueba a descargarlo o convertirlo de nuevo.",
    "o_download_parece_ter_sido_interrompid": "La descarga parece haberse interrumpido. Descarga el archivo de nuevo.",
    "tabela_de_compressao_mobi_corrompida": "Parte de este archivo MOBI está dañada.",
    "tabela_de_compressao_mobi_incompleta": "Este archivo MOBI está incompleto.",
    "tabela_de_compressao_mobi_invalida": "Parte de este archivo MOBI está dañada.",
    "este_arquivo_docx_nao_tem_conteudo_de": "Este archivo .docx no contiene texto que se pueda mostrar.",
    "documento_sem_texto": "Documento sin texto",
    "o_arquivo_pode_estar_corrompido_proteg": "El archivo puede estar dañado, protegido con contraseña o ser un .doc antiguo. Guárdalo de nuevo como .docx e impórtalo otra vez.",
    "nao_foi_possivel_ler_este_arquivo_docx": "No se pudo leer este archivo DOCX.",
    "convertendo_o_documento": "Convirtiendo el documento",
    "conecte_se_a_internet_uma_vez_para_bai": "Conéctate a Internet una vez para descargar el componente y después vuelve a abrir el libro.",
    "o_conversor_de_docx_nao_carregou": "El conversor de DOCX no se cargó.",
    "video_mp4": "Vídeo (MP4)",
    "audiolivro_m4b": "Audiolibro (M4B)",
    "audiolivro_mp3": "Audiolibro (MP3)",
    "quadrinho_cbt": "Cómic (CBT)",
    "quadrinho_cb7": "Cómic (CB7)",
    "quadrinho_cbr": "Cómic (CBR)",
    "quadrinho_cbz": "Cómic (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "Texto (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "Guardado cancelado.",
    "o_arquivo_esta_vindo_do_armazenamento": "El archivo se está descargando del almacenamiento en la nube a tu dispositivo.",
    "baixando_o_arquivo": "Descargando el archivo",
    "cancelando": "Cancelando...",
    "use_grifar_citacao_anotar_ou_marcador": "Usa Resaltar, Cita, Nota o Marcador mientras lees.",
    "nenhuma_marcacao_ainda": "Aún no hay marcas",
    "trecho_original": "Pasaje original",
    "procurar_meus_livros": "Buscar mis libros",
    "a_busca_fica_sempre_disponivel_no_menu": "La búsqueda está siempre disponible en el menú lateral, en Sistema.",
    "da_para_fazer_depois": "Puedes hacerlo más tarde",
    "nada_entra_na_estante_sem_a_sua_confir": "Nada llega a tu estantería sin que lo apruebes: ves la lista y marcas lo que quieres importar.",
    "voce_revisa_antes": "Primero revisas",
    "escolha_uma_pasta_downloads_e_um_bom_c": "Elige una carpeta (Descargas es un buen comienzo) y la aplicación buscará libros en ella y en todas sus subcarpetas.",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "Busca EPUB, MOBI, CBZ, CBR y M4B",
    "voltar_e_revisar": "Volver y revisar",
    "ler_os_termos": "Leer los términos",
    "ler_a_politica": "Leer la política",
    "os_dois_documentos_ficam_sempre_dispon": "Los dos documentos están siempre disponibles en el menú lateral, en Acerca de.",
    "leia_com_calma": "Tómate tu tiempo",
    "a_politica_e_os_termos_explicam_como_o": "La política y los términos explican cómo la aplicación conserva tus libros y qué puedes hacer con ellos. Para usar la biblioteca, es necesario que los aceptes.",
    "nada_acontece_sem_o_aceite": "Para empezar, es necesario aceptar los términos",
    "aceitar_e_continuar": "Aceptar y continuar",
    "nao_aceito": "No acepto",
    "termos_de_uso_2": "Términos de uso",
    "politica_de_privacidade_2": "Política de privacidad",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "La aplicación solo accede a los archivos y carpetas que eliges, cuando tú lo decides.",
    "voce_no_controle": "Tú tienes el control",
    "depois_de_importar_um_livro_voce_le_se": "Una vez importado un libro, puedes leerlo sin Internet.",
    "funciona_offline": "Funciona sin conexión",
    "livros_marcacoes_e_progresso_sao_guard": "Los libros, las marcas y el progreso se guardan en tu dispositivo. No se envía nada a nuestros servidores.",
    "tudo_fica_no_seu_aparelho": "Todo permanece en tu dispositivo",
    "escolha_o_que_deseja_adicionar_a_bibli": "Elige qué quieres añadir a la biblioteca. Los archivos idénticos a los que ya están en tu estantería se omiten automáticamente.",
    "voce_pode_tentar_outra_pasta_ou_import": "Puedes probar otra carpeta o importar archivos con el botón +.",
    "a_leitura_acontece_so_no_seu_dispositi": "La lectura ocurre solo en tu dispositivo.",
    "voce_escolhe_a_pasta": "Tú eliges la carpeta",
    "tema_tipografia_margens_modo_de_virada": "Tema, tipografía, márgenes, estilo de cambio de página y ajustes de audio.",
    "restaurar_minhas_preferencias": "Restaurar mis preferencias",
    "o_backup_manda_as_marcacoes_atuais_dos": "La copia de seguridad prevalece. Las marcas actuales de cualquier libro incluido en el archivo se reemplazarán por las de la copia de seguridad.",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "No se borra nada. Las marcas de ambos lados se combinan y el progreso más reciente prevalece.",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "Qué hacer con lo que ya está en tu estantería",
    "grifos_citacoes_e_notas": "resaltados, citas y notas",
    "preparando_o_arquivo_2": "Preparando el archivo...",
    "os_livros_em_si_nem_as_capas_por_isso": "Ni los libros en sí ni las portadas: por eso el archivo ocupa solo unos pocos KB. Quien lo reciba necesita tener los archivos de los libros para que las marcas vuelvan a su sitio, y las portadas reaparecen automáticamente al importarlos.",
    "nao_vai_no_arquivo": "No está en el archivo",
    "o_seu_progresso_de_leitura_os_grifos_a": "Tu progreso de lectura, tus resaltados, tus citas, tus notas, tus marcadores y la organización de tu estantería —estado, favoritos, colecciones, series y etiquetas.",
    "vai_no_arquivo": "Está en el archivo",
    "descartar_o_que_esta_esperando_2": "Eliminar datos pendientes",
    "esperando_o_arquivo": "Esperando el archivo",
    "avisar_quando_fizer_tempo_sem_backup": "Recordarme cuando haya pasado un tiempo sin hacer una copia de seguridad",
    "livros_que_ainda_nao_estiverem_na_esta": "Los libros que aún no estén en tu estantería quedarán pendientes: cuando importes su archivo, las marcas volverán automáticamente.",
    "restaurar_backup": "Restaurar copia de seguridad",
    "salvar_backup": "Guardar copia de seguridad",
    "ainda_nao_ha_itens": "Todavía no hay elementos",
    "arraste_um_livro_para_outra_posicao_na": "Arrastra un libro a otra posición de la estantería para guardar tu propio orden. Ese orden manual tiene prioridad sobre la agrupación por autor.",
    "separe_por_virgulas": "Separar con comas",
    "ex_estudos_ficcao": "p. ej., Estudios, Ficción...",
    "pasta_estante": "Carpeta / estantería",
    "ex_trilogia": "p. ej., Trilogía...",
    "serie": "Serie",
    "aparece_em_favoritos": "Aparece en Favoritos.",
    "nome_do_livro": "Nombre del libro",
    "nenhum_registro_ainda": "Aún no hay nada registrado",
    "no_leitor_toque_no_icone_de_marcador_p": "En el lector, toca el icono de marcador para guardar la página.",
    "nenhum_marcador_ainda": "Aún no hay marcadores",
    "a_gravacao_e_independente_da_localizac": "El guardado es independiente de dónde se encuentre el PDF y no modifica el archivo original.",
    "o_pdf_original_nao_precisa_estar_nessa": "El PDF original no tiene que estar en esa carpeta",
    "excluir_da_biblioteca": "Eliminar de la biblioteca",
    "adicionar_livro": "Añadir libro",
    "adicione_livros_e_acompanhe_o_que_esta": "Añade libros y controla qué está pendiente, qué está en proceso y cuánto has avanzado.",
    "tudo_pronto_para_a_proxima_leitura": "Todo listo para tu próxima lectura.",
    "sua_biblioteca": "Tu biblioteca",
    "arraste_um_livro_para_reposiciona_lo_a": "Arrastra un libro para moverlo: la estantería cambia a Mi orden y conserva la secuencia.",
    "importe_um_livro_ou_ajuste_seus_filtro": "Importa un libro o ajusta los filtros.",
    "nada_por_aqui_ainda": "Nada por aquí todavía",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "Toca + y elige archivos MP3, M4B o MP4. Varios MP3 de capítulos pueden convertirse en un único audiolibro.",
    "nada_para_ouvir_ou_assistir_ainda": "Todavía no hay nada para escuchar o ver",
    "o_pdf_original_permanece_intacto_na_pa": "El PDF original permanece intacto en tu propia carpeta.",
    "paginas_como_imagem": "Páginas como imágenes",
    "paginas_do_pdf": "Páginas del PDF",
    "em_navegadores_sem_suporte_a_acesso_di": "En navegadores sin acceso directo al sistema de archivos, el EPUB se descargará en su lugar.",
    "essa_permissao_e_dada_somente_a_esta_a": "Ese permiso se concede únicamente a esta aplicación y evita que se modifique el archivo original.",
    "selecione_a_pasta_que_contem_o_pdf": "Selecciona la carpeta que contiene el PDF",
    "preparando": "Preparando…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "El archivo se está leyendo y reconstruyendo. Los libros grandes pueden tardar unos instantes.",
    "revistas_apostilas_complexas_formulari": "Las revistas, los libros de ejercicios complejos, los formularios, los documentos con muchas tablas o los PDF escaneados pueden perder parte de su diseño original.",
    "funcionalidade_indicada_apenas_para_li": "Pensado para libros",
    "o_epub_e_melhor_para_livros_com_texto": "EPUB es mejor para libros con texto seleccionable porque permite ajustar la tipografía, el tamaño, los márgenes y el modo de lectura.",
    "trecho_selecionado": "Pasaje seleccionado",
    "trecho_comentado": "Pasaje con un comentario",
    "aplicando_zoom": "Aplicando zoom...",
    "nao_foi_possivel_carregar_esta_pagina": "No se pudo cargar esta página.",
    "nomear_marcador": "Nombrar marcador",
    "toque_em_marcar_agora_para_guardar_est": "Toca «Marcar ahora» para guardar este punto y volver a él cuando quieras.",
    "timer_ativo": "Temporizador activado",
    "trecho_ausente_ou_corrompido_no_arquiv": "[Pasaje ausente o dañado en el archivo original]",
    "novos_livros_vao_abrir_em_leitura_v": "Los libros nuevos se abrirán en modo de lectura {v}.",
    "leitura_efetivo_aplicada_a_este_livro": "Lectura {efetivo} aplicada a este libro.",
    "automatico_neste_livro_leitura_efetivo": "Automático para este libro: lectura {efetivo}.",
    "agora_esta_em_efetivo_no_automatico_fo": "Ahora está configurado como {efetivo}; en automático, {format} se abre en {padrao}.",
    "esta_escolha_vale_so_para_v_cada_livro": "Esta elección solo se aplica a «{v}». Cada libro conserva su propia dirección de desplazamiento.",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} todavía no están en tu estantería.",
    "escolha_uma_pasta_para_procurar_label": "Elige una carpeta para buscar {label}.",
    "subtitle_versao_build": "{subtitle} · versión {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "No se pudo leer {path}; se usará el texto integrado.",
    "seu_ultimo_backup_foi_ha_dias_dias": "Tu última copia de seguridad fue hace {dias} días",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "Todavía falta {aguardando} libro de la copia de seguridad. Su progreso y sus marcas se conservaron: en cuanto importes el archivo, todo volverá a su sitio automáticamente.",
      "other": "Todavía faltan {aguardando} libros de la copia de seguridad. Su progreso y sus marcas se conservaron: en cuanto importes cada archivo, todo volverá a su sitio automáticamente."
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "Se actualizó {atualizados} libro de tu estantería.",
      "other": "Se actualizaron {atualizados} libros de tu estantería."
    },
    "criado_em_quando": "Creado el {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "Copia de seguridad lista: {livros} libros y {marcacoes} marcas.",
    "endereco_seguro_seguro": "dirección segura: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "Progreso y {marcas} marca restaurados para este libro.",
      "other": "Progreso y {marcas} marcas restaurados para este libro."
    },
    "restaurando_v_de_length": "Restaurando ({v} de {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} libros · {marcacoes} marcas",
    "criado_em_v": "Creado el {v}",
    "reunindo_a_sua_estante_v_de_length": "Reuniendo tu estantería ({v} de {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "«{titulo}» se importó anteriormente y sigue en tu biblioteca. No se creó una copia nueva.",
    "length_arquivos_de_audio": "{length} archivos de audio...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "No se pudo leer {falhas} archivo.",
      "other": "No se pudieron leer {falhas} archivos."
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} ya estaban en la biblioteca y se omitieron.",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "{importados} libro añadido a tu estantería.",
      "other": "{importados} libros añadidos a tu estantería."
    },
    "epub_salvo_em_filename": "EPUB guardado en {fileName}.",
    "falha_ao_converter_o_pdf_v": "No se pudo convertir el PDF: {v}",
    "pagina_page_de_totalpages": "Página {page} de {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} página",
      "other": "{totalPages} páginas"
    },
    "length_resultado_s_para_search": {
      "one": "{length} resultado para «{search}»",
      "other": "{length} resultados para «{search}»"
    },
    "capitulo_v": "Capítulo {v}",
    "organizando_capitulo_v_de_totalchapter": "Organizando el capítulo {v} de {totalChapters}",
    "pagina_v": "Página {v}",
    "paginas_v_v2": "Páginas {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} página lista",
      "other": "{length} páginas listas"
    },
    "montando_as_paginas_pagessofar_prontas": "Creando las páginas — {pagesSoFar} listas",
    "lendo_pagina_v_de_length": "Leyendo la página {v} de {length}",
    "marcador_salvo_em_t": "Marcador guardado en {t}.",
    "o_audio_vai_pausar_em_minutes_minutos": "El audio se pausará en {minutes} minutos.",
    "length_capitulos_toque_para_ir_direto": "{length} capítulos · toca para ir directamente allí.",
    "narrado_por_narrator": "Narrado por {narrator}",
    "velocidade_de_reproducao_rate": "Velocidad de reproducción: {rate}",
    "avancar_f_segundos": "Avanzar {f} segundos",
    "nao_foi_possivel_abrir_este_v": "No se pudo abrir este {v}.",
    "nao_foi_possivel_ler_o_arquivo_de_v": "No se pudo leer el archivo {v}.",
    "o_v_esta_danificado_neste_ponto": "El {v} está dañado en este punto.",
    "o_navegador_nao_consegue_reproduzir_es": "El navegador no puede reproducir este archivo {v}.",
    "nao_foi_possivel_reproduzir_este_v": "No se pudo reproducir este {v}.",
    "os_dados_deste_noun_estao_incompletos": "Los datos de este {noun} están incompletos.",
    "importe_o_arquivo_novamente_para_conti_2": "Vuelve a importar el archivo para continuar con {v}.",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "El archivo de este {noun} ya no está guardado en tu dispositivo.",
    "nao_foi_possivel_descobrir_a_duracao_d": "No se pudo determinar la duración de «{name}».",
    "lendo_faixa_v_de_length": "Leyendo la pista {v} de {length}...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "No se pudo determinar la duración de este {v}.",
    "este_format_nao_pode_ser_reproduzido_n": "Este {format} no se puede reproducir en este navegador.",
    "este_format_esta_protegido_por_drm": "Este {format} está protegido por DRM.",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "El archivo ocupa {bytes} y quedan aproximadamente {v}. Libera espacio o elimina libros de la biblioteca.",
    "este_arquivo_nao_e_um_format_valido": "Este archivo no es un {format} válido.",
    "preparando_as_paginas_vistas_de_total": "Preparando las páginas ({vistas} de {total})...",
    "preparando_total_pagina_s": {
      "one": "Preparando {total} página...",
      "other": "Preparando {total} páginas..."
    },
    "preparando_as_paginas_v_de_total": "Preparando las páginas ({v} de {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "Ocupa aproximadamente {bytes} y quedan aproximadamente {v}. Libera espacio o elimina libros de la biblioteca.",
    "envio_direto_exige_endereco_seguro": "El envío directo a otra aplicación no está disponible porque esta página no se abrió desde una dirección segura. Guarda el archivo y envíalo con la aplicación que prefieras.",
    "na_estante": "en la estantería",
    "nao_foi_possivel_montar_o_arquivo": "No se pudo crear el archivo.",
    "este_navegador_nao_oferece_o_envio_dir": "Este navegador no permite enviar directamente a otra aplicación. Guarda el archivo y adjúntalo mediante la aplicación que prefieras.",
    "voce_ainda_nao_fez_nenhum_backup": "Todavía no has hecho ninguna copia de seguridad.",
    "converter_para_epub": "Convertir a EPUB",
    "esta_pagina_nao_pode_ser_exibida": "No se pudo mostrar esta página.",
    "na_ordem_em_que_serao_tocados": "En el orden en que se reproducirán",
    "este_capitulo_nao_pode_ser_exibido": "No se pudo mostrar este capítulo.",
    "livro": "Libro",
    "restantes": " restantes",
    "como_seus_dados_sao_tratados": "Cómo se tratan tus datos",
    "condicoes_de_uso_do_aplicativo": "Condiciones de uso de la aplicación",
    "audiolivro": "audiolibro",
    "sobre_o_aplicativo": "Acerca de la aplicación",
    "o_que_e_o_veredas_reader": "Qué es Veredas Reader",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(este dispositivo no permite compartir este tipo de archivo)",
    "livros": "libros",
    "lendo": "lectura",
    "lidos": "finalizados",
    "compartilhar_livro": "Compartir libro",
    "n_livros": {
      "one": "{n} libro",
      "other": "{n} libros"
    },
    "livros_unidade": {
      "one": "libro",
      "other": "libros"
    },
    "uma_faixa_discreta_depois_de_n_dias": "Una franja discreta en la estantería después de {n} días sin una copia de seguridad. Nunca interrumpe tu lectura.",
    "scanned_arquivos_verificados_livros_enc": "{scanned} archivos comprobados · {encontrados} libros encontrados",
    "v_de_total": "{v} de {total}",
    "voltar_n_segundos": "Retroceder {n} segundos",
    "cancelado": "Cancelado",
    "arquivo": "Archivo",
    "outro": "Otro",
    "outros": "Otros",
    "audiolivro_2": "Audiolibro",
    "pausar": "Pausa",
    "marcador": "Marcador",
    "leitura": "Lectura",
    "grifo": "Resaltado",
    "editar": "Editar",
    "apagar": "Eliminar",
    "concluir": "Finalizar",
    "recentes": "Recientes",
    "progresso": "Progreso",
    "entendi": "Entendido",
    "aviso": "Aviso",
    "descartar": "Eliminar",
    "copiado": "Copiado",
    "restaurar": "Restaurar",
    "restaurando": "Restaurando",
    "excluir": "Eliminar",
    "grifos": "Resaltados",
    "arquivo_vazio": "Archivo vacío.",
    "e_mais_n_arquivos": {
      "one": "y {n} archivo más, en el orden en que se reproducirán",
      "other": "y {n} archivos más, en el orden en que se reproducirán"
    },
    "n_arquivos_mp3": {
      "one": "{n} archivo MP3",
      "other": "{n} archivos MP3"
    },
    "pct_restam": "{pct}% · quedan {tempo}",
    "n_minutos": {
      "one": "{n} minuto",
      "other": "{n} minutos"
    },
    "ir_para_tempo": "Ir a {tempo}",
    "nomear": "Nombrar",
    "parte_n": "Parte {n}",
    "carregando_pagina_n": "Cargando página {n}...",
    "selecionar_pasta_e_continuar": "Seleccionar carpeta y continuar",
    "ler_agora": "Leer ahora",
    "agrupamento_v": "Agrupación: {v}.",
    "tempo_restante": "quedan {tempo}",
    "abrir_titulo": "Abrir {titulo}",
    "continuar_lendo_titulo": "Seguir leyendo {titulo}",
    "continuar_ouvindo_titulo": "Seguir escuchando {titulo}",
    "continuar_assistindo_titulo": "Seguir viendo {titulo}",
    "lido": "Leído",
    "pausado": "En pausa",
    "status": "Estado",
    "favorito": "Favorito",
    "escolher_local": "Elegir ubicación",
    "epub_baixado_como": "EPUB descargado como {nome}.",
    "ouvir_a_partir_de": "escuchar desde {tempo}",
    "assistir_a_partir_de": "ver desde {tempo}",
    "pagina_n_minuscula": "página {n}",
    "selecione_trecho_para_criar": "Selecciona un fragmento durante la lectura para crear {oque}.",
    "excluir_oque_pergunta": "¿Eliminar {oque}?",
    "excluir_oque": "Eliminar {oque}",
    "excluir_item_pergunta": "¿Eliminar este elemento?",
    "use_organizar_para_criar": "Usa «{botao}» en un libro para crear {oque}.",
    "n_arquivos_processados": {
      "one": "{n} archivo procesado",
      "other": "{n} archivos procesados"
    },
    "voce_ja_tem_titulo_de_autor": "Ya tienes «{titulo}» de {autor} en la biblioteca, aunque el archivo es distinto. ¿Quieres importarlo de todos modos?",
    "voce_ja_tem_titulo": "Ya tienes «{titulo}» en la biblioteca, aunque el archivo es distinto. ¿Quieres importarlo de todos modos?",
    "marcadores_unidade": {
      "one": "marcador",
      "other": "marcadores"
    },
    "ultimo_backup_em": "Última copia el <strong>{data}</strong>.",
    "guardar": "Guardar",
    "lembretes": "Recordatorios",
    "juntar": "Combinar",
    "recomendado": "recomendado",
    "substituir": "Reemplazar",
    "n_capas_recuperadas": {
      "one": "{n} portada recuperada.",
      "other": "{n} portadas recuperadas."
    },
    "nao_encontramos_arquivos_tipo": "No encontramos archivos {tipo} en esta carpeta.",
    "tentar_outra_pasta": "Probar otra carpeta",
    "n_livros_encontrados": {
      "one": "{n} libro encontrado",
      "other": "{n} libros encontrados"
    },
    "n_de_total_selecionados": {
      "one": "{n} de {total} seleccionado",
      "other": "{n} de {total} seleccionados"
    },
    "importar": "Importar",
    "importar_n": "Importar {n}",
    "aceite_frase": "He leído y acepto la {politica} y los {termos} de Veredas Reader.",
    "pdf_preservado": "El PDF original <strong>no se eliminará de tu propia carpeta</strong>. Solo se quitará de la biblioteca la copia de este PDF, después de que el EPUB se guarde correctamente.",
    "gravar_epub_mesma_pasta": "Para guardar el EPUB <strong>en la misma carpeta que el PDF</strong>, el navegador necesita permiso para acceder a esa carpeta.",
    "epub_pronto_qualquer_pasta": "El EPUB se ha convertido. Ahora puedes elegir <strong>cualquier carpeta del ordenador</strong> para guardar el archivo.",
    "backup_explicacao": "La copia original es un archivo ZIP o TXT. Cuando la recibas en otro dispositivo, impórtala mediante <strong>Restaurar copia de seguridad</strong>: Veredas reconoce el contenido y lo restaura normalmente. El archivo contiene tu progreso, tus resaltados, tus citas, tus notas, tus marcadores y la organización de tu estantería — <strong>no los libros en sí</strong>, ni las portadas.",
    "lembretes_desligados_frase": "Los recordatorios están <strong>desactivados</strong>. Recuerda hacer una copia de seguridad de vez en cuando.",
    "backup_salvo_nos_downloads": "<strong>El archivo de copia de seguridad se guardó en este dispositivo</strong>, en tus descargas. Puedes enviarlo ahora mismo: abre WhatsApp, correo, Drive o la aplicación que quieras, toca adjuntar y selecciona el archivo.",
    "arquivo_pronto_tamanho": "Archivo listo — <strong>{tamanho}</strong>.",
    "scan_intro_frase": "La aplicación puede buscar libros en <strong>EPUB</strong> y <strong>MOBI</strong>, cómics en <strong>CBZ</strong> y <strong>CBR</strong> y audiolibros en <strong>M4B</strong> dentro de una carpeta de tu dispositivo, incluidas las subcarpetas.",
    "scan_intro_auto_frase": "Para llenar tu estantería rápidamente, la aplicación puede buscar libros en <strong>EPUB</strong> y <strong>MOBI</strong>, cómics en <strong>CBZ</strong> y <strong>CBR</strong> y audiolibros en <strong>M4B</strong> dentro de una carpeta de tu dispositivo, incluidas las subcarpetas.",
    "n_livros_aguardando": {
      "one": "<strong>{n} libro</strong> con el progreso y las marcas conservados, a la espera de volver a importarlo.",
      "other": "<strong>{n} libros</strong> con el progreso y las marcas conservados, a la espera de volver a importarlos."
    },
    "fora_da_busca_titulo": "No importamos automáticamente archivos PDF, TXT, DOCX (Word), MD, MP3 ni MP4",
    "fora_da_busca_texto": "Estos formatos se usan para todo tipo de documentos, no solo para libros. Dejarlos fuera mantiene ordenada la estantería. <strong>Puedes importar cada uno manualmente con el botón +.</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "Tu biblioteca local",
    "biblioteca": "Biblioteca",
    "organizacao": "Organización",
    "minhas_marcacoes": "Mis marcas",
    "sistema": "Sistema",
    "sua_biblioteca": "Tu biblioteca",
    "toque_em_um_livro_para_comecar_a_ler": "Toca un libro para empezar a leer.",
    "agrupar": "Agrupar",
    "sua_estante_nao_tem_copia_de_seguranca": "Tu estantería no tiene copia de seguridad",
    "se_este_aparelho_se_perder_o_progresso": "Si algo le pasa a este dispositivo, tu progreso y tus marcas podrían perderse.",
    "agora_nao": "Ahora no",
    "nao_avisar_mais": "No volver a avisarme",
    "carregando": "Cargando...",
    "estante": "Estantería",
    "lendo": "Lectura",
    "favoritos": "Favoritos",
    "marcas": "Marcas",
    "mais": "Más",
    "neste_capitulo": "Este capítulo",
    "velocidade": "Velocidad",
    "timer": "Temporizador",
    "marcar": "Marcar",
    "marcadores": "Marcadores",
    "personalizar_leitura": "Preferencias de lectura",
    "as_preferencias_ficam_salvas_para_as_p": "Tus preferencias se conservarán para futuras sesiones de lectura.",
    "tema": "Tema",
    "claro": "Claro",
    "sepia": "Sepia",
    "escuro": "Oscuro",
    "oceano": "Océano",
    "tipografia": "Tipografía",
    "texto": "Texto",
    "tamanho": "Tamaño",
    "espacamento": "Interlineado",
    "margens": "Márgenes",
    "cores_personalizadas_opcional": "Colores personalizados (opcional)",
    "fundo": "Fondo",
    "fonte": "Color del texto",
    "brilho": "Brillo",
    "orientacao": "Orientación",
    "auto": "Automático",
    "retrato": "Vertical",
    "paisagem": "Horizontal",
    "modo_de_leitura": "Modo de lectura",
    "automatico": "Automático",
    "horizontal": "Horizontal",
    "vertical": "Vertical",
    "automatico_usa_rolagem_horizontal_para": "Automático usa paginación horizontal para EPUB, MOBI, TXT y MD, y desplazamiento vertical para PDF y DOCX. Si lo cambias mientras lees, el cambio se guarda solo para ese libro.",
    "quadrinhos": "Cómics",
    "como_a_pagina_aparece": "Cómo se ajusta la página",
    "pagina_inteira": "Página completa",
    "largura_da_tela": "Ancho de pantalla",
    "sentido_da_leitura": "Dirección de lectura",
    "normal": "Normal →",
    "manga": "← Manga",
    "revista_aberta_na_horizontal": "Doble página en horizontal",
    "com_o_aparelho_deitado_mostra_duas_pag": "Al sostener el dispositivo de lado, muestra dos páginas una al lado de la otra; la portada queda sola, como en un cómic de verdad.",
    "normal_vira_da_esquerda_para_a_direita": "Normal gira de izquierda a derecha. Manga invierte todo: el deslizamiento, los toques en los bordes y el orden de las dos páginas en la vista doble.",
    "gire_o_aparelho_para_a_horizontal_para": "Gira el dispositivo de lado para ver dos páginas a la vez.",
    "dois_toques_ampliam_no_ponto_tocado_co": "Toca dos veces para ampliar donde tocaste; con el zoom, arrastra para moverte por la página. También funciona pellizcar con dos dedos.",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "El botón de desplazamiento de la parte superior del lector alterna entre página por página y desplazamiento continuo (estilo webtoon). En el desplazamiento continuo, las páginas se unen y el zoom ensancha la página: puedes recorrerla desplazándote hacia los lados.",
    "virada_de_pagina": "Cambio de página",
    "folha_real": "Papel real",
    "deslizar": "Deslizar",
    "sem_animacao": "Sin animación",
    "na_leitura_horizontal_arraste_a_pagina": "En la lectura horizontal, arrastra la página desde el borde para doblarla con el dedo. Suelta a mitad de camino para cancelar el cambio.",
    "ouvir_leitura": "Escuchar",
    "continue_de_onde_parou_no_seu_ritmo": "Continúa desde donde lo dejaste, a tu propio ritmo.",
    "livro": "Libro",
    "pronto_para_comecar": "Listo para empezar",
    "voz": "Voz",
    "escolha_uma_voz_disponivel_no_disposit": "Elige una voz disponible en este dispositivo",
    "voz_padrao_do_sistema": "Voz predeterminada del sistema",
    "durante_a_reproducao": "Durante la reproducción",
    "a_leitura_avanca_pagina_a_pagina_os_co": "La lectura avanza página por página. Los controles del sistema aparecen cuando el navegador los admite.",
    "organizar_livro": "Organizar libro",
    "estantes_colecoes_tags_e_status": "Estanterías, colecciones, etiquetas y estado.",
    "cancelar": "Cancelar",
    "salvar": "Guardar",
    "grifos_citacoes_notas_e_marcadores_des": "Resaltados, citas, notas y marcadores de este libro.",
    "sumario": "Contenido",
    "toque_em_um_capitulo_para_ir_direto_ao": "Toca un capítulo para ir directamente allí.",
    "sua_anotacao": "Tu nota",
    "edite_ou_adicione_comentarios_ao_seu_t": "Edita o añade comentarios a tu pasaje.",
    "trecho": "Pasaje",
    "sua_nota": "Tu nota",
    "salvar_nota": "Guardar nota",
    "agrupar_biblioteca": "Agrupar biblioteca",
    "escolha_como_os_livros_serao_organizad": "Elige cómo se organizan los libros en la estantería.",
    "ao_arrastar_um_livro_para_outra_posica": "Cuando arrastras un libro a otra posición, la estantería cambia automáticamente a Mi orden y conserva la secuencia que has creado.",
    "backup_e_restauracao": "Copia de seguridad y restauración",
    "sua_estante_seu_progresso_e_suas_marca": "Tu estantería, tu progreso y tus marcas en un solo archivo.",
    "escolha_uma_dimensao_para_explorar_sua": "Elige una forma de explorar tu biblioteca.",
    "capitulos": "Capítulos",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "La voz mantiene su tono. Esto se aplica a este libro y a los siguientes.",
    "ajuste_fino": "Ajuste fino",
    "timer_de_sono": "Temporizador de sueño",
    "o_audio_diminui_de_volume_aos_poucos_e": "El audio baja de volumen poco a poco y se pausa automáticamente.",
    "pontos_que_voce_guardou_neste_audioliv": "Puntos que guardaste en este audiolibro.",
    "ajustes_do_audio": "Ajustes de audio",
    "as_preferencias_ficam_salvas_para_todo": "Estas preferencias se conservan para todos los audiolibros.",
    "botao_de_voltar": "Botón de rebobinar",
    "botao_de_avancar": "Botón de avanzar",
    "recuar_ao_retomar": "Rebobinar al reanudar",
    "depois_de_uma_pausa_longa_volta_alguns": "Después de una pausa larga, retrocede unos segundos para que puedas retomar el hilo.",
    "tocar_ao_abrir": "Reproducir al abrir",
    "ao_tocar_em_um_audiolivro_na_estante_a": "Al tocar un audiolibro en la estantería, la reproducción comienza de inmediato.",
    "no_computador_espaco_toca_e_pausa_pula": "En un ordenador: espacio reproduce y pausa · ← → avanzar/retroceder · Shift + ← → cambiar de capítulo · ↑ ↓ volumen · B marcadores · [ ] velocidad.",
    "converter_pdf_para_epub": "Convertir PDF a EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "Prepara el libro para una lectura fluida y ajustable.",
    "confirmacao": "Confirmar",
    "confirmar": "Confirmar",
    "processando": "Procesando",
    "documento": "Documento",
    "buscar_livros_no_dispositivo": "Buscar libros en este dispositivo",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "Encuentra archivos EPUB, MOBI, CBZ, CBR y M4B ya guardados en tu dispositivo.",
    "juntar_em_um_unico_audiolivro": "¿Unir en un único audiolibro?",
    "titulo": "Título",
    "autor": "Autor",
    "importar_separados": "Importar por separado",
    "bem_vindo_ao_veredas_reader": "Bienvenido a Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "Tu biblioteca de lectura, completamente en tu propio dispositivo.",
    "buscar": "Buscar",
    "importar_livro": "Importar libro",
    "buscar_titulo_autor_tag": "Buscar título, autor, etiqueta...",
    "fechar_busca": "Cerrar búsqueda",
    "navegacao_da_biblioteca": "Navegación de la biblioteca",
    "fechar_menu": "Cerrar menú",
    "agrupar_livros": "Agrupar libros",
    "voltar": "Volver",
    "marcar_pagina": "Marcar página",
    "personalizar": "Preferencias",
    "navegacao_principal": "Navegación principal",
    "acoes_do_trecho": "Acciones del pasaje",
    "amarelo": "Amarillo",
    "verde": "Verde",
    "rosa": "Rosa",
    "azul": "Azul",
    "player_de_audiolivro": "Reproductor de audiolibros",
    "minimizar_player": "Minimizar reproductor",
    "minimizar": "Minimizar",
    "video_em_reproducao": "Vídeo en reproducción",
    "abrir_a_lista_de_capitulos": "Abrir la lista de capítulos",
    "posicao_no_audio": "Posición en el audio",
    "alternar_entre_o_progresso_do_capitulo": "Cambiar entre el progreso del capítulo y el progreso del libro completo",
    "capitulo_anterior": "Capítulo anterior",
    "voltar_15_segundos": "Retroceder 15 segundos",
    "reproduzir": "Reproducir",
    "avancar_30_segundos": "Avanzar 30 segundos",
    "proximo_capitulo": "Próximo capítulo",
    "velocidade_de_reproducao": "Velocidad de reproducción",
    "marcar_este_ponto": "Marcar este punto",
    "ver_marcadores": "Ver marcadores",
    "silenciar": "Silenciar",
    "volume": "Volumen",
    "audiolivro_em_reproducao": "Audiolibro en reproducción",
    "abrir_o_player": "Abrir el reproductor",
    "fechar_o_player": "Cerrar el reproductor",
    "fechar": "Cerrar",
    "trecho_anterior": "Pasaje anterior",
    "iniciar_leitura": "Iniciar lectura en voz alta",
    "proximo_trecho": "Pasaje siguiente",
    "escreva_seu_comentario_interpretacao_o": "Escribe tu comentario, interpretación o recordatorio...",
    "cancelar_importacao": "Cancelar importación",
    "nome_do_audiolivro": "Nombre del audiolibro",
    "nome_do_autor": "Nombre del autor",
    "idioma": "Idioma",
    "idioma_do_aplicativo": "Idioma de la aplicación",
    "o_aplicativo_segue_o_idioma_do_apare": "La aplicación sigue el idioma de tu dispositivo. Si el tuyo todavía no existe aquí, se abrirá en inglés.",
    "seguir_o_aparelho": "Seguir el dispositivo",
    "fazer_backup": "Hacer copia de seguridad ahora",
    "todos": "Todos",
    "lidos": "Finalizados",
    "pausados": "En pausa",
    "autores": "Autores",
    "tags": "Etiquetas",
    "grifar": "Resaltar",
    "anotar": "Nota",
    "enviar": "Enviar",
    "restaurar_padroes": "Restaurar valores predeterminados",
    "voltar_para_1": "Volver a 1×",
    "marcar_agora": "Marcar ahora",
    "escolher_pasta": "Elegir carpeta",
    "juntar_em_um_audiolivro": "Unir en un audiolibro",
    "sobre": "Acerca de",
    "licencas_de_codigo_aberto": "Licencias de código abierto",
    "configuracoes": "Configuración",
    "temas_e_idioma": "Temas e idioma"
  },
  "aviso": {
    "idioma_trocado": "Idioma cambiado."
  },
  "vn": {
    "quem_le": "Quién lee",
    "natural": "Natural",
    "do_sistema": "Del sistema",
    "nota_sistema": "Usa las voces instaladas en tu dispositivo. Para una lectura más humana, elige Natural.",
    "nota_sistema_com_natural": "La voz natural sigue descargada. Vuelve a Natural cuando quieras.",
    "voz_natural": "Voz natural",
    "gerada_no_aparelho": "Una voz mucho más humana, generada en tu propio dispositivo.",
    "progresso_download": "Progreso de la descarga",
    "x_de_y": "{x} de {y}",
    "aviso_arquivo": "La voz natural necesita que Veredas se abra desde la dirección de la aplicación, no como un archivo del ordenador. Mientras tanto, la lectura usa la voz del sistema.",
    "aviso_navegador": "Este navegador no tiene las funciones que necesita la voz natural. La lectura continúa con la voz del sistema.",
    "verificando": "Comprobando la voz natural…",
    "fato_download": "Descarga única de {tamanho}. Después, funciona sin conexión.",
    "fato_wifi": "Mejor con Wi-Fi. Puedes pausarla y continuar más tarde.",
    "fato_privacidade": "El texto del libro nunca sale de tu dispositivo.",
    "fato_idiomas": "Habla 31 idiomas, entre ellos español, inglés y portugués. Los demás siguen con la voz del sistema.",
    "baixar_voz_natural": "Descargar voz natural ({tamanho})",
    "licenca_curta": "Modelo Supertonic 3, de Supertone, con licencia OpenRAIL-M. Más detalles en Acerca de > Licencias de código abierto.",
    "pode_continuar_usando": "Puedes seguir leyendo mientras se descarga. Si se corta la conexión, la descarga continuará donde se quedó.",
    "pausar_download": "Pausar descarga",
    "erro_espaco": "No hay espacio suficiente en tu dispositivo para terminar la descarga. Libera espacio e inténtalo de nuevo.",
    "erro_offline": "Ahora mismo no hay conexión. Lo que ya se ha descargado se conserva.",
    "erro_rede": "La conexión se ha cortado durante la descarga. Lo que ya se ha descargado se conserva.",
    "download_pausado": "Descarga en pausa. Lo que ya se ha descargado se conserva.",
    "continuar_download": "Continuar",
    "descartar": "Descartar",
    "voz_feminina": "Femenina",
    "voz_feminina_desc": "Suave y tranquila",
    "voz_masculina": "Masculina",
    "voz_masculina_desc": "Cálida y serena",
    "parar_amostra": "Detener muestra",
    "ouvir_amostra_de": "Escuchar muestra: {voz}",
    "escolha_a_voz": "Elige la voz",
    "qualidade": "Calidad",
    "q_auto": "Automática",
    "q_rapida": "Rápida",
    "q_maxima": "Máxima",
    "q_auto_desc": "Se adapta sola al rendimiento de tu dispositivo para que la lectura no tenga pausas.",
    "q_rapida_desc": "Genera la voz más rápido. Ideal para dispositivos más sencillos.",
    "q_maxima_desc": "El sonido más cuidado. En dispositivos sencillos, puede provocar pausas entre frases.",
    "ocupa": "Ocupa {tamanho} en este dispositivo",
    "remover": "Eliminar",
    "baixar_pelos_dados": "¿Descargar con datos móviles?",
    "baixar_pelos_dados_msg": "Parece que tu móvil no está conectado a una red Wi-Fi. La descarga ocupa {tamanho} y puede consumir tu tarifa de datos.",
    "baixar_agora": "Descargar de todos modos",
    "pronta": "La voz natural está lista.",
    "download_interrompido": "La descarga se ha detenido. Toca Continuar cuando quieras.",
    "remover_titulo": "¿Eliminar la voz natural?",
    "descartar_titulo": "¿Descartar la descarga?",
    "remover_msg": "Esto libera {tamanho}. La lectura vuelve a la voz del sistema y puedes descargarla de nuevo cuando quieras.",
    "descartar_msg": "Se borrará lo que ya se ha descargado.",
    "removida": "Voz natural eliminada de este dispositivo.",
    "amostra_falhou": "No se ha podido reproducir la muestra en este dispositivo.",
    "amostra": "¡Hola! Así sonarán tus libros con la voz natural.",
    "gerando_voz": "Preparando la voz…",
    "automatico_idioma": "Automático ({idioma})",
    "automatico": "Automático",
    "so_voz_do_sistema": "voz del sistema",
    "aviso_idioma": "Idioma del texto: {idioma}. La voz natural todavía no habla este idioma, así que el libro se leerá con la voz del sistema.",
    "aviso_idioma_desconhecido": "No se ha podido reconocer el idioma de este texto. Elige el idioma abajo para usar la voz natural.",
    "aviso_falha": "La voz natural no ha podido funcionar ahora en este dispositivo. La lectura continúa con la voz del sistema.",
    "nao_carregou_usando_sistema": "La voz natural no se ha cargado en este dispositivo. Leyendo con la voz del sistema.",
    "parou_usando_sistema": "La voz natural se ha detenido. Continuando con la voz del sistema.",
    "aparelho_lento": "Este dispositivo está generando la voz despacio. Elige la calidad Rápida para evitar pausas.",
    "idioma_do_texto": "Idioma del texto",
    "idioma_do_texto_dica": "Detectado a partir del propio texto. Cámbialo si la pronunciación no suena bien.",
    "leitura_em_voz_alta": "Lectura en voz alta",
    "lento_usando_sistema": "La voz natural va demasiado lenta en este dispositivo. Sigue la lectura con la voz del sistema.",
    "aviso_lento": "Este dispositivo no consigue generar la voz natural a la velocidad de la lectura, así que la voz del sistema ha tomado el relevo por ahora.",
    "sem_memoria_usando_sistema": "La voz natural no cupo en la memoria de este dispositivo. Se lee con la voz del sistema.",
    "aviso_falha_memoria": "No hubo memoria suficiente para la voz natural en este dispositivo. Cerrar otras apps y volver a intentarlo suele funcionar; mientras tanto, la lectura usa la voz del sistema.",
    "copiar_detalhe": "Copiar detalle",
    "copiado": "Detalle copiado."
  }
});
