/* ============================================================
   FILIPINO (PILIPINAS) — pagsasalin
   ------------------------------------------------------------
   Parehong mga key ang ginagamit ng source at lahat ng ibang
   wika. Ang mga key ay hindi kailanman binabago.

   TUNGKOL SA PLURAL / SOBRE O PLURAL
   ----------------------------------
   Sa Filipino, ang "one"/"other" ng CLDR ay hindi singular/plural:
   ang hati ay ayon sa huling digit — 4, 6 at 9 lamang ang napupunta
   sa "other". Kaya ang 7 ay "one" at ang 9 ay "other", na walang
   kinalaman sa dami.

   Em filipino, o "one"/"other" do CLDR NÃO é singular/plural: a
   divisão é pelo último dígito — só 4, 6 e 9 caem em "other". Sete
   seria "one" e nove seria "other", o que não tem nada a ver com
   quantidade. Como depois de um numeral o "mga" é dispensável (e
   soa errado para muita gente), as duas formas aqui são iguais, na
   versão sem "mga": assim a frase sai certa com qualquer número.
   ============================================================ */
Idiomas.registrar('fil', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "Na-delete ang bookmark.",
    "excluir_marcador": "I-delete ang bookmark",
    "o_marcador_sera_removido_permanentemen": "Permanenteng tatanggalin ang bookmark.",
    "excluir_marcador_2": "I-delete ang bookmark?",
    "pagina_salva": "Nai-save ang page",
    "anotacoes": "Mga tala",
    "citacoes": "Mga sipi",
    "item_excluido": "Na-delete ang item.",
    "este_registro_sera_removido_permanente": "Permanenteng tatanggalin ang entry na ito mula sa library.",
    "configuracoes_padrao_restauradas": "Naibalik ang default na mga setting.",
    "leitura_da_esquerda_para_a_direita": "Pagbasa mula kaliwa pakanan.",
    "leitura_da_direita_para_a_esquerda_man": "Pagbasa mula kanan pakaliwa (manga).",
    "a_pagina_inteira_passa_a_caber_na_tela": "Kasya na ngayon ang buong page sa screen.",
    "a_pagina_passa_a_ocupar_toda_a_largura": "Sasakupin na ngayon ng page ang buong lapad ng screen.",
    "virada_sem_animacao_ativada": "Naka-on ang page turn na walang animation.",
    "virada_deslizante_ativada": "Naka-on ang sliding page turn.",
    "virada_em_folha_real_ativada": "Naka-on ang real-paper page turn.",
    "padrao_automatico_cada_formato_abre_no": "Awtomatiko: bumubukas ang bawat format sa direksiyong pinakaangkop dito.",
    "mudando_durante_a_leitura_o_ajuste_fic": "Kapag binago mo ito habang nagbabasa, para sa librong ito lang ang pagbabago.",
    "automatico_usa_rolagem_horizontal_para": "Sa awtomatikong mode, horizontal ang paging para sa EPUB, MOBI, TXT, MD at comics, at vertical ang scrolling para sa PDF at DOCX.",
    "este_livro": "ang librong ito",
    "armazenamento_local_indisponivel_neste": "Hindi available ang local storage sa browser na ito.",
    "o_aplicativo_pode_procurar_os_livros_q": "Maaaring hanapin ng app ang mga librong nasa device mo na.",
    "vamos_montar_sua_estante": "Punuin natin ang bookshelf mo?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "Hindi magagamit ang app nang walang pahintulot mo.",
    "precisamos_do_seu_aceite": "Kailangan namin ang pahintulot mo",
    "antes_de_comecar_leia_e_aceite_os_docu": "Bago magsimula, basahin at tanggapin ang mga dokumento sa ibaba.",
    "selecionar_todos": "Piliin lahat",
    "limpar_selecao": "I-clear ang selection",
    "todos_parecem_ja_estar_na_sua_estante": "Mukhang nasa bookshelf mo na ang lahat.",
    "lendo_a_pasta_escolhida": "Binabasa ang napili mong folder…",
    "procurando_livros": "Naghahanap ng mga libro",
    "nao_foi_possivel_concluir_a_busca_no_d": "Hindi natapos ang paghahanap sa device na ito.",
    "tente_outra_pasta_do_aparelho": "Subukan ang ibang folder sa device mo.",
    "nenhum_livro_encontrado": "Walang nahanap na libro",
    "use_o_botao_para_escolher_os_arquivos": "Gamitin ang + button para manu-manong pumili ng mga file. Sa mga Android phone, karaniwang hinahayaan ng Chrome na pumili ng buong folder.",
    "seu_navegador_nao_permite_ler_pastas": "Hindi makapagbasa ng mga folder ang browser mo",
    "busca_automatica_indisponivel": "Hindi available ang awtomatikong paghahanap",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR at M4B",
    "termos_de_uso": "Mga tuntunin ng paggamit",
    "politica_de_privacidade": "Patakaran sa privacy",
    "um_minuto_agora_evita_perder_o_progres": "Isang minuto ngayon ang makakaiwas sa pagkawala ng progress at marks mo sa ibang pagkakataon.",
    "ver_estante": "Tingnan ang bookshelf",
    "modo_juntar": "Mode ng pagsasama",
    "modo_substituir": "Mode ng pagpapalit",
    "restauracao_concluida": "Tapos na ang restore",
    "tente_de_novo_com_o_arquivo_original": "Subukan muli gamit ang orihinal na file.",
    "a_restauracao_nao_pode_ser_concluida": "Hindi natapos ang restore",
    "devolvendo_o_seu_progresso_e_as_suas_m": "Ibinabalik ang progress at marks mo...",
    "restaurar_este_backup": "I-restore ang backup na ito?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Piliin ang .zip na sinave ng Veredas o ang .txt na natanggap mo sa pagbabahagi.",
    "nao_foi_possivel_ler_este_arquivo": "Hindi mabasa ang file na ito",
    "lendo_o_backup": "Binabasa ang backup",
    "backup_do_veredas_reader": "Backup ng Veredas Reader",
    "arquivo_de_transporte_txt_contendo_os": "kopya ng backup sa .txt format, na may parehong nilalaman ng ZIP",
    "nao_foi_possivel_montar_o_arquivo_de_b": "Hindi mabuo ang backup file.",
    "escolher_o_app": "Piliin ang app",
    "vale_conferir_o_que_vai_no_arquivo": "Suriin kung ano ang nasa file",
    "enviar_para_outro_app": "Ipadala sa ibang app",
    "salvar_o_arquivo": "I-save ang file",
    "o_navegador_aqui_nao_oferece_o_compart": "Hindi nag-aalok ang browser na ito ng direktang pagbabahagi. Maaari mong i-save ang file at ipadala ito mamaya gamit ang app na gusto mo.",
    "este_aparelho_nao_abre_a_lista_de_apli": "Hindi binubuksan ng device na ito ang listahan ng apps",
    "importe_pelo_menos_um_livro_antes_de_f": "Mag-import muna ng kahit isang libro bago gumawa ng backup.",
    "estante_vazia": "Walang laman ang bookshelf",
    "nao_deu_para_copiar": "Hindi makopya",
    "copiar_detalhes": "Kopyahin ang mga detalye",
    "o_backup_foi_salvo_assim_mesmo": "Na-save pa rin ang backup",
    "o_aparelho_recusou_abrir_a_lista": "Hindi mabuksan ang listahan ng pagbabahagi",
    "sem_detalhes_do_navegador": "walang detalye mula sa browser",
    "o_sistema_nao_aceitou_receber_o_arquiv": "Hindi natanggap ng system ng device ang file.",
    "o_navegador_considerou_a_situacao_inse": "Hinarang ng browser ang pagbabahagi dahil sa sarili nitong security rule. I-save ang file at ipadala ito gamit ang app na gusto mo.",
    "o_compartilhamento_so_funciona_em_ende": "Gumagana lang ang pagbabahagi sa mga secure na address. Binubuksan ang app mula sa karaniwang http:// address at sa ganitong kaso hinaharang ng browser ang pagpapadala sa ibang apps.",
    "este_navegador_nao_conseguiu_iniciar_o": "Hindi mabuksan ng browser na ito ang pagbabahagi. I-save ang file at ipadala ito gamit ang app na gusto mo.",
    "o_navegador_recebeu_um_arquivo_em_form": "Hindi binuksan ng browser ang listahan ng mga app na mapagbabahagian. I-tap ulit ang button, o i-save ang file at ipadala ito gamit ang app na gusto mo.",
    "nao_foi_possivel_gerar_o_backup": "Hindi nagawa ang backup.",
    "reunindo_a_sua_estante": "Kinokolekta ang bookshelf mo...",
    "preparando_o_backup": "Inihahanda ang backup",
    "pronto_nada_mais_esta_esperando": "Tapos na — wala nang naghihintay.",
    "o_progresso_e_as_marcacoes_desses_livr": "Mabubura ang progress at marks ng mga librong iyon. Kung i-import mo ang mga file mamaya, babalik silang walang marks.",
    "descartar_o_que_esta_esperando": "Burahin ang mga naghihintay na data?",
    "lembretes_de_backup_religados": "Muling binuksan ang mga backup reminder.",
    "sem_titulo": "Walang pamagat",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "Naka-off ang mga reminder.",
    "manter_ligado": "Panatilihing naka-on",
    "desligar_assim_mesmo": "I-off pa rin",
    "o_botao_de_salvar_continua_onde_sempre": "Nananatili ang Save button sa dati nitong lugar, sa Backup at restore.",
    "o_lembrete_e_o_unico_aviso_que_existe": "Ang reminder ang tanging babala. Kung wala ito, kakailanganin mong tandaan nang mag-isa na mag-backup.\n\n",
    "limpar_os_dados_do_navegador_desinstal": "Kung ma-clear ang browser data, ma-uninstall ang app, magpalit ka ng phone o masira ang device, hindi na mababawi ang progress, highlights, quotes, notes at bookmarks mo.\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "Sa device lang na ito umiiral ang bookshelf mo. Walang kopya sa server, kaya hindi namin ito mababawi para sa iyo.\n\n",
    "leia_antes_de_confirmar": "Basahin bago kumpirmahin",
    "desligar_os_lembretes_de_backup": "I-off ang mga backup reminder?",
    "progresso_de_leitura_restaurado_neste": "Naibalik ang reading progress para sa librong ito.",
    "pronto": "Tapos na.",
    "aplicando_as_suas_preferencias": "Inilalapat ang mga preference mo...",
    "atualize_o_veredas_reader_e_tente_de_n": "I-update ang Veredas Reader at subukan muli.",
    "este_backup_foi_feito_numa_versao_mais": "Ginawa ang backup na ito gamit ang mas bagong bersyon ng app.",
    "este_arquivo_nao_e_um_backup_de_biblio": "Hindi ito Veredas library backup.",
    "o_conteudo_interno_nao_pode_ser_lido": "Hindi mabasa ang laman sa loob.",
    "o_backup_esta_corrompido": "Sira ang backup.",
    "falta_o_arquivo_biblioteca_json_la_den": "Wala ang biblioteca.json file sa loob nito.",
    "este_arquivo_nao_parece_ser_um_backup": "Mukhang hindi ito Veredas backup.",
    "compactando": "Kino-compress...",
    "para_restaurar_menu_lateral_backup_e_r": "Para mag-restore: side menu > Backup at restore > Restore backup.",
    "o_veredas_devolve_sozinho_as_marcacoes": "awtomatikong ibinabalik ng Veredas ang marks at ang lugar kung saan ka huminto.",
    "importe_os_livros_normalmente_no_aplic": "i-import ang mga libro nang normal sa app: kapag nakilala na ang bawat file,",
    "ele_nao_contem_os_arquivos_dos_livros": "HINDI nito kasama ang mga book file. Para kumpletong maibalik,",
    "as_notas_os_marcadores_e_a_organizacao": "ang notes, bookmarks at ayos ng bookshelf mo.",
    "este_arquivo_guarda_o_seu_progresso_de": "Nasa file na ito ang reading progress, highlights, quotes,",
    "verificando_se_sao_partes_do_mesmo_aud": "Sinusuri kung bahagi ang mga ito ng parehong audiobook...",
    "analisando_os_arquivos": "Sinusuri ang mga file",
    "nao_foi_possivel_salvar_o_audiolivro": "Hindi ma-save ang audiobook.",
    "audiolivros_grandes_podem_levar_alguns": "Maaaring tumagal nang kaunti ang malalaking audiobook...",
    "salvando_na_sua_estante": "Sine-save sa bookshelf mo",
    "falha_ao_processar_os_arquivos": "Hindi ma-process ang mga file.",
    "falha_ao_processar_o_arquivo": "Hindi ma-process ang file.",
    "nao_foi_possivel_salvar_o_quadrinho": "Hindi ma-save ang comic.",
    "quase_la": "Malapit na...",
    "falha_ao_processar_o_quadrinho": "Hindi ma-process ang comic.",
    "autor_desconhecido": "Hindi kilalang author",
    "lendo_o_quadrinho": "Binabasa ang comic...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "Hindi ma-save ang libro sa library.",
    "nao_foi_possivel_ler_o_pdf": "Hindi mabasa ang PDF.",
    "lendo_o_pdf": "Binabasa ang PDF...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "Kung lumang .doc ito, buksan sa Word at i-save bilang .docx bago i-import.",
    "este_arquivo_nao_e_um_docx_valido": "Hindi valid na .docx ang file na ito.",
    "livros_com_protecao_da_amazon_nao_pode": "Hindi mabubuksan dito ang mga librong may Amazon protection. Gumamit ng kopyang walang DRM o i-convert ang libro sa EPUB.",
    "este_arquivo_esta_protegido_por_drm": "Protektado ng DRM ang file na ito.",
    "confira_se_a_extensao_corresponde_ao_c": "Tiyaking tugma ang extension sa laman, o i-convert ang libro sa EPUB.",
    "este_arquivo_nao_e_um_mobi_valido": "Hindi valid na MOBI ang file na ito.",
    "nao_foi_possivel_ler_o_arquivo": "Hindi mabasa ang file.",
    "formato_nao_suportado": "Hindi suportadong format.",
    "falha_ao_salvar_o_livro_na_biblioteca": "Hindi ma-save ang libro sa library.",
    "livro_importado_e_salvo_no_dispositivo": "Na-import at na-save ang libro sa device na ito.",
    "audiolivro_importado_e_salvo_no_dispos": "Na-import at na-save ang audiobook sa device na ito.",
    "quadrinho_importado_e_salvo_no_disposi": "Na-import at na-save ang comic sa device na ito.",
    "salvando_na_sua_estante_2": "Sine-save sa bookshelf mo...",
    "importando_livro": "Ini-import ang libro",
    "importar_mesmo_assim": "I-import pa rin",
    "parece_que_este_livro_ja_esta_na_estan": "Mukhang nasa bookshelf mo na ang librong ito",
    "este_livro_ja_esta_na_estante": "Nasa bookshelf mo na ang librong ito",
    "video_importado_e_salvo_no_dispositivo": "Na-import at na-save ang video sa device na ito.",
    "importacao_cancelada": "Kinansela ang import.",
    "preparando_o_arquivo": "Inihahanda ang file",
    "importando_audiolivro": "Ini-import ang audiobook",
    "importacao_concluida": "Tapos na ang import",
    "importacao_interrompida": "Itinigil ang import",
    "a_importacao_foi_interrompida_o_que_ja": "Itinigil ang import; mananatili sa bookshelf mo ang mga naidagdag na.",
    "finalizando": "Tinatapos…",
    "nao_foi_possivel_ler_o_arquivo_2": "hindi mabasa ang file",
    "importando_livros": "Ini-import ang mga libro",
    "livros_quadrinhos_documentos_audiolivr": "Mga libro, comics, dokumento, audiobook at video",
    "series": "Mga serye",
    "colecoes": "Mga koleksyon",
    "organizacao_salva": "Na-save ang organization.",
    "informe_um_nome_para_o_livro_antes_de": "Bigyan ng pangalan ang libro bago i-save.",
    "nome_do_livro_obrigatorio": "Kailangan ng pangalan ang libro",
    "importe_um_livro_primeiro": "Mag-import muna ng libro.",
    "citacao": "sipi",
    "anotacao": "tala",
    "citacao_2": "Sipi",
    "anotacao_2": "Tala",
    "uma_citacao": "isang sipi",
    "uma_anotacao": "isang tala",
    "o_marcador_sera_removido_da_biblioteca": "Aalisin ang bookmark sa library, pero mananatiling buo ang book file.",
    "marcador_de_audio": "Bookmark ng audio",
    "marcador_de_video": "Bookmark ng video",
    "nao_foi_possivel_excluir_o_livro": "Hindi ma-delete ang libro.",
    "livro_excluido_da_biblioteca": "Na-delete ang libro mula sa library.",
    "excluir_livro": "I-delete ang libro",
    "isso_remove_apenas_a_copia_armazenada": "Inaalis lang nito ang kopyang itinatago ng library, kasama ang progress, bookmarks at notes. Hindi mabubura ang orihinal na file sa sarili mong folder.",
    "excluir_livro_2": "I-delete ang libro?",
    "ordem_personalizada_salva": "Na-save ang custom order.",
    "ordem_manual_da_sua_estante": "Ang bookshelf mo, ayon sa pagkakaayos na itinakda mo.",
    "agrupamento_alterado_para_minha_ordem": "Pinalitan ang grouping ng My Order.",
    "nova_ordem_salva": "Na-save ang bagong order.",
    "nao_foi_possivel_salvar_a_nova_ordem": "Hindi ma-save ang bagong order.",
    "baixar_automaticamente": "Awtomatikong i-download",
    "escolha_livremente_onde_o_arquivo_sera": "Malaya mong piliin kung saan ise-save ang file.",
    "salvar_epub": "I-save ang EPUB",
    "livro_epub": "EPUB na libro",
    "erro_desconhecido": "hindi kilalang error",
    "a_permissao_para_salvar_o_arquivo_foi": "Kinansela ang pahintulot na i-save ang file. Walang binago sa library.",
    "conversao_cancelada_o_pdf_original_per": "Kinansela ang conversion. Nananatili sa library ang orihinal na PDF.",
    "preparando_salvamento": "Inihahanda ang pag-save…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "Hindi available sa library ang kopya ng PDF.",
    "reconstruindo_o_livro_localmente": "Muling binubuo ang libro sa device mo.",
    "convertendo_pdf": "Kino-convert ang PDF",
    "nao_foi_possivel_compartilhar_o_livro": "Hindi ma-share ang libro.",
    "o_arquivo_foi_preparado_para_voce_comp": "Handa na ang file para i-share sa ibang app.",
    "livro_compartilhado": "Na-share ang libro.",
    "a_copia_deste_livro_nao_esta_disponive": "Hindi available sa library ang kopya ng librong ito.",
    "para_manter_a_politica_de_compartilham": "Para mapanatili ang sharing policy ng library, hindi maaaring i-share ng app na ito ang EPUB at MOBI files.",
    "quadrinhos_ficam_guardados_somente_no": "Sa device mo lang itinatago ang comics at hindi sila maaaring i-share ng app na ito.",
    "audiolivros_e_videos_ficam_guardados_s": "Sa device mo lang itinatago ang audiobooks at videos at hindi sila maaaring i-share ng app na ito.",
    "formato_protegido": "Protected na format",
    "compartilhamento_indisponivel": "Hindi available ang sharing",
    "concluido": "Tapos na",
    "ainda_nao_comecado": "Hindi pa nagsisimula",
    "continue_lendo": "Ipagpatuloy ang pagbabasa",
    "continue_ouvindo": "Ipagpatuloy ang pakikinig",
    "continue_assistindo": "Ipagpatuloy ang panonood",
    "comece_por_aqui": "Magsimula rito",
    "comece_a_ouvir": "Simulan ang pakikinig",
    "comece_a_assistir": "Simulan ang panonood",
    "no_total": "kabuuan",
    "para_ler": "babasahin",
    "sua_estante": "Ang bookshelf mo",
    "livros_organizados_pela_opcao_selecion": "Inayos ang mga libro ayon sa pinili mong option.",
    "uma_prateleira_para_cada_tipo_de_arqui": "Isang shelf para sa bawat uri ng file.",
    "autores_agrupados_em_ordem_alfabetica": "Mga author na nakaayos ayon sa alpabeto.",
    "toque_para_continuar_de_onde_parou": "I-tap para magpatuloy kung saan ka tumigil.",
    "para_ler_2": "Babasahin",
    "lendo_agora": "Kasalukuyang binabasa",
    "audio_e_video": "Audio at video",
    "trechos_salvos_separadamente_dos_marca": "Mga passage na hiwalay na naka-save mula sa bookmarks.",
    "comentarios_vinculados_a_trechos_selec": "Mga komentong naka-link sa mga napili mong passage.",
    "paginas_salvas_para_voltar_rapidamente": "Mga page na naka-save para mabilis mong mabalikan.",
    "do_maior_para_o_menor_progresso_de_lei": "Mula sa pinakamataas hanggang pinakamababang reading progress.",
    "livros_adicionados_ou_lidos_mais_recen": "Mga librong pinakakamakailang idinagdag o binasa.",
    "ordem_alfabetica_pelo_titulo": "Nakaalpabetong ayos ayon sa title.",
    "separa_em_prateleiras_de_epub_pdf_docx": "Hinahati sa magkakahiwalay na shelf ang EPUB, PDF, DOCX, audiobooks, videos…",
    "tipo_de_arquivo": "Uri ng file",
    "organiza_e_separa_os_livros_por_autor": "Inaayos at pinaghihiwalay ang mga libro ayon sa author.",
    "agrupar_por_autor": "I-group ayon sa Author",
    "pressione_o_livro_e_mova_o": "Pindutin nang matagal ang libro, saka ilipat.",
    "minha_ordem": "Aking Ayos",
    "epub_pronto": "Handa na ang EPUB",
    "conversao_concluida": "Tapos na ang conversion",
    "necessario_para_salvar_o_epub_ao_lado": "Kailangan para ma-save ang EPUB katabi ng orihinal",
    "escolha_a_pasta_do_pdf": "Piliin ang folder ng PDF",
    "processando": "Pinoproseso…",
    "processamento_local_no_navegador": "Na-process sa device mo, sa browser",
    "convertendo_livro": "Kino-convert ang libro",
    "livro_em_pdf": "PDF na libro",
    "recalculando_paginas": "Muling kinakalkula ang mga page...",
    "ajustando_leitura": "Inaayos ang layout",
    "abrir_comentario": "Buksan ang comment",
    "anotacao_salva": "Na-save ang note.",
    "anotacao_atualizada": "Na-update ang note.",
    "escreva_uma_nota_antes_de_salvar": "Sumulat muna ng note bago i-save.",
    "nao_foi_possivel_compartilhar": "Hindi ma-share.",
    "compartilhamento_indisponivel_2": "Hindi available ang sharing.",
    "trecho_copiado": "Nakopya ang passage.",
    "trecho_compartilhado": "Na-share ang passage.",
    "citacao_salva": "Na-save ang quote.",
    "trecho_grifado": "Na-highlight ang passage.",
    "grifo_removido": "Inalis ang highlight.",
    "comentario_apagado": "Na-delete ang comment.",
    "remover_grifo": "Alisin ang highlight",
    "apagar_comentario": "I-delete ang comment",
    "remover_grifo_2": "Alisin ang highlight?",
    "apagar_comentario_2": "I-delete ang comment?",
    "remover_este_grifo": "Alisin ang highlight na ito?",
    "apagar_este_comentario": "I-delete ang comment na ito?",
    "sem_comentario": "Walang comment",
    "comentario": "Komento",
    "marcador_removido_desta_pagina": "Inalis ang bookmark sa page na ito.",
    "pagina_adicionada_aos_marcadores": "Idinagdag ang page sa bookmarks mo.",
    "este_e_o_inicio_do_livro": "Ito ang simula ng libro.",
    "esta_e_a_primeira_pagina": "Ito ang unang page.",
    "voce_chegou_ao_fim_do_livro": "Nakarating ka na sa dulo ng libro.",
    "voce_chegou_ao_fim_do_quadrinho": "Nakarating ka na sa dulo ng comic.",
    "agora_em_revista_aberta_duas_paginas_l": "Ngayon bilang spread: dalawang page na magkatabi, habang mag-isa ang cover.",
    "leitura_horizontal_ativada_neste_livro": "Naka-on ang horizontal reading para sa librong ito.",
    "rolagem_vertical_ativada_neste_livro": "Naka-on ang vertical scrolling para sa librong ito.",
    "leitura_pagina_a_pagina_ativada_neste": "Naka-on ang page-by-page reading para sa comic na ito.",
    "rolagem_continua_ativada_neste_quadrin": "Naka-on ang continuous scrolling para sa comic na ito.",
    "mudar_para_rolagem_vertical": "Lumipat sa vertical scrolling",
    "mudar_para_leitura_horizontal": "Lumipat sa horizontal reading",
    "rolagem_continua_estilo_webtoon": "Tuloy-tuloy na pag-scroll (estilong webtoon)",
    "voltar_para_pagina_a_pagina": "Bumalik sa page by page",
    "separando_os_capitulos": "Pinaghihiwalay ang mga chapter...",
    "lendo_o_livro": "Binabasa ang libro",
    "lendo_o_markdown": "Binabasa ang Markdown",
    "lendo_o_documento": "Binabasa ang dokumento",
    "pagina_indisponivel": "Hindi available ang page.",
    "isto_acontece_so_desta_vez": "Isang beses lang ito nangyayari.",
    "preparando_o_quadrinho": "Inihahanda ang comic",
    "abrindo_o_quadrinho": "Binubuksan ang comic...",
    "montando_as_paginas": "Binubuo ang mga page...",
    "nao_foi_possivel_abrir_este_livro": "Hindi mabuksan ang librong ito.",
    "abertura_cancelada": "Kinansela ang pagbubukas.",
    "o_livro_demorou_demais_para_abrir_e_fo": "Masyadong matagal magbukas ang libro kaya itinigil ito.",
    "importe_o_arquivo_novamente_para_conti": "I-import muli ang file para magpatuloy sa pagbabasa.",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "Wala na sa device mo ang file ng librong ito.",
    "preparando_sua_leitura": "Inihahanda ang babasahin mo...",
    "abrindo_livro": "Binubuksan ang libro",
    "leitura_concluida": "Tapos na ang pagbabasa.",
    "a_voz_foi_interrompida_pelo_navegador": "Pinatigil ng browser ang boses.",
    "nao_foi_possivel_preparar_este_trecho": "Hindi maihanda para sa audio ang passage na ito.",
    "a_leitura_em_voz_alta_nao_e_suportada": "Hindi sinusuportahan ng browser na ito ang read aloud.",
    "pausar_leitura": "I-pause ang pagbabasa",
    "em_pausa": "Naka-pause",
    "leitura_em_voz_alta_nao_disponivel_nes": "Hindi available ang read aloud sa browser na ito",
    "nome_do_marcador": "Pangalan ng bookmark",
    "o_marcador_sera_removido_deste_audioli": "Aalisin ang bookmark sa audiobook na ito.",
    "nao_foi_possivel_salvar_o_marcador": "Hindi ma-save ang bookmark.",
    "ja_existe_um_marcador_neste_ponto": "May bookmark na sa lugar na ito.",
    "timer_de_sono_encerrado": "Tapos na ang sleep timer.",
    "fim_do_cap": "Dulo ng ch.",
    "timer_desativado": "Na-off ang timer.",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "Ipa-pause ang audio sa dulo ng chapter.",
    "este_audiolivro_nao_tem_capitulos": "Walang chapter ang audiobook na ito.",
    "ao_fim_do_capitulo": "Sa dulo ng chapter",
    "desativar_timer": "I-off ang timer",
    "mais_10_minutos_no_timer": "10 minuto pa sa timer.",
    "somar_10_minutos": "Magdagdag ng 10 minuto",
    "pausa_ao_fim_do_capitulo": "I-pause sa dulo ng chapter",
    "no_livro_todo": "Sa buong libro",
    "video": "Video",
    "audiolivro_concluido": "Tapos na ang audiobook.",
    "video_concluido": "Tapos na ang video.",
    "video_2": "video",
    "audio": "audio",
    "toque_em_reproduzir_para_comecar": "I-tap ang play para magsimula.",
    "falha_ao_carregar_o_audio": "Hindi ma-load ang audio.",
    "exclua_o_da_biblioteca_e_importe_o_arq": "I-delete ito sa library at i-import muli ang file.",
    "os_nomes_dos_arquivos_seguem_uma_seque": "Sunod-sunod ang mga pangalan ng file, kaya mukhang mga chapter ng iisang audiobook.",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "Pareho ang album sa tags ng mga file, kaya mukhang mga chapter ng iisang audiobook.",
    "libere_espaco_ou_exclua_livros_da_bibl": "Magbakante ng space o mag-delete ng mga libro sa library at subukan muli.",
    "o_armazenamento_do_aparelho_esta_cheio": "Puno na ang storage ng device mo.",
    "preparando_a_capa": "Inihahanda ang cover...",
    "remova_esse_arquivo_da_selecao_e_tente": "Alisin ang file na iyon sa selection at subukan muli.",
    "sequencia": "Pagkakasunod-sunod",
    "o_arquivo_pode_estar_incompleto_tente": "Maaaring hindi kumpleto ang file. Subukang i-download muli.",
    "conferindo_se_o_audio_pode_ser_reprodu": "Sinusuri kung maaaring i-play ang audio...",
    "conferindo_se_o_video_pode_ser_reprodu": "Sinusuri kung maaaring i-play ang video...",
    "lendo_titulo_capitulos_e_capa": "Binabasa ang title, chapters at cover...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "Maaaring sira ang file o nasa audio format na hindi mape-play ng browser. Subukang i-convert ito sa MP3 o M4B (AAC).",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "Maaaring sira ang file o nasa video format na hindi mape-play ng browser. Subukang i-convert ito sa MP4 na may H.264 video at AAC audio.",
    "converta_o_audiolivro_para_m4b_com_aud": "I-convert ang audiobook sa M4B na may AAC audio (o MP3) at i-import muli.",
    "converta_o_video_para_mp4_com_audio_aa": "I-convert ang video sa MP4 na may AAC audio at H.264 video at i-import muli.",
    "o_navegador_nao_reproduz_o_formato_de": "Hindi mapi-play ng browser ang audio format ng file na ito.",
    "arquivos_com_protecao_nao_podem_ser_re": "Hindi mapi-play dito ang protected files. Gumamit ng kopyang walang DRM.",
    "nao_ha_espaco_suficiente_no_aparelho_p": "Kulang ang space sa device mo para sa audiobook na ito.",
    "confira_se_a_extensao_corresponde_ao_c_2": "Tiyaking tugma ang extension sa laman, o i-convert ang audio sa MP3 o M4B (AAC).",
    "imagem_invalida": "invalid na image",
    "imagem_demorou_demais": "masyadong natagalan ang pag-load ng image",
    "imagem_vazia": "walang laman na image",
    "inicio": "Simula",
    "mp4_moov_nao_encontrado": "Mukhang hindi kumpleto o sira ang video.",
    "pagina": "Pahina",
    "esta_pagina_nao_esta_disponivel": "Hindi available ang page na ito.",
    "esta_pagina_nao_pode_ser_descompactada": "Hindi ma-unpack ang page na ito.",
    "quadrinho_fechado": "Sarado ang comic.",
    "ele_pode_estar_incompleto_dividido_em": "Maaaring hindi ito kumpleto, nahati sa ilang bahagi, o gumagamit ng RAR variant na hindi nakikilala ng app. Karaniwang naaayos ito kapag kino-convert sa CBZ.",
    "remova_a_senha_do_arquivo_e_importe_de": "Alisin ang password ng file at i-import itong muli.",
    "nao_foi_possivel_ler_este_arquivo_de_q": "Hindi mabasa ang comic file na ito.",
    "este_quadrinho_esta_protegido_por_senh": "Protektado ng password ang comic na ito.",
    "lendo_o_indice_do_quadrinho": "Binabasa ang index ng comic...",
    "o_arquivo_pode_ser_grande_demais_para": "Maaaring masyadong malaki ang file para sa memory ng device na ito. Karaniwang naaayos ito kapag hinati ang comic sa mas maliliit na bahagi.",
    "nao_foi_possivel_abrir_este_quadrinho": "Hindi mabuksan ang comic na ito.",
    "lendo_o_arquivo": "Binabasa ang file...",
    "preparando_o_leitor_de_cbr": "Inihahanda ang CBR reader...",
    "o_arquivo_pode_estar_incompleto_proteg": "Maaaring hindi kumpleto, protektado ng password o sira ang file.",
    "nao_foi_possivel_ler_este_quadrinho": "Hindi mabasa ang comic na ito.",
    "o_arquivo_precisa_conter_imagens_jpg_p": "Kailangang may mga image ang file (JPG, PNG, WEBP o GIF).",
    "nao_encontramos_paginas_dentro_deste_q": "Walang nakitang page sa comic na ito.",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "Kulang ang space sa device mo para sa comic na ito.",
    "cabecalho_de_item_invalido": "May sirang bahagi ang file.",
    "a_pasta_vendor_libarchive_precisa_esta": "May kulang na component ng app para mabuksan ang comic na ito. I-convert ito sa CBZ o i-reinstall ang app.",
    "o_leitor_de_cbr_nao_foi_encontrado": "Hindi nakita ang CBR reader.",
    "converta_o_quadrinho_para_cbz_zip_e_im": "I-convert ang comic sa CBZ (ZIP) at i-import muli.",
    "este_navegador_nao_consegue_abrir_arqu": "Hindi makapagbukas ng CBR files ang browser na ito.",
    "convertendo_o_markdown": "Kino-convert ang Markdown",
    "lendo_o_texto": "Binabasa ang text",
    "pdf_indisponivel": "Hindi available ang PDF.",
    "epub_invalido_nenhum_capitulo_no_spine": "Sira ang EPUB na ito: hindi mahanap ang mga chapter ng libro.",
    "livro_sem_titulo": "Walang pamagat na libro",
    "epub_invalido_arquivo_opf_nao_encontra": "Hindi kumpleto o sira ang EPUB na ito kaya hindi ito mabuksan.",
    "epub_invalido_container_xml_nao_encont": "Hindi kumpleto o sira ang EPUB na ito kaya hindi ito mabuksan.",
    "organizando_o_texto": "Inaayos ang text",
    "descompactando_o_livro": "Ina-unpack ang libro",
    "nao_encontramos_conteudo_para_exibir_n": "Walang nakitang maipapakita sa file na ito.",
    "livro_sem_texto_legivel": "Libro na walang mababasang text",
    "o_arquivo_pode_estar_corrompido_tente": "Maaaring sira ang file. Subukang i-convert ito sa EPUB.",
    "nao_foi_possivel_extrair_o_texto_deste": "Hindi ma-extract ang text mula sa MOBI na ito.",
    "nenhum_registro_de_conteudo_foi_encont": "Hindi mahanap ang text ng libro sa file na ito.",
    "arquivo_mobi_sem_texto": "MOBI file na walang text.",
    "o_dicionario_de_compressao_esta_vazio": "May kulang na bahagi ng content ng MOBI na ito.",
    "arquivo_mobi_incompleto": "Hindi kumpletong MOBI file.",
    "as_tabelas_de_compressao_nao_foram_enc": "May kulang na bahagi ng content ng MOBI na ito.",
    "converta_o_arquivo_para_epub_em_um_pro": "I-convert ang file sa EPUB gamit ang program tulad ng Calibre at i-import muli.",
    "compressao_mobi_nao_reconhecida": "Gumagamit ang MOBI na ito ng internal format na hindi kilala ng app.",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "Hindi mabasa ang header ng libro.",
    "arquivo_mobi_corrompido": "Sira ang MOBI file.",
    "a_lista_interna_de_registros_esta_inco": "Hindi kumpleto ang file. Subukang i-download o i-convert ito ulit.",
    "o_download_parece_ter_sido_interrompid": "Mukhang naantala ang download. I-download muli ang file.",
    "tabela_de_compressao_mobi_corrompida": "May sirang bahagi ang MOBI file na ito.",
    "tabela_de_compressao_mobi_incompleta": "Hindi kumpleto ang MOBI file na ito.",
    "tabela_de_compressao_mobi_invalida": "May sirang bahagi ang MOBI file na ito.",
    "este_arquivo_docx_nao_tem_conteudo_de": "Walang text content na maipapakita ang .docx file na ito.",
    "documento_sem_texto": "Dokumentong walang text",
    "o_arquivo_pode_estar_corrompido_proteg": "Maaaring sira, protektado ng password, o lumang .doc ang file. I-save muli bilang .docx at i-import ulit.",
    "nao_foi_possivel_ler_este_arquivo_docx": "Hindi mabasa ang DOCX file na ito.",
    "convertendo_o_documento": "Kino-convert ang dokumento",
    "conecte_se_a_internet_uma_vez_para_bai": "Kumonekta sa internet nang isang beses para i-download ang component, pagkatapos ay buksan muli ang libro.",
    "o_conversor_de_docx_nao_carregou": "Hindi nag-load ang DOCX converter.",
    "video_mp4": "Video (MP4)",
    "audiolivro_m4b": "Audiolibro (M4B)",
    "audiolivro_mp3": "Audiolibro (MP3)",
    "quadrinho_cbt": "Komiks (CBT)",
    "quadrinho_cb7": "Komiks (CB7)",
    "quadrinho_cbr": "Komiks (CBR)",
    "quadrinho_cbz": "Komiks (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "Teksto (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "Kinansela ang pag-save.",
    "o_arquivo_esta_vindo_do_armazenamento": "Kumukuha ng file mula sa cloud storage papunta sa device mo.",
    "baixando_o_arquivo": "Dina-download ang file",
    "cancelando": "Kinakansela...",
    "use_grifar_citacao_anotar_ou_marcador": "Gamitin ang Highlight, Quote, Note o Bookmark habang nagbabasa.",
    "nenhuma_marcacao_ainda": "Wala pang marks",
    "trecho_original": "Orihinal na passage",
    "procurar_meus_livros": "Hanapin ang mga libro ko",
    "a_busca_fica_sempre_disponivel_no_menu": "Palaging available ang search sa side menu, sa ilalim ng System.",
    "da_para_fazer_depois": "Maaari mo itong gawin mamaya",
    "nada_entra_na_estante_sem_a_sua_confir": "Walang mapupunta sa bookshelf mo nang wala ang pagsang-ayon mo: makikita mo ang listahan at pipiliin ang gusto mong i-import.",
    "voce_revisa_antes": "Ikaw muna ang nagre-review",
    "escolha_uma_pasta_downloads_e_um_bom_c": "Pumili ng folder (magandang simula ang Downloads) at hahanapin iyon ng app kasama ang lahat ng subfolder.",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "Naghahanap ng EPUB, MOBI, CBZ, CBR at M4B",
    "voltar_e_revisar": "Bumalik at mag-review",
    "ler_os_termos": "Basahin ang mga tuntunin",
    "ler_a_politica": "Basahin ang policy",
    "os_dois_documentos_ficam_sempre_dispon": "Palaging available ang dalawang dokumento sa side menu, sa ilalim ng About.",
    "leia_com_calma": "Maglaan ng oras",
    "a_politica_e_os_termos_explicam_como_o": "Ipinapaliwanag ng policy at mga tuntunin kung paano iniingatan ng app ang mga libro mo at kung ano ang maaari mong gawin sa mga ito. Para magamit ang library, kailangan mong sumang-ayon sa mga ito.",
    "nada_acontece_sem_o_aceite": "Para makapagsimula, kailangang tanggapin ang mga tuntunin",
    "aceitar_e_continuar": "Tanggapin at magpatuloy",
    "nao_aceito": "Hindi ako sang-ayon",
    "termos_de_uso_2": "Mga Tuntunin ng Paggamit",
    "politica_de_privacidade_2": "Patakaran sa Privacy",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "Ang app ay uma-access lamang sa mga file at folder na pinili mo, kapag pinili mo ang mga ito.",
    "voce_no_controle": "Ikaw ang may kontrol",
    "depois_de_importar_um_livro_voce_le_se": "Kapag na-import na ang libro, mababasa mo ito nang walang internet.",
    "funciona_offline": "Gumagana offline",
    "livros_marcacoes_e_progresso_sao_guard": "Nananatili sa device mo ang mga libro, marks at progress. Walang ipinapadala sa aming mga server.",
    "tudo_fica_no_seu_aparelho": "Nananatili ang lahat sa device mo",
    "escolha_o_que_deseja_adicionar_a_bibli": "Piliin kung ano ang gusto mong idagdag sa library. Awtomatikong nilalaktawan ang mga file na kapareho ng nasa bookshelf mo na.",
    "voce_pode_tentar_outra_pasta_ou_import": "Maaari kang sumubok ng ibang folder o mag-import gamit ang + button.",
    "a_leitura_acontece_so_no_seu_dispositi": "Sa device mo lang nangyayari ang pagbasa.",
    "voce_escolhe_a_pasta": "Ikaw ang pumipili ng folder",
    "tema_tipografia_margens_modo_de_virada": "Tema, font, margins, page-turn style at audio settings.",
    "restaurar_minhas_preferencias": "Ibalik ang mga preference ko",
    "o_backup_manda_as_marcacoes_atuais_dos": "Masusunod ang backup. Ang kasalukuyang marks ng anumang librong nasa file ay papalitan ng nasa backup.",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "Walang buburahin. Pagsasamahin ang marks mula sa magkabilang panig at mananaig ang pinakabagong progress.",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "Ano ang gagawin sa nasa bookshelf na",
    "grifos_citacoes_e_notas": "highlights, quotes at notes",
    "preparando_o_arquivo_2": "Inihahanda ang file...",
    "os_livros_em_si_nem_as_capas_por_isso": "Hindi kasama ang mismong mga libro, at hindi rin ang mga cover — kaya ilang KB lang ang file. Kailangang may mga file ng libro ang tatanggap para bumalik sa tamang lugar ang marks, at awtomatikong babalik ang mga cover kapag in-import ang mga libro.",
    "nao_vai_no_arquivo": "Wala sa file",
    "o_seu_progresso_de_leitura_os_grifos_a": "Ang reading progress mo, highlights, quotes, notes, bookmarks at ayos ng bookshelf mo — status, favorites, collections, series at tags.",
    "vai_no_arquivo": "Nasa file",
    "descartar_o_que_esta_esperando_2": "Burahin ang naghihintay na data",
    "esperando_o_arquivo": "Naghihintay sa file",
    "avisar_quando_fizer_tempo_sem_backup": "Ipaalala sa akin kapag matagal nang walang backup",
    "livros_que_ainda_nao_estiverem_na_esta": "Mananatiling naghihintay ang mga librong wala pa sa bookshelf: kapag na-import mo ang file nila, awtomatikong babalik ang marks.",
    "restaurar_backup": "I-restore ang backup",
    "salvar_backup": "I-save ang backup",
    "ainda_nao_ha_itens": "Wala pa rito",
    "arraste_um_livro_para_outra_posicao_na": "I-drag ang libro sa ibang posisyon sa shelf para i-save ang sarili mong order. Ang manual na order na iyon ang uunahin kaysa grouping ayon sa author.",
    "separe_por_virgulas": "Paghiwalayin gamit ang kuwit",
    "ex_estudos_ficcao": "hal. Studies, Fiction...",
    "pasta_estante": "Folder / estante",
    "ex_trilogia": "hal. Trilogy...",
    "serie": "Serye",
    "aparece_em_favoritos": "Lumilitaw sa Favorites.",
    "nome_do_livro": "Pangalan ng libro",
    "nenhum_registro_ainda": "Wala pang naitatala",
    "no_leitor_toque_no_icone_de_marcador_p": "Sa reader, i-tap ang bookmark icon para i-save ang page.",
    "nenhum_marcador_ainda": "Wala pang bookmarks",
    "a_gravacao_e_independente_da_localizac": "Ang pag-save ay hiwalay sa lokasyon ng PDF at hindi binabago ang orihinal na file.",
    "o_pdf_original_nao_precisa_estar_nessa": "Hindi kailangang nasa folder na ito ang orihinal na PDF",
    "excluir_da_biblioteca": "I-delete sa library",
    "adicionar_livro": "Magdagdag ng libro",
    "adicione_livros_e_acompanhe_o_que_esta": "Magdagdag ng mga libro at subaybayan kung ano ang naghihintay, ginagawa at kung gaano na ang progress.",
    "tudo_pronto_para_a_proxima_leitura": "Handa na para sa susunod mong pagbasa.",
    "sua_biblioteca": "Ang library mo",
    "arraste_um_livro_para_reposiciona_lo_a": "I-drag ang libro para ilipat ito: lilipat ang shelf sa My Order at pananatilihin ang sequence.",
    "importe_um_livro_ou_ajuste_seus_filtro": "Mag-import ng libro o ayusin ang filters.",
    "nada_por_aqui_ainda": "Wala pa rito",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "I-tap ang + at pumili ng MP3, M4B o MP4 files. Maaaring pagsamahin ang ilang chapter MP3 bilang isang audiobook.",
    "nada_para_ouvir_ou_assistir_ainda": "Wala pang mapakinggan o mapanood",
    "o_pdf_original_permanece_intacto_na_pa": "Mananatiling buo ang orihinal na PDF sa sarili mong folder.",
    "paginas_como_imagem": "Mga page bilang images",
    "paginas_do_pdf": "Mga page ng PDF",
    "em_navegadores_sem_suporte_a_acesso_di": "Sa mga browser na walang direktang access sa file system, ida-download na lang ang EPUB.",
    "essa_permissao_e_dada_somente_a_esta_a": "Ibinibigay ang pahintulot na iyon sa app na ito lamang at pinipigilan nitong mabago ang orihinal na file.",
    "selecione_a_pasta_que_contem_o_pdf": "Piliin ang folder na naglalaman ng PDF",
    "preparando": "Inihahanda…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "Binabasa at muling binubuo ang file. Maaaring tumagal nang kaunti ang malalaking libro.",
    "revistas_apostilas_complexas_formulari": "Maaaring mawalan ng bahagi ng orihinal na layout ang magazines, kumplikadong workbooks, forms, documents na maraming table o scanned PDFs.",
    "funcionalidade_indicada_apenas_para_li": "Para sa mga libro",
    "o_epub_e_melhor_para_livros_com_texto": "Mas mainam ang EPUB para sa mga librong may selectable text dahil maaari mong ayusin ang font, size, margins at reading mode.",
    "trecho_selecionado": "Napiling passage",
    "trecho_comentado": "Passage na may comment",
    "aplicando_zoom": "Nag-zo-zoom...",
    "nao_foi_possivel_carregar_esta_pagina": "Hindi ma-load ang page na ito.",
    "nomear_marcador": "Bigyan ng pangalan ang bookmark",
    "toque_em_marcar_agora_para_guardar_est": "I-tap ang “Mark now” para i-save ang puntong ito at balikan kahit kailan.",
    "timer_ativo": "Naka-on ang timer",
    "trecho_ausente_ou_corrompido_no_arquiv": "[Wala o sira ang passage sa orihinal na file]",
    "novos_livros_vao_abrir_em_leitura_v": "Magbubukas ang mga bagong libro sa {v} reading.",
    "leitura_efetivo_aplicada_a_este_livro": "Inilapat ang {efetivo} reading sa librong ito.",
    "automatico_neste_livro_leitura_efetivo": "Awtomatiko para sa librong ito: {efetivo} reading.",
    "agora_esta_em_efetivo_no_automatico_fo": "Naka-set na ngayon sa {efetivo}; sa automatic, bubuksan ang {format} sa {padrao}.",
    "esta_escolha_vale_so_para_v_cada_livro": "Ang pagpiling ito ay para lang sa “{v}”. Sariling scrolling direction ang pinapanatili ng bawat libro.",
    "novos_ainda_nao_estao_na_sua_estante": "Wala pa sa bookshelf mo ang {novos}.",
    "escolha_uma_pasta_para_procurar_label": "Pumili ng folder kung saan hahanapin ang {label}.",
    "subtitle_versao_build": "{subtitle} · bersyon {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "Hindi mabasa ang {path}; gagamitin ang built-in text.",
    "seu_ultimo_backup_foi_ha_dias_dias": "{dias} araw na ang nakalipas mula sa huli mong backup",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "May {aguardando} libro mula sa backup na wala pa rito. Naitabi ang progress at marks nito: kapag na-import mo ang file, awtomatikong babalik sa tamang lugar ang lahat.",
      "other": "May {aguardando} libro mula sa backup na wala pa rito. Naitabi ang progress at marks ng mga ito: kapag na-import mo ang bawat file, awtomatikong babalik sa tamang lugar ang lahat."
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "Na-update ang {atualizados} libro sa bookshelf mo.",
      "other": "Na-update ang {atualizados} libro sa bookshelf mo."
    },
    "criado_em_quando": "Ginawa noong {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "Handa na ang backup: {livros} libro at {marcacoes} marks.",
    "endereco_seguro_seguro": "Ligtas na address: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "Na-restore ang progress at {marcas} mark para sa librong ito.",
      "other": "Na-restore ang progress at {marcas} mark para sa librong ito."
    },
    "restaurando_v_de_length": "Ni-re-restore ({v} sa {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} libro · {marcacoes} marks",
    "criado_em_v": "Ginawa noong {v}",
    "reunindo_a_sua_estante_v_de_length": "Kinokolekta ang bookshelf mo ({v} sa {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "Na-import na dati ang “{titulo}” at nasa library mo pa rin. Walang ginawang bagong kopya.",
    "length_arquivos_de_audio": "{length} audio file...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "Hindi mabasa ang {falhas} file.",
      "other": "Hindi mabasa ang {falhas} file."
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "Nasa library na ang {repetidos} at nilaktawan.",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "Nagdagdag ng {importados} libro sa bookshelf mo.",
      "other": "Nagdagdag ng {importados} libro sa bookshelf mo."
    },
    "epub_salvo_em_filename": "Na-save ang EPUB sa {fileName}.",
    "falha_ao_converter_o_pdf_v": "Hindi ma-convert ang PDF: {v}",
    "pagina_page_de_totalpages": "Page {page} ng {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} pahina",
      "other": "{totalPages} pahina"
    },
    "length_resultado_s_para_search": {
      "one": "{length} resulta para sa “{search}”",
      "other": "{length} resulta para sa “{search}”"
    },
    "capitulo_v": "Kabanata {v}",
    "organizando_capitulo_v_de_totalchapter": "Inaayos ang chapter {v} sa {totalChapters}",
    "pagina_v": "Pahina {v}",
    "paginas_v_v2": "Mga pahina {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} page na handa",
      "other": "{length} page na handa"
    },
    "montando_as_paginas_pagessofar_prontas": "Binubuo ang mga page — {pagesSoFar} na ang tapos",
    "lendo_pagina_v_de_length": "Binabasa ang page {v} sa {length}",
    "marcador_salvo_em_t": "Na-save ang bookmark sa {t}.",
    "o_audio_vai_pausar_em_minutes_minutos": "Magpa-pause ang audio sa loob ng {minutes} minuto.",
    "length_capitulos_toque_para_ir_direto": "{length} chapters · i-tap para direktang pumunta roon.",
    "narrado_por_narrator": "Isinalaysay ni {narrator}",
    "velocidade_de_reproducao_rate": "Bilis ng playback: {rate}",
    "avancar_f_segundos": "Mag-forward ng {f} segundo",
    "nao_foi_possivel_abrir_este_v": "Hindi mabuksan ang {v} na ito.",
    "nao_foi_possivel_ler_o_arquivo_de_v": "Hindi mabasa ang {v} file.",
    "o_v_esta_danificado_neste_ponto": "Sira ang {v} sa puntong ito.",
    "o_navegador_nao_consegue_reproduzir_es": "Hindi ma-play ng browser ang {v} file na ito.",
    "nao_foi_possivel_reproduzir_este_v": "Hindi ma-play ang {v} na ito.",
    "os_dados_deste_noun_estao_incompletos": "Hindi kumpleto ang data ng {noun}.",
    "importe_o_arquivo_novamente_para_conti_2": "I-import muli ang file para magpatuloy sa {v}.",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "Wala na sa device mo ang file ng {noun}.",
    "nao_foi_possivel_descobrir_a_duracao_d": "Hindi matukoy ang haba ng “{name}”.",
    "lendo_faixa_v_de_length": "Binabasa ang track {v} sa {length}...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "Hindi matukoy ang haba ng {v} na ito.",
    "este_format_nao_pode_ser_reproduzido_n": "Hindi ma-play sa browser na ito ang {format} na ito.",
    "este_format_esta_protegido_por_drm": "Protektado ng DRM ang {format} na ito.",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "{bytes} ang laki ng file at humigit-kumulang {v} ang natitira. Magbakante ng space o mag-delete ng mga libro sa library.",
    "este_arquivo_nao_e_um_format_valido": "Hindi valid na {format} ang file na ito.",
    "preparando_as_paginas_vistas_de_total": "Inihahanda ang mga page ({vistas} sa {total})...",
    "preparando_total_pagina_s": {
      "one": "Inihahanda ang {total} page...",
      "other": "Inihahanda ang {total} page..."
    },
    "preparando_as_paginas_v_de_total": "Inihahanda ang mga page ({v} sa {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "Humigit-kumulang {bytes} ang kailangan nito at mga {v} ang natitira. Magbakante ng space o mag-delete ng mga libro sa library.",
    "envio_direto_exige_endereco_seguro": "Hindi available ang direktang pagpapadala sa ibang app dahil hindi binuksan ang page na ito mula sa secure na address. I-save ang file at ipadala ito gamit ang app na gusto mo.",
    "na_estante": "sa bookshelf",
    "nao_foi_possivel_montar_o_arquivo": "Hindi mabuo ang file.",
    "este_navegador_nao_oferece_o_envio_dir": "Hindi nag-aalok ang browser na ito ng direktang pagpapadala sa ibang app. I-save ang file at i-attach ito gamit ang app na gusto mo.",
    "voce_ainda_nao_fez_nenhum_backup": "Wala ka pang ginagawang backup.",
    "converter_para_epub": "I-convert sa EPUB",
    "esta_pagina_nao_pode_ser_exibida": "Hindi maipakita ang page na ito.",
    "na_ordem_em_que_serao_tocados": "Sa pagkakasunod kung paano sila ipe-play",
    "este_capitulo_nao_pode_ser_exibido": "Hindi maipakita ang chapter na ito.",
    "livro": "Libro",
    "restantes": " natitira",
    "como_seus_dados_sao_tratados": "Paano hinahandle ang data mo",
    "condicoes_de_uso_do_aplicativo": "Mga kondisyon sa paggamit ng app",
    "audiolivro": "audiolibro",
    "sobre_o_aplicativo": "Tungkol sa app",
    "o_que_e_o_veredas_reader": "Ano ang Veredas Reader",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(hindi sinusuportahan ng device na ito ang pagbabahagi ng ganitong file type)",
    "livros": "mga libro",
    "lendo": "nagbabasa",
    "lidos": "tapos na",
    "compartilhar_livro": "I-share ang libro",
    "n_livros": {
      "one": "{n} libro",
      "other": "{n} libro"
    },
    "livros_unidade": {
      "one": "libro",
      "other": "libro"
    },
    "uma_faixa_discreta_depois_de_n_dias": "May banayad na strip sa bookshelf pagkatapos ng {n} araw na walang backup. Hindi nito kailanman iniistorbo ang pagbabasa mo.",
    "scanned_arquivos_verificados_livros_enc": "{scanned} files na na-check · {encontrados} libro ang nahanap",
    "v_de_total": "{v} sa {total}",
    "voltar_n_segundos": "Bumalik ng {n} segundo",
    "cancelado": "Kinansela",
    "arquivo": "File",
    "outro": "Iba pa",
    "outros": "Iba pa",
    "audiolivro_2": "Audiolibro",
    "pausar": "I-pause",
    "marcador": "Bookmark",
    "leitura": "Pagbabasa",
    "grifo": "Highlight",
    "editar": "I-edit",
    "apagar": "I-delete",
    "concluir": "Tapusin",
    "recentes": "Kamakailan",
    "progresso": "Progreso",
    "entendi": "Naintindihan",
    "aviso": "Abiso",
    "descartar": "I-delete",
    "copiado": "Nakopya",
    "restaurar": "I-restore",
    "restaurando": "Ni-re-restore",
    "excluir": "I-delete",
    "grifos": "Mga highlight",
    "arquivo_vazio": "Walang laman ang file.",
    "e_mais_n_arquivos": {
      "one": "at {n} pang file, sa pagkakasunod kung paano ipe-play",
      "other": "at {n} pang file, sa pagkakasunod kung paano ipe-play"
    },
    "n_arquivos_mp3": {
      "one": "{n} MP3 file",
      "other": "{n} MP3 file"
    },
    "pct_restam": "{pct}% · {tempo} na lang",
    "n_minutos": {
      "one": "{n} minuto",
      "other": "{n} minuto"
    },
    "ir_para_tempo": "Pumunta sa {tempo}",
    "nomear": "Pangalanan",
    "parte_n": "Bahagi {n}",
    "carregando_pagina_n": "Nilo-load ang pahina {n}...",
    "selecionar_pasta_e_continuar": "Pumili ng folder at magpatuloy",
    "ler_agora": "Basahin ngayon",
    "agrupamento_v": "Pagpapangkat: {v}.",
    "tempo_restante": "{tempo} na lang",
    "abrir_titulo": "Buksan ang {titulo}",
    "continuar_lendo_titulo": "Ipagpatuloy ang pagbasa ng {titulo}",
    "continuar_ouvindo_titulo": "Ipagpatuloy ang pakikinig sa {titulo}",
    "continuar_assistindo_titulo": "Ipagpatuloy ang panonood ng {titulo}",
    "lido": "Nabasa na",
    "pausado": "Naka-pause",
    "status": "Status",
    "favorito": "Paborito",
    "escolher_local": "Pumili ng lokasyon",
    "epub_baixado_como": "Na-download ang EPUB bilang {nome}.",
    "ouvir_a_partir_de": "makinig mula {tempo}",
    "assistir_a_partir_de": "manood mula {tempo}",
    "pagina_n_minuscula": "pahina {n}",
    "selecione_trecho_para_criar": "Pumili ng sipi habang nagbabasa para gumawa ng {oque}.",
    "excluir_oque_pergunta": "I-delete ang {oque}?",
    "excluir_oque": "I-delete ang {oque}",
    "excluir_item_pergunta": "I-delete ang item na ito?",
    "use_organizar_para_criar": "Gamitin ang “{botao}” sa isang libro para gumawa ng {oque}.",
    "n_arquivos_processados": {
      "one": "{n} file ang naproseso",
      "other": "{n} file ang naproseso"
    },
    "voce_ja_tem_titulo_de_autor": "Mayroon ka nang “{titulo}” ni {autor} sa library, kahit iba ang file. I-import pa rin?",
    "voce_ja_tem_titulo": "Mayroon ka nang “{titulo}” sa library, kahit iba ang file. I-import pa rin?",
    "marcadores_unidade": {
      "one": "bookmark",
      "other": "bookmark"
    },
    "ultimo_backup_em": "Huling backup noong <strong>{data}</strong>.",
    "guardar": "I-save",
    "lembretes": "Mga paalala",
    "juntar": "Pagsamahin",
    "recomendado": "inirerekomenda",
    "substituir": "Palitan",
    "n_capas_recuperadas": {
      "one": "{n} cover ang nabawi.",
      "other": "{n} cover ang nabawi."
    },
    "nao_encontramos_arquivos_tipo": "Walang nahanap na {tipo} file sa folder na ito.",
    "tentar_outra_pasta": "Sumubok ng ibang folder",
    "n_livros_encontrados": {
      "one": "{n} libro ang nahanap",
      "other": "{n} libro ang nahanap"
    },
    "n_de_total_selecionados": {
      "one": "{n} sa {total} ang napili",
      "other": "{n} sa {total} ang napili"
    },
    "importar": "I-import",
    "importar_n": "I-import ang {n}",
    "aceite_frase": "Nabasa ko at tinatanggap ko ang {politica} at ang {termos} ng Veredas Reader.",
    "pdf_preservado": "Ang orihinal na PDF <strong>ay hindi buburahin mula sa sarili mong folder</strong>. Ang kopya lang ng PDF na ito ang aalisin sa library, pagkatapos matagumpay na ma-save ang EPUB.",
    "gravar_epub_mesma_pasta": "Para i-save ang EPUB <strong>sa parehong folder ng PDF</strong>, kailangan ng browser ng pahintulot na ma-access ang folder na iyon.",
    "epub_pronto_qualquer_pasta": "Na-convert na ang EPUB. Maaari mo nang piliin ang <strong>anumang folder sa computer</strong> para i-save ang file.",
    "backup_explicacao": "Ang orihinal na backup ay ZIP o TXT. Kapag natanggap mo ito sa ibang device, i-import ito gamit ang <strong>I-restore ang backup</strong>: kinikilala ng Veredas ang laman at normal itong nire-restore. Nasa file ang progress, highlights, quotes, notes, bookmarks at ayos ng bookshelf mo — <strong>hindi ang mismong mga libro</strong>, o ang mga cover.",
    "lembretes_desligados_frase": "<strong>Naka-off</strong> ang mga reminder. Tandaang mag-backup paminsan-minsan.",
    "backup_salvo_nos_downloads": "<strong>Na-save ang backup file sa device na ito</strong>, sa downloads mo. Maaari mo itong ipadala ngayon: buksan ang WhatsApp, email, Drive o gusto mong app, i-tap ang attach at piliin ang file.",
    "arquivo_pronto_tamanho": "Handa na ang file — <strong>{tamanho}</strong>.",
    "scan_intro_frase": "Puwedeng maghanap ang app ng mga libro sa <strong>EPUB</strong> at <strong>MOBI</strong>, mga comic sa <strong>CBZ</strong> at <strong>CBR</strong> at mga audiobook sa <strong>M4B</strong> sa loob ng isang folder sa device mo, kasama ang mga subfolder.",
    "scan_intro_auto_frase": "Para mabilis mapuno ang iyong bookshelf, puwedeng maghanap ang app ng mga libro sa <strong>EPUB</strong> at <strong>MOBI</strong>, mga comic sa <strong>CBZ</strong> at <strong>CBR</strong> at mga audiobook sa <strong>M4B</strong> sa loob ng isang folder sa device mo, kasama ang mga subfolder.",
    "n_livros_aguardando": {
      "one": "<strong>{n} libro</strong> na may naka-save na progress at marks, naghihintay na ma-import muli.",
      "other": "<strong>{n} libro</strong> na may naka-save na progress at marks, naghihintay na ma-import muli."
    },
    "fora_da_busca_titulo": "Hindi namin awtomatikong ini-import ang mga PDF, TXT, DOCX (Word), MD, MP3 at MP4 file",
    "fora_da_busca_texto": "Ginagamit ang mga format na ito para sa lahat ng uri ng dokumento, hindi lang sa mga libro. Kapag hindi isinama ang mga ito, nananatiling maayos ang bookshelf mo. <strong>Maaari mong i-import nang manu-mano ang bawat file na ganito gamit ang + button.</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "Ang lokal mong library",
    "biblioteca": "Aklatan",
    "organizacao": "Organisasyon",
    "minhas_marcacoes": "Aking marks",
    "sistema": "Sistema",
    "sua_biblioteca": "Ang library mo",
    "toque_em_um_livro_para_comecar_a_ler": "I-tap ang isang libro para magsimulang magbasa.",
    "agrupar": "I-group",
    "sua_estante_nao_tem_copia_de_seguranca": "Walang backup ang bookshelf mo",
    "se_este_aparelho_se_perder_o_progresso": "Kung may mangyari sa device na ito, maaaring mawala ang progress at marks mo.",
    "agora_nao": "Hindi ngayon",
    "nao_avisar_mais": "Huwag na akong paalalahanan",
    "carregando": "Naglo-load...",
    "estante": "Bookshelf",
    "lendo": "Nagbabasa",
    "favoritos": "Mga Paborito",
    "marcas": "Mga Marka",
    "mais": "Higit pa",
    "neste_capitulo": "Chapter na ito",
    "velocidade": "Bilis",
    "timer": "Timer",
    "marcar": "Markahan",
    "marcadores": "Mga bookmark",
    "personalizar_leitura": "Mga kagustuhan sa pagbasa",
    "as_preferencias_ficam_salvas_para_as_p": "Nai-save ang preferences mo para sa mga susunod na reading session.",
    "tema": "Tema",
    "claro": "Maliwanag",
    "sepia": "Sepia",
    "escuro": "Madilim",
    "oceano": "Karagatan",
    "tipografia": "Font",
    "texto": "Teksto",
    "tamanho": "Laki",
    "espacamento": "Agwat ng linya",
    "margens": "Mga margin",
    "cores_personalizadas_opcional": "Mga custom na kulay (opsyonal)",
    "fundo": "Background",
    "fonte": "Kulay ng text",
    "brilho": "Liwanag",
    "orientacao": "Oryentasyon",
    "auto": "Awtomatiko",
    "retrato": "Patayo",
    "paisagem": "Pahiga",
    "modo_de_leitura": "Mode ng pagbasa",
    "automatico": "Awtomatiko",
    "horizontal": "Pahalang",
    "vertical": "Patayo",
    "automatico_usa_rolagem_horizontal_para": "Sa automatic, horizontal ang paging para sa EPUB, MOBI, TXT at MD, at vertical ang scrolling para sa PDF at DOCX. Kapag binago mo ito habang nagbabasa, para sa librong ito lang ang pagbabago.",
    "quadrinhos": "Mga komiks",
    "como_a_pagina_aparece": "Paano kasya ang page",
    "pagina_inteira": "Buong page",
    "largura_da_tela": "Lapad ng screen",
    "sentido_da_leitura": "Direksiyon ng pagbasa",
    "normal": "Normal →",
    "manga": "← Manga",
    "revista_aberta_na_horizontal": "Dalawang page na magkatabi sa landscape",
    "com_o_aparelho_deitado_mostra_duas_pag": "Kapag nakatagilid ang device, makikita ang dalawang page na magkatabi; mag-isa ang cover, gaya ng totoong comic.",
    "normal_vira_da_esquerda_para_a_direita": "Ang Normal ay bumubukas mula kaliwa pakanan. Binabaligtad ng Manga ang lahat: ang swipe, mga tap sa gilid at ayos ng dalawang page sa spread.",
    "gire_o_aparelho_para_a_horizontal_para": "Itagilid ang device para makita ang dalawang page nang sabay.",
    "dois_toques_ampliam_no_ponto_tocado_co": "I-double-tap para mag-zoom sa puntong tinap mo; kapag naka-zoom, i-drag para gumalaw sa page. Gumagana rin ang pinch gamit ang dalawang daliri.",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "Ang scrolling button sa itaas ng reader ay nagpapalit sa page-by-page at continuous scrolling (webtoon style). Sa continuous scrolling, nagsasanib ang mga page at pinapalawak ng zoom ang page: gumagalaw ka rito sa pamamagitan ng pag-scroll pakaliwa o pakanan.",
    "virada_de_pagina": "Paglipat ng pahina",
    "folha_real": "Totoong papel",
    "deslizar": "I-slide",
    "sem_animacao": "Walang animation",
    "na_leitura_horizontal_arraste_a_pagina": "Sa horizontal reading, i-drag ang page mula sa gilid para tiklupin ito gamit ang daliri. Bitawan sa gitna para kanselahin ang page turn.",
    "ouvir_leitura": "Makinig",
    "continue_de_onde_parou_no_seu_ritmo": "Ipagpatuloy kung saan ka tumigil, sa sarili mong ritmo.",
    "livro": "Libro",
    "pronto_para_comecar": "Handa nang magsimula",
    "voz": "Boses",
    "escolha_uma_voz_disponivel_no_disposit": "Pumili ng voice na available sa device na ito",
    "voz_padrao_do_sistema": "Default na voice ng system",
    "durante_a_reproducao": "Habang nagpe-play",
    "a_leitura_avanca_pagina_a_pagina_os_co": "Ang pagbabasa ay umuusad page-by-page. Lumalabas ang system controls kapag sinusuportahan ng browser.",
    "organizar_livro": "Ayusin ang libro",
    "estantes_colecoes_tags_e_status": "Shelves, collections, tags at status.",
    "cancelar": "Kanselahin",
    "salvar": "I-save",
    "grifos_citacoes_notas_e_marcadores_des": "Highlights, quotes, notes at bookmarks ng librong ito.",
    "sumario": "Nilalaman",
    "toque_em_um_capitulo_para_ir_direto_ao": "I-tap ang chapter para direktang pumunta roon.",
    "sua_anotacao": "Ang note mo",
    "edite_ou_adicione_comentarios_ao_seu_t": "I-edit o magdagdag ng comments sa passage mo.",
    "trecho": "Sipi",
    "sua_nota": "Ang note mo",
    "salvar_nota": "I-save ang note",
    "agrupar_biblioteca": "I-group ang library",
    "escolha_como_os_livros_serao_organizad": "Piliin kung paano aayusin ang mga libro sa bookshelf.",
    "ao_arrastar_um_livro_para_outra_posica": "Kapag nag-drag ka ng libro sa ibang posisyon, awtomatikong lilipat ang bookshelf sa My Order at pananatilihin ang sequence na ginawa mo.",
    "backup_e_restauracao": "Backup at restore",
    "sua_estante_seu_progresso_e_suas_marca": "Ang bookshelf, progress at marks mo sa iisang file.",
    "escolha_uma_dimensao_para_explorar_sua": "Pumili ng paraan para tuklasin ang library mo.",
    "capitulos": "Mga chapter",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "Nananatili ang pitch ng boses. Nalalapat ito sa librong ito at sa mga susunod.",
    "ajuste_fino": "Pino na pagsasaayos",
    "timer_de_sono": "Timer ng pagtulog",
    "o_audio_diminui_de_volume_aos_poucos_e": "Unti-unting humihina ang audio at awtomatikong nagpa-pause.",
    "pontos_que_voce_guardou_neste_audioliv": "Mga puntong na-save mo sa audiobook na ito.",
    "ajustes_do_audio": "Mga setting ng audio",
    "as_preferencias_ficam_salvas_para_todo": "Nai-save ang mga preference na ito para sa lahat ng audiobook.",
    "botao_de_voltar": "Button na bumalik",
    "botao_de_avancar": "Button na sumulong",
    "recuar_ao_retomar": "Rewind kapag ipinagpatuloy",
    "depois_de_uma_pausa_longa_volta_alguns": "Pagkatapos ng mahabang pause, babalik ito ng ilang segundo para madali mong mahanap ang pinagpatuloyan mo.",
    "tocar_ao_abrir": "I-play kapag binuksan",
    "ao_tocar_em_um_audiolivro_na_estante_a": "Kapag nag-tap ka ng audiobook sa bookshelf, agad magsisimula ang playback.",
    "no_computador_espaco_toca_e_pausa_pula": "Sa computer: space para play/pause · ← → skip · Shift + ← → palit chapter · ↑ ↓ volume · B bookmarks · [ ] speed.",
    "converter_pdf_para_epub": "I-convert ang PDF sa EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "Ihanda ang libro para sa tuloy-tuloy at naia-adjust na pagbabasa.",
    "confirmacao": "Kumpirmahin",
    "confirmar": "Kumpirmahin",
    "processando": "Pinoproseso",
    "documento": "Dokumento",
    "buscar_livros_no_dispositivo": "Maghanap ng mga libro sa device na ito",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "Hanapin ang mga EPUB, MOBI, CBZ, CBR at M4B file na naka-save na sa device mo.",
    "juntar_em_um_unico_audiolivro": "Pagsamahin sa iisang audiobook?",
    "titulo": "Pamagat",
    "autor": "May-akda",
    "importar_separados": "I-import nang magkahiwalay",
    "bem_vindo_ao_veredas_reader": "Maligayang pagdating sa Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "Ang reading library mo, ganap na nasa sarili mong device.",
    "buscar": "Maghanap",
    "importar_livro": "Mag-import ng libro",
    "buscar_titulo_autor_tag": "Maghanap ng title, author, tag...",
    "fechar_busca": "Isara ang search",
    "navegacao_da_biblioteca": "Navigation sa library",
    "fechar_menu": "Isara ang menu",
    "agrupar_livros": "I-group ang mga libro",
    "voltar": "Bumalik",
    "marcar_pagina": "Markahan ang page",
    "personalizar": "Mga kagustuhan",
    "navegacao_principal": "Pangunahing navigation",
    "acoes_do_trecho": "Mga action sa passage",
    "amarelo": "Dilaw",
    "verde": "Berde",
    "rosa": "Rosas",
    "azul": "Asul",
    "player_de_audiolivro": "Player ng audiolibro",
    "minimizar_player": "I-minimize ang player",
    "minimizar": "I-minimize",
    "video_em_reproducao": "Nagpe-play ang video",
    "abrir_a_lista_de_capitulos": "Buksan ang listahan ng chapters",
    "posicao_no_audio": "Posisyon sa audio",
    "alternar_entre_o_progresso_do_capitulo": "Magpalit sa pagitan ng progress ng chapter at progress ng buong libro",
    "capitulo_anterior": "Nakaraang chapter",
    "voltar_15_segundos": "Bumalik ng 15 segundo",
    "reproduzir": "I-play",
    "avancar_30_segundos": "Mag-forward ng 30 segundo",
    "proximo_capitulo": "Susunod na chapter",
    "velocidade_de_reproducao": "Bilis ng playback",
    "marcar_este_ponto": "Markahan ang puntong ito",
    "ver_marcadores": "Tingnan ang bookmarks",
    "silenciar": "I-mute",
    "volume": "Volume",
    "audiolivro_em_reproducao": "Nagpe-play na audiobook",
    "abrir_o_player": "Buksan ang player",
    "fechar_o_player": "Isara ang player",
    "fechar": "Isara",
    "trecho_anterior": "Nakaraang passage",
    "iniciar_leitura": "Simulan ang read aloud",
    "proximo_trecho": "Susunod na passage",
    "escreva_seu_comentario_interpretacao_o": "Isulat ang iyong comment, interpretasyon o paalala...",
    "cancelar_importacao": "Kanselahin ang import",
    "nome_do_audiolivro": "Pangalan ng audiobook",
    "nome_do_autor": "Pangalan ng author",
    "idioma": "Wika",
    "idioma_do_aplicativo": "Wika ng app",
    "o_aplicativo_segue_o_idioma_do_apare": "Sinusunod ng app ang wika ng device mo. Kung wala pa rito ang wika mo, bubuksan ito sa English.",
    "seguir_o_aparelho": "Sundin ang device",
    "fazer_backup": "Mag-backup ngayon",
    "todos": "Lahat",
    "lidos": "Tapos na",
    "pausados": "Naka-pause",
    "autores": "Mga author",
    "tags": "Tags",
    "grifar": "Mag-highlight",
    "anotar": "Magtala",
    "enviar": "Ipadala",
    "restaurar_padroes": "Ibalik ang default",
    "voltar_para_1": "Bumalik sa 1×",
    "marcar_agora": "Markahan ngayon",
    "escolher_pasta": "Pumili ng folder",
    "juntar_em_um_audiolivro": "Pagsamahin sa isang audiobook",
    "sobre": "Tungkol",
    "licencas_de_codigo_aberto": "Mga lisensiyang open source",
    "configuracoes": "Mga Setting",
    "temas_e_idioma": "Mga tema at wika"
  },
  "aviso": {
    "idioma_trocado": "Nabago ang wika."
  },
  "vn": {
    "quem_le": "Sino ang magbabasa",
    "natural": "Natural",
    "do_sistema": "System",
    "nota_sistema": "Ginagamit ang mga boses na naka-install sa device mo. Para sa mas parang-taong pagbasa, piliin ang Natural.",
    "nota_sistema_com_natural": "Naka-download pa rin ang natural na boses. Bumalik sa Natural kahit kailan mo gusto.",
    "voz_do_sistema": "Boses ng system",
    "lendo_com_a_voz_do_sistema": "Binabasa gamit ang boses ng system.",
    "voz_natural": "Natural na boses",
    "gerada_no_aparelho": "Boses na mas parang tao, ginagawa mismo sa device mo.",
    "progresso_download": "Progreso ng download",
    "x_de_y": "{x} sa {y}",
    "aviso_arquivo": "Para gumana ang natural na boses, kailangang buksan ang Veredas mula sa address ng app, hindi bilang file sa computer mo. Habang hindi pa, system voice muna ang gagamitin sa pagbasa.",
    "aviso_navegador": "Kulang ang browser na ito sa mga feature na kailangan ng natural na boses. Magpapatuloy ang pagbasa gamit ang system voice.",
    "verificando": "Tinitingnan ang natural na boses…",
    "fato_download": "Isang beses lang ang download na {tamanho}. Pagkatapos, gagana ito kahit walang internet.",
    "fato_wifi": "Mas mainam sa Wi-Fi. Puwede mong i-pause at ituloy mamaya.",
    "fato_privacidade": "Hindi kailanman lumalabas sa device mo ang text ng libro.",
    "fato_idiomas": "Nakakapagsalita ng 31 wika, kasama ang Ingles, Portuges at Espanyol. Hindi pa kasama ang Filipino, kaya system voice pa rin ang gagamitin dito.",
    "baixar_voz_natural": "I-download ang natural na boses ({tamanho})",
    "licenca_curta": "Supertonic 3 model ng Supertone, sa ilalim ng lisensiyang OpenRAIL-M. Detalye sa Tungkol > Mga lisensiyang open source.",
    "pode_continuar_usando": "Puwede kang magpatuloy sa pagbabasa habang nagda-download. Kapag naputol ang koneksiyon, itutuloy ang download kung saan ito huminto.",
    "pausar_download": "I-pause ang download",
    "erro_espaco": "Kulang ang espasyo sa device para matapos ang download. Magbakante ng kaunting espasyo at subukan ulit.",
    "erro_offline": "Walang internet sa ngayon. Nakatabi ang mga na-download na.",
    "erro_rede": "Naputol ang koneksiyon habang nagda-download. Nakatabi ang mga na-download na.",
    "download_pausado": "Naka-pause ang download. Nakatabi ang mga na-download na.",
    "continuar_download": "Ituloy",
    "descartar": "I-delete",
    "voz_feminina": "Babae",
    "voz_feminina_desc": "Malambot at kalmado",
    "voz_masculina": "Lalaki",
    "voz_masculina_desc": "Mainit at payapa",
    "parar_amostra": "Ihinto ang sample",
    "ouvir_amostra_de": "I-play ang sample: {voz}",
    "escolha_a_voz": "Piliin ang boses",
    "qualidade": "Kalidad",
    "q_auto": "Awtomatiko",
    "q_rapida": "Mabilis",
    "q_maxima": "Pinakamahusay",
    "q_auto_desc": "Kusang umaangkop sa performance ng device mo para tuloy-tuloy ang pagbasa.",
    "q_rapida_desc": "Mas mabilis gumawa ng boses. Bagay sa mas simpleng device.",
    "q_maxima_desc": "Pinakapulidong tunog. Sa mas simpleng device, puwedeng magkaroon ng mga pause sa pagitan ng mga pangungusap.",
    "ocupa": "Gumagamit ng {tamanho} sa device na ito",
    "remover": "Alisin",
    "baixar_pelos_dados": "I-download gamit ang mobile data?",
    "baixar_pelos_dados_msg": "Mukhang hindi naka-Wi-Fi ang device mo. {tamanho} ang download at puwede nitong makonsumo ang data plan mo.",
    "baixar_agora": "I-download pa rin",
    "pronta": "Handa na ang natural na boses.",
    "download_interrompido": "Huminto ang download. I-tap ang Ituloy kahit kailan mo gusto.",
    "remover_titulo": "Alisin ang natural na boses?",
    "descartar_titulo": "I-delete ang download?",
    "remover_msg": "Magbabakante ito ng {tamanho}. Babalik sa system voice ang pagbasa, at puwede mo itong i-download ulit kahit kailan.",
    "descartar_msg": "Mabubura ang mga na-download na.",
    "removida": "Naalis na ang natural na boses sa device na ito.",
    "amostra_falhou": "Hindi ma-play ang sample sa device na ito.",
    "amostra": "Hello! Ganito ang magiging tunog ng mga libro mo sa natural na boses.",
    "gerando_voz": "Inihahanda ang boses…",
    "automatico_idioma": "Awtomatiko ({idioma})",
    "automatico": "Awtomatiko",
    "so_voz_do_sistema": "system voice",
    "aviso_idioma": "Wika ng text: {idioma}. Hindi pa nakakapagsalita ng wikang ito ang natural na boses, kaya system voice ang magbabasa ng libro.",
    "aviso_idioma_desconhecido": "Hindi makilala ang wika ng text na ito. Piliin ang wika sa ibaba para magamit ang natural na boses.",
    "aviso_falha": "Hindi gumana ang natural na boses sa device na ito sa ngayon. Magpapatuloy ang pagbasa gamit ang system voice.",
    "nao_carregou_usando_sistema": "Hindi nag-load ang natural na boses sa device na ito. Nagbabasa gamit ang system voice.",
    "parou_usando_sistema": "Huminto ang natural na boses. Nagpapatuloy gamit ang system voice.",
    "aparelho_lento": "Mabagal gumawa ng boses ang device na ito. Piliin ang kalidad na Mabilis para maiwasan ang mga pause.",
    "idioma_do_texto": "Wika ng text",
    "idioma_do_texto_dica": "Kinilala mula mismo sa text. Palitan kung mali ang bigkas.",
    "leitura_em_voz_alta": "Read aloud",
    "lento_usando_sistema": "Masyadong mabagal ang natural na boses sa device na ito. Itutuloy gamit ang system voice.",
    "aviso_lento": "Hindi kayang gawin ng device na ito ang natural na boses nang kasimbilis ng pagbasa, kaya system voice muna ang gagamitin.",
    "sem_memoria_usando_sistema": "Hindi kasya ang natural na boses sa memory ng device na ito. System voice muna ang magbabasa.",
    "aviso_falha_memoria": "Kulang ang memory para sa natural na boses sa device na ito. Kadalasan, nakakatulong ang pagsara ng ibang app at muling pagsubok; pansamantala, system voice ang gagamitin.",
    "copiar_detalhe": "Kopyahin ang detalye",
    "copiado": "Nakopya ang detalye.",
    "falhou_titulo": "Hindi na-load ang natural na boses sa device na ito.",
    "falhou_texto": "Hindi naihanda ng device ang natural na boses. Magpapatuloy ang pagbasa gamit ang system voice. Para makatulong, kopyahin ang detalye sa ibaba at ipadala sa suporta.",
    "falhou_memoria_texto": "Kulang ang memory para sa natural na boses sa device na ito. Kadalasan, nakakatulong ang pagsara ng ibang app at muling pagsubok.",
    "tentar_de_novo": "Subukan ulit",
    "tentando": "Naglo-load…",
    "sondando": "Sinusuri ang memory ng device na ito…",
    "sonda_explica": "Ilang segundong inilalaan ng pagsubok ang memory na kakailanganin ng natural na boses, at agad itong ibinabalik. Kaya malalaman mo ngayon, hindi pagkatapos ng pag-download.",
    "aviso_aparelho_justo": "Kaunti ang memory ng device na ito para sa natural na boses. Baka hindi ito mag-load; kung gayon, alisin na lang ito at mababawi ang espasyo.",
    "preparando_demora": "Inihahanda ang boses. Maaaring tumagal ito nang ilang minuto.",
    "incompativel_titulo": "Hindi gumagana ang natural na boses sa device na ito.",
    "incompativel_memoria": "Kulang ang memory para ihanda ito. Mananatili sa system voice ang pagbasa, at nasa ibaba ang mga opsyon nito. Kung gusto mo, isara ang ibang app at i-tap ang Subukan muli.",
    "incompativel_lento": "Masyado itong mabagal para makasabay sa pagbasa. Mananatili sa system voice ang pagbasa, at nasa ibaba ang mga opsyon nito.",
    "incompativel_queda": "Nagsara ang app habang naglo-load ito. Mananatili sa system voice ang pagbasa, at nasa ibaba ang mga opsyon nito.",
    "incompativel_falha": "Hindi ito ma-load dito. Mananatili sa system voice ang pagbasa, at nasa ibaba ang mga opsyon nito.",
    "testar_de_novo": "Subukan ulit",
    "remover_e_liberar": "Alisin at makabawi ng {tamanho}",
    "tela_durante_a_leitura": "Screen habang nagbabasa",
    "manter_tela_ligada": "Panatilihing naka-on ang screen",
    "manter_tela_ligada_dica": "Habang bukas ang libro, hindi kusang mamamatay ang screen. Pagsara ng libro, babalik sa normal ang lahat."
  }
});
