/* ============================================================
   FRANÇAIS — traduction complète
   ------------------------------------------------------------
   Les clés sont identiques à pt-BR.js et en.js.
   ============================================================ */
Idiomas.registrar('fr', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "Marque-page supprimé.",
    "excluir_marcador": "Supprimer le marque-page",
    "o_marcador_sera_removido_permanentemen": "Le marque-page sera supprimé définitivement.",
    "excluir_marcador_2": "Supprimer le marque-page ?",
    "pagina_salva": "Page enregistrée",
    "anotacoes": "Notes",
    "citacoes": "Citations",
    "item_excluido": "Élément supprimé.",
    "este_registro_sera_removido_permanente": "Cette entrée sera définitivement supprimée de la bibliothèque.",
    "configuracoes_padrao_restauradas": "Paramètres par défaut restaurés.",
    "leitura_da_esquerda_para_a_direita": "Lecture de gauche à droite.",
    "leitura_da_direita_para_a_esquerda_man": "Lecture de droite à gauche (manga).",
    "a_pagina_inteira_passa_a_caber_na_tela": "La page entière tient maintenant à l’écran.",
    "a_pagina_passa_a_ocupar_toda_a_largura": "La page occupe maintenant toute la largeur de l’écran.",
    "virada_sem_animacao_ativada": "Le changement de page sans animation est activé.",
    "virada_deslizante_ativada": "Le changement de page par glissement est activé.",
    "virada_em_folha_real_ativada": "Le changement de page en feuille réelle est activé.",
    "padrao_automatico_cada_formato_abre_no": "Automatique : chaque format s’ouvre dans le sens qui lui convient.",
    "mudando_durante_a_leitura_o_ajuste_fic": "Si vous le changez pendant la lecture, la modification ne s’applique qu’à ce livre.",
    "automatico_usa_rolagem_horizontal_para": "Le mode automatique utilise la pagination horizontale pour EPUB, MOBI, TXT, MD et les bandes dessinées, et le défilement vertical pour PDF et DOCX.",
    "este_livro": "ce livre",
    "armazenamento_local_indisponivel_neste": "Le stockage local n’est pas disponible dans ce navigateur.",
    "o_aplicativo_pode_procurar_os_livros_q": "L’application peut rechercher les livres déjà présents sur votre appareil.",
    "vamos_montar_sua_estante": "Voulez-vous remplir votre étagère ?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "Sans votre accord, l’application ne peut pas être utilisée.",
    "precisamos_do_seu_aceite": "Nous avons besoin de votre accord",
    "antes_de_comecar_leia_e_aceite_os_docu": "Avant de commencer, lisez et acceptez les documents ci-dessous.",
    "selecionar_todos": "Tout sélectionner",
    "limpar_selecao": "Effacer la sélection",
    "todos_parecem_ja_estar_na_sua_estante": "Tous les livres semblent déjà être sur votre étagère.",
    "lendo_a_pasta_escolhida": "Lecture du dossier que vous avez choisi…",
    "procurando_livros": "Recherche de livres",
    "nao_foi_possivel_concluir_a_busca_no_d": "La recherche sur cet appareil n’a pas pu être terminée.",
    "tente_outra_pasta_do_aparelho": "Essayez un autre dossier de votre appareil.",
    "nenhum_livro_encontrado": "Aucun livre trouvé",
    "use_o_botao_para_escolher_os_arquivos": "Utilisez le bouton + pour choisir les fichiers manuellement. Sur les téléphones Android, Chrome permet généralement de sélectionner un dossier entier.",
    "seu_navegador_nao_permite_ler_pastas": "Votre navigateur ne peut pas lire les dossiers",
    "busca_automatica_indisponivel": "Recherche automatique indisponible",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR et M4B",
    "termos_de_uso": "Conditions d’utilisation",
    "politica_de_privacidade": "Politique de confidentialité",
    "um_minuto_agora_evita_perder_o_progres": "Une minute maintenant évite de perdre votre progression et vos marques plus tard.",
    "ver_estante": "Voir l’étagère",
    "modo_juntar": "Mode fusion",
    "modo_substituir": "Mode remplacement",
    "restauracao_concluida": "Restauration terminée",
    "tente_de_novo_com_o_arquivo_original": "Réessayez avec le fichier d’origine.",
    "a_restauracao_nao_pode_ser_concluida": "La restauration n’a pas pu être terminée",
    "devolvendo_o_seu_progresso_e_as_suas_m": "Récupération de votre progression et de vos marques...",
    "restaurar_este_backup": "Restaurer cette sauvegarde ?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Choisissez le .zip enregistré par Veredas ou le .txt reçu via le partage.",
    "nao_foi_possivel_ler_este_arquivo": "Impossible de lire ce fichier",
    "lendo_o_backup": "Lecture de la sauvegarde",
    "backup_do_veredas_reader": "Sauvegarde de Veredas Reader",
    "arquivo_de_transporte_txt_contendo_os": "copie de la sauvegarde au format .txt, avec le même contenu que le ZIP",
    "nao_foi_possivel_montar_o_arquivo_de_b": "Impossible de créer le fichier de sauvegarde.",
    "escolher_o_app": "Choisir l’application",
    "vale_conferir_o_que_vai_no_arquivo": "Vérifiez ce que contient le fichier",
    "enviar_para_outro_app": "Envoyer vers une autre application",
    "salvar_o_arquivo": "Enregistrer le fichier",
    "o_navegador_aqui_nao_oferece_o_compart": "Ce navigateur ne propose pas le partage direct. Vous pouvez enregistrer le fichier et l’envoyer ensuite avec l’application de votre choix.",
    "este_aparelho_nao_abre_a_lista_de_apli": "Cet appareil n’ouvre pas la liste des applications",
    "importe_pelo_menos_um_livro_antes_de_f": "Importez au moins un livre avant de créer une sauvegarde.",
    "estante_vazia": "Étagère vide",
    "nao_deu_para_copiar": "Copie impossible",
    "copiar_detalhes": "Copier les détails",
    "o_backup_foi_salvo_assim_mesmo": "La sauvegarde a quand même été enregistrée",
    "o_aparelho_recusou_abrir_a_lista": "Impossible d’ouvrir la liste de partage",
    "sem_detalhes_do_navegador": "aucun détail du navigateur",
    "o_sistema_nao_aceitou_receber_o_arquiv": "Le système de l’appareil n’a pas pu recevoir le fichier.",
    "o_navegador_considerou_a_situacao_inse": "Le navigateur a bloqué le partage en raison de l’une de ses propres règles de sécurité. Enregistrez le fichier et envoyez-le avec l’application de votre choix.",
    "o_compartilhamento_so_funciona_em_ende": "Le partage ne fonctionne qu’avec des adresses sécurisées. Cette application est ouverte depuis une adresse http:// classique et, dans ce cas, le navigateur bloque l’envoi vers d’autres applications.",
    "este_navegador_nao_conseguiu_iniciar_o": "Ce navigateur n’a pas pu ouvrir le partage. Enregistrez le fichier et envoyez-le avec l’application de votre choix.",
    "o_navegador_recebeu_um_arquivo_em_form": "Le navigateur n’a pas ouvert la liste des applications de partage. Touchez à nouveau le bouton, ou enregistrez le fichier et envoyez-le avec l’application de votre choix.",
    "nao_foi_possivel_gerar_o_backup": "Impossible de créer la sauvegarde.",
    "reunindo_a_sua_estante": "Rassemblement de votre étagère...",
    "preparando_o_backup": "Préparation de la sauvegarde",
    "pronto_nada_mais_esta_esperando": "Terminé : plus rien n’est en attente.",
    "o_progresso_e_as_marcacoes_desses_livr": "La progression et les marques de ces livres seront effacées. Si vous importez les fichiers plus tard, ils reviendront sans marques.",
    "descartar_o_que_esta_esperando": "Supprimer les données en attente ?",
    "lembretes_de_backup_religados": "Rappels de sauvegarde réactivés.",
    "sem_titulo": "Sans titre",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "Rappels désactivés.",
    "manter_ligado": "Les laisser activés",
    "desligar_assim_mesmo": "Désactiver quand même",
    "o_botao_de_salvar_continua_onde_sempre": "Le bouton Enregistrer reste là où il a toujours été, dans Sauvegarde et restauration.",
    "o_lembrete_e_o_unico_aviso_que_existe": "Le rappel est le seul avertissement qui existe. Sans lui, il faudra penser à faire une sauvegarde par vous-même.\n\n",
    "limpar_os_dados_do_navegador_desinstal": "Si les données du navigateur sont effacées, si l’application est désinstallée, si vous changez de téléphone ou si l’appareil tombe en panne, il ne sera pas possible de récupérer votre progression, vos surlignages, citations, notes et marque-pages.\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "Votre étagère n’existe que sur cet appareil. Il n’y a aucune copie sur un serveur, donc il est impossible de la récupérer pour vous.\n\n",
    "leia_antes_de_confirmar": "À lire avant de confirmer",
    "desligar_os_lembretes_de_backup": "Désactiver les rappels de sauvegarde ?",
    "progresso_de_leitura_restaurado_neste": "Progression de lecture restaurée pour ce livre.",
    "pronto": "Terminé.",
    "aplicando_as_suas_preferencias": "Application de vos préférences...",
    "atualize_o_veredas_reader_e_tente_de_n": "Mettez à jour Veredas Reader et réessayez.",
    "este_backup_foi_feito_numa_versao_mais": "Cette sauvegarde a été créée avec une version plus récente de l’application.",
    "este_arquivo_nao_e_um_backup_de_biblio": "Ce fichier n’est pas une sauvegarde de bibliothèque Veredas.",
    "o_conteudo_interno_nao_pode_ser_lido": "Le contenu interne n’a pas pu être lu.",
    "o_backup_esta_corrompido": "La sauvegarde est endommagée.",
    "falta_o_arquivo_biblioteca_json_la_den": "Le fichier biblioteca.json est manquant à l’intérieur.",
    "este_arquivo_nao_parece_ser_um_backup": "Ce fichier ne semble pas être une sauvegarde Veredas.",
    "compactando": "Compression...",
    "para_restaurar_menu_lateral_backup_e_r": "Pour restaurer : menu latéral > Sauvegarde et restauration > Restaurer la sauvegarde.",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas restaure automatiquement les marques et l’endroit où vous vous êtes arrêté.",
    "importe_os_livros_normalmente_no_aplic": "importez les livres normalement dans l’application : lorsqu’elle reconnaît chaque fichier,",
    "ele_nao_contem_os_arquivos_dos_livros": "Il ne contient PAS les fichiers des livres. Pour restaurer complètement,",
    "as_notas_os_marcadores_e_a_organizacao": "vos notes, vos marque-pages et l’organisation de votre étagère.",
    "este_arquivo_guarda_o_seu_progresso_de": "Ce fichier contient votre progression de lecture, vos surlignages, vos citations,",
    "verificando_se_sao_partes_do_mesmo_aud": "Vérification pour savoir s’il s’agit de parties du même livre audio...",
    "analisando_os_arquivos": "Analyse des fichiers",
    "nao_foi_possivel_salvar_o_audiolivro": "Impossible d’enregistrer le livre audio.",
    "audiolivros_grandes_podem_levar_alguns": "Les grands livres audio peuvent prendre quelques instants...",
    "salvando_na_sua_estante": "Enregistrement sur votre étagère",
    "falha_ao_processar_os_arquivos": "Impossible de traiter les fichiers.",
    "falha_ao_processar_o_arquivo": "Impossible de traiter le fichier.",
    "nao_foi_possivel_salvar_o_quadrinho": "Impossible d’enregistrer la bande dessinée.",
    "quase_la": "Presque terminé...",
    "falha_ao_processar_o_quadrinho": "Impossible de traiter la bande dessinée.",
    "autor_desconhecido": "Auteur inconnu",
    "lendo_o_quadrinho": "Lecture de la bande dessinée...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "Impossible d’enregistrer le livre dans la bibliothèque.",
    "nao_foi_possivel_ler_o_pdf": "Impossible de lire le PDF.",
    "lendo_o_pdf": "Lecture du PDF...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "S’il s’agit d’un ancien .doc, ouvrez-le dans Word et enregistrez-le au format .docx avant l’importation.",
    "este_arquivo_nao_e_um_docx_valido": "Ce fichier n’est pas un .docx valide.",
    "livros_com_protecao_da_amazon_nao_pode": "Les livres protégés par Amazon ne peuvent pas être ouverts ici. Utilisez une copie sans DRM ou convertissez le livre en EPUB.",
    "este_arquivo_esta_protegido_por_drm": "Ce fichier est protégé par DRM.",
    "confira_se_a_extensao_corresponde_ao_c": "Vérifiez que l’extension correspond au contenu ou convertissez le livre en EPUB.",
    "este_arquivo_nao_e_um_mobi_valido": "Ce fichier n’est pas un MOBI valide.",
    "nao_foi_possivel_ler_o_arquivo": "Impossible de lire le fichier.",
    "formato_nao_suportado": "Format non pris en charge.",
    "falha_ao_salvar_o_livro_na_biblioteca": "Impossible d’enregistrer le livre dans la bibliothèque.",
    "livro_importado_e_salvo_no_dispositivo": "Livre importé et enregistré sur cet appareil.",
    "audiolivro_importado_e_salvo_no_dispos": "Livre audio importé et enregistré sur cet appareil.",
    "quadrinho_importado_e_salvo_no_disposi": "Bande dessinée importée et enregistrée sur cet appareil.",
    "salvando_na_sua_estante_2": "Enregistrement sur votre étagère...",
    "importando_livro": "Importation du livre",
    "importar_mesmo_assim": "Importer quand même",
    "parece_que_este_livro_ja_esta_na_estan": "Il semble que ce livre soit déjà sur votre étagère",
    "este_livro_ja_esta_na_estante": "Ce livre est déjà sur votre étagère",
    "video_importado_e_salvo_no_dispositivo": "Vidéo importée et enregistrée sur cet appareil.",
    "importacao_cancelada": "Importation annulée.",
    "preparando_o_arquivo": "Préparation du fichier",
    "importando_audiolivro": "Importation du livre audio",
    "importacao_concluida": "Importation terminée",
    "importacao_interrompida": "Importation arrêtée",
    "a_importacao_foi_interrompida_o_que_ja": "L’importation a été arrêtée ; ce qui avait déjà été ajouté reste sur votre étagère.",
    "finalizando": "Finalisation…",
    "nao_foi_possivel_ler_o_arquivo_2": "impossible de lire le fichier",
    "importando_livros": "Importation des livres",
    "livros_quadrinhos_documentos_audiolivr": "Livres, bandes dessinées, documents, livres audio et vidéos",
    "series": "Séries",
    "colecoes": "Collections",
    "organizacao_salva": "Organisation enregistrée.",
    "informe_um_nome_para_o_livro_antes_de": "Donnez un nom au livre avant de l’enregistrer.",
    "nome_do_livro_obrigatorio": "Le livre doit avoir un nom",
    "importe_um_livro_primeiro": "Importez d’abord un livre.",
    "citacao": "citation",
    "anotacao": "note",
    "citacao_2": "Citation",
    "anotacao_2": "Note",
    "uma_citacao": "une citation",
    "uma_anotacao": "une note",
    "o_marcador_sera_removido_da_biblioteca": "Le marque-page sera retiré de la bibliothèque, mais le fichier du livre restera intact.",
    "marcador_de_audio": "Marque-page audio",
    "marcador_de_video": "Marque-page vidéo",
    "nao_foi_possivel_excluir_o_livro": "Impossible de supprimer le livre.",
    "livro_excluido_da_biblioteca": "Livre supprimé de la bibliothèque.",
    "excluir_livro": "Supprimer le livre",
    "isso_remove_apenas_a_copia_armazenada": "Cela supprime uniquement la copie conservée par la bibliothèque, ainsi que la progression, les marque-pages et les notes. Le fichier original de votre propre dossier ne sera pas supprimé.",
    "excluir_livro_2": "Supprimer le livre ?",
    "ordem_personalizada_salva": "Ordre personnalisé enregistré.",
    "ordem_manual_da_sua_estante": "Votre étagère, dans l’ordre que vous avez défini.",
    "agrupamento_alterado_para_minha_ordem": "Le regroupement est passé à Mon ordre.",
    "nova_ordem_salva": "Nouvel ordre enregistré.",
    "nao_foi_possivel_salvar_a_nova_ordem": "Impossible d’enregistrer le nouvel ordre.",
    "baixar_automaticamente": "Télécharger automatiquement",
    "escolha_livremente_onde_o_arquivo_sera": "Choisissez librement où le fichier sera enregistré.",
    "salvar_epub": "Enregistrer l’EPUB",
    "livro_epub": "Livre EPUB",
    "erro_desconhecido": "erreur inconnue",
    "a_permissao_para_salvar_o_arquivo_foi": "L’autorisation d’enregistrer le fichier a été annulée. Rien n’a été modifié dans la bibliothèque.",
    "conversao_cancelada_o_pdf_original_per": "Conversion annulée. Le PDF original reste dans la bibliothèque.",
    "preparando_salvamento": "Préparation de l’enregistrement…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "La copie du PDF n’est pas disponible dans la bibliothèque.",
    "reconstruindo_o_livro_localmente": "Reconstruction du livre sur votre appareil.",
    "convertendo_pdf": "Conversion du PDF",
    "nao_foi_possivel_compartilhar_o_livro": "Impossible de partager le livre.",
    "o_arquivo_foi_preparado_para_voce_comp": "Le fichier est prêt à être partagé dans une autre application.",
    "livro_compartilhado": "Livre partagé.",
    "a_copia_deste_livro_nao_esta_disponive": "La copie de ce livre n’est pas disponible dans la bibliothèque.",
    "para_manter_a_politica_de_compartilham": "Pour respecter la politique de partage de la bibliothèque, cette application ne permet pas de partager les fichiers EPUB et MOBI.",
    "quadrinhos_ficam_guardados_somente_no": "Les bandes dessinées sont conservées uniquement sur votre appareil et ne peuvent pas être partagées par cette application.",
    "audiolivros_e_videos_ficam_guardados_s": "Les livres audio et les vidéos sont conservés uniquement sur votre appareil et ne peuvent pas être partagés par cette application.",
    "formato_protegido": "Format protégé",
    "compartilhamento_indisponivel": "Partage indisponible",
    "concluido": "Terminé",
    "ainda_nao_comecado": "Pas encore commencé",
    "continue_lendo": "Continuer la lecture",
    "continue_ouvindo": "Continuer l’écoute",
    "continue_assistindo": "Continuer le visionnage",
    "comece_por_aqui": "Commencer ici",
    "comece_a_ouvir": "Commencer à écouter",
    "comece_a_assistir": "Commencer à regarder",
    "no_total": "au total",
    "para_ler": "à lire",
    "sua_estante": "Votre étagère",
    "livros_organizados_pela_opcao_selecion": "Livres organisés selon l’option que vous avez choisie.",
    "uma_prateleira_para_cada_tipo_de_arqui": "Une étagère pour chaque type de fichier.",
    "autores_agrupados_em_ordem_alfabetica": "Auteurs regroupés par ordre alphabétique.",
    "toque_para_continuar_de_onde_parou": "Touchez pour reprendre là où vous vous étiez arrêté.",
    "para_ler_2": "À lire",
    "lendo_agora": "En cours de lecture",
    "audio_e_video": "Audio et vidéo",
    "trechos_salvos_separadamente_dos_marca": "Passages enregistrés séparément des marque-pages.",
    "comentarios_vinculados_a_trechos_selec": "Commentaires liés aux passages que vous avez sélectionnés.",
    "paginas_salvas_para_voltar_rapidamente": "Pages enregistrées pour y revenir rapidement.",
    "do_maior_para_o_menor_progresso_de_lei": "Du plus grand au plus petit progrès de lecture.",
    "livros_adicionados_ou_lidos_mais_recen": "Livres ajoutés ou lus le plus récemment.",
    "ordem_alfabetica_pelo_titulo": "Par ordre alphabétique des titres.",
    "separa_em_prateleiras_de_epub_pdf_docx": "Sépare en étagères les EPUB, PDF, DOCX, livres audio, vidéos…",
    "tipo_de_arquivo": "Type de fichier",
    "organiza_e_separa_os_livros_por_autor": "Organise et sépare les livres par auteur.",
    "agrupar_por_autor": "Regrouper par auteur",
    "pressione_o_livro_e_mova_o": "Maintenez un livre appuyé, puis déplacez-le.",
    "minha_ordem": "Mon ordre",
    "epub_pronto": "EPUB prêt",
    "conversao_concluida": "Conversion terminée",
    "necessario_para_salvar_o_epub_ao_lado": "Nécessaire pour enregistrer l’EPUB à côté de l’original",
    "escolha_a_pasta_do_pdf": "Choisir le dossier du PDF",
    "processando": "Traitement…",
    "processamento_local_no_navegador": "Traité sur votre appareil, dans le navigateur",
    "convertendo_livro": "Conversion du livre",
    "livro_em_pdf": "Livre PDF",
    "recalculando_paginas": "Recalcul des pages...",
    "ajustando_leitura": "Ajustement de la mise en page",
    "abrir_comentario": "Ouvrir le commentaire",
    "anotacao_salva": "Note enregistrée.",
    "anotacao_atualizada": "Note mise à jour.",
    "escreva_uma_nota_antes_de_salvar": "Écrivez une note avant de l’enregistrer.",
    "nao_foi_possivel_compartilhar": "Impossible de partager.",
    "compartilhamento_indisponivel_2": "Partage indisponible.",
    "credito_do_trecho": "— {obra}, {autor}",
    "credito_do_trecho_sem_autor": "— {obra}",
    "trecho_copiado": "Passage copié.",
    "trecho_compartilhado": "Passage partagé.",
    "citacao_salva": "Citation enregistrée.",
    "trecho_grifado": "Passage surligné.",
    "grifo_removido": "Surlignage supprimé.",
    "comentario_apagado": "Commentaire supprimé.",
    "remover_grifo": "Supprimer le surlignage",
    "apagar_comentario": "Supprimer le commentaire",
    "remover_grifo_2": "Supprimer le surlignage ?",
    "apagar_comentario_2": "Supprimer le commentaire ?",
    "remover_este_grifo": "Supprimer ce surlignage ?",
    "apagar_este_comentario": "Supprimer ce commentaire ?",
    "sem_comentario": "Aucun commentaire",
    "comentario": "Commentaire",
    "marcador_removido_desta_pagina": "Marque-page supprimé de cette page.",
    "pagina_adicionada_aos_marcadores": "Page ajoutée à vos marque-pages.",
    "este_e_o_inicio_do_livro": "Ceci est le début du livre.",
    "esta_e_a_primeira_pagina": "Ceci est la première page.",
    "voce_chegou_ao_fim_do_livro": "Vous êtes arrivé à la fin du livre.",
    "voce_chegou_ao_fim_do_quadrinho": "Vous êtes arrivé à la fin de la bande dessinée.",
    "agora_em_revista_aberta_duas_paginas_l": "Maintenant en double page : deux pages côte à côte, avec la couverture seule.",
    "leitura_horizontal_ativada_neste_livro": "La lecture horizontale est activée pour ce livre.",
    "rolagem_vertical_ativada_neste_livro": "Le défilement vertical est activé pour ce livre.",
    "leitura_pagina_a_pagina_ativada_neste": "La lecture page par page est activée pour cette bande dessinée.",
    "rolagem_continua_ativada_neste_quadrin": "Le défilement continu est activé pour cette bande dessinée.",
    "mudar_para_rolagem_vertical": "Passer au défilement vertical",
    "mudar_para_leitura_horizontal": "Passer à la lecture horizontale",
    "rolagem_continua_estilo_webtoon": "Défilement continu (style webtoon)",
    "voltar_para_pagina_a_pagina": "Revenir à la lecture page par page",
    "separando_os_capitulos": "Séparation des chapitres...",
    "lendo_o_livro": "Lecture du livre",
    "lendo_o_markdown": "Lecture du Markdown",
    "lendo_o_documento": "Lecture du document",
    "pagina_indisponivel": "Page indisponible.",
    "isto_acontece_so_desta_vez": "Cela n’arrive que cette fois.",
    "preparando_o_quadrinho": "Préparation de la bande dessinée",
    "abrindo_o_quadrinho": "Ouverture de la bande dessinée...",
    "montando_as_paginas": "Création des pages...",
    "nao_foi_possivel_abrir_este_livro": "Impossible d’ouvrir ce livre.",
    "abertura_cancelada": "Ouverture annulée.",
    "o_livro_demorou_demais_para_abrir_e_fo": "Le livre a mis trop de temps à s’ouvrir et l’opération a été arrêtée.",
    "importe_o_arquivo_novamente_para_conti": "Importez à nouveau le fichier pour continuer la lecture.",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "Le fichier de ce livre n’est plus enregistré sur votre appareil.",
    "preparando_sua_leitura": "Préparation de votre lecture...",
    "abrindo_livro": "Ouverture du livre",
    "leitura_concluida": "Lecture terminée.",
    "a_voz_foi_interrompida_pelo_navegador": "Le navigateur a arrêté la voix.",
    "nao_foi_possivel_preparar_este_trecho": "Impossible de préparer ce passage pour l’audio.",
    "a_leitura_em_voz_alta_nao_e_suportada": "La lecture à voix haute n’est pas prise en charge par ce navigateur.",
    "pausar_leitura": "Mettre la lecture en pause",
    "em_pausa": "En pause",
    "leitura_em_voz_alta_nao_disponivel_nes": "La lecture à voix haute n’est pas disponible dans ce navigateur",
    "nome_do_marcador": "Nom du marque-page",
    "o_marcador_sera_removido_deste_audioli": "Le marque-page sera supprimé de ce livre audio.",
    "nao_foi_possivel_salvar_o_marcador": "Impossible d’enregistrer le marque-page.",
    "ja_existe_um_marcador_neste_ponto": "Un marque-page existe déjà à cet endroit.",
    "timer_de_sono_encerrado": "Le minuteur de sommeil est terminé.",
    "fim_do_cap": "Fin du chap.",
    "timer_desativado": "Minuteur désactivé.",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "L’audio se mettra en pause à la fin du chapitre.",
    "este_audiolivro_nao_tem_capitulos": "Ce livre audio n’a pas de chapitres.",
    "ao_fim_do_capitulo": "À la fin du chapitre",
    "desativar_timer": "Désactiver le minuteur",
    "mais_10_minutos_no_timer": "10 minutes de plus sur le minuteur.",
    "somar_10_minutos": "Ajouter 10 minutes",
    "pausa_ao_fim_do_capitulo": "Mettre en pause à la fin du chapitre",
    "no_livro_todo": "Dans tout le livre",
    "video": "Vidéo",
    "audiolivro_concluido": "Livre audio terminé.",
    "video_concluido": "Vidéo terminée.",
    "video_2": "vidéo",
    "audio": "audio",
    "toque_em_reproduzir_para_comecar": "Touchez Lecture pour commencer.",
    "falha_ao_carregar_o_audio": "Impossible de charger l’audio.",
    "exclua_o_da_biblioteca_e_importe_o_arq": "Supprimez-le de la bibliothèque et importez à nouveau le fichier.",
    "os_nomes_dos_arquivos_seguem_uma_seque": "Les noms des fichiers suivent une séquence, ils ressemblent donc aux chapitres d’un même livre audio.",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "Les fichiers partagent le même album dans leurs balises, ils ressemblent donc aux chapitres d’un même livre audio.",
    "libere_espaco_ou_exclua_livros_da_bibl": "Libérez de l’espace ou supprimez des livres de la bibliothèque et réessayez.",
    "o_armazenamento_do_aparelho_esta_cheio": "Le stockage de votre appareil est plein.",
    "preparando_a_capa": "Préparation de la couverture...",
    "remova_esse_arquivo_da_selecao_e_tente": "Retirez ce fichier de la sélection et réessayez.",
    "sequencia": "séquence",
    "o_arquivo_pode_estar_incompleto_tente": "Le fichier est peut-être incomplet. Essayez de le télécharger à nouveau.",
    "conferindo_se_o_audio_pode_ser_reprodu": "Vérification de la lecture audio...",
    "conferindo_se_o_video_pode_ser_reprodu": "Vérification de la lecture vidéo...",
    "lendo_titulo_capitulos_e_capa": "Lecture du titre, des chapitres et de la couverture...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "Le fichier est peut-être endommagé ou dans un format audio que le navigateur ne peut pas lire. Essayez de le convertir en MP3 ou M4B (AAC).",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "Le fichier est peut-être endommagé ou dans un format vidéo que le navigateur ne peut pas lire. Essayez de le convertir en MP4 avec une vidéo H.264 et un audio AAC.",
    "converta_o_audiolivro_para_m4b_com_aud": "Convertissez le livre audio en M4B avec audio AAC (ou en MP3), puis importez-le à nouveau.",
    "converta_o_video_para_mp4_com_audio_aa": "Convertissez la vidéo en MP4 avec audio AAC et vidéo H.264, puis importez-la à nouveau.",
    "o_navegador_nao_reproduz_o_formato_de": "Le navigateur ne peut pas lire le format audio de ce fichier.",
    "arquivos_com_protecao_nao_podem_ser_re": "Les fichiers protégés ne peuvent pas être lus ici. Utilisez une copie sans DRM.",
    "nao_ha_espaco_suficiente_no_aparelho_p": "Il n’y a pas assez d’espace sur votre appareil pour ce livre audio.",
    "confira_se_a_extensao_corresponde_ao_c_2": "Vérifiez que l’extension correspond au contenu ou convertissez l’audio en MP3 ou M4B (AAC).",
    "imagem_invalida": "image invalide",
    "imagem_demorou_demais": "l’image a mis trop de temps à charger",
    "imagem_vazia": "image vide",
    "inicio": "Début",
    "mp4_moov_nao_encontrado": "La vidéo semble incomplète ou endommagée.",
    "pagina": "Page",
    "esta_pagina_nao_esta_disponivel": "Cette page n’est pas disponible.",
    "esta_pagina_nao_pode_ser_descompactada": "Impossible de décompresser cette page.",
    "quadrinho_fechado": "Bande dessinée fermée.",
    "ele_pode_estar_incompleto_dividido_em": "Elle est peut-être incomplète, divisée en plusieurs parties ou utilise une variante RAR que l’application ne reconnaît pas. La convertir en CBZ règle généralement le problème.",
    "remova_a_senha_do_arquivo_e_importe_de": "Supprimez le mot de passe du fichier et importez-le à nouveau.",
    "nao_foi_possivel_ler_este_arquivo_de_q": "Impossible de lire ce fichier de bande dessinée.",
    "este_quadrinho_esta_protegido_por_senh": "Cette bande dessinée est protégée par un mot de passe.",
    "lendo_o_indice_do_quadrinho": "Lecture de l’index de la bande dessinée...",
    "o_arquivo_pode_ser_grande_demais_para": "Le fichier est peut-être trop volumineux pour la mémoire de cet appareil. Diviser la bande dessinée en parties plus petites règle généralement le problème.",
    "nao_foi_possivel_abrir_este_quadrinho": "Impossible d’ouvrir cette bande dessinée.",
    "lendo_o_arquivo": "Lecture du fichier...",
    "preparando_o_leitor_de_cbr": "Préparation du lecteur CBR...",
    "o_arquivo_pode_estar_incompleto_proteg": "Le fichier est peut-être incomplet, protégé par un mot de passe ou endommagé.",
    "nao_foi_possivel_ler_este_quadrinho": "Impossible de lire cette bande dessinée.",
    "o_arquivo_precisa_conter_imagens_jpg_p": "Le fichier doit contenir des images (JPG, PNG, WEBP ou GIF).",
    "nao_encontramos_paginas_dentro_deste_q": "Aucune page trouvée dans cette bande dessinée.",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "Il n’y a pas assez d’espace sur votre appareil pour cette bande dessinée.",
    "cabecalho_de_item_invalido": "Une partie du fichier est endommagée.",
    "a_pasta_vendor_libarchive_precisa_esta": "Il manque un composant de l’application pour ouvrir cette bande dessinée. Convertissez-la en CBZ ou réinstallez l’application.",
    "o_leitor_de_cbr_nao_foi_encontrado": "Le lecteur CBR est introuvable.",
    "converta_o_quadrinho_para_cbz_zip_e_im": "Convertissez la bande dessinée en CBZ (ZIP) et importez-la à nouveau.",
    "este_navegador_nao_consegue_abrir_arqu": "Ce navigateur ne peut pas ouvrir les fichiers CBR.",
    "convertendo_o_markdown": "Conversion du Markdown",
    "lendo_o_texto": "Lecture du texte",
    "pdf_indisponivel": "PDF indisponible.",
    "epub_invalido_nenhum_capitulo_no_spine": "Cet EPUB est endommagé : les chapitres du livre sont introuvables.",
    "livro_sem_titulo": "Livre sans titre",
    "epub_invalido_arquivo_opf_nao_encontra": "Cet EPUB est incomplet ou endommagé et ne peut pas être ouvert.",
    "epub_invalido_container_xml_nao_encont": "Cet EPUB est incomplet ou endommagé et ne peut pas être ouvert.",
    "organizando_o_texto": "Mise en page du texte",
    "descompactando_o_livro": "Décompression du livre",
    "nao_encontramos_conteudo_para_exibir_n": "Nous n’avons rien trouvé à afficher dans ce fichier.",
    "livro_sem_texto_legivel": "Livre sans texte lisible",
    "o_arquivo_pode_estar_corrompido_tente": "Le fichier est peut-être endommagé. Essayez de le convertir en EPUB.",
    "nao_foi_possivel_extrair_o_texto_deste": "Impossible d’extraire le texte de ce MOBI.",
    "nenhum_registro_de_conteudo_foi_encont": "Le texte du livre est introuvable dans ce fichier.",
    "arquivo_mobi_sem_texto": "Fichier MOBI sans texte.",
    "o_dicionario_de_compressao_esta_vazio": "Une partie du contenu de ce MOBI est manquante.",
    "arquivo_mobi_incompleto": "Fichier MOBI incomplet.",
    "as_tabelas_de_compressao_nao_foram_enc": "Une partie du contenu de ce MOBI est manquante.",
    "converta_o_arquivo_para_epub_em_um_pro": "Convertissez le fichier en EPUB avec un programme comme Calibre et importez-le à nouveau.",
    "compressao_mobi_nao_reconhecida": "Ce MOBI utilise un format interne que l’application ne reconnaît pas.",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "Impossible de lire l’en-tête du livre.",
    "arquivo_mobi_corrompido": "Fichier MOBI endommagé.",
    "a_lista_interna_de_registros_esta_inco": "Le fichier est incomplet. Essayez de le télécharger ou de le convertir à nouveau.",
    "o_download_parece_ter_sido_interrompid": "Le téléchargement semble avoir été interrompu. Téléchargez à nouveau le fichier.",
    "tabela_de_compressao_mobi_corrompida": "Une partie de ce fichier MOBI est endommagée.",
    "tabela_de_compressao_mobi_incompleta": "Ce fichier MOBI est incomplet.",
    "tabela_de_compressao_mobi_invalida": "Une partie de ce fichier MOBI est endommagée.",
    "este_arquivo_docx_nao_tem_conteudo_de": "Ce fichier .docx ne contient aucun texte pouvant être affiché.",
    "documento_sem_texto": "Document sans texte",
    "o_arquivo_pode_estar_corrompido_proteg": "Le fichier est peut-être endommagé, protégé par un mot de passe ou être un ancien .doc. Enregistrez-le à nouveau en .docx et importez-le une nouvelle fois.",
    "nao_foi_possivel_ler_este_arquivo_docx": "Impossible de lire ce fichier DOCX.",
    "convertendo_o_documento": "Conversion du document",
    "conecte_se_a_internet_uma_vez_para_bai": "Connectez-vous à Internet une fois pour télécharger le composant, puis rouvrez le livre.",
    "o_conversor_de_docx_nao_carregou": "Le convertisseur DOCX ne s’est pas chargé.",
    "video_mp4": "Vidéo (MP4)",
    "audiolivro_m4b": "Livre audio (M4B)",
    "audiolivro_mp3": "Livre audio (MP3)",
    "quadrinho_cbt": "Bande dessinée (CBT)",
    "quadrinho_cb7": "Bande dessinée (CB7)",
    "quadrinho_cbr": "Bande dessinée (CBR)",
    "quadrinho_cbz": "Bande dessinée (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "Texte (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "Enregistrement annulé.",
    "o_arquivo_esta_vindo_do_armazenamento": "Le fichier est en cours de transfert depuis le stockage cloud vers votre appareil.",
    "baixando_o_arquivo": "Téléchargement du fichier",
    "cancelando": "Annulation...",
    "use_grifar_citacao_anotar_ou_marcador": "Utilisez Surligner, Citation, Note ou Marque-page pendant la lecture.",
    "nenhuma_marcacao_ainda": "Aucune marque pour le moment",
    "trecho_original": "Passage original",
    "procurar_meus_livros": "Trouver mes livres",
    "a_busca_fica_sempre_disponivel_no_menu": "La recherche est toujours disponible dans le menu latéral, sous Système.",
    "da_para_fazer_depois": "Vous pouvez le faire plus tard",
    "nada_entra_na_estante_sem_a_sua_confir": "Rien n’arrive sur votre étagère sans votre accord : vous voyez la liste et cochez ce que vous voulez importer.",
    "voce_revisa_antes": "Vous vérifiez d’abord",
    "escolha_uma_pasta_downloads_e_um_bom_c": "Choisissez un dossier et l’application le parcourt, ainsi que tous ses sous-dossiers.",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "Recherche d’EPUB, MOBI, CBZ, CBR et M4B",
    "voltar_e_revisar": "Retour et vérification",
    "ler_os_termos": "Lire les conditions",
    "ler_a_politica": "Lire la politique",
    "os_dois_documentos_ficam_sempre_dispon": "Les deux documents sont toujours disponibles dans le menu latéral, sous À propos.",
    "leia_com_calma": "Prenez votre temps",
    "a_politica_e_os_termos_explicam_como_o": "La politique et les conditions expliquent comment l’application conserve vos livres et ce que vous pouvez en faire. Pour utiliser la bibliothèque, vous devez les accepter.",
    "nada_acontece_sem_o_aceite": "Pour commencer, veuillez accepter les conditions",
    "aceitar_e_continuar": "Accepter et continuer",
    "nao_aceito": "Je n’accepte pas",
    "termos_de_uso_2": "Conditions d’utilisation",
    "politica_de_privacidade_2": "Politique de confidentialité",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "L’application n’accède qu’aux fichiers et dossiers que vous choisissez, au moment où vous le décidez.",
    "voce_no_controle": "Vous gardez le contrôle",
    "depois_de_importar_um_livro_voce_le_se": "Une fois un livre importé, vous pouvez le lire sans Internet.",
    "funciona_offline": "Fonctionne hors ligne",
    "livros_marcacoes_e_progresso_sao_guard": "Les livres, les marques et la progression restent sur votre appareil. Rien n’est envoyé à nos serveurs.",
    "tudo_fica_no_seu_aparelho": "Tout reste sur votre appareil",
    "escolha_o_que_deseja_adicionar_a_bibli": "Choisissez ce que vous souhaitez ajouter à la bibliothèque. Les fichiers identiques à ceux déjà présents sur votre étagère sont automatiquement ignorés.",
    "voce_pode_tentar_outra_pasta_ou_import": "Vous pouvez essayer un autre dossier ou importer des fichiers avec le bouton +.",
    "a_leitura_acontece_so_no_seu_dispositi": "La lecture se fait uniquement sur votre appareil.",
    "voce_escolhe_a_pasta": "Vous choisissez le dossier",
    "tema_tipografia_margens_modo_de_virada": "Thème, typographie, marges, style de changement de page et réglages audio.",
    "restaurar_minhas_preferencias": "Restaurer mes préférences",
    "o_backup_manda_as_marcacoes_atuais_dos": "La sauvegarde l’emporte. Les marques actuelles de tout livre présent dans le fichier seront remplacées par celles de la sauvegarde.",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "Rien n’est effacé. Les marques des deux côtés sont réunies et la progression la plus récente l’emporte.",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "Que faire de ce qui est déjà sur votre étagère",
    "grifos_citacoes_e_notas": "surlignages, citations et notes",
    "preparando_o_arquivo_2": "Préparation du fichier...",
    "os_livros_em_si_nem_as_capas_por_isso": "Ni les livres eux-mêmes, ni les couvertures — c’est pourquoi le fichier ne pèse que quelques Ko. La personne qui le reçoit doit avoir les fichiers des livres pour que les marques retrouvent leur place, et les couvertures réapparaissent automatiquement à l’importation.",
    "nao_vai_no_arquivo": "Absent du fichier",
    "o_seu_progresso_de_leitura_os_grifos_a": "Votre progression de lecture, vos surlignages, vos citations, vos notes, vos marque-pages et l’organisation de votre étagère — statut, favoris, collections, séries et tags.",
    "vai_no_arquivo": "Présent dans le fichier",
    "descartar_o_que_esta_esperando_2": "Supprimer les données en attente",
    "esperando_o_arquivo": "En attente du fichier",
    "avisar_quando_fizer_tempo_sem_backup": "Me rappeler lorsqu’un certain temps s’est écoulé sans sauvegarde",
    "livros_que_ainda_nao_estiverem_na_esta": "Les livres qui ne sont pas encore sur votre étagère restent en attente : dès que vous importez leur fichier, les marques reviennent automatiquement.",
    "restaurar_backup": "Restaurer la sauvegarde",
    "salvar_backup": "Enregistrer la sauvegarde",
    "ainda_nao_ha_itens": "Rien ici pour le moment",
    "arraste_um_livro_para_outra_posicao_na": "Faites glisser un livre vers une autre position sur l’étagère pour enregistrer votre propre ordre. Cet ordre manuel devient alors prioritaire sur le regroupement par auteur.",
    "separe_por_virgulas": "Séparer par des virgules",
    "ex_estudos_ficcao": "ex. Études, Fiction...",
    "pasta_estante": "Dossier / étagère",
    "ex_trilogia": "ex. Trilogie...",
    "serie": "Série",
    "aparece_em_favoritos": "Apparaît dans les Favoris.",
    "nome_do_livro": "Nom du livre",
    "nenhum_registro_ainda": "Rien d’enregistré pour le moment",
    "no_leitor_toque_no_icone_de_marcador_p": "Dans le lecteur, touchez l’icône de marque-page pour enregistrer la page.",
    "nenhum_marcador_ainda": "Aucun marque-page pour le moment",
    "a_gravacao_e_independente_da_localizac": "L’enregistrement est indépendant de l’emplacement du PDF et ne modifie pas le fichier original.",
    "o_pdf_original_nao_precisa_estar_nessa": "Le PDF original n’a pas besoin d’être dans ce dossier",
    "excluir_da_biblioteca": "Supprimer de la bibliothèque",
    "adicionar_livro": "Ajouter un livre",
    "adicione_livros_e_acompanhe_o_que_esta": "Ajoutez des livres et suivez ce qui est en attente, en cours et votre progression.",
    "tudo_pronto_para_a_proxima_leitura": "Tout est prêt pour votre prochaine lecture.",
    "sua_biblioteca": "Votre bibliothèque",
    "arraste_um_livro_para_reposiciona_lo_a": "Faites glisser un livre pour le déplacer : l’étagère passe à Mon ordre et conserve la séquence.",
    "importe_um_livro_ou_ajuste_seus_filtro": "Importez un livre ou ajustez vos filtres.",
    "nada_por_aqui_ainda": "Rien ici pour le moment",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "Touchez + et choisissez des fichiers MP3, M4B ou MP4. Plusieurs MP3 de chapitres peuvent devenir un seul livre audio.",
    "nada_para_ouvir_ou_assistir_ainda": "Rien à écouter ou à regarder pour le moment",
    "o_pdf_original_permanece_intacto_na_pa": "Le PDF original reste intact dans votre propre dossier.",
    "paginas_como_imagem": "Pages sous forme d’images",
    "paginas_do_pdf": "Pages du PDF",
    "em_navegadores_sem_suporte_a_acesso_di": "Dans les navigateurs sans accès direct au système de fichiers, l’EPUB sera téléchargé à la place.",
    "essa_permissao_e_dada_somente_a_esta_a": "Cette autorisation est accordée à cette application uniquement et empêche toute modification du fichier original.",
    "selecione_a_pasta_que_contem_o_pdf": "Sélectionnez le dossier qui contient le PDF",
    "preparando": "Préparation…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "Le fichier est en cours de lecture et de reconstruction. Les gros livres peuvent prendre quelques instants.",
    "revistas_apostilas_complexas_formulari": "Les magazines, cahiers complexes, formulaires, documents contenant de nombreux tableaux ou PDF numérisés peuvent perdre une partie de leur mise en page d’origine.",
    "funcionalidade_indicada_apenas_para_li": "Destiné aux livres",
    "o_epub_e_melhor_para_livros_com_texto": "L’EPUB est préférable pour les livres avec du texte sélectionnable, car il permet d’ajuster la typographie, la taille, les marges et le mode de lecture.",
    "trecho_selecionado": "Passage sélectionné",
    "trecho_comentado": "Passage avec un commentaire",
    "aplicando_zoom": "Zoom en cours...",
    "nao_foi_possivel_carregar_esta_pagina": "Impossible de charger cette page.",
    "nomear_marcador": "Nommer le marque-page",
    "toque_em_marcar_agora_para_guardar_est": "Touchez « Marquer maintenant » pour enregistrer cet emplacement et y revenir quand vous le souhaitez.",
    "timer_ativo": "Minuteur activé",
    "trecho_ausente_ou_corrompido_no_arquiv": "[Passage absent ou endommagé dans le fichier original]",
    "novos_livros_vao_abrir_em_leitura_v": "Les nouveaux livres s’ouvriront en mode de lecture {v}.",
    "leitura_efetivo_aplicada_a_este_livro": "Lecture {efetivo} appliquée à ce livre.",
    "automatico_neste_livro_leitura_efetivo": "Automatique pour ce livre : lecture {efetivo}.",
    "agora_esta_em_efetivo_no_automatico_fo": "Maintenant réglé sur {efetivo} ; en mode automatique, {format} s’ouvre en {padrao}.",
    "esta_escolha_vale_so_para_v_cada_livro": "Ce choix s’applique uniquement à « {v} ». Chaque livre conserve son propre sens de défilement.",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} ne sont pas encore sur votre étagère.",
    "escolha_uma_pasta_para_procurar_label": "Choisissez un dossier pour rechercher {label}.",
    "subtitle_versao_build": "{subtitle} · version {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "Impossible de lire {path} ; utilisation du texte intégré.",
    "seu_ultimo_backup_foi_ha_dias_dias": "Votre dernière sauvegarde date de {dias} jours",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "{aguardando} livre de la sauvegarde n’est pas encore présent. Sa progression et ses marques ont été conservées : dès que vous importez le fichier, tout se remet automatiquement en place.",
      "other": "{aguardando} livres de la sauvegarde ne sont pas encore présents. Leur progression et leurs marques ont été conservées : dès que vous importez chaque fichier, tout se remet automatiquement en place."
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "{atualizados} livre sur votre étagère a été mis à jour.",
      "other": "{atualizados} livres sur votre étagère ont été mis à jour."
    },
    "criado_em_quando": "Créé le {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "Sauvegarde prête : {livros} livres et {marcacoes} marques.",
    "endereco_seguro_seguro": "adresse sécurisée : {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "Progression et {marcas} marque restaurées pour ce livre.",
      "other": "Progression et {marcas} marques restaurées pour ce livre."
    },
    "restaurando_v_de_length": "Restauration ({v} sur {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} livres · {marcacoes} marques",
    "criado_em_v": "Créé le {v}",
    "reunindo_a_sua_estante_v_de_length": "Rassemblement de votre étagère ({v} sur {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "« {titulo} » a déjà été importé et se trouve toujours dans votre bibliothèque. Aucune nouvelle copie n’a été créée.",
    "length_arquivos_de_audio": "{length} fichiers audio...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "{falhas} fichier n’a pas pu être lu.",
      "other": "{falhas} fichiers n’ont pas pu être lus."
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} étaient déjà dans la bibliothèque et ont été ignorés.",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "{importados} livre ajouté à votre étagère.",
      "other": "{importados} livres ajoutés à votre étagère."
    },
    "epub_salvo_em_filename": "EPUB enregistré dans {fileName}.",
    "falha_ao_converter_o_pdf_v": "Impossible de convertir le PDF : {v}",
    "pagina_page_de_totalpages": "Page {page} sur {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} page",
      "other": "{totalPages} pages"
    },
    "length_resultado_s_para_search": {
      "one": "{length} résultat pour « {search} »",
      "other": "{length} résultats pour « {search} »"
    },
    "capitulo_v": "Chapitre {v}",
    "organizando_capitulo_v_de_totalchapter": "Mise en page du chapitre {v} sur {totalChapters}",
    "pagina_v": "Page {v}",
    "paginas_v_v2": "Pages {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} page prête",
      "other": "{length} pages prêtes"
    },
    "montando_as_paginas_pagessofar_prontas": "Création des pages — {pagesSoFar} terminées",
    "lendo_pagina_v_de_length": "Lecture de la page {v} sur {length}",
    "marcador_salvo_em_t": "Marque-page enregistré à {t}.",
    "o_audio_vai_pausar_em_minutes_minutos": "L’audio se mettra en pause dans {minutes} minutes.",
    "length_capitulos_toque_para_ir_direto": "{length} chapitres · touchez pour accéder directement au chapitre.",
    "narrado_por_narrator": "Narration par {narrator}",
    "velocidade_de_reproducao_rate": "Vitesse de lecture : {rate}",
    "avancar_f_segundos": "Avancer de {f} secondes",
    "nao_foi_possivel_abrir_este_v": "Impossible d’ouvrir ce {v}.",
    "nao_foi_possivel_ler_o_arquivo_de_v": "Impossible de lire le fichier {v}.",
    "o_v_esta_danificado_neste_ponto": "Le {v} est endommagé à cet endroit.",
    "o_navegador_nao_consegue_reproduzir_es": "Le navigateur ne peut pas lire ce fichier {v}.",
    "nao_foi_possivel_reproduzir_este_v": "Impossible de lire ce {v}.",
    "os_dados_deste_noun_estao_incompletos": "Les données de ce fichier ({noun}) sont incomplètes.",
    "importe_o_arquivo_novamente_para_conti_2": "Importez à nouveau le fichier pour continuer avec {v}.",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "Le fichier de ce contenu ({noun}) n’est plus enregistré sur votre appareil.",
    "nao_foi_possivel_descobrir_a_duracao_d": "Impossible de déterminer la durée de « {name} ».",
    "lendo_faixa_v_de_length": "Lecture de la piste {v} sur {length}...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "Impossible de déterminer la durée de ce {v}.",
    "este_format_nao_pode_ser_reproduzido_n": "Ce {format} ne peut pas être lu dans ce navigateur.",
    "este_format_esta_protegido_por_drm": "Ce {format} est protégé par DRM.",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "Le fichier fait {bytes} et il reste environ {v}. Libérez de l’espace ou supprimez des livres de la bibliothèque.",
    "este_arquivo_nao_e_um_format_valido": "Ce fichier n’est pas un {format} valide.",
    "preparando_as_paginas_vistas_de_total": "Préparation des pages ({vistas} sur {total})...",
    "preparando_total_pagina_s": {
      "one": "Préparation de {total} page...",
      "other": "Préparation de {total} pages..."
    },
    "preparando_as_paginas_v_de_total": "Préparation des pages ({v} sur {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "Il occupe environ {bytes} et il reste environ {v}. Libérez de l’espace ou supprimez des livres de la bibliothèque.",
    "envio_direto_exige_endereco_seguro": "L’envoi direct vers une autre application n’est pas disponible, car cette page n’a pas été ouverte depuis une adresse sécurisée. Enregistrez le fichier et envoyez-le avec l’application de votre choix.",
    "na_estante": "sur l’étagère",
    "nao_foi_possivel_montar_o_arquivo": "Impossible de créer le fichier.",
    "este_navegador_nao_oferece_o_envio_dir": "Ce navigateur ne permet pas l’envoi direct vers une autre application. Enregistrez le fichier et joignez-le avec l’application de votre choix.",
    "voce_ainda_nao_fez_nenhum_backup": "Vous n’avez encore effectué aucune sauvegarde.",
    "converter_para_epub": "Convertir en EPUB",
    "esta_pagina_nao_pode_ser_exibida": "Impossible d’afficher cette page.",
    "na_ordem_em_que_serao_tocados": "Dans l’ordre de lecture",
    "este_capitulo_nao_pode_ser_exibido": "Impossible d’afficher ce chapitre.",
    "livro": "Livre",
    "restantes": " restants",
    "como_seus_dados_sao_tratados": "Comment vos données sont traitées",
    "condicoes_de_uso_do_aplicativo": "Conditions d’utilisation de l’application",
    "audiolivro": "livre audio",
    "sobre_o_aplicativo": "À propos de l’application",
    "o_que_e_o_veredas_reader": "Ce qu’est Veredas Reader",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(cet appareil ne permet pas de partager ce type de fichier)",
    "livros": "livres",
    "lendo": "lecture",
    "lidos": "terminés",
    "compartilhar_livro": "Partager le livre",
    "n_livros": {
      "one": "{n} livre",
      "other": "{n} livres"
    },
    "livros_unidade": {
      "one": "livre",
      "other": "livres"
    },
    "uma_faixa_discreta_depois_de_n_dias": "Une bande discrète apparaît sur l’étagère après {n} jours sans sauvegarde. Elle n’interrompt jamais votre lecture.",
    "scanned_arquivos_verificados_livros_enc": "{scanned} fichiers vérifiés · {encontrados} livres trouvés",
    "v_de_total": "{v} sur {total}",
    "voltar_n_segundos": "Revenir en arrière de {n} secondes",
    "cancelado": "Annulé",
    "arquivo": "Fichier",
    "outro": "Autre",
    "outros": "Autres",
    "audiolivro_2": "Livre audio",
    "pausar": "Pause",
    "marcador": "Marque-page",
    "leitura": "Lecture",
    "grifo": "Surlignage",
    "editar": "Modifier",
    "apagar": "Supprimer",
    "concluir": "Terminer",
    "recentes": "Récent",
    "progresso": "Progression",
    "entendi": "Compris",
    "aviso": "Avis",
    "descartar": "Supprimer",
    "copiado": "Copié",
    "restaurar": "Restaurer",
    "restaurando": "Restauration",
    "excluir": "Supprimer",
    "grifos": "Surlignages",
    "arquivo_vazio": "Fichier vide.",
    "e_mais_n_arquivos": {
      "one": "et {n} autre fichier, dans l’ordre de lecture",
      "other": "et {n} autres fichiers, dans l’ordre de lecture"
    },
    "n_arquivos_mp3": {
      "one": "{n} fichier MP3",
      "other": "{n} fichiers MP3"
    },
    "pct_restam": "{pct}% · reste {tempo}",
    "n_minutos": {
      "one": "{n} minute",
      "other": "{n} minutes"
    },
    "ir_para_tempo": "Aller à {tempo}",
    "nomear": "Nommer",
    "parte_n": "Partie {n}",
    "carregando_pagina_n": "Chargement de la page {n}...",
    "selecionar_pasta_e_continuar": "Choisir le dossier et continuer",
    "ler_agora": "Lire maintenant",
    "agrupamento_v": "Regroupement : {v}.",
    "tempo_restante": "reste {tempo}",
    "abrir_titulo": "Ouvrir {titulo}",
    "continuar_lendo_titulo": "Continuer la lecture de {titulo}",
    "continuar_ouvindo_titulo": "Continuer l’écoute de {titulo}",
    "continuar_assistindo_titulo": "Continuer à regarder {titulo}",
    "lido": "Lu",
    "pausado": "En pause",
    "status": "Statut",
    "favorito": "Favori",
    "escolher_local": "Choisir l’emplacement",
    "epub_baixado_como": "EPUB téléchargé sous le nom {nome}.",
    "ouvir_a_partir_de": "écouter à partir de {tempo}",
    "assistir_a_partir_de": "regarder à partir de {tempo}",
    "pagina_n_minuscula": "page {n}",
    "selecione_trecho_para_criar": "Sélectionnez un passage pendant la lecture pour créer {oque}.",
    "excluir_oque_pergunta": "Supprimer {oque} ?",
    "excluir_oque": "Supprimer {oque}",
    "excluir_item_pergunta": "Supprimer cet élément ?",
    "use_organizar_para_criar": "Utilisez « {botao} » sur un livre pour créer des {oque}.",
    "n_arquivos_processados": {
      "one": "{n} fichier traité",
      "other": "{n} fichiers traités"
    },
    "voce_ja_tem_titulo_de_autor": "Vous avez déjà « {titulo} » de {autor} dans la bibliothèque, même si le fichier est différent. L’importer quand même ?",
    "voce_ja_tem_titulo": "Vous avez déjà « {titulo} » dans la bibliothèque, même si le fichier est différent. L’importer quand même ?",
    "marcadores_unidade": {
      "one": "marque-page",
      "other": "marque-pages"
    },
    "ultimo_backup_em": "Dernière sauvegarde le <strong>{data}</strong>.",
    "guardar": "Enregistrer",
    "lembretes": "Rappels",
    "juntar": "Fusionner",
    "recomendado": "recommandé",
    "substituir": "Remplacer",
    "n_capas_recuperadas": {
      "one": "{n} couverture récupérée.",
      "other": "{n} couvertures récupérées."
    },
    "nao_encontramos_arquivos_tipo": "Aucun fichier {tipo} trouvé dans ce dossier.",
    "tentar_outra_pasta": "Essayer un autre dossier",
    "n_livros_encontrados": {
      "one": "{n} livre trouvé",
      "other": "{n} livres trouvés"
    },
    "n_de_total_selecionados": {
      "one": "{n} sur {total} sélectionné",
      "other": "{n} sur {total} sélectionnés"
    },
    "importar": "Importer",
    "importar_n": "Importer {n}",
    "aceite_frase": "J’ai lu et j’accepte la {politica} et les {termos} de Veredas Reader.",
    "pdf_preservado": "Le PDF original <strong>ne sera pas supprimé de votre propre dossier</strong>. Seule la copie de ce PDF sera retirée de la bibliothèque, une fois l’EPUB enregistré avec succès.",
    "gravar_epub_mesma_pasta": "Pour enregistrer l’EPUB <strong>dans le même dossier que le PDF</strong>, le navigateur a besoin de l’autorisation d’accéder à ce dossier.",
    "epub_pronto_qualquer_pasta": "L’EPUB est converti. Vous pouvez maintenant choisir <strong>n’importe quel dossier sur l’ordinateur</strong> pour enregistrer le fichier.",
    "backup_explicacao": "La sauvegarde originale est un fichier ZIP ou TXT. Lorsque vous la recevez sur un autre appareil, importez-la via <strong>Restaurer la sauvegarde</strong> : Veredas reconnaît le contenu et la restaure normalement. Le fichier contient votre progression, vos surlignages, vos citations, vos notes, vos marque-pages et l’organisation de votre étagère — <strong>pas les livres eux-mêmes</strong>, ni les couvertures.",
    "lembretes_desligados_frase": "Les rappels sont <strong>désactivés</strong>. Pensez à faire une sauvegarde de temps en temps.",
    "backup_salvo_nos_downloads": "<strong>Le fichier de sauvegarde a été enregistré sur cet appareil</strong>, dans vos téléchargements. Vous pouvez l’envoyer maintenant : ouvrez WhatsApp, votre messagerie, Drive ou l’application de votre choix, touchez Joindre et sélectionnez le fichier.",
    "arquivo_pronto_tamanho": "Fichier prêt — <strong>{tamanho}</strong>.",
    "scan_intro_frase": "L’application peut chercher des livres au format <strong>EPUB</strong> et <strong>MOBI</strong>, des bandes dessinées au format <strong>CBZ</strong> et <strong>CBR</strong> et des livres audio au format <strong>M4B</strong> dans un dossier de votre appareil, sous-dossiers compris.",
    "scan_intro_auto_frase": "Pour remplir rapidement votre étagère, l’application peut chercher des livres au format <strong>EPUB</strong> et <strong>MOBI</strong>, des bandes dessinées au format <strong>CBZ</strong> et <strong>CBR</strong> et des livres audio au format <strong>M4B</strong> dans un dossier de votre appareil, sous-dossiers compris.",
    "n_livros_aguardando": {
      "one": "<strong>{n} livre</strong> avec la progression et les marques conservées, en attente d’une nouvelle importation.",
      "other": "<strong>{n} livres</strong> avec la progression et les marques conservées, en attente d’une nouvelle importation."
    },
    "fora_da_busca_titulo": "Nous n’importons pas automatiquement les fichiers PDF, TXT, DOCX (Word), MD, MP3 et MP4",
    "fora_da_busca_texto": "Ces formats servent à toutes sortes de documents, pas seulement aux livres. Les laisser de côté permet de garder votre étagère bien rangée. <strong>Vous pouvez importer chacun d’eux manuellement avec le bouton +.</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "Votre bibliothèque locale",
    "biblioteca": "Bibliothèque",
    "organizacao": "Organisation",
    "minhas_marcacoes": "Mes marques",
    "sistema": "Système",
    "sua_biblioteca": "Votre bibliothèque",
    "toque_em_um_livro_para_comecar_a_ler": "Touchez un livre pour commencer la lecture.",
    "agrupar": "Regrouper",
    "sua_estante_nao_tem_copia_de_seguranca": "Votre étagère n’a pas de sauvegarde",
    "se_este_aparelho_se_perder_o_progresso": "S’il arrive quelque chose à cet appareil, votre progression et vos marques pourraient être perdues.",
    "agora_nao": "Pas maintenant",
    "nao_avisar_mais": "Ne plus me le rappeler",
    "carregando": "Chargement...",
    "estante": "Étagère",
    "lendo": "Lecture",
    "favoritos": "Favoris",
    "marcas": "Marques",
    "mais": "Plus",
    "neste_capitulo": "Ce chapitre",
    "velocidade": "Vitesse",
    "timer": "Minuteur",
    "marcar": "Marquer",
    "marcadores": "Marque-pages",
    "personalizar_leitura": "Préférences de lecture",
    "as_preferencias_ficam_salvas_para_as_p": "Vos préférences sont conservées pour les prochaines sessions de lecture.",
    "tema": "Thème",
    "claro": "Clair",
    "sepia": "Sépia",
    "escuro": "Sombre",
    "oceano": "Océan",
    "tipografia": "Police",
    "texto": "Texte",
    "tamanho": "Taille",
    "espacamento": "Interligne",
    "margens": "Marges",
    "cores_personalizadas_opcional": "Couleurs personnalisées (facultatif)",
    "fundo": "Arrière-plan",
    "fonte": "Couleur du texte",
    "brilho": "Luminosité",
    "orientacao": "Orientation",
    "auto": "Auto",
    "retrato": "Portrait",
    "paisagem": "Paysage",
    "modo_de_leitura": "Mode de lecture",
    "automatico": "Automatique",
    "horizontal": "Horizontal",
    "vertical": "Vertical",
    "automatico_usa_rolagem_horizontal_para": "Le mode automatique utilise la pagination horizontale pour EPUB, MOBI, TXT et MD, et le défilement vertical pour PDF et DOCX. Si vous le changez pendant la lecture, la modification ne s’applique qu’à ce livre.",
    "quadrinhos": "Bandes dessinées",
    "como_a_pagina_aparece": "Ajustement de la page",
    "pagina_inteira": "Page entière",
    "largura_da_tela": "Largeur de l’écran",
    "sentido_da_leitura": "Sens de lecture",
    "normal": "Normal →",
    "manga": "← Manga",
    "revista_aberta_na_horizontal": "Double page en mode paysage",
    "com_o_aparelho_deitado_mostra_duas_pag": "Tenez l’appareil à l’horizontale pour afficher deux pages côte à côte ; la couverture reste seule, comme dans une vraie bande dessinée.",
    "normal_vira_da_esquerda_para_a_direita": "Normal tourne de gauche à droite. Manga inverse tout : le geste de balayage, les touches sur les bords et l’ordre des deux pages en double page.",
    "gire_o_aparelho_para_a_horizontal_para": "Faites pivoter l’appareil à l’horizontale pour voir deux pages à la fois.",
    "dois_toques_ampliam_no_ponto_tocado_co": "Touchez deux fois pour zoomer à l’endroit touché ; une fois zoomé, faites glisser pour vous déplacer dans la page. Le pincement à deux doigts fonctionne aussi.",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "Le bouton de défilement en haut du lecteur permet d’alterner entre lecture page par page et défilement continu (style webtoon). En défilement continu, les pages se rejoignent et le zoom élargit la page : vous pouvez la parcourir en faisant défiler horizontalement.",
    "virada_de_pagina": "Changement de page",
    "folha_real": "Papier réel",
    "deslizar": "Glisser",
    "sem_animacao": "Aucune animation",
    "na_leitura_horizontal_arraste_a_pagina": "En lecture horizontale, faites glisser la page depuis son bord pour la plier avec le doigt. Relâchez à mi-chemin pour annuler le changement.",
    "ouvir_leitura": "Écouter",
    "continue_de_onde_parou_no_seu_ritmo": "Reprenez là où vous vous étiez arrêté, à votre rythme.",
    "livro": "Livre",
    "pronto_para_comecar": "Prêt à commencer",
    "voz": "Voix",
    "escolha_uma_voz_disponivel_no_disposit": "Choisissez une voix disponible sur cet appareil",
    "voz_padrao_do_sistema": "Voix système par défaut",
    "durante_a_reproducao": "Pendant la lecture",
    "a_leitura_avanca_pagina_a_pagina_os_co": "La lecture avance page par page. Les commandes du système apparaissent lorsque le navigateur les prend en charge.",
    "organizar_livro": "Organiser le livre",
    "estantes_colecoes_tags_e_status": "Étagères, collections, tags et statut.",
    "cancelar": "Annuler",
    "salvar": "Enregistrer",
    "grifos_citacoes_notas_e_marcadores_des": "Surlignages, citations, notes et marque-pages de ce livre.",
    "sumario": "Sommaire",
    "toque_em_um_capitulo_para_ir_direto_ao": "Touchez un chapitre pour y accéder directement.",
    "sua_anotacao": "Votre note",
    "edite_ou_adicione_comentarios_ao_seu_t": "Modifiez ou ajoutez des commentaires à votre passage.",
    "trecho": "Passage",
    "sua_nota": "Votre note",
    "salvar_nota": "Enregistrer la note",
    "agrupar_biblioteca": "Regrouper la bibliothèque",
    "escolha_como_os_livros_serao_organizad": "Choisissez comment les livres sont organisés sur l’étagère.",
    "ao_arrastar_um_livro_para_outra_posica": "Lorsque vous faites glisser un livre vers une autre position, l’étagère passe automatiquement à Mon ordre et conserve la séquence que vous avez créée.",
    "backup_e_restauracao": "Sauvegarde et restauration",
    "sua_estante_seu_progresso_e_suas_marca": "Votre étagère, votre progression et vos marques dans un seul fichier.",
    "escolha_uma_dimensao_para_explorar_sua": "Choisissez une façon d’explorer votre bibliothèque.",
    "capitulos": "Chapitres",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "La voix conserve sa hauteur. Cela s’applique à ce livre et aux suivants.",
    "ajuste_fino": "Réglage fin",
    "timer_de_sono": "Minuteur de sommeil",
    "o_audio_diminui_de_volume_aos_poucos_e": "L’audio baisse progressivement puis se met automatiquement en pause.",
    "pontos_que_voce_guardou_neste_audioliv": "Les passages que vous avez enregistrés dans ce livre audio.",
    "ajustes_do_audio": "Réglages audio",
    "as_preferencias_ficam_salvas_para_todo": "Ces préférences sont conservées pour tous les livres audio.",
    "botao_de_voltar": "Bouton de retour",
    "botao_de_avancar": "Bouton d’avance",
    "recuar_ao_retomar": "Revenir en arrière à la reprise",
    "depois_de_uma_pausa_longa_volta_alguns": "Après une longue pause, le lecteur revient de quelques secondes afin que vous puissiez reprendre le fil.",
    "tocar_ao_abrir": "Lire à l’ouverture",
    "ao_tocar_em_um_audiolivro_na_estante_a": "Toucher un livre audio sur l’étagère lance immédiatement la lecture.",
    "no_computador_espaco_toca_e_pausa_pula": "Sur ordinateur : espace lecture/pause · ← → avancer/reculer · Maj + ← → changer de chapitre · ↑ ↓ volume · B marque-page · [ ] vitesse.",
    "converter_pdf_para_epub": "Convertir un PDF en EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "Préparez le livre pour une lecture fluide et réglable.",
    "confirmacao": "Confirmer",
    "confirmar": "Confirmer",
    "processando": "Traitement",
    "documento": "Document",
    "buscar_livros_no_dispositivo": "Rechercher des livres sur cet appareil",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "Trouvez les fichiers EPUB, MOBI, CBZ, CBR et M4B déjà enregistrés sur votre appareil.",
    "juntar_em_um_unico_audiolivro": "Assembler en un seul livre audio ?",
    "titulo": "Titre",
    "autor": "Auteur",
    "importar_separados": "Importer séparément",
    "bem_vindo_ao_veredas_reader": "Bienvenue dans Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "Votre bibliothèque de lecture, entièrement sur votre propre appareil.",
    "buscar": "Rechercher",
    "importar_livro": "Importer un livre",
    "buscar_titulo_autor_tag": "Rechercher un titre, un auteur, un tag...",
    "fechar_busca": "Fermer la recherche",
    "navegacao_da_biblioteca": "Navigation de la bibliothèque",
    "fechar_menu": "Fermer le menu",
    "agrupar_livros": "Regrouper les livres",
    "voltar": "Retour",
    "marcar_pagina": "Marquer la page",
    "personalizar": "Préférences",
    "navegacao_principal": "Navigation principale",
    "acoes_do_trecho": "Actions sur le passage",
    "amarelo": "Jaune",
    "verde": "Vert",
    "rosa": "Rose",
    "azul": "Bleu",
    "player_de_audiolivro": "Lecteur de livres audio",
    "minimizar_player": "Réduire le lecteur",
    "minimizar": "Réduire",
    "video_em_reproducao": "Vidéo en cours de lecture",
    "abrir_a_lista_de_capitulos": "Ouvrir la liste des chapitres",
    "posicao_no_audio": "Position dans l’audio",
    "alternar_entre_o_progresso_do_capitulo": "Basculer entre la progression du chapitre et celle du livre entier",
    "capitulo_anterior": "Chapitre précédent",
    "voltar_15_segundos": "Revenir 15 secondes en arrière",
    "reproduzir": "Lire",
    "avancar_30_segundos": "Avancer de 30 secondes",
    "proximo_capitulo": "Chapitre suivant",
    "velocidade_de_reproducao": "Vitesse de lecture",
    "marcar_este_ponto": "Marquer cet emplacement",
    "ver_marcadores": "Voir les marque-pages",
    "silenciar": "Couper le son",
    "volume": "Volume",
    "audiolivro_em_reproducao": "Livre audio en cours de lecture",
    "abrir_o_player": "Ouvrir le lecteur",
    "fechar_o_player": "Fermer le lecteur",
    "fechar": "Fermer",
    "trecho_anterior": "Passage précédent",
    "iniciar_leitura": "Démarrer la lecture à voix haute",
    "proximo_trecho": "Passage suivant",
    "escreva_seu_comentario_interpretacao_o": "Écrivez votre commentaire, interprétation ou rappel...",
    "cancelar_importacao": "Annuler l’importation",
    "nome_do_audiolivro": "Nom du livre audio",
    "nome_do_autor": "Nom de l’auteur",
    "idioma": "Langue",
    "idioma_do_aplicativo": "Langue de l’application",
    "o_aplicativo_segue_o_idioma_do_apare": "L’application suit la langue de votre appareil. Si la vôtre n’existe pas encore ici, elle s’ouvrira en anglais.",
    "seguir_o_aparelho": "Suivre l’appareil",
    "fazer_backup": "Sauvegarder maintenant",
    "todos": "Tous",
    "lidos": "Terminés",
    "pausados": "En pause",
    "autores": "Auteurs",
    "tags": "Tags",
    "grifar": "Surligner",
    "anotar": "Note",
    "enviar": "Envoyer",
    "restaurar_padroes": "Restaurer les valeurs par défaut",
    "voltar_para_1": "Revenir à 1×",
    "marcar_agora": "Marquer maintenant",
    "escolher_pasta": "Choisir un dossier",
    "juntar_em_um_audiolivro": "Assembler en un livre audio",
    "sobre": "À propos",
    "licencas_de_codigo_aberto": "Licences open source",
    "configuracoes": "Paramètres",
    "temas_e_idioma": "Thèmes et langue"
  },
  "aviso": {
    "idioma_trocado": "Langue modifiée."
  },
  "guia": {
      "pular": "Passer",
      "voltar": "Retour",
      "proximo": "Suivant",
      "concluir": "J’ai compris",
      "secao": "Conseils d’utilisation",
      "rever_titulo": "Revoir les conseils",
      "rever_dica": "Les conseils apparaissent une fois, à l’endroit où chaque chose se passe. Ceci les fait tous revenir depuis le début.",
      "rever_botao": "Revoir",
      "voltaram": "Les conseils sont de retour.",
      "primeiro_t": "Commencez ici",
      "primeiro_p": "Touchez le + pour importer un livre depuis votre appareil. EPUB, PDF, MOBI, DOCX, TXT, bandes dessinées et livres audio sont acceptés.",
      "card_t": "Touchez pour lire, maintenez pour déplacer",
      "card_p": "Une touche ouvre le livre. Maintenez et faites glisser pour le placer où vous voulez sur l’étagère.",
      "agrupar_t": "Organisez à votre façon",
      "agrupar_p": "Regroupez l’étagère par auteur, série, collection ou étiquette — et revenez à la liste simple quand vous voulez.",
      "mais_t": "Le reste est ici",
      "mais_p": "La recherche sur l’appareil, la sauvegarde, les réglages et les politiques sont dans ce menu.",
      "pdf_epub_t": "Ce PDF vaut la conversion",
      "pdf_epub_p": "En EPUB le texte s’adapte à l’écran, vous changez la taille des caractères, et la lecture à voix haute est bien meilleure. Touchez ici pour convertir — le PDF d’origine reste sur l’étagère.",
      "virar_t": "Balayez pour tourner la page",
      "virar_p": "Faites glisser sur le côté, ou touchez près du bord droit et du bord gauche. Touchez au milieu pour afficher et masquer les commandes.",
      "rolar_t": "Faites défiler pour lire",
      "rolar_p": "Ce livre s’ouvre en défilement continu : balayez vers le haut pour continuer. Touchez au milieu pour afficher et masquer les commandes.",
      "voltar_t": "Retour à l’étagère",
      "voltar_p": "Ce bouton ferme le livre et vous ramène. L’endroit où vous vous êtes arrêté est enregistré tout seul.",
      "ouvir_t": "Écouter au lieu de lire",
      "ouvir_p": "L’application lit le livre à voix haute. Elle peut utiliser la voix de l’appareil ou télécharger une voix naturelle, bien plus humaine et qui fonctionne hors ligne.",
      "sentido_t": "Page par page ou en défilant",
      "sentido_p": "Changez le sens de lecture quand vous voulez. Le choix ne vaut que pour ce livre.",
      "personalizar_t": "À votre goût",
      "personalizar_p": "Le thème, la police, la taille du texte, les marges et la luminosité sont ici.",
      "pdf_sentido_t": "Le PDF s’ouvre en défilement",
      "pdf_sentido_p": "Les pages de PDF ont une taille fixe, il démarre donc en défilement continu. Ici vous passez au mode page par page.",
      "pdf_volte_t": "Si le texte paraît petit",
      "pdf_volte_p": "Pincez pour agrandir. Et souvenez-vous : converti en EPUB, le texte s’adapte tout seul à votre écran.",
      "hq_zoom_t": "Zoomez à deux doigts",
      "hq_zoom_p": "Pincez pour agrandir une case et faites glisser pour parcourir la page. Un double toucher revient à la taille normale.",
      "hq_ajustes_t": "Réglages de la BD",
      "hq_ajustes_p": "Choisissez comment la page tient dans l’écran, le sens de lecture, et si vous voulez deux pages côte à côte en tournant l’appareil.",
      "tema_t": "Choisissez le thème",
      "tema_p": "Clair, sépia ou sombre. Le sépia fatigue moins les yeux sur de longues lectures, et le sombre gêne moins la nuit.",
      "fonte_t": "Taille du texte",
      "fonte_p": "Faites glisser pour agrandir ou réduire. Juste en dessous : l’interligne et les marges.",
      "modo_t": "Sens de lecture",
      "modo_p": "Automatique utilise le défilement horizontal pour l’EPUB et vertical pour le PDF. Changé avec un livre ouvert, le réglage ne vaut que pour lui.",
      "audio_cap_t": "Passez d’un chapitre à l’autre",
      "audio_cap_p": "Touchez pour voir la liste des chapitres et aller directement à celui que vous voulez.",
      "audio_ajustes_t": "Vitesse et minuterie",
      "audio_ajustes_p": "Ici vous accélérez ou ralentissez la narration et programmez l’arrêt automatique après un moment.",
      "audio_min_t": "Continuez à naviguer",
      "audio_min_p": "Réduisez le lecteur et continuez d’écouter en parcourant l’étagère. Touchez la barre du bas pour revenir."
  },
  "vn": {
    "quem_le": "Voix de lecture",
    "natural": "Naturelle",
    "do_sistema": "Système",
    "nota_sistema": "Utilise les voix installées sur votre appareil. Pour une lecture plus humaine, choisissez Naturelle.",
    "nota_sistema_com_natural": "La voix naturelle reste téléchargée. Revenez à Naturelle quand vous le souhaitez.",
    "voz_do_sistema": "Voix du système",
    "lendo_com_a_voz_do_sistema": "Lecture avec la voix du système.",
    "voz_natural": "Voix naturelle",
    "gerada_no_aparelho": "Une voix bien plus humaine, générée directement sur votre appareil.",
    "progresso_download": "Progression du téléchargement",
    "x_de_y": "{x} sur {y}",
    "aviso_arquivo": "La voix naturelle nécessite d’ouvrir Veredas depuis l’adresse de l’application, et non comme un fichier sur votre ordinateur. En attendant, la lecture utilise la voix du système.",
    "aviso_navegador": "Ce navigateur ne dispose pas des fonctions nécessaires à la voix naturelle. La lecture continue avec la voix du système.",
    "verificando": "Vérification de la voix naturelle…",
    "fato_download": "Téléchargement unique de {tamanho}. Ensuite, elle fonctionne hors ligne.",
    "fato_wifi": "Le Wi-Fi est conseillé. Vous pouvez mettre en pause et reprendre plus tard.",
    "fato_privacidade": "Le texte du livre ne quitte jamais votre appareil.",
    "fato_idiomas": "Parle 31 langues, dont le français, l’anglais et le portugais. Les autres langues continuent avec la voix du système.",
    "baixar_voz_natural": "Télécharger la voix naturelle ({tamanho})",
    "licenca_curta": "Modèle Supertonic 3 de Supertone, sous licence OpenRAIL-M. Détails dans À propos > Licences open source.",
    "pode_continuar_usando": "Vous pouvez continuer à lire pendant le téléchargement. Si la connexion est coupée, il reprendra là où il s’est arrêté.",
    "pausar_download": "Mettre en pause",
    "erro_espaco": "Espace insuffisant sur l’appareil pour terminer le téléchargement. Libérez de l’espace et réessayez.",
    "erro_offline": "Pas de connexion Internet pour le moment. Ce qui a déjà été téléchargé est conservé.",
    "erro_rede": "La connexion a été coupée pendant le téléchargement. Ce qui a déjà été téléchargé est conservé.",
    "download_pausado": "Téléchargement en pause. Ce qui a déjà été téléchargé est conservé.",
    "continuar_download": "Reprendre",
    "descartar": "Abandonner",
    "voz_feminina": "Féminine",
    "voz_feminina_desc": "Douce et calme",
    "voz_masculina": "Masculine",
    "voz_masculina_desc": "Chaleureuse et sereine",
    "parar_amostra": "Arrêter l’extrait",
    "ouvir_amostra_de": "Écouter un extrait : {voz}",
    "escolha_a_voz": "Choisissez la voix",
    "qualidade": "Qualité",
    "q_auto": "Automatique",
    "q_rapida": "Rapide",
    "q_maxima": "Maximale",
    "q_auto_desc": "S’adapte aux performances de votre appareil pour une lecture sans pauses.",
    "q_rapida_desc": "Génère la voix plus vite. Idéal pour les appareils plus modestes.",
    "q_maxima_desc": "Le son le plus soigné. Sur les appareils modestes, des pauses peuvent survenir entre les phrases.",
    "ocupa": "Occupe {tamanho} sur cet appareil",
    "remover": "Supprimer",
    "baixar_pelos_dados": "Télécharger avec les données mobiles ?",
    "baixar_pelos_dados_msg": "Votre appareil ne semble pas connecté au Wi-Fi. Le téléchargement fait {tamanho} et peut entamer votre forfait de données.",
    "baixar_agora": "Télécharger quand même",
    "pronta": "La voix naturelle est prête.",
    "download_interrompido": "Le téléchargement s’est arrêté. Touchez Reprendre quand vous le souhaitez.",
    "remover_titulo": "Supprimer la voix naturelle ?",
    "descartar_titulo": "Abandonner le téléchargement ?",
    "remover_msg": "Cela libère {tamanho}. La lecture repasse à la voix du système, et vous pourrez la télécharger de nouveau à tout moment.",
    "descartar_msg": "Ce qui a déjà été téléchargé sera effacé.",
    "removida": "Voix naturelle supprimée de cet appareil.",
    "amostra_falhou": "Impossible de lire l’extrait sur cet appareil.",
    "amostra": "Bonjour ! Voici comment vos livres sonneront avec la voix naturelle.",
    "pode_demorar_um_minuto": "Cela peut prendre une minute.",
    "gerando_voz": "Préparation de la voix…",
    "automatico_idioma": "Automatique ({idioma})",
    "automatico": "Automatique",
    "so_voz_do_sistema": "voix du système",
    "aviso_idioma": "Langue du texte : {idioma}. La voix naturelle ne parle pas encore cette langue ; le livre sera donc lu par la voix du système.",
    "aviso_idioma_desconhecido": "Impossible de reconnaître la langue de ce texte. Choisissez la langue ci-dessous pour utiliser la voix naturelle.",
    "aviso_falha": "La voix naturelle n’a pas pu fonctionner sur cet appareil pour le moment. La lecture continue avec la voix du système.",
    "nao_carregou_usando_sistema": "La voix naturelle ne s’est pas chargée sur cet appareil. Lecture avec la voix du système.",
    "parou_usando_sistema": "La voix naturelle s’est arrêtée. La lecture continue avec la voix du système.",
    "aparelho_lento": "Cet appareil génère la voix lentement. Choisissez la qualité Rapide pour éviter les pauses.",
    "idioma_do_texto": "Langue du texte",
    "idioma_do_texto_dica": "Détectée à partir du texte. Changez-la si la prononciation semble incorrecte.",
    "leitura_em_voz_alta": "Lecture à voix haute",
    "lento_usando_sistema": "La voix naturelle est trop lente sur cet appareil. La lecture continue avec la voix du système.",
    "aviso_lento": "Cet appareil n’arrive pas à générer la voix naturelle au rythme de la lecture : la voix du système prend le relais pour l’instant.",
    "sem_memoria_usando_sistema": "La voix naturelle n’a pas tenu dans la mémoire de cet appareil. Lecture avec la voix du système.",
    "aviso_falha_memoria": "Il n’y avait pas assez de mémoire pour la voix naturelle sur cet appareil. Fermer d’autres applications et réessayer suffit souvent ; en attendant, la lecture utilise la voix du système.",
    "copiar_detalhe": "Copier le détail",
    "copiado": "Détail copié.",
    "falhou_titulo": "La voix naturelle ne s’est pas chargée sur cet appareil.",
    "falhou_texto": "L’appareil n’a pas réussi à préparer la voix naturelle. La lecture continue avec la voix du système. Pour aider à résoudre le problème, copiez le détail ci-dessous et envoyez-le au support.",
    "falhou_memoria_texto": "Il a manqué de la mémoire pour la voix naturelle sur cet appareil. Fermer d’autres applications et réessayer suffit souvent.",
    "tentar_de_novo": "Réessayer",
    "tentando": "Chargement…",
    "sondando": "Test de la mémoire de cet appareil…",
    "sonda_explica": "Le test réserve quelques secondes la mémoire dont la voix naturelle aura besoin, puis la rend aussitôt. Vous le savez donc maintenant, et non après le téléchargement.",
    "so_aparelhos_compativeis": "Fonctionne uniquement sur les appareils compatibles. Le fonctionnement n’est pas garanti sur tous les modèles de téléphone et de tablette.",
    "aviso_aparelho_justo": "Cet appareil a peu de mémoire pour la voix naturelle. Elle risque de ne pas se charger ; dans ce cas, il suffit de la supprimer pour récupérer l’espace.",
    "preparando_demora": "Préparation de la voix. Cela peut prendre quelques minutes.",
    "incompativel_titulo": "La voix naturelle ne fonctionne pas sur cet appareil.",
    "incompativel_memoria": "Il n’y avait pas assez de mémoire pour la préparer. La lecture reste avec la voix du système, dont les options sont ci-dessous. Si vous voulez, fermez d’autres applications et touchez Réessayer.",
    "incompativel_lento": "Elle était trop lente pour suivre la lecture. La lecture reste avec la voix du système, dont les options sont ci-dessous.",
    "incompativel_queda": "L’application s’est fermée pendant le chargement. La lecture reste avec la voix du système, dont les options sont ci-dessous.",
    "incompativel_falha": "Elle n’a pas pu se charger ici. La lecture reste avec la voix du système, dont les options sont ci-dessous.",
    "testar_de_novo": "Réessayer le test",
    "remover_e_liberar": "Supprimer et libérer {tamanho}",
    "tela_durante_a_leitura": "Écran pendant la lecture",
    "manter_tela_ligada": "Garder l’écran allumé",
    "manter_tela_ligada_dica": "Tant qu’un livre est ouvert, l’écran ne s’éteint pas tout seul. À la fermeture du livre, tout revient à la normale."
  }
});
