/* ============================================================
   HINDI — hi.js
   Tradução de Veredas Reader. Chaves em português são
   imutáveis (ver idioma.js). Fallback: en.js.
   ============================================================ */
Idiomas.registrar('hi', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "बुकमार्क हटा दिया गया।",
    "excluir_marcador": "बुकमार्क हटाएँ",
    "o_marcador_sera_removido_permanentemen": "बुकमार्क हमेशा के लिए हटा दिया जाएगा।",
    "excluir_marcador_2": "बुकमार्क हटाएँ?",
    "pagina_salva": "पृष्ठ सहेजा गया",
    "anotacoes": "नोट्स",
    "citacoes": "उद्धरण",
    "item_excluido": "आइटम हटा दिया गया।",
    "este_registro_sera_removido_permanente": "यह प्रविष्टि लाइब्रेरी से हमेशा के लिए हटा दी जाएगी।",
    "configuracoes_padrao_restauradas": "डिफ़ॉल्ट सेटिंग्स बहाल की गईं।",
    "leitura_da_esquerda_para_a_direita": "बाएँ से दाएँ पढ़ना।",
    "leitura_da_direita_para_a_esquerda_man": "दाएँ से बाएँ पढ़ना (मांगा)।",
    "a_pagina_inteira_passa_a_caber_na_tela": "अब पूरा पृष्ठ स्क्रीन पर फ़िट होता है।",
    "a_pagina_passa_a_ocupar_toda_a_largura": "अब पृष्ठ स्क्रीन की पूरी चौड़ाई लेता है।",
    "virada_sem_animacao_ativada": "अब बिना एनिमेशन के पृष्ठ पलटता है।",
    "virada_deslizante_ativada": "स्लाइडिंग पृष्ठ पलटाव चालू है।",
    "virada_em_folha_real_ativada": "असली कागज़ जैसा पृष्ठ पलटाव चालू है।",
    "padrao_automatico_cada_formato_abre_no": "स्वचालित: हर प्रारूप अपने अनुकूल तरीके से खुलता है।",
    "mudando_durante_a_leitura_o_ajuste_fic": "पढ़ते समय बदलने पर, बदलाव केवल उसी पुस्तक के लिए सहेजा जाता है।",
    "automatico_usa_rolagem_horizontal_para": "स्वचालित EPUB, MOBI, TXT, MD और कॉमिक्स के लिए क्षैतिज पृष्ठ बदलाव तथा PDF और DOCX के लिए लंबवत स्क्रॉल का उपयोग करता है।",
    "este_livro": "यह पुस्तक",
    "armazenamento_local_indisponivel_neste": "इस ब्राउज़र में स्थानीय संग्रहण उपलब्ध नहीं है।",
    "o_aplicativo_pode_procurar_os_livros_q": "ऐप आपके डिवाइस पर पहले से मौजूद पुस्तकों को खोज सकता है।",
    "vamos_montar_sua_estante": "क्या हम आपकी शेल्फ सजाएँ?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "आपकी सहमति के बिना ऐप का उपयोग नहीं किया जा सकता।",
    "precisamos_do_seu_aceite": "हमें आपकी सहमति चाहिए",
    "antes_de_comecar_leia_e_aceite_os_docu": "शुरू करने से पहले नीचे दिए दस्तावेज़ पढ़ें और स्वीकार करें।",
    "selecionar_todos": "सभी चुनें",
    "limpar_selecao": "चयन हटाएँ",
    "todos_parecem_ja_estar_na_sua_estante": "ये सभी पहले से आपकी शेल्फ पर लगते हैं।",
    "lendo_a_pasta_escolhida": "आपके चुने फ़ोल्डर को पढ़ रहे हैं…",
    "procurando_livros": "पुस्तकें खोज रहे हैं",
    "nao_foi_possivel_concluir_a_busca_no_d": "इस डिवाइस पर खोज पूरी नहीं हो सकी।",
    "tente_outra_pasta_do_aparelho": "डिवाइस का कोई दूसरा फ़ोल्डर आज़माएँ।",
    "nenhum_livro_encontrado": "कोई पुस्तक नहीं मिली",
    "use_o_botao_para_escolher_os_arquivos": "फ़ाइलें हाथ से चुनने के लिए + बटन का उपयोग करें। Android फ़ोन पर Chrome आमतौर पर पूरा फ़ोल्डर चुनने देता है।",
    "seu_navegador_nao_permite_ler_pastas": "आपका ब्राउज़र फ़ोल्डर नहीं पढ़ सकता",
    "busca_automatica_indisponivel": "स्वचालित खोज अनुपलब्ध",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR और M4B",
    "termos_de_uso": "उपयोग की शर्तें",
    "politica_de_privacidade": "गोपनीयता नीति",
    "um_minuto_agora_evita_perder_o_progres": "एक मिनट अभी बाद में प्रगति और निशान खोने से बचाता है।",
    "ver_estante": "शेल्फ देखें",
    "modo_juntar": "मिलान मोड",
    "modo_substituir": "बदलने का मोड",
    "restauracao_concluida": "पुनर्स्थापन पूरा हुआ",
    "tente_de_novo_com_o_arquivo_original": "मूल फ़ाइल के साथ फिर प्रयास करें।",
    "a_restauracao_nao_pode_ser_concluida": "पुनर्स्थापन पूरा नहीं हो सका",
    "devolvendo_o_seu_progresso_e_as_suas_m": "आपकी प्रगति और निशान वापस ला रहे हैं...",
    "restaurar_este_backup": "यह बैकअप पुनर्स्थापित करें?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Veredas द्वारा सहेजी गई .zip या साझा की गई .txt चुनें।",
    "nao_foi_possivel_ler_este_arquivo": "यह फ़ाइल पढ़ी नहीं जा सकी",
    "lendo_o_backup": "बैकअप पढ़ रहे हैं",
    "backup_do_veredas_reader": "Veredas Reader बैकअप",
    "arquivo_de_transporte_txt_contendo_os": "बैकअप की .txt प्रति, जिसमें ZIP जैसी ही सामग्री है",
    "nao_foi_possivel_montar_o_arquivo_de_b": "बैकअप फ़ाइल बनाई नहीं जा सकी।",
    "escolher_o_app": "ऐप चुनें",
    "vale_conferir_o_que_vai_no_arquivo": "फ़ाइल में क्या जाता है, यह देख लेना अच्छा है",
    "enviar_para_outro_app": "दूसरे ऐप पर भेजें",
    "salvar_o_arquivo": "फ़ाइल सहेजें",
    "o_navegador_aqui_nao_oferece_o_compart": "यह ब्राउज़र सीधा साझा करना नहीं देता। फ़ाइल सहेजें और बाद में किसी भी ऐप से भेजें।",
    "este_aparelho_nao_abre_a_lista_de_apli": "यह डिवाइस ऐप सूची नहीं खोलता",
    "importe_pelo_menos_um_livro_antes_de_f": "बैकअप बनाने से पहले कम से कम एक पुस्तक आयात करें।",
    "estante_vazia": "खाली शेल्फ",
    "nao_deu_para_copiar": "कॉपी नहीं हो सका",
    "copiar_detalhes": "विवरण कॉपी करें",
    "o_backup_foi_salvo_assim_mesmo": "बैकअप फिर भी सहेजा गया",
    "o_aparelho_recusou_abrir_a_lista": "साझा करने की सूची नहीं खोली जा सकी",
    "sem_detalhes_do_navegador": "ब्राउज़र से कोई विवरण नहीं",
    "o_sistema_nao_aceitou_receber_o_arquiv": "डिवाइस का सिस्टम फ़ाइल प्राप्त नहीं कर सका।",
    "o_navegador_considerou_a_situacao_inse": "ब्राउज़र ने अपने ही एक सुरक्षा नियम के कारण साझा करना रोक दिया। फ़ाइल सहेजें और अपनी पसंद के किसी भी ऐप से भेजें।",
    "o_compartilhamento_so_funciona_em_ende": "साझा करना केवल सुरक्षित पते पर काम करता है। यह ऐप सादे http:// पते से खुल रहा है, और ऐसी स्थिति में ब्राउज़र दूसरे ऐप पर भेजना रोक देता है।",
    "este_navegador_nao_conseguiu_iniciar_o": "यह ब्राउज़र साझा करना शुरू नहीं कर सका। फ़ाइल सहेजें और अपनी पसंद के किसी भी ऐप से भेजें।",
    "o_navegador_recebeu_um_arquivo_em_form": "ब्राउज़र ने साझा करने के लिए ऐप्स की सूची नहीं खोली। बटन फिर से टैप करें, या फ़ाइल सहेजें और अपनी पसंद के किसी भी ऐप से भेजें।",
    "nao_foi_possivel_gerar_o_backup": "बैकअप नहीं बनाया जा सका।",
    "reunindo_a_sua_estante": "आपकी शेल्फ इकट्ठा कर रहे हैं...",
    "preparando_o_backup": "बैकअप तैयार कर रहे हैं",
    "pronto_nada_mais_esta_esperando": "हो गया — अब कुछ इंतज़ार नहीं कर रहा।",
    "o_progresso_e_as_marcacoes_desses_livr": "इन पुस्तकों की प्रगति और निशान मिटा दिए जाएंगे। बाद में फ़ाइलें आयात करने पर वे खाली लौटेंगी।",
    "descartar_o_que_esta_esperando": "प्रतीक्षा में रखा डेटा हटाएँ?",
    "lembretes_de_backup_religados": "बैकअप रिमाइंडर फिर से चालू।",
    "sem_titulo": "बिना शीर्षक",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "रिमाइंडर बंद।",
    "manter_ligado": "चालू रखें",
    "desligar_assim_mesmo": "फिर भी बंद करें",
    "o_botao_de_salvar_continua_onde_sempre": "सहेजने का बटन वहीं है जहाँ हमेशा था, बैकअप और पुनर्स्थापन में।",
    "o_lembrete_e_o_unico_aviso_que_existe": "रिमाइंडर ही एकमात्र चेतावनी है। इसके बिना, बैकअप लेना आपको स्वयं याद रखना होगा।\n\n",
    "limpar_os_dados_do_navegador_desinstal": "यदि ब्राउज़र डेटा साफ़ हो जाए, ऐप हटा दिया जाए, फ़ोन बदला जाए या डिवाइस खराब हो जाए, तो प्रगति, हाइलाइट, उद्धरण, नोट्स और बुकमार्क वापस नहीं पाए जा सकेंगे।\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "आपकी शेल्फ केवल इसी डिवाइस पर है। किसी सर्वर पर प्रति नहीं है, इसलिए आपके लिए इसे पुनर्प्राप्त करने का कोई तरीका नहीं है।\n\n",
    "leia_antes_de_confirmar": "पुष्टि से पहले पढ़ें",
    "desligar_os_lembretes_de_backup": "बैकअप रिमाइंडर बंद करें?",
    "progresso_de_leitura_restaurado_neste": "इस पुस्तक के लिए पठन प्रगति बहाल की गई।",
    "pronto": "हो गया।",
    "aplicando_as_suas_preferencias": "आपकी प्राथमिकताएँ लागू कर रहे हैं...",
    "atualize_o_veredas_reader_e_tente_de_n": "Veredas Reader अपडेट करें और फिर प्रयास करें।",
    "este_backup_foi_feito_numa_versao_mais": "यह बैकअप ऐप के नए संस्करण से बनाया गया था।",
    "este_arquivo_nao_e_um_backup_de_biblio": "यह फ़ाइल Veredas लाइब्रेरी बैकअप नहीं है।",
    "o_conteudo_interno_nao_pode_ser_lido": "भीतर की सामग्री पढ़ी नहीं जा सकी।",
    "o_backup_esta_corrompido": "बैकअप खराब है।",
    "falta_o_arquivo_biblioteca_json_la_den": "उसमें biblioteca.json फ़ाइल नहीं है।",
    "este_arquivo_nao_parece_ser_um_backup": "यह फ़ाइल Veredas बैकअप जैसी नहीं लगती।",
    "compactando": "संपीड़ित कर रहे हैं...",
    "para_restaurar_menu_lateral_backup_e_r": "पुनर्स्थापित करने के लिए: साइड मेन्यू > बैकअप और पुनर्स्थापन > बैकअप पुनर्स्थापित करें।",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas निशान और आपके रुकने का स्थान स्वचालित रूप से पुनर्स्थापित कर देता है।",
    "importe_os_livros_normalmente_no_aplic": "पुस्तकें सामान्य रूप से ऐप में आयात करें: हर फ़ाइल को पहचानते ही,",
    "ele_nao_contem_os_arquivos_dos_livros": "इसमें पुस्तकों की फ़ाइलें नहीं हैं। पूर्ण पुनर्स्थापन के लिए,",
    "as_notas_os_marcadores_e_a_organizacao": "आपके नोट्स, बुकमार्क और आपकी शेल्फ का संगठन।",
    "este_arquivo_guarda_o_seu_progresso_de": "यह फ़ाइल आपकी पठन प्रगति, हाइलाइट, उद्धरण,",
    "verificando_se_sao_partes_do_mesmo_aud": "देख रहे हैं कि ये एक ही ऑडियोबुक के भाग हैं...",
    "analisando_os_arquivos": "फ़ाइलें पढ़ रहे हैं",
    "nao_foi_possivel_salvar_o_audiolivro": "ऑडियोबुक सहेजी नहीं जा सकी।",
    "audiolivros_grandes_podem_levar_alguns": "बड़ी ऑडियोबुक में कुछ क्षण लग सकते हैं...",
    "salvando_na_sua_estante": "आपकी शेल्फ पर सहेज रहे हैं",
    "falha_ao_processar_os_arquivos": "फ़ाइलें संसाधित नहीं हो सकीं।",
    "falha_ao_processar_o_arquivo": "फ़ाइल संसाधित नहीं हो सकी।",
    "nao_foi_possivel_salvar_o_quadrinho": "कॉमिक सहेजी नहीं जा सकी।",
    "quase_la": "लगभग हो गया...",
    "falha_ao_processar_o_quadrinho": "कॉमिक संसाधित नहीं हो सकी।",
    "autor_desconhecido": "अज्ञात लेखक",
    "lendo_o_quadrinho": "कॉमिक पढ़ रहे हैं...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "पुस्तक लाइब्रेरी में सहेजी नहीं जा सकी।",
    "nao_foi_possivel_ler_o_pdf": "PDF पढ़ी नहीं जा सकी।",
    "lendo_o_pdf": "PDF पढ़ रहे हैं...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "यदि पुरानी .doc है, तो Word में खोलें और .docx के रूप में सहेजें, फिर आयात करें।",
    "este_arquivo_nao_e_um_docx_valido": "यह फ़ाइल मान्य .docx नहीं है।",
    "livros_com_protecao_da_amazon_nao_pode": "Amazon सुरक्षा वाली पुस्तकें यहाँ नहीं खोली जा सकतीं। DRM-मुक्त प्रति उपयोग करें या पुस्तक को EPUB में बदलें।",
    "este_arquivo_esta_protegido_por_drm": "यह फ़ाइल DRM से सुरक्षित है।",
    "confira_se_a_extensao_corresponde_ao_c": "जाँचें कि एक्सटेंशन सामग्री से मेल खाती है, या पुस्तक को EPUB में बदलें।",
    "este_arquivo_nao_e_um_mobi_valido": "यह फ़ाइल मान्य MOBI नहीं है।",
    "nao_foi_possivel_ler_o_arquivo": "फ़ाइल पढ़ी नहीं जा सकी।",
    "formato_nao_suportado": "प्रारूप समर्थित नहीं।",
    "falha_ao_salvar_o_livro_na_biblioteca": "पुस्तक लाइब्रेरी में सहेजी नहीं जा सकी।",
    "livro_importado_e_salvo_no_dispositivo": "पुस्तक आयात और इस डिवाइस पर सहेजी गई।",
    "audiolivro_importado_e_salvo_no_dispos": "ऑडियोबुक आयात और इस डिवाइस पर सहेजी गई।",
    "quadrinho_importado_e_salvo_no_disposi": "कॉमिक आयात और इस डिवाइस पर सहेजी गई।",
    "salvando_na_sua_estante_2": "आपकी शेल्फ पर सहेज रहे हैं...",
    "importando_livro": "पुस्तक आयात कर रहे हैं",
    "importar_mesmo_assim": "फिर भी आयात करें",
    "parece_que_este_livro_ja_esta_na_estan": "लगता है यह पुस्तक पहले से आपकी शेल्फ पर है",
    "este_livro_ja_esta_na_estante": "यह पुस्तक पहले से शेल्फ पर है",
    "video_importado_e_salvo_no_dispositivo": "वीडियो आयात और इस डिवाइस पर सहेजा गया।",
    "importacao_cancelada": "आयात रद्द किया गया।",
    "preparando_o_arquivo": "फ़ाइल तैयार कर रहे हैं",
    "importando_audiolivro": "ऑडियोबुक आयात कर रहे हैं",
    "importacao_concluida": "आयात पूरा हुआ",
    "importacao_interrompida": "आयात रोका गया",
    "a_importacao_foi_interrompida_o_que_ja": "आयात रोका गया; जो आ चुका था वह आपकी शेल्फ पर रहेगा।",
    "finalizando": "समाप्त कर रहे हैं…",
    "nao_foi_possivel_ler_o_arquivo_2": "फ़ाइल पढ़ी नहीं जा सकी",
    "importando_livros": "पुस्तकें आयात कर रहे हैं",
    "livros_quadrinhos_documentos_audiolivr": "पुस्तकें, कॉमिक्स, दस्तावेज़, ऑडियोबुक और वीडियो",
    "series": "श्रृंखलाएँ",
    "colecoes": "संग्रह",
    "organizacao_salva": "संगठन सहेजा गया।",
    "informe_um_nome_para_o_livro_antes_de": "सहेजने से पहले पुस्तक को नाम दें।",
    "nome_do_livro_obrigatorio": "पुस्तक का नाम आवश्यक है",
    "importe_um_livro_primeiro": "पहले एक पुस्तक आयात करें।",
    "citacao": "उद्धरण",
    "anotacao": "नोट",
    "citacao_2": "उद्धरण",
    "anotacao_2": "नोट",
    "uma_citacao": "एक उद्धरण",
    "uma_anotacao": "एक नोट",
    "o_marcador_sera_removido_da_biblioteca": "बुकमार्क लाइब्रेरी से हटा दिया जाएगा, पर पुस्तक की फ़ाइल अछूती रहेगी।",
    "marcador_de_audio": "ऑडियो बुकमार्क",
    "marcador_de_video": "वीडियो बुकमार्क",
    "nao_foi_possivel_excluir_o_livro": "पुस्तक हटाई नहीं जा सकी।",
    "livro_excluido_da_biblioteca": "पुस्तक लाइब्रेरी से हटा दी गई।",
    "excluir_livro": "पुस्तक हटाएँ",
    "isso_remove_apenas_a_copia_armazenada": "यह केवल लाइब्रेरी की प्रति, प्रगति, बुकमार्क और नोट्स हटाता है। आपके फ़ोल्डर की मूल फ़ाइल नहीं हटेगी।",
    "excluir_livro_2": "पुस्तक हटाएँ?",
    "ordem_personalizada_salva": "कस्टम क्रम सहेजा गया।",
    "ordem_manual_da_sua_estante": "आपकी शेल्फ, आपके क्रम में।",
    "agrupamento_alterado_para_minha_ordem": "समूहन मेरे क्रम पर बदल गया।",
    "nova_ordem_salva": "नया क्रम सहेजा गया।",
    "nao_foi_possivel_salvar_a_nova_ordem": "नया क्रम सहेजा नहीं जा सका।",
    "baixar_automaticamente": "स्वतः डाउनलोड करें",
    "escolha_livremente_onde_o_arquivo_sera": "फ़ाइल कहाँ लिखी जाए, स्वतंत्र रूप से चुनें।",
    "salvar_epub": "EPUB सहेजें",
    "livro_epub": "EPUB पुस्तक",
    "erro_desconhecido": "अज्ञात त्रुटि",
    "a_permissao_para_salvar_o_arquivo_foi": "फ़ाइल सहेजने की अनुमति रद्द कर दी गई। लाइब्रेरी में कुछ नहीं बदला।",
    "conversao_cancelada_o_pdf_original_per": "रूपांतरण रद्द। मूल PDF लाइब्रेरी में रहेगी।",
    "preparando_salvamento": "सहेजने की तैयारी…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "PDF की प्रति लाइब्रेरी में उपलब्ध नहीं है।",
    "reconstruindo_o_livro_localmente": "पुस्तक आपके डिवाइस पर फिर से बना रहे हैं।",
    "convertendo_pdf": "PDF बदल रहे हैं",
    "nao_foi_possivel_compartilhar_o_livro": "पुस्तक साझा नहीं की जा सकी।",
    "o_arquivo_foi_preparado_para_voce_comp": "फ़ाइल दूसरे ऐप में साझा करने के लिए तैयार है।",
    "livro_compartilhado": "पुस्तक साझा की गई।",
    "a_copia_deste_livro_nao_esta_disponive": "इस पुस्तक की प्रति लाइब्रेरी में उपलब्ध नहीं है।",
    "para_manter_a_politica_de_compartilham": "लाइब्रेरी की साझा नीति बनाए रखने के लिए, EPUB और MOBI फ़ाइलें इस ऐप से साझा नहीं की जा सकतीं।",
    "quadrinhos_ficam_guardados_somente_no": "कॉमिक्स केवल आपके डिवाइस पर रखी जाती हैं और इस ऐप से साझा नहीं की जा सकतीं।",
    "audiolivros_e_videos_ficam_guardados_s": "ऑडियोबुक और वीडियो केवल आपके डिवाइस पर रखे जाते हैं और इस ऐप से साझा नहीं किए जा सकते।",
    "formato_protegido": "सुरक्षित प्रारूप",
    "compartilhamento_indisponivel": "साझा करना अनुपलब्ध",
    "concluido": "पूरा हुआ",
    "ainda_nao_comecado": "अभी शुरू नहीं हुआ",
    "continue_lendo": "पढ़ना जारी रखें",
    "continue_ouvindo": "सुनना जारी रखें",
    "continue_assistindo": "देखना जारी रखें",
    "comece_por_aqui": "यहाँ से शुरू करें",
    "comece_a_ouvir": "सुनना शुरू करें",
    "comece_a_assistir": "देखना शुरू करें",
    "no_total": "कुल",
    "para_ler": "पढ़ने के लिए",
    "sua_estante": "आपकी शेल्फ",
    "livros_organizados_pela_opcao_selecion": "चुने विकल्प के अनुसार व्यवस्थित पुस्तकें।",
    "uma_prateleira_para_cada_tipo_de_arqui": "हर प्रकार की फ़ाइल के लिए एक शेल्फ।",
    "autores_agrupados_em_ordem_alfabetica": "लेखक वर्णानुक्रम में समूहित।",
    "toque_para_continuar_de_onde_parou": "जहाँ छोड़ा था वहीं से जारी रखने के लिए टैप करें।",
    "para_ler_2": "पढ़ने के लिए",
    "lendo_agora": "अभी पढ़ रहे हैं",
    "audio_e_video": "ऑडियो और वीडियो",
    "trechos_salvos_separadamente_dos_marca": "बुकमार्क से अलग सहेजे गए अंश।",
    "comentarios_vinculados_a_trechos_selec": "चुने अंशों से जुड़ी टिप्पणियाँ।",
    "paginas_salvas_para_voltar_rapidamente": "जल्दी लौटने के लिए सहेजे गए पृष्ठ।",
    "do_maior_para_o_menor_progresso_de_lei": "पठन प्रगति के अधिक से कम क्रम में।",
    "livros_adicionados_ou_lidos_mais_recen": "सबसे हाल में जोड़ी या पढ़ी पुस्तकें।",
    "ordem_alfabetica_pelo_titulo": "शीर्षक से वर्णानुक्रम।",
    "separa_em_prateleiras_de_epub_pdf_docx": "EPUB, PDF, DOCX, ऑडियोबुक, वीडियो… की शेल्फ में बाँटता है।",
    "tipo_de_arquivo": "फ़ाइल प्रकार",
    "organiza_e_separa_os_livros_por_autor": "पुस्तकों को लेखक के अनुसार व्यवस्थित और अलग करता है।",
    "agrupar_por_autor": "लेखक से समूहित करें",
    "pressione_o_livro_e_mova_o": "पुस्तक दबाकर पकड़ें और हिलाएँ।",
    "minha_ordem": "मेरा क्रम",
    "epub_pronto": "EPUB तैयार",
    "conversao_concluida": "रूपांतरण पूरा",
    "necessario_para_salvar_o_epub_ao_lado": "मूल के पास EPUB सहेजने के लिए आवश्यक",
    "escolha_a_pasta_do_pdf": "PDF का फ़ोल्डर चुनें",
    "processando": "काम चल रहा है…",
    "processamento_local_no_navegador": "आपके डिवाइस पर, ब्राउज़र में संसाधित",
    "convertendo_livro": "पुस्तक बदल रहे हैं",
    "livro_em_pdf": "PDF पुस्तक",
    "recalculando_paginas": "पृष्ठ फिर से गिन रहे हैं...",
    "ajustando_leitura": "लेआउट समायोजित कर रहे हैं",
    "abrir_comentario": "टिप्पणी खोलें",
    "anotacao_salva": "नोट सहेजा गया।",
    "anotacao_atualizada": "नोट अपडेट किया गया।",
    "escreva_uma_nota_antes_de_salvar": "सहेजने से पहले नोट लिखें।",
    "nao_foi_possivel_compartilhar": "साझा नहीं किया जा सका।",
    "compartilhamento_indisponivel_2": "साझा करना अनुपलब्ध।",
    "trecho_copiado": "अंश कॉपी किया गया।",
    "trecho_compartilhado": "अंश साझा किया गया।",
    "citacao_salva": "उद्धरण सहेजा गया।",
    "trecho_grifado": "अंश हाइलाइट किया गया।",
    "grifo_removido": "हाइलाइट हटाया गया।",
    "comentario_apagado": "टिप्पणी मिटाई गई।",
    "remover_grifo": "हाइलाइट हटाएँ",
    "apagar_comentario": "टिप्पणी मिटाएँ",
    "remover_grifo_2": "हाइलाइट हटाएँ?",
    "apagar_comentario_2": "टिप्पणी मिटाएँ?",
    "remover_este_grifo": "यह हाइलाइट हटाएँ?",
    "apagar_este_comentario": "यह टिप्पणी मिटाएँ?",
    "sem_comentario": "कोई टिप्पणी नहीं",
    "comentario": "टिप्पणी",
    "marcador_removido_desta_pagina": "इस पृष्ठ से बुकमार्क हटाया गया।",
    "pagina_adicionada_aos_marcadores": "पृष्ठ बुकमार्क में जोड़ा गया।",
    "este_e_o_inicio_do_livro": "यह पुस्तक की शुरुआत है।",
    "esta_e_a_primeira_pagina": "यह पहला पृष्ठ है।",
    "voce_chegou_ao_fim_do_livro": "पुस्तक का अंत आ गया।",
    "voce_chegou_ao_fim_do_quadrinho": "कॉमिक का अंत आ गया।",
    "agora_em_revista_aberta_duas_paginas_l": "अब दो-पृष्ठ दृश्य में: दो पृष्ठ साथ-साथ, कवर अलग।",
    "leitura_horizontal_ativada_neste_livro": "इस पुस्तक के लिए क्षैतिज पठन चालू।",
    "rolagem_vertical_ativada_neste_livro": "इस पुस्तक के लिए लंबवत स्क्रॉल चालू।",
    "leitura_pagina_a_pagina_ativada_neste": "इस कॉमिक के लिए पृष्ठ-दर-पृष्ठ पठन चालू।",
    "rolagem_continua_ativada_neste_quadrin": "इस कॉमिक के लिए सतत स्क्रॉल चालू।",
    "mudar_para_rolagem_vertical": "लंबवत स्क्रॉल पर जाएँ",
    "mudar_para_leitura_horizontal": "क्षैतिज पठन पर जाएँ",
    "rolagem_continua_estilo_webtoon": "सतत स्क्रॉल (वेबटून शैली)",
    "voltar_para_pagina_a_pagina": "पृष्ठ-दर-पृष्ठ पर लौटें",
    "separando_os_capitulos": "अध्याय अलग कर रहे हैं...",
    "lendo_o_livro": "पुस्तक पढ़ रहे हैं",
    "lendo_o_markdown": "Markdown पढ़ रहे हैं",
    "lendo_o_documento": "दस्तावेज़ पढ़ रहे हैं",
    "pagina_indisponivel": "पृष्ठ अनुपलब्ध।",
    "isto_acontece_so_desta_vez": "यह केवल इस बार हो रहा है।",
    "preparando_o_quadrinho": "कॉमिक तैयार कर रहे हैं",
    "abrindo_o_quadrinho": "कॉमिक खोल रहे हैं...",
    "montando_as_paginas": "पृष्ठ बना रहे हैं...",
    "nao_foi_possivel_abrir_este_livro": "यह पुस्तक नहीं खोली जा सकी।",
    "abertura_cancelada": "खोलना रद्द किया गया।",
    "o_livro_demorou_demais_para_abrir_e_fo": "पुस्तक खोलने में बहुत समय लगा और रोक दी गई।",
    "importe_o_arquivo_novamente_para_conti": "पढ़ना जारी रखने के लिए फ़ाइल फिर आयात करें।",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "इस पुस्तक की फ़ाइल अब आपके डिवाइस पर नहीं है।",
    "preparando_sua_leitura": "आपकी पुस्तक तैयार कर रहे हैं...",
    "abrindo_livro": "पुस्तक खोल रहे हैं",
    "leitura_concluida": "पठन पूरा हुआ।",
    "a_voz_foi_interrompida_pelo_navegador": "ब्राउज़र ने आवाज़ रोक दी।",
    "nao_foi_possivel_preparar_este_trecho": "यह अंश ऑडियो के लिए तैयार नहीं हो सका।",
    "a_leitura_em_voz_alta_nao_e_suportada": "इस ब्राउज़र में ज़ोर से पढ़ना समर्थित नहीं है।",
    "pausar_leitura": "पठन रोकें",
    "em_pausa": "रुका हुआ",
    "leitura_em_voz_alta_nao_disponivel_nes": "इस ब्राउज़र में ज़ोर से पढ़ना उपलब्ध नहीं",
    "nome_do_marcador": "बुकमार्क का नाम",
    "o_marcador_sera_removido_deste_audioli": "बुकमार्क इस ऑडियोबुक से हटा दिया जाएगा।",
    "nao_foi_possivel_salvar_o_marcador": "बुकमार्क सहेजा नहीं जा सका।",
    "ja_existe_um_marcador_neste_ponto": "इस स्थान पर पहले से एक बुकमार्क है।",
    "timer_de_sono_encerrado": "स्लीप टाइमर समाप्त।",
    "fim_do_cap": "अध्याय का अंत",
    "timer_desativado": "टाइमर बंद।",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "ऑडियो अध्याय के अंत में रुकेगा।",
    "este_audiolivro_nao_tem_capitulos": "इस ऑडियोबुक में अध्याय नहीं हैं।",
    "ao_fim_do_capitulo": "अध्याय के अंत में",
    "desativar_timer": "टाइमर बंद करें",
    "mais_10_minutos_no_timer": "टाइमर में 10 मिनट और।",
    "somar_10_minutos": "10 मिनट जोड़ें",
    "pausa_ao_fim_do_capitulo": "अध्याय के अंत में रोकें",
    "no_livro_todo": "पूरी पुस्तक में",
    "video": "वीडियो",
    "audiolivro_concluido": "ऑडियोबुक पूरी हुई।",
    "video_concluido": "वीडियो पूरा हुआ।",
    "video_2": "वीडियो",
    "audio": "ऑडियो",
    "toque_em_reproduzir_para_comecar": "शुरू करने के लिए प्ले दबाएँ।",
    "falha_ao_carregar_o_audio": "ऑडियो लोड नहीं हुआ।",
    "exclua_o_da_biblioteca_e_importe_o_arq": "लाइब्रेरी से हटाएँ और फ़ाइल फिर आयात करें।",
    "os_nomes_dos_arquivos_seguem_uma_seque": "फ़ाइल नाम क्रम में हैं, इसलिए वे एक ही ऑडियोबुक के अध्याय लगते हैं।",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "फ़ाइलों की टैग में एक ही एल्बम है, इसलिए वे एक ही ऑडियोबुक के अध्याय लगते हैं।",
    "libere_espaco_ou_exclua_livros_da_bibl": "जगह खाली करें या लाइब्रेरी से पुस्तकें हटाएँ और फिर प्रयास करें।",
    "o_armazenamento_do_aparelho_esta_cheio": "आपके डिवाइस का संग्रहण भरा है।",
    "preparando_a_capa": "कवर तैयार कर रहे हैं...",
    "remova_esse_arquivo_da_selecao_e_tente": "उस फ़ाइल को चयन से हटाएँ और फिर प्रयास करें।",
    "sequencia": "क्रम",
    "o_arquivo_pode_estar_incompleto_tente": "फ़ाइल अधूरी हो सकती है। फिर डाउनलोड करें।",
    "conferindo_se_o_audio_pode_ser_reprodu": "देख रहे हैं कि ऑडियो चल सकता है या नहीं...",
    "conferindo_se_o_video_pode_ser_reprodu": "देख रहे हैं कि वीडियो चल सकता है या नहीं...",
    "lendo_titulo_capitulos_e_capa": "शीर्षक, अध्याय और कवर पढ़ रहे हैं...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "फ़ाइल खराब हो सकती है या ऐसे ऑडियो प्रारूप में हो सकती है जिसे ब्राउज़र नहीं चला सकता। इसे MP3 या M4B (AAC) में बदलकर देखें।",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "फ़ाइल खराब हो सकती है या ऐसे वीडियो प्रारूप में हो सकती है जिसे ब्राउज़र नहीं चला सकता। इसे H.264 वीडियो और AAC ऑडियो वाले MP4 में बदलकर देखें।",
    "converta_o_audiolivro_para_m4b_com_aud": "ऑडियोबुक को AAC ऑडियो के साथ M4B (या MP3) में बदलें और फिर आयात करें।",
    "converta_o_video_para_mp4_com_audio_aa": "वीडियो को AAC ऑडियो और H.264 वीडियो के साथ MP4 में बदलें और फिर आयात करें।",
    "o_navegador_nao_reproduz_o_formato_de": "ब्राउज़र इस फ़ाइल का ऑडियो प्रारूप नहीं चलाता।",
    "arquivos_com_protecao_nao_podem_ser_re": "सुरक्षित फ़ाइलें यहाँ नहीं चलाई जा सकतीं। DRM-मुक्त प्रति उपयोग करें।",
    "nao_ha_espaco_suficiente_no_aparelho_p": "इस ऑडियोबुक के लिए आपके डिवाइस पर पर्याप्त जगह नहीं है।",
    "confira_se_a_extensao_corresponde_ao_c_2": "जाँचें कि एक्सटेंशन सामग्री से मेल खाती है, या ऑडियो को MP3 या M4B (AAC) में बदलें।",
    "imagem_invalida": "अमान्य छवि",
    "imagem_demorou_demais": "छवि लोड होने में बहुत समय लगा",
    "imagem_vazia": "खाली छवि",
    "inicio": "शुरुआत",
    "mp4_moov_nao_encontrado": "वीडियो अधूरा या खराब लगता है।",
    "pagina": "पृष्ठ",
    "esta_pagina_nao_esta_disponivel": "यह पृष्ठ उपलब्ध नहीं है।",
    "esta_pagina_nao_pode_ser_descompactada": "यह पृष्ठ खोला नहीं जा सका।",
    "quadrinho_fechado": "कॉमिक बंद।",
    "ele_pode_estar_incompleto_dividido_em": "यह अधूरा, कई भागों में बँटा, या RAR के ऐसे रूप में हो सकता है जिसे ऐप नहीं पहचानता। CBZ में बदलने से ठीक हो जाता है।",
    "remova_a_senha_do_arquivo_e_importe_de": "फ़ाइल से पासवर्ड हटाएँ और फिर आयात करें।",
    "nao_foi_possivel_ler_este_arquivo_de_q": "यह कॉमिक फ़ाइल पढ़ी नहीं जा सकी।",
    "este_quadrinho_esta_protegido_por_senh": "यह कॉमिक पासवर्ड से सुरक्षित है।",
    "lendo_o_indice_do_quadrinho": "कॉमिक की अनुक्रमणिका पढ़ रहे हैं...",
    "o_arquivo_pode_ser_grande_demais_para": "फ़ाइल इस डिवाइस की मेमोरी के लिए बहुत बड़ी हो सकती है। कॉमिक को छोटे भागों में बाँटना आमतौर पर ठीक कर देता है।",
    "nao_foi_possivel_abrir_este_quadrinho": "यह कॉमिक नहीं खोली जा सकी।",
    "lendo_o_arquivo": "फ़ाइल पढ़ रहे हैं...",
    "preparando_o_leitor_de_cbr": "CBR रीडर तैयार कर रहे हैं...",
    "o_arquivo_pode_estar_incompleto_proteg": "फ़ाइल अधूरी, पासवर्ड-सुरक्षित या खराब हो सकती है।",
    "nao_foi_possivel_ler_este_quadrinho": "यह कॉमिक पढ़ी नहीं जा सकी।",
    "o_arquivo_precisa_conter_imagens_jpg_p": "फ़ाइल में छवियाँ होनी चाहिए (JPG, PNG, WEBP या GIF)।",
    "nao_encontramos_paginas_dentro_deste_q": "इस कॉमिक में कोई पृष्ठ नहीं मिला।",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "इस कॉमिक के लिए आपके डिवाइस पर पर्याप्त जगह नहीं है।",
    "cabecalho_de_item_invalido": "फ़ाइल का एक हिस्सा खराब है।",
    "a_pasta_vendor_libarchive_precisa_esta": "इस कॉमिक को खोलने के लिए ऐप का एक घटक मौजूद नहीं है। इसे CBZ में बदलें या ऐप को फिर से इंस्टॉल करें।",
    "o_leitor_de_cbr_nao_foi_encontrado": "CBR रीडर नहीं मिला।",
    "converta_o_quadrinho_para_cbz_zip_e_im": "कॉमिक को CBZ (ZIP) में बदलें और फिर आयात करें।",
    "este_navegador_nao_consegue_abrir_arqu": "यह ब्राउज़र CBR फ़ाइलें नहीं खोल सकता।",
    "convertendo_o_markdown": "Markdown बदल रहे हैं",
    "lendo_o_texto": "पाठ पढ़ रहे हैं",
    "pdf_indisponivel": "PDF अनुपलब्ध।",
    "epub_invalido_nenhum_capitulo_no_spine": "यह EPUB खराब है: पुस्तक के अध्याय नहीं मिले।",
    "livro_sem_titulo": "बिना शीर्षक पुस्तक",
    "epub_invalido_arquivo_opf_nao_encontra": "यह EPUB अधूरा या खराब है और खोला नहीं जा सकता।",
    "epub_invalido_container_xml_nao_encont": "यह EPUB अधूरा या खराब है और खोला नहीं जा सकता।",
    "organizando_o_texto": "पाठ व्यवस्थित कर रहे हैं",
    "descompactando_o_livro": "पुस्तक खोल रहे हैं",
    "nao_encontramos_conteudo_para_exibir_n": "इस फ़ाइल में दिखाने के लिए कुछ नहीं मिला।",
    "livro_sem_texto_legivel": "पढ़ने योग्य पाठ के बिना पुस्तक",
    "o_arquivo_pode_estar_corrompido_tente": "फ़ाइल खराब हो सकती है। इसे EPUB में बदलने का प्रयास करें।",
    "nao_foi_possivel_extrair_o_texto_deste": "इस MOBI से पाठ नहीं निकाला जा सका।",
    "nenhum_registro_de_conteudo_foi_encont": "इस फ़ाइल में पुस्तक का पाठ नहीं मिला।",
    "arquivo_mobi_sem_texto": "पाठ के बिना MOBI फ़ाइल।",
    "o_dicionario_de_compressao_esta_vazio": "इस MOBI की कुछ सामग्री मौजूद नहीं है।",
    "arquivo_mobi_incompleto": "अधूरी MOBI फ़ाइल।",
    "as_tabelas_de_compressao_nao_foram_enc": "इस MOBI की कुछ सामग्री मौजूद नहीं है।",
    "converta_o_arquivo_para_epub_em_um_pro": "Calibre जैसे प्रोग्राम में फ़ाइल को EPUB में बदलें और फिर आयात करें।",
    "compressao_mobi_nao_reconhecida": "यह MOBI एक ऐसे आंतरिक प्रारूप का उपयोग करता है जिसे ऐप नहीं पहचानता।",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "पुस्तक का हेडर पढ़ा नहीं जा सका।",
    "arquivo_mobi_corrompido": "खराब MOBI फ़ाइल।",
    "a_lista_interna_de_registros_esta_inco": "फ़ाइल अधूरी है। इसे फिर से डाउनलोड करके या बदलकर देखें।",
    "o_download_parece_ter_sido_interrompid": "डाउनलोड बीच में रुका लगता है। फ़ाइल फिर डाउनलोड करें।",
    "tabela_de_compressao_mobi_corrompida": "इस MOBI फ़ाइल का एक हिस्सा खराब है।",
    "tabela_de_compressao_mobi_incompleta": "यह MOBI फ़ाइल अधूरी है।",
    "tabela_de_compressao_mobi_invalida": "इस MOBI फ़ाइल का एक हिस्सा खराब है।",
    "este_arquivo_docx_nao_tem_conteudo_de": "इस .docx फ़ाइल में दिखाने योग्य पाठ सामग्री नहीं है।",
    "documento_sem_texto": "पाठ के बिना दस्तावेज़",
    "o_arquivo_pode_estar_corrompido_proteg": "फ़ाइल खराब, पासवर्ड-सुरक्षित या पुरानी .doc हो सकती है। इसे .docx के रूप में फिर सहेजें और फिर आयात करें।",
    "nao_foi_possivel_ler_este_arquivo_docx": "यह DOCX फ़ाइल पढ़ी नहीं जा सकी।",
    "convertendo_o_documento": "दस्तावेज़ बदल रहे हैं",
    "conecte_se_a_internet_uma_vez_para_bai": "घटक डाउनलोड करने के लिए एक बार इंटरनेट से जुड़ें, फिर पुस्तक फिर खोलें।",
    "o_conversor_de_docx_nao_carregou": "DOCX कन्वर्टर लोड नहीं हुआ।",
    "video_mp4": "वीडियो (MP4)",
    "audiolivro_m4b": "ऑडियोबुक (M4B)",
    "audiolivro_mp3": "ऑडियोबुक (MP3)",
    "quadrinho_cbt": "कॉमिक (CBT)",
    "quadrinho_cb7": "कॉमिक (CB7)",
    "quadrinho_cbr": "कॉमिक (CBR)",
    "quadrinho_cbz": "कॉमिक (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "पाठ (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "सहेजना रद्द किया गया।",
    "o_arquivo_esta_vindo_do_armazenamento": "फ़ाइल क्लाउड संग्रहण से आपके डिवाइस पर आ रही है।",
    "baixando_o_arquivo": "फ़ाइल डाउनलोड कर रहे हैं",
    "cancelando": "रद्द कर रहे हैं...",
    "use_grifar_citacao_anotar_ou_marcador": "पढ़ते समय हाइलाइट, उद्धरण, नोट या बुकमार्क का उपयोग करें।",
    "nenhuma_marcacao_ainda": "अभी कोई निशान नहीं",
    "trecho_original": "मूल अंश",
    "procurar_meus_livros": "मेरी पुस्तकें खोजें",
    "a_busca_fica_sempre_disponivel_no_menu": "खोज हमेशा साइड मेन्यू में, सिस्टम के अंतर्गत उपलब्ध है।",
    "da_para_fazer_depois": "बाद में कर सकते हैं",
    "nada_entra_na_estante_sem_a_sua_confir": "आपकी अनुमति के बिना कुछ भी शेल्फ पर नहीं आता: आप सूची देखते हैं और जो चाहें चुनते हैं।",
    "voce_revisa_antes": "आप पहले जाँचते हैं",
    "escolha_uma_pasta_downloads_e_um_bom_c": "एक फ़ोल्डर चुनें (Downloads अच्छी शुरुआत है) और ऐप उसे व उसकी सभी उप-फ़ोल्डरों को खोजता है।",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR और M4B खोजता है",
    "voltar_e_revisar": "लौटें और जाँचें",
    "ler_os_termos": "शर्तें पढ़ें",
    "ler_a_politica": "नीति पढ़ें",
    "os_dois_documentos_ficam_sempre_dispon": "दोनों दस्तावेज़ हमेशा साइड मेन्यू में, परिचय के अंतर्गत उपलब्ध हैं।",
    "leia_com_calma": "आराम से पढ़ें",
    "a_politica_e_os_termos_explicam_como_o": "नीति और शर्तें बताती हैं कि ऐप आपकी पुस्तकें कैसे रखता है और उनके साथ क्या किया जा सकता है। लाइब्रेरी का उपयोग करने के लिए इनसे सहमति देना ज़रूरी है।",
    "nada_acontece_sem_o_aceite": "शुरू करने के लिए, कृपया शर्तें स्वीकार करें",
    "aceitar_e_continuar": "स्वीकारें और जारी रखें",
    "nao_aceito": "अस्वीकार करें",
    "termos_de_uso_2": "उपयोग की शर्तें",
    "politica_de_privacidade_2": "गोपनीयता नीति",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "ऐप केवल उन फ़ाइलों और फ़ोल्डरों तक पहुँचता है जो आप चुनते हैं, जब आप चुनते हैं।",
    "voce_no_controle": "नियंत्रण आपके पास है",
    "depois_de_importar_um_livro_voce_le_se": "पुस्तक आयात करने के बाद आप बिना इंटरनेट पढ़ते हैं।",
    "funciona_offline": "ऑफ़लाइन काम करता है",
    "livros_marcacoes_e_progresso_sao_guard": "पुस्तकें, निशान और प्रगति आपके डिवाइस पर रखी जाती हैं। हमारे किसी सर्वर पर कुछ नहीं भेजा जाता।",
    "tudo_fica_no_seu_aparelho": "सब कुछ आपके डिवाइस पर रहता है",
    "escolha_o_que_deseja_adicionar_a_bibli": "लाइब्रेरी में जोड़ने के लिए चुनें। शेल्फ पर पहले से मौजूद समान फ़ाइलें स्वतः छोड़ दी जाती हैं।",
    "voce_pode_tentar_outra_pasta_ou_import": "आप दूसरा फ़ोल्डर आज़मा सकते हैं, या + बटन से फ़ाइलें आयात कर सकते हैं।",
    "a_leitura_acontece_so_no_seu_dispositi": "पढ़ना केवल आपके डिवाइस पर होता है।",
    "voce_escolhe_a_pasta": "फ़ोल्डर आप चुनते हैं",
    "tema_tipografia_margens_modo_de_virada": "थीम, टाइपफ़ेस, मार्जिन, पृष्ठ पलटाव शैली और ऑडियो सेटिंग्स।",
    "restaurar_minhas_preferencias": "मेरी प्राथमिकताएँ बहाल करें",
    "o_backup_manda_as_marcacoes_atuais_dos": "बैकअप जीतता है। फ़ाइल में मौजूद पुस्तकों के वर्तमान निशान बैकअप के निशानों से बदल दिए जाएंगे।",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "कुछ नहीं मिटता। दोनों ओर के निशान जुड़ते हैं और अधिक हाल की प्रगति जीतती है।",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "शेल्फ पर पहले से मौजूद चीज़ों का क्या करें",
    "grifos_citacoes_e_notas": "हाइलाइट, उद्धरण और नोट्स",
    "preparando_o_arquivo_2": "फ़ाइल तैयार कर रहे हैं...",
    "os_livros_em_si_nem_as_capas_por_isso": "इसमें न तो पुस्तकें शामिल हैं, न ही कवर — इसीलिए फ़ाइल केवल कुछ KB की है। प्राप्तकर्ता के पास पुस्तकों की फ़ाइलें होनी चाहिए ताकि निशान अपनी जगह लौट आएँ, और आयात के समय कवर स्वचालित रूप से फिर दिखाई देते हैं।",
    "nao_vai_no_arquivo": "फ़ाइल में नहीं जाता",
    "o_seu_progresso_de_leitura_os_grifos_a": "आपकी पठन प्रगति, हाइलाइट, उद्धरण, नोट्स, बुकमार्क और शेल्फ का संगठन — स्थिति, पसंदीदा, संग्रह, श्रृंखलाएँ और टैग।",
    "vai_no_arquivo": "फ़ाइल में जाता है",
    "descartar_o_que_esta_esperando_2": "प्रतीक्षा में रखा डेटा हटाएँ",
    "esperando_o_arquivo": "फ़ाइल का इंतज़ार",
    "avisar_quando_fizer_tempo_sem_backup": "बिना बैकअप बहुत समय होने पर याद दिलाएँ",
    "livros_que_ainda_nao_estiverem_na_esta": "जो पुस्तकें अभी शेल्फ पर नहीं हैं, वे प्रतीक्षा में रहती हैं: उनकी फ़ाइल आयात करते ही निशान स्वचालित रूप से वापस आ जाते हैं।",
    "restaurar_backup": "बैकअप पुनर्स्थापित करें",
    "salvar_backup": "बैकअप सहेजें",
    "ainda_nao_ha_itens": "अभी यहाँ कुछ नहीं",
    "arraste_um_livro_para_outra_posicao_na": "अपना क्रम सहेजने के लिए पुस्तक को शेल्फ पर कहीं और खींचें। यह मैन्युअल क्रम लेखक के समूहन पर प्राथमिकता ले लेता है।",
    "separe_por_virgulas": "अल्पविराम से अलग करें",
    "ex_estudos_ficcao": "जैसे अध्ययन, कथा...",
    "pasta_estante": "फ़ोल्डर / शेल्फ",
    "ex_trilogia": "जैसे त्रयी...",
    "serie": "श्रृंखला",
    "aparece_em_favoritos": "पसंदीदा में दिखता है।",
    "nome_do_livro": "पुस्तक का नाम",
    "nenhum_registro_ainda": "अभी कुछ दर्ज नहीं",
    "no_leitor_toque_no_icone_de_marcador_p": "रीडर में, पृष्ठ सहेजने के लिए बुकमार्क आइकन दबाएँ।",
    "nenhum_marcador_ainda": "अभी कोई बुकमार्क नहीं",
    "a_gravacao_e_independente_da_localizac": "सहेजना PDF के स्थान से स्वतंत्र है और मूल फ़ाइल को नहीं बदलता।",
    "o_pdf_original_nao_precisa_estar_nessa": "मूल PDF का उस फ़ोल्डर में होना आवश्यक नहीं",
    "excluir_da_biblioteca": "लाइब्रेरी से हटाएँ",
    "adicionar_livro": "पुस्तक जोड़ें",
    "adicione_livros_e_acompanhe_o_que_esta": "पुस्तकें जोड़ें और देखें क्या इंतज़ार में है, क्या चल रहा है और कितनी दूर पहुँचे।",
    "tudo_pronto_para_a_proxima_leitura": "अगली पढ़ाई के लिए सब तैयार।",
    "sua_biblioteca": "आपकी लाइब्रेरी",
    "arraste_um_livro_para_reposiciona_lo_a": "पुस्तक खींचकर हिलाएँ: शेल्फ मेरे क्रम पर बदल जाती है और क्रम बनाए रखती है।",
    "importe_um_livro_ou_ajuste_seus_filtro": "पुस्तक आयात करें, या अपने फ़िल्टर समायोजित करें।",
    "nada_por_aqui_ainda": "अभी यहाँ कुछ नहीं",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "+ दबाएँ और MP3, M4B या MP4 फ़ाइलें चुनें। कई अध्याय MP3 एक ऑडियोबुक बन सकते हैं।",
    "nada_para_ouvir_ou_assistir_ainda": "अभी सुनने या देखने के लिए कुछ नहीं",
    "o_pdf_original_permanece_intacto_na_pa": "मूल PDF आपके फ़ोल्डर में अछूती रहती है।",
    "paginas_como_imagem": "छवियों के रूप में पृष्ठ",
    "paginas_do_pdf": "PDF के पृष्ठ",
    "em_navegadores_sem_suporte_a_acesso_di": "सीधी फ़ाइल सिस्टम पहुँच के बिना ब्राउज़र में, EPUB डाउनलोड हो जाएगी।",
    "essa_permissao_e_dada_somente_a_esta_a": "यह अनुमति केवल इस ऐप को दी जाती है और मूल फ़ाइल को बदलने से बचाती है।",
    "selecione_a_pasta_que_contem_o_pdf": "वह फ़ोल्डर चुनें जिसमें PDF है",
    "preparando": "तैयारी…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "फ़ाइल पढ़ी और फिर से बनाई जा रही है। बड़ी पुस्तकों में कुछ समय लग सकता है।",
    "revistas_apostilas_complexas_formulari": "पत्रिकाएँ, जटिल कार्यपुस्तिकाएँ, फ़ॉर्म, कई तालिकाओं वाले दस्तावेज़ या स्कैन PDF अपना कुछ मूल लेआउट खो सकते हैं।",
    "funcionalidade_indicada_apenas_para_li": "केवल पुस्तकों के लिए",
    "o_epub_e_melhor_para_livros_com_texto": "चयनयोग्य पाठ वाली पुस्तकों के लिए EPUB बेहतर है, क्योंकि इसमें टाइपफ़ेस, आकार, मार्जिन और पठन मोड समायोजित होते हैं।",
    "trecho_selecionado": "चयनित अंश",
    "trecho_comentado": "टिप्पणी वाला अंश",
    "aplicando_zoom": "ज़ूम लगा रहे हैं...",
    "nao_foi_possivel_carregar_esta_pagina": "यह पृष्ठ लोड नहीं हो सका।",
    "nomear_marcador": "बुकमार्क का नाम दें",
    "toque_em_marcar_agora_para_guardar_est": "इस स्थान को सहेजने और जब चाहें लौटने के लिए “अभी चिह्नित करें” दबाएँ।",
    "timer_ativo": "टाइमर चालू",
    "trecho_ausente_ou_corrompido_no_arquiv": "[मूल फ़ाइल में अंश अनुपस्थित या खराब]",
    "novos_livros_vao_abrir_em_leitura_v": "नई पुस्तकें {v} पठन में खुलेंगी।",
    "leitura_efetivo_aplicada_a_este_livro": "इस पुस्तक पर {efetivo} पठन लागू।",
    "automatico_neste_livro_leitura_efetivo": "इस पुस्तक में स्वचालित: {efetivo} पठन।",
    "agora_esta_em_efetivo_no_automatico_fo": "अब {efetivo} पर सेट; स्वचालित पर, {format} {padrao} में खुलता है।",
    "esta_escolha_vale_so_para_v_cada_livro": "यह चयन केवल “{v}” पर लागू। हर पुस्तक अपनी स्क्रॉल दिशा रखती है।",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} अभी आपकी शेल्फ पर नहीं हैं।",
    "escolha_uma_pasta_para_procurar_label": "{label} खोजने के लिए फ़ोल्डर चुनें।",
    "subtitle_versao_build": "{subtitle} · संस्करण {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "{path} पढ़ा नहीं जा सका; अंतर्निहित पाठ उपयोग कर रहे हैं।",
    "seu_ultimo_backup_foi_ha_dias_dias": "आपका अंतिम बैकअप {dias} दिन पहले था",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "बैकअप की {aguardando} पुस्तक अभी यहाँ नहीं है। उसकी प्रगति और निशान सुरक्षित रखे गए हैं: फ़ाइल आयात करते ही सब कुछ स्वचालित रूप से अपनी जगह वापस आ जाएगा।",
      "other": "बैकअप की {aguardando} पुस्तकें अभी यहाँ नहीं हैं। उनकी प्रगति और निशान सुरक्षित रखे गए हैं: हर फ़ाइल आयात करते ही सब कुछ स्वचालित रूप से अपनी जगह वापस आ जाएगा।"
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "आपकी शेल्फ की {atualizados} पुस्तक अपडेट की गई।",
      "other": "आपकी शेल्फ की {atualizados} पुस्तकें अपडेट की गईं।"
    },
    "criado_em_quando": "{quando} को बनाया",
    "backup_pronto_livros_livro_s_e_marcaco": "बैकअप तैयार: {livros} पुस्तकें और {marcacoes} निशान।",
    "endereco_seguro_seguro": "सुरक्षित पता: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "इस पुस्तक के लिए प्रगति और {marcas} निशान बहाल।",
      "other": "इस पुस्तक के लिए प्रगति और {marcas} निशान बहाल।"
    },
    "restaurando_v_de_length": "पुनर्स्थापित ({v} / {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} पुस्तकें · {marcacoes} निशान",
    "criado_em_v": "{v} को बनाया",
    "reunindo_a_sua_estante_v_de_length": "आपकी शेल्फ इकट्ठा ({v} / {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "“{titulo}” पहले आयात की गई और आपकी लाइब्रेरी में बनी हुई है। कोई नई प्रति नहीं बनी।",
    "length_arquivos_de_audio": "{length} ऑडियो फ़ाइलें...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "{falhas} फ़ाइल पढ़ी नहीं जा सकी।",
      "other": "{falhas} फ़ाइलें पढ़ी नहीं जा सकीं।"
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} पहले से लाइब्रेरी में थीं और छोड़ दी गईं।",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "{importados} पुस्तक आपकी शेल्फ पर जोड़ी गई।",
      "other": "{importados} पुस्तकें आपकी शेल्फ पर जोड़ी गईं।"
    },
    "epub_salvo_em_filename": "EPUB {fileName} में सहेजी गई।",
    "falha_ao_converter_o_pdf_v": "PDF बदलने में विफल: {v}",
    "pagina_page_de_totalpages": "पृष्ठ {page} / {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} पृष्ठ",
      "other": "{totalPages} पृष्ठ"
    },
    "length_resultado_s_para_search": {
      "one": "“{search}” के लिए {length} परिणाम",
      "other": "“{search}” के लिए {length} परिणाम"
    },
    "capitulo_v": "अध्याय {v}",
    "organizando_capitulo_v_de_totalchapter": "अध्याय {v} / {totalChapters} व्यवस्थित कर रहे हैं",
    "pagina_v": "पृष्ठ {v}",
    "paginas_v_v2": "पृष्ठ {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} पृष्ठ तैयार",
      "other": "{length} पृष्ठ तैयार"
    },
    "montando_as_paginas_pagessofar_prontas": "पृष्ठ बना रहे हैं — {pagesSoFar} हो गए",
    "lendo_pagina_v_de_length": "पृष्ठ {v} / {length} पढ़ रहे हैं",
    "marcador_salvo_em_t": "बुकमार्क {t} पर सहेजा गया।",
    "o_audio_vai_pausar_em_minutes_minutos": "ऑडियो {minutes} मिनट में रुकेगा।",
    "length_capitulos_toque_para_ir_direto": "{length} अध्याय · सीधे जाने के लिए टैप करें।",
    "narrado_por_narrator": "{narrator} द्वारा सुनाया गया",
    "velocidade_de_reproducao_rate": "प्लेबैक गति: {rate}",
    "avancar_f_segundos": "{f} सेकंड आगे",
    "nao_foi_possivel_abrir_este_v": "यह {v} नहीं खोला जा सका।",
    "nao_foi_possivel_ler_o_arquivo_de_v": "{v} फ़ाइल पढ़ी नहीं जा सकी।",
    "o_v_esta_danificado_neste_ponto": "{v} इस बिंदु पर खराब है।",
    "o_navegador_nao_consegue_reproduzir_es": "ब्राउज़र यह {v} फ़ाइल नहीं चला सकता।",
    "nao_foi_possivel_reproduzir_este_v": "यह {v} नहीं चलाया जा सका।",
    "os_dados_deste_noun_estao_incompletos": "इस {noun} का डेटा अधूरा है।",
    "importe_o_arquivo_novamente_para_conti_2": "{v} जारी रखने के लिए फ़ाइल फिर आयात करें।",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "इस {noun} की फ़ाइल अब आपके डिवाइस पर नहीं है।",
    "nao_foi_possivel_descobrir_a_duracao_d": "“{name}” की अवधि पता नहीं चल सकी।",
    "lendo_faixa_v_de_length": "ट्रैक {v} / {length} पढ़ रहे हैं...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "इस {v} की अवधि पता नहीं चल सकी।",
    "este_format_nao_pode_ser_reproduzido_n": "यह {format} इस ब्राउज़र में नहीं चल सकता।",
    "este_format_esta_protegido_por_drm": "यह {format} DRM से सुरक्षित है।",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "फ़ाइल {bytes} की है और लगभग {v} बचा है। जगह खाली करें या लाइब्रेरी से पुस्तकें हटाएँ।",
    "este_arquivo_nao_e_um_format_valido": "यह फ़ाइल मान्य {format} नहीं है।",
    "preparando_as_paginas_vistas_de_total": "पृष्ठ तैयार ({vistas} / {total})...",
    "preparando_total_pagina_s": {
      "one": "{total} पृष्ठ तैयार...",
      "other": "{total} पृष्ठ तैयार..."
    },
    "preparando_as_paginas_v_de_total": "पृष्ठ तैयार ({v} / {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "यह लगभग {bytes} लेता है और करीब {v} बचा है। जगह खाली करें या लाइब्रेरी से पुस्तकें हटाएँ।",
    "envio_direto_exige_endereco_seguro": "किसी दूसरे ऐप पर सीधे भेजना उपलब्ध नहीं है, क्योंकि यह पेज सुरक्षित पते से नहीं खोला गया। फ़ाइल सहेजें और अपनी पसंद के किसी भी ऐप से भेजें।",
    "na_estante": "शेल्फ पर",
    "nao_foi_possivel_montar_o_arquivo": "फ़ाइल बनाई नहीं जा सकी।",
    "este_navegador_nao_oferece_o_envio_dir": "यह ब्राउज़र सीधे दूसरे ऐप पर भेजना नहीं देता। फ़ाइल सहेजें और जो ऐप पसंद हो उससे भेजें।",
    "voce_ainda_nao_fez_nenhum_backup": "आपने अभी कोई बैकअप नहीं बनाया।",
    "converter_para_epub": "EPUB में बदलें",
    "esta_pagina_nao_pode_ser_exibida": "यह पृष्ठ दिखाया नहीं जा सका।",
    "na_ordem_em_que_serao_tocados": "जिस क्रम में बजेंगे",
    "este_capitulo_nao_pode_ser_exibido": "यह अध्याय दिखाया नहीं जा सका।",
    "livro": "पुस्तक",
    "restantes": " शेष",
    "como_seus_dados_sao_tratados": "आपके डेटा का उपयोग कैसे होता है",
    "condicoes_de_uso_do_aplicativo": "ऐप के उपयोग की शर्तें",
    "audiolivro": "ऑडियोबुक",
    "sobre_o_aplicativo": "ऐप के बारे में",
    "o_que_e_o_veredas_reader": "Veredas Reader क्या है",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(यह डिवाइस इस प्रकार की फ़ाइल साझा करने की सुविधा नहीं देता)",
    "livros": "पुस्तकें",
    "lendo": "पढ़ रहे हैं",
    "lidos": "पूरी हुईं",
    "compartilhar_livro": "पुस्तक साझा करें",
    "n_livros": {
      "one": "{n} पुस्तक",
      "other": "{n} पुस्तकें"
    },
    "livros_unidade": {
      "one": "पुस्तक",
      "other": "पुस्तकें"
    },
    "uma_faixa_discreta_depois_de_n_dias": "{n} दिनों तक बिना बैकअप के बाद शेल्फ पर एक हल्की पट्टी। यह आपकी पढ़ाई कभी नहीं रोकती।",
    "scanned_arquivos_verificados_livros_enc": "{scanned} फ़ाइलें जाँचीं · {encontrados} पुस्तकें मिलीं",
    "v_de_total": "{v} / {total}",
    "voltar_n_segundos": "{n} सेकंड पीछे",
    "cancelado": "रद्द",
    "arquivo": "फ़ाइल",
    "outro": "अन्य",
    "outros": "अन्य",
    "audiolivro_2": "ऑडियोबुक",
    "pausar": "रोकें",
    "marcador": "बुकमार्क",
    "leitura": "पठन",
    "grifo": "हाइलाइट",
    "editar": "संपादित करें",
    "apagar": "मिटाएँ",
    "concluir": "समाप्त करें",
    "recentes": "हाल के",
    "progresso": "प्रगति",
    "entendi": "ठीक है",
    "aviso": "सूचना",
    "descartar": "हटाएँ",
    "copiado": "कॉपी किया",
    "restaurar": "पुनर्स्थापित करें",
    "restaurando": "पुनर्स्थापित कर रहे हैं",
    "excluir": "हटाएँ",
    "grifos": "हाइलाइट",
    "arquivo_vazio": "फ़ाइल खाली है।",
    "e_mais_n_arquivos": {
      "one": "और {n} फ़ाइल, जिस क्रम में बजेगी",
      "other": "और {n} फ़ाइलें, जिस क्रम में बजेंगी"
    },
    "n_arquivos_mp3": {
      "one": "{n} MP3 फ़ाइल",
      "other": "{n} MP3 फ़ाइलें"
    },
    "pct_restam": "{pct}% · {tempo} शेष",
    "n_minutos": {
      "one": "{n} मिनट",
      "other": "{n} मिनट"
    },
    "ir_para_tempo": "{tempo} पर जाएँ",
    "nomear": "नाम दें",
    "parte_n": "भाग {n}",
    "carregando_pagina_n": "पृष्ठ {n} लोड हो रहा है...",
    "selecionar_pasta_e_continuar": "फ़ोल्डर चुनें और जारी रखें",
    "ler_agora": "अभी पढ़ें",
    "agrupamento_v": "समूहन: {v}।",
    "tempo_restante": "{tempo} शेष",
    "abrir_titulo": "{titulo} खोलें",
    "continuar_lendo_titulo": "{titulo} पढ़ना जारी रखें",
    "continuar_ouvindo_titulo": "{titulo} सुनना जारी रखें",
    "continuar_assistindo_titulo": "{titulo} देखना जारी रखें",
    "lido": "पढ़ी हुई",
    "pausado": "रुकी हुई",
    "status": "स्थिति",
    "favorito": "पसंदीदा",
    "escolher_local": "स्थान चुनें",
    "epub_baixado_como": "EPUB {nome} के रूप में डाउनलोड हुआ।",
    "ouvir_a_partir_de": "{tempo} से सुनें",
    "assistir_a_partir_de": "{tempo} से देखें",
    "pagina_n_minuscula": "पृष्ठ {n}",
    "selecione_trecho_para_criar": "पढ़ते समय कोई अंश चुनें और {oque} बनाएँ।",
    "excluir_oque_pergunta": "{oque} हटाएँ?",
    "excluir_oque": "{oque} हटाएँ",
    "excluir_item_pergunta": "यह आइटम हटाएँ?",
    "use_organizar_para_criar": "किसी पुस्तक पर “{botao}” का उपयोग करके {oque} बनाएँ।",
    "n_arquivos_processados": {
      "one": "{n} फ़ाइल संसाधित",
      "other": "{n} फ़ाइलें संसाधित"
    },
    "voce_ja_tem_titulo_de_autor": "आपकी लाइब्रेरी में {autor} की “{titulo}” पहले से है, हालाँकि फ़ाइल अलग है। फिर भी आयात करें?",
    "voce_ja_tem_titulo": "आपकी लाइब्रेरी में “{titulo}” पहले से है, हालाँकि फ़ाइल अलग है। फिर भी आयात करें?",
    "marcadores_unidade": {
      "one": "बुकमार्क",
      "other": "बुकमार्क"
    },
    "ultimo_backup_em": "अंतिम बैकअप <strong>{data}</strong> को।",
    "guardar": "सहेजें",
    "lembretes": "रिमाइंडर",
    "juntar": "मिलाएँ",
    "recomendado": "अनुशंसित",
    "substituir": "बदलें",
    "n_capas_recuperadas": {
      "one": "{n} कवर वापस मिला।",
      "other": "{n} कवर वापस मिले।"
    },
    "nao_encontramos_arquivos_tipo": "इस फ़ोल्डर में कोई {tipo} फ़ाइल नहीं मिली।",
    "tentar_outra_pasta": "दूसरा फ़ोल्डर आज़माएँ",
    "n_livros_encontrados": {
      "one": "{n} पुस्तक मिली",
      "other": "{n} पुस्तकें मिलीं"
    },
    "n_de_total_selecionados": {
      "one": "{total} में से {n} चुनी गई",
      "other": "{total} में से {n} चुनी गईं"
    },
    "importar": "आयात करें",
    "importar_n": "{n} आयात करें",
    "aceite_frase": "मैंने Veredas Reader की {politica} और {termos} पढ़कर स्वीकार कर ली हैं।",
    "pdf_preservado": "मूल PDF <strong>आपके फ़ोल्डर से नहीं मिटेगी</strong>। EPUB के सफलतापूर्वक सहेजे जाने के बाद केवल इस PDF की प्रति लाइब्रेरी से हटाई जाएगी।",
    "gravar_epub_mesma_pasta": "EPUB को <strong>PDF वाले फ़ोल्डर में ही</strong> सहेजने के लिए ब्राउज़र को उस फ़ोल्डर तक पहुँचने की अनुमति चाहिए।",
    "epub_pronto_qualquer_pasta": "EPUB बदल दिया गया है। अब आप फ़ाइल सहेजने के लिए <strong>कंप्यूटर का कोई भी फ़ोल्डर</strong> चुन सकते हैं।",
    "backup_explicacao": "मूल बैकअप ZIP या TXT फ़ाइल है। दूसरे डिवाइस पर मिलने पर इसे <strong>बैकअप पुनर्स्थापित करें</strong> से आयात करें: Veredas सामग्री पहचानकर उसे सामान्य रूप से बहाल कर देता है। फ़ाइल में आपकी प्रगति, हाइलाइट, उद्धरण, नोट्स, बुकमार्क और शेल्फ़ का संगठन रहता है — <strong>पुस्तकें स्वयं नहीं</strong>, न ही कवर।",
    "lembretes_desligados_frase": "रिमाइंडर <strong>बंद</strong> हैं। समय-समय पर बैकअप लेना याद रखें।",
    "backup_salvo_nos_downloads": "<strong>बैकअप फ़ाइल इस डिवाइस पर सहेजी गई</strong>, आपके डाउनलोड में। इसे अभी भेज सकते हैं: WhatsApp, ईमेल, Drive या जो चाहें खोलें, अटैच दबाएँ और फ़ाइल चुनें।",
    "arquivo_pronto_tamanho": "फ़ाइल तैयार — <strong>{tamanho}</strong>।",
    "scan_intro_frase": "ऐप आपके डिवाइस के किसी फ़ोल्डर में, उप-फ़ोल्डर सहित, <strong>EPUB</strong> और <strong>MOBI</strong> में पुस्तकें, <strong>CBZ</strong> और <strong>CBR</strong> में कॉमिक्स और <strong>M4B</strong> में ऑडियोबुक खोज सकता है।",
    "scan_intro_auto_frase": "अपनी शेल्फ़ जल्दी भरने के लिए, ऐप आपके डिवाइस के किसी फ़ोल्डर में, उप-फ़ोल्डर सहित, <strong>EPUB</strong> और <strong>MOBI</strong> में पुस्तकें, <strong>CBZ</strong> और <strong>CBR</strong> में कॉमिक्स और <strong>M4B</strong> में ऑडियोबुक खोज सकता है।",
    "n_livros_aguardando": {
      "one": "<strong>{n} पुस्तक</strong> की प्रगति और निशान सहेजे हुए हैं; वह फिर से आयात होने का इंतज़ार कर रही है।",
      "other": "<strong>{n} पुस्तकों</strong> की प्रगति और निशान सहेजे हुए हैं; वे फिर से आयात होने का इंतज़ार कर रही हैं।"
    },
    "fora_da_busca_titulo": "हम PDF, TXT, DOCX (Word), MD, MP3 और MP4 फ़ाइलें अपने-आप आयात नहीं करते",
    "fora_da_busca_texto": "ये प्रारूप हर तरह के दस्तावेज़ों के लिए इस्तेमाल होते हैं, केवल पुस्तकों के लिए नहीं। इन्हें बाहर रखने से शेल्फ व्यवस्थित रहती है। <strong>+ बटन से हर एक को स्वयं आयात किया जा सकता है।</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "आपकी स्थानीय लाइब्रेरी",
    "biblioteca": "लाइब्रेरी",
    "organizacao": "संगठन",
    "minhas_marcacoes": "मेरे निशान",
    "sistema": "सिस्टम",
    "sua_biblioteca": "आपकी लाइब्रेरी",
    "toque_em_um_livro_para_comecar_a_ler": "पढ़ना शुरू करने के लिए पुस्तक पर टैप करें।",
    "agrupar": "समूहित करें",
    "sua_estante_nao_tem_copia_de_seguranca": "आपकी शेल्फ का बैकअप नहीं है",
    "se_este_aparelho_se_perder_o_progresso": "यदि इस डिवाइस को कुछ हो जाए, तो प्रगति और निशान खो सकते हैं।",
    "agora_nao": "अभी नहीं",
    "nao_avisar_mais": "याद न दिलाएँ",
    "carregando": "लोड हो रहा है...",
    "estante": "शेल्फ",
    "lendo": "पढ़ रहे हैं",
    "favoritos": "पसंदीदा",
    "marcas": "निशान",
    "mais": "और",
    "neste_capitulo": "इस अध्याय में",
    "velocidade": "गति",
    "timer": "टाइमर",
    "marcar": "चिह्नित करें",
    "marcadores": "बुकमार्क",
    "personalizar_leitura": "पठन अनुकूलित करें",
    "as_preferencias_ficam_salvas_para_as_p": "प्राथमिकताएँ भविष्य के पठन के लिए सहेजी जाती हैं।",
    "tema": "थीम",
    "claro": "हल्का",
    "sepia": "सीपिया",
    "escuro": "गहरा",
    "oceano": "समुद्र",
    "tipografia": "टाइपफ़ेस",
    "texto": "पाठ",
    "tamanho": "आकार",
    "espacamento": "पंक्ति अंतराल",
    "margens": "मार्जिन",
    "cores_personalizadas_opcional": "कस्टम रंग (वैकल्पिक)",
    "fundo": "पृष्ठभूमि",
    "fonte": "पाठ रंग",
    "brilho": "चमक",
    "orientacao": "अभिविन्यास",
    "auto": "स्वतः",
    "retrato": "पोर्ट्रेट",
    "paisagem": "लैंडस्केप",
    "modo_de_leitura": "पठन मोड",
    "automatico": "स्वचालित",
    "horizontal": "क्षैतिज",
    "vertical": "लंबवत",
    "automatico_usa_rolagem_horizontal_para": "स्वचालित EPUB, MOBI, TXT और MD के लिए क्षैतिज पृष्ठ बदलाव तथा PDF और DOCX के लिए लंबवत स्क्रॉल का उपयोग करता है। पढ़ते समय बदलने पर, बदलाव केवल उसी पुस्तक के लिए सहेजा जाता है।",
    "quadrinhos": "कॉमिक्स",
    "como_a_pagina_aparece": "पृष्ठ कैसे फ़िट होता है",
    "pagina_inteira": "पूरा पृष्ठ",
    "largura_da_tela": "स्क्रीन चौड़ाई",
    "sentido_da_leitura": "पठन दिशा",
    "normal": "सामान्य →",
    "manga": "← मांगा",
    "revista_aberta_na_horizontal": "लैंडस्केप में दो-पृष्ठ दृश्य",
    "com_o_aparelho_deitado_mostra_duas_pag": "किनारे की ओर पकड़े जाने पर दो पृष्ठ साथ-साथ दिखते हैं — कवर अलग रहता है, जैसे असली कॉमिक खुलती है।",
    "normal_vira_da_esquerda_para_a_direita": "सामान्य बाएँ से दाएँ पलटता है। मांगा सब कुछ उलट देता है: स्वाइप, किनारे टैप और दो-पृष्ठ दृश्य में पृष्ठों का क्रम।",
    "gire_o_aparelho_para_a_horizontal_para": "एक साथ दो पृष्ठ देखने के लिए डिवाइस को किनारे की ओर घुमाएँ।",
    "dois_toques_ampliam_no_ponto_tocado_co": "डबल-टैप उस बिंदु पर ज़ूम करता है; ज़ूम होने पर, पृष्ठ पर घूमने के लिए खींचें। दो उँगलियों से पिंच भी काम करता है।",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "रीडर के शीर्ष पर स्क्रॉल बटन पृष्ठ-दर-पृष्ठ और सतत स्क्रॉल (वेबटून शैली) के बीच बदलता है। सतत स्क्रॉल में पृष्ठ एक में एक मिल जाते हैं, और ज़ूम पृष्ठ को चौड़ा करता है: आप किनारे की ओर स्क्रॉल करके उस पर चलते हैं।",
    "virada_de_pagina": "पृष्ठ पलटाव",
    "folha_real": "असली कागज़",
    "deslizar": "स्लाइड",
    "sem_animacao": "बिना एनिमेशन",
    "na_leitura_horizontal_arraste_a_pagina": "क्षैतिज पठन में, उँगली से मोड़ने के लिए पृष्ठ को उसके किनारे से खींचें। पलटाव रद्द करने के लिए बीच में छोड़ दें।",
    "ouvir_leitura": "सुनें",
    "continue_de_onde_parou_no_seu_ritmo": "जहाँ छोड़ा था वहीं से, अपनी गति से।",
    "livro": "पुस्तक",
    "pronto_para_comecar": "शुरू करने के लिए तैयार",
    "voz": "आवाज़",
    "escolha_uma_voz_disponivel_no_disposit": "इस डिवाइस पर उपलब्ध आवाज़ चुनें",
    "voz_padrao_do_sistema": "सिस्टम की डिफ़ॉल्ट आवाज़",
    "durante_a_reproducao": "चलते समय",
    "a_leitura_avanca_pagina_a_pagina_os_co": "पठन पृष्ठ-दर-पृष्ठ आगे बढ़ता है। ब्राउज़र समर्थन देने पर सिस्टम नियंत्रण दिखते हैं।",
    "organizar_livro": "पुस्तक व्यवस्थित करें",
    "estantes_colecoes_tags_e_status": "शेल्फ, संग्रह, टैग और स्थिति।",
    "cancelar": "रद्द करें",
    "salvar": "सहेजें",
    "grifos_citacoes_notas_e_marcadores_des": "इस पुस्तक के हाइलाइट, उद्धरण, नोट्स और बुकमार्क।",
    "sumario": "विषय-सूची",
    "toque_em_um_capitulo_para_ir_direto_ao": "सीधे जाने के लिए अध्याय पर टैप करें।",
    "sua_anotacao": "आपका नोट",
    "edite_ou_adicione_comentarios_ao_seu_t": "अपने अंश पर टिप्पणियाँ संपादित करें या जोड़ें।",
    "trecho": "अंश",
    "sua_nota": "आपका नोट",
    "salvar_nota": "नोट सहेजें",
    "agrupar_biblioteca": "लाइब्रेरी समूहित करें",
    "escolha_como_os_livros_serao_organizad": "चुनें कि शेल्फ पर पुस्तकें कैसे व्यवस्थित हों।",
    "ao_arrastar_um_livro_para_outra_posica": "किसी पुस्तक को दूसरी जगह खींचने पर, शेल्फ स्वचालित रूप से मेरे क्रम पर बदल जाती है और बनाया गया क्रम बनाए रखती है।",
    "backup_e_restauracao": "बैकअप और पुनर्स्थापन",
    "sua_estante_seu_progresso_e_suas_marca": "आपकी शेल्फ, प्रगति और निशान एक ही फ़ाइल में।",
    "escolha_uma_dimensao_para_explorar_sua": "अपनी लाइब्रेरी खोजने का तरीका चुनें।",
    "capitulos": "अध्याय",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "आवाज़ की पिच नहीं बदलती — वह न भारी होती है, न पतली। यह इस पुस्तक और आगे की पुस्तकों पर लागू होता है।",
    "ajuste_fino": "बारीक समायोजन",
    "timer_de_sono": "स्लीप टाइमर",
    "o_audio_diminui_de_volume_aos_poucos_e": "ऑडियो की आवाज़ धीरे-धीरे कम होती है और वह स्वचालित रूप से रुक जाता है।",
    "pontos_que_voce_guardou_neste_audioliv": "इस ऑडियोबुक में आपके सहेजे स्थान।",
    "ajustes_do_audio": "ऑडियो सेटिंग्स",
    "as_preferencias_ficam_salvas_para_todo": "ये प्राथमिकताएँ हर ऑडियोबुक के लिए सहेजी जाती हैं।",
    "botao_de_voltar": "पीछे जाने का बटन",
    "botao_de_avancar": "आगे जाने का बटन",
    "recuar_ao_retomar": "फिर शुरू करने पर पीछे",
    "depois_de_uma_pausa_longa_volta_alguns": "लंबे विराम के बाद, कुछ सेकंड पीछे जाता है ताकि आप सूत्र फिर पकड़ सकें।",
    "tocar_ao_abrir": "खोलते ही चलाएँ",
    "ao_tocar_em_um_audiolivro_na_estante_a": "शेल्फ पर ऑडियोबुक टैप करते ही प्लेबैक शुरू होता है।",
    "no_computador_espaco_toca_e_pausa_pula": "कंप्यूटर पर: space चलाता और रोकता है · ← → छोड़ते हैं · Shift + ← → अध्याय बदलते हैं · ↑ ↓ आवाज़ · B बुकमार्क · [ ] गति।",
    "converter_pdf_para_epub": "PDF को EPUB में बदलें",
    "prepare_o_livro_para_leitura_fluida_e": "पुस्तक को प्रवाहमय, समायोज्य पठन के लिए तैयार करें।",
    "confirmacao": "पुष्टि",
    "confirmar": "पुष्टि करें",
    "processando": "काम चल रहा है",
    "documento": "दस्तावेज़",
    "buscar_livros_no_dispositivo": "इस डिवाइस पर पुस्तकें खोजें",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "आपके डिवाइस पर पहले से सहेजी EPUB, MOBI, CBZ, CBR और M4B फ़ाइलें खोजें।",
    "juntar_em_um_unico_audiolivro": "एक ही ऑडियोबुक में मिलाएँ?",
    "titulo": "शीर्षक",
    "autor": "लेखक",
    "importar_separados": "अलग-अलग आयात करें",
    "bem_vindo_ao_veredas_reader": "Veredas Reader में आपका स्वागत है",
    "sua_biblioteca_de_leitura_inteiramente": "आपकी पठन लाइब्रेरी, पूरी तरह आपके डिवाइस पर।",
    "buscar": "खोजें",
    "importar_livro": "पुस्तक आयात करें",
    "buscar_titulo_autor_tag": "शीर्षक, लेखक, टैग खोजें...",
    "fechar_busca": "खोज बंद करें",
    "navegacao_da_biblioteca": "लाइब्रेरी नेविगेशन",
    "fechar_menu": "मेन्यू बंद करें",
    "agrupar_livros": "पुस्तकें समूहित करें",
    "voltar": "वापस",
    "marcar_pagina": "पृष्ठ चिह्नित करें",
    "personalizar": "अनुकूलित करें",
    "navegacao_principal": "मुख्य नेविगेशन",
    "acoes_do_trecho": "अंश क्रियाएँ",
    "amarelo": "पीला",
    "verde": "हरा",
    "rosa": "गुलाबी",
    "azul": "नीला",
    "player_de_audiolivro": "ऑडियोबुक प्लेयर",
    "minimizar_player": "प्लेयर छोटा करें",
    "minimizar": "छोटा करें",
    "video_em_reproducao": "वीडियो चल रहा है",
    "abrir_a_lista_de_capitulos": "अध्याय सूची खोलें",
    "posicao_no_audio": "ऑडियो में स्थान",
    "alternar_entre_o_progresso_do_capitulo": "अध्याय प्रगति और पूरी पुस्तक प्रगति के बीच बदलें",
    "capitulo_anterior": "पिछला अध्याय",
    "voltar_15_segundos": "15 सेकंड पीछे",
    "reproduzir": "चलाएँ",
    "avancar_30_segundos": "30 सेकंड आगे",
    "proximo_capitulo": "अगला अध्याय",
    "velocidade_de_reproducao": "प्लेबैक गति",
    "marcar_este_ponto": "यह स्थान चिह्नित करें",
    "ver_marcadores": "बुकमार्क देखें",
    "silenciar": "म्यूट करें",
    "volume": "आवाज़",
    "audiolivro_em_reproducao": "ऑडियोबुक चल रही है",
    "abrir_o_player": "प्लेयर खोलें",
    "fechar_o_player": "प्लेयर बंद करें",
    "fechar": "बंद करें",
    "trecho_anterior": "पिछला अंश",
    "iniciar_leitura": "ज़ोर से पढ़ना शुरू करें",
    "proximo_trecho": "अगला अंश",
    "escreva_seu_comentario_interpretacao_o": "अपनी टिप्पणी, व्याख्या या अनुस्मारक लिखें...",
    "cancelar_importacao": "आयात रद्द करें",
    "nome_do_audiolivro": "ऑडियोबुक का नाम",
    "nome_do_autor": "लेखक का नाम",
    "idioma": "भाषा",
    "idioma_do_aplicativo": "ऐप की भाषा",
    "o_aplicativo_segue_o_idioma_do_apare": "ऐप आपके डिवाइस की भाषा का पालन करता है। यदि आपकी भाषा अभी यहाँ नहीं है, तो यह अंग्रेज़ी में खुलता है।",
    "seguir_o_aparelho": "डिवाइस का पालन करें",
    "fazer_backup": "अभी बैकअप लें",
    "todos": "सभी",
    "lidos": "पूरी हुईं",
    "pausados": "रुकी हुईं",
    "autores": "लेखक",
    "tags": "टैग",
    "grifar": "हाइलाइट करें",
    "anotar": "नोट करें",
    "enviar": "भेजें",
    "restaurar_padroes": "डिफ़ॉल्ट बहाल करें",
    "voltar_para_1": "1× पर लौटें",
    "marcar_agora": "अभी चिह्नित करें",
    "escolher_pasta": "फ़ोल्डर चुनें",
    "juntar_em_um_audiolivro": "एक ऑडियोबुक में मिलाएँ",
    "sobre": "परिचय",
    "licencas_de_codigo_aberto": "ओपन-सोर्स लाइसेंस",
    "configuracoes": "सेटिंग्स",
    "temas_e_idioma": "थीम और भाषा"
  },
  "aviso": {
    "idioma_trocado": "भाषा बदल गई।"
  },
  "vn": {
    "quem_le": "कौन पढ़े",
    "natural": "प्राकृतिक",
    "do_sistema": "सिस्टम",
    "nota_sistema": "आपके डिवाइस पर इंस्टॉल की गई आवाज़ों का उपयोग करता है। ज़्यादा इंसानी आवाज़ में पढ़ने के लिए प्राकृतिक चुनें।",
    "nota_sistema_com_natural": "प्राकृतिक आवाज़ अब भी डाउनलोड है। जब चाहें, प्राकृतिक पर वापस जाएँ।",
    "voz_natural": "प्राकृतिक आवाज़",
    "gerada_no_aparelho": "कहीं ज़्यादा इंसानी आवाज़, जो सीधे आपके डिवाइस पर बनती है।",
    "progresso_download": "डाउनलोड की प्रगति",
    "x_de_y": "{y} में से {x}",
    "aviso_arquivo": "प्राकृतिक आवाज़ के लिए Veredas को ऐप के पते से खोलना ज़रूरी है, कंप्यूटर पर फ़ाइल के रूप में नहीं। तब तक पढ़ने के लिए सिस्टम की आवाज़ का उपयोग होगा।",
    "aviso_navegador": "इस ब्राउज़र में वे सुविधाएँ नहीं हैं जिनकी प्राकृतिक आवाज़ को ज़रूरत है। पढ़ना सिस्टम की आवाज़ में जारी रहेगा।",
    "verificando": "प्राकृतिक आवाज़ की जाँच हो रही है…",
    "fato_download": "{tamanho} का एक बार का डाउनलोड। उसके बाद यह बिना इंटरनेट के चलती है।",
    "fato_wifi": "Wi-Fi बेहतर रहेगा। आप इसे रोककर बाद में जारी रख सकते हैं।",
    "fato_privacidade": "पुस्तक का पाठ कभी आपके डिवाइस से बाहर नहीं जाता।",
    "fato_idiomas": "31 भाषाएँ बोलती है, जिनमें हिंदी, अंग्रेज़ी और पुर्तगाली शामिल हैं। बाकी भाषाओं के लिए सिस्टम की आवाज़ ही चलती रहेगी।",
    "baixar_voz_natural": "प्राकृतिक आवाज़ डाउनलोड करें ({tamanho})",
    "licenca_curta": "Supertone का Supertonic 3 मॉडल, OpenRAIL-M लाइसेंस के तहत। विवरण परिचय > ओपन-सोर्स लाइसेंस में।",
    "pode_continuar_usando": "डाउनलोड के दौरान आप पढ़ना जारी रख सकते हैं। कनेक्शन टूटने पर डाउनलोड वहीं से जारी होगा जहाँ रुका था।",
    "pausar_download": "डाउनलोड रोकें",
    "erro_espaco": "डाउनलोड पूरा करने के लिए डिवाइस पर पर्याप्त जगह नहीं है। थोड़ी जगह खाली करें और फिर प्रयास करें।",
    "erro_offline": "अभी इंटरनेट नहीं है। जितना डाउनलोड हो चुका है, वह सुरक्षित है।",
    "erro_rede": "डाउनलोड के बीच कनेक्शन टूट गया। जितना डाउनलोड हो चुका है, वह सुरक्षित है।",
    "download_pausado": "डाउनलोड रुका हुआ है। जितना डाउनलोड हो चुका है, वह सुरक्षित है।",
    "continuar_download": "जारी रखें",
    "descartar": "रद्द करें",
    "voz_feminina": "महिला",
    "voz_feminina_desc": "कोमल और शांत",
    "voz_masculina": "पुरुष",
    "voz_masculina_desc": "आत्मीय और सौम्य",
    "parar_amostra": "नमूना रोकें",
    "ouvir_amostra_de": "नमूना सुनें: {voz}",
    "escolha_a_voz": "आवाज़ चुनें",
    "qualidade": "गुणवत्ता",
    "q_auto": "स्वचालित",
    "q_rapida": "तेज़",
    "q_maxima": "सर्वोत्तम",
    "q_auto_desc": "आपके डिवाइस के प्रदर्शन के अनुसार अपने-आप ढल जाती है, ताकि पढ़ना बिना रुकावट चले।",
    "q_rapida_desc": "आवाज़ जल्दी बनाती है। साधारण डिवाइस के लिए अच्छी।",
    "q_maxima_desc": "सबसे निखरी हुई ध्वनि। साधारण डिवाइस पर वाक्यों के बीच ठहराव आ सकते हैं।",
    "ocupa": "इस डिवाइस पर {tamanho} जगह लेती है",
    "remover": "हटाएँ",
    "baixar_pelos_dados": "मोबाइल डेटा से डाउनलोड करें?",
    "baixar_pelos_dados_msg": "लगता है आपका डिवाइस Wi-Fi पर नहीं है। डाउनलोड {tamanho} का है और आपके डेटा प्लान से खर्च हो सकता है।",
    "baixar_agora": "फिर भी डाउनलोड करें",
    "pronta": "प्राकृतिक आवाज़ तैयार है।",
    "download_interrompido": "डाउनलोड रुक गया। जब चाहें, जारी रखें दबाएँ।",
    "remover_titulo": "प्राकृतिक आवाज़ हटाएँ?",
    "descartar_titulo": "डाउनलोड रद्द करें?",
    "remover_msg": "इससे {tamanho} जगह खाली होगी। पढ़ना सिस्टम की आवाज़ पर लौट आएगा, और आप जब चाहें इसे फिर से डाउनलोड कर सकते हैं।",
    "descartar_msg": "जितना डाउनलोड हो चुका है, वह मिटा दिया जाएगा।",
    "removida": "प्राकृतिक आवाज़ इस डिवाइस से हटा दी गई।",
    "amostra_falhou": "इस डिवाइस पर नमूना नहीं चल सका।",
    "amostra": "नमस्ते! प्राकृतिक आवाज़ में आपकी पुस्तकें कुछ ऐसी सुनाई देंगी।",
    "gerando_voz": "आवाज़ तैयार हो रही है…",
    "automatico_idioma": "स्वचालित ({idioma})",
    "automatico": "स्वचालित",
    "so_voz_do_sistema": "सिस्टम की आवाज़",
    "aviso_idioma": "पाठ की भाषा: {idioma}। प्राकृतिक आवाज़ अभी यह भाषा नहीं बोलती, इसलिए पुस्तक सिस्टम की आवाज़ में पढ़ी जाएगी।",
    "aviso_idioma_desconhecido": "इस पाठ की भाषा पहचानी नहीं जा सकी। प्राकृतिक आवाज़ का उपयोग करने के लिए नीचे भाषा चुनें।",
    "aviso_falha": "प्राकृतिक आवाज़ अभी इस डिवाइस पर नहीं चल सकी। पढ़ना सिस्टम की आवाज़ में जारी है।",
    "nao_carregou_usando_sistema": "प्राकृतिक आवाज़ इस डिवाइस पर लोड नहीं हुई। सिस्टम की आवाज़ में पढ़ रहे हैं।",
    "parou_usando_sistema": "प्राकृतिक आवाज़ रुक गई। सिस्टम की आवाज़ में जारी रख रहे हैं।",
    "aparelho_lento": "यह डिवाइस आवाज़ धीरे बना रहा है। ठहराव से बचने के लिए तेज़ गुणवत्ता चुनें।",
    "idioma_do_texto": "पाठ की भाषा",
    "idioma_do_texto_dica": "पाठ से ही पहचानी गई। उच्चारण गलत लगे तो इसे बदलें।",
    "leitura_em_voz_alta": "ज़ोर से पढ़ना",
    "lento_usando_sistema": "इस डिवाइस पर प्राकृतिक आवाज़ बहुत धीमी है। पढ़ना सिस्टम की आवाज़ से जारी रहेगा।",
    "aviso_lento": "यह डिवाइस पढ़ने की रफ़्तार से प्राकृतिक आवाज़ नहीं बना पा रहा, इसलिए अभी सिस्टम की आवाज़ पढ़ रही है।",
    "sem_memoria_usando_sistema": "इस डिवाइस की मेमोरी में प्राकृतिक आवाज़ नहीं समाई। सिस्टम की आवाज़ से पढ़ा जा रहा है।",
    "aviso_falha_memoria": "इस डिवाइस पर प्राकृतिक आवाज़ के लिए पर्याप्त मेमोरी नहीं थी। दूसरे ऐप्स बंद करके दोबारा कोशिश करने से आमतौर पर काम बन जाता है; तब तक सिस्टम की आवाज़ पढ़ेगी।",
    "copiar_detalhe": "विवरण कॉपी करें",
    "copiado": "विवरण कॉपी हो गया।",
    "falhou_titulo": "इस डिवाइस पर प्राकृतिक आवाज़ लोड नहीं हुई।",
    "falhou_texto": "डिवाइस प्राकृतिक आवाज़ तैयार नहीं कर पाया। पढ़ना सिस्टम की आवाज़ से जारी है। मदद के लिए नीचे दिया विवरण कॉपी करके सपोर्ट को भेजें।",
    "falhou_memoria_texto": "इस डिवाइस पर प्राकृतिक आवाज़ के लिए मेमोरी कम पड़ गई। दूसरे ऐप्स बंद करके दोबारा कोशिश करने से आमतौर पर काम बन जाता है।",
    "tentar_de_novo": "फिर कोशिश करें",
    "tentando": "लोड हो रहा है…",
    "aviso_aparelho_justo": "इस डिवाइस में प्राकृतिक आवाज़ के लिए मेमोरी कम है। हो सकता है वह लोड न हो; ऐसे में उसे हटाकर जगह वापस पा सकते हैं।",
    "preparando_demora": "आवाज़ तैयार की जा रही है। इसमें कुछ मिनट लग सकते हैं।",
    "incompativel_titulo": "इस डिवाइस पर प्राकृतिक आवाज़ काम नहीं करती।",
    "incompativel_memoria": "इसे तैयार करने के लिए पर्याप्त मेमोरी नहीं थी। पढ़ना सिस्टम की आवाज़ से होगा, जिसके विकल्प नीचे हैं।",
    "incompativel_lento": "यह पढ़ने की रफ़्तार के साथ नहीं चल पाई। पढ़ना सिस्टम की आवाज़ से होगा, जिसके विकल्प नीचे हैं।",
    "incompativel_queda": "लोड होते समय ऐप बंद हो गया। पढ़ना सिस्टम की आवाज़ से होगा, जिसके विकल्प नीचे हैं।",
    "incompativel_falha": "यह यहाँ लोड नहीं हो सकी। पढ़ना सिस्टम की आवाज़ से होगा, जिसके विकल्प नीचे हैं।",
    "testar_de_novo": "फिर से जाँचें",
    "remover_e_liberar": "हटाएँ और {tamanho} खाली करें",
    "tela_durante_a_leitura": "पढ़ते समय स्क्रीन",
    "manter_tela_ligada": "स्क्रीन चालू रखें",
    "manter_tela_ligada_dica": "किताब खुली रहने तक स्क्रीन अपने आप बंद नहीं होगी। किताब बंद करते ही सब सामान्य हो जाता है।"
  }
});