/* ============================================================
   ITALIANO — traduzione completa
   ------------------------------------------------------------
   Le chiavi sono identiche a pt-BR.js e en.js.
   ============================================================ */
Idiomas.registrar('it', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "Segnalibro eliminato.",
    "excluir_marcador": "Elimina segnalibro",
    "o_marcador_sera_removido_permanentemen": "Il segnalibro verrà eliminato definitivamente.",
    "excluir_marcador_2": "Eliminare il segnalibro?",
    "pagina_salva": "Pagina salvata",
    "anotacoes": "Note",
    "citacoes": "Citazioni",
    "item_excluido": "Elemento eliminato.",
    "este_registro_sera_removido_permanente": "Questa voce verrà eliminata definitivamente dalla biblioteca.",
    "configuracoes_padrao_restauradas": "Impostazioni predefinite ripristinate.",
    "leitura_da_esquerda_para_a_direita": "Lettura da sinistra a destra.",
    "leitura_da_direita_para_a_esquerda_man": "Lettura da destra a sinistra (manga).",
    "a_pagina_inteira_passa_a_caber_na_tela": "Ora l’intera pagina entra nello schermo.",
    "a_pagina_passa_a_ocupar_toda_a_largura": "La pagina ora occupa tutta la larghezza dello schermo.",
    "virada_sem_animacao_ativada": "Cambio pagina senza animazione attivato.",
    "virada_deslizante_ativada": "Cambio pagina a scorrimento attivato.",
    "virada_em_folha_real_ativada": "Cambio pagina a foglio reale attivato.",
    "padrao_automatico_cada_formato_abre_no": "Automatico: ogni formato si apre nel verso più adatto.",
    "mudando_durante_a_leitura_o_ajuste_fic": "Se lo cambi durante la lettura, la modifica viene applicata solo a questo libro.",
    "automatico_usa_rolagem_horizontal_para": "Automatico usa la paginazione orizzontale per EPUB, MOBI, TXT, MD e fumetti, e lo scorrimento verticale per PDF e DOCX.",
    "este_livro": "questo libro",
    "armazenamento_local_indisponivel_neste": "Lo spazio di archiviazione locale non è disponibile in questo browser.",
    "o_aplicativo_pode_procurar_os_livros_q": "L’app può cercare i libri già presenti sul dispositivo.",
    "vamos_montar_sua_estante": "Vuoi riempire il tuo scaffale?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "Senza il tuo consenso, l’app non può essere utilizzata.",
    "precisamos_do_seu_aceite": "Abbiamo bisogno del tuo consenso",
    "antes_de_comecar_leia_e_aceite_os_docu": "Prima di iniziare, leggi e accetta i documenti riportati di seguito.",
    "selecionar_todos": "Seleziona tutto",
    "limpar_selecao": "Cancella selezione",
    "todos_parecem_ja_estar_na_sua_estante": "Sembra che siano già tutti sul tuo scaffale.",
    "lendo_a_pasta_escolhida": "Lettura della cartella scelta…",
    "procurando_livros": "Ricerca di libri",
    "nao_foi_possivel_concluir_a_busca_no_d": "Non è stato possibile completare la ricerca sul dispositivo.",
    "tente_outra_pasta_do_aparelho": "Prova un’altra cartella del dispositivo.",
    "nenhum_livro_encontrado": "Nessun libro trovato",
    "use_o_botao_para_escolher_os_arquivos": "Usa il pulsante + per scegliere manualmente i file. Sui telefoni Android, Chrome di solito consente di scegliere un’intera cartella.",
    "seu_navegador_nao_permite_ler_pastas": "Il browser non può leggere le cartelle",
    "busca_automatica_indisponivel": "Ricerca automatica non disponibile",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR e M4B",
    "termos_de_uso": "Termini di utilizzo",
    "politica_de_privacidade": "Informativa sulla privacy",
    "um_minuto_agora_evita_perder_o_progres": "Un minuto adesso evita di perdere in seguito i tuoi progressi e le tue annotazioni.",
    "ver_estante": "Vedi scaffale",
    "modo_juntar": "Modalità unione",
    "modo_substituir": "Modalità sostituzione",
    "restauracao_concluida": "Ripristino completato",
    "tente_de_novo_com_o_arquivo_original": "Riprova con il file originale.",
    "a_restauracao_nao_pode_ser_concluida": "Impossibile completare il ripristino",
    "devolvendo_o_seu_progresso_e_as_suas_m": "Ripristino dei progressi e delle annotazioni...",
    "restaurar_este_backup": "Ripristinare questo backup?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Scegli il file .zip salvato da Veredas o il .txt ricevuto tramite condivisione.",
    "nao_foi_possivel_ler_este_arquivo": "Impossibile leggere questo file",
    "lendo_o_backup": "Lettura del backup",
    "backup_do_veredas_reader": "Backup di Veredas Reader",
    "arquivo_de_transporte_txt_contendo_os": "copia del backup in formato .txt, con lo stesso contenuto dello ZIP",
    "nao_foi_possivel_montar_o_arquivo_de_b": "Impossibile creare il file di backup.",
    "escolher_o_app": "Scegli app",
    "vale_conferir_o_que_vai_no_arquivo": "Controlla cosa contiene il file",
    "enviar_para_outro_app": "Invia a un’altra app",
    "salvar_o_arquivo": "Salva il file",
    "o_navegador_aqui_nao_oferece_o_compart": "Questo browser non offre la condivisione diretta. Puoi salvare il file e inviarlo in seguito con l’app che preferisci.",
    "este_aparelho_nao_abre_a_lista_de_apli": "Questo dispositivo non apre l’elenco delle app",
    "importe_pelo_menos_um_livro_antes_de_f": "Importa almeno un libro prima di creare un backup.",
    "estante_vazia": "Scaffale vuoto",
    "nao_deu_para_copiar": "Impossibile copiare",
    "copiar_detalhes": "Copia dettagli",
    "o_backup_foi_salvo_assim_mesmo": "Il backup è stato comunque salvato",
    "o_aparelho_recusou_abrir_a_lista": "Impossibile aprire l’elenco di condivisione",
    "sem_detalhes_do_navegador": "nessun dettaglio del browser",
    "o_sistema_nao_aceitou_receber_o_arquiv": "Il sistema del dispositivo non è riuscito a ricevere il file.",
    "o_navegador_considerou_a_situacao_inse": "Il browser ha bloccato la condivisione per una sua regola di sicurezza. Salva il file e invialo con l’app che preferisci.",
    "o_compartilhamento_so_funciona_em_ende": "La condivisione funziona solo con indirizzi sicuri. Questa app viene aperta da un normale indirizzo http:// e, in questo caso, il browser blocca l’invio ad altre app.",
    "este_navegador_nao_conseguiu_iniciar_o": "Questo browser non è riuscito ad aprire la condivisione. Salva il file e invialo con l’app che preferisci.",
    "o_navegador_recebeu_um_arquivo_em_form": "Il browser non ha aperto l’elenco delle app con cui condividere. Tocca di nuovo il pulsante oppure salva il file e invialo con l’app che preferisci.",
    "nao_foi_possivel_gerar_o_backup": "Impossibile creare il backup.",
    "reunindo_a_sua_estante": "Raccolta del tuo scaffale...",
    "preparando_o_backup": "Preparazione del backup",
    "pronto_nada_mais_esta_esperando": "Fatto: non c’è più nulla in attesa.",
    "o_progresso_e_as_marcacoes_desses_livr": "I progressi e le annotazioni di questi libri verranno cancellati. Se importi i file in seguito, torneranno senza annotazioni.",
    "descartar_o_que_esta_esperando": "Eliminare i dati in attesa?",
    "lembretes_de_backup_religados": "Promemoria di backup riattivati.",
    "sem_titulo": "Senza titolo",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "Promemoria disattivati.",
    "manter_ligado": "Mantienili attivi",
    "desligar_assim_mesmo": "Disattivali comunque",
    "o_botao_de_salvar_continua_onde_sempre": "Il pulsante Salva rimane dove è sempre stato, in Backup e ripristino.",
    "o_lembrete_e_o_unico_aviso_que_existe": "Il promemoria è l’unico avviso. Senza promemoria, dovrai ricordarti tu di fare il backup.\n\n",
    "limpar_os_dados_do_navegador_desinstal": "Se i dati del browser vengono cancellati, l’app viene disinstallata, cambi telefono o il dispositivo si guasta, non sarà possibile recuperare progressi, evidenziazioni, citazioni, note e segnalibri.\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "Il tuo scaffale esiste solo su questo dispositivo. Non c’è alcuna copia su un server, quindi non c’è modo di recuperarlo per te.\n\n",
    "leia_antes_de_confirmar": "Leggi prima di confermare",
    "desligar_os_lembretes_de_backup": "Disattivare i promemoria di backup?",
    "progresso_de_leitura_restaurado_neste": "Progressi di lettura ripristinati per questo libro.",
    "pronto": "Fatto.",
    "aplicando_as_suas_preferencias": "Applicazione delle tue preferenze...",
    "atualize_o_veredas_reader_e_tente_de_n": "Aggiorna Veredas Reader e riprova.",
    "este_backup_foi_feito_numa_versao_mais": "Questo backup è stato creato con una versione più recente dell’app.",
    "este_arquivo_nao_e_um_backup_de_biblio": "Questo file non è un backup della libreria Veredas.",
    "o_conteudo_interno_nao_pode_ser_lido": "Non è stato possibile leggere il contenuto interno.",
    "o_backup_esta_corrompido": "Il backup è danneggiato.",
    "falta_o_arquivo_biblioteca_json_la_den": "Manca il file biblioteca.json al suo interno.",
    "este_arquivo_nao_parece_ser_um_backup": "Questo file non sembra essere un backup di Veredas.",
    "compactando": "Compressione...",
    "para_restaurar_menu_lateral_backup_e_r": "Per ripristinare: menu laterale > Backup e ripristino > Ripristina backup.",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas ripristina automaticamente le annotazioni e il punto in cui ti eri fermato.",
    "importe_os_livros_normalmente_no_aplic": "importa normalmente i libri nell’app: quando riconosce ogni file,",
    "ele_nao_contem_os_arquivos_dos_livros": "NON contiene i file dei libri. Per ripristinare completamente,",
    "as_notas_os_marcadores_e_a_organizacao": "le tue note, i tuoi segnalibri e l’organizzazione del tuo scaffale.",
    "este_arquivo_guarda_o_seu_progresso_de": "Questo file contiene i tuoi progressi di lettura, le evidenziazioni e le citazioni,",
    "verificando_se_sao_partes_do_mesmo_aud": "Verifica se sono parti dello stesso audiolibro...",
    "analisando_os_arquivos": "Analisi dei file",
    "nao_foi_possivel_salvar_o_audiolivro": "Impossibile salvare l’audiolibro.",
    "audiolivros_grandes_podem_levar_alguns": "Gli audiolibri grandi possono richiedere qualche istante...",
    "salvando_na_sua_estante": "Salvataggio sul tuo scaffale",
    "falha_ao_processar_os_arquivos": "Impossibile elaborare i file.",
    "falha_ao_processar_o_arquivo": "Impossibile elaborare il file.",
    "nao_foi_possivel_salvar_o_quadrinho": "Impossibile salvare il fumetto.",
    "quase_la": "Ci siamo quasi...",
    "falha_ao_processar_o_quadrinho": "Impossibile elaborare il fumetto.",
    "autor_desconhecido": "Autore sconosciuto",
    "lendo_o_quadrinho": "Lettura del fumetto...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "Impossibile salvare il libro nella biblioteca.",
    "nao_foi_possivel_ler_o_pdf": "Impossibile leggere il PDF.",
    "lendo_o_pdf": "Lettura del PDF...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "Se è un vecchio .doc, aprilo in Word e salvalo come .docx prima di importarlo.",
    "este_arquivo_nao_e_um_docx_valido": "Questo file non è un .docx valido.",
    "livros_com_protecao_da_amazon_nao_pode": "I libri con protezione Amazon non possono essere aperti qui. Usa una copia senza DRM oppure converti il libro in EPUB.",
    "este_arquivo_esta_protegido_por_drm": "Questo file è protetto da DRM.",
    "confira_se_a_extensao_corresponde_ao_c": "Controlla che l’estensione corrisponda al contenuto oppure converti il libro in EPUB.",
    "este_arquivo_nao_e_um_mobi_valido": "Questo file non è un MOBI valido.",
    "nao_foi_possivel_ler_o_arquivo": "Impossibile leggere il file.",
    "formato_nao_suportado": "Formato non supportato.",
    "falha_ao_salvar_o_livro_na_biblioteca": "Impossibile salvare il libro nella biblioteca.",
    "livro_importado_e_salvo_no_dispositivo": "Libro importato e salvato su questo dispositivo.",
    "audiolivro_importado_e_salvo_no_dispos": "Audiolibro importato e salvato su questo dispositivo.",
    "quadrinho_importado_e_salvo_no_disposi": "Fumetto importato e salvato su questo dispositivo.",
    "salvando_na_sua_estante_2": "Salvataggio sul tuo scaffale...",
    "importando_livro": "Importazione del libro",
    "importar_mesmo_assim": "Importa comunque",
    "parece_que_este_livro_ja_esta_na_estan": "Sembra che questo libro sia già sul tuo scaffale",
    "este_livro_ja_esta_na_estante": "Questo libro è già sul tuo scaffale",
    "video_importado_e_salvo_no_dispositivo": "Video importato e salvato su questo dispositivo.",
    "importacao_cancelada": "Importazione annullata.",
    "preparando_o_arquivo": "Preparazione del file",
    "importando_audiolivro": "Importazione dell’audiolibro",
    "importacao_concluida": "Importazione completata",
    "importacao_interrompida": "Importazione interrotta",
    "a_importacao_foi_interrompida_o_que_ja": "L’importazione è stata interrotta; ciò che era già stato aggiunto rimane sul tuo scaffale.",
    "finalizando": "Finalizzazione…",
    "nao_foi_possivel_ler_o_arquivo_2": "impossibile leggere il file",
    "importando_livros": "Importazione dei libri",
    "livros_quadrinhos_documentos_audiolivr": "Libri, fumetti, documenti, audiolibri e video",
    "series": "Serie",
    "colecoes": "Collezioni",
    "organizacao_salva": "Organizzazione salvata.",
    "informe_um_nome_para_o_livro_antes_de": "Dai un nome al libro prima di salvarlo.",
    "nome_do_livro_obrigatorio": "Il libro deve avere un nome",
    "importe_um_livro_primeiro": "Importa prima un libro.",
    "citacao": "citazione",
    "anotacao": "nota",
    "citacao_2": "Citazione",
    "anotacao_2": "Nota",
    "uma_citacao": "una citazione",
    "uma_anotacao": "una nota",
    "o_marcador_sera_removido_da_biblioteca": "Il segnalibro verrà rimosso dalla biblioteca, ma il file del libro resterà intatto.",
    "marcador_de_audio": "Segnalibro audio",
    "marcador_de_video": "Segnalibro video",
    "nao_foi_possivel_excluir_o_livro": "Impossibile eliminare il libro.",
    "livro_excluido_da_biblioteca": "Libro eliminato dalla biblioteca.",
    "excluir_livro": "Elimina libro",
    "isso_remove_apenas_a_copia_armazenada": "Rimuove solo la copia conservata dalla biblioteca, insieme a progressi, segnalibri e note. Il file originale nella tua cartella non verrà eliminato.",
    "excluir_livro_2": "Eliminare il libro?",
    "ordem_personalizada_salva": "Ordine personalizzato salvato.",
    "ordem_manual_da_sua_estante": "Il tuo scaffale, nell’ordine che hai impostato.",
    "agrupamento_alterado_para_minha_ordem": "Raggruppamento impostato su Il mio ordine.",
    "nova_ordem_salva": "Nuovo ordine salvato.",
    "nao_foi_possivel_salvar_a_nova_ordem": "Impossibile salvare il nuovo ordine.",
    "baixar_automaticamente": "Scarica automaticamente",
    "escolha_livremente_onde_o_arquivo_sera": "Scegli liberamente dove verrà salvato il file.",
    "salvar_epub": "Salva EPUB",
    "livro_epub": "Libro EPUB",
    "erro_desconhecido": "errore sconosciuto",
    "a_permissao_para_salvar_o_arquivo_foi": "L’autorizzazione a salvare il file è stata annullata. Nulla è cambiato nella biblioteca.",
    "conversao_cancelada_o_pdf_original_per": "Conversione annullata. Il PDF originale rimane nella biblioteca.",
    "preparando_salvamento": "Preparazione al salvataggio…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "La copia del PDF non è disponibile nella biblioteca.",
    "reconstruindo_o_livro_localmente": "Ricostruzione del libro sul dispositivo.",
    "convertendo_pdf": "Conversione del PDF",
    "nao_foi_possivel_compartilhar_o_livro": "Impossibile condividere il libro.",
    "o_arquivo_foi_preparado_para_voce_comp": "Il file è pronto per essere condiviso in un’altra app.",
    "livro_compartilhado": "Libro condiviso.",
    "a_copia_deste_livro_nao_esta_disponive": "La copia di questo libro non è disponibile nella biblioteca.",
    "para_manter_a_politica_de_compartilham": "Per rispettare la politica di condivisione della biblioteca, questa app non consente di condividere file EPUB e MOBI.",
    "quadrinhos_ficam_guardados_somente_no": "I fumetti sono conservati solo sul dispositivo e non possono essere condivisi da questa app.",
    "audiolivros_e_videos_ficam_guardados_s": "Audiolibri e video sono conservati solo sul dispositivo e non possono essere condivisi da questa app.",
    "formato_protegido": "Formato protetto",
    "compartilhamento_indisponivel": "Condivisione non disponibile",
    "concluido": "Completato",
    "ainda_nao_comecado": "Non ancora iniziato",
    "continue_lendo": "Continua a leggere",
    "continue_ouvindo": "Continua ad ascoltare",
    "continue_assistindo": "Continua a guardare",
    "comece_por_aqui": "Inizia qui",
    "comece_a_ouvir": "Inizia ad ascoltare",
    "comece_a_assistir": "Inizia a guardare",
    "no_total": "complessivamente",
    "para_ler": "da leggere",
    "sua_estante": "Il tuo scaffale",
    "livros_organizados_pela_opcao_selecion": "Libri organizzati secondo l’opzione scelta.",
    "uma_prateleira_para_cada_tipo_de_arqui": "Uno scaffale per ogni tipo di file.",
    "autores_agrupados_em_ordem_alfabetica": "Autori raggruppati in ordine alfabetico.",
    "toque_para_continuar_de_onde_parou": "Tocca per riprendere da dove avevi lasciato.",
    "para_ler_2": "Da leggere",
    "lendo_agora": "In lettura",
    "audio_e_video": "Audio e video",
    "trechos_salvos_separadamente_dos_marca": "Passaggi salvati separatamente dai segnalibri.",
    "comentarios_vinculados_a_trechos_selec": "Commenti collegati ai passaggi selezionati.",
    "paginas_salvas_para_voltar_rapidamente": "Pagine salvate per tornare rapidamente.",
    "do_maior_para_o_menor_progresso_de_lei": "Dal progresso di lettura maggiore al minore.",
    "livros_adicionados_ou_lidos_mais_recen": "Libri aggiunti o letti più di recente.",
    "ordem_alfabetica_pelo_titulo": "In ordine alfabetico per titolo.",
    "separa_em_prateleiras_de_epub_pdf_docx": "Divide in scaffali EPUB, PDF, DOCX, audiolibri, video…",
    "tipo_de_arquivo": "Tipo di file",
    "organiza_e_separa_os_livros_por_autor": "Organizza e separa i libri per autore.",
    "agrupar_por_autor": "Raggruppa per autore",
    "pressione_o_livro_e_mova_o": "Tieni premuto un libro, poi spostalo.",
    "minha_ordem": "Il mio ordine",
    "epub_pronto": "EPUB pronto",
    "conversao_concluida": "Conversione completata",
    "necessario_para_salvar_o_epub_ao_lado": "Necessario per salvare l’EPUB accanto all’originale",
    "escolha_a_pasta_do_pdf": "Scegli la cartella del PDF",
    "processando": "Elaborazione…",
    "processamento_local_no_navegador": "Elaborato sul dispositivo, nel browser",
    "convertendo_livro": "Conversione del libro",
    "livro_em_pdf": "Libro PDF",
    "recalculando_paginas": "Ricalcolo delle pagine...",
    "ajustando_leitura": "Regolazione del layout",
    "abrir_comentario": "Apri commento",
    "anotacao_salva": "Nota salvata.",
    "anotacao_atualizada": "Nota aggiornata.",
    "escreva_uma_nota_antes_de_salvar": "Scrivi una nota prima di salvarla.",
    "nao_foi_possivel_compartilhar": "Impossibile condividere.",
    "compartilhamento_indisponivel_2": "Condivisione non disponibile.",
    "trecho_copiado": "Passaggio copiato.",
    "trecho_compartilhado": "Passaggio condiviso.",
    "citacao_salva": "Citazione salvata.",
    "trecho_grifado": "Passaggio evidenziato.",
    "grifo_removido": "Evidenziazione rimossa.",
    "comentario_apagado": "Commento eliminato.",
    "remover_grifo": "Rimuovi evidenziazione",
    "apagar_comentario": "Elimina commento",
    "remover_grifo_2": "Rimuovere l’evidenziazione?",
    "apagar_comentario_2": "Eliminare il commento?",
    "remover_este_grifo": "Rimuovere questa evidenziazione?",
    "apagar_este_comentario": "Eliminare questo commento?",
    "sem_comentario": "Nessun commento",
    "comentario": "Commento",
    "marcador_removido_desta_pagina": "Segnalibro rimosso da questa pagina.",
    "pagina_adicionada_aos_marcadores": "Pagina aggiunta ai tuoi segnalibri.",
    "este_e_o_inicio_do_livro": "Questo è l’inizio del libro.",
    "esta_e_a_primeira_pagina": "Questa è la prima pagina.",
    "voce_chegou_ao_fim_do_livro": "Hai raggiunto la fine del libro.",
    "voce_chegou_ao_fim_do_quadrinho": "Hai raggiunto la fine del fumetto.",
    "agora_em_revista_aberta_duas_paginas_l": "Ora in doppia pagina: due pagine affiancate, con la copertina da sola.",
    "leitura_horizontal_ativada_neste_livro": "La lettura orizzontale è attiva per questo libro.",
    "rolagem_vertical_ativada_neste_livro": "Lo scorrimento verticale è attivo per questo libro.",
    "leitura_pagina_a_pagina_ativada_neste": "La lettura pagina per pagina è attiva per questo fumetto.",
    "rolagem_continua_ativada_neste_quadrin": "Lo scorrimento continuo è attivo per questo fumetto.",
    "mudar_para_rolagem_vertical": "Passa allo scorrimento verticale",
    "mudar_para_leitura_horizontal": "Passa alla lettura orizzontale",
    "rolagem_continua_estilo_webtoon": "Scorrimento continuo (stile webtoon)",
    "voltar_para_pagina_a_pagina": "Torna alla lettura pagina per pagina",
    "separando_os_capitulos": "Separazione dei capitoli...",
    "lendo_o_livro": "Lettura del libro",
    "lendo_o_markdown": "Lettura del Markdown",
    "lendo_o_documento": "Lettura del documento",
    "pagina_indisponivel": "Pagina non disponibile.",
    "isto_acontece_so_desta_vez": "Succede solo questa volta.",
    "preparando_o_quadrinho": "Preparazione del fumetto",
    "abrindo_o_quadrinho": "Apertura del fumetto...",
    "montando_as_paginas": "Creazione delle pagine...",
    "nao_foi_possivel_abrir_este_livro": "Impossibile aprire questo libro.",
    "abertura_cancelada": "Apertura annullata.",
    "o_livro_demorou_demais_para_abrir_e_fo": "Il libro ha impiegato troppo tempo ad aprirsi e l’operazione è stata interrotta.",
    "importe_o_arquivo_novamente_para_conti": "Importa di nuovo il file per continuare a leggere.",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "Il file di questo libro non è più salvato sul dispositivo.",
    "preparando_sua_leitura": "Preparazione della lettura...",
    "abrindo_livro": "Apertura del libro",
    "leitura_concluida": "Lettura terminata.",
    "a_voz_foi_interrompida_pelo_navegador": "Il browser ha interrotto la voce.",
    "nao_foi_possivel_preparar_este_trecho": "Impossibile preparare questo passaggio per l’audio.",
    "a_leitura_em_voz_alta_nao_e_suportada": "La lettura ad alta voce non è supportata da questo browser.",
    "pausar_leitura": "Metti in pausa la lettura",
    "em_pausa": "In pausa",
    "leitura_em_voz_alta_nao_disponivel_nes": "La lettura ad alta voce non è disponibile in questo browser",
    "nome_do_marcador": "Nome del segnalibro",
    "o_marcador_sera_removido_deste_audioli": "Il segnalibro verrà rimosso da questo audiolibro.",
    "nao_foi_possivel_salvar_o_marcador": "Impossibile salvare il segnalibro.",
    "ja_existe_um_marcador_neste_ponto": "Esiste già un segnalibro in questo punto.",
    "timer_de_sono_encerrado": "Timer di spegnimento terminato.",
    "fim_do_cap": "Fine cap.",
    "timer_desativado": "Timer disattivato.",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "L’audio si metterà in pausa alla fine del capitolo.",
    "este_audiolivro_nao_tem_capitulos": "Questo audiolibro non ha capitoli.",
    "ao_fim_do_capitulo": "Alla fine del capitolo",
    "desativar_timer": "Disattiva timer",
    "mais_10_minutos_no_timer": "Altri 10 minuti sul timer.",
    "somar_10_minutos": "Aggiungi 10 minuti",
    "pausa_ao_fim_do_capitulo": "Pausa alla fine del capitolo",
    "no_livro_todo": "In tutto il libro",
    "video": "Video",
    "audiolivro_concluido": "Audiolibro terminato.",
    "video_concluido": "Video terminato.",
    "video_2": "video",
    "audio": "audio",
    "toque_em_reproduzir_para_comecar": "Tocca Riproduci per iniziare.",
    "falha_ao_carregar_o_audio": "Impossibile caricare l’audio.",
    "exclua_o_da_biblioteca_e_importe_o_arq": "Eliminalo dalla biblioteca e importa di nuovo il file.",
    "os_nomes_dos_arquivos_seguem_uma_seque": "I nomi dei file seguono una sequenza, quindi sembrano capitoli dello stesso audiolibro.",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "I file condividono lo stesso album nei tag, quindi sembrano capitoli dello stesso audiolibro.",
    "libere_espaco_ou_exclua_livros_da_bibl": "Libera spazio o elimina libri dalla biblioteca e riprova.",
    "o_armazenamento_do_aparelho_esta_cheio": "Lo spazio di archiviazione del dispositivo è pieno.",
    "preparando_a_capa": "Preparazione della copertina...",
    "remova_esse_arquivo_da_selecao_e_tente": "Rimuovi quel file dalla selezione e riprova.",
    "sequencia": "sequenza",
    "o_arquivo_pode_estar_incompleto_tente": "Il file potrebbe essere incompleto. Prova a scaricarlo di nuovo.",
    "conferindo_se_o_audio_pode_ser_reprodu": "Verifica della riproduzione audio...",
    "conferindo_se_o_video_pode_ser_reprodu": "Verifica della riproduzione video...",
    "lendo_titulo_capitulos_e_capa": "Lettura di titolo, capitoli e copertina...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "Il file potrebbe essere danneggiato o in un formato audio che il browser non riproduce. Prova a convertirlo in MP3 o M4B (AAC).",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "Il file potrebbe essere danneggiato o in un formato video che il browser non riproduce. Prova a convertirlo in MP4 con video H.264 e audio AAC.",
    "converta_o_audiolivro_para_m4b_com_aud": "Converti l’audiolibro in M4B con audio AAC (o in MP3) e importalo di nuovo.",
    "converta_o_video_para_mp4_com_audio_aa": "Converti il video in MP4 con audio AAC e video H.264 e importalo di nuovo.",
    "o_navegador_nao_reproduz_o_formato_de": "Il browser non riprodurrà il formato audio di questo file.",
    "arquivos_com_protecao_nao_podem_ser_re": "I file protetti non possono essere riprodotti qui. Usa una copia senza DRM.",
    "nao_ha_espaco_suficiente_no_aparelho_p": "Non c’è abbastanza spazio sul dispositivo per questo audiolibro.",
    "confira_se_a_extensao_corresponde_ao_c_2": "Controlla che l’estensione corrisponda al contenuto oppure converti l’audio in MP3 o M4B (AAC).",
    "imagem_invalida": "immagine non valida",
    "imagem_demorou_demais": "l’immagine ha impiegato troppo tempo a caricarsi",
    "imagem_vazia": "immagine vuota",
    "inicio": "Inizio",
    "mp4_moov_nao_encontrado": "Il video sembra incompleto o danneggiato.",
    "pagina": "Pagina",
    "esta_pagina_nao_esta_disponivel": "Questa pagina non è disponibile.",
    "esta_pagina_nao_pode_ser_descompactada": "Non è stato possibile decomprimere questa pagina.",
    "quadrinho_fechado": "Fumetto chiuso.",
    "ele_pode_estar_incompleto_dividido_em": "Potrebbe essere incompleto, diviso in più parti o usare una variante RAR non riconosciuta dall’app. Convertirlo in CBZ di solito risolve il problema.",
    "remova_a_senha_do_arquivo_e_importe_de": "Rimuovi la password dal file e importalo di nuovo.",
    "nao_foi_possivel_ler_este_arquivo_de_q": "Non è stato possibile leggere questo file di fumetti.",
    "este_quadrinho_esta_protegido_por_senh": "Questo fumetto è protetto da password.",
    "lendo_o_indice_do_quadrinho": "Lettura dell’indice del fumetto...",
    "o_arquivo_pode_ser_grande_demais_para": "Il file potrebbe essere troppo grande per la memoria del dispositivo. Dividere il fumetto in parti più piccole di solito risolve il problema.",
    "nao_foi_possivel_abrir_este_quadrinho": "Non è stato possibile aprire questo fumetto.",
    "lendo_o_arquivo": "Lettura del file...",
    "preparando_o_leitor_de_cbr": "Preparazione del lettore CBR...",
    "o_arquivo_pode_estar_incompleto_proteg": "Il file potrebbe essere incompleto, protetto da password o danneggiato.",
    "nao_foi_possivel_ler_este_quadrinho": "Non è stato possibile leggere questo fumetto.",
    "o_arquivo_precisa_conter_imagens_jpg_p": "Il file deve contenere immagini (JPG, PNG, WEBP o GIF).",
    "nao_encontramos_paginas_dentro_deste_q": "Non abbiamo trovato pagine all’interno di questo fumetto.",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "Non c’è abbastanza spazio sul dispositivo per questo fumetto.",
    "cabecalho_de_item_invalido": "Una parte del file è danneggiata.",
    "a_pasta_vendor_libarchive_precisa_esta": "Manca un componente dell’app necessario per aprire questo fumetto. Convertilo in CBZ o reinstalla l’app.",
    "o_leitor_de_cbr_nao_foi_encontrado": "Lettore CBR non trovato.",
    "converta_o_quadrinho_para_cbz_zip_e_im": "Converti il fumetto in CBZ (ZIP) e importalo di nuovo.",
    "este_navegador_nao_consegue_abrir_arqu": "Questo browser non può aprire file CBR.",
    "convertendo_o_markdown": "Conversione del Markdown",
    "lendo_o_texto": "Lettura del testo",
    "pdf_indisponivel": "PDF non disponibile.",
    "epub_invalido_nenhum_capitulo_no_spine": "Questo EPUB è danneggiato: non è stato possibile trovare i capitoli del libro.",
    "livro_sem_titulo": "Libro senza titolo",
    "epub_invalido_arquivo_opf_nao_encontra": "Questo EPUB è incompleto o danneggiato e non può essere aperto.",
    "epub_invalido_container_xml_nao_encont": "Questo EPUB è incompleto o danneggiato e non può essere aperto.",
    "organizando_o_texto": "Impaginazione del testo",
    "descompactando_o_livro": "Decompressione del libro",
    "nao_encontramos_conteudo_para_exibir_n": "Non abbiamo trovato nulla da mostrare in questo file.",
    "livro_sem_texto_legivel": "Libro senza testo leggibile",
    "o_arquivo_pode_estar_corrompido_tente": "Il file potrebbe essere danneggiato. Prova a convertirlo in EPUB.",
    "nao_foi_possivel_extrair_o_texto_deste": "Non è stato possibile estrarre il testo da questo MOBI.",
    "nenhum_registro_de_conteudo_foi_encont": "Non è stato possibile trovare il testo del libro in questo file.",
    "arquivo_mobi_sem_texto": "File MOBI senza testo.",
    "o_dicionario_de_compressao_esta_vazio": "Manca una parte del contenuto di questo MOBI.",
    "arquivo_mobi_incompleto": "File MOBI incompleto.",
    "as_tabelas_de_compressao_nao_foram_enc": "Manca una parte del contenuto di questo MOBI.",
    "converta_o_arquivo_para_epub_em_um_pro": "Converti il file in EPUB con un programma come Calibre e importalo di nuovo.",
    "compressao_mobi_nao_reconhecida": "Questo MOBI usa un formato interno che l’app non riconosce.",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "Non è stato possibile leggere l’intestazione del libro.",
    "arquivo_mobi_corrompido": "File MOBI danneggiato.",
    "a_lista_interna_de_registros_esta_inco": "Il file è incompleto. Prova a scaricarlo o a convertirlo di nuovo.",
    "o_download_parece_ter_sido_interrompid": "Il download sembra essere stato interrotto. Scarica di nuovo il file.",
    "tabela_de_compressao_mobi_corrompida": "Una parte di questo file MOBI è danneggiata.",
    "tabela_de_compressao_mobi_incompleta": "Questo file MOBI è incompleto.",
    "tabela_de_compressao_mobi_invalida": "Una parte di questo file MOBI è danneggiata.",
    "este_arquivo_docx_nao_tem_conteudo_de": "Questo file .docx non contiene testo visualizzabile.",
    "documento_sem_texto": "Documento senza testo",
    "o_arquivo_pode_estar_corrompido_proteg": "Il file potrebbe essere danneggiato, protetto da password o essere un vecchio .doc. Salvalo di nuovo come .docx e importalo un’altra volta.",
    "nao_foi_possivel_ler_este_arquivo_docx": "Non è stato possibile leggere questo file DOCX.",
    "convertendo_o_documento": "Conversione del documento",
    "conecte_se_a_internet_uma_vez_para_bai": "Connettiti a Internet una volta per scaricare il componente, poi riapri il libro.",
    "o_conversor_de_docx_nao_carregou": "Il convertitore DOCX non è stato caricato.",
    "video_mp4": "Video (MP4)",
    "audiolivro_m4b": "Audiolibro (M4B)",
    "audiolivro_mp3": "Audiolibro (MP3)",
    "quadrinho_cbt": "Fumetto (CBT)",
    "quadrinho_cb7": "Fumetto (CB7)",
    "quadrinho_cbr": "Fumetto (CBR)",
    "quadrinho_cbz": "Fumetto (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "Testo (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "Salvataggio annullato.",
    "o_arquivo_esta_vindo_do_armazenamento": "Il file sta arrivando dal cloud storage al tuo dispositivo.",
    "baixando_o_arquivo": "Download del file",
    "cancelando": "Annullamento...",
    "use_grifar_citacao_anotar_ou_marcador": "Usa Evidenzia, Citazione, Nota o Segnalibro mentre leggi.",
    "nenhuma_marcacao_ainda": "Nessuna annotazione ancora",
    "trecho_original": "Passaggio originale",
    "procurar_meus_livros": "Trova i miei libri",
    "a_busca_fica_sempre_disponivel_no_menu": "La ricerca è sempre disponibile nel menu laterale, sotto Sistema.",
    "da_para_fazer_depois": "Puoi farlo più tardi",
    "nada_entra_na_estante_sem_a_sua_confir": "Nulla arriva sul tuo scaffale senza il tuo consenso: vedi l’elenco e selezioni ciò che vuoi importare.",
    "voce_revisa_antes": "Controlli prima",
    "escolha_uma_pasta_downloads_e_um_bom_c": "Scegli una cartella (Download è un buon punto di partenza) e l’app cerca al suo interno e in tutte le sottocartelle.",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "Cerca EPUB, MOBI, CBZ, CBR e M4B",
    "voltar_e_revisar": "Indietro e controlla",
    "ler_os_termos": "Leggi i termini",
    "ler_a_politica": "Leggi l’informativa",
    "os_dois_documentos_ficam_sempre_dispon": "I due documenti sono sempre disponibili nel menu laterale, sotto Informazioni.",
    "leia_com_calma": "Prenditi il tuo tempo",
    "a_politica_e_os_termos_explicam_como_o": "L’informativa e i termini spiegano come l’app conserva i tuoi libri e cosa puoi farne. Per usare la biblioteca, è necessario accettarli.",
    "nada_acontece_sem_o_aceite": "Per iniziare, è necessario accettare i termini",
    "aceitar_e_continuar": "Accetta e continua",
    "nao_aceito": "Non accetto",
    "termos_de_uso_2": "Termini di utilizzo",
    "politica_de_privacidade_2": "Informativa sulla privacy",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "L’app accede solo ai file e alle cartelle che scegli, quando lo decidi tu.",
    "voce_no_controle": "Sei tu a controllare",
    "depois_de_importar_um_livro_voce_le_se": "Dopo aver importato un libro, puoi leggerlo senza Internet.",
    "funciona_offline": "Funziona offline",
    "livros_marcacoes_e_progresso_sao_guard": "Libri, annotazioni e progressi restano sul dispositivo. Nulla viene inviato ai nostri server.",
    "tudo_fica_no_seu_aparelho": "Tutto resta sul tuo dispositivo",
    "escolha_o_que_deseja_adicionar_a_bibli": "Scegli cosa vuoi aggiungere alla biblioteca. I file identici a quelli già presenti sullo scaffale vengono ignorati automaticamente.",
    "voce_pode_tentar_outra_pasta_ou_import": "Puoi provare un’altra cartella oppure importare file con il pulsante +.",
    "a_leitura_acontece_so_no_seu_dispositi": "La lettura avviene solo sul tuo dispositivo.",
    "voce_escolhe_a_pasta": "Scegli la cartella",
    "tema_tipografia_margens_modo_de_virada": "Tema, carattere, margini, stile di cambio pagina e impostazioni audio.",
    "restaurar_minhas_preferencias": "Ripristina le mie preferenze",
    "o_backup_manda_as_marcacoes_atuais_dos": "Il backup prevale. Le annotazioni attuali di qualsiasi libro presente nel file verranno sostituite da quelle del backup.",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "Nulla viene cancellato. Le annotazioni di entrambe le parti vengono unite e prevale il progresso più recente.",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "Cosa fare con ciò che è già sullo scaffale",
    "grifos_citacoes_e_notas": "evidenziazioni, citazioni e note",
    "preparando_o_arquivo_2": "Preparazione del file...",
    "os_livros_em_si_nem_as_capas_por_isso": "Né i libri veri e propri né le copertine: per questo il file pesa solo pochi KB. Chi lo riceve deve avere i file dei libri perché le annotazioni tornino al loro posto; le copertine riappaiono automaticamente durante l’importazione.",
    "nao_vai_no_arquivo": "Non nel file",
    "o_seu_progresso_de_leitura_os_grifos_a": "Il tuo progresso di lettura, le evidenziazioni, le citazioni, le note, i segnalibri e l’organizzazione dello scaffale — stato, preferiti, raccolte, serie e tag.",
    "vai_no_arquivo": "Nel file",
    "descartar_o_que_esta_esperando_2": "Elimina dati in attesa",
    "esperando_o_arquivo": "In attesa del file",
    "avisar_quando_fizer_tempo_sem_backup": "Ricordami quando è passato un po’ di tempo senza un backup",
    "livros_que_ainda_nao_estiverem_na_esta": "I libri che non sono ancora sullo scaffale restano in attesa: quando importi il loro file, le annotazioni tornano automaticamente.",
    "restaurar_backup": "Ripristina backup",
    "salvar_backup": "Salva backup",
    "ainda_nao_ha_itens": "Niente qui per ora",
    "arraste_um_livro_para_outra_posicao_na": "Trascina un libro in un’altra posizione sullo scaffale per salvare un ordine personale. Questo ordine manuale ha poi la priorità sul raggruppamento per autore.",
    "separe_por_virgulas": "Separa con virgole",
    "ex_estudos_ficcao": "es. Studi, Narrativa...",
    "pasta_estante": "Cartella / scaffale",
    "ex_trilogia": "es. Trilogia...",
    "serie": "Serie",
    "aparece_em_favoritos": "Compare nei Preferiti.",
    "nome_do_livro": "Nome del libro",
    "nenhum_registro_ainda": "Nessun dato registrato ancora",
    "no_leitor_toque_no_icone_de_marcador_p": "Nel lettore, tocca l’icona del segnalibro per salvare la pagina.",
    "nenhum_marcador_ainda": "Nessun segnalibro ancora",
    "a_gravacao_e_independente_da_localizac": "Il salvataggio è indipendente dalla posizione del PDF e non modifica il file originale.",
    "o_pdf_original_nao_precisa_estar_nessa": "Il PDF originale non deve trovarsi in questa cartella",
    "excluir_da_biblioteca": "Elimina dalla biblioteca",
    "adicionar_livro": "Aggiungi libro",
    "adicione_livros_e_acompanhe_o_que_esta": "Aggiungi libri e tieni traccia di ciò che è in attesa, in corso e dei tuoi progressi.",
    "tudo_pronto_para_a_proxima_leitura": "Tutto pronto per la prossima lettura.",
    "sua_biblioteca": "La tua biblioteca",
    "arraste_um_livro_para_reposiciona_lo_a": "Trascina un libro per spostarlo: lo scaffale passa a Il mio ordine e mantiene la sequenza.",
    "importe_um_livro_ou_ajuste_seus_filtro": "Importa un libro o regola i filtri.",
    "nada_por_aqui_ainda": "Niente qui per ora",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "Tocca + e scegli file MP3, M4B o MP4. Più MP3 di capitoli possono diventare un unico audiolibro.",
    "nada_para_ouvir_ou_assistir_ainda": "Niente ancora da ascoltare o guardare",
    "o_pdf_original_permanece_intacto_na_pa": "Il PDF originale resta intatto nella tua cartella.",
    "paginas_como_imagem": "Pagine come immagini",
    "paginas_do_pdf": "Pagine del PDF",
    "em_navegadores_sem_suporte_a_acesso_di": "Nei browser senza accesso diretto al file system, l’EPUB verrà scaricato al suo posto.",
    "essa_permissao_e_dada_somente_a_esta_a": "Questa autorizzazione viene concessa solo a questa app e impedisce di modificare il file originale.",
    "selecione_a_pasta_que_contem_o_pdf": "Seleziona la cartella che contiene il PDF",
    "preparando": "Preparazione…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "Il file viene letto e ricostruito. I libri di grandi dimensioni possono richiedere qualche istante.",
    "revistas_apostilas_complexas_formulari": "Riviste, manuali complessi, moduli, documenti con molte tabelle o PDF scansionati possono perdere parte del layout originale.",
    "funcionalidade_indicada_apenas_para_li": "Pensato per i libri",
    "o_epub_e_melhor_para_livros_com_texto": "EPUB è migliore per i libri con testo selezionabile, perché consente di regolare carattere, dimensioni, margini e modalità di lettura.",
    "trecho_selecionado": "Passaggio selezionato",
    "trecho_comentado": "Passaggio con un commento",
    "aplicando_zoom": "Zoom in corso...",
    "nao_foi_possivel_carregar_esta_pagina": "Impossibile caricare questa pagina.",
    "nomear_marcador": "Dai un nome al segnalibro",
    "toque_em_marcar_agora_para_guardar_est": "Tocca «Segna ora» per salvare questo punto e tornarci quando vuoi.",
    "timer_ativo": "Timer attivo",
    "trecho_ausente_ou_corrompido_no_arquiv": "[Passaggio mancante o danneggiato nel file originale]",
    "novos_livros_vao_abrir_em_leitura_v": "I nuovi libri si apriranno con la lettura {v}.",
    "leitura_efetivo_aplicada_a_este_livro": "Lettura {efetivo} applicata a questo libro.",
    "automatico_neste_livro_leitura_efetivo": "Automatico per questo libro: lettura {efetivo}.",
    "agora_esta_em_efetivo_no_automatico_fo": "Ora impostato su {efetivo}; in automatico, {format} si apre in {padrao}.",
    "esta_escolha_vale_so_para_v_cada_livro": "Questa scelta si applica solo a “{v}”. Ogni libro mantiene la propria direzione di scorrimento.",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} non sono ancora sul tuo scaffale.",
    "escolha_uma_pasta_para_procurar_label": "Scegli una cartella in cui cercare {label}.",
    "subtitle_versao_build": "{subtitle} · versione {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "Impossibile leggere {path}; verrà usato il testo integrato.",
    "seu_ultimo_backup_foi_ha_dias_dias": "L’ultimo backup risale a {dias} giorni fa",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "Dal backup manca ancora {aguardando} libro. I suoi progressi e le sue annotazioni sono stati conservati: appena importi il file, tutto tornerà automaticamente al suo posto.",
      "other": "Dal backup mancano ancora {aguardando} libri. I loro progressi e le loro annotazioni sono stati conservati: appena importi ogni file, tutto tornerà automaticamente al suo posto."
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "{atualizados} libro del tuo scaffale è stato aggiornato.",
      "other": "{atualizados} libri del tuo scaffale sono stati aggiornati."
    },
    "criado_em_quando": "Creato il {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "Backup pronto: {livros} libri e {marcacoes} annotazioni.",
    "endereco_seguro_seguro": "indirizzo sicuro: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "Progressi e {marcas} annotazione ripristinati per questo libro.",
      "other": "Progressi e {marcas} annotazioni ripristinati per questo libro."
    },
    "restaurando_v_de_length": "Ripristino ({v} di {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} libri · {marcacoes} annotazioni",
    "criado_em_v": "Creato il {v}",
    "reunindo_a_sua_estante_v_de_length": "Raccolta del tuo scaffale ({v} di {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "“{titulo}” è già stato importato ed è ancora nella tua biblioteca. Non è stata creata una nuova copia.",
    "length_arquivos_de_audio": "{length} file audio...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "Non è stato possibile leggere {falhas} file.",
      "other": "Non è stato possibile leggere {falhas} file."
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} erano già nella biblioteca e sono stati ignorati.",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "{importados} libro aggiunto al tuo scaffale.",
      "other": "{importados} libri aggiunti al tuo scaffale."
    },
    "epub_salvo_em_filename": "EPUB salvato in {fileName}.",
    "falha_ao_converter_o_pdf_v": "Impossibile convertire il PDF: {v}",
    "pagina_page_de_totalpages": "Pagina {page} di {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} pagina",
      "other": "{totalPages} pagine"
    },
    "length_resultado_s_para_search": {
      "one": "{length} risultato per “{search}”",
      "other": "{length} risultati per “{search}”"
    },
    "capitulo_v": "Capitolo {v}",
    "organizando_capitulo_v_de_totalchapter": "Impaginazione del capitolo {v} di {totalChapters}",
    "pagina_v": "Pagina {v}",
    "paginas_v_v2": "Pagine {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} pagina pronta",
      "other": "{length} pagine pronte"
    },
    "montando_as_paginas_pagessofar_prontas": "Creazione delle pagine — {pagesSoFar} completate",
    "lendo_pagina_v_de_length": "Lettura della pagina {v} di {length}",
    "marcador_salvo_em_t": "Segnalibro salvato in {t}.",
    "o_audio_vai_pausar_em_minutes_minutos": "L’audio verrà messo in pausa tra {minutes} minuti.",
    "length_capitulos_toque_para_ir_direto": "{length} capitoli · tocca per andare direttamente lì.",
    "narrado_por_narrator": "Narrato da {narrator}",
    "velocidade_de_reproducao_rate": "Velocità di riproduzione: {rate}",
    "avancar_f_segundos": "Avanti di {f} secondi",
    "nao_foi_possivel_abrir_este_v": "Impossibile aprire questo {v}.",
    "nao_foi_possivel_ler_o_arquivo_de_v": "Impossibile leggere il file {v}.",
    "o_v_esta_danificado_neste_ponto": "Il {v} è danneggiato in questo punto.",
    "o_navegador_nao_consegue_reproduzir_es": "Il browser non può riprodurre questo file {v}.",
    "nao_foi_possivel_reproduzir_este_v": "Impossibile riprodurre questo {v}.",
    "os_dados_deste_noun_estao_incompletos": "I dati di {noun} sono incompleti.",
    "importe_o_arquivo_novamente_para_conti_2": "Importa di nuovo il file per continuare con {v}.",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "Il file di {noun} non è più salvato sul dispositivo.",
    "nao_foi_possivel_descobrir_a_duracao_d": "Impossibile determinare la durata di “{name}”.",
    "lendo_faixa_v_de_length": "Lettura della traccia {v} di {length}...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "Impossibile determinare la durata di questo {v}.",
    "este_format_nao_pode_ser_reproduzido_n": "Questo {format} non può essere riprodotto in questo browser.",
    "este_format_esta_protegido_por_drm": "Questo {format} è protetto da DRM.",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "Il file occupa {bytes} e ne rimane circa {v}. Libera spazio o elimina libri dalla biblioteca.",
    "este_arquivo_nao_e_um_format_valido": "Questo file non è un {format} valido.",
    "preparando_as_paginas_vistas_de_total": "Preparazione delle pagine ({vistas} di {total})...",
    "preparando_total_pagina_s": {
      "one": "Preparazione di {total} pagina...",
      "other": "Preparazione di {total} pagine..."
    },
    "preparando_as_paginas_v_de_total": "Preparazione delle pagine ({v} di {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "Occupa circa {bytes} e ne rimane circa {v}. Libera spazio o elimina libri dalla biblioteca.",
    "envio_direto_exige_endereco_seguro": "L’invio diretto a un’altra app non è disponibile perché questa pagina non è stata aperta da un indirizzo sicuro. Salva il file e invialo con l’app che preferisci.",
    "na_estante": "sullo scaffale",
    "nao_foi_possivel_montar_o_arquivo": "Impossibile creare il file.",
    "este_navegador_nao_oferece_o_envio_dir": "Questo browser non offre l’invio diretto a un’altra app. Salva il file e allegalo con l’app che preferisci.",
    "voce_ainda_nao_fez_nenhum_backup": "Non hai ancora eseguito alcun backup.",
    "converter_para_epub": "Converti in EPUB",
    "esta_pagina_nao_pode_ser_exibida": "Impossibile mostrare questa pagina.",
    "na_ordem_em_que_serao_tocados": "Nell’ordine in cui verranno riprodotti",
    "este_capitulo_nao_pode_ser_exibido": "Impossibile mostrare questo capitolo.",
    "livro": "Libro",
    "restantes": " rimanenti",
    "como_seus_dados_sao_tratados": "Come vengono trattati i tuoi dati",
    "condicoes_de_uso_do_aplicativo": "Condizioni per l’uso dell’app",
    "audiolivro": "audiolibro",
    "sobre_o_aplicativo": "Informazioni sull’app",
    "o_que_e_o_veredas_reader": "Che cos’è Veredas Reader",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(questo dispositivo non supporta la condivisione di questo tipo di file)",
    "livros": "libri",
    "lendo": "lettura",
    "lidos": "terminati",
    "compartilhar_livro": "Condividi libro",
    "n_livros": {
      "one": "{n} libro",
      "other": "{n} libri"
    },
    "livros_unidade": {
      "one": "libro",
      "other": "libri"
    },
    "uma_faixa_discreta_depois_de_n_dias": "Una piccola fascia appare sullo scaffale dopo {n} giorni senza backup. Non interrompe mai la lettura.",
    "scanned_arquivos_verificados_livros_enc": "{scanned} file controllati · {encontrados} libri trovati",
    "v_de_total": "{v} di {total}",
    "voltar_n_segundos": "Indietro di {n} secondi",
    "cancelado": "Annullato",
    "arquivo": "File",
    "outro": "Altro",
    "outros": "Altri",
    "audiolivro_2": "Audiolibro",
    "pausar": "Pausa",
    "marcador": "Segnalibro",
    "leitura": "Lettura",
    "grifo": "Evidenziazione",
    "editar": "Modifica",
    "apagar": "Elimina",
    "concluir": "Fine",
    "recentes": "Recenti",
    "progresso": "Progressi",
    "entendi": "Capito",
    "aviso": "Avviso",
    "descartar": "Elimina",
    "copiado": "Copiato",
    "restaurar": "Ripristina",
    "restaurando": "Ripristino",
    "excluir": "Elimina",
    "grifos": "Evidenziazioni",
    "arquivo_vazio": "File vuoto.",
    "e_mais_n_arquivos": {
      "one": "e {n} altro file, nell’ordine in cui verranno riprodotti",
      "other": "e altri {n} file, nell’ordine in cui verranno riprodotti"
    },
    "n_arquivos_mp3": {
      "one": "{n} file MP3",
      "other": "{n} file MP3"
    },
    "pct_restam": "{pct}% · mancano {tempo}",
    "n_minutos": {
      "one": "{n} minuto",
      "other": "{n} minuti"
    },
    "ir_para_tempo": "Vai a {tempo}",
    "nomear": "Rinomina",
    "parte_n": "Parte {n}",
    "carregando_pagina_n": "Caricamento pagina {n}...",
    "selecionar_pasta_e_continuar": "Seleziona cartella e continua",
    "ler_agora": "Leggi ora",
    "agrupamento_v": "Raggruppamento: {v}.",
    "tempo_restante": "mancano {tempo}",
    "abrir_titulo": "Apri {titulo}",
    "continuar_lendo_titulo": "Continua a leggere {titulo}",
    "continuar_ouvindo_titulo": "Continua ad ascoltare {titulo}",
    "continuar_assistindo_titulo": "Continua a guardare {titulo}",
    "lido": "Letto",
    "pausado": "In pausa",
    "status": "Stato",
    "favorito": "Preferito",
    "escolher_local": "Scegli posizione",
    "epub_baixado_como": "EPUB scaricato come {nome}.",
    "ouvir_a_partir_de": "ascolta da {tempo}",
    "assistir_a_partir_de": "guarda da {tempo}",
    "pagina_n_minuscula": "pagina {n}",
    "selecione_trecho_para_criar": "Seleziona un passaggio durante la lettura per creare {oque}.",
    "excluir_oque_pergunta": "Eliminare {oque}?",
    "excluir_oque": "Elimina {oque}",
    "excluir_item_pergunta": "Eliminare questo elemento?",
    "use_organizar_para_criar": "Usa «{botao}» su un libro per creare {oque}.",
    "n_arquivos_processados": {
      "one": "{n} file elaborato",
      "other": "{n} file elaborati"
    },
    "voce_ja_tem_titulo_de_autor": "Hai già «{titulo}» di {autor} nella libreria, anche se il file è diverso. Vuoi importarlo comunque?",
    "voce_ja_tem_titulo": "Hai già «{titulo}» nella libreria, anche se il file è diverso. Vuoi importarlo comunque?",
    "marcadores_unidade": {
      "one": "segnalibro",
      "other": "segnalibri"
    },
    "ultimo_backup_em": "Ultimo backup il <strong>{data}</strong>.",
    "guardar": "Salva",
    "lembretes": "Promemoria",
    "juntar": "Unisci",
    "recomendado": "consigliato",
    "substituir": "Sostituisci",
    "n_capas_recuperadas": {
      "one": "{n} copertina recuperata.",
      "other": "{n} copertine recuperate."
    },
    "nao_encontramos_arquivos_tipo": "Nessun file {tipo} trovato in questa cartella.",
    "tentar_outra_pasta": "Prova un’altra cartella",
    "n_livros_encontrados": {
      "one": "{n} libro trovato",
      "other": "{n} libri trovati"
    },
    "n_de_total_selecionados": {
      "one": "{n} di {total} selezionato",
      "other": "{n} di {total} selezionati"
    },
    "importar": "Importa",
    "importar_n": "Importa {n}",
    "aceite_frase": "Ho letto e accetto l’{politica} e i {termos} di Veredas Reader.",
    "pdf_preservado": "Il PDF originale <strong>non verrà eliminato dalla tua cartella</strong>. Solo la copia di questo PDF verrà rimossa dalla libreria, dopo che l’EPUB sarà stato salvato correttamente.",
    "gravar_epub_mesma_pasta": "Per salvare l’EPUB <strong>nella stessa cartella del PDF</strong>, il browser ha bisogno dell’autorizzazione per accedere a quella cartella.",
    "epub_pronto_qualquer_pasta": "L’EPUB è convertito. Ora puoi scegliere <strong>qualsiasi cartella sul computer</strong> per salvare il file.",
    "backup_explicacao": "Il backup originale è un file ZIP o TXT. Quando lo ricevi su un altro dispositivo, importalo tramite <strong>Ripristina backup</strong>: Veredas riconosce il contenuto e lo ripristina normalmente. Il file contiene i tuoi progressi, le evidenziazioni, le citazioni, le note, i segnalibri e l’organizzazione dello scaffale — <strong>non i libri stessi</strong>, né le copertine.",
    "lembretes_desligados_frase": "I promemoria sono <strong>disattivati</strong>. Ricordati di fare il backup ogni tanto.",
    "backup_salvo_nos_downloads": "<strong>Il file di backup è stato salvato su questo dispositivo</strong>, nei tuoi download. Puoi inviarlo subito: apri WhatsApp, email, Drive o l’app che preferisci, tocca Allega e scegli il file.",
    "arquivo_pronto_tamanho": "File pronto — <strong>{tamanho}</strong>.",
    "scan_intro_frase": "L’app può cercare libri in <strong>EPUB</strong> e <strong>MOBI</strong>, fumetti in <strong>CBZ</strong> e <strong>CBR</strong> e audiolibri in <strong>M4B</strong> all’interno di una cartella del dispositivo, comprese le sottocartelle.",
    "scan_intro_auto_frase": "Per riempire in fretta lo scaffale, l’app può cercare libri in <strong>EPUB</strong> e <strong>MOBI</strong>, fumetti in <strong>CBZ</strong> e <strong>CBR</strong> e audiolibri in <strong>M4B</strong> all’interno di una cartella del dispositivo, comprese le sottocartelle.",
    "n_livros_aguardando": {
      "one": "<strong>{n} libro</strong> con progressi e annotazioni conservati, in attesa di essere importato di nuovo.",
      "other": "<strong>{n} libri</strong> con progressi e annotazioni conservati, in attesa di essere importati di nuovo."
    },
    "fora_da_busca_titulo": "Non importiamo automaticamente file PDF, TXT, DOCX (Word), MD, MP3 e MP4",
    "fora_da_busca_texto": "Questi formati si usano per ogni tipo di documento, non solo per i libri. Lasciarli fuori mantiene lo scaffale in ordine. <strong>Puoi importare questi file uno per uno manualmente con il pulsante +.</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "La tua biblioteca locale",
    "biblioteca": "Biblioteca",
    "organizacao": "Organizzazione",
    "minhas_marcacoes": "Le mie annotazioni",
    "sistema": "Sistema",
    "sua_biblioteca": "La tua biblioteca",
    "toque_em_um_livro_para_comecar_a_ler": "Tocca un libro per iniziare a leggere.",
    "agrupar": "Raggruppa",
    "sua_estante_nao_tem_copia_de_seguranca": "Il tuo scaffale non ha un backup",
    "se_este_aparelho_se_perder_o_progresso": "Se succede qualcosa a questo dispositivo, i progressi e le annotazioni potrebbero andare persi.",
    "agora_nao": "Non ora",
    "nao_avisar_mais": "Non ricordarmelo più",
    "carregando": "Caricamento...",
    "estante": "Scaffale",
    "lendo": "Lettura",
    "favoritos": "Preferiti",
    "marcas": "Annotazioni",
    "mais": "Altro",
    "neste_capitulo": "Questo capitolo",
    "velocidade": "Velocità",
    "timer": "Timer",
    "marcar": "Segna",
    "marcadores": "Segnalibri",
    "personalizar_leitura": "Preferenze di lettura",
    "as_preferencias_ficam_salvas_para_as_p": "Le tue preferenze vengono conservate per le prossime sessioni di lettura.",
    "tema": "Tema",
    "claro": "Chiaro",
    "sepia": "Seppia",
    "escuro": "Scuro",
    "oceano": "Oceano",
    "tipografia": "Carattere",
    "texto": "Testo",
    "tamanho": "Dimensione",
    "espacamento": "Interlinea",
    "margens": "Margini",
    "cores_personalizadas_opcional": "Colori personalizzati (facoltativo)",
    "fundo": "Sfondo",
    "fonte": "Colore del testo",
    "brilho": "Luminosità",
    "orientacao": "Orientamento",
    "auto": "Automatico",
    "retrato": "Ritratto",
    "paisagem": "Paesaggio",
    "modo_de_leitura": "Modalità di lettura",
    "automatico": "Automatico",
    "horizontal": "Orizzontale",
    "vertical": "Verticale",
    "automatico_usa_rolagem_horizontal_para": "Automatico usa la paginazione orizzontale per EPUB, MOBI, TXT e MD, e lo scorrimento verticale per PDF e DOCX. Se lo cambi durante la lettura, la modifica viene applicata solo a questo libro.",
    "quadrinhos": "Fumetti",
    "como_a_pagina_aparece": "Adattamento della pagina",
    "pagina_inteira": "Pagina intera",
    "largura_da_tela": "Larghezza dello schermo",
    "sentido_da_leitura": "Direzione di lettura",
    "normal": "Normale →",
    "manga": "← Manga",
    "revista_aberta_na_horizontal": "Doppia pagina in modalità orizzontale",
    "com_o_aparelho_deitado_mostra_duas_pag": "Tenendo il dispositivo di lato, vengono mostrate due pagine affiancate; la copertina resta da sola, come in un vero fumetto.",
    "normal_vira_da_esquerda_para_a_direita": "Normale gira da sinistra a destra. Manga inverte tutto: lo scorrimento, i tocchi ai bordi e l’ordine delle due pagine nella vista doppia.",
    "gire_o_aparelho_para_a_horizontal_para": "Ruota il dispositivo di lato per vedere due pagine insieme.",
    "dois_toques_ampliam_no_ponto_tocado_co": "Tocca due volte per ingrandire nel punto toccato; con lo zoom, trascina per spostarti nella pagina. Funziona anche il pizzico con due dita.",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "Il pulsante di scorrimento in alto nel lettore alterna tra lettura pagina per pagina e scorrimento continuo (stile webtoon). Con lo scorrimento continuo le pagine si susseguono e lo zoom allarga la pagina: puoi esplorarla scorrendo lateralmente.",
    "virada_de_pagina": "Cambio pagina",
    "folha_real": "Carta reale",
    "deslizar": "Scorrimento",
    "sem_animacao": "Nessuna animazione",
    "na_leitura_horizontal_arraste_a_pagina": "Nella lettura orizzontale, trascina la pagina dal bordo per piegarla con il dito. Rilascia a metà per annullare il cambio.",
    "ouvir_leitura": "Ascolta",
    "continue_de_onde_parou_no_seu_ritmo": "Riprendi da dove avevi lasciato, al tuo ritmo.",
    "livro": "Libro",
    "pronto_para_comecar": "Pronto per iniziare",
    "voz": "Voce",
    "escolha_uma_voz_disponivel_no_disposit": "Scegli una voce disponibile su questo dispositivo",
    "voz_padrao_do_sistema": "Voce predefinita del sistema",
    "durante_a_reproducao": "Durante la riproduzione",
    "a_leitura_avanca_pagina_a_pagina_os_co": "La lettura procede pagina per pagina. I controlli di sistema appaiono quando il browser li supporta.",
    "organizar_livro": "Organizza libro",
    "estantes_colecoes_tags_e_status": "Scaffali, raccolte, tag e stato.",
    "cancelar": "Annulla",
    "salvar": "Salva",
    "grifos_citacoes_notas_e_marcadores_des": "Evidenziazioni, citazioni, note e segnalibri di questo libro.",
    "sumario": "Sommario",
    "toque_em_um_capitulo_para_ir_direto_ao": "Tocca un capitolo per andarci direttamente.",
    "sua_anotacao": "La tua nota",
    "edite_ou_adicione_comentarios_ao_seu_t": "Modifica o aggiungi commenti al tuo passaggio.",
    "trecho": "Passaggio",
    "sua_nota": "La tua nota",
    "salvar_nota": "Salva nota",
    "agrupar_biblioteca": "Raggruppa biblioteca",
    "escolha_como_os_livros_serao_organizad": "Scegli come organizzare i libri sullo scaffale.",
    "ao_arrastar_um_livro_para_outra_posica": "Quando trascini un libro in un’altra posizione, lo scaffale passa automaticamente a Il mio ordine e mantiene la sequenza che hai creato.",
    "backup_e_restauracao": "Backup e ripristino",
    "sua_estante_seu_progresso_e_suas_marca": "Il tuo scaffale, i tuoi progressi e le tue annotazioni in un unico file.",
    "escolha_uma_dimensao_para_explorar_sua": "Scegli un modo per esplorare la tua biblioteca.",
    "capitulos": "Capitoli",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "La voce mantiene la stessa tonalità. Vale per questo libro e per i successivi.",
    "ajuste_fino": "Regolazione fine",
    "timer_de_sono": "Timer di spegnimento",
    "o_audio_diminui_de_volume_aos_poucos_e": "L’audio sfuma gradualmente e si mette in pausa automaticamente.",
    "pontos_que_voce_guardou_neste_audioliv": "I punti che hai salvato in questo audiolibro.",
    "ajustes_do_audio": "Impostazioni audio",
    "as_preferencias_ficam_salvas_para_todo": "Queste preferenze vengono conservate per tutti gli audiolibri.",
    "botao_de_voltar": "Pulsante indietro",
    "botao_de_avancar": "Pulsante avanti",
    "recuar_ao_retomar": "Torna indietro alla ripresa",
    "depois_de_uma_pausa_longa_volta_alguns": "Dopo una pausa lunga, torna indietro di alcuni secondi così puoi riprendere il filo.",
    "tocar_ao_abrir": "Riproduci all’apertura",
    "ao_tocar_em_um_audiolivro_na_estante_a": "Toccando un audiolibro sullo scaffale, la riproduzione inizia subito.",
    "no_computador_espaco_toca_e_pausa_pula": "Su computer: spazio riproduce e mette in pausa · ← → avanti/indietro · Shift + ← → cambia capitolo · ↑ ↓ volume · B segnalibri · [ ] velocità.",
    "converter_pdf_para_epub": "Converti PDF in EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "Prepara il libro per una lettura fluida e regolabile.",
    "confirmacao": "Conferma",
    "confirmar": "Conferma",
    "processando": "Elaborazione",
    "documento": "Documento",
    "buscar_livros_no_dispositivo": "Cerca libri su questo dispositivo",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "Trova i file EPUB, MOBI, CBZ, CBR e M4B già salvati sul dispositivo.",
    "juntar_em_um_unico_audiolivro": "Unire in un unico audiolibro?",
    "titulo": "Titolo",
    "autor": "Autore",
    "importar_separados": "Importa separatamente",
    "bem_vindo_ao_veredas_reader": "Benvenuto in Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "La tua biblioteca di lettura, interamente sul tuo dispositivo.",
    "buscar": "Cerca",
    "importar_livro": "Importa libro",
    "buscar_titulo_autor_tag": "Cerca titolo, autore, tag...",
    "fechar_busca": "Chiudi ricerca",
    "navegacao_da_biblioteca": "Navigazione della biblioteca",
    "fechar_menu": "Chiudi menu",
    "agrupar_livros": "Raggruppa libri",
    "voltar": "Indietro",
    "marcar_pagina": "Segna pagina",
    "personalizar": "Preferenze",
    "navegacao_principal": "Navigazione principale",
    "acoes_do_trecho": "Azioni sul passaggio",
    "amarelo": "Giallo",
    "verde": "Verde",
    "rosa": "Rosa",
    "azul": "Blu",
    "player_de_audiolivro": "Lettore audiolibri",
    "minimizar_player": "Riduci lettore",
    "minimizar": "Riduci",
    "video_em_reproducao": "Video in riproduzione",
    "abrir_a_lista_de_capitulos": "Apri l’elenco dei capitoli",
    "posicao_no_audio": "Posizione nell’audio",
    "alternar_entre_o_progresso_do_capitulo": "Passa dal progresso del capitolo a quello dell’intero libro",
    "capitulo_anterior": "Capitolo precedente",
    "voltar_15_segundos": "Indietro di 15 secondi",
    "reproduzir": "Riproduci",
    "avancar_30_segundos": "Avanti di 30 secondi",
    "proximo_capitulo": "Capitolo successivo",
    "velocidade_de_reproducao": "Velocità di riproduzione",
    "marcar_este_ponto": "Segna questo punto",
    "ver_marcadores": "Vedi segnalibri",
    "silenciar": "Disattiva audio",
    "volume": "Volume",
    "audiolivro_em_reproducao": "Audiolibro in riproduzione",
    "abrir_o_player": "Apri il lettore",
    "fechar_o_player": "Chiudi il lettore",
    "fechar": "Chiudi",
    "trecho_anterior": "Passaggio precedente",
    "iniciar_leitura": "Avvia lettura ad alta voce",
    "proximo_trecho": "Passaggio successivo",
    "escreva_seu_comentario_interpretacao_o": "Scrivi il tuo commento, interpretazione o promemoria...",
    "cancelar_importacao": "Annulla importazione",
    "nome_do_audiolivro": "Nome dell’audiolibro",
    "nome_do_autor": "Nome dell’autore",
    "idioma": "Lingua",
    "idioma_do_aplicativo": "Lingua dell’app",
    "o_aplicativo_segue_o_idioma_do_apare": "L’app segue la lingua del dispositivo. Se la tua lingua non è ancora presente qui, si aprirà in inglese.",
    "seguir_o_aparelho": "Segui il dispositivo",
    "fazer_backup": "Esegui backup ora",
    "todos": "Tutti",
    "lidos": "Terminati",
    "pausados": "In pausa",
    "autores": "Autori",
    "tags": "Tag",
    "grifar": "Evidenzia",
    "anotar": "Nota",
    "enviar": "Invia",
    "restaurar_padroes": "Ripristina valori predefiniti",
    "voltar_para_1": "Torna a 1×",
    "marcar_agora": "Segna ora",
    "escolher_pasta": "Scegli cartella",
    "juntar_em_um_audiolivro": "Unisci in un audiolibro",
    "sobre": "Informazioni",
    "licencas_de_codigo_aberto": "Licenze open source",
    "configuracoes": "Impostazioni",
    "temas_e_idioma": "Temi e lingua"
  },
  "aviso": {
    "idioma_trocado": "Lingua modificata."
  },
  "vn": {
    "quem_le": "Chi legge",
    "natural": "Naturale",
    "do_sistema": "Di sistema",
    "nota_sistema": "Usa le voci installate sul dispositivo. Per una lettura più umana, scegli Naturale.",
    "nota_sistema_com_natural": "La voce naturale resta scaricata. Torna a Naturale quando vuoi.",
    "voz_do_sistema": "Voce di sistema",
    "lendo_com_a_voz_do_sistema": "Lettura con la voce di sistema.",
    "voz_natural": "Voce naturale",
    "gerada_no_aparelho": "Una voce molto più umana, creata direttamente sul tuo dispositivo.",
    "progresso_download": "Avanzamento del download",
    "x_de_y": "{x} di {y}",
    "aviso_arquivo": "La voce naturale funziona solo se apri Veredas dall’indirizzo dell’app, non come file sul computer. Nel frattempo, la lettura usa la voce di sistema.",
    "aviso_navegador": "Questo browser non ha le funzioni necessarie per la voce naturale. La lettura continua con la voce di sistema.",
    "verificando": "Verifica della voce naturale…",
    "fato_download": "Download unico di {tamanho}. Poi funziona anche senza internet.",
    "fato_wifi": "Meglio con il Wi-Fi. Puoi mettere in pausa e riprendere più tardi.",
    "fato_privacidade": "Il testo del libro non lascia mai il tuo dispositivo.",
    "fato_idiomas": "Parla 31 lingue, tra cui italiano, inglese e portoghese. Le altre lingue continuano con la voce di sistema.",
    "baixar_voz_natural": "Scarica la voce naturale ({tamanho})",
    "licenca_curta": "Modello Supertonic 3 di Supertone, con licenza OpenRAIL-M. Dettagli in Informazioni > Licenze open source.",
    "pode_continuar_usando": "Puoi continuare a leggere durante il download. Se la connessione si interrompe, il download riprende da dove si era fermato.",
    "pausar_download": "Metti in pausa il download",
    "erro_espaco": "Non c’è abbastanza spazio sul dispositivo per completare il download. Libera un po’ di spazio e riprova.",
    "erro_offline": "Al momento non c’è connessione a internet. Ciò che è già stato scaricato viene conservato.",
    "erro_rede": "La connessione si è interrotta durante il download. Ciò che è già stato scaricato viene conservato.",
    "download_pausado": "Download in pausa. Ciò che è già stato scaricato viene conservato.",
    "continuar_download": "Riprendi",
    "descartar": "Elimina",
    "voz_feminina": "Femminile",
    "voz_feminina_desc": "Morbida e calma",
    "voz_masculina": "Maschile",
    "voz_masculina_desc": "Calda e serena",
    "parar_amostra": "Ferma l’anteprima",
    "ouvir_amostra_de": "Ascolta l’anteprima: {voz}",
    "escolha_a_voz": "Scegli la voce",
    "qualidade": "Qualità",
    "q_auto": "Automatica",
    "q_rapida": "Rapida",
    "q_maxima": "Massima",
    "q_auto_desc": "Si adatta alle prestazioni del dispositivo, così la lettura scorre senza pause.",
    "q_rapida_desc": "Genera la voce più in fretta. Ideale per i dispositivi più semplici.",
    "q_maxima_desc": "Il suono più curato. Sui dispositivi più semplici può causare pause tra le frasi.",
    "ocupa": "Occupa {tamanho} su questo dispositivo",
    "remover": "Rimuovi",
    "baixar_pelos_dados": "Scaricare con i dati mobili?",
    "baixar_pelos_dados_msg": "Sembra che il dispositivo non sia connesso al Wi-Fi. Il download è di {tamanho} e potrebbe consumare il tuo piano dati.",
    "baixar_agora": "Scarica comunque",
    "pronta": "La voce naturale è pronta.",
    "download_interrompido": "Il download si è interrotto. Tocca Riprendi quando vuoi.",
    "remover_titulo": "Rimuovere la voce naturale?",
    "descartar_titulo": "Eliminare il download?",
    "remover_msg": "Così liberi {tamanho}. La lettura torna alla voce di sistema e potrai scaricarla di nuovo quando vuoi.",
    "descartar_msg": "Ciò che è già stato scaricato verrà eliminato.",
    "removida": "Voce naturale rimossa da questo dispositivo.",
    "amostra_falhou": "Impossibile riprodurre l’anteprima su questo dispositivo.",
    "amostra": "Ciao! Ecco come suoneranno i tuoi libri con la voce naturale.",
    "pode_demorar_um_minuto": "Può richiedere un minuto.",
    "gerando_voz": "Preparazione della voce…",
    "automatico_idioma": "Automatico ({idioma})",
    "automatico": "Automatico",
    "so_voz_do_sistema": "voce di sistema",
    "aviso_idioma": "Lingua del testo: {idioma}. La voce naturale non parla ancora questa lingua, quindi il libro verrà letto con la voce di sistema.",
    "aviso_idioma_desconhecido": "Impossibile riconoscere la lingua di questo testo. Scegli la lingua qui sotto per usare la voce naturale.",
    "aviso_falha": "Al momento la voce naturale non riesce a funzionare su questo dispositivo. La lettura continua con la voce di sistema.",
    "nao_carregou_usando_sistema": "La voce naturale non si è caricata su questo dispositivo. Lettura con la voce di sistema.",
    "parou_usando_sistema": "La voce naturale si è interrotta. Si continua con la voce di sistema.",
    "aparelho_lento": "Questo dispositivo genera la voce lentamente. Scegli la qualità Rapida per evitare pause.",
    "idioma_do_texto": "Lingua del testo",
    "idioma_do_texto_dica": "Riconosciuta dal testo stesso. Cambiala se la pronuncia non suona bene.",
    "leitura_em_voz_alta": "Lettura ad alta voce",
    "lento_usando_sistema": "La voce naturale è troppo lenta su questo dispositivo. La lettura continua con la voce di sistema.",
    "aviso_lento": "Questo dispositivo non riesce a generare la voce naturale alla velocità della lettura, quindi per ora legge la voce di sistema.",
    "sem_memoria_usando_sistema": "La voce naturale non è entrata nella memoria di questo dispositivo. Legge la voce di sistema.",
    "aviso_falha_memoria": "Non c’era memoria sufficiente per la voce naturale su questo dispositivo. Chiudere altre app e riprovare di solito risolve; nel frattempo legge la voce di sistema.",
    "copiar_detalhe": "Copia il dettaglio",
    "copiado": "Dettaglio copiato.",
    "falhou_titulo": "La voce naturale non si è caricata su questo dispositivo.",
    "falhou_texto": "Il dispositivo non è riuscito a preparare la voce naturale. La lettura continua con la voce di sistema. Per aiutare a risolvere, copia il dettaglio qui sotto e invialo all’assistenza.",
    "falhou_memoria_texto": "Non c’era memoria sufficiente per la voce naturale su questo dispositivo. Chiudere altre app e riprovare di solito risolve.",
    "tentar_de_novo": "Riprova",
    "tentando": "Caricamento…",
    "sondando": "Test della memoria di questo dispositivo…",
    "sonda_explica": "Il test occupa per qualche secondo la memoria che servirà alla voce naturale e la restituisce subito dopo. Così lo scopri adesso e non dopo lo scaricamento.",
    "aviso_aparelho_justo": "Questo dispositivo ha poca memoria per la voce naturale. Potrebbe non caricarsi; in tal caso basta rimuoverla e recuperare lo spazio.",
    "preparando_demora": "Preparazione della voce. Può richiedere qualche minuto.",
    "incompativel_titulo": "La voce naturale non funziona su questo dispositivo.",
    "incompativel_memoria": "Non c’era memoria sufficiente per prepararla. La lettura resta con la voce di sistema, le cui opzioni sono qui sotto. Se vuoi, chiudi altre app e tocca Riprova.",
    "incompativel_lento": "Era troppo lenta per stare al passo con la lettura. La lettura resta con la voce di sistema, le cui opzioni sono qui sotto.",
    "incompativel_queda": "L’app si è chiusa durante il caricamento. La lettura resta con la voce di sistema, le cui opzioni sono qui sotto.",
    "incompativel_falha": "Non è riuscita a caricarsi qui. La lettura resta con la voce di sistema, le cui opzioni sono qui sotto.",
    "testar_de_novo": "Riprova il test",
    "remover_e_liberar": "Rimuovi e libera {tamanho}",
    "tela_durante_a_leitura": "Schermo durante la lettura",
    "manter_tela_ligada": "Tieni lo schermo acceso",
    "manter_tela_ligada_dica": "Finché un libro è aperto, lo schermo non si spegne da solo. Chiudendo il libro, tutto torna come prima."
  }
});
