/* ============================================================
   JAPANESE — ja.js
   ============================================================ */
Idiomas.registrar('ja', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "ブックマークを削除しました。",
    "excluir_marcador": "ブックマークを削除",
    "o_marcador_sera_removido_permanentemen": "ブックマークは完全に削除されます。",
    "excluir_marcador_2": "ブックマークを削除しますか？",
    "pagina_salva": "ページを保存しました",
    "anotacoes": "メモ",
    "citacoes": "引用",
    "item_excluido": "項目を削除しました。",
    "este_registro_sera_removido_permanente": "この登録はライブラリから完全に削除されます。",
    "configuracoes_padrao_restauradas": "既定の設定を復元しました。",
    "leitura_da_esquerda_para_a_direita": "左から右へ読みます。",
    "leitura_da_direita_para_a_esquerda_man": "右から左へ読みます（マンガ）。",
    "a_pagina_inteira_passa_a_caber_na_tela": "ページ全体が画面に収まるようになりました。",
    "a_pagina_passa_a_ocupar_toda_a_largura": "ページが画面の幅いっぱいになりました。",
    "virada_sem_animacao_ativada": "アニメーションなしのページ送りになりました。",
    "virada_deslizante_ativada": "スライド式のページ送りが有効です。",
    "virada_em_folha_real_ativada": "本物の紙のようなページ送りが有効です。",
    "padrao_automatico_cada_formato_abre_no": "自動：各形式がそれに合った方法で開きます。",
    "mudando_durante_a_leitura_o_ajuste_fic": "読書中に変更した場合、その変更はその本だけに保持されます。",
    "automatico_usa_rolagem_horizontal_para": "自動は EPUB、MOBI、TXT、MD とコミックに横方向のページ送りを、PDF と DOCX に縦スクロールを使います。",
    "este_livro": "この本",
    "armazenamento_local_indisponivel_neste": "このブラウザではローカルストレージが使えません。",
    "o_aplicativo_pode_procurar_os_livros_q": "アプリはお使いの端末にある本を探せます。",
    "vamos_montar_sua_estante": "本棚を埋めてみましょうか？",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "同意がないとアプリは使えません。",
    "precisamos_do_seu_aceite": "同意が必要です",
    "antes_de_comecar_leia_e_aceite_os_docu": "始める前に以下の文書をお読みいただき、同意してください。",
    "selecionar_todos": "すべて選択",
    "limpar_selecao": "選択を解除",
    "todos_parecem_ja_estar_na_sua_estante": "どれもすでに本棚にあるようです。",
    "lendo_a_pasta_escolhida": "選択したフォルダを読み込んでいます…",
    "procurando_livros": "本を探しています",
    "nao_foi_possivel_concluir_a_busca_no_d": "この端末での検索を完了できませんでした。",
    "tente_outra_pasta_do_aparelho": "端末の別のフォルダを試してください。",
    "nenhum_livro_encontrado": "本が見つかりません",
    "use_o_botao_para_escolher_os_arquivos": "+ ボタンでファイルを手動で選びます。Android スマホの Chrome なら通常フォルダ全体を選べます。",
    "seu_navegador_nao_permite_ler_pastas": "お使いのブラウザはフォルダを読めません",
    "busca_automatica_indisponivel": "自動検索は使えません",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB、MOBI、CBZ、CBR、M4B",
    "termos_de_uso": "利用規約",
    "politica_de_privacidade": "プライバシーポリシー",
    "um_minuto_agora_evita_perder_o_progres": "今の1分が、あとで進行状況や印を失うのを防ぎます。",
    "ver_estante": "本棚を見る",
    "modo_juntar": "統合モード",
    "modo_substituir": "置換モード",
    "restauracao_concluida": "復元が完了しました",
    "tente_de_novo_com_o_arquivo_original": "元のファイルで再度お試しください。",
    "a_restauracao_nao_pode_ser_concluida": "復元を完了できませんでした",
    "devolvendo_o_seu_progresso_e_as_suas_m": "進行状況と印を戻しています...",
    "restaurar_este_backup": "このバックアップを復元しますか？",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Veredas が保存した .zip、または共有で受け取った .txt を選んでください。",
    "nao_foi_possivel_ler_este_arquivo": "このファイルを読めませんでした",
    "lendo_o_backup": "バックアップを読み込んでいます",
    "backup_do_veredas_reader": "Veredas Reader バックアップ",
    "arquivo_de_transporte_txt_contendo_os": "ZIP と同じ内容を含む、.txt 形式のバックアップのコピー",
    "nao_foi_possivel_montar_o_arquivo_de_b": "バックアップファイルを作成できませんでした。",
    "escolher_o_app": "アプリを選ぶ",
    "vale_conferir_o_que_vai_no_arquivo": "ファイルの中身を確認する価値があります",
    "enviar_para_outro_app": "他のアプリへ送る",
    "salvar_o_arquivo": "ファイルを保存",
    "o_navegador_aqui_nao_oferece_o_compart": "ここのブラウザは直接共有を提供していません。ファイルを保存し、あとで好きなアプリで送れます。",
    "este_aparelho_nao_abre_a_lista_de_apli": "この端末はアプリ一覧を開きません",
    "importe_pelo_menos_um_livro_antes_de_f": "バックアップを作る前に少なくとも一冊取り込んでください。",
    "estante_vazia": "空の本棚",
    "nao_deu_para_copiar": "コピーできませんでした",
    "copiar_detalhes": "詳細をコピー",
    "o_backup_foi_salvo_assim_mesmo": "それでもバックアップは保存されました",
    "o_aparelho_recusou_abrir_a_lista": "共有リストを開けませんでした",
    "sem_detalhes_do_navegador": "ブラウザからの詳細なし",
    "o_sistema_nao_aceitou_receber_o_arquiv": "端末のシステムがファイルを受け取れませんでした。",
    "o_navegador_considerou_a_situacao_inse": "ブラウザ独自のセキュリティルールにより、共有がブロックされました。ファイルを保存して、お好きなアプリで送ってください。",
    "o_compartilhamento_so_funciona_em_ende": "共有は安全なアドレスでのみ機能します。このアプリは普通の http:// で開かれており、その場合ブラウザは他のアプリへの送信をブロックします。",
    "este_navegador_nao_conseguiu_iniciar_o": "このブラウザでは共有を開けませんでした。ファイルを保存して、お好きなアプリで送ってください。",
    "o_navegador_recebeu_um_arquivo_em_form": "ブラウザで共有先アプリの一覧が開きませんでした。もう一度ボタンをタップするか、ファイルを保存してお好きなアプリで送ってください。",
    "nao_foi_possivel_gerar_o_backup": "バックアップを作成できませんでした。",
    "reunindo_a_sua_estante": "本棚を集めています...",
    "preparando_o_backup": "バックアップを準備しています",
    "pronto_nada_mais_esta_esperando": "完了 — 保留中の項目はありません。",
    "o_progresso_e_as_marcacoes_desses_livr": "これらの本の進行状況と印は消えます。後でファイルを取り込むと、空の状態で戻ります。",
    "descartar_o_que_esta_esperando": "保留中のデータを削除しますか？",
    "lembretes_de_backup_religados": "バックアップのリマインダーを再びオンにしました。",
    "sem_titulo": "無題",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "リマインダーをオフにしました。",
    "manter_ligado": "オンのまま",
    "desligar_assim_mesmo": "それでもオフにする",
    "o_botao_de_salvar_continua_onde_sempre": "保存ボタンはいつもの場所、バックアップと復元にあります。",
    "o_lembrete_e_o_unico_aviso_que_existe": "リマインダーが唯一のお知らせです。オフにすると、バックアップのタイミングはご自身で覚えておく必要があります。\n\n",
    "limpar_os_dados_do_navegador_desinstal": "ブラウザのデータを消去したり、アプリをアンインストールしたり、機種変更をしたり、端末が故障したりすると、進行状況、ハイライト、引用、メモ、ブックマークは復元できなくなります。\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "本棚はこの端末にのみ保存されています。サーバーにコピーはないため、失われた場合は復元できません。\n\n",
    "leia_antes_de_confirmar": "確認する前にお読みください",
    "desligar_os_lembretes_de_backup": "バックアップのリマインダーをオフにしますか？",
    "progresso_de_leitura_restaurado_neste": "この本の読書進行状況を復元しました。",
    "pronto": "完了。",
    "aplicando_as_suas_preferencias": "設定を適用しています...",
    "atualize_o_veredas_reader_e_tente_de_n": "Veredas Reader を更新して再度お試しください。",
    "este_backup_foi_feito_numa_versao_mais": "このバックアップはアプリのより新しいバージョンで作られました。",
    "este_arquivo_nao_e_um_backup_de_biblio": "このファイルは Veredas ライブラリのバックアップではありません。",
    "o_conteudo_interno_nao_pode_ser_lido": "内部の内容を読めませんでした。",
    "o_backup_esta_corrompido": "バックアップが壊れています。",
    "falta_o_arquivo_biblioteca_json_la_den": "中に biblioteca.json ファイルがありません。",
    "este_arquivo_nao_parece_ser_um_backup": "このファイルは Veredas バックアップに見えません。",
    "compactando": "圧縮しています...",
    "para_restaurar_menu_lateral_backup_e_r": "復元するには：サイドメニュー > バックアップと復元 > バックアップを復元。",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas が印と読み終えた位置を自動的に復元します。",
    "importe_os_livros_normalmente_no_aplic": "アプリで本を通常どおり取り込みます：各ファイルを認識すると、",
    "ele_nao_contem_os_arquivos_dos_livros": "本のファイルは含まれていません。完全に復元するには、",
    "as_notas_os_marcadores_e_a_organizacao": "あなたのメモ、ブックマーク、本棚の構成。",
    "este_arquivo_guarda_o_seu_progresso_de": "このファイルはあなたの読書進行状況、ハイライト、引用、",
    "verificando_se_sao_partes_do_mesmo_aud": "同じオーディオブックの一部か確認しています...",
    "analisando_os_arquivos": "ファイルを読み込んでいます",
    "nao_foi_possivel_salvar_o_audiolivro": "オーディオブックを保存できませんでした。",
    "audiolivros_grandes_podem_levar_alguns": "大きなオーディオブックは少し時間がかかります...",
    "salvando_na_sua_estante": "本棚に保存しています",
    "falha_ao_processar_os_arquivos": "ファイルを処理できませんでした。",
    "falha_ao_processar_o_arquivo": "ファイルを処理できませんでした。",
    "nao_foi_possivel_salvar_o_quadrinho": "コミックを保存できませんでした。",
    "quase_la": "もうすぐ...",
    "falha_ao_processar_o_quadrinho": "コミックを処理できませんでした。",
    "autor_desconhecido": "作者不明",
    "lendo_o_quadrinho": "コミックを読んでいます...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "本をライブラリに保存できませんでした。",
    "nao_foi_possivel_ler_o_pdf": "PDF を読めませんでした。",
    "lendo_o_pdf": "PDF を読み込んでいます...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "古い .doc なら Word で開き、.docx として保存してから取り込んでください。",
    "este_arquivo_nao_e_um_docx_valido": "このファイルは有効な .docx ではありません。",
    "livros_com_protecao_da_amazon_nao_pode": "Amazon の保護がかかった本はここで開けません。DRM なしのコピーを使うか、EPUB に変換してください。",
    "este_arquivo_esta_protegido_por_drm": "このファイルは DRM で保護されています。",
    "confira_se_a_extensao_corresponde_ao_c": "拡張子が中身と一致しているか確認するか、本を EPUB に変換してください。",
    "este_arquivo_nao_e_um_mobi_valido": "このファイルは有効な MOBI ではありません。",
    "nao_foi_possivel_ler_o_arquivo": "ファイルを読めませんでした。",
    "formato_nao_suportado": "対応していない形式です。",
    "falha_ao_salvar_o_livro_na_biblioteca": "本をライブラリに保存できませんでした。",
    "livro_importado_e_salvo_no_dispositivo": "本を取り込み、この端末に保存しました。",
    "audiolivro_importado_e_salvo_no_dispos": "オーディオブックを取り込み、この端末に保存しました。",
    "quadrinho_importado_e_salvo_no_disposi": "コミックを取り込み、この端末に保存しました。",
    "salvando_na_sua_estante_2": "本棚に保存しています...",
    "importando_livro": "本を取り込んでいます",
    "importar_mesmo_assim": "それでも取り込む",
    "parece_que_este_livro_ja_esta_na_estan": "この本はすでに本棚にあるようです",
    "este_livro_ja_esta_na_estante": "この本はすでに本棚にあります",
    "video_importado_e_salvo_no_dispositivo": "動画を取り込み、この端末に保存しました。",
    "importacao_cancelada": "取り込みをキャンセルしました。",
    "preparando_o_arquivo": "ファイルを準備しています",
    "importando_audiolivro": "オーディオブックを取り込んでいます",
    "importacao_concluida": "取り込みが完了しました",
    "importacao_interrompida": "取り込みが中断されました",
    "a_importacao_foi_interrompida_o_que_ja": "取り込みが中断されました。すでに入ったものは本棚に残ります。",
    "finalizando": "仕上げています…",
    "nao_foi_possivel_ler_o_arquivo_2": "ファイルを読めませんでした",
    "importando_livros": "本を取り込んでいます",
    "livros_quadrinhos_documentos_audiolivr": "本、コミック、文書、オーディオブック、動画",
    "series": "シリーズ",
    "colecoes": "コレクション",
    "organizacao_salva": "整理内容を保存しました。",
    "informe_um_nome_para_o_livro_antes_de": "保存する前に本に名前を付けてください。",
    "nome_do_livro_obrigatorio": "本の名前が必要です",
    "importe_um_livro_primeiro": "先に本を取り込んでください。",
    "citacao": "引用",
    "anotacao": "メモ",
    "citacao_2": "引用",
    "anotacao_2": "メモ",
    "uma_citacao": "引用",
    "uma_anotacao": "メモ",
    "o_marcador_sera_removido_da_biblioteca": "ブックマークはライブラリから削除されますが、本のファイルはそのままです。",
    "marcador_de_audio": "音声ブックマーク",
    "marcador_de_video": "動画ブックマーク",
    "nao_foi_possivel_excluir_o_livro": "本を削除できませんでした。",
    "livro_excluido_da_biblioteca": "本をライブラリから削除しました。",
    "excluir_livro": "本を削除",
    "isso_remove_apenas_a_copia_armazenada": "これはライブラリが保存しているコピーと、進行状況、ブックマーク、メモだけを削除します。あなたのフォルダにある元のファイルは削除されません。",
    "excluir_livro_2": "本を削除しますか？",
    "ordem_personalizada_salva": "カスタム順を保存しました。",
    "ordem_manual_da_sua_estante": "自分で決めた順に本棚を並べます。",
    "agrupamento_alterado_para_minha_ordem": "グループ化を「マイオーダー」に切り替えました。",
    "nova_ordem_salva": "新しい順を保存しました。",
    "nao_foi_possivel_salvar_a_nova_ordem": "新しい順を保存できませんでした。",
    "baixar_automaticamente": "自動でダウンロード",
    "escolha_livremente_onde_o_arquivo_sera": "ファイルをどこに書き出すか自由に選んでください。",
    "salvar_epub": "EPUB を保存",
    "livro_epub": "EPUB の本",
    "erro_desconhecido": "不明なエラー",
    "a_permissao_para_salvar_o_arquivo_foi": "ファイルを保存する許可が取り消されました。ライブラリの内容は何も変わっていません。",
    "conversao_cancelada_o_pdf_original_per": "変換をキャンセルしました。元の PDF はライブラリに残ります。",
    "preparando_salvamento": "保存を準備しています…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "PDF のコピーがライブラリにありません。",
    "reconstruindo_o_livro_localmente": "端末上で本を再構築しています。",
    "convertendo_pdf": "PDF を変換しています",
    "nao_foi_possivel_compartilhar_o_livro": "本を共有できませんでした。",
    "o_arquivo_foi_preparado_para_voce_comp": "ファイルは他のアプリで共有できるように準備されました。",
    "livro_compartilhado": "本を共有しました。",
    "a_copia_deste_livro_nao_esta_disponive": "この本のコピーはライブラリにありません。",
    "para_manter_a_politica_de_compartilham": "ライブラリの共有ポリシーを守るため、EPUB と MOBI ファイルはこのアプリでは共有できません。",
    "quadrinhos_ficam_guardados_somente_no": "コミックはあなたの端末にだけ保存され、このアプリで共有できません。",
    "audiolivros_e_videos_ficam_guardados_s": "オーディオブックと動画はあなたの端末にだけ保存され、このアプリで共有できません。",
    "formato_protegido": "保護された形式",
    "compartilhamento_indisponivel": "共有できません",
    "concluido": "完了",
    "ainda_nao_comecado": "まだ始まっていません",
    "continue_lendo": "読み続ける",
    "continue_ouvindo": "聴き続ける",
    "continue_assistindo": "観続ける",
    "comece_por_aqui": "ここから始める",
    "comece_a_ouvir": "聴き始める",
    "comece_a_assistir": "観始める",
    "no_total": "全体",
    "para_ler": "読むもの",
    "sua_estante": "本棚",
    "livros_organizados_pela_opcao_selecion": "選んだオプションで並べた本。",
    "uma_prateleira_para_cada_tipo_de_arqui": "ファイルの種類ごとに一棚。",
    "autores_agrupados_em_ordem_alfabetica": "著者をアルファベット順にグループ化。",
    "toque_para_continuar_de_onde_parou": "タップして続きから読む。",
    "para_ler_2": "読むもの",
    "lendo_agora": "いま読んでいる",
    "audio_e_video": "音声と動画",
    "trechos_salvos_separadamente_dos_marca": "ブックマークとは別に保存した一節。",
    "comentarios_vinculados_a_trechos_selec": "選んだ一節に結びついたコメント。",
    "paginas_salvas_para_voltar_rapidamente": "すぐ戻れるように保存したページ。",
    "do_maior_para_o_menor_progresso_de_lei": "読書の進み具合が多い順に。",
    "livros_adicionados_ou_lidos_mais_recen": "最近追加した、または読んだ本。",
    "ordem_alfabetica_pelo_titulo": "タイトルのアルファベット順。",
    "separa_em_prateleiras_de_epub_pdf_docx": "EPUB、PDF、DOCX、オーディオブック、動画…の棚に分けます。",
    "tipo_de_arquivo": "ファイルの種類",
    "organiza_e_separa_os_livros_por_autor": "本を著者ごとに整理して分けます。",
    "agrupar_por_autor": "著者でグループ化",
    "pressione_o_livro_e_mova_o": "本を長押しして動かします。",
    "minha_ordem": "マイオーダー",
    "epub_pronto": "EPUB 準備完了",
    "conversao_concluida": "変換が完了しました",
    "necessario_para_salvar_o_epub_ao_lado": "元のファイルの隣に EPUB を保存するために必要",
    "escolha_a_pasta_do_pdf": "PDF のフォルダを選ぶ",
    "processando": "処理中…",
    "processamento_local_no_navegador": "お使いの端末で、ブラウザ内で処理します",
    "convertendo_livro": "本を変換しています",
    "livro_em_pdf": "PDF の本",
    "recalculando_paginas": "ページを再計算しています...",
    "ajustando_leitura": "レイアウトを調整しています",
    "abrir_comentario": "コメントを開く",
    "anotacao_salva": "メモを保存しました。",
    "anotacao_atualizada": "メモを更新しました。",
    "escreva_uma_nota_antes_de_salvar": "保存する前にメモを書いてください。",
    "nao_foi_possivel_compartilhar": "共有できませんでした。",
    "compartilhamento_indisponivel_2": "共有できません。",
    "credito_do_trecho": "——{obra}／{autor}",
    "credito_do_trecho_sem_autor": "——{obra}",
    "trecho_copiado": "一節をコピーしました。",
    "trecho_compartilhado": "一節を共有しました。",
    "citacao_salva": "引用を保存しました。",
    "trecho_grifado": "一節をハイライトしました。",
    "grifo_removido": "ハイライトを削除しました。",
    "comentario_apagado": "コメントを削除しました。",
    "remover_grifo": "ハイライトを外す",
    "apagar_comentario": "コメントを削除",
    "remover_grifo_2": "ハイライトを外しますか？",
    "apagar_comentario_2": "コメントを削除しますか？",
    "remover_este_grifo": "このハイライトを外しますか？",
    "apagar_este_comentario": "このコメントを削除しますか？",
    "sem_comentario": "コメントなし",
    "comentario": "コメント",
    "marcador_removido_desta_pagina": "このページからブックマークを外しました。",
    "pagina_adicionada_aos_marcadores": "ページをブックマークに追加しました。",
    "este_e_o_inicio_do_livro": "ここが本の始まりです。",
    "esta_e_a_primeira_pagina": "これが最初のページです。",
    "voce_chegou_ao_fim_do_livro": "本の終わりに来ました。",
    "voce_chegou_ao_fim_do_quadrinho": "コミックの終わりに来ました。",
    "agora_em_revista_aberta_duas_paginas_l": "見開き表示になりました：2ページが並び、表紙は別です。",
    "leitura_horizontal_ativada_neste_livro": "この本では横読みが有効です。",
    "rolagem_vertical_ativada_neste_livro": "この本では縦スクロールが有効です。",
    "leitura_pagina_a_pagina_ativada_neste": "このコミックでは1ページずつの読み方が有効です。",
    "rolagem_continua_ativada_neste_quadrin": "このコミックでは連続スクロールが有効です。",
    "mudar_para_rolagem_vertical": "縦スクロールに切り替える",
    "mudar_para_leitura_horizontal": "横読みに切り替える",
    "rolagem_continua_estilo_webtoon": "連続スクロール（Webtoon 風）",
    "voltar_para_pagina_a_pagina": "1ページずつに戻す",
    "separando_os_capitulos": "章を分けています...",
    "lendo_o_livro": "本を読み込んでいます",
    "lendo_o_markdown": "Markdown を読んでいます",
    "lendo_o_documento": "文書を読んでいます",
    "pagina_indisponivel": "ページを利用できません。",
    "isto_acontece_so_desta_vez": "これは今回だけです。",
    "preparando_o_quadrinho": "コミックを準備しています",
    "abrindo_o_quadrinho": "コミックを開いています...",
    "montando_as_paginas": "ページを組み立てています...",
    "nao_foi_possivel_abrir_este_livro": "この本を開けませんでした。",
    "abertura_cancelada": "開くのをキャンセルしました。",
    "o_livro_demorou_demais_para_abrir_e_fo": "本を開くのに時間がかかりすぎたため中断しました。",
    "importe_o_arquivo_novamente_para_conti": "読み続けるにはファイルをもう一度取り込んでください。",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "この本のファイルはもう端末に保存されていません。",
    "preparando_sua_leitura": "本を準備しています...",
    "abrindo_livro": "本を開いています",
    "leitura_concluida": "読了しました。",
    "a_voz_foi_interrompida_pelo_navegador": "ブラウザが音声を中断しました。",
    "nao_foi_possivel_preparar_este_trecho": "この一節を音声用に準備できませんでした。",
    "a_leitura_em_voz_alta_nao_e_suportada": "このブラウザは読み上げに対応していません。",
    "pausar_leitura": "読み上げを一時停止",
    "em_pausa": "一時停止中",
    "leitura_em_voz_alta_nao_disponivel_nes": "このブラウザでは読み上げを利用できません",
    "nome_do_marcador": "ブックマークの名前",
    "o_marcador_sera_removido_deste_audioli": "このオーディオブックからブックマークを外します。",
    "nao_foi_possivel_salvar_o_marcador": "ブックマークを保存できませんでした。",
    "ja_existe_um_marcador_neste_ponto": "この場所にはもうブックマークがあります。",
    "timer_de_sono_encerrado": "スリープタイマーが終了しました。",
    "fim_do_cap": "章の終わり",
    "timer_desativado": "タイマーをオフにしました。",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "音声は章の終わりで一時停止します。",
    "este_audiolivro_nao_tem_capitulos": "このオーディオブックには章がありません。",
    "ao_fim_do_capitulo": "章の終わりに",
    "desativar_timer": "タイマーをオフ",
    "mais_10_minutos_no_timer": "タイマーに 10 分追加しました。",
    "somar_10_minutos": "10 分追加",
    "pausa_ao_fim_do_capitulo": "章の終わりに一時停止",
    "no_livro_todo": "本全体で",
    "video": "動画",
    "audiolivro_concluido": "オーディオブックが終了しました。",
    "video_concluido": "動画が終了しました。",
    "video_2": "動画",
    "audio": "音声",
    "toque_em_reproduzir_para_comecar": "再生をタップして始めます。",
    "falha_ao_carregar_o_audio": "音声を読み込めませんでした。",
    "exclua_o_da_biblioteca_e_importe_o_arq": "ライブラリから削除してファイルをもう一度取り込んでください。",
    "os_nomes_dos_arquivos_seguem_uma_seque": "ファイル名が順番どおりなので、1 つのオーディオブックの章のように見えます。",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "ファイルのタグに同じアルバムがあるので、1 つのオーディオブックの章のように見えます。",
    "libere_espaco_ou_exclua_livros_da_bibl": "空きを作るかライブラリから本を削除して、もう一度お試しください。",
    "o_armazenamento_do_aparelho_esta_cheio": "端末のストレージが一杯です。",
    "preparando_a_capa": "表紙を準備しています...",
    "remova_esse_arquivo_da_selecao_e_tente": "そのファイルを選択から外して、もう一度お試しください。",
    "sequencia": "順序",
    "o_arquivo_pode_estar_incompleto_tente": "ファイルが不完全かもしれません。もう一度ダウンロードしてみてください。",
    "conferindo_se_o_audio_pode_ser_reprodu": "音声を再生できるか確認しています...",
    "conferindo_se_o_video_pode_ser_reprodu": "動画を再生できるか確認しています...",
    "lendo_titulo_capitulos_e_capa": "タイトル、章、表紙を読んでいます...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "ファイルが破損しているか、ブラウザで再生できない音声形式の可能性があります。MP3 または M4B（AAC）に変換してみてください。",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "ファイルが破損しているか、ブラウザで再生できない動画形式の可能性があります。H.264 動画と AAC 音声の MP4 に変換してみてください。",
    "converta_o_audiolivro_para_m4b_com_aud": "オーディオブックを AAC 音声の M4B（または MP3）に変換して再度取り込んでください。",
    "converta_o_video_para_mp4_com_audio_aa": "動画を AAC 音声と H.264 動画の MP4 に変換して再度取り込んでください。",
    "o_navegador_nao_reproduz_o_formato_de": "ブラウザがこのファイルの音声形式を再生しません。",
    "arquivos_com_protecao_nao_podem_ser_re": "保護されたファイルはここで再生できません。DRM なしのコピーをお使いください。",
    "nao_ha_espaco_suficiente_no_aparelho_p": "このオーディオブックのための空きが端末に足りません。",
    "confira_se_a_extensao_corresponde_ao_c_2": "拡張子が中身と一致しているか確認するか、音声を MP3 または M4B（AAC）に変換してください。",
    "imagem_invalida": "無効な画像",
    "imagem_demorou_demais": "画像の読み込みに時間がかかりすぎました",
    "imagem_vazia": "空の画像",
    "inicio": "始まり",
    "mp4_moov_nao_encontrado": "動画が不完全か、破損しているようです。",
    "pagina": "ページ",
    "esta_pagina_nao_esta_disponivel": "このページは利用できません。",
    "esta_pagina_nao_pode_ser_descompactada": "このページを展開できませんでした。",
    "quadrinho_fechado": "コミックを閉じました。",
    "ele_pode_estar_incompleto_dividido_em": "不完全か、複数の部分に分かれているか、アプリが認識しない RAR の変種かもしれません。CBZ に変換すると通常は直ります。",
    "remova_a_senha_do_arquivo_e_importe_de": "ファイルからパスワードを外して再度取り込んでください。",
    "nao_foi_possivel_ler_este_arquivo_de_q": "このコミックファイルを読めませんでした。",
    "este_quadrinho_esta_protegido_por_senh": "このコミックはパスワードで保護されています。",
    "lendo_o_indice_do_quadrinho": "コミックの目次を読んでいます...",
    "o_arquivo_pode_ser_grande_demais_para": "ファイルがこの端末のメモリには大きすぎるかもしれません。コミックを小さく分けると通常は直ります。",
    "nao_foi_possivel_abrir_este_quadrinho": "このコミックを開けませんでした。",
    "lendo_o_arquivo": "ファイルを読んでいます...",
    "preparando_o_leitor_de_cbr": "CBR リーダーを準備しています...",
    "o_arquivo_pode_estar_incompleto_proteg": "ファイルが不完全か、パスワード保護されているか、壊れている可能性があります。",
    "nao_foi_possivel_ler_este_quadrinho": "このコミックを読めませんでした。",
    "o_arquivo_precisa_conter_imagens_jpg_p": "ファイルには画像（JPG、PNG、WEBP、GIF）が必要です。",
    "nao_encontramos_paginas_dentro_deste_q": "このコミックにページが見つかりませんでした。",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "このコミックのための空きが端末に足りません。",
    "cabecalho_de_item_invalido": "ファイルの一部が破損しています。",
    "a_pasta_vendor_libarchive_precisa_esta": "このコミックを開くのに必要なアプリの部品が見つかりません。CBZ に変換するか、アプリを再インストールしてください。",
    "o_leitor_de_cbr_nao_foi_encontrado": "CBR リーダーが見つかりませんでした。",
    "converta_o_quadrinho_para_cbz_zip_e_im": "コミックを CBZ（ZIP）に変換して再度取り込んでください。",
    "este_navegador_nao_consegue_abrir_arqu": "このブラウザは CBR ファイルを開けません。",
    "convertendo_o_markdown": "Markdown を変換しています",
    "lendo_o_texto": "テキストを読んでいます",
    "pdf_indisponivel": "PDF を利用できません。",
    "epub_invalido_nenhum_capitulo_no_spine": "この EPUB は破損しているため、本の章が見つかりませんでした。",
    "livro_sem_titulo": "無題の本",
    "epub_invalido_arquivo_opf_nao_encontra": "この EPUB は不完全か破損しているため、開けません。",
    "epub_invalido_container_xml_nao_encont": "この EPUB は不完全か破損しているため、開けません。",
    "organizando_o_texto": "テキストを配置しています",
    "descompactando_o_livro": "本を展開しています",
    "nao_encontramos_conteudo_para_exibir_n": "このファイルに表示する内容が見つかりませんでした。",
    "livro_sem_texto_legivel": "読めるテキストのない本",
    "o_arquivo_pode_estar_corrompido_tente": "ファイルが壊れているかもしれません。EPUB への変換をお試しください。",
    "nao_foi_possivel_extrair_o_texto_deste": "この MOBI からテキストを取り出せませんでした。",
    "nenhum_registro_de_conteudo_foi_encont": "このファイルに本の本文が見つかりませんでした。",
    "arquivo_mobi_sem_texto": "テキストのない MOBI ファイル。",
    "o_dicionario_de_compressao_esta_vazio": "この MOBI の内容の一部が欠けています。",
    "arquivo_mobi_incompleto": "不完全な MOBI ファイル。",
    "as_tabelas_de_compressao_nao_foram_enc": "この MOBI の内容の一部が欠けています。",
    "converta_o_arquivo_para_epub_em_um_pro": "Calibre などのプログラムでファイルを EPUB に変換し、再度取り込んでください。",
    "compressao_mobi_nao_reconhecida": "この MOBI は、アプリが認識できない内部形式を使っています。",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "本のヘッダーを読めませんでした。",
    "arquivo_mobi_corrompido": "壊れた MOBI ファイル。",
    "a_lista_interna_de_registros_esta_inco": "ファイルが不完全です。もう一度ダウンロードするか、変換し直してみてください。",
    "o_download_parece_ter_sido_interrompid": "ダウンロードが中断されたようです。もう一度ダウンロードしてください。",
    "tabela_de_compressao_mobi_corrompida": "この MOBI ファイルの一部が破損しています。",
    "tabela_de_compressao_mobi_incompleta": "この MOBI ファイルは不完全です。",
    "tabela_de_compressao_mobi_invalida": "この MOBI ファイルの一部が破損しています。",
    "este_arquivo_docx_nao_tem_conteudo_de": "この .docx ファイルには表示できるテキスト内容がありません。",
    "documento_sem_texto": "テキストのない文書",
    "o_arquivo_pode_estar_corrompido_proteg": "ファイルが壊れているか、パスワード保護されているか、古い .doc かもしれません。.docx として保存し直して、もう一度取り込んでください。",
    "nao_foi_possivel_ler_este_arquivo_docx": "この DOCX ファイルを読めませんでした。",
    "convertendo_o_documento": "文書を変換しています",
    "conecte_se_a_internet_uma_vez_para_bai": "必要なコンポーネントをダウンロードするため、一度インターネットに接続してから、本をもう一度開いてください。",
    "o_conversor_de_docx_nao_carregou": "DOCX コンバーターが読み込まれませんでした。",
    "video_mp4": "動画（MP4）",
    "audiolivro_m4b": "オーディオブック（M4B）",
    "audiolivro_mp3": "オーディオブック（MP3）",
    "quadrinho_cbt": "コミック（CBT）",
    "quadrinho_cb7": "コミック（CB7）",
    "quadrinho_cbr": "コミック（CBR）",
    "quadrinho_cbz": "コミック（CBZ）",
    "markdown_md": "Markdown（MD）",
    "texto_txt": "テキスト（TXT）",
    "word_docx": "Word（DOCX）",
    "gravacao_cancelada": "保存をキャンセルしました。",
    "o_arquivo_esta_vindo_do_armazenamento": "ファイルをクラウドストレージから端末にダウンロードしています。",
    "baixando_o_arquivo": "ファイルをダウンロードしています",
    "cancelando": "キャンセルしています...",
    "use_grifar_citacao_anotar_ou_marcador": "読書中にハイライト、引用、メモ、ブックマークを使ってください。",
    "nenhuma_marcacao_ainda": "まだ印がありません",
    "trecho_original": "元の一節",
    "procurar_meus_livros": "自分の本を探す",
    "a_busca_fica_sempre_disponivel_no_menu": "検索はいつもサイドメニューのシステムの下にあります。",
    "da_para_fazer_depois": "あとでできます",
    "nada_entra_na_estante_sem_a_sua_confir": "あなたの確認なしに本棚には何も入りません：一覧を見て、取り込むものを選びます。",
    "voce_revisa_antes": "取り込む前に自分で確認できます",
    "escolha_uma_pasta_downloads_e_um_bom_c": "フォルダーを選ぶと、その中とすべてのサブフォルダーを探します。",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "EPUB、MOBI、CBZ、CBR、M4B を検索",
    "voltar_e_revisar": "戻って確認",
    "ler_os_termos": "規約を読む",
    "ler_a_politica": "ポリシーを読む",
    "os_dois_documentos_ficam_sempre_dispon": "両方の文書はいつもサイドメニューの情報の下にあります。",
    "leia_com_calma": "ゆっくり読んでください",
    "a_politica_e_os_termos_explicam_como_o": "ポリシーと規約では、アプリが本をどのように保管するか、また本をどのように利用できるかを説明しています。ライブラリを使うには、これらに同意していただく必要があります。",
    "nada_acontece_sem_o_aceite": "始めるには、規約への同意が必要です",
    "aceitar_e_continuar": "同意して続ける",
    "nao_aceito": "同意しません",
    "termos_de_uso_2": "利用規約",
    "politica_de_privacidade_2": "プライバシーポリシー",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "アプリがアクセスするのは、選択したファイルとフォルダだけです。それも選択したときに限ります。",
    "voce_no_controle": "主導権はあなたに",
    "depois_de_importar_um_livro_voce_le_se": "本を取り込んだら、インターネットなしで読めます。",
    "funciona_offline": "オフラインで動きます",
    "livros_marcacoes_e_progresso_sao_guard": "本、印、進行状況は端末に保管されます。私たちのサーバーには何も送りません。",
    "tudo_fica_no_seu_aparelho": "すべてはあなたの端末に残ります",
    "escolha_o_que_deseja_adicionar_a_bibli": "ライブラリに追加したいものを選んでください。すでに本棚にあるものと同じファイルは自動で飛ばされます。",
    "voce_pode_tentar_outra_pasta_ou_import": "別のフォルダを試すか、+ ボタンでファイルを取り込めます。",
    "a_leitura_acontece_so_no_seu_dispositi": "読み取りはこの端末の中だけで行われます。",
    "voce_escolhe_a_pasta": "あなたがフォルダを選ぶ",
    "tema_tipografia_margens_modo_de_virada": "テーマ、書体、余白、ページ送りの方式、音声設定。",
    "restaurar_minhas_preferencias": "自分の設定を復元",
    "o_backup_manda_as_marcacoes_atuais_dos": "バックアップが優先します。ファイルにある本の現在の印は、バックアップのものと置き換わります。",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "何も消えません。両側の印が合わさり、より新しい進行状況が優先します。",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "すでに本棚にあるものをどうするか",
    "grifos_citacoes_e_notas": "ハイライト、引用、メモ",
    "preparando_o_arquivo_2": "ファイルを準備しています...",
    "os_livros_em_si_nem_as_capas_por_isso": "本のファイルも表紙も含まれません。そのため、ファイルのサイズは数 KB だけです。受け取った人の手元に本のファイルがあれば印が元の場所に戻り、表紙は本を取り込んだときに自動的に表示されます。",
    "nao_vai_no_arquivo": "ファイルに含まれない",
    "o_seu_progresso_de_leitura_os_grifos_a": "あなたの読書進行状況、ハイライト、引用、メモ、ブックマーク、本棚の構成 — 状態、お気に入り、コレクション、シリーズ、タグ。",
    "vai_no_arquivo": "ファイルに含まれる",
    "descartar_o_que_esta_esperando_2": "保留中のデータを削除",
    "esperando_o_arquivo": "ファイルを待っています",
    "avisar_quando_fizer_tempo_sem_backup": "バックアップなしでしばらく経ったら知らせる",
    "livros_que_ainda_nao_estiverem_na_esta": "まだ本棚にない本は保留として保管されます。その本のファイルを取り込むと、印が自動的に戻ります。",
    "restaurar_backup": "バックアップを復元",
    "salvar_backup": "バックアップを保存",
    "ainda_nao_ha_itens": "まだ何もありません",
    "arraste_um_livro_para_outra_posicao_na": "本を本棚の別の位置へドラッグして、自分だけの順を保存します。この手動の順は著者ごとのグループ化より優先されます。",
    "separe_por_virgulas": "カンマで区切る",
    "ex_estudos_ficcao": "例：勉強、フィクション...",
    "pasta_estante": "フォルダ / 本棚",
    "ex_trilogia": "例：三部作...",
    "serie": "シリーズ",
    "aparece_em_favoritos": "お気に入りに表示されます。",
    "nome_do_livro": "本の名前",
    "nenhum_registro_ainda": "まだ登録がありません",
    "no_leitor_toque_no_icone_de_marcador_p": "リーダーで、ページを保存するにはブックマークのアイコンをタップします。",
    "nenhum_marcador_ainda": "まだブックマークがありません",
    "a_gravacao_e_independente_da_localizac": "保存は PDF の場所に左右されず、元のファイルを変えません。",
    "o_pdf_original_nao_precisa_estar_nessa": "元の PDF はそのフォルダにある必要はありません",
    "excluir_da_biblioteca": "ライブラリから削除",
    "adicionar_livro": "本を追加",
    "adicione_livros_e_acompanhe_o_que_esta": "本を追加して、何が待ちで、何が進行中で、どこまで進んだかを追いかけます。",
    "tudo_pronto_para_a_proxima_leitura": "次の読書の準備ができました。",
    "sua_biblioteca": "マイライブラリ",
    "arraste_um_livro_para_reposiciona_lo_a": "本をドラッグして動かすと、本棚がマイオーダーに切り替わり、並びを保ちます。",
    "importe_um_livro_ou_ajuste_seus_filtro": "本を取り込むか、フィルターを調整してください。",
    "nada_por_aqui_ainda": "まだここには何もありません",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "+ をタップして MP3、M4B、MP4 ファイルを選んでください。章ごとの複数の MP3 を 1 つのオーディオブックにできます。",
    "nada_para_ouvir_ou_assistir_ainda": "まだ聴いたり観たりするものがありません",
    "o_pdf_original_permanece_intacto_na_pa": "元の PDF はあなたのフォルダにそのまま残ります。",
    "paginas_como_imagem": "画像としてのページ",
    "paginas_do_pdf": "PDF のページ",
    "em_navegadores_sem_suporte_a_acesso_di": "ファイルシステムへの直接アクセスに対応していないブラウザでは、代わりに EPUB がダウンロードされます。",
    "essa_permissao_e_dada_somente_a_esta_a": "この許可はこのアプリにだけ与えられ、元のファイルが変更されないようにします。",
    "selecione_a_pasta_que_contem_o_pdf": "PDF の入っているフォルダを選んでください",
    "preparando": "準備しています…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "ファイルを読み、組み立て直しています。大きな本は少し時間がかかります。",
    "revistas_apostilas_complexas_formulari": "雑誌、複雑な教材、フォーム、表の多い文書、スキャンした PDF は元のレイアウトの一部を失うことがあります。",
    "funcionalidade_indicada_apenas_para_li": "本のための機能です",
    "o_epub_e_melhor_para_livros_com_texto": "EPUB は選択できるテキストのある本に向いています。書体、大きさ、余白、読み方を調整できるからです。",
    "trecho_selecionado": "選択した一節",
    "trecho_comentado": "コメント付きの一節",
    "aplicando_zoom": "ズームしています...",
    "nao_foi_possivel_carregar_esta_pagina": "このページを読み込めませんでした。",
    "nomear_marcador": "ブックマークに名前を付ける",
    "toque_em_marcar_agora_para_guardar_est": "「今すぐ印を付ける」をタップしてこの場所を保存し、いつでも戻れるようにします。",
    "timer_ativo": "タイマーオン",
    "trecho_ausente_ou_corrompido_no_arquiv": "[元のファイルで一節が欠けているか壊れています]",
    "novos_livros_vao_abrir_em_leitura_v": "新しい本は {v} 読みで開きます。",
    "leitura_efetivo_aplicada_a_este_livro": "この本に {efetivo} 読みを適用しました。",
    "automatico_neste_livro_leitura_efetivo": "この本では自動：{efetivo} 読み。",
    "agora_esta_em_efetivo_no_automatico_fo": "いま {efetivo} に設定されています；自動では {format} が {padrao} で開きます。",
    "esta_escolha_vale_so_para_v_cada_livro": "この選択は「{v}」だけに有効です。本ごとにスクロールの向きを持ちます。",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} はまだ本棚にありません。",
    "escolha_uma_pasta_para_procurar_label": "{label} を探すフォルダを選んでください。",
    "subtitle_versao_build": "{subtitle} · バージョン {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "{path} を読めませんでした；組み込みのテキストを使います。",
    "seu_ultimo_backup_foi_ha_dias_dias": "最後のバックアップは {dias} 日前でした",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "バックアップの本のうち {aguardando} 冊がまだここにありません。その本の進行状況と印は保管されています。ファイルを取り込めば、すべて自動的に元の場所に戻ります。",
      "other": "バックアップの本のうち {aguardando} 冊がまだここにありません。それらの本の進行状況と印は保管されています。各ファイルを取り込めば、すべて自動的に元の場所に戻ります。"
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "本棚の {atualizados} 冊が更新されました。",
      "other": "本棚の {atualizados} 冊が更新されました。"
    },
    "criado_em_quando": "{quando} に作成",
    "backup_pronto_livros_livro_s_e_marcaco": "バックアップ準備完了：{livros} 冊、{marcacoes} 個の印。",
    "endereco_seguro_seguro": "安全なアドレス：{seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "この本の進行状況と {marcas} 個の印を復元しました。",
      "other": "この本の進行状況と {marcas} 個の印を復元しました。"
    },
    "restaurando_v_de_length": "復元中（{v} / {length}）...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} 冊 · {marcacoes} 個の印",
    "criado_em_v": "{v} に作成",
    "reunindo_a_sua_estante_v_de_length": "本棚を集めています（{v} / {length}）...",
    "titulo_ja_foi_importado_antes_e_contin": "「{titulo}」は前にも取り込まれ、ライブラリに残っています。新しいコピーは作られませんでした。",
    "length_arquivos_de_audio": "{length} 個の音声ファイル...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "{falhas} 個のファイルを読めませんでした。",
      "other": "{falhas} 個のファイルを読めませんでした。"
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} はすでにライブラリにあり、飛ばしました。",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "{importados} 冊を本棚に追加しました。",
      "other": "{importados} 冊を本棚に追加しました。"
    },
    "epub_salvo_em_filename": "EPUB を {fileName} に保存しました。",
    "falha_ao_converter_o_pdf_v": "PDF の変換に失敗：{v}",
    "pagina_page_de_totalpages": "{page} / {totalPages} ページ",
    "totalpages_paginas": {
      "one": "{totalPages} ページ",
      "other": "{totalPages} ページ"
    },
    "length_resultado_s_para_search": {
      "one": "「{search}」の {length} 件の結果",
      "other": "「{search}」の {length} 件の結果"
    },
    "capitulo_v": "第 {v} 章",
    "organizando_capitulo_v_de_totalchapter": "第 {v} / {totalChapters} 章を配置しています",
    "pagina_v": "{v} ページ",
    "paginas_v_v2": "{v}–{v2} ページ",
    "length_pagina_s_prontas": {
      "one": "{length} ページ準備完了",
      "other": "{length} ページ準備完了"
    },
    "montando_as_paginas_pagessofar_prontas": "ページを組み立てています — {pagesSoFar} 完了",
    "lendo_pagina_v_de_length": "{v} / {length} ページを読んでいます",
    "marcador_salvo_em_t": "ブックマークを {t} に保存しました。",
    "o_audio_vai_pausar_em_minutes_minutos": "音声は {minutes} 分後に一時停止します。",
    "length_capitulos_toque_para_ir_direto": "{length} 章 · タップで直接そこへ。",
    "narrado_por_narrator": "{narrator} の朗読",
    "velocidade_de_reproducao_rate": "再生速度：{rate}",
    "avancar_f_segundos": "{f} 秒進む",
    "nao_foi_possivel_abrir_este_v": "この {v} を開けませんでした。",
    "nao_foi_possivel_ler_o_arquivo_de_v": "{v} ファイルを読めませんでした。",
    "o_v_esta_danificado_neste_ponto": "{v} はこの地点で壊れています。",
    "o_navegador_nao_consegue_reproduzir_es": "ブラウザがこの {v} ファイルを再生できません。",
    "nao_foi_possivel_reproduzir_este_v": "この {v} を再生できませんでした。",
    "os_dados_deste_noun_estao_incompletos": "この {noun} のデータが不完全です。",
    "importe_o_arquivo_novamente_para_conti_2": "{v} を続けるにはファイルをもう一度取り込んでください。",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "この {noun} のファイルはもう端末に保存されていません。",
    "nao_foi_possivel_descobrir_a_duracao_d": "「{name}」の長さが分かりませんでした。",
    "lendo_faixa_v_de_length": "トラック {v} / {length} を読んでいます...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "この {v} の長さが分かりませんでした。",
    "este_format_nao_pode_ser_reproduzido_n": "この {format} はこのブラウザで再生できません。",
    "este_format_esta_protegido_por_drm": "この {format} は DRM で保護されています。",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "ファイルは {bytes} で、約 {v} 残っています。空きを作るかライブラリから本を削除してください。",
    "este_arquivo_nao_e_um_format_valido": "このファイルは有効な {format} ではありません。",
    "preparando_as_paginas_vistas_de_total": "ページを準備しています（{vistas} / {total}）...",
    "preparando_total_pagina_s": {
      "one": "{total} ページを準備しています...",
      "other": "{total} ページを準備しています..."
    },
    "preparando_as_paginas_v_de_total": "ページを準備しています（{v} / {total}）...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "約 {bytes} を使い、{v} ほど残っています。空きを作るかライブラリから本を削除してください。",
    "envio_direto_exige_endereco_seguro": "このページは安全なアドレスから開かれていないため、ほかのアプリへ直接送ることができません。ファイルを保存して、お好きなアプリで送ってください。",
    "na_estante": "本棚に",
    "nao_foi_possivel_montar_o_arquivo": "ファイルを作成できませんでした。",
    "este_navegador_nao_oferece_o_envio_dir": "このブラウザは他のアプリへの直接送信を提供していません。ファイルを保存し、好きなアプリで添付してください。",
    "voce_ainda_nao_fez_nenhum_backup": "まだバックアップを作っていません。",
    "converter_para_epub": "EPUB に変換",
    "esta_pagina_nao_pode_ser_exibida": "このページを表示できませんでした。",
    "na_ordem_em_que_serao_tocados": "再生される順に",
    "este_capitulo_nao_pode_ser_exibido": "この章を表示できませんでした。",
    "livro": "本",
    "restantes": " 残り",
    "como_seus_dados_sao_tratados": "あなたのデータの扱い",
    "condicoes_de_uso_do_aplicativo": "アプリの利用条件",
    "audiolivro": "オーディオブック",
    "sobre_o_aplicativo": "アプリについて",
    "o_que_e_o_veredas_reader": "Veredas Reader とは",
    "o_aparelho_recusou_o_tipo_do_arquivo": "（この端末では、この種類のファイルは共有できません）",
    "livros": "冊",
    "lendo": "読書中",
    "lidos": "読了",
    "compartilhar_livro": "本を共有",
    "n_livros": {
      "one": "{n} 冊",
      "other": "{n} 冊"
    },
    "livros_unidade": {
      "one": "冊",
      "other": "冊"
    },
    "uma_faixa_discreta_depois_de_n_dias": "{n} 日間バックアップがないと、本棚に控えめなお知らせが表示されます。読書を妨げることはありません。",
    "scanned_arquivos_verificados_livros_enc": "{scanned} ファイルを確認 · {encontrados} 冊発見",
    "v_de_total": "{v} / {total}",
    "voltar_n_segundos": "{n} 秒戻る",
    "cancelado": "キャンセル",
    "arquivo": "ファイル",
    "outro": "その他",
    "outros": "その他",
    "audiolivro_2": "オーディオブック",
    "pausar": "一時停止",
    "marcador": "ブックマーク",
    "leitura": "読書",
    "grifo": "ハイライト",
    "editar": "編集",
    "apagar": "削除",
    "concluir": "完了",
    "recentes": "最近",
    "progresso": "進行",
    "entendi": "わかりました",
    "aviso": "お知らせ",
    "descartar": "削除",
    "copiado": "コピーしました",
    "restaurar": "復元",
    "restaurando": "復元中",
    "excluir": "削除",
    "grifos": "ハイライト",
    "arquivo_vazio": "空のファイルです。",
    "e_mais_n_arquivos": {
      "one": "ほか {n} 個のファイル（再生される順）",
      "other": "ほか {n} 個のファイル（再生される順）"
    },
    "n_arquivos_mp3": {
      "one": "MP3 ファイル {n} 個",
      "other": "MP3 ファイル {n} 個"
    },
    "pct_restam": "{pct}% · 残り {tempo}",
    "n_minutos": {
      "one": "{n} 分",
      "other": "{n} 分"
    },
    "ir_para_tempo": "{tempo} に移動",
    "nomear": "名前を付ける",
    "parte_n": "パート {n}",
    "carregando_pagina_n": "{n} ページを読み込み中...",
    "selecionar_pasta_e_continuar": "フォルダを選んで続ける",
    "ler_agora": "今すぐ読む",
    "agrupamento_v": "グループ化：{v}",
    "tempo_restante": "残り {tempo}",
    "abrir_titulo": "{titulo} を開く",
    "continuar_lendo_titulo": "{titulo} を続けて読む",
    "continuar_ouvindo_titulo": "{titulo} を続けて聴く",
    "continuar_assistindo_titulo": "{titulo} を続けて見る",
    "lido": "読了",
    "pausado": "一時停止",
    "status": "ステータス",
    "favorito": "お気に入り",
    "escolher_local": "保存先を選ぶ",
    "epub_baixado_como": "EPUB を {nome} としてダウンロードしました。",
    "ouvir_a_partir_de": "{tempo} から聴く",
    "assistir_a_partir_de": "{tempo} から見る",
    "pagina_n_minuscula": "{n} ページ",
    "selecione_trecho_para_criar": "読書中に文章を選択すると、{oque}を作成できます。",
    "excluir_oque_pergunta": "{oque}を削除しますか？",
    "excluir_oque": "{oque}を削除",
    "excluir_item_pergunta": "この項目を削除しますか？",
    "use_organizar_para_criar": "本の「{botao}」から{oque}を作成できます。",
    "n_arquivos_processados": {
      "one": "{n} 個のファイルを処理しました",
      "other": "{n} 個のファイルを処理しました"
    },
    "voce_ja_tem_titulo_de_autor": "ファイルは異なりますが、{autor}の「{titulo}」はすでにライブラリにあります。それでも取り込みますか？",
    "voce_ja_tem_titulo": "ファイルは異なりますが、「{titulo}」はすでにライブラリにあります。それでも取り込みますか？",
    "marcadores_unidade": {
      "one": "ブックマーク",
      "other": "ブックマーク"
    },
    "ultimo_backup_em": "最終バックアップ：<strong>{data}</strong>",
    "guardar": "保存",
    "lembretes": "リマインダー",
    "juntar": "統合",
    "recomendado": "おすすめ",
    "substituir": "置き換え",
    "n_capas_recuperadas": {
      "one": "表紙を {n} 件復元しました。",
      "other": "表紙を {n} 件復元しました。"
    },
    "nao_encontramos_arquivos_tipo": "このフォルダに {tipo} ファイルは見つかりませんでした。",
    "tentar_outra_pasta": "別のフォルダを試す",
    "n_livros_encontrados": {
      "one": "{n} 冊の本が見つかりました",
      "other": "{n} 冊の本が見つかりました"
    },
    "n_de_total_selecionados": {
      "one": "{total} 件中 {n} 件を選択",
      "other": "{total} 件中 {n} 件を選択"
    },
    "importar": "取り込む",
    "importar_n": "{n} 件を取り込む",
    "aceite_frase": "Veredas Reader の{politica}と{termos}を読み、同意します。",
    "pdf_preservado": "元の PDF は<strong>あなたのフォルダからは削除されません</strong>。EPUB が正常に保存されたあと、ライブラリからこの PDF のコピーだけが外されます。",
    "gravar_epub_mesma_pasta": "EPUB を<strong>PDF と同じフォルダに</strong>保存するには、ブラウザがそのフォルダにアクセスする許可が必要です。",
    "epub_pronto_qualquer_pasta": "EPUB の変換が完了しました。ファイルの保存先として、<strong>コンピューター上のどのフォルダでも</strong>選べます。",
    "backup_explicacao": "元のバックアップは ZIP または TXT ファイルです。別の端末で受け取ったら、<strong>バックアップを復元</strong>から取り込んでください。Veredas が中身を見分けて通常どおり復元します。ファイルに含まれるのは進行状況、ハイライト、引用、メモ、ブックマーク、本棚の構成で、<strong>本そのもの</strong>や表紙は含まれません。",
    "lembretes_desligados_frase": "リマインダーは<strong>オフ</strong>になっています。ときどきバックアップするのを忘れないでください。",
    "backup_salvo_nos_downloads": "<strong>バックアップファイルをこの端末に保存しました</strong>（ダウンロードフォルダ）。すぐに送れます：WhatsApp、メール、Drive など好きなアプリを開き、添付をタップしてファイルを選んでください。",
    "arquivo_pronto_tamanho": "ファイルの準備ができました — <strong>{tamanho}</strong>",
    "scan_intro_frase": "アプリは端末のフォルダ（サブフォルダを含む）から、<strong>EPUB</strong>・<strong>MOBI</strong> の本、<strong>CBZ</strong>・<strong>CBR</strong> のコミック、<strong>M4B</strong> のオーディオブックを探せます。",
    "scan_intro_auto_frase": "本棚をすばやく埋めるために、アプリは端末のフォルダ（サブフォルダを含む）から、<strong>EPUB</strong>・<strong>MOBI</strong> の本、<strong>CBZ</strong>・<strong>CBR</strong> のコミック、<strong>M4B</strong> のオーディオブックを探せます。",
    "n_livros_aguardando": {
      "one": "<strong>{n} 冊</strong>の進行状況と印を保管してあり、再び取り込まれるのを待っています。",
      "other": "<strong>{n} 冊</strong>の進行状況と印を保管してあり、再び取り込まれるのを待っています。"
    },
    "fora_da_busca_titulo": "PDF、TXT、DOCX（Word）、MD、MP3、MP4 ファイルは自動では取り込みません",
    "fora_da_busca_texto": "これらの形式は、本だけでなくあらゆる種類の文書に使われます。対象から外しておくと、本棚がすっきり保たれます。<strong>+ ボタンから 1 つずつ手動で取り込めます。</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "ローカルライブラリ",
    "biblioteca": "ライブラリ",
    "organizacao": "整理",
    "minhas_marcacoes": "自分の印",
    "sistema": "システム",
    "sua_biblioteca": "マイライブラリ",
    "toque_em_um_livro_para_comecar_a_ler": "本をタップして読み始めます。",
    "agrupar": "グループ化",
    "sua_estante_nao_tem_copia_de_seguranca": "本棚にバックアップがありません",
    "se_este_aparelho_se_perder_o_progresso": "この端末に何かあった場合、進行状況と印が失われるおそれがあります。",
    "agora_nao": "今はしない",
    "nao_avisar_mais": "もう知らせない",
    "carregando": "読み込んでいます...",
    "estante": "本棚",
    "lendo": "読書中",
    "favoritos": "お気に入り",
    "marcas": "印",
    "mais": "その他",
    "neste_capitulo": "この章で",
    "velocidade": "速度",
    "timer": "タイマー",
    "marcar": "印を付ける",
    "marcadores": "ブックマーク",
    "personalizar_leitura": "読書をカスタマイズ",
    "as_preferencias_ficam_salvas_para_as_p": "設定は今後の読書のために保存されます。",
    "tema": "テーマ",
    "claro": "明るい",
    "sepia": "セピア",
    "escuro": "暗い",
    "oceano": "海",
    "tipografia": "書体",
    "texto": "テキスト",
    "tamanho": "大きさ",
    "espacamento": "行間",
    "margens": "余白",
    "cores_personalizadas_opcional": "カスタムカラー（任意）",
    "fundo": "背景",
    "fonte": "テキストの色",
    "brilho": "明るさ",
    "orientacao": "向き",
    "auto": "自動",
    "retrato": "縦",
    "paisagem": "横",
    "modo_de_leitura": "読み方",
    "automatico": "自動",
    "horizontal": "横",
    "vertical": "縦",
    "automatico_usa_rolagem_horizontal_para": "自動は EPUB、MOBI、TXT、MD に横のページ送りを、PDF と DOCX に縦スクロールを使います。読書中に変更した場合、その変更はその本だけに保持されます。",
    "quadrinhos": "コミック",
    "como_a_pagina_aparece": "ページの合わせ方",
    "pagina_inteira": "ページ全体",
    "largura_da_tela": "画面の幅",
    "sentido_da_leitura": "読む向き",
    "normal": "通常 →",
    "manga": "← マンガ",
    "revista_aberta_na_horizontal": "横で見開き",
    "com_o_aparelho_deitado_mostra_duas_pag": "横向きにすると 2 ページが並びます — 表紙は別に、本物のコミックの開き方です。",
    "normal_vira_da_esquerda_para_a_direita": "通常は左から右へめくります。マンガはすべてを反転します：スワイプ、端のタップ、見開きでの 2 ページの順。",
    "gire_o_aparelho_para_a_horizontal_para": "2 ページを同時に見るには端末を横向きにしてください。",
    "dois_toques_ampliam_no_ponto_tocado_co": "ダブルタップでその場所を拡大します；拡大したらドラッグでページを動きます。2 本指のピンチも使えます。",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "リーダー上部のスクロールボタンが、1 ページずつと連続スクロール（Webtoon 風）を切り替えます。連続スクロールではページがつながり、拡大するとページが横に広がって、横スクロールで移動します。",
    "virada_de_pagina": "ページ送り",
    "folha_real": "本物の紙",
    "deslizar": "スライド",
    "sem_animacao": "アニメーションなし",
    "na_leitura_horizontal_arraste_a_pagina": "横読みでは、指で折るようにページを端からドラッグします。途中で離すとページ送りをやめます。",
    "ouvir_leitura": "聴く",
    "continue_de_onde_parou_no_seu_ritmo": "止めたところから、自分のペースで。",
    "livro": "本",
    "pronto_para_comecar": "始める準備完了",
    "voz": "声",
    "escolha_uma_voz_disponivel_no_disposit": "この端末で使える声を選んでください",
    "voz_padrao_do_sistema": "システムの既定の声",
    "durante_a_reproducao": "再生中",
    "a_leitura_avanca_pagina_a_pagina_os_co": "読み上げはページごとに進みます。ブラウザが対応していればシステムのコントロールが出ます。",
    "organizar_livro": "本を整理",
    "estantes_colecoes_tags_e_status": "本棚、コレクション、タグ、状態。",
    "cancelar": "キャンセル",
    "salvar": "保存",
    "grifos_citacoes_notas_e_marcadores_des": "この本のハイライト、引用、メモ、ブックマーク。",
    "sumario": "目次",
    "toque_em_um_capitulo_para_ir_direto_ao": "章をタップしてそこへ直接移動します。",
    "sua_anotacao": "メモ",
    "edite_ou_adicione_comentarios_ao_seu_t": "一節にコメントを編集または追加します。",
    "trecho": "一節",
    "sua_nota": "メモ",
    "salvar_nota": "メモを保存",
    "agrupar_biblioteca": "ライブラリをグループ化",
    "escolha_como_os_livros_serao_organizad": "本棚で本をどう並べるか選んでください。",
    "ao_arrastar_um_livro_para_outra_posica": "本を別の場所へドラッグすると、本棚は自動的に「マイオーダー」に切り替わり、作成した並び順が保たれます。",
    "backup_e_restauracao": "バックアップと復元",
    "sua_estante_seu_progresso_e_suas_marca": "あなたの本棚、進行状況、印を 1 つのファイルに。",
    "escolha_uma_dimensao_para_explorar_sua": "ライブラリを探る方法を選んでください。",
    "capitulos": "章",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "声の高さは変わりません。この本と次の本に適用されます。",
    "ajuste_fino": "細かい調整",
    "timer_de_sono": "スリープタイマー",
    "o_audio_diminui_de_volume_aos_poucos_e": "音声は徐々に小さくなり、自動的に一時停止します。",
    "pontos_que_voce_guardou_neste_audioliv": "このオーディオブックで保存した場所。",
    "ajustes_do_audio": "音声設定",
    "as_preferencias_ficam_salvas_para_todo": "この設定はすべてのオーディオブックに保存されます。",
    "botao_de_voltar": "戻るボタン",
    "botao_de_avancar": "進むボタン",
    "recuar_ao_retomar": "再開時に巻き戻す",
    "depois_de_uma_pausa_longa_volta_alguns": "長い休みの後、数秒戻して流れを取り戻せるようにします。",
    "tocar_ao_abrir": "開いたら再生",
    "ao_tocar_em_um_audiolivro_na_estante_a": "本棚でオーディオブックをタップするとすぐ再生が始まります。",
    "no_computador_espaco_toca_e_pausa_pula": "パソコンでは：space で再生/一時停止 · ← → でスキップ · Shift + ← → で章移動 · ↑ ↓ 音量 · B ブックマーク · [ ] 速度。",
    "converter_pdf_para_epub": "PDF を EPUB に変換",
    "prepare_o_livro_para_leitura_fluida_e": "本をなめらかで調整できる読書に整えます。",
    "confirmacao": "確認",
    "confirmar": "確認",
    "processando": "処理中",
    "documento": "文書",
    "buscar_livros_no_dispositivo": "この端末で本を探す",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "端末に保存されている EPUB、MOBI、CBZ、CBR、M4B ファイルを探します。",
    "juntar_em_um_unico_audiolivro": "1 つのオーディオブックにまとめますか？",
    "titulo": "タイトル",
    "autor": "著者",
    "importar_separados": "別々に取り込む",
    "bem_vindo_ao_veredas_reader": "Veredas Reader へようこそ",
    "sua_biblioteca_de_leitura_inteiramente": "読書ライブラリは、すべてこの端末の中に。",
    "buscar": "検索",
    "importar_livro": "本を取り込む",
    "buscar_titulo_autor_tag": "タイトル、著者、タグを検索...",
    "fechar_busca": "検索を閉じる",
    "navegacao_da_biblioteca": "ライブラリのナビ",
    "fechar_menu": "メニューを閉じる",
    "agrupar_livros": "本をグループ化",
    "voltar": "戻る",
    "marcar_pagina": "ページに印を付ける",
    "personalizar": "カスタマイズ",
    "navegacao_principal": "メインナビ",
    "acoes_do_trecho": "一節の操作",
    "amarelo": "黄",
    "verde": "緑",
    "rosa": "ピンク",
    "azul": "青",
    "player_de_audiolivro": "オーディオブックプレイヤー",
    "minimizar_player": "プレイヤーを最小化",
    "minimizar": "最小化",
    "video_em_reproducao": "動画再生中",
    "abrir_a_lista_de_capitulos": "章の一覧を開く",
    "posicao_no_audio": "音声内の位置",
    "alternar_entre_o_progresso_do_capitulo": "章の進行と本全体の進行を切り替える",
    "capitulo_anterior": "前の章",
    "voltar_15_segundos": "15 秒戻る",
    "reproduzir": "再生",
    "avancar_30_segundos": "30 秒進む",
    "proximo_capitulo": "次の章",
    "velocidade_de_reproducao": "再生速度",
    "marcar_este_ponto": "この場所に印を付ける",
    "ver_marcadores": "ブックマークを見る",
    "silenciar": "ミュート",
    "volume": "音量",
    "audiolivro_em_reproducao": "オーディオブック再生中",
    "abrir_o_player": "プレイヤーを開く",
    "fechar_o_player": "プレイヤーを閉じる",
    "fechar": "閉じる",
    "trecho_anterior": "前の一節",
    "iniciar_leitura": "読み上げを始める",
    "proximo_trecho": "次の一節",
    "escreva_seu_comentario_interpretacao_o": "コメント、解釈、リマインダーを書いてください...",
    "cancelar_importacao": "取り込みをキャンセル",
    "nome_do_audiolivro": "オーディオブックの名前",
    "nome_do_autor": "著者の名前",
    "idioma": "言語",
    "idioma_do_aplicativo": "アプリの言語",
    "o_aplicativo_segue_o_idioma_do_apare": "アプリは端末の言語に従います。お使いの言語が未対応の場合は英語で表示されます。",
    "seguir_o_aparelho": "端末に従う",
    "fazer_backup": "今すぐバックアップ",
    "todos": "すべて",
    "lidos": "読了",
    "pausados": "一時停止",
    "autores": "著者",
    "tags": "タグ",
    "grifar": "ハイライト",
    "anotar": "メモ",
    "enviar": "送る",
    "restaurar_padroes": "既定値に戻す",
    "voltar_para_1": "1× に戻す",
    "marcar_agora": "今すぐ印を付ける",
    "escolher_pasta": "フォルダを選ぶ",
    "juntar_em_um_audiolivro": "1 つのオーディオブックにまとめる",
    "sobre": "このアプリについて",
    "licencas_de_codigo_aberto": "オープンソースライセンス",
    "configuracoes": "設定",
    "temas_e_idioma": "テーマと言語"
  },
  "aviso": {
    "idioma_trocado": "言語を変更しました。"
  },
  "vn": {
    "quem_le": "読み上げる声",
    "natural": "ナチュラル",
    "do_sistema": "システム",
    "nota_sistema": "端末にインストールされている声を使います。より人間らしい読み上げには、ナチュラルを選んでください。",
    "nota_sistema_com_natural": "自然な声はダウンロードしたまま残っています。いつでもナチュラルに戻せます。",
    "voz_do_sistema": "端末の音声",
    "lendo_com_a_voz_do_sistema": "端末の音声で読み上げています。",
    "voz_natural": "自然な声",
    "gerada_no_aparelho": "ずっと人間らしい声を、この端末の中で生成します。",
    "progresso_download": "ダウンロードの進行状況",
    "x_de_y": "{x} / {y}",
    "aviso_arquivo": "自然な声を使うには、Veredas をパソコン上のファイルとしてではなく、アプリのアドレスから開く必要があります。それまでは、システムの声で読み上げます。",
    "aviso_navegador": "このブラウザには、自然な声に必要な機能がありません。読み上げはシステムの声で続けます。",
    "verificando": "自然な声を確認しています…",
    "fato_download": "ダウンロードは 1 回だけ（{tamanho}）。その後はオフラインで使えます。",
    "fato_wifi": "Wi-Fi がおすすめです。一時停止して、あとで再開することもできます。",
    "fato_privacidade": "本の文章が端末の外に送られることはありません。",
    "fato_idiomas": "日本語、英語、韓国語など 31 の言語を話せます。それ以外の言語はシステムの声で読み上げます。",
    "baixar_voz_natural": "自然な声をダウンロード（{tamanho}）",
    "licenca_curta": "Supertone の Supertonic 3 モデル、OpenRAIL-M ライセンス。詳しくは「このアプリについて」>「オープンソースライセンス」をご覧ください。",
    "pode_continuar_usando": "ダウンロード中も読書を続けられます。接続が切れても、止まったところから再開します。",
    "pausar_download": "ダウンロードを一時停止",
    "erro_espaco": "端末の空き容量が足りず、ダウンロードを完了できません。空き容量を増やして、もう一度お試しください。",
    "erro_offline": "現在インターネットに接続されていません。ダウンロード済みの分は保存されています。",
    "erro_rede": "ダウンロード中に接続が切れました。ダウンロード済みの分は保存されています。",
    "download_pausado": "ダウンロードを一時停止しました。ダウンロード済みの分は保存されています。",
    "continuar_download": "再開",
    "descartar": "破棄",
    "voz_feminina": "女性",
    "voz_feminina_desc": "やわらかく落ち着いた声",
    "voz_masculina": "男性",
    "voz_masculina_desc": "あたたかく穏やかな声",
    "parar_amostra": "サンプルを停止",
    "ouvir_amostra_de": "サンプルを再生：{voz}",
    "escolha_a_voz": "声を選ぶ",
    "qualidade": "品質",
    "q_auto": "自動",
    "q_rapida": "高速",
    "q_maxima": "最高",
    "q_auto_desc": "端末の性能に合わせて自動で調整し、途切れずに読み上げます。",
    "q_rapida_desc": "声をより速く生成します。性能が控えめな端末に向いています。",
    "q_maxima_desc": "いちばん丁寧な音質です。性能が控えめな端末では、文と文の間に間が空くことがあります。",
    "ocupa": "この端末で {tamanho} を使用",
    "remover": "削除",
    "baixar_pelos_dados": "モバイルデータでダウンロードしますか？",
    "baixar_pelos_dados_msg": "端末が Wi-Fi に接続されていないようです。ダウンロードは {tamanho} あり、データ通信量を消費する場合があります。",
    "baixar_agora": "ダウンロードする",
    "pronta": "自然な声の準備ができました。",
    "download_interrompido": "ダウンロードが止まりました。都合のよいときに「再開」をタップしてください。",
    "remover_titulo": "自然な声を削除しますか？",
    "descartar_titulo": "ダウンロードを破棄しますか？",
    "remover_msg": "{tamanho} が空きます。読み上げはシステムの声に戻り、いつでも再ダウンロードできます。",
    "descartar_msg": "ダウンロード済みの分は削除されます。",
    "removida": "この端末から自然な声を削除しました。",
    "amostra_falhou": "この端末ではサンプルを再生できませんでした。",
    "amostra": "こんにちは！自然な声で読むと、本はこんなふうに聞こえます。",
    "pode_demorar_um_minuto": "1分ほどかかることがあります。",
    "gerando_voz": "声を準備しています…",
    "automatico_idioma": "自動（{idioma}）",
    "automatico": "自動",
    "so_voz_do_sistema": "システムの声",
    "aviso_idioma": "テキストの言語：{idioma}。自然な声はまだこの言語に対応していないため、システムの声で読み上げます。",
    "aviso_idioma_desconhecido": "このテキストの言語を判別できませんでした。自然な声を使うには、下で言語を選んでください。",
    "aviso_falha": "今はこの端末で自然な声を使えませんでした。読み上げはシステムの声で続けます。",
    "nao_carregou_usando_sistema": "この端末で自然な声を読み込めませんでした。システムの声で読み上げています。",
    "parou_usando_sistema": "自然な声が停止しました。システムの声で続けます。",
    "aparelho_lento": "この端末では声の生成に時間がかかっています。間が空かないよう、品質を「高速」にしてください。",
    "idioma_do_texto": "テキストの言語",
    "idioma_do_texto_dica": "テキストから自動で判別しました。発音がおかしい場合は変更してください。",
    "leitura_em_voz_alta": "読み上げ",
    "lento_usando_sistema": "この端末では自然な声の生成が遅すぎるため、システムの声で読み上げを続けます。",
    "aviso_lento": "この端末では読み上げの速さに合わせて自然な声を生成できないため、いまはシステムの声で読み上げています。",
    "sem_memoria_usando_sistema": "この端末のメモリーに自然な声が収まりませんでした。システムの声で読み上げます。",
    "aviso_falha_memoria": "この端末では自然な声に使えるメモリーが足りませんでした。ほかのアプリを閉じてもう一度試すと動くことが多いです。それまではシステムの声で読み上げます。",
    "copiar_detalhe": "詳細をコピー",
    "copiado": "詳細をコピーしました。",
    "falhou_titulo": "この端末では自然な声を読み込めませんでした。",
    "falhou_texto": "端末が自然な声を準備できませんでした。システムの声で読み上げを続けます。解決に役立てるため、下の詳細をコピーしてサポートへ送ってください。",
    "falhou_memoria_texto": "この端末では自然な声に使えるメモリーが足りませんでした。ほかのアプリを閉じてもう一度試すと動くことが多いです。",
    "tentar_de_novo": "もう一度試す",
    "tentando": "読み込み中…",
    "sondando": "この端末のメモリーを確認しています…",
    "sonda_explica": "自然な音声に必要となるメモリーを数秒だけ確保し、すぐに解放します。ダウンロードの後ではなく、今わかります。",
    "so_aparelhos_compativeis": "対応した端末でのみ動作します。すべてのスマートフォンやタブレットでの動作は保証されません。",
    "aviso_aparelho_justo": "この端末は自然な声に使えるメモリーが少なめです。読み込めないことがあります。その場合は削除すれば容量が戻ります。",
    "preparando_demora": "声を準備しています。数分かかることがあります。",
    "incompativel_titulo": "この端末では自然な声を使えません。",
    "incompativel_memoria": "準備に使えるメモリーが足りませんでした。読み上げはシステムの声で行い、その設定は下にあります。よろしければ、ほかのアプリを閉じて「もう一度試す」を押してください。",
    "incompativel_lento": "読み上げの速さに追いつけませんでした。読み上げはシステムの声で行い、その設定は下にあります。",
    "incompativel_queda": "読み込み中にアプリが終了しました。読み上げはシステムの声で行い、その設定は下にあります。",
    "incompativel_falha": "この端末では読み込めませんでした。読み上げはシステムの声で行い、その設定は下にあります。",
    "testar_de_novo": "もう一度試す",
    "remover_e_liberar": "削除して {tamanho} を空ける",
    "tela_durante_a_leitura": "読書中の画面",
    "manter_tela_ligada": "画面を消さない",
    "manter_tela_ligada_dica": "本を開いている間は画面が自動で消えません。本を閉じると元に戻ります。"
  }
});