/* ============================================================
   KOREAN — ko.js
   ============================================================ */
Idiomas.registrar('ko', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "북마크가 삭제되었습니다.",
    "excluir_marcador": "북마크 삭제",
    "o_marcador_sera_removido_permanentemen": "북마크가 영구적으로 삭제됩니다.",
    "excluir_marcador_2": "북마크를 삭제할까요?",
    "pagina_salva": "페이지가 저장되었습니다",
    "anotacoes": "메모",
    "citacoes": "인용",
    "item_excluido": "항목이 삭제되었습니다.",
    "este_registro_sera_removido_permanente": "이 항목은 라이브러리에서 영구적으로 삭제됩니다.",
    "configuracoes_padrao_restauradas": "기본 설정이 복원되었습니다.",
    "leitura_da_esquerda_para_a_direita": "왼쪽에서 오른쪽으로 읽기.",
    "leitura_da_direita_para_a_esquerda_man": "오른쪽에서 왼쪽으로 읽기(망가).",
    "a_pagina_inteira_passa_a_caber_na_tela": "이제 전체 페이지가 화면에 맞습니다.",
    "a_pagina_passa_a_ocupar_toda_a_largura": "이제 페이지가 화면 너비를 채웁니다.",
    "virada_sem_animacao_ativada": "이제 애니메이션 없이 페이지가 넘어갑니다.",
    "virada_deslizante_ativada": "슬라이드 페이지 넘김이 켜졌습니다.",
    "virada_em_folha_real_ativada": "실제 종이 페이지 넘김이 켜졌습니다.",
    "padrao_automatico_cada_formato_abre_no": "자동: 각 형식이 알맞은 방식으로 열립니다.",
    "mudando_durante_a_leitura_o_ajuste_fic": "읽는 중에 변경하면 해당 책에만 적용됩니다.",
    "automatico_usa_rolagem_horizontal_para": "자동은 EPUB, MOBI, TXT, MD와 만화에는 가로 페이지 넘김을, PDF와 DOCX에는 세로 스크롤을 사용합니다.",
    "este_livro": "이 책",
    "armazenamento_local_indisponivel_neste": "이 브라우저에서는 로컬 저장소를 사용할 수 없습니다.",
    "o_aplicativo_pode_procurar_os_livros_q": "앱이 기기에 이미 있는 책을 찾을 수 있습니다.",
    "vamos_montar_sua_estante": "책장을 채워볼까요?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "동의하지 않으면 앱을 사용할 수 없습니다.",
    "precisamos_do_seu_aceite": "동의가 필요합니다",
    "antes_de_comecar_leia_e_aceite_os_docu": "시작하기 전에 아래 문서를 읽고 동의해 주세요.",
    "selecionar_todos": "모두 선택",
    "limpar_selecao": "선택 해제",
    "todos_parecem_ja_estar_na_sua_estante": "모두 이미 책장에 있는 것 같습니다.",
    "lendo_a_pasta_escolhida": "선택한 폴더를 읽는 중…",
    "procurando_livros": "책을 찾는 중",
    "nao_foi_possivel_concluir_a_busca_no_d": "이 기기에서 검색을 완료할 수 없었습니다.",
    "tente_outra_pasta_do_aparelho": "기기의 다른 폴더를 시도해 보세요.",
    "nenhum_livro_encontrado": "책을 찾을 수 없음",
    "use_o_botao_para_escolher_os_arquivos": "직접 파일을 고르려면 + 버튼을 사용하세요. Android 폰의 Chrome은 보통 폴더 전체를 선택할 수 있게 해줍니다.",
    "seu_navegador_nao_permite_ler_pastas": "브라우저가 폴더를 읽지 못합니다",
    "busca_automatica_indisponivel": "자동 검색 사용 불가",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR 및 M4B",
    "termos_de_uso": "이용 약관",
    "politica_de_privacidade": "개인정보 처리방침",
    "um_minuto_agora_evita_perder_o_progres": "지금 1분이 나중에 진행 상황과 표시를 잃지 않게 합니다.",
    "ver_estante": "책장 보기",
    "modo_juntar": "병합 모드",
    "modo_substituir": "교체 모드",
    "restauracao_concluida": "복원 완료",
    "tente_de_novo_com_o_arquivo_original": "원본 파일로 다시 시도하세요.",
    "a_restauracao_nao_pode_ser_concluida": "복원을 완료할 수 없습니다",
    "devolvendo_o_seu_progresso_e_as_suas_m": "진행 상황과 표시를 되돌리는 중...",
    "restaurar_este_backup": "이 백업을 복원할까요?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Veredas가 저장한 .zip 또는 공유로 받은 .txt를 선택하세요.",
    "nao_foi_possivel_ler_este_arquivo": "이 파일을 읽을 수 없습니다",
    "lendo_o_backup": "백업을 읽는 중",
    "backup_do_veredas_reader": "Veredas Reader 백업",
    "arquivo_de_transporte_txt_contendo_os": "ZIP과 같은 내용을 담은 .txt 형식의 백업 사본",
    "nao_foi_possivel_montar_o_arquivo_de_b": "백업 파일을 만들 수 없습니다.",
    "escolher_o_app": "앱 선택",
    "vale_conferir_o_que_vai_no_arquivo": "파일 내용을 확인해 볼 만합니다",
    "enviar_para_outro_app": "다른 앱으로 보내기",
    "salvar_o_arquivo": "파일 저장",
    "o_navegador_aqui_nao_oferece_o_compart": "여기 브라우저는 직접 공유를 제공하지 않습니다. 파일을 저장한 뒤 원하는 앱으로 보내면 됩니다.",
    "este_aparelho_nao_abre_a_lista_de_apli": "이 기기는 앱 목록을 열지 않습니다",
    "importe_pelo_menos_um_livro_antes_de_f": "백업을 만들기 전에 책을 하나 이상 가져오세요.",
    "estante_vazia": "빈 책장",
    "nao_deu_para_copiar": "복사하지 못했습니다",
    "copiar_detalhes": "세부 정보 복사",
    "o_backup_foi_salvo_assim_mesmo": "백업이 그래도 저장되었습니다",
    "o_aparelho_recusou_abrir_a_lista": "공유 목록을 열 수 없습니다",
    "sem_detalhes_do_navegador": "브라우저 세부 정보 없음",
    "o_sistema_nao_aceitou_receber_o_arquiv": "기기 시스템에서 파일을 받을 수 없었습니다.",
    "o_navegador_considerou_a_situacao_inse": "브라우저의 자체 보안 규칙 때문에 공유가 차단되었습니다. 파일을 저장한 뒤 원하는 앱으로 보내 주세요.",
    "o_compartilhamento_so_funciona_em_ende": "공유는 보안 주소에서만 작동합니다. 이 앱은 일반 http:// 주소에서 열리고 있으며, 이 경우 브라우저가 다른 앱으로의 전송을 차단합니다.",
    "este_navegador_nao_conseguiu_iniciar_o": "이 브라우저에서 공유를 열 수 없었습니다. 파일을 저장한 뒤 원하는 앱으로 보내 주세요.",
    "o_navegador_recebeu_um_arquivo_em_form": "브라우저에서 공유할 앱 목록이 열리지 않았습니다. 버튼을 다시 탭하거나, 파일을 저장한 뒤 원하는 앱으로 보내 주세요.",
    "nao_foi_possivel_gerar_o_backup": "백업을 만들 수 없습니다.",
    "reunindo_a_sua_estante": "책장을 모으는 중...",
    "preparando_o_backup": "백업을 준비하는 중",
    "pronto_nada_mais_esta_esperando": "완료 — 더 이상 기다리는 것이 없습니다.",
    "o_progresso_e_as_marcacoes_desses_livr": "이 책들의 진행 상황과 표시가 지워집니다. 나중에 파일을 가져오면 빈 상태로 돌아옵니다.",
    "descartar_o_que_esta_esperando": "대기 중인 데이터를 삭제할까요?",
    "lembretes_de_backup_religados": "백업 알림이 다시 켜졌습니다.",
    "sem_titulo": "제목 없음",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "알림이 꺼졌습니다.",
    "manter_ligado": "켜둠",
    "desligar_assim_mesmo": "그래도 끔",
    "o_botao_de_salvar_continua_onde_sempre": "저장 버튼은 늘 있던 곳, 백업 및 복원에 있습니다.",
    "o_lembrete_e_o_unico_aviso_que_existe": "알림이 유일한 안내입니다. 알림을 끄면 백업할 때를 직접 기억해야 합니다.\n\n",
    "limpar_os_dados_do_navegador_desinstal": "브라우저 데이터를 지우거나, 앱을 제거하거나, 휴대폰을 바꾸거나, 기기가 고장 나면 진행 상황, 강조, 인용, 메모와 북마크를 복구할 수 없습니다.\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "책장은 이 기기에만 저장됩니다. 서버에 사본이 없어 데이터가 사라지면 복구할 수 없습니다.\n\n",
    "leia_antes_de_confirmar": "확인 전에 읽어 주세요",
    "desligar_os_lembretes_de_backup": "백업 알림을 끌까요?",
    "progresso_de_leitura_restaurado_neste": "이 책의 읽기 진행 상황이 복원되었습니다.",
    "pronto": "완료.",
    "aplicando_as_suas_preferencias": "설정을 적용하는 중...",
    "atualize_o_veredas_reader_e_tente_de_n": "Veredas Reader를 업데이트하고 다시 시도하세요.",
    "este_backup_foi_feito_numa_versao_mais": "이 백업은 앱의 더 새로운 버전으로 만들어졌습니다.",
    "este_arquivo_nao_e_um_backup_de_biblio": "이 파일은 Veredas 라이브러리 백업이 아닙니다.",
    "o_conteudo_interno_nao_pode_ser_lido": "내부 내용을 읽을 수 없습니다.",
    "o_backup_esta_corrompido": "백업이 손상되었습니다.",
    "falta_o_arquivo_biblioteca_json_la_den": "그 안에 biblioteca.json 파일이 없습니다.",
    "este_arquivo_nao_parece_ser_um_backup": "이 파일은 Veredas 백업처럼 보이지 않습니다.",
    "compactando": "압축하는 중...",
    "para_restaurar_menu_lateral_backup_e_r": "복원하려면: 사이드 메뉴 > 백업 및 복원 > 백업 복원.",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas가 표시와 읽다 멈춘 위치를 자동으로 복원합니다.",
    "importe_os_livros_normalmente_no_aplic": "앱에서 책을 평소처럼 가져오세요: 각 파일을 인식하면,",
    "ele_nao_contem_os_arquivos_dos_livros": "책 파일은 들어 있지 않습니다. 완전히 복원하려면,",
    "as_notas_os_marcadores_e_a_organizacao": "메모, 북마크와 책장 구성.",
    "este_arquivo_guarda_o_seu_progresso_de": "이 파일에는 읽기 진행 상황, 하이라이트, 인용,",
    "verificando_se_sao_partes_do_mesmo_aud": "같은 오디오북의 일부인지 확인 중...",
    "analisando_os_arquivos": "파일을 읽는 중",
    "nao_foi_possivel_salvar_o_audiolivro": "오디오북을 저장할 수 없습니다.",
    "audiolivros_grandes_podem_levar_alguns": "큰 오디오북은 잠시 걸릴 수 있습니다...",
    "salvando_na_sua_estante": "책장에 저장하는 중",
    "falha_ao_processar_os_arquivos": "파일을 처리하지 못했습니다.",
    "falha_ao_processar_o_arquivo": "파일을 처리하지 못했습니다.",
    "nao_foi_possivel_salvar_o_quadrinho": "만화를 저장할 수 없습니다.",
    "quase_la": "거의 다 됐어요...",
    "falha_ao_processar_o_quadrinho": "만화를 처리하지 못했습니다.",
    "autor_desconhecido": "알 수 없는 저자",
    "lendo_o_quadrinho": "만화를 읽는 중...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "책을 라이브러리에 저장할 수 없습니다.",
    "nao_foi_possivel_ler_o_pdf": "PDF를 읽을 수 없습니다.",
    "lendo_o_pdf": "PDF를 읽는 중...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "구식 .doc라면 Word에서 열고 .docx로 저장한 뒤 가져오세요.",
    "este_arquivo_nao_e_um_docx_valido": "이 파일은 유효한 .docx가 아닙니다.",
    "livros_com_protecao_da_amazon_nao_pode": "Amazon 보호가 걸린 책은 여기서 열 수 없습니다. DRM 없는 사본을 쓰거나 책을 EPUB로 변환하세요.",
    "este_arquivo_esta_protegido_por_drm": "이 파일은 DRM으로 보호되어 있습니다.",
    "confira_se_a_extensao_corresponde_ao_c": "확장자가 내용과 맞는지 확인하거나 책을 EPUB로 변환하세요.",
    "este_arquivo_nao_e_um_mobi_valido": "이 파일은 유효한 MOBI가 아닙니다.",
    "nao_foi_possivel_ler_o_arquivo": "파일을 읽을 수 없습니다.",
    "formato_nao_suportado": "지원하지 않는 형식.",
    "falha_ao_salvar_o_livro_na_biblioteca": "책을 라이브러리에 저장하지 못했습니다.",
    "livro_importado_e_salvo_no_dispositivo": "책을 가져와 이 기기에 저장했습니다.",
    "audiolivro_importado_e_salvo_no_dispos": "오디오북을 가져와 이 기기에 저장했습니다.",
    "quadrinho_importado_e_salvo_no_disposi": "만화를 가져와 이 기기에 저장했습니다.",
    "salvando_na_sua_estante_2": "책장에 저장하는 중...",
    "importando_livro": "책을 가져오는 중",
    "importar_mesmo_assim": "그래도 가져오기",
    "parece_que_este_livro_ja_esta_na_estan": "이 책이 이미 책장에 있는 것 같습니다",
    "este_livro_ja_esta_na_estante": "이 책은 이미 책장에 있습니다",
    "video_importado_e_salvo_no_dispositivo": "동영상을 가져와 이 기기에 저장했습니다.",
    "importacao_cancelada": "가져오기가 취소되었습니다.",
    "preparando_o_arquivo": "파일을 준비하는 중",
    "importando_audiolivro": "오디오북을 가져오는 중",
    "importacao_concluida": "가져오기 완료",
    "importacao_interrompida": "가져오기가 중단되었습니다",
    "a_importacao_foi_interrompida_o_que_ja": "가져오기가 중단되었습니다. 이미 들어온 것은 책장에 남습니다.",
    "finalizando": "마무리 중…",
    "nao_foi_possivel_ler_o_arquivo_2": "파일을 읽을 수 없습니다",
    "importando_livros": "책을 가져오는 중",
    "livros_quadrinhos_documentos_audiolivr": "책, 만화, 문서, 오디오북 및 동영상",
    "series": "시리즈",
    "colecoes": "컬렉션",
    "organizacao_salva": "구성이 저장되었습니다.",
    "informe_um_nome_para_o_livro_antes_de": "저장하기 전에 책에 이름을 붙이세요.",
    "nome_do_livro_obrigatorio": "책 이름이 필요합니다",
    "importe_um_livro_primeiro": "먼저 책을 가져오세요.",
    "citacao": "인용",
    "anotacao": "메모",
    "citacao_2": "인용",
    "anotacao_2": "메모",
    "uma_citacao": "인용문",
    "uma_anotacao": "메모",
    "o_marcador_sera_removido_da_biblioteca": "북마크는 라이브러리에서 삭제되지만 책 파일은 그대로입니다.",
    "marcador_de_audio": "오디오 북마크",
    "marcador_de_video": "동영상 북마크",
    "nao_foi_possivel_excluir_o_livro": "책을 삭제할 수 없습니다.",
    "livro_excluido_da_biblioteca": "책이 라이브러리에서 삭제되었습니다.",
    "excluir_livro": "책 삭제",
    "isso_remove_apenas_a_copia_armazenada": "이것은 라이브러리가 보관한 사본과 진행 상황, 북마크, 메모만 삭제합니다. 사용자 폴더의 원본 파일은 지워지지 않습니다.",
    "excluir_livro_2": "책을 삭제할까요?",
    "ordem_personalizada_salva": "사용자 지정 순서가 저장되었습니다.",
    "ordem_manual_da_sua_estante": "내가 정한 순서대로 책장을 정렬합니다.",
    "agrupamento_alterado_para_minha_ordem": "그룹화가 내 순서로 바뀌었습니다.",
    "nova_ordem_salva": "새 순서가 저장되었습니다.",
    "nao_foi_possivel_salvar_a_nova_ordem": "새 순서를 저장할 수 없습니다.",
    "baixar_automaticamente": "자동으로 다운로드",
    "escolha_livremente_onde_o_arquivo_sera": "파일이 저장될 위치를 자유롭게 선택하세요.",
    "salvar_epub": "EPUB 저장",
    "livro_epub": "EPUB 책",
    "erro_desconhecido": "알 수 없는 오류",
    "a_permissao_para_salvar_o_arquivo_foi": "파일 저장 권한이 취소되었습니다. 라이브러리에서 아무것도 바뀌지 않았습니다.",
    "conversao_cancelada_o_pdf_original_per": "변환이 취소되었습니다. 원본 PDF는 라이브러리에 남아 있습니다.",
    "preparando_salvamento": "저장을 준비하는 중…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "PDF 사본이 라이브러리에 없습니다.",
    "reconstruindo_o_livro_localmente": "기기에서 책을 다시 만드는 중.",
    "convertendo_pdf": "PDF 변환 중",
    "nao_foi_possivel_compartilhar_o_livro": "책을 공유할 수 없습니다.",
    "o_arquivo_foi_preparado_para_voce_comp": "파일이 다른 앱에서 공유할 수 있도록 준비되었습니다.",
    "livro_compartilhado": "책이 공유되었습니다.",
    "a_copia_deste_livro_nao_esta_disponive": "이 책의 사본이 라이브러리에 없습니다.",
    "para_manter_a_politica_de_compartilham": "라이브러리의 공유 정책을 지키기 위해 EPUB과 MOBI 파일은 이 앱으로 공유할 수 없습니다.",
    "quadrinhos_ficam_guardados_somente_no": "만화는 기기에만 보관되며 이 앱으로 공유할 수 없습니다.",
    "audiolivros_e_videos_ficam_guardados_s": "오디오북과 동영상은 기기에만 보관되며 이 앱으로 공유할 수 없습니다.",
    "formato_protegido": "보호된 형식",
    "compartilhamento_indisponivel": "공유 불가",
    "concluido": "완료",
    "ainda_nao_comecado": "아직 시작하지 않음",
    "continue_lendo": "계속 읽기",
    "continue_ouvindo": "계속 듣기",
    "continue_assistindo": "계속 보기",
    "comece_por_aqui": "여기서 시작",
    "comece_a_ouvir": "듣기 시작",
    "comece_a_assistir": "보기 시작",
    "no_total": "전체",
    "para_ler": "읽을 책",
    "sua_estante": "내 책장",
    "livros_organizados_pela_opcao_selecion": "선택한 옵션에 따라 정리된 책들.",
    "uma_prateleira_para_cada_tipo_de_arqui": "파일 종류마다 한 칸씩.",
    "autores_agrupados_em_ordem_alfabetica": "저자가 알파벳순으로 묶여 있습니다.",
    "toque_para_continuar_de_onde_parou": "멈춘 곳에서 이어 보려면 탭하세요.",
    "para_ler_2": "읽을 책",
    "lendo_agora": "지금 읽는 중",
    "audio_e_video": "오디오와 동영상",
    "trechos_salvos_separadamente_dos_marca": "북마크와 별도로 저장한 구절.",
    "comentarios_vinculados_a_trechos_selec": "선택한 구절에 붙은 댓글.",
    "paginas_salvas_para_voltar_rapidamente": "빠르게 돌아올 수 있도록 저장한 페이지.",
    "do_maior_para_o_menor_progresso_de_lei": "읽기 진행이 많은 순서대로.",
    "livros_adicionados_ou_lidos_mais_recen": "가장 최근에 추가하거나 읽은 책.",
    "ordem_alfabetica_pelo_titulo": "제목순 정렬.",
    "separa_em_prateleiras_de_epub_pdf_docx": "EPUB, PDF, DOCX, 오디오북, 동영상… 칸으로 나눕니다.",
    "tipo_de_arquivo": "파일 종류",
    "organiza_e_separa_os_livros_por_autor": "책을 저자별로 정리하고 나눕니다.",
    "agrupar_por_autor": "저자별 그룹",
    "pressione_o_livro_e_mova_o": "책을 길게 눌러 옮기세요.",
    "minha_ordem": "내 순서",
    "epub_pronto": "EPUB 준비됨",
    "conversao_concluida": "변환 완료",
    "necessario_para_salvar_o_epub_ao_lado": "원본 옆에 EPUB을 저장하는 데 필요",
    "escolha_a_pasta_do_pdf": "PDF가 있는 폴더 선택",
    "processando": "처리 중…",
    "processamento_local_no_navegador": "기기에서, 브라우저에서 처리",
    "convertendo_livro": "책을 변환하는 중",
    "livro_em_pdf": "PDF 책",
    "recalculando_paginas": "페이지를 다시 계산하는 중...",
    "ajustando_leitura": "레이아웃 조정 중",
    "abrir_comentario": "댓글 열기",
    "anotacao_salva": "메모가 저장되었습니다.",
    "anotacao_atualizada": "메모가 업데이트되었습니다.",
    "escreva_uma_nota_antes_de_salvar": "저장하기 전에 메모를 작성하세요.",
    "nao_foi_possivel_compartilhar": "공유하지 못했습니다.",
    "compartilhamento_indisponivel_2": "공유를 사용할 수 없습니다.",
    "trecho_copiado": "구절이 복사되었습니다.",
    "trecho_compartilhado": "구절이 공유되었습니다.",
    "citacao_salva": "인용이 저장되었습니다.",
    "trecho_grifado": "구절이 강조되었습니다.",
    "grifo_removido": "강조가 제거되었습니다.",
    "comentario_apagado": "댓글이 삭제되었습니다.",
    "remover_grifo": "강조 제거",
    "apagar_comentario": "댓글 삭제",
    "remover_grifo_2": "강조를 제거할까요?",
    "apagar_comentario_2": "댓글을 삭제할까요?",
    "remover_este_grifo": "이 강조를 제거할까요?",
    "apagar_este_comentario": "이 댓글을 삭제할까요?",
    "sem_comentario": "댓글 없음",
    "comentario": "댓글",
    "marcador_removido_desta_pagina": "이 페이지에서 북마크가 제거되었습니다.",
    "pagina_adicionada_aos_marcadores": "페이지가 북마크에 추가되었습니다.",
    "este_e_o_inicio_do_livro": "책의 시작입니다.",
    "esta_e_a_primeira_pagina": "첫 페이지입니다.",
    "voce_chegou_ao_fim_do_livro": "책의 끝에 도착했습니다.",
    "voce_chegou_ao_fim_do_quadrinho": "만화의 끝에 도착했습니다.",
    "agora_em_revista_aberta_duas_paginas_l": "이제 펼침면으로: 두 페이지가 나란히, 표지는 따로.",
    "leitura_horizontal_ativada_neste_livro": "이 책에서 가로 읽기가 켜졌습니다.",
    "rolagem_vertical_ativada_neste_livro": "이 책에서 세로 스크롤이 켜졌습니다.",
    "leitura_pagina_a_pagina_ativada_neste": "이 만화에서 한 페이지씩 읽기가 켜졌습니다.",
    "rolagem_continua_ativada_neste_quadrin": "이 만화에서 연속 스크롤이 켜졌습니다.",
    "mudar_para_rolagem_vertical": "세로 스크롤로 전환",
    "mudar_para_leitura_horizontal": "가로 읽기로 전환",
    "rolagem_continua_estilo_webtoon": "연속 스크롤(웹툰 스타일)",
    "voltar_para_pagina_a_pagina": "한 페이지씩으로 돌아가기",
    "separando_os_capitulos": "챕터를 나누는 중...",
    "lendo_o_livro": "책을 읽는 중",
    "lendo_o_markdown": "Markdown을 읽는 중",
    "lendo_o_documento": "문서를 읽는 중",
    "pagina_indisponivel": "페이지를 사용할 수 없습니다.",
    "isto_acontece_so_desta_vez": "이번 한 번만 그렇습니다.",
    "preparando_o_quadrinho": "만화를 준비하는 중",
    "abrindo_o_quadrinho": "만화를 여는 중...",
    "montando_as_paginas": "페이지를 만드는 중...",
    "nao_foi_possivel_abrir_este_livro": "이 책을 열 수 없습니다.",
    "abertura_cancelada": "열기가 취소되었습니다.",
    "o_livro_demorou_demais_para_abrir_e_fo": "책을 여는 데 너무 오래 걸려 중단되었습니다.",
    "importe_o_arquivo_novamente_para_conti": "계속 읽으려면 파일을 다시 가져오세요.",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "이 책의 파일이 더 이상 기기에 저장되어 있지 않습니다.",
    "preparando_sua_leitura": "책을 준비하는 중...",
    "abrindo_livro": "책을 여는 중",
    "leitura_concluida": "읽기 완료.",
    "a_voz_foi_interrompida_pelo_navegador": "브라우저가 음성을 중단했습니다.",
    "nao_foi_possivel_preparar_este_trecho": "이 구절을 오디오용으로 준비할 수 없습니다.",
    "a_leitura_em_voz_alta_nao_e_suportada": "이 브라우저에서는 소리 내어 읽기를 지원하지 않습니다.",
    "pausar_leitura": "읽기 일시정지",
    "em_pausa": "일시정지됨",
    "leitura_em_voz_alta_nao_disponivel_nes": "이 브라우저에서는 소리 내어 읽기를 사용할 수 없습니다",
    "nome_do_marcador": "북마크 이름",
    "o_marcador_sera_removido_deste_audioli": "북마크가 이 오디오북에서 제거됩니다.",
    "nao_foi_possivel_salvar_o_marcador": "북마크를 저장할 수 없습니다.",
    "ja_existe_um_marcador_neste_ponto": "이 지점에 이미 북마크가 있습니다.",
    "timer_de_sono_encerrado": "수면 타이머가 끝났습니다.",
    "fim_do_cap": "챕터 끝",
    "timer_desativado": "타이머가 꺼졌습니다.",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "오디오가 챕터 끝에서 일시정지됩니다.",
    "este_audiolivro_nao_tem_capitulos": "이 오디오북에는 챕터가 없습니다.",
    "ao_fim_do_capitulo": "챕터 끝에서",
    "desativar_timer": "타이머 끄기",
    "mais_10_minutos_no_timer": "타이머에 10분 추가.",
    "somar_10_minutos": "10분 추가",
    "pausa_ao_fim_do_capitulo": "챕터 끝에서 일시정지",
    "no_livro_todo": "책 전체에서",
    "video": "동영상",
    "audiolivro_concluido": "오디오북 완료.",
    "video_concluido": "동영상 완료.",
    "video_2": "동영상",
    "audio": "오디오",
    "toque_em_reproduzir_para_comecar": "시작하려면 재생을 탭하세요.",
    "falha_ao_carregar_o_audio": "오디오를 불러오지 못했습니다.",
    "exclua_o_da_biblioteca_e_importe_o_arq": "라이브러리에서 삭제하고 파일을 다시 가져오세요.",
    "os_nomes_dos_arquivos_seguem_uma_seque": "파일 이름이 순서대로라서 한 오디오북의 챕터처럼 보입니다.",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "파일이 태그에 같은 앨범을 갖고 있어서 한 오디오북의 챕터처럼 보입니다.",
    "libere_espaco_ou_exclua_livros_da_bibl": "공간을 확보하거나 라이브러리에서 책을 삭제한 뒤 다시 시도하세요.",
    "o_armazenamento_do_aparelho_esta_cheio": "기기 저장 공간이 가득 찼습니다.",
    "preparando_a_capa": "표지를 준비하는 중...",
    "remova_esse_arquivo_da_selecao_e_tente": "그 파일을 선택에서 빼고 다시 시도하세요.",
    "sequencia": "순서",
    "o_arquivo_pode_estar_incompleto_tente": "파일이 불완전할 수 있습니다. 다시 다운로드해 보세요.",
    "conferindo_se_o_audio_pode_ser_reprodu": "오디오를 재생할 수 있는지 확인 중...",
    "conferindo_se_o_video_pode_ser_reprodu": "동영상을 재생할 수 있는지 확인 중...",
    "lendo_titulo_capitulos_e_capa": "제목, 챕터, 표지를 읽는 중...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "파일이 손상되었거나 브라우저에서 재생할 수 없는 오디오 형식일 수 있습니다. MP3 또는 M4B(AAC)로 변환해 보세요.",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "파일이 손상되었거나 브라우저에서 재생할 수 없는 동영상 형식일 수 있습니다. H.264 동영상과 AAC 오디오를 사용하는 MP4로 변환해 보세요.",
    "converta_o_audiolivro_para_m4b_com_aud": "오디오북을 AAC 오디오의 M4B(또는 MP3)로 변환하고 다시 가져오세요.",
    "converta_o_video_para_mp4_com_audio_aa": "동영상을 AAC 오디오와 H.264 동영상의 MP4로 변환하고 다시 가져오세요.",
    "o_navegador_nao_reproduz_o_formato_de": "브라우저가 이 파일의 오디오 형식을 재생하지 않습니다.",
    "arquivos_com_protecao_nao_podem_ser_re": "보호된 파일은 여기서 재생할 수 없습니다. DRM 없는 사본을 사용하세요.",
    "nao_ha_espaco_suficiente_no_aparelho_p": "이 오디오북을 담을 기기 공간이 부족합니다.",
    "confira_se_a_extensao_corresponde_ao_c_2": "확장자가 내용과 맞는지 확인하거나 오디오를 MP3 또는 M4B(AAC)로 변환하세요.",
    "imagem_invalida": "잘못된 이미지",
    "imagem_demorou_demais": "이미지를 불러오는 데 시간이 너무 오래 걸렸습니다",
    "imagem_vazia": "빈 이미지",
    "inicio": "시작",
    "mp4_moov_nao_encontrado": "동영상이 불완전하거나 손상된 것 같습니다.",
    "pagina": "페이지",
    "esta_pagina_nao_esta_disponivel": "이 페이지는 사용할 수 없습니다.",
    "esta_pagina_nao_pode_ser_descompactada": "이 페이지를 풀 수 없습니다.",
    "quadrinho_fechado": "만화를 닫았습니다.",
    "ele_pode_estar_incompleto_dividido_em": "불완전하거나, 여러 부분으로 나뉘어 있거나, 앱이 인식하지 못하는 RAR 변형일 수 있습니다. CBZ로 변환하면 보통 해결됩니다.",
    "remova_a_senha_do_arquivo_e_importe_de": "파일에서 비밀번호를 제거하고 다시 가져오세요.",
    "nao_foi_possivel_ler_este_arquivo_de_q": "이 만화 파일을 읽을 수 없습니다.",
    "este_quadrinho_esta_protegido_por_senh": "이 만화는 비밀번호로 보호되어 있습니다.",
    "lendo_o_indice_do_quadrinho": "만화의 목차를 읽는 중...",
    "o_arquivo_pode_ser_grande_demais_para": "파일이 이 기기의 메모리에 비해 너무 클 수 있습니다. 만화를 더 작게 나누면 보통 해결됩니다.",
    "nao_foi_possivel_abrir_este_quadrinho": "이 만화를 열 수 없습니다.",
    "lendo_o_arquivo": "파일을 읽는 중...",
    "preparando_o_leitor_de_cbr": "CBR 리더를 준비하는 중...",
    "o_arquivo_pode_estar_incompleto_proteg": "파일이 불완전하거나 비밀번호로 보호되었거나 손상되었을 수 있습니다.",
    "nao_foi_possivel_ler_este_quadrinho": "이 만화를 읽을 수 없습니다.",
    "o_arquivo_precisa_conter_imagens_jpg_p": "파일에 이미지(JPG, PNG, WEBP 또는 GIF)가 있어야 합니다.",
    "nao_encontramos_paginas_dentro_deste_q": "이 만화에서 페이지를 찾지 못했습니다.",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "이 만화를 담을 기기 공간이 부족합니다.",
    "cabecalho_de_item_invalido": "파일의 일부가 손상되었습니다.",
    "a_pasta_vendor_libarchive_precisa_esta": "이 만화를 여는 데 필요한 앱 구성 요소가 없습니다. CBZ로 변환하거나 앱을 다시 설치해 주세요.",
    "o_leitor_de_cbr_nao_foi_encontrado": "CBR 리더를 찾지 못했습니다.",
    "converta_o_quadrinho_para_cbz_zip_e_im": "만화를 CBZ(ZIP)로 변환하고 다시 가져오세요.",
    "este_navegador_nao_consegue_abrir_arqu": "이 브라우저는 CBR 파일을 열 수 없습니다.",
    "convertendo_o_markdown": "Markdown 변환 중",
    "lendo_o_texto": "텍스트를 읽는 중",
    "pdf_indisponivel": "PDF를 사용할 수 없습니다.",
    "epub_invalido_nenhum_capitulo_no_spine": "이 EPUB 파일이 손상되어 책의 챕터를 찾을 수 없습니다.",
    "livro_sem_titulo": "제목 없는 책",
    "epub_invalido_arquivo_opf_nao_encontra": "이 EPUB 파일이 불완전하거나 손상되어 열 수 없습니다.",
    "epub_invalido_container_xml_nao_encont": "이 EPUB 파일이 불완전하거나 손상되어 열 수 없습니다.",
    "organizando_o_texto": "텍스트를 배치하는 중",
    "descompactando_o_livro": "책을 푸는 중",
    "nao_encontramos_conteudo_para_exibir_n": "이 파일에서 보여줄 내용을 찾지 못했습니다.",
    "livro_sem_texto_legivel": "읽을 수 있는 텍스트가 없는 책",
    "o_arquivo_pode_estar_corrompido_tente": "파일이 손상되었을 수 있습니다. EPUB로 변환해 보세요.",
    "nao_foi_possivel_extrair_o_texto_deste": "이 MOBI에서 텍스트를 추출할 수 없습니다.",
    "nenhum_registro_de_conteudo_foi_encont": "이 파일에서 책의 본문을 찾을 수 없습니다.",
    "arquivo_mobi_sem_texto": "텍스트 없는 MOBI 파일.",
    "o_dicionario_de_compressao_esta_vazio": "이 MOBI 파일의 내용 일부가 없습니다.",
    "arquivo_mobi_incompleto": "불완전한 MOBI 파일.",
    "as_tabelas_de_compressao_nao_foram_enc": "이 MOBI 파일의 내용 일부가 없습니다.",
    "converta_o_arquivo_para_epub_em_um_pro": "Calibre 같은 프로그램에서 파일을 EPUB로 변환하고 다시 가져오세요.",
    "compressao_mobi_nao_reconhecida": "이 MOBI 파일은 앱이 인식하지 못하는 내부 형식을 사용합니다.",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "책의 헤더를 읽을 수 없습니다.",
    "arquivo_mobi_corrompido": "손상된 MOBI 파일.",
    "a_lista_interna_de_registros_esta_inco": "파일이 불완전합니다. 다시 다운로드하거나 변환해 보세요.",
    "o_download_parece_ter_sido_interrompid": "다운로드가 중단된 것 같습니다. 파일을 다시 다운로드하세요.",
    "tabela_de_compressao_mobi_corrompida": "이 MOBI 파일의 일부가 손상되었습니다.",
    "tabela_de_compressao_mobi_incompleta": "이 MOBI 파일이 불완전합니다.",
    "tabela_de_compressao_mobi_invalida": "이 MOBI 파일의 일부가 손상되었습니다.",
    "este_arquivo_docx_nao_tem_conteudo_de": "이 .docx 파일에는 표시할 텍스트 내용이 없습니다.",
    "documento_sem_texto": "텍스트 없는 문서",
    "o_arquivo_pode_estar_corrompido_proteg": "파일이 손상되었거나, 비밀번호로 보호되었거나, 구식 .doc일 수 있습니다. .docx로 다시 저장하고 한 번 더 가져오세요.",
    "nao_foi_possivel_ler_este_arquivo_docx": "이 DOCX 파일을 읽을 수 없습니다.",
    "convertendo_o_documento": "문서를 변환하는 중",
    "conecte_se_a_internet_uma_vez_para_bai": "구성 요소를 내려받기 위해 한 번 인터넷에 연결한 뒤 책을 다시 여세요.",
    "o_conversor_de_docx_nao_carregou": "DOCX 변환기가 로드되지 않았습니다.",
    "video_mp4": "동영상 (MP4)",
    "audiolivro_m4b": "오디오북 (M4B)",
    "audiolivro_mp3": "오디오북 (MP3)",
    "quadrinho_cbt": "만화 (CBT)",
    "quadrinho_cb7": "만화 (CB7)",
    "quadrinho_cbr": "만화 (CBR)",
    "quadrinho_cbz": "만화 (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "텍스트 (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "저장이 취소되었습니다.",
    "o_arquivo_esta_vindo_do_armazenamento": "파일이 클라우드 저장소에서 기기로 내려오고 있습니다.",
    "baixando_o_arquivo": "파일을 내려받는 중",
    "cancelando": "취소하는 중...",
    "use_grifar_citacao_anotar_ou_marcador": "읽는 동안 강조, 인용, 메모 또는 북마크를 사용하세요.",
    "nenhuma_marcacao_ainda": "아직 표시 없음",
    "trecho_original": "원문 구절",
    "procurar_meus_livros": "내 책 찾기",
    "a_busca_fica_sempre_disponivel_no_menu": "검색은 항상 사이드 메뉴의 시스템 아래에 있습니다.",
    "da_para_fazer_depois": "나중에 해도 됩니다",
    "nada_entra_na_estante_sem_a_sua_confir": "확인 없이 책장에 추가되는 것은 없습니다. 목록을 보고 가져올 항목을 직접 고르세요.",
    "voce_revisa_antes": "가져오기 전에 직접 확인합니다",
    "escolha_uma_pasta_downloads_e_um_bom_c": "폴더를 고르세요(Downloads가 좋은 시작점입니다). 앱이 그 폴더와 모든 하위 폴더를 검색합니다.",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR 및 M4B를 검색",
    "voltar_e_revisar": "돌아가 검토",
    "ler_os_termos": "약관 읽기",
    "ler_a_politica": "방침 읽기",
    "os_dois_documentos_ficam_sempre_dispon": "두 문서 모두 항상 사이드 메뉴의 정보 아래에 있습니다.",
    "leia_com_calma": "천천히 읽어 보세요",
    "a_politica_e_os_termos_explicam_como_o": "방침과 약관은 앱이 책을 어떻게 보관하는지, 그리고 책으로 무엇을 할 수 있는지 설명합니다. 라이브러리를 사용하려면 이에 동의해야 합니다.",
    "nada_acontece_sem_o_aceite": "시작하려면 약관에 동의해 주세요",
    "aceitar_e_continuar": "동의하고 계속",
    "nao_aceito": "동의하지 않음",
    "termos_de_uso_2": "이용 약관",
    "politica_de_privacidade_2": "개인정보 처리방침",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "앱은 사용자가 선택한 파일과 폴더에만, 선택한 때에만 접근합니다.",
    "voce_no_controle": "직접 선택하고 관리합니다",
    "depois_de_importar_um_livro_voce_le_se": "책을 가져오면 인터넷 없이 읽습니다.",
    "funciona_offline": "오프라인으로 작동합니다",
    "livros_marcacoes_e_progresso_sao_guard": "책, 표시, 진행 상황은 기기에 보관됩니다. 우리 서버로 아무것도 보내지 않습니다.",
    "tudo_fica_no_seu_aparelho": "모든 것이 기기에 남습니다",
    "escolha_o_que_deseja_adicionar_a_bibli": "라이브러리에 추가할 것을 고르세요. 이미 책장에 있는 것과 동일한 파일은 자동으로 건너뜁니다.",
    "voce_pode_tentar_outra_pasta_ou_import": "다른 폴더를 시도하거나 + 버튼으로 파일을 가져올 수 있습니다.",
    "a_leitura_acontece_so_no_seu_dispositi": "읽기는 이 기기 안에서만 이루어집니다.",
    "voce_escolhe_a_pasta": "폴더는 직접 고릅니다",
    "tema_tipografia_margens_modo_de_virada": "테마, 서체, 여백, 페이지 넘김 방식 및 오디오 설정.",
    "restaurar_minhas_preferencias": "내 설정 복원",
    "o_backup_manda_as_marcacoes_atuais_dos": "백업이 우선합니다. 파일에 있는 책들의 현재 표시는 백업의 것으로 교체됩니다.",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "아무것도 지워지지 않습니다. 양쪽 표시가 합쳐지고 더 최근 진행 상황이 우선합니다.",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "이미 책장에 있는 것들을 어떻게 할까요",
    "grifos_citacoes_e_notas": "강조, 인용 및 메모",
    "preparando_o_arquivo_2": "파일을 준비하는 중...",
    "os_livros_em_si_nem_as_capas_por_isso": "책 파일도 표지도 포함되지 않습니다. 그래서 파일 크기가 몇 KB밖에 되지 않습니다. 받는 사람에게 책 파일이 있어야 표시가 제자리로 돌아오며, 표지는 책을 가져올 때 자동으로 다시 나타납니다.",
    "nao_vai_no_arquivo": "파일에 없음",
    "o_seu_progresso_de_leitura_os_grifos_a": "읽기 진행 상황, 강조, 인용, 메모, 북마크와 책장 구성 — 상태, 즐겨찾기, 컬렉션, 시리즈 및 태그.",
    "vai_no_arquivo": "파일에 있음",
    "descartar_o_que_esta_esperando_2": "대기 중인 데이터 삭제",
    "esperando_o_arquivo": "파일을 기다리는 중",
    "avisar_quando_fizer_tempo_sem_backup": "백업 없이 오래 지나면 알려 주기",
    "livros_que_ainda_nao_estiverem_na_esta": "아직 책장에 없는 책은 대기 상태로 보관됩니다. 해당 파일을 가져오면 표시가 자동으로 돌아옵니다.",
    "restaurar_backup": "백업 복원",
    "salvar_backup": "백업 저장",
    "ainda_nao_ha_itens": "아직 아무것도 없습니다",
    "arraste_um_livro_para_outra_posicao_na": "책을 책장의 다른 위치로 끌어 자신만의 순서를 저장하세요. 이 수동 순서는 저자별 그룹화보다 우선합니다.",
    "separe_por_virgulas": "쉼표로 구분",
    "ex_estudos_ficcao": "예: 공부, 소설...",
    "pasta_estante": "폴더 / 책장",
    "ex_trilogia": "예: 삼부작...",
    "serie": "시리즈",
    "aparece_em_favoritos": "즐겨찾기에 나타납니다.",
    "nome_do_livro": "책 이름",
    "nenhum_registro_ainda": "아직 기록 없음",
    "no_leitor_toque_no_icone_de_marcador_p": "리더에서 북마크 아이콘을 눌러 페이지를 저장하세요.",
    "nenhum_marcador_ainda": "아직 북마크 없음",
    "a_gravacao_e_independente_da_localizac": "저장은 PDF 위치와 무관하며 원본 파일을 바꾸지 않습니다.",
    "o_pdf_original_nao_precisa_estar_nessa": "원본 PDF가 그 폴더에 있을 필요는 없습니다",
    "excluir_da_biblioteca": "라이브러리에서 삭제",
    "adicionar_livro": "책 추가",
    "adicione_livros_e_acompanhe_o_que_esta": "책을 추가하고 무엇이 기다리고, 무엇이 진행 중이며 얼마나 나아갔는지 확인하세요.",
    "tudo_pronto_para_a_proxima_leitura": "다음 읽기를 위한 모든 준비 완료.",
    "sua_biblioteca": "내 라이브러리",
    "arraste_um_livro_para_reposiciona_lo_a": "책을 끌어 옮기세요: 책장이 내 순서로 바뀌고 순서를 유지합니다.",
    "importe_um_livro_ou_ajuste_seus_filtro": "책을 가져오거나 필터를 조정하세요.",
    "nada_por_aqui_ainda": "아직 아무것도 없습니다",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "+를 누르고 MP3, M4B 또는 MP4 파일을 고르세요. 여러 챕터의 MP3가 하나의 오디오북이 될 수 있습니다.",
    "nada_para_ouvir_ou_assistir_ainda": "아직 듣거나 볼 것이 없습니다",
    "o_pdf_original_permanece_intacto_na_pa": "원본 PDF는 원래 폴더에 그대로 남아 있습니다.",
    "paginas_como_imagem": "이미지로 된 페이지",
    "paginas_do_pdf": "PDF 페이지",
    "em_navegadores_sem_suporte_a_acesso_di": "파일 시스템 직접 접근을 지원하지 않는 브라우저에서는 대신 EPUB이 다운로드됩니다.",
    "essa_permissao_e_dada_somente_a_esta_a": "이 권한은 이 앱에만 주어지며 원본 파일이 바뀌지 않게 합니다.",
    "selecione_a_pasta_que_contem_o_pdf": "PDF가 있는 폴더 선택",
    "preparando": "준비 중…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "파일을 읽고 다시 만드는 중입니다. 큰 책은 잠시 걸릴 수 있습니다.",
    "revistas_apostilas_complexas_formulari": "잡지, 복잡한 학습서, 양식, 표가 많은 문서 또는 스캔한 PDF는 원래 레이아웃의 일부를 잃을 수 있습니다.",
    "funcionalidade_indicada_apenas_para_li": "책에만 권장되는 기능",
    "o_epub_e_melhor_para_livros_com_texto": "EPUB은 선택 가능한 텍스트가 있는 책에 더 좋습니다. 서체, 크기, 여백과 읽기 모드를 조정할 수 있기 때문입니다.",
    "trecho_selecionado": "선택한 구절",
    "trecho_comentado": "댓글이 있는 구절",
    "aplicando_zoom": "확대 중...",
    "nao_foi_possivel_carregar_esta_pagina": "이 페이지를 불러올 수 없습니다.",
    "nomear_marcador": "북마크 이름 지정",
    "toque_em_marcar_agora_para_guardar_est": "“지금 표시”를 눌러 이 지점을 저장하고 언제든 돌아오세요.",
    "timer_ativo": "타이머 켜짐",
    "trecho_ausente_ou_corrompido_no_arquiv": "[원본 파일에서 구절이 없거나 손상됨]",
    "novos_livros_vao_abrir_em_leitura_v": "새 책이 {v} 읽기로 열립니다.",
    "leitura_efetivo_aplicada_a_este_livro": "이 책에 {efetivo} 읽기가 적용되었습니다.",
    "automatico_neste_livro_leitura_efetivo": "이 책에서 자동: {efetivo} 읽기.",
    "agora_esta_em_efetivo_no_automatico_fo": "이제 {efetivo}로 설정됨; 자동에서는 {format}이(가) {padrao}로 열립니다.",
    "esta_escolha_vale_so_para_v_cada_livro": "이 선택은 “{v}”에만 적용됩니다. 각 책은 스크롤 방향을 따로 갖습니다.",
    "novos_ainda_nao_estao_na_sua_estante": "{novos}은(는) 아직 책장에 없습니다.",
    "escolha_uma_pasta_para_procurar_label": "{label}을(를) 찾을 폴더를 고르세요.",
    "subtitle_versao_build": "{subtitle} · 버전 {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "{path}을(를) 읽을 수 없습니다; 내장 텍스트를 사용합니다.",
    "seu_ultimo_backup_foi_ha_dias_dias": "마지막 백업이 {dias}일 전이었습니다",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "백업에 있는 책 {aguardando}권이 아직 여기에 없습니다. 이 책의 진행 상황과 표시는 보관되어 있으니, 파일을 가져오면 모두 자동으로 제자리로 돌아옵니다.",
      "other": "백업에 있는 책 {aguardando}권이 아직 여기에 없습니다. 이 책들의 진행 상황과 표시는 보관되어 있으니, 각 파일을 가져오면 모두 자동으로 제자리로 돌아옵니다."
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "책장의 {atualizados}권이 업데이트되었습니다.",
      "other": "책장의 {atualizados}권이 업데이트되었습니다."
    },
    "criado_em_quando": "{quando}에 생성",
    "backup_pronto_livros_livro_s_e_marcaco": "백업 준비 완료: {livros}권, {marcacoes}개 표시.",
    "endereco_seguro_seguro": "보안 주소: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "이 책의 진행과 {marcas}개 표시가 복원되었습니다.",
      "other": "이 책의 진행과 {marcas}개 표시가 복원되었습니다."
    },
    "restaurando_v_de_length": "복원 중 ({v} / {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros}권 · {marcacoes}개 표시",
    "criado_em_v": "{v}에 생성",
    "reunindo_a_sua_estante_v_de_length": "책장을 모으는 중 ({v} / {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "“{titulo}”은(는) 전에 가져와 라이브러리에 남아 있습니다. 새 사본을 만들지 않았습니다.",
    "length_arquivos_de_audio": "{length}개 오디오 파일...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "{falhas}개 파일을 읽을 수 없습니다.",
      "other": "{falhas}개 파일을 읽을 수 없습니다."
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos}은(는) 이미 라이브러리에 있어 건너뛰었습니다.",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "{importados}권이 책장에 추가되었습니다.",
      "other": "{importados}권이 책장에 추가되었습니다."
    },
    "epub_salvo_em_filename": "EPUB이 {fileName}에 저장되었습니다.",
    "falha_ao_converter_o_pdf_v": "PDF 변환 실패: {v}",
    "pagina_page_de_totalpages": "{page}페이지 / {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages}페이지",
      "other": "{totalPages}페이지"
    },
    "length_resultado_s_para_search": {
      "one": "“{search}”에 대한 {length}개 결과",
      "other": "“{search}”에 대한 {length}개 결과"
    },
    "capitulo_v": "챕터 {v}",
    "organizando_capitulo_v_de_totalchapter": "챕터 {v} / {totalChapters} 배치 중",
    "pagina_v": "페이지 {v}",
    "paginas_v_v2": "페이지 {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length}페이지 준비됨",
      "other": "{length}페이지 준비됨"
    },
    "montando_as_paginas_pagessofar_prontas": "페이지를 만드는 중 — {pagesSoFar} 완료",
    "lendo_pagina_v_de_length": "{v} / {length}페이지를 읽는 중",
    "marcador_salvo_em_t": "북마크가 {t}에 저장되었습니다.",
    "o_audio_vai_pausar_em_minutes_minutos": "오디오가 {minutes}분 후에 일시정지됩니다.",
    "length_capitulos_toque_para_ir_direto": "{length}개 챕터 · 바로 가려면 탭하세요.",
    "narrado_por_narrator": "{narrator} 낭독",
    "velocidade_de_reproducao_rate": "재생 속도: {rate}",
    "avancar_f_segundos": "{f}초 앞으로",
    "nao_foi_possivel_abrir_este_v": "이 {v}을(를) 열 수 없습니다.",
    "nao_foi_possivel_ler_o_arquivo_de_v": "{v} 파일을 읽을 수 없습니다.",
    "o_v_esta_danificado_neste_ponto": "{v}이(가) 이 지점에서 손상되었습니다.",
    "o_navegador_nao_consegue_reproduzir_es": "브라우저가 이 {v} 파일을 재생할 수 없습니다.",
    "nao_foi_possivel_reproduzir_este_v": "이 {v}을(를) 재생할 수 없습니다.",
    "os_dados_deste_noun_estao_incompletos": "이 {noun}의 데이터가 불완전합니다.",
    "importe_o_arquivo_novamente_para_conti_2": "{v}을(를) 계속하려면 파일을 다시 가져오세요.",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "이 {noun}의 파일이 더 이상 기기에 저장되어 있지 않습니다.",
    "nao_foi_possivel_descobrir_a_duracao_d": "“{name}”의 길이를 알 수 없습니다.",
    "lendo_faixa_v_de_length": "트랙 {v} / {length} 읽는 중...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "이 {v}의 길이를 알 수 없습니다.",
    "este_format_nao_pode_ser_reproduzido_n": "이 {format}은(는) 이 브라우저에서 재생할 수 없습니다.",
    "este_format_esta_protegido_por_drm": "이 {format}은(는) DRM으로 보호되어 있습니다.",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "파일은 {bytes}이고 약 {v} 남았습니다. 공간을 확보하거나 라이브러리에서 책을 삭제하세요.",
    "este_arquivo_nao_e_um_format_valido": "이 파일은 유효한 {format}이(가) 아닙니다.",
    "preparando_as_paginas_vistas_de_total": "페이지 준비 중 ({vistas} / {total})...",
    "preparando_total_pagina_s": {
      "one": "{total}페이지 준비 중...",
      "other": "{total}페이지 준비 중..."
    },
    "preparando_as_paginas_v_de_total": "페이지 준비 중 ({v} / {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "약 {bytes}를 차지하고 {v} 정도 남았습니다. 공간을 확보하거나 라이브러리에서 책을 삭제하세요.",
    "envio_direto_exige_endereco_seguro": "이 페이지가 보안 주소로 열리지 않아 다른 앱으로 바로 보낼 수 없습니다. 파일을 저장한 뒤 원하는 앱으로 보내 주세요.",
    "na_estante": "책장에",
    "nao_foi_possivel_montar_o_arquivo": "파일을 만들 수 없습니다.",
    "este_navegador_nao_oferece_o_envio_dir": "이 브라우저는 다른 앱으로 직접 보내기를 제공하지 않습니다. 파일을 저장하고 원하는 앱으로 첨부하세요.",
    "voce_ainda_nao_fez_nenhum_backup": "아직 백업을 만들지 않았습니다.",
    "converter_para_epub": "EPUB으로 변환",
    "esta_pagina_nao_pode_ser_exibida": "이 페이지를 표시할 수 없습니다.",
    "na_ordem_em_que_serao_tocados": "재생될 순서대로",
    "este_capitulo_nao_pode_ser_exibido": "이 챕터를 표시할 수 없습니다.",
    "livro": "책",
    "restantes": " 남음",
    "como_seus_dados_sao_tratados": "내 데이터 처리 방식",
    "condicoes_de_uso_do_aplicativo": "앱 사용 조건",
    "audiolivro": "오디오북",
    "sobre_o_aplicativo": "앱 정보",
    "o_que_e_o_veredas_reader": "Veredas Reader란",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(이 기기에서는 이 파일 형식을 공유할 수 없습니다)",
    "livros": "권",
    "lendo": "읽는 중",
    "lidos": "완독",
    "compartilhar_livro": "책 공유",
    "n_livros": {
      "one": "{n}권",
      "other": "{n}권"
    },
    "livros_unidade": {
      "one": "권",
      "other": "권"
    },
    "uma_faixa_discreta_depois_de_n_dias": "{n}일 동안 백업하지 않으면 책장에 눈에 띄지 않는 안내가 표시됩니다. 읽기를 방해하지 않습니다.",
    "scanned_arquivos_verificados_livros_enc": "{scanned}개 파일 확인 · {encontrados}권 발견",
    "v_de_total": "{v} / {total}",
    "voltar_n_segundos": "{n}초 뒤로",
    "cancelado": "취소됨",
    "arquivo": "파일",
    "outro": "기타",
    "outros": "기타",
    "audiolivro_2": "오디오북",
    "pausar": "일시정지",
    "marcador": "북마크",
    "leitura": "읽기",
    "grifo": "강조",
    "editar": "편집",
    "apagar": "삭제",
    "concluir": "완료",
    "recentes": "최근",
    "progresso": "진행",
    "entendi": "알겠습니다",
    "aviso": "알림",
    "descartar": "삭제",
    "copiado": "복사됨",
    "restaurar": "복원",
    "restaurando": "복원 중",
    "excluir": "삭제",
    "grifos": "강조",
    "arquivo_vazio": "빈 파일입니다.",
    "e_mais_n_arquivos": {
      "one": "외 {n}개 파일, 재생될 순서대로",
      "other": "외 {n}개 파일, 재생될 순서대로"
    },
    "n_arquivos_mp3": {
      "one": "MP3 파일 {n}개",
      "other": "MP3 파일 {n}개"
    },
    "pct_restam": "{pct}% · {tempo} 남음",
    "n_minutos": {
      "one": "{n}분",
      "other": "{n}분"
    },
    "ir_para_tempo": "{tempo}(으)로 이동",
    "nomear": "이름 지정",
    "parte_n": "파트 {n}",
    "carregando_pagina_n": "{n}페이지 불러오는 중...",
    "selecionar_pasta_e_continuar": "폴더 선택 후 계속",
    "ler_agora": "지금 읽기",
    "agrupamento_v": "그룹: {v}",
    "tempo_restante": "{tempo} 남음",
    "abrir_titulo": "{titulo} 열기",
    "continuar_lendo_titulo": "{titulo} 계속 읽기",
    "continuar_ouvindo_titulo": "{titulo} 계속 듣기",
    "continuar_assistindo_titulo": "{titulo} 계속 보기",
    "lido": "완독",
    "pausado": "일시정지",
    "status": "상태",
    "favorito": "즐겨찾기",
    "escolher_local": "위치 선택",
    "epub_baixado_como": "EPUB을 {nome}(으)로 내려받았습니다.",
    "ouvir_a_partir_de": "{tempo}부터 듣기",
    "assistir_a_partir_de": "{tempo}부터 보기",
    "pagina_n_minuscula": "{n}페이지",
    "selecione_trecho_para_criar": "읽는 중에 구절을 선택해 {oque}을(를) 만드세요.",
    "excluir_oque_pergunta": "{oque}을(를) 삭제할까요?",
    "excluir_oque": "{oque} 삭제",
    "excluir_item_pergunta": "이 항목을 삭제할까요?",
    "use_organizar_para_criar": "책에서 “{botao}”을(를) 사용해 {oque}을(를) 만드세요.",
    "n_arquivos_processados": {
      "one": "파일 {n}개 처리됨",
      "other": "파일 {n}개 처리됨"
    },
    "voce_ja_tem_titulo_de_autor": "파일은 다르지만 {autor}의 “{titulo}”이(가) 이미 서재에 있습니다. 그래도 가져올까요?",
    "voce_ja_tem_titulo": "파일은 다르지만 “{titulo}”이(가) 이미 서재에 있습니다. 그래도 가져올까요?",
    "marcadores_unidade": {
      "one": "북마크",
      "other": "북마크"
    },
    "ultimo_backup_em": "마지막 백업: <strong>{data}</strong>",
    "guardar": "저장",
    "lembretes": "알림",
    "juntar": "합치기",
    "recomendado": "권장",
    "substituir": "바꾸기",
    "n_capas_recuperadas": {
      "one": "표지 {n}개를 복구했습니다.",
      "other": "표지 {n}개를 복구했습니다."
    },
    "nao_encontramos_arquivos_tipo": "이 폴더에서 {tipo} 파일을 찾지 못했습니다.",
    "tentar_outra_pasta": "다른 폴더 시도",
    "n_livros_encontrados": {
      "one": "책 {n}권을 찾았습니다",
      "other": "책 {n}권을 찾았습니다"
    },
    "n_de_total_selecionados": {
      "one": "{total}개 중 {n}개 선택됨",
      "other": "{total}개 중 {n}개 선택됨"
    },
    "importar": "가져오기",
    "importar_n": "{n}개 가져오기",
    "aceite_frase": "Veredas Reader의 {politica} 및 {termos}을 읽었으며 이에 동의합니다.",
    "pdf_preservado": "원본 PDF는 <strong>사용자 폴더에서 지워지지 않습니다</strong>. EPUB이 제대로 저장된 뒤에 이 PDF의 사본만 서재에서 빠집니다.",
    "gravar_epub_mesma_pasta": "EPUB을 <strong>PDF와 같은 폴더에</strong> 저장하려면 브라우저가 그 폴더에 접근할 권한이 필요합니다.",
    "epub_pronto_qualquer_pasta": "EPUB 변환이 끝났습니다. 이제 <strong>컴퓨터의 아무 폴더</strong>나 골라 파일을 저장할 수 있습니다.",
    "backup_explicacao": "원본 백업은 ZIP 또는 TXT 파일입니다. 다른 기기에서 받으면 <strong>백업 복원</strong>으로 가져오세요. Veredas가 내용을 알아보고 정상적으로 복원합니다. 파일에는 진행 상황, 강조, 인용, 메모, 북마크와 책장 구성이 담기며, <strong>책 자체</strong>와 표지는 포함되지 않습니다.",
    "lembretes_desligados_frase": "알림이 <strong>꺼져 있습니다</strong>. 가끔 백업하는 것을 잊지 마세요.",
    "backup_salvo_nos_downloads": "<strong>백업 파일이 이 기기에 저장되었습니다</strong>(다운로드 폴더). 지금 바로 보낼 수 있습니다: WhatsApp, 이메일, Drive 등 원하는 앱을 열고 첨부를 눌러 파일을 고르세요.",
    "arquivo_pronto_tamanho": "파일 준비됨 — <strong>{tamanho}</strong>",
    "scan_intro_frase": "앱이 기기의 한 폴더(하위 폴더 포함)에서 <strong>EPUB</strong>·<strong>MOBI</strong> 책, <strong>CBZ</strong>·<strong>CBR</strong> 만화, <strong>M4B</strong> 오디오북을 찾을 수 있습니다.",
    "scan_intro_auto_frase": "책장을 빠르게 채우기 위해 앱이 기기의 한 폴더(하위 폴더 포함)에서 <strong>EPUB</strong>·<strong>MOBI</strong> 책, <strong>CBZ</strong>·<strong>CBR</strong> 만화, <strong>M4B</strong> 오디오북을 찾을 수 있습니다.",
    "n_livros_aguardando": {
      "one": "<strong>{n}권</strong>의 진행 상황과 표시가 보관되어 있으며, 다시 가져오기를 기다리고 있습니다.",
      "other": "<strong>{n}권</strong>의 진행 상황과 표시가 보관되어 있으며, 다시 가져오기를 기다리고 있습니다."
    },
    "fora_da_busca_titulo": "PDF, TXT, DOCX(Word), MD, MP3, MP4 파일은 자동으로 가져오지 않습니다",
    "fora_da_busca_texto": "이 형식들은 책뿐 아니라 온갖 종류의 문서에 쓰입니다. 제외해 두면 책장이 깔끔하게 유지됩니다. <strong>+ 버튼으로 하나씩 직접 가져올 수 있습니다.</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "로컬 라이브러리",
    "biblioteca": "라이브러리",
    "organizacao": "구성",
    "minhas_marcacoes": "내 표시",
    "sistema": "시스템",
    "sua_biblioteca": "내 라이브러리",
    "toque_em_um_livro_para_comecar_a_ler": "책을 탭해 읽기 시작하세요.",
    "agrupar": "그룹",
    "sua_estante_nao_tem_copia_de_seguranca": "책장에 백업이 없습니다",
    "se_este_aparelho_se_perder_o_progresso": "이 기기에 문제가 생기면 진행 상황과 표시를 잃을 수 있습니다.",
    "agora_nao": "나중에",
    "nao_avisar_mais": "다시 알리지 않기",
    "carregando": "불러오는 중...",
    "estante": "책장",
    "lendo": "읽는 중",
    "favoritos": "즐겨찾기",
    "marcas": "표시",
    "mais": "더보기",
    "neste_capitulo": "이 챕터에서",
    "velocidade": "속도",
    "timer": "타이머",
    "marcar": "표시",
    "marcadores": "북마크",
    "personalizar_leitura": "읽기 설정",
    "as_preferencias_ficam_salvas_para_as_p": "설정은 다음 읽기를 위해 저장됩니다.",
    "tema": "테마",
    "claro": "밝게",
    "sepia": "세피아",
    "escuro": "어둡게",
    "oceano": "바다",
    "tipografia": "서체",
    "texto": "텍스트",
    "tamanho": "크기",
    "espacamento": "줄 간격",
    "margens": "여백",
    "cores_personalizadas_opcional": "사용자 지정 색상 (선택)",
    "fundo": "배경",
    "fonte": "텍스트 색상",
    "brilho": "밝기",
    "orientacao": "방향",
    "auto": "자동",
    "retrato": "세로",
    "paisagem": "가로",
    "modo_de_leitura": "읽기 모드",
    "automatico": "자동",
    "horizontal": "가로",
    "vertical": "세로",
    "automatico_usa_rolagem_horizontal_para": "자동은 EPUB, MOBI, TXT와 MD에는 가로 페이지 넘김을, PDF와 DOCX에는 세로 스크롤을 사용합니다. 읽는 중에 바꾸면 그 책에만 적용됩니다.",
    "quadrinhos": "만화",
    "como_a_pagina_aparece": "페이지 맞춤",
    "pagina_inteira": "전체 페이지",
    "largura_da_tela": "화면 너비",
    "sentido_da_leitura": "읽기 방향",
    "normal": "일반 →",
    "manga": "← 망가",
    "revista_aberta_na_horizontal": "가로에서 펼침면",
    "com_o_aparelho_deitado_mostra_duas_pag": "옆으로 들면 두 페이지가 나란히 보입니다 — 표지는 따로, 진짜 만화처럼 열립니다.",
    "normal_vira_da_esquerda_para_a_direita": "일반은 왼쪽에서 오른쪽으로 넘깁니다. 망가는 모든 것을 뒤집습니다: 스와이프, 가장자리 탭과 펼침면에서 두 페이지 순서.",
    "gire_o_aparelho_para_a_horizontal_para": "두 페이지를 한 번에 보려면 기기를 옆으로 돌리세요.",
    "dois_toques_ampliam_no_ponto_tocado_co": "두 번 탭하면 탭한 곳이 확대됩니다; 확대되면 끌어서 페이지를 이동하세요. 두 손가락으로 집기도 됩니다.",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "리더 위쪽의 스크롤 버튼이 한 페이지씩과 연속 스크롤(웹툰 스타일)을 전환합니다. 연속 스크롤에서는 페이지가 이어지고, 확대하면 페이지가 넓어져 옆으로 스크롤하며 이동합니다.",
    "virada_de_pagina": "페이지 넘김",
    "folha_real": "실제 종이",
    "deslizar": "슬라이드",
    "sem_animacao": "애니메이션 없음",
    "na_leitura_horizontal_arraste_a_pagina": "가로 읽기에서는 손가락으로 접으려면 페이지를 가장자리에서 끌어 보세요. 중간에 놓으면 넘김이 취소됩니다.",
    "ouvir_leitura": "듣기",
    "continue_de_onde_parou_no_seu_ritmo": "멈춘 곳에서, 나만의 속도로.",
    "livro": "책",
    "pronto_para_comecar": "시작할 준비됨",
    "voz": "음성",
    "escolha_uma_voz_disponivel_no_disposit": "이 기기에서 사용할 수 있는 음성을 고르세요",
    "voz_padrao_do_sistema": "시스템 기본 음성",
    "durante_a_reproducao": "재생 중",
    "a_leitura_avanca_pagina_a_pagina_os_co": "읽기는 페이지 단위로 나아갑니다. 브라우저가 지원하면 시스템 컨트롤이 나타납니다.",
    "organizar_livro": "책 정리",
    "estantes_colecoes_tags_e_status": "책장, 컬렉션, 태그 및 상태.",
    "cancelar": "취소",
    "salvar": "저장",
    "grifos_citacoes_notas_e_marcadores_des": "이 책의 강조, 인용, 메모와 북마크.",
    "sumario": "목차",
    "toque_em_um_capitulo_para_ir_direto_ao": "챕터를 탭해 바로 이동하세요.",
    "sua_anotacao": "내 메모",
    "edite_ou_adicione_comentarios_ao_seu_t": "구절에 댓글을 편집하거나 추가하세요.",
    "trecho": "구절",
    "sua_nota": "내 메모",
    "salvar_nota": "메모 저장",
    "agrupar_biblioteca": "라이브러리 그룹화",
    "escolha_como_os_livros_serao_organizad": "책장에서 책이 어떻게 정리될지 고르세요.",
    "ao_arrastar_um_livro_para_outra_posica": "책을 다른 위치로 끌면 책장이 자동으로 내 순서로 바뀌고, 직접 정한 순서가 유지됩니다.",
    "backup_e_restauracao": "백업 및 복원",
    "sua_estante_seu_progresso_e_suas_marca": "책장, 진행과 표시를 한 파일에.",
    "escolha_uma_dimensao_para_explorar_sua": "라이브러리를 살펴볼 방법을 고르세요.",
    "capitulos": "챕터",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "음성의 높낮이는 그대로입니다. 이 책과 다음 책에 적용됩니다.",
    "ajuste_fino": "세부 조정",
    "timer_de_sono": "수면 타이머",
    "o_audio_diminui_de_volume_aos_poucos_e": "오디오 볼륨이 서서히 줄어들다가 자동으로 일시정지됩니다.",
    "pontos_que_voce_guardou_neste_audioliv": "이 오디오북에서 저장한 지점.",
    "ajustes_do_audio": "오디오 설정",
    "as_preferencias_ficam_salvas_para_todo": "이 설정은 모든 오디오북에 저장됩니다.",
    "botao_de_voltar": "뒤로 버튼",
    "botao_de_avancar": "앞으로 버튼",
    "recuar_ao_retomar": "다시 시작할 때 되감기",
    "depois_de_uma_pausa_longa_volta_alguns": "긴 멈춤 후 몇 초 뒤로 가서 흐름을 다시 잡을 수 있습니다.",
    "tocar_ao_abrir": "열면 재생",
    "ao_tocar_em_um_audiolivro_na_estante_a": "책장에서 오디오북을 탭하면 바로 재생이 시작됩니다.",
    "no_computador_espaco_toca_e_pausa_pula": "컴퓨터: space 재생/일시정지 · ← → 건너뛰기 · Shift + ← → 챕터 변경 · ↑ ↓ 볼륨 · B 북마크 · [ ] 속도.",
    "converter_pdf_para_epub": "PDF를 EPUB으로 변환",
    "prepare_o_livro_para_leitura_fluida_e": "책을 매끄럽고 조정 가능한 읽기로 준비하세요.",
    "confirmacao": "확인",
    "confirmar": "확인",
    "processando": "처리 중",
    "documento": "문서",
    "buscar_livros_no_dispositivo": "이 기기에서 책 찾기",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "기기에 저장된 EPUB, MOBI, CBZ, CBR 및 M4B 파일을 찾으세요.",
    "juntar_em_um_unico_audiolivro": "하나의 오디오북으로 합칠까요?",
    "titulo": "제목",
    "autor": "저자",
    "importar_separados": "따로 가져오기",
    "bem_vindo_ao_veredas_reader": "Veredas Reader에 오신 것을 환영합니다",
    "sua_biblioteca_de_leitura_inteiramente": "나만의 독서 라이브러리, 모두 이 기기 안에.",
    "buscar": "검색",
    "importar_livro": "책 가져오기",
    "buscar_titulo_autor_tag": "제목, 저자, 태그 검색...",
    "fechar_busca": "검색 닫기",
    "navegacao_da_biblioteca": "라이브러리 탐색",
    "fechar_menu": "메뉴 닫기",
    "agrupar_livros": "책 그룹화",
    "voltar": "뒤로",
    "marcar_pagina": "페이지 표시",
    "personalizar": "설정",
    "navegacao_principal": "주 탐색",
    "acoes_do_trecho": "구절 작업",
    "amarelo": "노랑",
    "verde": "초록",
    "rosa": "분홍",
    "azul": "파랑",
    "player_de_audiolivro": "오디오북 플레이어",
    "minimizar_player": "플레이어 최소화",
    "minimizar": "최소화",
    "video_em_reproducao": "동영상 재생 중",
    "abrir_a_lista_de_capitulos": "챕터 목록 열기",
    "posicao_no_audio": "오디오 위치",
    "alternar_entre_o_progresso_do_capitulo": "챕터 진행과 책 전체 진행 전환",
    "capitulo_anterior": "이전 챕터",
    "voltar_15_segundos": "15초 뒤로",
    "reproduzir": "재생",
    "avancar_30_segundos": "30초 앞으로",
    "proximo_capitulo": "다음 챕터",
    "velocidade_de_reproducao": "재생 속도",
    "marcar_este_ponto": "이 지점 표시",
    "ver_marcadores": "북마크 보기",
    "silenciar": "음소거",
    "volume": "볼륨",
    "audiolivro_em_reproducao": "오디오북 재생 중",
    "abrir_o_player": "플레이어 열기",
    "fechar_o_player": "플레이어 닫기",
    "fechar": "닫기",
    "trecho_anterior": "이전 구절",
    "iniciar_leitura": "소리 내어 읽기 시작",
    "proximo_trecho": "다음 구절",
    "escreva_seu_comentario_interpretacao_o": "댓글, 해석 또는 알림을 작성하세요...",
    "cancelar_importacao": "가져오기 취소",
    "nome_do_audiolivro": "오디오북 이름",
    "nome_do_autor": "저자 이름",
    "idioma": "언어",
    "idioma_do_aplicativo": "앱 언어",
    "o_aplicativo_segue_o_idioma_do_apare": "앱은 기기의 언어를 따릅니다. 사용 중인 언어가 아직 지원되지 않으면 영어로 표시됩니다.",
    "seguir_o_aparelho": "기기 따르기",
    "fazer_backup": "지금 백업",
    "todos": "전체",
    "lidos": "완독",
    "pausados": "일시정지",
    "autores": "저자",
    "tags": "태그",
    "grifar": "강조",
    "anotar": "메모",
    "enviar": "보내기",
    "restaurar_padroes": "기본값 복원",
    "voltar_para_1": "1×로 돌아가기",
    "marcar_agora": "지금 표시",
    "escolher_pasta": "폴더 선택",
    "juntar_em_um_audiolivro": "하나의 오디오북으로 합치기",
    "sobre": "정보",
    "licencas_de_codigo_aberto": "오픈 소스 라이선스",
    "configuracoes": "설정",
    "temas_e_idioma": "테마 및 언어"
  },
  "aviso": {
    "idioma_trocado": "언어가 변경되었습니다."
  },
  "vn": {
    "quem_le": "읽어 주는 음성",
    "natural": "자연스러운 음성",
    "do_sistema": "시스템 음성",
    "nota_sistema": "기기에 설치된 음성을 사용합니다. 더 사람 같은 낭독을 원하면 자연스러운 음성을 선택하세요.",
    "nota_sistema_com_natural": "자연스러운 음성은 그대로 다운로드되어 있습니다. 언제든 다시 전환할 수 있어요.",
    "voz_natural": "자연스러운 음성",
    "gerada_no_aparelho": "훨씬 사람다운 목소리를 기기 안에서 바로 만들어 냅니다.",
    "progresso_download": "다운로드 진행률",
    "x_de_y": "{x}/{y}",
    "aviso_arquivo": "자연스러운 음성을 사용하려면 Veredas를 컴퓨터의 파일이 아니라 앱 주소로 열어야 합니다. 그전까지는 시스템 음성으로 읽습니다.",
    "aviso_navegador": "이 브라우저에는 자연스러운 음성에 필요한 기능이 없습니다. 시스템 음성으로 계속 읽습니다.",
    "verificando": "자연스러운 음성 확인 중…",
    "fato_download": "{tamanho} 한 번만 다운로드하면 이후에는 오프라인으로 작동합니다.",
    "fato_wifi": "Wi-Fi 사용을 권장합니다. 일시정지했다가 나중에 이어서 받을 수 있어요.",
    "fato_privacidade": "책의 텍스트는 기기 밖으로 나가지 않습니다.",
    "fato_idiomas": "한국어, 영어, 일본어 등 31개 언어를 지원합니다. 그 밖의 언어는 시스템 음성으로 읽습니다.",
    "baixar_voz_natural": "자연스러운 음성 다운로드({tamanho})",
    "licenca_curta": "Supertone의 Supertonic 3 모델, OpenRAIL-M 라이선스. 자세한 내용은 정보 > 오픈 소스 라이선스에서 확인하세요.",
    "pode_continuar_usando": "다운로드하는 동안에도 계속 읽을 수 있습니다. 연결이 끊겨도 멈춘 곳부터 이어서 받습니다.",
    "pausar_download": "다운로드 일시정지",
    "erro_espaco": "기기 저장 공간이 부족해 다운로드를 마칠 수 없습니다. 공간을 확보한 뒤 다시 시도하세요.",
    "erro_offline": "지금은 인터넷에 연결되어 있지 않습니다. 이미 받은 부분은 저장되어 있어요.",
    "erro_rede": "다운로드 중에 연결이 끊겼습니다. 이미 받은 부분은 저장되어 있어요.",
    "download_pausado": "다운로드를 일시정지했습니다. 이미 받은 부분은 저장되어 있어요.",
    "continuar_download": "이어서 받기",
    "descartar": "삭제",
    "voz_feminina": "여성",
    "voz_feminina_desc": "부드럽고 차분한 목소리",
    "voz_masculina": "남성",
    "voz_masculina_desc": "따뜻하고 편안한 목소리",
    "parar_amostra": "샘플 중지",
    "ouvir_amostra_de": "샘플 듣기: {voz}",
    "escolha_a_voz": "음성 선택",
    "qualidade": "품질",
    "q_auto": "자동",
    "q_rapida": "빠르게",
    "q_maxima": "최고",
    "q_auto_desc": "기기 성능에 맞춰 자동으로 조절해 끊김 없이 읽습니다.",
    "q_rapida_desc": "음성을 더 빠르게 생성합니다. 사양이 낮은 기기에 적합합니다.",
    "q_maxima_desc": "가장 정교한 소리입니다. 사양이 낮은 기기에서는 문장 사이에 끊김이 생길 수 있습니다.",
    "ocupa": "이 기기에서 {tamanho} 사용 중",
    "remover": "삭제",
    "baixar_pelos_dados": "모바일 데이터로 다운로드할까요?",
    "baixar_pelos_dados_msg": "기기가 Wi-Fi에 연결되어 있지 않은 것 같습니다. 다운로드 크기는 {tamanho}이며 데이터 요금제 사용량이 소모될 수 있습니다.",
    "baixar_agora": "그래도 다운로드",
    "pronta": "자연스러운 음성이 준비되었습니다.",
    "download_interrompido": "다운로드가 멈췄습니다. 원할 때 이어서 받기를 탭하세요.",
    "remover_titulo": "자연스러운 음성을 삭제할까요?",
    "descartar_titulo": "다운로드를 취소하고 삭제할까요?",
    "remover_msg": "{tamanho}의 공간이 확보됩니다. 시스템 음성으로 다시 읽으며, 언제든 다시 다운로드할 수 있습니다.",
    "descartar_msg": "이미 받은 부분이 삭제됩니다.",
    "removida": "이 기기에서 자연스러운 음성을 삭제했습니다.",
    "amostra_falhou": "이 기기에서 샘플을 재생할 수 없습니다.",
    "amostra": "안녕하세요! 자연스러운 음성으로 들으면 책이 이렇게 들려요.",
    "gerando_voz": "음성 준비 중…",
    "automatico_idioma": "자동({idioma})",
    "automatico": "자동",
    "so_voz_do_sistema": "시스템 음성",
    "aviso_idioma": "텍스트 언어: {idioma}. 자연스러운 음성은 아직 이 언어를 지원하지 않아 시스템 음성으로 읽습니다.",
    "aviso_idioma_desconhecido": "이 텍스트의 언어를 인식하지 못했습니다. 자연스러운 음성을 사용하려면 아래에서 언어를 선택하세요.",
    "aviso_falha": "지금은 이 기기에서 자연스러운 음성을 실행할 수 없습니다. 시스템 음성으로 계속 읽습니다.",
    "nao_carregou_usando_sistema": "이 기기에서 자연스러운 음성을 불러오지 못했습니다. 시스템 음성으로 읽는 중입니다.",
    "parou_usando_sistema": "자연스러운 음성이 멈췄습니다. 시스템 음성으로 계속합니다.",
    "aparelho_lento": "이 기기에서는 음성 생성이 느립니다. 끊김 없이 들으려면 품질을 빠르게로 선택하세요.",
    "idioma_do_texto": "텍스트 언어",
    "idioma_do_texto_dica": "텍스트를 바탕으로 인식했습니다. 발음이 어색하면 바꿔 주세요.",
    "leitura_em_voz_alta": "소리 내어 읽기",
    "lento_usando_sistema": "이 기기에서는 자연스러운 음성이 너무 느립니다. 시스템 음성으로 계속 읽습니다.",
    "aviso_lento": "이 기기는 읽는 속도에 맞춰 자연스러운 음성을 만들지 못해 지금은 시스템 음성으로 읽습니다."
  }
});