/* ============================================================
   NEDERLANDS — volledige vertaling
   ------------------------------------------------------------
   De sleutels zijn identiek aan pt-BR.js en en.js.
   ============================================================ */
Idiomas.registrar('nl', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "Bladwijzer verwijderd.",
    "excluir_marcador": "Bladwijzer verwijderen",
    "o_marcador_sera_removido_permanentemen": "De bladwijzer wordt definitief verwijderd.",
    "excluir_marcador_2": "Bladwijzer verwijderen?",
    "pagina_salva": "Pagina opgeslagen",
    "anotacoes": "Notities",
    "citacoes": "Citaten",
    "item_excluido": "Item verwijderd.",
    "este_registro_sera_removido_permanente": "Deze vermelding wordt definitief uit de bibliotheek verwijderd.",
    "configuracoes_padrao_restauradas": "Standaardinstellingen hersteld.",
    "leitura_da_esquerda_para_a_direita": "Lezen van links naar rechts.",
    "leitura_da_direita_para_a_esquerda_man": "Lezen van rechts naar links (manga).",
    "a_pagina_inteira_passa_a_caber_na_tela": "De hele pagina past nu op het scherm.",
    "a_pagina_passa_a_ocupar_toda_a_largura": "De pagina vult nu de volledige schermbreedte.",
    "virada_sem_animacao_ativada": "Pagina omslaan zonder animatie is ingeschakeld.",
    "virada_deslizante_ativada": "Pagina omslaan met schuiven is ingeschakeld.",
    "virada_em_folha_real_ativada": "Pagina omslaan als echt papier is ingeschakeld.",
    "padrao_automatico_cada_formato_abre_no": "Automatisch: elk formaat wordt geopend in de richting die erbij past.",
    "mudando_durante_a_leitura_o_ajuste_fic": "Als je dit tijdens het lezen wijzigt, geldt de wijziging alleen voor dit boek.",
    "automatico_usa_rolagem_horizontal_para": "Automatisch gebruikt horizontaal bladeren voor EPUB, MOBI, TXT, MD en strips, en verticaal scrollen voor PDF en DOCX.",
    "este_livro": "dit boek",
    "armazenamento_local_indisponivel_neste": "Lokale opslag is niet beschikbaar in deze browser.",
    "o_aplicativo_pode_procurar_os_livros_q": "De app kan zoeken naar boeken die al op je apparaat staan.",
    "vamos_montar_sua_estante": "Je boekenkast vullen?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "Zonder jouw toestemming kan de app niet worden gebruikt.",
    "precisamos_do_seu_aceite": "We hebben je toestemming nodig",
    "antes_de_comecar_leia_e_aceite_os_docu": "Lees en accepteer de onderstaande documenten voordat je begint.",
    "selecionar_todos": "Alles selecteren",
    "limpar_selecao": "Selectie wissen",
    "todos_parecem_ja_estar_na_sua_estante": "Ze lijken allemaal al in je boekenkast te staan.",
    "lendo_a_pasta_escolhida": "De gekozen map wordt gelezen…",
    "procurando_livros": "Boeken zoeken",
    "nao_foi_possivel_concluir_a_busca_no_d": "De zoekopdracht op dit apparaat kon niet worden voltooid.",
    "tente_outra_pasta_do_aparelho": "Probeer een andere map op je apparaat.",
    "nenhum_livro_encontrado": "Geen boeken gevonden",
    "use_o_botao_para_escolher_os_arquivos": "Gebruik de knop + om bestanden handmatig te kiezen. Op Android-telefoons kun je met Chrome meestal een hele map kiezen.",
    "seu_navegador_nao_permite_ler_pastas": "Je browser kan geen mappen lezen",
    "busca_automatica_indisponivel": "Automatisch zoeken niet beschikbaar",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR en M4B",
    "termos_de_uso": "Gebruiksvoorwaarden",
    "politica_de_privacidade": "Privacybeleid",
    "um_minuto_agora_evita_perder_o_progres": "Een minuut nu voorkomt dat je later je voortgang en markeringen kwijtraakt.",
    "ver_estante": "Boekenkast bekijken",
    "modo_juntar": "Samenvoegmodus",
    "modo_substituir": "Vervangmodus",
    "restauracao_concluida": "Herstel voltooid",
    "tente_de_novo_com_o_arquivo_original": "Probeer het opnieuw met het oorspronkelijke bestand.",
    "a_restauracao_nao_pode_ser_concluida": "Herstel kon niet worden voltooid",
    "devolvendo_o_seu_progresso_e_as_suas_m": "Je voortgang en markeringen worden teruggezet...",
    "restaurar_este_backup": "Deze back-up herstellen?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Kies de .zip die Veredas heeft opgeslagen of de .txt die je via delen hebt ontvangen.",
    "nao_foi_possivel_ler_este_arquivo": "Dit bestand kon niet worden gelezen",
    "lendo_o_backup": "Back-up lezen",
    "backup_do_veredas_reader": "Veredas Reader-back-up",
    "arquivo_de_transporte_txt_contendo_os": "kopie van de back-up in .txt-formaat, met dezelfde inhoud als de ZIP",
    "nao_foi_possivel_montar_o_arquivo_de_b": "Het back-upbestand kon niet worden gemaakt.",
    "escolher_o_app": "App kiezen",
    "vale_conferir_o_que_vai_no_arquivo": "Controleer wat er in het bestand staat",
    "enviar_para_outro_app": "Naar een andere app sturen",
    "salvar_o_arquivo": "Bestand opslaan",
    "o_navegador_aqui_nao_oferece_o_compart": "Deze browser biedt geen direct delen. Je kunt het bestand opslaan en later via elke gewenste app versturen.",
    "este_aparelho_nao_abre_a_lista_de_apli": "Dit apparaat opent de lijst met apps niet",
    "importe_pelo_menos_um_livro_antes_de_f": "Importeer eerst minstens één boek voordat je een back-up maakt.",
    "estante_vazia": "Boekenkast is leeg",
    "nao_deu_para_copiar": "Kopiëren mislukt",
    "copiar_detalhes": "Details kopiëren",
    "o_backup_foi_salvo_assim_mesmo": "De back-up is toch opgeslagen",
    "o_aparelho_recusou_abrir_a_lista": "Kan de deellijst niet openen",
    "sem_detalhes_do_navegador": "geen details van de browser",
    "o_sistema_nao_aceitou_receber_o_arquiv": "Het systeem van het apparaat kon het bestand niet ontvangen.",
    "o_navegador_considerou_a_situacao_inse": "De browser heeft het delen geblokkeerd vanwege een eigen beveiligingsregel. Sla het bestand op en verstuur het via de app die je wilt.",
    "o_compartilhamento_so_funciona_em_ende": "Delen werkt alleen met beveiligde adressen. Deze app wordt geopend vanaf een gewoon http://-adres; in dat geval blokkeert de browser het verzenden naar andere apps.",
    "este_navegador_nao_conseguiu_iniciar_o": "Deze browser kon het delen niet openen. Sla het bestand op en verstuur het via de app die je wilt.",
    "o_navegador_recebeu_um_arquivo_em_form": "De browser heeft de lijst met apps om mee te delen niet geopend. Tik nog een keer op de knop, of sla het bestand op en verstuur het via de app die je wilt.",
    "nao_foi_possivel_gerar_o_backup": "De back-up kon niet worden gemaakt.",
    "reunindo_a_sua_estante": "Je boekenkast verzamelen...",
    "preparando_o_backup": "Back-up voorbereiden",
    "pronto_nada_mais_esta_esperando": "Klaar — er staat niets meer te wachten.",
    "o_progresso_e_as_marcacoes_desses_livr": "De voortgang en markeringen van deze boeken worden gewist. Als je de bestanden later importeert, komen ze zonder markeringen terug.",
    "descartar_o_que_esta_esperando": "Wachtende gegevens verwijderen?",
    "lembretes_de_backup_religados": "Back-upherinneringen weer ingeschakeld.",
    "sem_titulo": "Naamloos",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "Herinneringen uitgeschakeld.",
    "manter_ligado": "Ingeschakeld houden",
    "desligar_assim_mesmo": "Toch uitschakelen",
    "o_botao_de_salvar_continua_onde_sempre": "De knop Opslaan staat nog steeds waar die altijd stond, bij Back-up en herstel.",
    "o_lembrete_e_o_unico_aviso_que_existe": "De herinnering is de enige waarschuwing. Zonder herinnering moet je er zelf aan denken om een back-up te maken.\n\n",
    "limpar_os_dados_do_navegador_desinstal": "Als de browsergegevens worden gewist, de app wordt verwijderd, je van telefoon wisselt of het apparaat defect raakt, kunnen je voortgang, markeringen, citaten, notities en bladwijzers niet worden hersteld.\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "Je boekenkast bestaat alleen op dit apparaat. Er staat geen kopie op een server, dus we kunnen hem niet voor je herstellen.\n\n",
    "leia_antes_de_confirmar": "Lees dit voordat je bevestigt",
    "desligar_os_lembretes_de_backup": "Back-upherinneringen uitschakelen?",
    "progresso_de_leitura_restaurado_neste": "Leesvoortgang voor dit boek hersteld.",
    "pronto": "Klaar.",
    "aplicando_as_suas_preferencias": "Je voorkeuren worden toegepast...",
    "atualize_o_veredas_reader_e_tente_de_n": "Werk Veredas Reader bij en probeer het opnieuw.",
    "este_backup_foi_feito_numa_versao_mais": "Deze back-up is gemaakt met een nieuwere versie van de app.",
    "este_arquivo_nao_e_um_backup_de_biblio": "Dit bestand is geen back-up van de Veredas-bibliotheek.",
    "o_conteudo_interno_nao_pode_ser_lido": "De inhoud kon niet worden gelezen.",
    "o_backup_esta_corrompido": "De back-up is beschadigd.",
    "falta_o_arquivo_biblioteca_json_la_den": "Het bestand biblioteca.json ontbreekt.",
    "este_arquivo_nao_parece_ser_um_backup": "Dit bestand lijkt geen Veredas-back-up te zijn.",
    "compactando": "Comprimeren...",
    "para_restaurar_menu_lateral_backup_e_r": "Herstellen: zijmenu > Back-up en herstel > Back-up herstellen.",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas herstelt automatisch de markeringen en de plek waar je was gebleven.",
    "importe_os_livros_normalmente_no_aplic": "importeer je de boeken gewoon in de app: zodra elk bestand wordt herkend,",
    "ele_nao_contem_os_arquivos_dos_livros": "Het bevat NIET de boekbestanden. Voor volledig herstel,",
    "as_notas_os_marcadores_e_a_organizacao": "je notities, bladwijzers en de indeling van je boekenkast.",
    "este_arquivo_guarda_o_seu_progresso_de": "Dit bestand bevat je leesvoortgang, markeringen en citaten,",
    "verificando_se_sao_partes_do_mesmo_aud": "Controleren of dit delen van hetzelfde audioboek zijn...",
    "analisando_os_arquivos": "Bestanden analyseren",
    "nao_foi_possivel_salvar_o_audiolivro": "Het audioboek kon niet worden opgeslagen.",
    "audiolivros_grandes_podem_levar_alguns": "Grote audioboeken kunnen even duren...",
    "salvando_na_sua_estante": "Opslaan in je boekenkast",
    "falha_ao_processar_os_arquivos": "De bestanden konden niet worden verwerkt.",
    "falha_ao_processar_o_arquivo": "Het bestand kon niet worden verwerkt.",
    "nao_foi_possivel_salvar_o_quadrinho": "De strip kon niet worden opgeslagen.",
    "quase_la": "Bijna klaar...",
    "falha_ao_processar_o_quadrinho": "De strip kon niet worden verwerkt.",
    "autor_desconhecido": "Onbekende auteur",
    "lendo_o_quadrinho": "Strip lezen...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "Het boek kon niet in de bibliotheek worden opgeslagen.",
    "nao_foi_possivel_ler_o_pdf": "De PDF kon niet worden gelezen.",
    "lendo_o_pdf": "PDF lezen...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "Als het een oude .doc is, open je die in Word en sla je hem op als .docx voordat je hem importeert.",
    "este_arquivo_nao_e_um_docx_valido": "Dit bestand is geen geldige .docx.",
    "livros_com_protecao_da_amazon_nao_pode": "Boeken met Amazon-bescherming kunnen hier niet worden geopend. Gebruik een DRM-vrije kopie of converteer het boek naar EPUB.",
    "este_arquivo_esta_protegido_por_drm": "Dit bestand is beveiligd met DRM.",
    "confira_se_a_extensao_corresponde_ao_c": "Controleer of de extensie overeenkomt met de inhoud of converteer het boek naar EPUB.",
    "este_arquivo_nao_e_um_mobi_valido": "Dit bestand is geen geldige MOBI.",
    "nao_foi_possivel_ler_o_arquivo": "Het bestand kon niet worden gelezen.",
    "formato_nao_suportado": "Indeling wordt niet ondersteund.",
    "falha_ao_salvar_o_livro_na_biblioteca": "Het boek kon niet in de bibliotheek worden opgeslagen.",
    "livro_importado_e_salvo_no_dispositivo": "Boek geïmporteerd en op dit apparaat opgeslagen.",
    "audiolivro_importado_e_salvo_no_dispos": "Audioboek geïmporteerd en op dit apparaat opgeslagen.",
    "quadrinho_importado_e_salvo_no_disposi": "Strip geïmporteerd en op dit apparaat opgeslagen.",
    "salvando_na_sua_estante_2": "Opslaan in je boekenkast...",
    "importando_livro": "Boek importeren",
    "importar_mesmo_assim": "Toch importeren",
    "parece_que_este_livro_ja_esta_na_estan": "Dit boek staat waarschijnlijk al in je boekenkast",
    "este_livro_ja_esta_na_estante": "Dit boek staat al in je boekenkast",
    "video_importado_e_salvo_no_dispositivo": "Video geïmporteerd en op dit apparaat opgeslagen.",
    "importacao_cancelada": "Importeren geannuleerd.",
    "preparando_o_arquivo": "Bestand voorbereiden",
    "importando_audiolivro": "Audioboek importeren",
    "importacao_concluida": "Importeren voltooid",
    "importacao_interrompida": "Importeren gestopt",
    "a_importacao_foi_interrompida_o_que_ja": "Het importeren is gestopt; wat al was toegevoegd, blijft in je boekenkast.",
    "finalizando": "Afronden…",
    "nao_foi_possivel_ler_o_arquivo_2": "het bestand kon niet worden gelezen",
    "importando_livros": "Boeken importeren",
    "livros_quadrinhos_documentos_audiolivr": "Boeken, strips, documenten, audioboeken en video’s",
    "series": "Series",
    "colecoes": "Collecties",
    "organizacao_salva": "Organisatie opgeslagen.",
    "informe_um_nome_para_o_livro_antes_de": "Geef het boek een naam voordat je het opslaat.",
    "nome_do_livro_obrigatorio": "Het boek heeft een naam nodig",
    "importe_um_livro_primeiro": "Importeer eerst een boek.",
    "citacao": "citaat",
    "anotacao": "notitie",
    "citacao_2": "Citaat",
    "anotacao_2": "Notitie",
    "uma_citacao": "een citaat",
    "uma_anotacao": "een notitie",
    "o_marcador_sera_removido_da_biblioteca": "De bladwijzer wordt uit de bibliotheek verwijderd, maar het boekbestand blijft intact.",
    "marcador_de_audio": "Audiobladwijzer",
    "marcador_de_video": "Videobladwijzer",
    "nao_foi_possivel_excluir_o_livro": "Het boek kon niet worden verwijderd.",
    "livro_excluido_da_biblioteca": "Boek uit de bibliotheek verwijderd.",
    "excluir_livro": "Boek verwijderen",
    "isso_remove_apenas_a_copia_armazenada": "Dit verwijdert alleen de kopie die de bibliotheek bewaart, samen met voortgang, bladwijzers en notities. Het originele bestand in je eigen map wordt niet verwijderd.",
    "excluir_livro_2": "Boek verwijderen?",
    "ordem_personalizada_salva": "Aangepaste volgorde opgeslagen.",
    "ordem_manual_da_sua_estante": "Je boekenkast, in de volgorde die je hebt ingesteld.",
    "agrupamento_alterado_para_minha_ordem": "Groepering gewijzigd naar Mijn volgorde.",
    "nova_ordem_salva": "Nieuwe volgorde opgeslagen.",
    "nao_foi_possivel_salvar_a_nova_ordem": "De nieuwe volgorde kon niet worden opgeslagen.",
    "baixar_automaticamente": "Automatisch downloaden",
    "escolha_livremente_onde_o_arquivo_sera": "Kies zelf waar het bestand wordt opgeslagen.",
    "salvar_epub": "EPUB opslaan",
    "livro_epub": "EPUB-boek",
    "erro_desconhecido": "onbekende fout",
    "a_permissao_para_salvar_o_arquivo_foi": "De toestemming om het bestand op te slaan is geannuleerd. Er is niets in de bibliotheek gewijzigd.",
    "conversao_cancelada_o_pdf_original_per": "Conversie geannuleerd. De oorspronkelijke PDF blijft in de bibliotheek.",
    "preparando_salvamento": "Opslaan voorbereiden…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "De PDF-kopie is niet beschikbaar in de bibliotheek.",
    "reconstruindo_o_livro_localmente": "Het boek wordt op je apparaat opnieuw opgebouwd.",
    "convertendo_pdf": "PDF converteren",
    "nao_foi_possivel_compartilhar_o_livro": "Het boek kon niet worden gedeeld.",
    "o_arquivo_foi_preparado_para_voce_comp": "Het bestand is klaar om in een andere app te delen.",
    "livro_compartilhado": "Boek gedeeld.",
    "a_copia_deste_livro_nao_esta_disponive": "De kopie van dit boek is niet beschikbaar in de bibliotheek.",
    "para_manter_a_politica_de_compartilham": "Om het deelbeleid van de bibliotheek te handhaven, kunnen EPUB- en MOBI-bestanden niet via deze app worden gedeeld.",
    "quadrinhos_ficam_guardados_somente_no": "Strips worden alleen op je apparaat bewaard en kunnen niet via deze app worden gedeeld.",
    "audiolivros_e_videos_ficam_guardados_s": "Audioboeken en video's worden alleen op je apparaat bewaard en kunnen niet via deze app worden gedeeld.",
    "formato_protegido": "Beveiligd formaat",
    "compartilhamento_indisponivel": "Delen niet beschikbaar",
    "concluido": "Voltooid",
    "ainda_nao_comecado": "Nog niet gestart",
    "continue_lendo": "Verder lezen",
    "continue_ouvindo": "Verder luisteren",
    "continue_assistindo": "Verder kijken",
    "comece_por_aqui": "Hier beginnen",
    "comece_a_ouvir": "Begin met luisteren",
    "comece_a_assistir": "Begin met kijken",
    "no_total": "in totaal",
    "para_ler": "te lezen",
    "sua_estante": "Je boekenkast",
    "livros_organizados_pela_opcao_selecion": "Boeken gerangschikt volgens de optie die je hebt gekozen.",
    "uma_prateleira_para_cada_tipo_de_arqui": "Een plank voor elk bestandstype.",
    "autores_agrupados_em_ordem_alfabetica": "Auteurs alfabetisch gegroepeerd.",
    "toque_para_continuar_de_onde_parou": "Tik om verder te gaan waar je was gebleven.",
    "para_ler_2": "Te lezen",
    "lendo_agora": "Nu aan het lezen",
    "audio_e_video": "Audio en video",
    "trechos_salvos_separadamente_dos_marca": "Passages apart van bladwijzers opgeslagen.",
    "comentarios_vinculados_a_trechos_selec": "Opmerkingen gekoppeld aan passages die je hebt geselecteerd.",
    "paginas_salvas_para_voltar_rapidamente": "Pagina’s opgeslagen om snel terug te keren.",
    "do_maior_para_o_menor_progresso_de_lei": "Van meeste naar minste leesvoortgang.",
    "livros_adicionados_ou_lidos_mais_recen": "Boeken die het meest recent zijn toegevoegd of gelezen.",
    "ordem_alfabetica_pelo_titulo": "Alfabetisch op titel.",
    "separa_em_prateleiras_de_epub_pdf_docx": "Verdeelt EPUB, PDF, DOCX, audioboeken en video’s over aparte planken…",
    "tipo_de_arquivo": "Bestandstype",
    "organiza_e_separa_os_livros_por_autor": "Rangschikt en splitst boeken per auteur.",
    "agrupar_por_autor": "Groeperen op auteur",
    "pressione_o_livro_e_mova_o": "Houd een boek ingedrukt en verplaats het.",
    "minha_ordem": "Mijn volgorde",
    "epub_pronto": "EPUB klaar",
    "conversao_concluida": "Conversie voltooid",
    "necessario_para_salvar_o_epub_ao_lado": "Nodig om de EPUB naast het origineel op te slaan",
    "escolha_a_pasta_do_pdf": "Kies de PDF-map",
    "processando": "Bezig…",
    "processamento_local_no_navegador": "Verwerkt op je apparaat, in de browser",
    "convertendo_livro": "Boek converteren",
    "livro_em_pdf": "PDF-boek",
    "recalculando_paginas": "Pagina’s opnieuw berekenen...",
    "ajustando_leitura": "Lay-out aanpassen",
    "abrir_comentario": "Opmerking openen",
    "anotacao_salva": "Notitie opgeslagen.",
    "anotacao_atualizada": "Notitie bijgewerkt.",
    "escreva_uma_nota_antes_de_salvar": "Schrijf eerst een notitie voordat je opslaat.",
    "nao_foi_possivel_compartilhar": "Delen mislukt.",
    "compartilhamento_indisponivel_2": "Delen niet beschikbaar.",
    "trecho_copiado": "Passage gekopieerd.",
    "trecho_compartilhado": "Passage gedeeld.",
    "citacao_salva": "Citaat opgeslagen.",
    "trecho_grifado": "Passage gemarkeerd.",
    "grifo_removido": "Markering verwijderd.",
    "comentario_apagado": "Opmerking verwijderd.",
    "remover_grifo": "Markering verwijderen",
    "apagar_comentario": "Opmerking verwijderen",
    "remover_grifo_2": "Markering verwijderen?",
    "apagar_comentario_2": "Opmerking verwijderen?",
    "remover_este_grifo": "Deze markering verwijderen?",
    "apagar_este_comentario": "Deze opmerking verwijderen?",
    "sem_comentario": "Geen opmerking",
    "comentario": "Opmerking",
    "marcador_removido_desta_pagina": "Bladwijzer van deze pagina verwijderd.",
    "pagina_adicionada_aos_marcadores": "Pagina aan je bladwijzers toegevoegd.",
    "este_e_o_inicio_do_livro": "Dit is het begin van het boek.",
    "esta_e_a_primeira_pagina": "Dit is de eerste pagina.",
    "voce_chegou_ao_fim_do_livro": "Je hebt het einde van het boek bereikt.",
    "voce_chegou_ao_fim_do_quadrinho": "Je hebt het einde van de strip bereikt.",
    "agora_em_revista_aberta_duas_paginas_l": "Nu als dubbele pagina: twee pagina’s naast elkaar, met de omslag alleen.",
    "leitura_horizontal_ativada_neste_livro": "Horizontaal lezen is ingeschakeld voor dit boek.",
    "rolagem_vertical_ativada_neste_livro": "Verticaal scrollen is ingeschakeld voor dit boek.",
    "leitura_pagina_a_pagina_ativada_neste": "Pagina-voor-pagina lezen is ingeschakeld voor deze strip.",
    "rolagem_continua_ativada_neste_quadrin": "Continu scrollen is ingeschakeld voor deze strip.",
    "mudar_para_rolagem_vertical": "Overschakelen naar verticaal scrollen",
    "mudar_para_leitura_horizontal": "Overschakelen naar horizontaal lezen",
    "rolagem_continua_estilo_webtoon": "Continu scrollen (webtoonstijl)",
    "voltar_para_pagina_a_pagina": "Terug naar pagina-voor-pagina",
    "separando_os_capitulos": "Hoofdstukken scheiden...",
    "lendo_o_livro": "Boek lezen",
    "lendo_o_markdown": "Markdown lezen",
    "lendo_o_documento": "Document lezen",
    "pagina_indisponivel": "Pagina niet beschikbaar.",
    "isto_acontece_so_desta_vez": "Dit gebeurt maar één keer.",
    "preparando_o_quadrinho": "Strip voorbereiden",
    "abrindo_o_quadrinho": "Strip openen...",
    "montando_as_paginas": "Pagina’s opbouwen...",
    "nao_foi_possivel_abrir_este_livro": "Dit boek kon niet worden geopend.",
    "abertura_cancelada": "Openen geannuleerd.",
    "o_livro_demorou_demais_para_abrir_e_fo": "Het boek deed er te lang over om te openen en is gestopt.",
    "importe_o_arquivo_novamente_para_conti": "Importeer het bestand opnieuw om verder te lezen.",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "Het bestand van dit boek staat niet meer op je apparaat.",
    "preparando_sua_leitura": "Je leessessie voorbereiden...",
    "abrindo_livro": "Boek openen",
    "leitura_concluida": "Lezen voltooid.",
    "a_voz_foi_interrompida_pelo_navegador": "De browser heeft de stem gestopt.",
    "nao_foi_possivel_preparar_este_trecho": "Deze passage kon niet voor audio worden voorbereid.",
    "a_leitura_em_voz_alta_nao_e_suportada": "Voorlezen wordt niet ondersteund in deze browser.",
    "pausar_leitura": "Lezen pauzeren",
    "em_pausa": "Gepauzeerd",
    "leitura_em_voz_alta_nao_disponivel_nes": "Voorlezen is niet beschikbaar in deze browser",
    "nome_do_marcador": "Naam van bladwijzer",
    "o_marcador_sera_removido_deste_audioli": "De bladwijzer wordt uit dit audioboek verwijderd.",
    "nao_foi_possivel_salvar_o_marcador": "De bladwijzer kon niet worden opgeslagen.",
    "ja_existe_um_marcador_neste_ponto": "Er staat al een bladwijzer op deze plek.",
    "timer_de_sono_encerrado": "Slaaptimer afgelopen.",
    "fim_do_cap": "Einde hfdst.",
    "timer_desativado": "Timer uitgeschakeld.",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "De audio wordt aan het einde van het hoofdstuk gepauzeerd.",
    "este_audiolivro_nao_tem_capitulos": "Dit audioboek heeft geen hoofdstukken.",
    "ao_fim_do_capitulo": "Aan het einde van het hoofdstuk",
    "desativar_timer": "Timer uitschakelen",
    "mais_10_minutos_no_timer": "Nog 10 minuten op de timer.",
    "somar_10_minutos": "10 minuten toevoegen",
    "pausa_ao_fim_do_capitulo": "Pauzeren aan het einde van het hoofdstuk",
    "no_livro_todo": "Voor het hele boek",
    "video": "Video",
    "audiolivro_concluido": "Audioboek voltooid.",
    "video_concluido": "Video voltooid.",
    "video_2": "video",
    "audio": "audio",
    "toque_em_reproduzir_para_comecar": "Tik op afspelen om te beginnen.",
    "falha_ao_carregar_o_audio": "De audio kon niet worden geladen.",
    "exclua_o_da_biblioteca_e_importe_o_arq": "Verwijder het uit de bibliotheek en importeer het bestand opnieuw.",
    "os_nomes_dos_arquivos_seguem_uma_seque": "De bestandsnamen volgen een reeks, dus ze lijken op hoofdstukken van één audioboek.",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "De bestanden hebben hetzelfde album in hun tags, dus ze lijken op hoofdstukken van één audioboek.",
    "libere_espaco_ou_exclua_livros_da_bibl": "Maak ruimte vrij of verwijder boeken uit de bibliotheek en probeer het opnieuw.",
    "o_armazenamento_do_aparelho_esta_cheio": "De opslagruimte van je apparaat is vol.",
    "preparando_a_capa": "Omslag voorbereiden...",
    "remova_esse_arquivo_da_selecao_e_tente": "Verwijder dat bestand uit de selectie en probeer het opnieuw.",
    "sequencia": "reeks",
    "o_arquivo_pode_estar_incompleto_tente": "Het bestand is mogelijk onvolledig. Probeer het opnieuw te downloaden.",
    "conferindo_se_o_audio_pode_ser_reprodu": "Controleren of de audio kan worden afgespeeld...",
    "conferindo_se_o_video_pode_ser_reprodu": "Controleren of de video kan worden afgespeeld...",
    "lendo_titulo_capitulos_e_capa": "Titel, hoofdstukken en omslag lezen...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "Het bestand is mogelijk beschadigd of heeft een audioformaat dat de browser niet kan afspelen. Probeer het om te zetten naar MP3 of M4B (AAC).",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "Het bestand is mogelijk beschadigd of heeft een videoformaat dat de browser niet kan afspelen. Probeer het om te zetten naar MP4 met H.264-video en AAC-audio.",
    "converta_o_audiolivro_para_m4b_com_aud": "Converteer het audioboek naar M4B met AAC-audio (of naar MP3) en importeer het opnieuw.",
    "converta_o_video_para_mp4_com_audio_aa": "Converteer de video naar MP4 met AAC-audio en H.264-video en importeer het opnieuw.",
    "o_navegador_nao_reproduz_o_formato_de": "De browser kan het audioformaat van dit bestand niet afspelen.",
    "arquivos_com_protecao_nao_podem_ser_re": "Beveiligde bestanden kunnen hier niet worden afgespeeld. Gebruik een DRM-vrije kopie.",
    "nao_ha_espaco_suficiente_no_aparelho_p": "Er is niet genoeg ruimte op je apparaat voor dit audioboek.",
    "confira_se_a_extensao_corresponde_ao_c_2": "Controleer of de extensie overeenkomt met de inhoud of converteer de audio naar MP3 of M4B (AAC).",
    "imagem_invalida": "ongeldige afbeelding",
    "imagem_demorou_demais": "het laden van de afbeelding duurde te lang",
    "imagem_vazia": "lege afbeelding",
    "inicio": "Start",
    "mp4_moov_nao_encontrado": "De video lijkt onvolledig of beschadigd.",
    "pagina": "Pagina",
    "esta_pagina_nao_esta_disponivel": "Deze pagina is niet beschikbaar.",
    "esta_pagina_nao_pode_ser_descompactada": "Deze pagina kon niet worden uitgepakt.",
    "quadrinho_fechado": "Strip gesloten.",
    "ele_pode_estar_incompleto_dividido_em": "Het bestand is mogelijk onvolledig, opgesplitst in meerdere delen of gebruikt een RAR-variant die de app niet herkent. Converteren naar CBZ verhelpt dit meestal.",
    "remova_a_senha_do_arquivo_e_importe_de": "Verwijder het wachtwoord van het bestand en importeer het opnieuw.",
    "nao_foi_possivel_ler_este_arquivo_de_q": "Dit stripbestand kon niet worden gelezen.",
    "este_quadrinho_esta_protegido_por_senh": "Deze strip is met een wachtwoord beveiligd.",
    "lendo_o_indice_do_quadrinho": "Index van de strip lezen...",
    "o_arquivo_pode_ser_grande_demais_para": "Het bestand is mogelijk te groot voor het geheugen van dit apparaat. De strip opsplitsen in kleinere delen verhelpt dit meestal.",
    "nao_foi_possivel_abrir_este_quadrinho": "Deze strip kon niet worden geopend.",
    "lendo_o_arquivo": "Bestand lezen...",
    "preparando_o_leitor_de_cbr": "CBR-lezer voorbereiden...",
    "o_arquivo_pode_estar_incompleto_proteg": "Het bestand is mogelijk onvolledig, met een wachtwoord beveiligd of beschadigd.",
    "nao_foi_possivel_ler_este_quadrinho": "Deze strip kon niet worden gelezen.",
    "o_arquivo_precisa_conter_imagens_jpg_p": "Het bestand moet afbeeldingen bevatten (JPG, PNG, WEBP of GIF).",
    "nao_encontramos_paginas_dentro_deste_q": "We hebben geen pagina’s in deze strip gevonden.",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "Er is niet genoeg ruimte op je apparaat voor deze strip.",
    "cabecalho_de_item_invalido": "Een deel van het bestand is beschadigd.",
    "a_pasta_vendor_libarchive_precisa_esta": "Er ontbreekt een onderdeel van de app om deze strip te openen. Zet de strip om naar CBZ of installeer de app opnieuw.",
    "o_leitor_de_cbr_nao_foi_encontrado": "CBR-lezer niet gevonden.",
    "converta_o_quadrinho_para_cbz_zip_e_im": "Converteer de strip naar CBZ (ZIP) en importeer hem opnieuw.",
    "este_navegador_nao_consegue_abrir_arqu": "Deze browser kan geen CBR-bestanden openen.",
    "convertendo_o_markdown": "Markdown converteren",
    "lendo_o_texto": "Tekst lezen",
    "pdf_indisponivel": "PDF niet beschikbaar.",
    "epub_invalido_nenhum_capitulo_no_spine": "Dit EPUB-bestand is beschadigd: de hoofdstukken van het boek zijn niet gevonden.",
    "livro_sem_titulo": "Naamloos boek",
    "epub_invalido_arquivo_opf_nao_encontra": "Dit EPUB-bestand is onvolledig of beschadigd en kan niet worden geopend.",
    "epub_invalido_container_xml_nao_encont": "Dit EPUB-bestand is onvolledig of beschadigd en kan niet worden geopend.",
    "organizando_o_texto": "Tekst opmaken",
    "descompactando_o_livro": "Boek uitpakken",
    "nao_encontramos_conteudo_para_exibir_n": "Er is niets gevonden om in dit bestand weer te geven.",
    "livro_sem_texto_legivel": "Boek zonder leesbare tekst",
    "o_arquivo_pode_estar_corrompido_tente": "Het bestand is mogelijk beschadigd. Probeer het te converteren naar EPUB.",
    "nao_foi_possivel_extrair_o_texto_deste": "De tekst kon niet uit deze MOBI worden gehaald.",
    "nenhum_registro_de_conteudo_foi_encont": "De tekst van het boek is niet gevonden in dit bestand.",
    "arquivo_mobi_sem_texto": "MOBI-bestand zonder tekst.",
    "o_dicionario_de_compressao_esta_vazio": "Een deel van de inhoud van dit MOBI-bestand ontbreekt.",
    "arquivo_mobi_incompleto": "Onvolledig MOBI-bestand.",
    "as_tabelas_de_compressao_nao_foram_enc": "Een deel van de inhoud van dit MOBI-bestand ontbreekt.",
    "converta_o_arquivo_para_epub_em_um_pro": "Converteer het bestand met een programma zoals Calibre naar EPUB en importeer het opnieuw.",
    "compressao_mobi_nao_reconhecida": "Dit MOBI-bestand gebruikt een intern formaat dat de app niet herkent.",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "De kop van het boek kon niet worden gelezen.",
    "arquivo_mobi_corrompido": "Beschadigd MOBI-bestand.",
    "a_lista_interna_de_registros_esta_inco": "Het bestand is onvolledig. Probeer het opnieuw te downloaden of om te zetten.",
    "o_download_parece_ter_sido_interrompid": "De download lijkt te zijn onderbroken. Download het bestand opnieuw.",
    "tabela_de_compressao_mobi_corrompida": "Een deel van dit MOBI-bestand is beschadigd.",
    "tabela_de_compressao_mobi_incompleta": "Dit MOBI-bestand is onvolledig.",
    "tabela_de_compressao_mobi_invalida": "Een deel van dit MOBI-bestand is beschadigd.",
    "este_arquivo_docx_nao_tem_conteudo_de": "Dit .docx-bestand bevat geen tekst die kan worden weergegeven.",
    "documento_sem_texto": "Document zonder tekst",
    "o_arquivo_pode_estar_corrompido_proteg": "Het bestand is mogelijk beschadigd, met een wachtwoord beveiligd of een oude .doc. Sla het opnieuw op als .docx en importeer het nogmaals.",
    "nao_foi_possivel_ler_este_arquivo_docx": "Dit DOCX-bestand kon niet worden gelezen.",
    "convertendo_o_documento": "Document converteren",
    "conecte_se_a_internet_uma_vez_para_bai": "Maak één keer verbinding met internet om de component te downloaden en open daarna het boek opnieuw.",
    "o_conversor_de_docx_nao_carregou": "De DOCX-converter is niet geladen.",
    "video_mp4": "Video (MP4)",
    "audiolivro_m4b": "Audioboek (M4B)",
    "audiolivro_mp3": "Audioboek (MP3)",
    "quadrinho_cbt": "Strip (CBT)",
    "quadrinho_cb7": "Strip (CB7)",
    "quadrinho_cbr": "Strip (CBR)",
    "quadrinho_cbz": "Strip (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "Tekst (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "Opslaan geannuleerd.",
    "o_arquivo_esta_vindo_do_armazenamento": "Het bestand wordt vanuit cloudopslag naar je apparaat gedownload.",
    "baixando_o_arquivo": "Bestand downloaden",
    "cancelando": "Annuleren...",
    "use_grifar_citacao_anotar_ou_marcador": "Gebruik Markeren, Citaat, Notitie of Bladwijzer tijdens het lezen.",
    "nenhuma_marcacao_ainda": "Nog geen markeringen",
    "trecho_original": "Oorspronkelijke passage",
    "procurar_meus_livros": "Mijn boeken zoeken",
    "a_busca_fica_sempre_disponivel_no_menu": "Zoeken is altijd beschikbaar in het zijmenu, onder Systeem.",
    "da_para_fazer_depois": "Je kunt dit later doen",
    "nada_entra_na_estante_sem_a_sua_confir": "Er komt niets in je boekenkast zonder jouw toestemming: je ziet de lijst en selecteert wat je wilt importeren.",
    "voce_revisa_antes": "Je controleert eerst",
    "escolha_uma_pasta_downloads_e_um_bom_c": "Kies een map (Downloads is een goed begin) en de app zoekt daarin en in alle submappen.",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "Zoeken naar EPUB, MOBI, CBZ, CBR en M4B",
    "voltar_e_revisar": "Teruggaan en controleren",
    "ler_os_termos": "Voorwaarden lezen",
    "ler_a_politica": "Beleid lezen",
    "os_dois_documentos_ficam_sempre_dispon": "Beide documenten zijn altijd beschikbaar in het zijmenu, onder Over.",
    "leia_com_calma": "Neem de tijd",
    "a_politica_e_os_termos_explicam_como_o": "Het beleid en de voorwaarden leggen uit hoe de app je boeken bewaart en wat je ermee mag doen. Om de bibliotheek te gebruiken, moet je ermee akkoord gaan.",
    "nada_acontece_sem_o_aceite": "Om te beginnen moet je de voorwaarden accepteren",
    "aceitar_e_continuar": "Accepteren en doorgaan",
    "nao_aceito": "Ik ga niet akkoord",
    "termos_de_uso_2": "Gebruiksvoorwaarden",
    "politica_de_privacidade_2": "Privacybeleid",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "De app heeft alleen toegang tot de bestanden en mappen die je kiest, wanneer je daarvoor kiest.",
    "voce_no_controle": "Jij hebt de controle",
    "depois_de_importar_um_livro_voce_le_se": "Nadat een boek is geïmporteerd, kun je het zonder internet lezen.",
    "funciona_offline": "Werkt offline",
    "livros_marcacoes_e_progresso_sao_guard": "Boeken, markeringen en voortgang blijven op je apparaat. Er wordt niets naar onze servers gestuurd.",
    "tudo_fica_no_seu_aparelho": "Alles blijft op je apparaat",
    "escolha_o_que_deseja_adicionar_a_bibli": "Kies wat je aan de bibliotheek wilt toevoegen. Bestanden die identiek zijn aan bestanden die al in je boekenkast staan, worden automatisch overgeslagen.",
    "voce_pode_tentar_outra_pasta_ou_import": "Je kunt een andere map proberen of bestanden importeren met de knop +.",
    "a_leitura_acontece_so_no_seu_dispositi": "Het lezen gebeurt alleen op je apparaat.",
    "voce_escolhe_a_pasta": "Jij kiest de map",
    "tema_tipografia_margens_modo_de_virada": "Thema, lettertype, marges, pagina-omslaanstijl en audio-instellingen.",
    "restaurar_minhas_preferencias": "Mijn voorkeuren herstellen",
    "o_backup_manda_as_marcacoes_atuais_dos": "De back-up heeft voorrang. De huidige markeringen van elk boek in het bestand worden vervangen door die uit de back-up.",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "Er wordt niets gewist. Markeringen van beide kanten worden samengevoegd en de meest recente voortgang krijgt voorrang.",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "Wat te doen met wat al in je boekenkast staat",
    "grifos_citacoes_e_notas": "markeringen, citaten en notities",
    "preparando_o_arquivo_2": "Bestand voorbereiden...",
    "os_livros_em_si_nem_as_capas_por_isso": "Noch de boeken zelf, noch de omslagen — daarom is het bestand maar een paar KB. Wie het ontvangt, heeft de boekbestanden nodig om de markeringen weer op hun plek te krijgen; de omslagen komen bij het importeren automatisch terug.",
    "nao_vai_no_arquivo": "Niet in het bestand",
    "o_seu_progresso_de_leitura_os_grifos_a": "Je leesvoortgang, markeringen, citaten, notities, bladwijzers en de indeling van je boekenkast — status, favorieten, collecties, series en tags.",
    "vai_no_arquivo": "In het bestand",
    "descartar_o_que_esta_esperando_2": "Wachtende gegevens verwijderen",
    "esperando_o_arquivo": "Wachten op het bestand",
    "avisar_quando_fizer_tempo_sem_backup": "Mij eraan herinneren wanneer het een tijdje geleden is dat ik een back-up heb gemaakt",
    "livros_que_ainda_nao_estiverem_na_esta": "Boeken die nog niet in je boekenkast staan, worden in de wacht gezet: zodra je hun bestand importeert, komen de markeringen automatisch terug.",
    "restaurar_backup": "Back-up herstellen",
    "salvar_backup": "Back-up opslaan",
    "ainda_nao_ha_itens": "Nog niets hier",
    "arraste_um_livro_para_outra_posicao_na": "Sleep een boek naar een andere plek op de plank om je eigen volgorde op te slaan. Die handmatige volgorde krijgt daarna voorrang op groeperen op auteur.",
    "separe_por_virgulas": "Scheid met komma’s",
    "ex_estudos_ficcao": "bijv. Studies, Fictie...",
    "pasta_estante": "Map / plank",
    "ex_trilogia": "bijv. Trilogie...",
    "serie": "Serie",
    "aparece_em_favoritos": "Verschijnt in Favorieten.",
    "nome_do_livro": "Boeknaam",
    "nenhum_registro_ainda": "Nog niets geregistreerd",
    "no_leitor_toque_no_icone_de_marcador_p": "Tik in de lezer op het bladwijzerpictogram om de pagina op te slaan.",
    "nenhum_marcador_ainda": "Nog geen bladwijzers",
    "a_gravacao_e_independente_da_localizac": "Opslaan staat los van waar de PDF zich bevindt en verandert het oorspronkelijke bestand niet.",
    "o_pdf_original_nao_precisa_estar_nessa": "De oorspronkelijke PDF hoeft niet in deze map te staan",
    "excluir_da_biblioteca": "Uit bibliotheek verwijderen",
    "adicionar_livro": "Boek toevoegen",
    "adicione_livros_e_acompanhe_o_que_esta": "Voeg boeken toe en houd bij wat wacht, wat bezig is en hoever je bent.",
    "tudo_pronto_para_a_proxima_leitura": "Alles klaar voor je volgende leesmoment.",
    "sua_biblioteca": "Je bibliotheek",
    "arraste_um_livro_para_reposiciona_lo_a": "Sleep een boek om het te verplaatsen: de boekenkast schakelt naar Mijn volgorde en behoudt de volgorde.",
    "importe_um_livro_ou_ajuste_seus_filtro": "Importeer een boek of pas je filters aan.",
    "nada_por_aqui_ainda": "Nog niets hier",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "Tik op + en kies MP3-, M4B- of MP4-bestanden. Meerdere hoofdstuk-MP3’s kunnen één audioboek worden.",
    "nada_para_ouvir_ou_assistir_ainda": "Nog niets om naar te luisteren of te kijken",
    "o_pdf_original_permanece_intacto_na_pa": "De oorspronkelijke PDF blijft onaangetast in je eigen map.",
    "paginas_como_imagem": "Pagina’s als afbeeldingen",
    "paginas_do_pdf": "PDF-pagina’s",
    "em_navegadores_sem_suporte_a_acesso_di": "In browsers zonder directe toegang tot het bestandssysteem wordt de EPUB in plaats daarvan gedownload.",
    "essa_permissao_e_dada_somente_a_esta_a": "Die toestemming wordt alleen aan deze app gegeven en voorkomt dat het oorspronkelijke bestand wordt gewijzigd.",
    "selecione_a_pasta_que_contem_o_pdf": "Selecteer de map met de PDF",
    "preparando": "Voorbereiden…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "Het bestand wordt gelezen en opnieuw opgebouwd. Grote boeken kunnen even duren.",
    "revistas_apostilas_complexas_formulari": "Tijdschriften, complexe werkboeken, formulieren, documenten met veel tabellen of gescande PDF’s kunnen een deel van hun oorspronkelijke opmaak verliezen.",
    "funcionalidade_indicada_apenas_para_li": "Bedoeld voor boeken",
    "o_epub_e_melhor_para_livros_com_texto": "EPUB is beter voor boeken met selecteerbare tekst, omdat je het lettertype, de grootte, marges en leesmodus kunt aanpassen.",
    "trecho_selecionado": "Geselecteerde passage",
    "trecho_comentado": "Passage met een opmerking",
    "aplicando_zoom": "Zoomen...",
    "nao_foi_possivel_carregar_esta_pagina": "Deze pagina kon niet worden geladen.",
    "nomear_marcador": "Bladwijzer een naam geven",
    "toque_em_marcar_agora_para_guardar_est": "Tik op ‘Nu markeren’ om deze plek op te slaan en er later naar terug te keren.",
    "timer_ativo": "Timer actief",
    "trecho_ausente_ou_corrompido_no_arquiv": "[Passage ontbreekt of is beschadigd in het oorspronkelijke bestand]",
    "novos_livros_vao_abrir_em_leitura_v": "Nieuwe boeken openen in leesmodus {v}.",
    "leitura_efetivo_aplicada_a_este_livro": "Leesmodus {efetivo} toegepast op dit boek.",
    "automatico_neste_livro_leitura_efetivo": "Automatisch voor dit boek: leesmodus {efetivo}.",
    "agora_esta_em_efetivo_no_automatico_fo": "Nu ingesteld op {efetivo}; bij automatisch wordt {format} geopend als {padrao}.",
    "esta_escolha_vale_so_para_v_cada_livro": "Deze keuze geldt alleen voor “{v}”. Elk boek behoudt zijn eigen scrollrichting.",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} staan nog niet in je boekenkast.",
    "escolha_uma_pasta_para_procurar_label": "Kies een map om naar {label} te zoeken.",
    "subtitle_versao_build": "{subtitle} · versie {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "Kan {path} niet lezen; de ingebouwde tekst wordt gebruikt.",
    "seu_ultimo_backup_foi_ha_dias_dias": "Je laatste back-up was {dias} dagen geleden",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "{aguardando} boek uit de back-up ontbreekt nog. De voortgang en markeringen ervan zijn bewaard: zodra je het bestand importeert, komt alles automatisch weer op zijn plaats.",
      "other": "{aguardando} boeken uit de back-up ontbreken nog. Hun voortgang en markeringen zijn bewaard: zodra je elk bestand importeert, komt alles automatisch weer op zijn plaats."
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "{atualizados} boek in je boekenkast is bijgewerkt.",
      "other": "{atualizados} boeken in je boekenkast zijn bijgewerkt."
    },
    "criado_em_quando": "Aangemaakt op {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "Back-up klaar: {livros} boeken en {marcacoes} markeringen.",
    "endereco_seguro_seguro": "beveiligd adres: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "Voortgang en {marcas} markering hersteld voor dit boek.",
      "other": "Voortgang en {marcas} markeringen hersteld voor dit boek."
    },
    "restaurando_v_de_length": "Herstellen ({v} van {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} boeken · {marcacoes} markeringen",
    "criado_em_v": "Aangemaakt op {v}",
    "reunindo_a_sua_estante_v_de_length": "Je boekenkast verzamelen ({v} van {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "“{titulo}” is al eerder geïmporteerd en staat nog in je bibliotheek. Er is geen nieuwe kopie gemaakt.",
    "length_arquivos_de_audio": "{length} audiobestanden...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "{falhas} bestand kon niet worden gelezen.",
      "other": "{falhas} bestanden konden niet worden gelezen."
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} stonden al in de bibliotheek en zijn overgeslagen.",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "{importados} boek aan je boekenkast toegevoegd.",
      "other": "{importados} boeken aan je boekenkast toegevoegd."
    },
    "epub_salvo_em_filename": "EPUB opgeslagen in {fileName}.",
    "falha_ao_converter_o_pdf_v": "PDF kon niet worden geconverteerd: {v}",
    "pagina_page_de_totalpages": "Pagina {page} van {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} pagina",
      "other": "{totalPages} pagina’s"
    },
    "length_resultado_s_para_search": {
      "one": "{length} resultaat voor “{search}”",
      "other": "{length} resultaten voor “{search}”"
    },
    "capitulo_v": "Hoofdstuk {v}",
    "organizando_capitulo_v_de_totalchapter": "Hoofdstuk {v} van {totalChapters} opmaken",
    "pagina_v": "Pagina {v}",
    "paginas_v_v2": "Pagina’s {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} pagina klaar",
      "other": "{length} pagina’s klaar"
    },
    "montando_as_paginas_pagessofar_prontas": "Pagina’s opbouwen — {pagesSoFar} klaar",
    "lendo_pagina_v_de_length": "Pagina {v} van {length} lezen",
    "marcador_salvo_em_t": "Bladwijzer opgeslagen op {t}.",
    "o_audio_vai_pausar_em_minutes_minutos": "De audio wordt over {minutes} minuten gepauzeerd.",
    "length_capitulos_toque_para_ir_direto": "{length} hoofdstukken · tik om er direct naartoe te gaan.",
    "narrado_por_narrator": "Verteld door {narrator}",
    "velocidade_de_reproducao_rate": "Afspeelsnelheid: {rate}",
    "avancar_f_segundos": "{f} seconden vooruit",
    "nao_foi_possivel_abrir_este_v": "Deze {v} kon niet worden geopend.",
    "nao_foi_possivel_ler_o_arquivo_de_v": "Het {v}-bestand kon niet worden gelezen.",
    "o_v_esta_danificado_neste_ponto": "De {v} is op dit punt beschadigd.",
    "o_navegador_nao_consegue_reproduzir_es": "De browser kan dit {v}-bestand niet afspelen.",
    "nao_foi_possivel_reproduzir_este_v": "Deze {v} kon niet worden afgespeeld.",
    "os_dados_deste_noun_estao_incompletos": "De gegevens van {noun} zijn onvolledig.",
    "importe_o_arquivo_novamente_para_conti_2": "Importeer het bestand opnieuw om door te gaan met {v}.",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "Het bestand van {noun} staat niet meer op je apparaat.",
    "nao_foi_possivel_descobrir_a_duracao_d": "De duur van “{name}” kon niet worden bepaald.",
    "lendo_faixa_v_de_length": "Track {v} van {length} lezen...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "De duur van deze {v} kon niet worden bepaald.",
    "este_format_nao_pode_ser_reproduzido_n": "Deze {format} kan in deze browser niet worden afgespeeld.",
    "este_format_esta_protegido_por_drm": "Deze {format} is beveiligd met DRM.",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "Het bestand is {bytes} groot en er is nog ongeveer {v} over. Maak ruimte vrij of verwijder boeken uit de bibliotheek.",
    "este_arquivo_nao_e_um_format_valido": "Dit bestand is geen geldige {format}.",
    "preparando_as_paginas_vistas_de_total": "Pagina’s voorbereiden ({vistas} van {total})...",
    "preparando_total_pagina_s": {
      "one": "{total} pagina voorbereiden...",
      "other": "{total} pagina’s voorbereiden..."
    },
    "preparando_as_paginas_v_de_total": "Pagina’s voorbereiden ({v} van {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "Het neemt ongeveer {bytes} in beslag en er is nog ongeveer {v} over. Maak ruimte vrij of verwijder boeken uit de bibliotheek.",
    "envio_direto_exige_endereco_seguro": "Direct naar een andere app versturen is niet beschikbaar, omdat deze pagina niet via een beveiligd adres is geopend. Sla het bestand op en verstuur het via de app die je wilt.",
    "na_estante": "op de plank",
    "nao_foi_possivel_montar_o_arquivo": "Het bestand kon niet worden gemaakt.",
    "este_navegador_nao_oferece_o_envio_dir": "Deze browser biedt geen direct verzenden naar een andere app. Sla het bestand op en voeg het toe via de app van je keuze.",
    "voce_ainda_nao_fez_nenhum_backup": "Je hebt nog geen back-up gemaakt.",
    "converter_para_epub": "Converteren naar EPUB",
    "esta_pagina_nao_pode_ser_exibida": "Deze pagina kon niet worden weergegeven.",
    "na_ordem_em_que_serao_tocados": "In de volgorde waarin ze worden afgespeeld",
    "este_capitulo_nao_pode_ser_exibido": "Dit hoofdstuk kon niet worden weergegeven.",
    "livro": "Boek",
    "restantes": " resterend",
    "como_seus_dados_sao_tratados": "Hoe met je gegevens wordt omgegaan",
    "condicoes_de_uso_do_aplicativo": "Voorwaarden voor het gebruik van de app",
    "audiolivro": "audioboek",
    "sobre_o_aplicativo": "Over de app",
    "o_que_e_o_veredas_reader": "Wat Veredas Reader is",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(dit apparaat ondersteunt het delen van dit bestandstype niet)",
    "livros": "boeken",
    "lendo": "lezen",
    "lidos": "voltooid",
    "compartilhar_livro": "Boek delen",
    "n_livros": {
      "one": "{n} boek",
      "other": "{n} boeken"
    },
    "livros_unidade": {
      "one": "boek",
      "other": "boeken"
    },
    "uma_faixa_discreta_depois_de_n_dias": "Na {n} dagen zonder back-up verschijnt er een subtiele strook op de boekenkast. Deze onderbreekt het lezen nooit.",
    "scanned_arquivos_verificados_livros_enc": "{scanned} bestanden gecontroleerd · {encontrados} boeken gevonden",
    "v_de_total": "{v} van {total}",
    "voltar_n_segundos": "{n} seconden terug",
    "cancelado": "Geannuleerd",
    "arquivo": "Bestand",
    "outro": "Overig",
    "outros": "Overige",
    "audiolivro_2": "Audioboek",
    "pausar": "Pauzeren",
    "marcador": "Bladwijzer",
    "leitura": "Lezen",
    "grifo": "Markering",
    "editar": "Bewerken",
    "apagar": "Verwijderen",
    "concluir": "Voltooien",
    "recentes": "Recent",
    "progresso": "Voortgang",
    "entendi": "Begrepen",
    "aviso": "Melding",
    "descartar": "Verwijderen",
    "copiado": "Gekopieerd",
    "restaurar": "Herstellen",
    "restaurando": "Herstellen",
    "excluir": "Verwijderen",
    "grifos": "Markeringen",
    "arquivo_vazio": "Leeg bestand.",
    "e_mais_n_arquivos": {
      "one": "en nog {n} bestand, in de volgorde waarin ze worden afgespeeld",
      "other": "en nog {n} bestanden, in de volgorde waarin ze worden afgespeeld"
    },
    "n_arquivos_mp3": {
      "one": "{n} MP3-bestand",
      "other": "{n} MP3-bestanden"
    },
    "pct_restam": "{pct}% · nog {tempo}",
    "n_minutos": {
      "one": "{n} minuut",
      "other": "{n} minuten"
    },
    "ir_para_tempo": "Ga naar {tempo}",
    "nomear": "Naam geven",
    "parte_n": "Deel {n}",
    "carregando_pagina_n": "Pagina {n} laden...",
    "selecionar_pasta_e_continuar": "Map kiezen en doorgaan",
    "ler_agora": "Nu lezen",
    "agrupamento_v": "Groepering: {v}.",
    "tempo_restante": "nog {tempo}",
    "abrir_titulo": "{titulo} openen",
    "continuar_lendo_titulo": "Verder lezen in {titulo}",
    "continuar_ouvindo_titulo": "Verder luisteren naar {titulo}",
    "continuar_assistindo_titulo": "Verder kijken naar {titulo}",
    "lido": "Gelezen",
    "pausado": "Gepauzeerd",
    "status": "Status",
    "favorito": "Favoriet",
    "escolher_local": "Locatie kiezen",
    "epub_baixado_como": "EPUB gedownload als {nome}.",
    "ouvir_a_partir_de": "luisteren vanaf {tempo}",
    "assistir_a_partir_de": "kijken vanaf {tempo}",
    "pagina_n_minuscula": "pagina {n}",
    "selecione_trecho_para_criar": "Selecteer tijdens het lezen een passage om {oque} te maken.",
    "excluir_oque_pergunta": "{oque} verwijderen?",
    "excluir_oque": "{oque} verwijderen",
    "excluir_item_pergunta": "Dit item verwijderen?",
    "use_organizar_para_criar": "Gebruik ‘{botao}’ bij een boek om {oque} te maken.",
    "n_arquivos_processados": {
      "one": "{n} bestand verwerkt",
      "other": "{n} bestanden verwerkt"
    },
    "voce_ja_tem_titulo_de_autor": "Je hebt ‘{titulo}’ van {autor} al in je bibliotheek, al is het bestand anders. Toch importeren?",
    "voce_ja_tem_titulo": "Je hebt ‘{titulo}’ al in je bibliotheek, al is het bestand anders. Toch importeren?",
    "marcadores_unidade": {
      "one": "bladwijzer",
      "other": "bladwijzers"
    },
    "ultimo_backup_em": "Laatste back-up op <strong>{data}</strong>.",
    "guardar": "Opslaan",
    "lembretes": "Herinneringen",
    "juntar": "Samenvoegen",
    "recomendado": "aanbevolen",
    "substituir": "Vervangen",
    "n_capas_recuperadas": {
      "one": "{n} omslag hersteld.",
      "other": "{n} omslagen hersteld."
    },
    "nao_encontramos_arquivos_tipo": "Geen {tipo}-bestanden gevonden in deze map.",
    "tentar_outra_pasta": "Andere map proberen",
    "n_livros_encontrados": {
      "one": "{n} boek gevonden",
      "other": "{n} boeken gevonden"
    },
    "n_de_total_selecionados": {
      "one": "{n} van {total} geselecteerd",
      "other": "{n} van {total} geselecteerd"
    },
    "importar": "Importeren",
    "importar_n": "{n} importeren",
    "aceite_frase": "Ik heb het {politica} en de {termos} van Veredas Reader gelezen en ga ermee akkoord.",
    "pdf_preservado": "De oorspronkelijke PDF <strong>wordt niet uit je eigen map verwijderd</strong>. Alleen de kopie van deze pdf wordt uit de bibliotheek gehaald, nadat de EPUB goed is opgeslagen.",
    "gravar_epub_mesma_pasta": "Om de EPUB <strong>in dezelfde map als de PDF</strong> op te slaan, heeft de browser toestemming nodig om die map te openen.",
    "epub_pronto_qualquer_pasta": "De EPUB is geconverteerd. Je kunt nu <strong>elke map op de computer</strong> kiezen om het bestand op te slaan.",
    "backup_explicacao": "De oorspronkelijke back-up is een ZIP- of TXT-bestand. Als je die op een ander apparaat ontvangt, importeer je hem via <strong>Back-up herstellen</strong>: Veredas herkent de inhoud en herstelt die normaal. Het bestand bevat je voortgang, markeringen, citaten, notities, bladwijzers en de indeling van je boekenkast — <strong>niet de boeken zelf</strong>, en ook niet de omslagen.",
    "lembretes_desligados_frase": "Herinneringen staan <strong>uit</strong>. Denk eraan om af en toe een back-up te maken.",
    "backup_salvo_nos_downloads": "<strong>Het back-upbestand is op dit apparaat opgeslagen</strong>, in je downloads. Je kunt het meteen versturen: open WhatsApp, e-mail, Drive of een andere app, tik op bijvoegen en kies het bestand.",
    "arquivo_pronto_tamanho": "Bestand gereed — <strong>{tamanho}</strong>.",
    "scan_intro_frase": "De app kan zoeken naar boeken in <strong>EPUB</strong> en <strong>MOBI</strong>, strips in <strong>CBZ</strong> en <strong>CBR</strong> en audioboeken in <strong>M4B</strong> in een map op je apparaat, inclusief submappen.",
    "scan_intro_auto_frase": "Om je boekenkast snel te vullen, kan de app zoeken naar boeken in <strong>EPUB</strong> en <strong>MOBI</strong>, strips in <strong>CBZ</strong> en <strong>CBR</strong> en audioboeken in <strong>M4B</strong> in een map op je apparaat, inclusief submappen.",
    "n_livros_aguardando": {
      "one": "<strong>{n} boek</strong> met bewaarde voortgang en markeringen wacht op een nieuwe import.",
      "other": "<strong>{n} boeken</strong> met bewaarde voortgang en markeringen wachten op een nieuwe import."
    },
    "fora_da_busca_titulo": "We importeren PDF-, TXT-, DOCX- (Word), MD-, MP3- en MP4-bestanden niet automatisch",
    "fora_da_busca_texto": "Deze formaten worden voor allerlei soorten documenten gebruikt, niet alleen voor boeken. Door ze over te slaan blijft je boekenkast overzichtelijk. <strong>Je kunt elk van deze bestanden zelf importeren met de knop +.</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "Je lokale bibliotheek",
    "biblioteca": "Bibliotheek",
    "organizacao": "Organisatie",
    "minhas_marcacoes": "Mijn markeringen",
    "sistema": "Systeem",
    "sua_biblioteca": "Je bibliotheek",
    "toque_em_um_livro_para_comecar_a_ler": "Tik op een boek om te beginnen met lezen.",
    "agrupar": "Groeperen",
    "sua_estante_nao_tem_copia_de_seguranca": "Je boekenkast heeft geen back-up",
    "se_este_aparelho_se_perder_o_progresso": "Als er iets met dit apparaat gebeurt, kunnen je voortgang en markeringen verloren gaan.",
    "agora_nao": "Niet nu",
    "nao_avisar_mais": "Niet meer herinneren",
    "carregando": "Laden...",
    "estante": "Boekenkast",
    "lendo": "Lezen",
    "favoritos": "Favorieten",
    "marcas": "Markeringen",
    "mais": "Meer",
    "neste_capitulo": "Dit hoofdstuk",
    "velocidade": "Snelheid",
    "timer": "Timer",
    "marcar": "Markeren",
    "marcadores": "Bladwijzers",
    "personalizar_leitura": "Leesvoorkeuren",
    "as_preferencias_ficam_salvas_para_as_p": "Je voorkeuren worden bewaard voor toekomstige leessessies.",
    "tema": "Thema",
    "claro": "Licht",
    "sepia": "Sepia",
    "escuro": "Donker",
    "oceano": "Oceaan",
    "tipografia": "Lettertype",
    "texto": "Tekst",
    "tamanho": "Grootte",
    "espacamento": "Regelafstand",
    "margens": "Marges",
    "cores_personalizadas_opcional": "Aangepaste kleuren (optioneel)",
    "fundo": "Achtergrond",
    "fonte": "Tekstkleur",
    "brilho": "Helderheid",
    "orientacao": "Oriëntatie",
    "auto": "Auto",
    "retrato": "Staand",
    "paisagem": "Liggend",
    "modo_de_leitura": "Leesmodus",
    "automatico": "Automatisch",
    "horizontal": "Horizontaal",
    "vertical": "Verticaal",
    "automatico_usa_rolagem_horizontal_para": "Automatisch gebruikt horizontaal bladeren voor EPUB, MOBI, TXT en MD, en verticaal scrollen voor PDF en DOCX. Als je dit tijdens het lezen wijzigt, geldt de wijziging alleen voor dit boek.",
    "quadrinhos": "Strips",
    "como_a_pagina_aparece": "Hoe de pagina past",
    "pagina_inteira": "Hele pagina",
    "largura_da_tela": "Schermbreedte",
    "sentido_da_leitura": "Leesrichting",
    "normal": "Normaal →",
    "manga": "← Manga",
    "revista_aberta_na_horizontal": "Twee pagina’s naast elkaar in liggende stand",
    "com_o_aparelho_deitado_mostra_duas_pag": "Houd het apparaat zijwaarts om twee pagina’s naast elkaar te zien; de omslag staat alleen, zoals bij een echte strip.",
    "normal_vira_da_esquerda_para_a_direita": "Normaal slaat van links naar rechts om. Manga draait alles om: de veegbeweging, tikken op de randen en de volgorde van de twee pagina’s in een dubbele paginaweergave.",
    "gire_o_aparelho_para_a_horizontal_para": "Draai het apparaat zijwaarts om twee pagina’s tegelijk te zien.",
    "dois_toques_ampliam_no_ponto_tocado_co": "Tik twee keer om in te zoomen op de plek waar je tikte; sleep na het inzoomen om over de pagina te bewegen. Knijpen met twee vingers werkt ook.",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "De scrollknop bovenaan de lezer schakelt tussen pagina voor pagina en continu scrollen (webtoonstijl). Bij continu scrollen lopen de pagina’s in elkaar over en maakt zoomen de pagina breder: je beweegt erdoorheen door zijwaarts te scrollen.",
    "virada_de_pagina": "Pagina omslaan",
    "folha_real": "Echt papier",
    "deslizar": "Schuiven",
    "sem_animacao": "Geen animatie",
    "na_leitura_horizontal_arraste_a_pagina": "Sleep bij horizontaal lezen de pagina vanaf de rand om hem met je vinger om te vouwen. Laat halverwege los om het omslaan te annuleren.",
    "ouvir_leitura": "Luisteren",
    "continue_de_onde_parou_no_seu_ritmo": "Ga verder waar je was gebleven, in je eigen tempo.",
    "livro": "Boek",
    "pronto_para_comecar": "Klaar om te beginnen",
    "voz": "Stem",
    "escolha_uma_voz_disponivel_no_disposit": "Kies een stem die op dit apparaat beschikbaar is",
    "voz_padrao_do_sistema": "Standaardstem van het systeem",
    "durante_a_reproducao": "Tijdens het afspelen",
    "a_leitura_avanca_pagina_a_pagina_os_co": "Het lezen gaat pagina voor pagina. Systeemknoppen verschijnen wanneer de browser ze ondersteunt.",
    "organizar_livro": "Boek organiseren",
    "estantes_colecoes_tags_e_status": "Planken, collecties, tags en status.",
    "cancelar": "Annuleren",
    "salvar": "Opslaan",
    "grifos_citacoes_notas_e_marcadores_des": "Markeringen, citaten, notities en bladwijzers van dit boek.",
    "sumario": "Inhoud",
    "toque_em_um_capitulo_para_ir_direto_ao": "Tik op een hoofdstuk om er direct naartoe te gaan.",
    "sua_anotacao": "Je notitie",
    "edite_ou_adicione_comentarios_ao_seu_t": "Bewerk je passage of voeg er opmerkingen aan toe.",
    "trecho": "Passage",
    "sua_nota": "Je notitie",
    "salvar_nota": "Notitie opslaan",
    "agrupar_biblioteca": "Bibliotheek groeperen",
    "escolha_como_os_livros_serao_organizad": "Kies hoe boeken in de boekenkast worden gerangschikt.",
    "ao_arrastar_um_livro_para_outra_posica": "Wanneer je een boek naar een andere plek sleept, schakelt de boekenkast automatisch over naar Mijn volgorde en behoudt hij de volgorde die je hebt opgebouwd.",
    "backup_e_restauracao": "Back-up en herstel",
    "sua_estante_seu_progresso_e_suas_marca": "Je boekenkast, je voortgang en je markeringen in één bestand.",
    "escolha_uma_dimensao_para_explorar_sua": "Kies een manier om je bibliotheek te verkennen.",
    "capitulos": "Hoofdstukken",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "De stem behoudt zijn toonhoogte. Dit geldt voor dit boek en de volgende.",
    "ajuste_fino": "Fijnafstelling",
    "timer_de_sono": "Slaaptimer",
    "o_audio_diminui_de_volume_aos_poucos_e": "De audio wordt geleidelijk zachter en pauzeert automatisch.",
    "pontos_que_voce_guardou_neste_audioliv": "Plekken die je in dit audioboek hebt opgeslagen.",
    "ajustes_do_audio": "Audio-instellingen",
    "as_preferencias_ficam_salvas_para_todo": "Deze voorkeuren worden voor elk audioboek bewaard.",
    "botao_de_voltar": "Terugspoelknop",
    "botao_de_avancar": "Vooruitknop",
    "recuar_ao_retomar": "Terugspoelen bij hervatten",
    "depois_de_uma_pausa_longa_volta_alguns": "Na een lange pauze gaat hij een paar seconden terug, zodat je de draad weer kunt oppakken.",
    "tocar_ao_abrir": "Afspelen bij openen",
    "ao_tocar_em_um_audiolivro_na_estante_a": "Als je op een audioboek in de boekenkast tikt, begint het direct af te spelen.",
    "no_computador_espaco_toca_e_pausa_pula": "Op een computer: spatiebalk afspelen/pauzeren · ← → overslaan · Shift + ← → hoofdstuk wijzigen · ↑ ↓ volume · B bladwijzers · [ ] snelheid.",
    "converter_pdf_para_epub": "PDF naar EPUB converteren",
    "prepare_o_livro_para_leitura_fluida_e": "Maak het boek klaar voor soepel lezen met aanpasbare instellingen.",
    "confirmacao": "Bevestigen",
    "confirmar": "Bevestigen",
    "processando": "Bezig",
    "documento": "Document",
    "buscar_livros_no_dispositivo": "Boeken zoeken op dit apparaat",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "Zoek EPUB-, MOBI-, CBZ-, CBR- en M4B-bestanden die al op je apparaat zijn opgeslagen.",
    "juntar_em_um_unico_audiolivro": "Samenvoegen tot één audioboek?",
    "titulo": "Titel",
    "autor": "Auteur",
    "importar_separados": "Apart importeren",
    "bem_vindo_ao_veredas_reader": "Welkom bij Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "Je leesbibliotheek, volledig op je eigen apparaat.",
    "buscar": "Zoeken",
    "importar_livro": "Boek importeren",
    "buscar_titulo_autor_tag": "Titel, auteur, tag zoeken...",
    "fechar_busca": "Zoeken sluiten",
    "navegacao_da_biblioteca": "Bibliotheeknavigatie",
    "fechar_menu": "Menu sluiten",
    "agrupar_livros": "Boeken groeperen",
    "voltar": "Terug",
    "marcar_pagina": "Pagina markeren",
    "personalizar": "Voorkeuren",
    "navegacao_principal": "Hoofdnavigatie",
    "acoes_do_trecho": "Acties voor passage",
    "amarelo": "Geel",
    "verde": "Groen",
    "rosa": "Roze",
    "azul": "Blauw",
    "player_de_audiolivro": "Audioboekspeler",
    "minimizar_player": "Speler minimaliseren",
    "minimizar": "Minimaliseren",
    "video_em_reproducao": "Video wordt afgespeeld",
    "abrir_a_lista_de_capitulos": "Hoofdstukkenlijst openen",
    "posicao_no_audio": "Positie in audio",
    "alternar_entre_o_progresso_do_capitulo": "Schakelen tussen hoofdstukvoortgang en voortgang van het hele boek",
    "capitulo_anterior": "Vorig hoofdstuk",
    "voltar_15_segundos": "15 seconden terug",
    "reproduzir": "Afspelen",
    "avancar_30_segundos": "30 seconden vooruit",
    "proximo_capitulo": "Volgend hoofdstuk",
    "velocidade_de_reproducao": "Afspeelsnelheid",
    "marcar_este_ponto": "Deze plek markeren",
    "ver_marcadores": "Bladwijzers bekijken",
    "silenciar": "Dempen",
    "volume": "Volume",
    "audiolivro_em_reproducao": "Audioboek wordt afgespeeld",
    "abrir_o_player": "Speler openen",
    "fechar_o_player": "Speler sluiten",
    "fechar": "Sluiten",
    "trecho_anterior": "Vorige passage",
    "iniciar_leitura": "Voorlezen starten",
    "proximo_trecho": "Volgende passage",
    "escreva_seu_comentario_interpretacao_o": "Schrijf je opmerking, interpretatie of herinnering...",
    "cancelar_importacao": "Importeren annuleren",
    "nome_do_audiolivro": "Naam van audioboek",
    "nome_do_autor": "Naam van auteur",
    "idioma": "Taal",
    "idioma_do_aplicativo": "Taal van de app",
    "o_aplicativo_segue_o_idioma_do_apare": "De app volgt de taal van je apparaat. Als jouw taal hier nog niet bestaat, wordt de app in het Engels geopend.",
    "seguir_o_aparelho": "Apparaat volgen",
    "fazer_backup": "Nu back-up maken",
    "todos": "Alle",
    "lidos": "Voltooid",
    "pausados": "Gepauzeerd",
    "autores": "Auteurs",
    "tags": "Tags",
    "grifar": "Markeren",
    "anotar": "Notitie",
    "enviar": "Versturen",
    "restaurar_padroes": "Standaardwaarden herstellen",
    "voltar_para_1": "Terug naar 1×",
    "marcar_agora": "Nu markeren",
    "escolher_pasta": "Map kiezen",
    "juntar_em_um_audiolivro": "Samenvoegen tot één audioboek",
    "sobre": "Over",
    "licencas_de_codigo_aberto": "Opensourcelicenties",
    "configuracoes": "Instellingen",
    "temas_e_idioma": "Thema’s en taal"
  },
  "aviso": {
    "idioma_trocado": "Taal gewijzigd."
  },
  "vn": {
    "quem_le": "Wie leest er voor",
    "natural": "Natuurlijk",
    "do_sistema": "Systeem",
    "nota_sistema": "Gebruikt de stemmen die op je apparaat zijn geïnstalleerd. Kies Natuurlijk voor voorlezen dat menselijker klinkt.",
    "nota_sistema_com_natural": "De natuurlijke stem blijft gedownload. Schakel terug naar Natuurlijk wanneer je wilt.",
    "voz_do_sistema": "Systeemstem",
    "lendo_com_a_voz_do_sistema": "Wordt voorgelezen met de systeemstem.",
    "voz_natural": "Natuurlijke stem",
    "gerada_no_aparelho": "Een veel menselijkere stem, direct op je apparaat gemaakt.",
    "progresso_download": "Downloadvoortgang",
    "x_de_y": "{x} van {y}",
    "aviso_arquivo": "Voor de natuurlijke stem moet Veredas worden geopend via het adres van de app, niet als bestand op je computer. Tot die tijd wordt voorgelezen met de systeemstem.",
    "aviso_navegador": "Deze browser mist functies die de natuurlijke stem nodig heeft. Het voorlezen gaat verder met de systeemstem.",
    "verificando": "Natuurlijke stem controleren…",
    "fato_download": "Eenmalige download van {tamanho}. Daarna werkt het zonder internet.",
    "fato_wifi": "Wi-Fi is het handigst. Je kunt pauzeren en later verdergaan.",
    "fato_privacidade": "De tekst van het boek verlaat je apparaat nooit.",
    "fato_idiomas": "Spreekt 31 talen, waaronder Nederlands, Engels en Portugees. Andere talen blijven de systeemstem gebruiken.",
    "baixar_voz_natural": "Natuurlijke stem downloaden ({tamanho})",
    "licenca_curta": "Model Supertonic 3 van Supertone, onder de OpenRAIL-M-licentie. Details bij Over > Opensourcelicenties.",
    "pode_continuar_usando": "Je kunt gewoon verder lezen tijdens het downloaden. Valt de verbinding weg, dan gaat de download verder waar hij gebleven was.",
    "pausar_download": "Download pauzeren",
    "erro_espaco": "Er is niet genoeg ruimte op het apparaat om de download af te ronden. Maak wat ruimte vrij en probeer het opnieuw.",
    "erro_offline": "Op dit moment geen internet. Wat al gedownload is, blijft bewaard.",
    "erro_rede": "De verbinding viel weg tijdens de download. Wat al gedownload is, blijft bewaard.",
    "download_pausado": "Download gepauzeerd. Wat al gedownload is, blijft bewaard.",
    "continuar_download": "Hervatten",
    "descartar": "Verwijderen",
    "voz_feminina": "Vrouwelijk",
    "voz_feminina_desc": "Zacht en kalm",
    "voz_masculina": "Mannelijk",
    "voz_masculina_desc": "Warm en sereen",
    "parar_amostra": "Voorbeeld stoppen",
    "ouvir_amostra_de": "Voorbeeld afspelen: {voz}",
    "escolha_a_voz": "Kies de stem",
    "qualidade": "Kwaliteit",
    "q_auto": "Automatisch",
    "q_rapida": "Snel",
    "q_maxima": "Beste",
    "q_auto_desc": "Past zich aan de prestaties van je apparaat aan, zodat het voorlezen zonder pauzes verloopt.",
    "q_rapida_desc": "Maakt de stem sneller aan. Handig voor eenvoudigere apparaten.",
    "q_maxima_desc": "Het meest verfijnde geluid. Op eenvoudigere apparaten kunnen er pauzes tussen zinnen vallen.",
    "ocupa": "Neemt {tamanho} in beslag op dit apparaat",
    "remover": "Verwijderen",
    "baixar_pelos_dados": "Downloaden via mobiele data?",
    "baixar_pelos_dados_msg": "Je apparaat lijkt niet met Wi-Fi verbonden te zijn. De download is {tamanho} en gaat mogelijk van je databundel af.",
    "baixar_agora": "Toch downloaden",
    "pronta": "De natuurlijke stem is klaar.",
    "download_interrompido": "De download is gestopt. Tik op Hervatten wanneer je wilt.",
    "remover_titulo": "Natuurlijke stem verwijderen?",
    "descartar_titulo": "Download verwijderen?",
    "remover_msg": "Dit maakt {tamanho} vrij. Er wordt weer voorgelezen met de systeemstem, en je kunt de natuurlijke stem altijd opnieuw downloaden.",
    "descartar_msg": "Wat al gedownload is, wordt verwijderd.",
    "removida": "Natuurlijke stem verwijderd van dit apparaat.",
    "amostra_falhou": "Het voorbeeld kan op dit apparaat niet worden afgespeeld.",
    "amostra": "Hallo! Zo klinken je boeken met de natuurlijke stem.",
    "pode_demorar_um_minuto": "Dit kan een minuut duren.",
    "gerando_voz": "Stem voorbereiden…",
    "automatico_idioma": "Automatisch ({idioma})",
    "automatico": "Automatisch",
    "so_voz_do_sistema": "systeemstem",
    "aviso_idioma": "Taal van de tekst: {idioma}. De natuurlijke stem spreekt deze taal nog niet, dus het boek wordt voorgelezen met de systeemstem.",
    "aviso_idioma_desconhecido": "De taal van deze tekst werd niet herkend. Kies hieronder de taal om de natuurlijke stem te gebruiken.",
    "aviso_falha": "De natuurlijke stem kon nu niet werken op dit apparaat. Het voorlezen gaat verder met de systeemstem.",
    "nao_carregou_usando_sistema": "De natuurlijke stem is niet geladen op dit apparaat. Voorlezen met de systeemstem.",
    "parou_usando_sistema": "De natuurlijke stem is gestopt. Verder met de systeemstem.",
    "aparelho_lento": "Dit apparaat maakt de stem traag aan. Kies kwaliteit Snel om pauzes te voorkomen.",
    "idioma_do_texto": "Taal van de tekst",
    "idioma_do_texto_dica": "Herkend aan de tekst zelf. Wijzig dit als de uitspraak niet klopt.",
    "leitura_em_voz_alta": "Voorlezen",
    "lento_usando_sistema": "De natuurlijke stem is te traag op dit apparaat. Het voorlezen gaat verder met de systeemstem.",
    "aviso_lento": "Dit apparaat kan de natuurlijke stem niet snel genoeg maken, dus de systeemstem leest voorlopig voor.",
    "sem_memoria_usando_sistema": "De natuurlijke stem paste niet in het geheugen van dit apparaat. De systeemstem leest voor.",
    "aviso_falha_memoria": "Er was niet genoeg geheugen voor de natuurlijke stem op dit apparaat. Andere apps sluiten en het opnieuw proberen helpt meestal; zolang leest de systeemstem voor.",
    "copiar_detalhe": "Details kopiëren",
    "copiado": "Details gekopieerd.",
    "falhou_titulo": "De natuurlijke stem is niet geladen op dit apparaat.",
    "falhou_texto": "Het apparaat kon de natuurlijke stem niet klaarzetten. Het voorlezen gaat verder met de systeemstem. Kopieer de details hieronder en stuur ze naar de ondersteuning om te helpen.",
    "falhou_memoria_texto": "Er was te weinig geheugen voor de natuurlijke stem op dit apparaat. Andere apps sluiten en opnieuw proberen helpt meestal.",
    "tentar_de_novo": "Opnieuw proberen",
    "tentando": "Laden…",
    "sondando": "Het geheugen van dit apparaat wordt getest…",
    "sonda_explica": "De test reserveert een paar seconden het geheugen dat de natuurlijke stem nodig heeft en geeft het meteen weer vrij. Zo weet je het nu en niet pas na het downloaden.",
    "aviso_aparelho_justo": "Dit apparaat heeft weinig geheugen voor de natuurlijke stem. Mogelijk laadt hij niet; verwijder hem dan gewoon en krijg de ruimte terug.",
    "preparando_demora": "De stem wordt voorbereid. Dit kan een paar minuten duren.",
    "incompativel_titulo": "De natuurlijke stem werkt niet op dit apparaat.",
    "incompativel_memoria": "Er was te weinig geheugen om hem klaar te zetten. Het voorlezen blijft bij de systeemstem; de opties daarvoor staan hieronder. Sluit desgewenst andere apps en tik op Opnieuw testen.",
    "incompativel_lento": "Hij was te traag om het voorlezen bij te houden. Het voorlezen blijft bij de systeemstem; de opties daarvoor staan hieronder.",
    "incompativel_queda": "De app sloot tijdens het laden. Het voorlezen blijft bij de systeemstem; de opties daarvoor staan hieronder.",
    "incompativel_falha": "Hij kon hier niet laden. Het voorlezen blijft bij de systeemstem; de opties daarvoor staan hieronder.",
    "testar_de_novo": "Opnieuw testen",
    "remover_e_liberar": "Verwijderen en {tamanho} vrijmaken",
    "tela_durante_a_leitura": "Scherm tijdens het lezen",
    "manter_tela_ligada": "Scherm aan laten",
    "manter_tela_ligada_dica": "Zolang een boek open is, gaat het scherm niet vanzelf uit. Bij het sluiten van het boek is alles weer normaal."
  }
});
