/* ============================================================
   PORTUGUÊS (BRASIL) — o original
   ------------------------------------------------------------
   Este arquivo é a FONTE DA VERDADE do texto do aplicativo. Para
   mudar uma palavra que aparece na tela, mude aqui — não no
   app.js nem no index.html, onde agora só existem chaves.

   Sobre as chaves: elas nasceram do próprio texto em português
   ("ui.agora_nao" veio de "Agora não"), mas uma vez criadas NÃO
   MUDAM MAIS. Se você reescrever "Agora não" para "Mais tarde",
   troque só o texto à direita e deixe a chave quieta — senão as
   outras onze línguas perdem a linha e caem no inglês.

   Por que .js e não .json: no PC o aplicativo abre por duplo
   clique, em endereço file://, e ali o navegador proíbe ler um
   arquivo .json vizinho. O conteúdo abaixo é JSON puro; só a
   casca é JavaScript. Está explicado em idioma.js.
   ============================================================ */
Idiomas.registrar('pt-BR', {
  "ui": {
    "sua_biblioteca_local": "Sua biblioteca local",
    "biblioteca": "Biblioteca",
    "organizacao": "Organização",
    "minhas_marcacoes": "Minhas marcações",
    "sistema": "Sistema",
    "sua_biblioteca": "Sua Biblioteca",
    "toque_em_um_livro_para_comecar_a_ler": "Toque em um livro para começar a ler.",
    "agrupar": "Agrupar",
    "sua_estante_nao_tem_copia_de_seguranca": "Sua estante não tem cópia de segurança",
    "se_este_aparelho_se_perder_o_progresso": "Se algo acontecer com este aparelho, o progresso e as marcações podem se perder.",
    "agora_nao": "Agora não",
    "nao_avisar_mais": "Não avisar mais",
    "carregando": "Carregando...",
    "estante": "Estante",
    "lendo": "Lendo",
    "favoritos": "Favoritos",
    "marcas": "Marcas",
    "mais": "Mais",
    "neste_capitulo": "Neste capítulo",
    "velocidade": "Velocidade",
    "timer": "Timer",
    "marcar": "Marcar",
    "marcadores": "Marcadores",
    "personalizar_leitura": "Personalizar leitura",
    "as_preferencias_ficam_salvas_para_as_p": "As preferências ficam salvas para as próximas leituras.",
    "tema": "Tema",
    "claro": "Claro",
    "sepia": "Sépia",
    "escuro": "Escuro",
    "oceano": "Oceano",
    "tipografia": "Tipografia",
    "texto": "Texto",
    "tamanho": "Tamanho",
    "espacamento": "Espaçamento",
    "margens": "Margens",
    "cores_personalizadas_opcional": "Cores personalizadas (Opcional)",
    "fundo": "Fundo",
    "fonte": "Fonte",
    "brilho": "Brilho",
    "orientacao": "Orientação",
    "auto": "Auto",
    "retrato": "Retrato",
    "paisagem": "Paisagem",
    "modo_de_leitura": "Modo de leitura",
    "automatico": "Automático",
    "horizontal": "Horizontal",
    "vertical": "Vertical",
    "automatico_usa_rolagem_horizontal_para": "Automático usa rolagem horizontal para EPUB, MOBI, TXT e MD, e vertical para PDF e DOCX. Mudando durante a leitura, o ajuste fica guardado só naquele livro.",
    "quadrinhos": "Quadrinhos",
    "como_a_pagina_aparece": "Como a página aparece",
    "pagina_inteira": "Página inteira",
    "largura_da_tela": "Largura da tela",
    "sentido_da_leitura": "Sentido da leitura",
    "normal": "Normal →",
    "manga": "← Mangá",
    "revista_aberta_na_horizontal": "Revista aberta na horizontal",
    "com_o_aparelho_deitado_mostra_duas_pag": "Com o aparelho deitado, mostra duas páginas lado a lado — a capa fica sozinha, como numa revista de verdade.",
    "normal_vira_da_esquerda_para_a_direita": "Normal vira da esquerda para a direita. Mangá inverte tudo: o deslize, o toque nas bordas e a ordem das duas páginas na revista aberta.",
    "gire_o_aparelho_para_a_horizontal_para": "Gire o aparelho para a horizontal para ver duas páginas lado a lado.",
    "dois_toques_ampliam_no_ponto_tocado_co": "Dois toques ampliam no ponto tocado; com zoom, arraste para passear pela página. Pinçar com dois dedos também funciona.",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "O botão de rolagem, no topo do leitor, alterna entre página a página e rolagem contínua (estilo webtoon). Na rolagem contínua as páginas emendam uma na outra, e ampliar alarga a página: você passeia por ela rolando para os lados.",
    "virada_de_pagina": "Virada de página",
    "folha_real": "Folha real",
    "deslizar": "Deslizar",
    "sem_animacao": "Sem animação",
    "na_leitura_horizontal_arraste_a_pagina": "Na leitura horizontal, arraste a página a partir da borda para dobrá-la com o dedo. Solte no meio do caminho para desistir da virada.",
    "ouvir_leitura": "Ouvir leitura",
    "continue_de_onde_parou_no_seu_ritmo": "Continue de onde parou, no seu ritmo.",
    "livro": "Livro",
    "pronto_para_comecar": "Pronto para começar",
    "voz": "Voz",
    "escolha_uma_voz_disponivel_no_disposit": "Escolha uma voz disponível no dispositivo",
    "voz_padrao_do_sistema": "Voz padrão do sistema",
    "durante_a_reproducao": "Durante a reprodução",
    "a_leitura_avanca_pagina_a_pagina_os_co": "A leitura avança página a página. Os controles do sistema aparecem quando o navegador oferece suporte.",
    "organizar_livro": "Organizar livro",
    "estantes_colecoes_tags_e_status": "Estantes, coleções, tags e status.",
    "cancelar": "Cancelar",
    "salvar": "Salvar",
    "grifos_citacoes_notas_e_marcadores_des": "Grifos, citações, notas e marcadores deste livro.",
    "sumario": "Sumário",
    "toque_em_um_capitulo_para_ir_direto_ao": "Toque em um capítulo para ir direto ao ponto.",
    "sua_anotacao": "Sua anotação",
    "edite_ou_adicione_comentarios_ao_seu_t": "Edite ou adicione comentários ao seu trecho.",
    "trecho": "Trecho",
    "sua_nota": "Sua nota",
    "salvar_nota": "Salvar nota",
    "agrupar_biblioteca": "Agrupar biblioteca",
    "escolha_como_os_livros_serao_organizad": "Escolha como os livros serão organizados na estante.",
    "ao_arrastar_um_livro_para_outra_posica": "Ao arrastar um livro para outra posição, a estante muda automaticamente para Minha Ordem e mantém a sequência que você montou.",
    "backup_e_restauracao": "Backup e restauração",
    "sua_estante_seu_progresso_e_suas_marca": "Sua estante, seu progresso e suas marcações num arquivo só.",
    "escolha_uma_dimensao_para_explorar_sua": "Escolha uma dimensão para explorar sua biblioteca.",
    "capitulos": "Capítulos",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "A voz não fica mais grave nem mais aguda. A escolha vale para este e para os próximos livros.",
    "ajuste_fino": "Ajuste fino",
    "timer_de_sono": "Timer de sono",
    "o_audio_diminui_de_volume_aos_poucos_e": "O áudio diminui de volume aos poucos e pausa automaticamente.",
    "pontos_que_voce_guardou_neste_audioliv": "Pontos que você guardou neste audiolivro.",
    "ajustes_do_audio": "Ajustes do áudio",
    "as_preferencias_ficam_salvas_para_todo": "As preferências ficam salvas para todos os audiolivros.",
    "botao_de_voltar": "Botão de voltar",
    "botao_de_avancar": "Botão de avançar",
    "recuar_ao_retomar": "Recuar ao retomar",
    "depois_de_uma_pausa_longa_volta_alguns": "Depois de uma pausa longa, volta alguns segundos para você reencontrar o fio da história.",
    "tocar_ao_abrir": "Tocar ao abrir",
    "ao_tocar_em_um_audiolivro_na_estante_a": "Ao tocar em um audiolivro na estante, a reprodução começa na hora.",
    "no_computador_espaco_toca_e_pausa_pula": "No computador: espaço toca e pausa · ← → pulam · Shift + ← → trocam de capítulo · ↑ ↓ volume · B marca · [ ] velocidade.",
    "converter_pdf_para_epub": "Converter PDF para EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "Prepare o livro para leitura fluida e ajustável.",
    "confirmacao": "Confirmação",
    "confirmar": "Confirmar",
    "processando": "Processando",
    "documento": "Documento",
    "buscar_livros_no_dispositivo": "Buscar livros no dispositivo",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "Encontre arquivos EPUB, MOBI, CBZ, CBR e M4B já salvos no aparelho.",
    "juntar_em_um_unico_audiolivro": "Juntar em um único audiolivro?",
    "titulo": "Título",
    "autor": "Autor",
    "importar_separados": "Importar separados",
    "bem_vindo_ao_veredas_reader": "Bem-vindo ao Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "Sua biblioteca de leitura, inteiramente no seu dispositivo.",
    "buscar": "Buscar",
    "importar_livro": "Importar livro",
    "buscar_titulo_autor_tag": "Buscar título, autor, tag...",
    "fechar_busca": "Fechar busca",
    "navegacao_da_biblioteca": "Navegação da biblioteca",
    "fechar_menu": "Fechar menu",
    "agrupar_livros": "Agrupar livros",
    "voltar": "Voltar",
    "marcar_pagina": "Marcar página",
    "personalizar": "Personalizar",
    "navegacao_principal": "Navegação principal",
    "acoes_do_trecho": "Ações do trecho",
    "amarelo": "Amarelo",
    "verde": "Verde",
    "rosa": "Rosa",
    "azul": "Azul",
    "player_de_audiolivro": "Player de audiolivro",
    "minimizar_player": "Minimizar player",
    "minimizar": "Minimizar",
    "video_em_reproducao": "Vídeo em reprodução",
    "abrir_a_lista_de_capitulos": "Abrir a lista de capítulos",
    "posicao_no_audio": "Posição no áudio",
    "alternar_entre_o_progresso_do_capitulo": "Alternar entre o progresso do capítulo e o do livro inteiro",
    "capitulo_anterior": "Capítulo anterior",
    "voltar_15_segundos": "Voltar 15 segundos",
    "reproduzir": "Reproduzir",
    "avancar_30_segundos": "Avançar 30 segundos",
    "proximo_capitulo": "Próximo capítulo",
    "velocidade_de_reproducao": "Velocidade de reprodução",
    "marcar_este_ponto": "Marcar este ponto",
    "ver_marcadores": "Ver marcadores",
    "silenciar": "Silenciar",
    "volume": "Volume",
    "audiolivro_em_reproducao": "Audiolivro em reprodução",
    "abrir_o_player": "Abrir o player",
    "fechar_o_player": "Fechar o player",
    "fechar": "Fechar",
    "trecho_anterior": "Trecho anterior",
    "iniciar_leitura": "Iniciar leitura",
    "proximo_trecho": "Próximo trecho",
    "escreva_seu_comentario_interpretacao_o": "Escreva seu comentário, interpretação ou lembrete...",
    "cancelar_importacao": "Cancelar importação",
    "nome_do_audiolivro": "Nome do audiolivro",
    "nome_do_autor": "Nome do autor",
    "idioma": "Idioma",
    "idioma_do_aplicativo": "Idioma do aplicativo",
    "o_aplicativo_segue_o_idioma_do_apare": "O aplicativo segue o idioma do aparelho. Se o seu idioma ainda não existir aqui, ele abre em inglês.",
    "seguir_o_aparelho": "Seguir o aparelho",
    "fazer_backup": "Fazer backup",
    "todos": "Todos",
    "lidos": "Lidos",
    "pausados": "Pausados",
    "autores": "Autores",
    "tags": "Tags",
    "grifar": "Grifar",
    "anotar": "Anotar",
    "enviar": "Enviar",
    "restaurar_padroes": "Restaurar Padrões",
    "voltar_para_1": "Voltar para 1×",
    "marcar_agora": "Marcar agora",
    "escolher_pasta": "Escolher pasta",
    "juntar_em_um_audiolivro": "Juntar em um audiolivro",
    "sobre": "Sobre",
    "licencas_de_codigo_aberto": "Licenças de código aberto",
    "configuracoes": "Configurações",
    "temas_e_idioma": "Temas e idioma"
  },
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "Marcador excluído.",
    "excluir_marcador": "Excluir marcador",
    "o_marcador_sera_removido_permanentemen": "O marcador será removido permanentemente.",
    "excluir_marcador_2": "Excluir marcador?",
    "pagina_salva": "Página salva",
    "anotacoes": "Anotações",
    "citacoes": "Citações",
    "item_excluido": "Item excluído.",
    "este_registro_sera_removido_permanente": "Este registro será removido permanentemente da biblioteca.",
    "configuracoes_padrao_restauradas": "Configurações padrão restauradas.",
    "leitura_da_esquerda_para_a_direita": "Leitura da esquerda para a direita.",
    "leitura_da_direita_para_a_esquerda_man": "Leitura da direita para a esquerda (mangá).",
    "a_pagina_inteira_passa_a_caber_na_tela": "A página inteira passa a caber na tela.",
    "a_pagina_passa_a_ocupar_toda_a_largura": "A página passa a ocupar toda a largura da tela.",
    "virada_sem_animacao_ativada": "Virada sem animação ativada.",
    "virada_deslizante_ativada": "Virada deslizante ativada.",
    "virada_em_folha_real_ativada": "Virada em folha real ativada.",
    "padrao_automatico_cada_formato_abre_no": "Padrão automático: cada formato abre no sentido natural dele.",
    "mudando_durante_a_leitura_o_ajuste_fic": "Mudando durante a leitura, o ajuste fica guardado só naquele livro.",
    "automatico_usa_rolagem_horizontal_para": "Automático usa rolagem horizontal para EPUB, MOBI, TXT, MD e quadrinhos, e vertical para PDF e DOCX.",
    "este_livro": "este livro",
    "armazenamento_local_indisponivel_neste": "Armazenamento local indisponível neste navegador.",
    "o_aplicativo_pode_procurar_os_livros_q": "O aplicativo pode procurar os livros que já estão no seu aparelho.",
    "vamos_montar_sua_estante": "Vamos montar sua estante?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "Sem a aceitação, o aplicativo não pode ser usado.",
    "precisamos_do_seu_aceite": "Precisamos do seu aceite",
    "antes_de_comecar_leia_e_aceite_os_docu": "Antes de começar, leia e aceite os documentos abaixo.",
    "selecionar_todos": "Selecionar todos",
    "limpar_selecao": "Limpar seleção",
    "todos_parecem_ja_estar_na_sua_estante": "Todos parecem já estar na sua estante.",
    "lendo_a_pasta_escolhida": "Lendo a pasta escolhida…",
    "procurando_livros": "Procurando livros",
    "nao_foi_possivel_concluir_a_busca_no_d": "Não foi possível concluir a busca no dispositivo.",
    "tente_outra_pasta_do_aparelho": "Tente outra pasta do aparelho.",
    "nenhum_livro_encontrado": "Nenhum livro encontrado",
    "use_o_botao_para_escolher_os_arquivos": "Use o botão + para escolher os arquivos manualmente. Em celulares Android, o Chrome costuma permitir a escolha de uma pasta inteira.",
    "seu_navegador_nao_permite_ler_pastas": "Seu navegador não permite ler pastas",
    "busca_automatica_indisponivel": "Busca automática indisponível",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR e M4B",
    "termos_de_uso": "Termos de uso",
    "politica_de_privacidade": "Política de privacidade",
    "um_minuto_agora_evita_perder_o_progres": "Um minuto agora evita perder o progresso e as marcações depois.",
    "ver_estante": "Ver estante",
    "modo_juntar": "Modo juntar",
    "modo_substituir": "Modo substituir",
    "restauracao_concluida": "Restauração concluída",
    "tente_de_novo_com_o_arquivo_original": "Tente de novo com o arquivo original.",
    "a_restauracao_nao_pode_ser_concluida": "A restauração não pôde ser concluída",
    "devolvendo_o_seu_progresso_e_as_suas_m": "Devolvendo o seu progresso e as suas marcações...",
    "restaurar_este_backup": "Restaurar este backup?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Escolha o .zip salvo pelo Veredas ou o .txt recebido pelo compartilhamento.",
    "nao_foi_possivel_ler_este_arquivo": "Não foi possível ler este arquivo",
    "lendo_o_backup": "Lendo o backup",
    "backup_do_veredas_reader": "Backup do Veredas Reader",
    "arquivo_de_transporte_txt_contendo_os": "cópia do backup em formato .txt, com o mesmo conteúdo do ZIP",
    "nao_foi_possivel_montar_o_arquivo_de_b": "Não foi possível montar o arquivo de backup.",
    "escolher_o_app": "Escolher o app",
    "vale_conferir_o_que_vai_no_arquivo": "Vale conferir o que vai no arquivo",
    "enviar_para_outro_app": "Enviar para outro app",
    "salvar_o_arquivo": "Salvar o arquivo",
    "o_navegador_aqui_nao_oferece_o_compart": "O navegador aqui não oferece o compartilhamento direto. Dá para salvar o arquivo e enviá-lo depois pelo aplicativo que você quiser.",
    "este_aparelho_nao_abre_a_lista_de_apli": "Este aparelho não abre a lista de aplicativos",
    "importe_pelo_menos_um_livro_antes_de_f": "Importe pelo menos um livro antes de fazer um backup.",
    "estante_vazia": "Estante vazia",
    "nao_deu_para_copiar": "Não deu para copiar",
    "copiar_detalhes": "Copiar detalhes",
    "o_backup_foi_salvo_assim_mesmo": "O backup foi salvo assim mesmo",
    "o_aparelho_recusou_abrir_a_lista": "Não foi possível abrir a lista de compartilhamento",
    "sem_detalhes_do_navegador": "sem detalhes do navegador",
    "o_sistema_nao_aceitou_receber_o_arquiv": "O sistema do aparelho não conseguiu receber o arquivo.",
    "o_navegador_considerou_a_situacao_inse": "O navegador bloqueou o compartilhamento por uma regra de segurança própria. Salve o arquivo e envie-o pelo aplicativo que preferir.",
    "o_compartilhamento_so_funciona_em_ende": "O compartilhamento só funciona em endereços seguros. Este aplicativo está sendo aberto por um endereço http:// comum, e nesse caso o navegador bloqueia o envio para outros aplicativos.",
    "este_navegador_nao_conseguiu_iniciar_o": "Este navegador não conseguiu abrir o compartilhamento. Salve o arquivo e envie-o pelo aplicativo que preferir.",
    "o_navegador_recebeu_um_arquivo_em_form": "O navegador não abriu a lista de aplicativos para compartilhar. Toque no botão de novo ou salve o arquivo e envie-o pelo aplicativo que preferir.",
    "nao_foi_possivel_gerar_o_backup": "Não foi possível gerar o backup.",
    "reunindo_a_sua_estante": "Reunindo a sua estante...",
    "preparando_o_backup": "Preparando o backup",
    "pronto_nada_mais_esta_esperando": "Pronto, nada mais está esperando.",
    "o_progresso_e_as_marcacoes_desses_livr": "O progresso e as marcações desses livros serão apagados. Se você importar os arquivos depois, eles voltarão em branco.",
    "descartar_o_que_esta_esperando": "Apagar os dados em espera?",
    "lembretes_de_backup_religados": "Lembretes de backup religados.",
    "sem_titulo": "Sem título",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "Lembretes desligados.",
    "manter_ligado": "Manter ligado",
    "desligar_assim_mesmo": "Desligar assim mesmo",
    "o_botao_de_salvar_continua_onde_sempre": "O botão de salvar continua onde sempre esteve, em Backup e restauração.",
    "o_lembrete_e_o_unico_aviso_que_existe": "O lembrete é o único aviso que existe. Sem ele, será preciso lembrar de fazer backup por conta própria.\n\n",
    "limpar_os_dados_do_navegador_desinstal": "Se os dados do navegador forem limpos, o aplicativo for desinstalado, você trocar de celular ou o aparelho apresentar defeito, não será possível recuperar o progresso, os grifos, as citações, as notas e os marcadores.\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "A sua estante existe só neste aparelho. Não há cópia em servidor nenhum, e por isso não há como recuperá-la para você.\n\n",
    "leia_antes_de_confirmar": "Leia antes de confirmar",
    "desligar_os_lembretes_de_backup": "Desligar os lembretes de backup?",
    "progresso_de_leitura_restaurado_neste": "Progresso de leitura restaurado neste livro.",
    "pronto": "Pronto.",
    "aplicando_as_suas_preferencias": "Aplicando as suas preferências...",
    "atualize_o_veredas_reader_e_tente_de_n": "Atualize o Veredas Reader e tente de novo.",
    "este_backup_foi_feito_numa_versao_mais": "Este backup foi feito numa versão mais nova do aplicativo.",
    "este_arquivo_nao_e_um_backup_de_biblio": "Este arquivo não é um backup de biblioteca do Veredas.",
    "o_conteudo_interno_nao_pode_ser_lido": "O conteúdo interno não pôde ser lido.",
    "o_backup_esta_corrompido": "O backup está corrompido.",
    "falta_o_arquivo_biblioteca_json_la_den": "Falta o arquivo biblioteca.json lá dentro.",
    "este_arquivo_nao_parece_ser_um_backup": "Este arquivo não parece ser um backup do Veredas.",
    "compactando": "Compactando...",
    "para_restaurar_menu_lateral_backup_e_r": "Para restaurar: menu lateral > Backup e restauração > Restaurar backup.",
    "o_veredas_devolve_sozinho_as_marcacoes": "o Veredas restaura automaticamente as marcações e o ponto onde você parou.",
    "importe_os_livros_normalmente_no_aplic": "importe os livros normalmente no aplicativo: ao reconhecer cada arquivo,",
    "ele_nao_contem_os_arquivos_dos_livros": "Ele NÃO contém os arquivos dos livros. Para restaurar por completo,",
    "as_notas_os_marcadores_e_a_organizacao": "as notas, os marcadores e a organização da sua estante.",
    "este_arquivo_guarda_o_seu_progresso_de": "Este arquivo guarda o seu progresso de leitura, os grifos, as citações,",
    "verificando_se_sao_partes_do_mesmo_aud": "Verificando se são partes do mesmo audiolivro...",
    "analisando_os_arquivos": "Analisando os arquivos",
    "nao_foi_possivel_salvar_o_audiolivro": "Não foi possível salvar o audiolivro.",
    "audiolivros_grandes_podem_levar_alguns": "Audiolivros grandes podem levar alguns instantes...",
    "salvando_na_sua_estante": "Salvando na sua estante",
    "falha_ao_processar_os_arquivos": "Falha ao processar os arquivos.",
    "falha_ao_processar_o_arquivo": "Falha ao processar o arquivo.",
    "nao_foi_possivel_salvar_o_quadrinho": "Não foi possível salvar o quadrinho.",
    "quase_la": "Quase lá...",
    "falha_ao_processar_o_quadrinho": "Falha ao processar o quadrinho.",
    "autor_desconhecido": "Autor Desconhecido",
    "lendo_o_quadrinho": "Lendo o quadrinho...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "Não foi possível salvar o livro na biblioteca.",
    "nao_foi_possivel_ler_o_pdf": "Não foi possível ler o PDF.",
    "lendo_o_pdf": "Lendo o PDF...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "Se for um .doc antigo, abra no Word e salve como .docx antes de importar.",
    "este_arquivo_nao_e_um_docx_valido": "Este arquivo não é um .docx válido.",
    "livros_com_protecao_da_amazon_nao_pode": "Livros com proteção da Amazon não podem ser abertos aqui. Use uma cópia sem DRM ou converta o livro para EPUB.",
    "este_arquivo_esta_protegido_por_drm": "Este arquivo está protegido por DRM.",
    "confira_se_a_extensao_corresponde_ao_c": "Confira se a extensão corresponde ao conteúdo ou converta o livro para EPUB.",
    "este_arquivo_nao_e_um_mobi_valido": "Este arquivo não é um MOBI válido.",
    "nao_foi_possivel_ler_o_arquivo": "Não foi possível ler o arquivo.",
    "formato_nao_suportado": "Formato não suportado.",
    "falha_ao_salvar_o_livro_na_biblioteca": "Falha ao salvar o livro na biblioteca.",
    "livro_importado_e_salvo_no_dispositivo": "Livro importado e salvo no dispositivo.",
    "audiolivro_importado_e_salvo_no_dispos": "Audiolivro importado e salvo no dispositivo.",
    "quadrinho_importado_e_salvo_no_disposi": "Quadrinho importado e salvo no dispositivo.",
    "salvando_na_sua_estante_2": "Salvando na sua estante...",
    "importando_livro": "Importando livro",
    "importar_mesmo_assim": "Importar mesmo assim",
    "parece_que_este_livro_ja_esta_na_estan": "Parece que este livro já está na estante",
    "este_livro_ja_esta_na_estante": "Este livro já está na estante",
    "video_importado_e_salvo_no_dispositivo": "Vídeo importado e salvo no dispositivo.",
    "importacao_cancelada": "Importação cancelada.",
    "preparando_o_arquivo": "Preparando o arquivo",
    "importando_audiolivro": "Importando audiolivro",
    "importacao_concluida": "Importação concluída",
    "importacao_interrompida": "Importação interrompida",
    "a_importacao_foi_interrompida_o_que_ja": "A importação foi interrompida; o que já tinha entrado continua na estante.",
    "finalizando": "Finalizando…",
    "nao_foi_possivel_ler_o_arquivo_2": "não foi possível ler o arquivo",
    "importando_livros": "Importando livros",
    "livros_quadrinhos_documentos_audiolivr": "Livros, quadrinhos, documentos, audiolivros e vídeos",
    "series": "Séries",
    "colecoes": "Coleções",
    "organizacao_salva": "Organização salva.",
    "informe_um_nome_para_o_livro_antes_de": "Informe um nome para o livro antes de salvar.",
    "nome_do_livro_obrigatorio": "Nome do livro obrigatório",
    "importe_um_livro_primeiro": "Importe um livro primeiro.",
    "citacao": "citação",
    "anotacao": "anotação",
    "citacao_2": "Citação",
    "anotacao_2": "Anotação",
    "uma_citacao": "uma citação",
    "uma_anotacao": "uma anotação",
    "o_marcador_sera_removido_da_biblioteca": "O marcador será removido da biblioteca, mas o arquivo do livro permanecerá intacto.",
    "marcador_de_audio": "Marcador de áudio",
    "marcador_de_video": "Marcador de vídeo",
    "nao_foi_possivel_excluir_o_livro": "Não foi possível excluir o livro.",
    "livro_excluido_da_biblioteca": "Livro excluído da biblioteca.",
    "excluir_livro": "Excluir livro",
    "isso_remove_apenas_a_copia_armazenada": "Isso remove apenas a cópia armazenada pela biblioteca, além do progresso, marcadores e anotações. O arquivo original na sua pasta não será apagado.",
    "excluir_livro_2": "Excluir livro?",
    "ordem_personalizada_salva": "Ordem personalizada salva.",
    "ordem_manual_da_sua_estante": "Ordem manual da sua estante.",
    "agrupamento_alterado_para_minha_ordem": "Agrupamento alterado para Minha Ordem.",
    "nova_ordem_salva": "Nova ordem salva.",
    "nao_foi_possivel_salvar_a_nova_ordem": "Não foi possível salvar a nova ordem.",
    "baixar_automaticamente": "Baixar automaticamente",
    "escolha_livremente_onde_o_arquivo_sera": "Escolha livremente onde o arquivo será gravado.",
    "salvar_epub": "Salvar EPUB",
    "livro_epub": "Livro EPUB",
    "erro_desconhecido": "erro desconhecido",
    "a_permissao_para_salvar_o_arquivo_foi": "A permissão para salvar o arquivo foi cancelada. Nenhum item da biblioteca foi alterado.",
    "conversao_cancelada_o_pdf_original_per": "Conversão cancelada. O PDF original permanece na biblioteca.",
    "preparando_salvamento": "Preparando salvamento…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "A cópia do PDF não está disponível na biblioteca.",
    "reconstruindo_o_livro_localmente": "Reconstruindo o livro localmente.",
    "convertendo_pdf": "Convertendo PDF",
    "nao_foi_possivel_compartilhar_o_livro": "Não foi possível compartilhar o livro.",
    "o_arquivo_foi_preparado_para_voce_comp": "O arquivo foi preparado para você compartilhar em outro aplicativo.",
    "livro_compartilhado": "Livro compartilhado.",
    "a_copia_deste_livro_nao_esta_disponive": "A cópia deste livro não está disponível na biblioteca.",
    "para_manter_a_politica_de_compartilham": "Para manter a política de compartilhamento da biblioteca, arquivos EPUB e MOBI não podem ser compartilhados por este aplicativo.",
    "quadrinhos_ficam_guardados_somente_no": "Quadrinhos ficam guardados somente no seu aparelho e não podem ser compartilhados por este aplicativo.",
    "audiolivros_e_videos_ficam_guardados_s": "Audiolivros e vídeos ficam guardados somente no seu aparelho e não podem ser compartilhados por este aplicativo.",
    "formato_protegido": "Formato protegido",
    "compartilhamento_indisponivel": "Compartilhamento indisponível",
    "concluido": "Concluído",
    "ainda_nao_comecado": "Ainda não começado",
    "continue_lendo": "Continue lendo",
    "continue_ouvindo": "Continue ouvindo",
    "continue_assistindo": "Continue assistindo",
    "comece_por_aqui": "Comece por aqui",
    "comece_a_ouvir": "Comece a ouvir",
    "comece_a_assistir": "Comece a assistir",
    "no_total": "no total",
    "para_ler": "para ler",
    "sua_estante": "Sua estante",
    "livros_organizados_pela_opcao_selecion": "Livros organizados pela opção selecionada.",
    "uma_prateleira_para_cada_tipo_de_arqui": "Uma prateleira para cada tipo de arquivo.",
    "autores_agrupados_em_ordem_alfabetica": "Autores agrupados em ordem alfabética.",
    "toque_para_continuar_de_onde_parou": "Toque para continuar de onde parou.",
    "para_ler_2": "Para ler",
    "lendo_agora": "Lendo agora",
    "audio_e_video": "Áudio e vídeo",
    "trechos_salvos_separadamente_dos_marca": "Trechos salvos separadamente dos marcadores.",
    "comentarios_vinculados_a_trechos_selec": "Comentários vinculados a trechos selecionados.",
    "paginas_salvas_para_voltar_rapidamente": "Páginas salvas para voltar rapidamente.",
    "do_maior_para_o_menor_progresso_de_lei": "Do maior para o menor progresso de leitura.",
    "livros_adicionados_ou_lidos_mais_recen": "Livros adicionados ou lidos mais recentemente.",
    "ordem_alfabetica_pelo_titulo": "Ordem alfabética pelo título.",
    "separa_em_prateleiras_de_epub_pdf_docx": "Separa em prateleiras de EPUB, PDF, DOCX, audiolivros, vídeos…",
    "tipo_de_arquivo": "Tipo de arquivo",
    "organiza_e_separa_os_livros_por_autor": "Organiza e separa os livros por autor.",
    "agrupar_por_autor": "Agrupar por Autor",
    "pressione_o_livro_e_mova_o": "Pressione o livro e mova-o.",
    "minha_ordem": "Minha Ordem",
    "epub_pronto": "EPUB pronto",
    "conversao_concluida": "Conversão concluída",
    "necessario_para_salvar_o_epub_ao_lado": "Necessário para salvar o EPUB ao lado do original",
    "escolha_a_pasta_do_pdf": "Escolha a pasta do PDF",
    "processando": "Processando…",
    "processamento_local_no_navegador": "Processamento local no navegador",
    "convertendo_livro": "Convertendo livro",
    "livro_em_pdf": "Livro em PDF",
    "recalculando_paginas": "Recalculando páginas...",
    "ajustando_leitura": "Ajustando leitura",
    "abrir_comentario": "Abrir comentário",
    "anotacao_salva": "Anotação salva.",
    "anotacao_atualizada": "Anotação atualizada.",
    "escreva_uma_nota_antes_de_salvar": "Escreva uma nota antes de salvar.",
    "nao_foi_possivel_compartilhar": "Não foi possível compartilhar.",
    "compartilhamento_indisponivel_2": "Compartilhamento indisponível.",
    "trecho_copiado": "Trecho copiado.",
    "trecho_compartilhado": "Trecho compartilhado.",
    "citacao_salva": "Citação salva.",
    "trecho_grifado": "Trecho grifado.",
    "grifo_removido": "Grifo removido.",
    "comentario_apagado": "Comentário apagado.",
    "remover_grifo": "Remover grifo",
    "apagar_comentario": "Apagar comentário",
    "remover_grifo_2": "Remover grifo?",
    "apagar_comentario_2": "Apagar comentário?",
    "remover_este_grifo": "Remover este grifo?",
    "apagar_este_comentario": "Apagar este comentário?",
    "sem_comentario": "Sem comentário",
    "comentario": "Comentário",
    "marcador_removido_desta_pagina": "Marcador removido desta página.",
    "pagina_adicionada_aos_marcadores": "Página adicionada aos marcadores.",
    "este_e_o_inicio_do_livro": "Este é o início do livro.",
    "esta_e_a_primeira_pagina": "Esta é a primeira página.",
    "voce_chegou_ao_fim_do_livro": "Você chegou ao fim do livro.",
    "voce_chegou_ao_fim_do_quadrinho": "Você chegou ao fim do quadrinho.",
    "agora_em_revista_aberta_duas_paginas_l": "Agora em revista aberta: duas páginas lado a lado, com a capa sozinha.",
    "leitura_horizontal_ativada_neste_livro": "Leitura horizontal ativada neste livro.",
    "rolagem_vertical_ativada_neste_livro": "Rolagem vertical ativada neste livro.",
    "leitura_pagina_a_pagina_ativada_neste": "Leitura página a página ativada neste quadrinho.",
    "rolagem_continua_ativada_neste_quadrin": "Rolagem contínua ativada neste quadrinho.",
    "mudar_para_rolagem_vertical": "Mudar para rolagem vertical",
    "mudar_para_leitura_horizontal": "Mudar para leitura horizontal",
    "rolagem_continua_estilo_webtoon": "Rolagem contínua (estilo webtoon)",
    "voltar_para_pagina_a_pagina": "Voltar para página a página",
    "separando_os_capitulos": "Separando os capítulos...",
    "lendo_o_livro": "Lendo o livro",
    "lendo_o_markdown": "Lendo o Markdown",
    "lendo_o_documento": "Lendo o documento",
    "pagina_indisponivel": "Página indisponível.",
    "isto_acontece_so_desta_vez": "Isto acontece só desta vez.",
    "preparando_o_quadrinho": "Preparando o quadrinho",
    "abrindo_o_quadrinho": "Abrindo o quadrinho...",
    "montando_as_paginas": "Montando as páginas...",
    "nao_foi_possivel_abrir_este_livro": "Não foi possível abrir este livro.",
    "abertura_cancelada": "Abertura cancelada.",
    "o_livro_demorou_demais_para_abrir_e_fo": "O livro demorou demais para abrir e foi interrompido.",
    "importe_o_arquivo_novamente_para_conti": "Importe o arquivo novamente para continuar a leitura.",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "O arquivo deste livro não está mais salvo no aparelho.",
    "preparando_sua_leitura": "Preparando sua leitura...",
    "abrindo_livro": "Abrindo livro",
    "leitura_concluida": "Leitura concluída.",
    "a_voz_foi_interrompida_pelo_navegador": "A voz foi interrompida pelo navegador.",
    "nao_foi_possivel_preparar_este_trecho": "Não foi possível preparar este trecho para áudio.",
    "a_leitura_em_voz_alta_nao_e_suportada": "A leitura em voz alta não é suportada neste navegador.",
    "pausar_leitura": "Pausar leitura",
    "em_pausa": "Em pausa",
    "leitura_em_voz_alta_nao_disponivel_nes": "Leitura em voz alta não disponível neste navegador",
    "nome_do_marcador": "Nome do marcador",
    "o_marcador_sera_removido_deste_audioli": "O marcador será removido deste audiolivro.",
    "nao_foi_possivel_salvar_o_marcador": "Não foi possível salvar o marcador.",
    "ja_existe_um_marcador_neste_ponto": "Já existe um marcador neste ponto.",
    "timer_de_sono_encerrado": "Timer de sono encerrado.",
    "fim_do_cap": "Fim do cap.",
    "timer_desativado": "Timer desativado.",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "O áudio vai pausar ao fim do capítulo.",
    "este_audiolivro_nao_tem_capitulos": "Este audiolivro não tem capítulos.",
    "ao_fim_do_capitulo": "Ao fim do capítulo",
    "desativar_timer": "Desativar timer",
    "mais_10_minutos_no_timer": "Mais 10 minutos no timer.",
    "somar_10_minutos": "Somar 10 minutos",
    "pausa_ao_fim_do_capitulo": "Pausa ao fim do capítulo",
    "no_livro_todo": "No livro todo",
    "video": "Vídeo",
    "audiolivro_concluido": "Audiolivro concluído.",
    "video_concluido": "Vídeo concluído.",
    "video_2": "vídeo",
    "audio": "áudio",
    "toque_em_reproduzir_para_comecar": "Toque em reproduzir para começar.",
    "falha_ao_carregar_o_audio": "Falha ao carregar o áudio.",
    "exclua_o_da_biblioteca_e_importe_o_arq": "Exclua-o da biblioteca e importe o arquivo novamente.",
    "os_nomes_dos_arquivos_seguem_uma_seque": "Os nomes dos arquivos seguem uma sequência, então parecem ser capítulos de um mesmo audiolivro.",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "Os arquivos têm o mesmo álbum nas etiquetas, então parecem ser capítulos de um mesmo audiolivro.",
    "libere_espaco_ou_exclua_livros_da_bibl": "Libere espaço ou exclua livros da biblioteca e tente novamente.",
    "o_armazenamento_do_aparelho_esta_cheio": "O armazenamento do aparelho está cheio.",
    "preparando_a_capa": "Preparando a capa...",
    "remova_esse_arquivo_da_selecao_e_tente": "Remova esse arquivo da seleção e tente de novo.",
    "sequencia": "sequência",
    "o_arquivo_pode_estar_incompleto_tente": "O arquivo pode estar incompleto. Tente baixá-lo novamente.",
    "conferindo_se_o_audio_pode_ser_reprodu": "Conferindo se o áudio pode ser reproduzido...",
    "conferindo_se_o_video_pode_ser_reprodu": "Conferindo se o vídeo pode ser reproduzido...",
    "lendo_titulo_capitulos_e_capa": "Lendo título, capítulos e capa...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "O arquivo pode estar danificado ou num formato de áudio que o navegador não reproduz. Tente convertê-lo para MP3 ou M4B (AAC).",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "O arquivo pode estar danificado ou num formato de vídeo que o navegador não reproduz. Tente convertê-lo para MP4 com vídeo H.264 e áudio AAC.",
    "converta_o_audiolivro_para_m4b_com_aud": "Converta o audiolivro para M4B com áudio AAC (ou para MP3) e importe novamente.",
    "converta_o_video_para_mp4_com_audio_aa": "Converta o vídeo para MP4 com áudio AAC e vídeo H.264 e importe novamente.",
    "o_navegador_nao_reproduz_o_formato_de": "O navegador não reproduz o formato de áudio deste arquivo.",
    "arquivos_com_protecao_nao_podem_ser_re": "Arquivos com proteção não podem ser reproduzidos aqui. Use uma cópia sem DRM.",
    "nao_ha_espaco_suficiente_no_aparelho_p": "Não há espaço suficiente no aparelho para este audiolivro.",
    "confira_se_a_extensao_corresponde_ao_c_2": "Confira se a extensão corresponde ao conteúdo ou converta o áudio para MP3 ou M4B (AAC).",
    "imagem_invalida": "imagem inválida",
    "imagem_demorou_demais": "a imagem demorou demais para carregar",
    "imagem_vazia": "imagem vazia",
    "inicio": "Início",
    "mp4_moov_nao_encontrado": "O vídeo parece incompleto ou danificado.",
    "pagina": "Página",
    "esta_pagina_nao_esta_disponivel": "Esta página não está disponível.",
    "esta_pagina_nao_pode_ser_descompactada": "Esta página não pôde ser descompactada.",
    "quadrinho_fechado": "Quadrinho fechado.",
    "ele_pode_estar_incompleto_dividido_em": "Ele pode estar incompleto, dividido em várias partes ou em uma variação de RAR que o aplicativo não reconhece. Converter para CBZ resolve.",
    "remova_a_senha_do_arquivo_e_importe_de": "Remova a senha do arquivo e importe de novo.",
    "nao_foi_possivel_ler_este_arquivo_de_q": "Não foi possível ler este arquivo de quadrinho.",
    "este_quadrinho_esta_protegido_por_senh": "Este quadrinho está protegido por senha.",
    "lendo_o_indice_do_quadrinho": "Lendo o índice do quadrinho...",
    "o_arquivo_pode_ser_grande_demais_para": "O arquivo pode ser grande demais para a memória deste aparelho. Dividir o quadrinho em partes menores costuma resolver.",
    "nao_foi_possivel_abrir_este_quadrinho": "Não foi possível abrir este quadrinho.",
    "lendo_o_arquivo": "Lendo o arquivo...",
    "preparando_o_leitor_de_cbr": "Preparando o leitor de CBR...",
    "o_arquivo_pode_estar_incompleto_proteg": "O arquivo pode estar incompleto, protegido por senha ou corrompido.",
    "nao_foi_possivel_ler_este_quadrinho": "Não foi possível ler este quadrinho.",
    "o_arquivo_precisa_conter_imagens_jpg_p": "O arquivo precisa conter imagens (JPG, PNG, WEBP ou GIF).",
    "nao_encontramos_paginas_dentro_deste_q": "Não encontramos páginas dentro deste quadrinho.",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "Não há espaço suficiente no aparelho para este quadrinho.",
    "cabecalho_de_item_invalido": "Parte do arquivo está danificada.",
    "a_pasta_vendor_libarchive_precisa_esta": "Falta um componente do aplicativo para abrir este quadrinho. Converta-o para CBZ ou reinstale o aplicativo.",
    "o_leitor_de_cbr_nao_foi_encontrado": "O leitor de CBR não foi encontrado.",
    "converta_o_quadrinho_para_cbz_zip_e_im": "Converta o quadrinho para CBZ (ZIP) e importe novamente.",
    "este_navegador_nao_consegue_abrir_arqu": "Este navegador não consegue abrir arquivos CBR.",
    "convertendo_o_markdown": "Convertendo o Markdown",
    "lendo_o_texto": "Lendo o texto",
    "pdf_indisponivel": "PDF indisponível.",
    "epub_invalido_nenhum_capitulo_no_spine": "Este EPUB está danificado: não encontramos os capítulos do livro.",
    "livro_sem_titulo": "Livro Sem Título",
    "epub_invalido_arquivo_opf_nao_encontra": "Este EPUB está incompleto ou danificado e não pode ser aberto.",
    "epub_invalido_container_xml_nao_encont": "Este EPUB está incompleto ou danificado e não pode ser aberto.",
    "organizando_o_texto": "Organizando o texto",
    "descompactando_o_livro": "Descompactando o livro",
    "nao_encontramos_conteudo_para_exibir_n": "Não encontramos conteúdo para exibir neste arquivo.",
    "livro_sem_texto_legivel": "Livro sem texto legível",
    "o_arquivo_pode_estar_corrompido_tente": "O arquivo pode estar corrompido. Tente convertê-lo para EPUB.",
    "nao_foi_possivel_extrair_o_texto_deste": "Não foi possível extrair o texto deste MOBI.",
    "nenhum_registro_de_conteudo_foi_encont": "Não encontramos o texto do livro neste arquivo.",
    "arquivo_mobi_sem_texto": "Arquivo MOBI sem texto.",
    "o_dicionario_de_compressao_esta_vazio": "Parte do conteúdo deste MOBI está faltando.",
    "arquivo_mobi_incompleto": "Arquivo MOBI incompleto.",
    "as_tabelas_de_compressao_nao_foram_enc": "Parte do conteúdo deste MOBI está faltando.",
    "converta_o_arquivo_para_epub_em_um_pro": "Converta o arquivo para EPUB em um programa como o Calibre e importe novamente.",
    "compressao_mobi_nao_reconhecida": "Este MOBI usa um formato interno que o aplicativo não reconhece.",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "O cabeçalho do livro não pôde ser lido.",
    "arquivo_mobi_corrompido": "Arquivo MOBI corrompido.",
    "a_lista_interna_de_registros_esta_inco": "O arquivo está incompleto. Tente baixá-lo ou convertê-lo novamente.",
    "o_download_parece_ter_sido_interrompid": "O download parece ter sido interrompido. Baixe o arquivo novamente.",
    "tabela_de_compressao_mobi_corrompida": "Parte deste arquivo MOBI está danificada.",
    "tabela_de_compressao_mobi_incompleta": "Este arquivo MOBI está incompleto.",
    "tabela_de_compressao_mobi_invalida": "Parte deste arquivo MOBI está danificada.",
    "este_arquivo_docx_nao_tem_conteudo_de": "Este arquivo .docx não tem conteúdo de texto que possa ser exibido.",
    "documento_sem_texto": "Documento sem texto",
    "o_arquivo_pode_estar_corrompido_proteg": "O arquivo pode estar corrompido, protegido por senha ou ser um .doc antigo. Salve-o novamente como .docx e importe de novo.",
    "nao_foi_possivel_ler_este_arquivo_docx": "Não foi possível ler este arquivo DOCX.",
    "convertendo_o_documento": "Convertendo o documento",
    "conecte_se_a_internet_uma_vez_para_bai": "Conecte-se à internet uma vez para baixar o componente e abra o livro novamente.",
    "o_conversor_de_docx_nao_carregou": "O conversor de DOCX não carregou.",
    "video_mp4": "Vídeo (MP4)",
    "audiolivro_m4b": "Audiolivro (M4B)",
    "audiolivro_mp3": "Audiolivro (MP3)",
    "quadrinho_cbt": "Quadrinho (CBT)",
    "quadrinho_cb7": "Quadrinho (CB7)",
    "quadrinho_cbr": "Quadrinho (CBR)",
    "quadrinho_cbz": "Quadrinho (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "Texto (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "Gravação cancelada.",
    "o_arquivo_esta_vindo_do_armazenamento": "O arquivo está vindo do armazenamento em nuvem para o seu aparelho.",
    "baixando_o_arquivo": "Baixando o arquivo",
    "cancelando": "Cancelando...",
    "use_grifar_citacao_anotar_ou_marcador": "Use Grifar, Citação, Anotar ou Marcador durante a leitura.",
    "nenhuma_marcacao_ainda": "Nenhuma marcação ainda",
    "trecho_original": "Trecho original",
    "procurar_meus_livros": "Procurar meus livros",
    "a_busca_fica_sempre_disponivel_no_menu": "A busca fica sempre disponível no menu lateral, em Sistema.",
    "da_para_fazer_depois": "Dá para fazer depois",
    "nada_entra_na_estante_sem_a_sua_confir": "Nada entra na estante sem a sua confirmação: você vê a lista e marca o que quer importar.",
    "voce_revisa_antes": "Você revisa antes",
    "escolha_uma_pasta_downloads_e_um_bom_c": "Escolha uma pasta (Downloads é um bom começo) e o aplicativo procura nela e em todas as subpastas.",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "Busca por EPUB, MOBI, CBZ, CBR e M4B",
    "voltar_e_revisar": "Voltar e revisar",
    "ler_os_termos": "Ler os termos",
    "ler_a_politica": "Ler a política",
    "os_dois_documentos_ficam_sempre_dispon": "Os dois documentos ficam sempre disponíveis no menu lateral, em Sobre.",
    "leia_com_calma": "Leia com calma",
    "a_politica_e_os_termos_explicam_como_o": "A política e os termos explicam como o aplicativo guarda seus livros e o que você pode fazer com eles. Para usar a biblioteca, é preciso concordar com eles.",
    "nada_acontece_sem_o_aceite": "Para começar, é preciso aceitar os termos",
    "aceitar_e_continuar": "Aceitar e continuar",
    "nao_aceito": "Não aceito",
    "termos_de_uso_2": "Termos de Uso",
    "politica_de_privacidade_2": "Política de Privacidade",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "O aplicativo só acessa os arquivos e pastas que você escolher, quando você escolher.",
    "voce_no_controle": "Você no controle",
    "depois_de_importar_um_livro_voce_le_se": "Depois de importar um livro, você lê sem internet.",
    "funciona_offline": "Funciona offline",
    "livros_marcacoes_e_progresso_sao_guard": "Livros, marcações e progresso são guardados localmente. Nada é enviado para servidores nossos.",
    "tudo_fica_no_seu_aparelho": "Tudo fica no seu aparelho",
    "escolha_o_que_deseja_adicionar_a_bibli": "Escolha o que deseja adicionar à biblioteca. Arquivos idênticos aos que já estão na estante são ignorados automaticamente.",
    "voce_pode_tentar_outra_pasta_ou_import": "Você pode tentar outra pasta ou importar os arquivos pelo botão +.",
    "a_leitura_acontece_so_no_seu_dispositi": "A leitura acontece só no seu dispositivo.",
    "voce_escolhe_a_pasta": "Você escolhe a pasta",
    "tema_tipografia_margens_modo_de_virada": "Tema, tipografia, margens, modo de virada e ajustes de áudio.",
    "restaurar_minhas_preferencias": "Restaurar minhas preferências",
    "o_backup_manda_as_marcacoes_atuais_dos": "O backup manda. As marcações atuais dos livros que estiverem no arquivo serão trocadas pelas do backup.",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "Nada é apagado. As marcações dos dois lados se somam e o progresso mais recente prevalece.",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "O que fazer com o que já está na estante",
    "grifos_citacoes_e_notas": "grifos, citações e notas",
    "preparando_o_arquivo_2": "Preparando o arquivo...",
    "os_livros_em_si_nem_as_capas_por_isso": "Nem os livros em si, nem as capas — por isso o arquivo tem só alguns KB. Quem receber precisa ter os arquivos dos livros para que as marcações voltem ao lugar, e as capas reaparecem automaticamente na importação.",
    "nao_vai_no_arquivo": "Não vai no arquivo",
    "o_seu_progresso_de_leitura_os_grifos_a": "O seu progresso de leitura, os grifos, as citações, as notas, os marcadores e a organização da estante — status, favoritos, coleções, séries e tags.",
    "vai_no_arquivo": "Vai no arquivo",
    "descartar_o_que_esta_esperando_2": "Apagar dados em espera",
    "esperando_o_arquivo": "Esperando o arquivo",
    "avisar_quando_fizer_tempo_sem_backup": "Avisar quando fizer tempo sem backup",
    "livros_que_ainda_nao_estiverem_na_esta": "Livros que ainda não estiverem na estante ficam em espera: quando você importar o arquivo deles, as marcações voltam automaticamente.",
    "restaurar_backup": "Restaurar backup",
    "salvar_backup": "Salvar backup",
    "ainda_nao_ha_itens": "Ainda não há itens",
    "arraste_um_livro_para_outra_posicao_na": "Arraste um livro para outra posição na estante para salvar uma ordem manual. A ordem manual passa a ter prioridade sobre o agrupamento por autor.",
    "separe_por_virgulas": "Separe por vírgulas",
    "ex_estudos_ficcao": "Ex.: Estudos, Ficção...",
    "pasta_estante": "Pasta / estante",
    "ex_trilogia": "Ex.: Trilogia...",
    "serie": "Série",
    "aparece_em_favoritos": "Aparece em Favoritos.",
    "nome_do_livro": "Nome do livro",
    "nenhum_registro_ainda": "Nenhum registro ainda",
    "no_leitor_toque_no_icone_de_marcador_p": "No leitor, toque no ícone de marcador para salvar a página.",
    "nenhum_marcador_ainda": "Nenhum marcador ainda",
    "a_gravacao_e_independente_da_localizac": "A gravação é independente da localização do PDF e não altera o arquivo original.",
    "o_pdf_original_nao_precisa_estar_nessa": "O PDF original não precisa estar nessa pasta",
    "excluir_da_biblioteca": "Excluir da biblioteca",
    "adicionar_livro": "Adicionar livro",
    "adicione_livros_e_acompanhe_o_que_esta": "Adicione livros e acompanhe o que está por ler, o que está em andamento e seu progresso.",
    "tudo_pronto_para_a_proxima_leitura": "Tudo pronto para a próxima leitura.",
    "sua_biblioteca": "Sua biblioteca",
    "arraste_um_livro_para_reposiciona_lo_a": "Arraste um livro para reposicioná-lo: a estante passa para Minha Ordem e guarda a sequência.",
    "importe_um_livro_ou_ajuste_seus_filtro": "Importe um livro ou ajuste seus filtros de organização.",
    "nada_por_aqui_ainda": "Nada por aqui ainda",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "Toque em + e escolha arquivos MP3, M4B ou MP4. Vários MP3 de capítulos podem virar um único audiolivro.",
    "nada_para_ouvir_ou_assistir_ainda": "Nada para ouvir ou assistir ainda",
    "o_pdf_original_permanece_intacto_na_pa": "O PDF original permanece intacto na sua pasta.",
    "paginas_como_imagem": "Páginas como imagem",
    "paginas_do_pdf": "Páginas do PDF",
    "em_navegadores_sem_suporte_a_acesso_di": "Em navegadores sem suporte a acesso direto ao sistema de arquivos, o EPUB será baixado como alternativa.",
    "essa_permissao_e_dada_somente_a_esta_a": "Essa permissão é dada somente a esta aplicação e evita que o arquivo original seja alterado.",
    "selecione_a_pasta_que_contem_o_pdf": "Selecione a pasta que contém o PDF",
    "preparando": "Preparando…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "O arquivo está sendo lido e reconstruído. Livros grandes podem levar alguns instantes.",
    "revistas_apostilas_complexas_formulari": "Revistas, apostilas complexas, formulários, documentos com muitas tabelas ou PDFs escaneados podem perder parte do layout original.",
    "funcionalidade_indicada_apenas_para_li": "Funcionalidade indicada apenas para livros",
    "o_epub_e_melhor_para_livros_com_texto": "O EPUB é melhor para livros com texto selecionável, porque permite ajustar fonte, tamanho, margens e modo de leitura.",
    "trecho_selecionado": "Trecho selecionado",
    "trecho_comentado": "Trecho comentado",
    "aplicando_zoom": "Aplicando zoom...",
    "nao_foi_possivel_carregar_esta_pagina": "Não foi possível carregar esta página.",
    "nomear_marcador": "Nomear marcador",
    "toque_em_marcar_agora_para_guardar_est": "Toque em “Marcar agora” para guardar este ponto e voltar a ele quando quiser.",
    "timer_ativo": "Timer ativo",
    "trecho_ausente_ou_corrompido_no_arquiv": "[Trecho ausente ou corrompido no arquivo original]",
    "novos_livros_vao_abrir_em_leitura_v": "Novos livros vão abrir em leitura {v}.",
    "leitura_efetivo_aplicada_a_este_livro": "Leitura {efetivo} aplicada a este livro.",
    "automatico_neste_livro_leitura_efetivo": "Automático neste livro: leitura {efetivo}.",
    "agora_esta_em_efetivo_no_automatico_fo": "Agora está em {efetivo}; no automático, {format} abre em {padrao}.",
    "esta_escolha_vale_so_para_v_cada_livro": "Esta escolha vale só para “{v}”. Cada livro guarda o seu sentido de rolagem.",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} ainda não estão na sua estante.",
    "escolha_uma_pasta_para_procurar_label": "Escolha uma pasta para procurar {label}.",
    "subtitle_versao_build": "{subtitle} · versão {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "Não foi possível ler {path}; usando o texto embutido.",
    "seu_ultimo_backup_foi_ha_dias_dias": "Seu último backup foi há {dias} dias",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "{aguardando} livro do backup ainda não está aqui. O progresso e as marcações dele ficaram guardados: assim que você importar o arquivo, tudo volta automaticamente para o lugar.",
      "other": "{aguardando} livros do backup ainda não estão aqui. O progresso e as marcações deles ficaram guardados: assim que você importar cada arquivo, tudo volta automaticamente para o lugar."
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "{atualizados} livro da sua estante foi atualizado.",
      "other": "{atualizados} livros da sua estante foram atualizados."
    },
    "criado_em_quando": "Criado em {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "Backup pronto: {livros} livro(s) e {marcacoes} marcação(ões).",
    "endereco_seguro_seguro": "endereço seguro: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "Progresso e {marcas} marcação restaurados neste livro.",
      "other": "Progresso e {marcas} marcações restaurados neste livro."
    },
    "restaurando_v_de_length": "Restaurando ({v} de {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} livro(s) · {marcacoes} marcação(ões)",
    "criado_em_v": "Criado em {v}",
    "reunindo_a_sua_estante_v_de_length": "Reunindo a sua estante ({v} de {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "“{titulo}” já foi importado antes e continua disponível na sua biblioteca. Nenhuma cópia nova foi criada.",
    "length_arquivos_de_audio": "{length} arquivos de áudio...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "{falhas} arquivo não pôde ser lido.",
      "other": "{falhas} arquivos não puderam ser lidos."
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} já estavam na biblioteca e foram ignorados.",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "{importados} livro adicionado à estante.",
      "other": "{importados} livros adicionados à estante."
    },
    "epub_salvo_em_filename": "EPUB salvo em {fileName}.",
    "falha_ao_converter_o_pdf_v": "Falha ao converter o PDF: {v}",
    "pagina_page_de_totalpages": "Página {page} de {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} página",
      "other": "{totalPages} páginas"
    },
    "length_resultado_s_para_search": {
      "one": "{length} resultado para “{search}”",
      "other": "{length} resultados para “{search}”"
    },
    "capitulo_v": "Capítulo {v}",
    "organizando_capitulo_v_de_totalchapter": "Organizando capítulo {v} de {totalChapters}",
    "pagina_v": "Página {v}",
    "paginas_v_v2": "Páginas {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} página pronta",
      "other": "{length} páginas prontas"
    },
    "montando_as_paginas_pagessofar_prontas": "Montando as páginas — {pagesSoFar} prontas",
    "lendo_pagina_v_de_length": "Lendo página {v} de {length}",
    "marcador_salvo_em_t": "Marcador salvo em {t}.",
    "o_audio_vai_pausar_em_minutes_minutos": "O áudio vai pausar em {minutes} minutos.",
    "length_capitulos_toque_para_ir_direto": "{length} capítulos · toque para ir direto ao ponto.",
    "narrado_por_narrator": "Narrado por {narrator}",
    "velocidade_de_reproducao_rate": "Velocidade de reprodução: {rate}",
    "avancar_f_segundos": "Avançar {f} segundos",
    "nao_foi_possivel_abrir_este_v": "Não foi possível abrir este {v}.",
    "nao_foi_possivel_ler_o_arquivo_de_v": "Não foi possível ler o arquivo de {v}.",
    "o_v_esta_danificado_neste_ponto": "O {v} está danificado neste ponto.",
    "o_navegador_nao_consegue_reproduzir_es": "O navegador não consegue reproduzir este arquivo de {v}.",
    "nao_foi_possivel_reproduzir_este_v": "Não foi possível reproduzir este {v}.",
    "os_dados_deste_noun_estao_incompletos": "Os dados deste {noun} estão incompletos.",
    "importe_o_arquivo_novamente_para_conti_2": "Importe o arquivo novamente para continuar {v}.",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "O arquivo deste {noun} não está mais salvo no aparelho.",
    "nao_foi_possivel_descobrir_a_duracao_d": "Não foi possível descobrir a duração de “{name}”.",
    "lendo_faixa_v_de_length": "Lendo faixa {v} de {length}...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "Não foi possível descobrir a duração deste {v}.",
    "este_format_nao_pode_ser_reproduzido_n": "Este {format} não pode ser reproduzido neste navegador.",
    "este_format_esta_protegido_por_drm": "Este {format} está protegido por DRM.",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "O arquivo tem {bytes} e restam cerca de {v}. Libere espaço ou exclua livros da biblioteca.",
    "este_arquivo_nao_e_um_format_valido": "Este arquivo não é um {format} válido.",
    "preparando_as_paginas_vistas_de_total": "Preparando as páginas ({vistas} de {total})...",
    "preparando_total_pagina_s": {
      "one": "Preparando {total} página...",
      "other": "Preparando {total} páginas..."
    },
    "preparando_as_paginas_v_de_total": "Preparando as páginas ({v} de {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "Ele ocupa cerca de {bytes} e restam por volta de {v}. Libere espaço ou exclua livros da biblioteca.",
    "envio_direto_exige_endereco_seguro": "O envio direto para outro aplicativo não está disponível porque esta página não foi aberta por um endereço seguro. Salve o arquivo e envie-o pelo aplicativo que preferir.",
    "na_estante": "na estante",
    "nao_foi_possivel_montar_o_arquivo": "Não foi possível montar o arquivo.",
    "este_navegador_nao_oferece_o_envio_dir": "Este navegador não oferece o envio direto para outro aplicativo. Salve o arquivo e anexe-o pelo aplicativo que preferir.",
    "voce_ainda_nao_fez_nenhum_backup": "Você ainda não fez nenhum backup.",
    "converter_para_epub": "Converter para EPUB",
    "esta_pagina_nao_pode_ser_exibida": "Esta página não pôde ser exibida.",
    "na_ordem_em_que_serao_tocados": "Na ordem em que serão tocados",
    "este_capitulo_nao_pode_ser_exibido": "Este capítulo não pôde ser exibido.",
    "livro": "Livro",
    "restantes": " restantes",
    "como_seus_dados_sao_tratados": "Como seus dados são tratados",
    "condicoes_de_uso_do_aplicativo": "Condições de uso do aplicativo",
    "audiolivro": "audiolivro",
    "sobre_o_aplicativo": "Sobre o aplicativo",
    "o_que_e_o_veredas_reader": "O que é o Veredas Reader",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(este aparelho não permite compartilhar este tipo de arquivo)",
    "livros": "livros",
    "lendo": "lendo",
    "lidos": "lidos",
    "compartilhar_livro": "Compartilhar livro",
    "n_livros": {
      "one": "{n} livro",
      "other": "{n} livros"
    },
    "livros_unidade": {
      "one": "livro",
      "other": "livros"
    },
    "uma_faixa_discreta_depois_de_n_dias": "Uma faixa discreta na estante depois de {n} dias sem cópia de segurança. Nunca interrompe a leitura.",
    "scanned_arquivos_verificados_livros_enc": "{scanned} arquivo(s) verificado(s) · {encontrados} livro(s) encontrado(s)",
    "v_de_total": "{v} de {total}",
    "voltar_n_segundos": "Voltar {n} segundos",
    "grifos": "Grifos",
    "excluir": "Excluir",
    "entendi": "Entendi",
    "restaurando": "Restaurando",
    "restaurar": "Restaurar",
    "copiado": "Copiado",
    "descartar": "Apagar",
    "aviso": "Aviso",
    "cancelado": "Cancelado",
    "audiolivro_2": "Audiolivro",
    "progresso": "Progresso",
    "recentes": "Recentes",
    "concluir": "Concluir",
    "apagar": "Apagar",
    "editar": "Editar",
    "grifo": "Grifo",
    "leitura": "Leitura",
    "marcador": "Marcador",
    "pausar": "Pausar",
    "outros": "Outros",
    "outro": "Outro",
    "arquivo": "Arquivo",
    "arquivo_vazio": "Arquivo vazio.",
    "e_mais_n_arquivos": {
      "one": "e mais {n} arquivo, na ordem em que serão tocados",
      "other": "e mais {n} arquivos, na ordem em que serão tocados"
    },
    "n_arquivos_mp3": {
      "one": "{n} arquivo MP3",
      "other": "{n} arquivos MP3"
    },
    "pct_restam": "{pct}% · restam {tempo}",
    "n_minutos": {
      "one": "{n} minuto",
      "other": "{n} minutos"
    },
    "ir_para_tempo": "Ir para {tempo}",
    "nomear": "Nomear",
    "parte_n": "Parte {n}",
    "carregando_pagina_n": "Carregando página {n}...",
    "selecionar_pasta_e_continuar": "Selecionar pasta e continuar",
    "ler_agora": "Ler agora",
    "agrupamento_v": "Agrupamento: {v}.",
    "tempo_restante": "{tempo} restantes",
    "abrir_titulo": "Abrir {titulo}",
    "continuar_lendo_titulo": "Continuar lendo {titulo}",
    "continuar_ouvindo_titulo": "Continuar ouvindo {titulo}",
    "continuar_assistindo_titulo": "Continuar assistindo {titulo}",
    "lido": "Lido",
    "pausado": "Pausado",
    "status": "Status",
    "favorito": "Favorito",
    "escolher_local": "Escolher local",
    "epub_baixado_como": "EPUB baixado como {nome}.",
    "ouvir_a_partir_de": "ouvir a partir de {tempo}",
    "assistir_a_partir_de": "assistir a partir de {tempo}",
    "pagina_n_minuscula": "página {n}",
    "selecione_trecho_para_criar": "Selecione um trecho durante a leitura para criar {oque}.",
    "excluir_oque_pergunta": "Excluir {oque}?",
    "excluir_oque": "Excluir {oque}",
    "excluir_item_pergunta": "Excluir este item?",
    "use_organizar_para_criar": "Use “{botao}” em um livro para criar {oque}.",
    "n_arquivos_processados": {
      "one": "{n} arquivo processado",
      "other": "{n} arquivos processados"
    },
    "voce_ja_tem_titulo_de_autor": "Você já tem “{titulo}” de {autor} na biblioteca, embora o arquivo seja diferente. Deseja importar mesmo assim?",
    "voce_ja_tem_titulo": "Você já tem “{titulo}” na biblioteca, embora o arquivo seja diferente. Deseja importar mesmo assim?",
    "marcadores_unidade": {
      "one": "marcador",
      "other": "marcadores"
    },
    "ultimo_backup_em": "Último backup em <strong>{data}</strong>.",
    "guardar": "Guardar",
    "lembretes": "Lembretes",
    "juntar": "Juntar",
    "recomendado": "recomendado",
    "substituir": "Substituir",
    "n_capas_recuperadas": {
      "one": "{n} capa recuperada.",
      "other": "{n} capas recuperadas."
    },
    "nao_encontramos_arquivos_tipo": "Não encontramos arquivos {tipo} nessa pasta.",
    "tentar_outra_pasta": "Tentar outra pasta",
    "n_livros_encontrados": {
      "one": "{n} livro encontrado",
      "other": "{n} livros encontrados"
    },
    "n_de_total_selecionados": {
      "one": "{n} de {total} selecionado",
      "other": "{n} de {total} selecionados"
    },
    "importar": "Importar",
    "importar_n": "Importar {n}",
    "aceite_frase": "Li e aceito a {politica} e os {termos} do Veredas Reader.",
    "pdf_preservado": "O PDF original <strong>não será apagado da sua pasta</strong>. Apenas a cópia desse PDF será retirada da biblioteca depois que o EPUB for salvo com sucesso.",
    "gravar_epub_mesma_pasta": "Para gravar o EPUB <strong>na mesma pasta do PDF</strong>, o navegador precisa de permissão para acessar essa pasta.",
    "epub_pronto_qualquer_pasta": "O EPUB já foi convertido. Agora você pode escolher <strong>qualquer pasta do computador</strong> para salvar o arquivo.",
    "backup_explicacao": "O backup original é um ZIP ou TXT. Ao recebê-lo em outro dispositivo, faça a importação através de <strong>Restaurar backup</strong>: o próprio Veredas reconhece o conteúdo e restaura normalmente. O arquivo guarda o seu progresso, os grifos, as citações, as notas, os marcadores e a organização da estante — <strong>não os livros em si</strong>, nem as capas.",
    "lembretes_desligados_frase": "Os lembretes estão <strong>desligados</strong>. Lembre-se de fazer backup de vez em quando.",
    "backup_salvo_nos_downloads": "<strong>O arquivo de backup foi salvo neste aparelho</strong>, nos downloads. Dá para enviá-lo agora mesmo: abra o WhatsApp, o e-mail, o Drive ou o que preferir, toque em anexar e escolha o arquivo.",
    "arquivo_pronto_tamanho": "Arquivo pronto — <strong>{tamanho}</strong>.",
    "scan_intro_frase": "O aplicativo pode procurar livros em <strong>EPUB</strong> e <strong>MOBI</strong>, quadrinhos em <strong>CBZ</strong> e <strong>CBR</strong> e audiolivros em <strong>M4B</strong> dentro de uma pasta do seu aparelho, incluindo as subpastas.",
    "scan_intro_auto_frase": "Para montar sua estante rapidamente, o aplicativo pode procurar livros em <strong>EPUB</strong> e <strong>MOBI</strong>, quadrinhos em <strong>CBZ</strong> e <strong>CBR</strong> e audiolivros em <strong>M4B</strong> dentro de uma pasta do seu aparelho, incluindo as subpastas.",
    "n_livros_aguardando": {
      "one": "<strong>{n} livro</strong> com progresso e marcações guardados, à espera de ser importado de novo.",
      "other": "<strong>{n} livros</strong> com progresso e marcações guardados, à espera de serem importados de novo."
    },
    "fora_da_busca_titulo": "Não importamos automaticamente arquivos PDF, TXT, DOCX (Word), MD, MP3 e MP4",
    "fora_da_busca_texto": "Esses formatos são usados para todo tipo de documento, não só para livros. Deixá-los de fora mantém a estante organizada. <strong>Você pode importar cada um manualmente pelo botão +.</strong>"
  },
  "aviso": {
    "idioma_trocado": "Idioma alterado."
  },
  "vn": {
    "quem_le": "Quem lê",
    "natural": "Natural",
    "do_sistema": "Do sistema",
    "nota_sistema": "Usa as vozes instaladas no aparelho. Para uma leitura mais humana, escolha Natural.",
    "nota_sistema_com_natural": "A voz natural continua baixada. Volte para Natural quando quiser.",
    "voz_natural": "Voz natural",
    "gerada_no_aparelho": "Uma voz muito mais humana, criada no próprio aparelho.",
    "progresso_download": "Progresso do download",
    "x_de_y": "{x} de {y}",
    "aviso_arquivo": "A voz natural precisa que o Veredas seja aberto pelo endereço do aplicativo, e não como arquivo no computador. Enquanto isso, a leitura usa a voz do sistema.",
    "aviso_navegador": "Este navegador não tem os recursos de que a voz natural precisa. A leitura continua com a voz do sistema.",
    "verificando": "Verificando a voz natural…",
    "fato_download": "Download único de {tamanho}. Depois, funciona sem internet.",
    "fato_wifi": "Prefira o Wi-Fi. Dá para pausar e continuar depois.",
    "fato_privacidade": "O texto do livro não sai do aparelho.",
    "fato_idiomas": "Fala 31 idiomas, entre eles português, inglês e espanhol. Os demais continuam com a voz do sistema.",
    "baixar_voz_natural": "Baixar voz natural ({tamanho})",
    "licenca_curta": "Modelo Supertonic 3, da Supertone, sob a licença OpenRAIL-M. Detalhes em Sobre > Licenças de código aberto.",
    "pode_continuar_usando": "Você pode continuar lendo enquanto baixa. Se a conexão cair, o download continua de onde parou.",
    "pausar_download": "Pausar download",
    "erro_espaco": "Falta espaço no aparelho para terminar o download. Libere espaço e tente de novo.",
    "erro_offline": "Sem internet no momento. O que já foi baixado está guardado.",
    "erro_rede": "A conexão caiu no meio do download. O que já foi baixado está guardado.",
    "download_pausado": "Download pausado. O que já foi baixado está guardado.",
    "continuar_download": "Continuar",
    "descartar": "Descartar",
    "voz_feminina": "Feminina",
    "voz_feminina_desc": "Suave e calma",
    "voz_masculina": "Masculina",
    "voz_masculina_desc": "Calorosa e serena",
    "parar_amostra": "Parar amostra",
    "ouvir_amostra_de": "Ouvir amostra: {voz}",
    "escolha_a_voz": "Escolha a voz",
    "qualidade": "Qualidade",
    "q_auto": "Automática",
    "q_rapida": "Rápida",
    "q_maxima": "Máxima",
    "q_auto_desc": "Ajusta-se sozinha ao desempenho do aparelho, para a leitura não ter pausas.",
    "q_rapida_desc": "Gera a voz mais depressa. Boa para aparelhos mais simples.",
    "q_maxima_desc": "Som mais caprichado. Em aparelhos simples, pode causar pausas entre as frases.",
    "ocupa": "Ocupa {tamanho} neste aparelho",
    "remover": "Remover",
    "baixar_pelos_dados": "Baixar pelos dados móveis?",
    "baixar_pelos_dados_msg": "Parece que o aparelho não está no Wi-Fi. O download tem {tamanho} e pode consumir o seu plano de dados.",
    "baixar_agora": "Baixar mesmo assim",
    "pronta": "A voz natural está pronta.",
    "download_interrompido": "O download parou. Toque em Continuar quando quiser.",
    "remover_titulo": "Remover a voz natural?",
    "descartar_titulo": "Descartar o download?",
    "remover_msg": "Isso libera {tamanho}. A leitura volta para a voz do sistema, e dá para baixar de novo quando quiser.",
    "descartar_msg": "O que já foi baixado será apagado.",
    "removida": "Voz natural removida deste aparelho.",
    "amostra_falhou": "Não foi possível tocar a amostra neste aparelho.",
    "amostra": "Olá! É assim que os seus livros vão soar com a voz natural.",
    "gerando_voz": "Preparando a voz…",
    "automatico_idioma": "Automático ({idioma})",
    "automatico": "Automático",
    "so_voz_do_sistema": "voz do sistema",
    "aviso_idioma": "Idioma do texto: {idioma}. A voz natural ainda não fala este idioma, então o livro será lido pela voz do sistema.",
    "aviso_idioma_desconhecido": "Não foi possível reconhecer o idioma deste texto. Escolha o idioma abaixo para usar a voz natural.",
    "aviso_falha": "A voz natural não conseguiu rodar neste aparelho agora. A leitura segue com a voz do sistema.",
    "nao_carregou_usando_sistema": "A voz natural não carregou neste aparelho. Lendo com a voz do sistema.",
    "parou_usando_sistema": "A voz natural parou. Continuando com a voz do sistema.",
    "aparelho_lento": "Este aparelho está gerando a voz devagar. Escolha a qualidade Rápida para evitar pausas.",
    "idioma_do_texto": "Idioma do texto",
    "idioma_do_texto_dica": "Reconhecido pelo próprio texto. Troque se a pronúncia sair errada.",
    "leitura_em_voz_alta": "Leitura em voz alta",
    "lento_usando_sistema": "A voz natural ficou lenta demais neste aparelho. Continuando com a voz do sistema.",
    "aviso_lento": "Este aparelho não consegue gerar a voz natural na velocidade da leitura, então a voz do sistema assumiu por enquanto."
  }
});
