/* ============================================================
   PORTUGUÊS (PORTUGAL) — pt-PT
   ============================================================ */
Idiomas.registrar('pt-PT', {
  "ui": {
    "sua_biblioteca_local": "A sua biblioteca local",
    "biblioteca": "Biblioteca",
    "organizacao": "Organização",
    "minhas_marcacoes": "As minhas marcações",
    "sistema": "Sistema",
    "sua_biblioteca": "A sua Biblioteca",
    "toque_em_um_livro_para_comecar_a_ler": "Toque num livro para começar a ler.",
    "agrupar": "Agrupar",
    "sua_estante_nao_tem_copia_de_seguranca": "A sua estante não tem cópia de segurança",
    "se_este_aparelho_se_perder_o_progresso": "Se algo acontecer a este aparelho, o progresso e as marcações podem perder-se.",
    "agora_nao": "Agora não",
    "nao_avisar_mais": "Não avisar mais",
    "carregando": "A carregar...",
    "estante": "Estante",
    "lendo": "A ler",
    "favoritos": "Favoritos",
    "marcas": "Marcas",
    "mais": "Mais",
    "neste_capitulo": "Neste capítulo",
    "velocidade": "Velocidade",
    "timer": "Temporizador",
    "marcar": "Marcar",
    "marcadores": "Marcadores",
    "personalizar_leitura": "Personalizar leitura",
    "as_preferencias_ficam_salvas_para_as_p": "As preferências ficam guardadas para as próximas leituras.",
    "tema": "Tema",
    "claro": "Claro",
    "sepia": "Sépia",
    "escuro": "Escuro",
    "oceano": "Oceano",
    "tipografia": "Tipografia",
    "texto": "Texto",
    "tamanho": "Tamanho",
    "espacamento": "Espaçamento",
    "margens": "Margens",
    "cores_personalizadas_opcional": "Cores personalizadas (opcional)",
    "fundo": "Fundo",
    "fonte": "Cor do texto",
    "brilho": "Brilho",
    "orientacao": "Orientação",
    "auto": "Auto",
    "retrato": "Retrato",
    "paisagem": "Paisagem",
    "modo_de_leitura": "Modo de leitura",
    "automatico": "Automático",
    "horizontal": "Horizontal",
    "vertical": "Vertical",
    "automatico_usa_rolagem_horizontal_para": "O modo Automático usa deslocamento horizontal para EPUB, MOBI, TXT e MD, e vertical para PDF e DOCX. Se alterar durante a leitura, a alteração fica guardada apenas nesse livro.",
    "quadrinhos": "Banda desenhada",
    "como_a_pagina_aparece": "Como a página aparece",
    "pagina_inteira": "Página inteira",
    "largura_da_tela": "Largura do ecrã",
    "sentido_da_leitura": "Sentido da leitura",
    "normal": "Normal →",
    "manga": "← Mangá",
    "revista_aberta_na_horizontal": "Revista aberta na horizontal",
    "com_o_aparelho_deitado_mostra_duas_pag": "Com o aparelho deitado, mostra duas páginas lado a lado — a capa fica sozinha, como numa revista a sério.",
    "normal_vira_da_esquerda_para_a_direita": "O modo Normal vira da esquerda para a direita. O modo Mangá inverte tudo: o deslize, o toque nas margens e a ordem das duas páginas na revista aberta.",
    "gire_o_aparelho_para_a_horizontal_para": "Rode o aparelho para a horizontal para ver duas páginas lado a lado.",
    "dois_toques_ampliam_no_ponto_tocado_co": "Dois toques ampliam no ponto tocado; com zoom, arraste para percorrer a página. Beliscar com dois dedos também funciona.",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "O botão de deslocamento, no topo do leitor, alterna entre página a página e deslocamento contínuo (estilo webtoon). No deslocamento contínuo as páginas ligam-se umas às outras, e ampliar alarga a página: percorre-a deslocando para os lados.",
    "virada_de_pagina": "Viragem de página",
    "folha_real": "Folha real",
    "deslizar": "Deslizar",
    "sem_animacao": "Sem animação",
    "na_leitura_horizontal_arraste_a_pagina": "Na leitura horizontal, arraste a página a partir da margem para a dobrar com o dedo. Solte a meio do caminho para desistir da viragem.",
    "ouvir_leitura": "Ouvir leitura",
    "continue_de_onde_parou_no_seu_ritmo": "Continue de onde parou, ao seu ritmo.",
    "livro": "Livro",
    "pronto_para_comecar": "Pronto para começar",
    "voz": "Voz",
    "escolha_uma_voz_disponivel_no_disposit": "Escolha uma voz disponível no dispositivo",
    "voz_padrao_do_sistema": "Voz padrão do sistema",
    "durante_a_reproducao": "Durante a reprodução",
    "a_leitura_avanca_pagina_a_pagina_os_co": "A leitura avança página a página. Os controlos do sistema aparecem quando o navegador os suporta.",
    "organizar_livro": "Organizar livro",
    "estantes_colecoes_tags_e_status": "Estantes, coleções, etiquetas e estado.",
    "cancelar": "Cancelar",
    "salvar": "Guardar",
    "grifos_citacoes_notas_e_marcadores_des": "Realces, citações, notas e marcadores deste livro.",
    "sumario": "Índice",
    "toque_em_um_capitulo_para_ir_direto_ao": "Toque num capítulo para ir diretamente ao ponto.",
    "sua_anotacao": "A sua anotação",
    "edite_ou_adicione_comentarios_ao_seu_t": "Edite ou adicione comentários ao seu trecho.",
    "trecho": "Trecho",
    "sua_nota": "A sua nota",
    "salvar_nota": "Guardar nota",
    "agrupar_biblioteca": "Agrupar biblioteca",
    "escolha_como_os_livros_serao_organizad": "Escolha como os livros serão organizados na estante.",
    "ao_arrastar_um_livro_para_outra_posica": "Ao arrastar um livro para outra posição, a estante muda automaticamente para A Minha Ordem e mantém a sequência que criou.",
    "backup_e_restauracao": "Cópia de segurança e restauro",
    "sua_estante_seu_progresso_e_suas_marca": "A sua estante, o seu progresso e as suas marcações num só ficheiro.",
    "escolha_uma_dimensao_para_explorar_sua": "Escolha uma dimensão para explorar a sua biblioteca.",
    "capitulos": "Capítulos",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "A voz não fica mais grave nem mais aguda. A escolha aplica-se a este e aos próximos livros.",
    "ajuste_fino": "Ajuste fino",
    "timer_de_sono": "Temporizador de sono",
    "o_audio_diminui_de_volume_aos_poucos_e": "O áudio diminui de volume aos poucos e pausa automaticamente.",
    "pontos_que_voce_guardou_neste_audioliv": "Pontos que guardou neste audiolivro.",
    "ajustes_do_audio": "Ajustes do áudio",
    "as_preferencias_ficam_salvas_para_todo": "As preferências ficam guardadas para todos os audiolivros.",
    "botao_de_voltar": "Botão de recuar",
    "botao_de_avancar": "Botão de avançar",
    "recuar_ao_retomar": "Recuar ao retomar",
    "depois_de_uma_pausa_longa_volta_alguns": "Depois de uma pausa longa, volta alguns segundos atrás para reencontrar o fio da história.",
    "tocar_ao_abrir": "Reproduzir ao abrir",
    "ao_tocar_em_um_audiolivro_na_estante_a": "Ao tocar num audiolivro na estante, a reprodução começa de imediato.",
    "no_computador_espaco_toca_e_pausa_pula": "No computador: espaço reproduz e pausa · ← → saltam · Shift + ← → mudam de capítulo · ↑ ↓ volume · B marca · [ ] velocidade.",
    "converter_pdf_para_epub": "Converter PDF para EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "Prepare o livro para uma leitura fluida e ajustável.",
    "confirmacao": "Confirmação",
    "confirmar": "Confirmar",
    "processando": "A processar",
    "documento": "Documento",
    "buscar_livros_no_dispositivo": "Procurar livros no dispositivo",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "Encontre ficheiros EPUB, MOBI, CBZ, CBR e M4B já guardados no aparelho.",
    "juntar_em_um_unico_audiolivro": "Juntar num único audiolivro?",
    "titulo": "Título",
    "autor": "Autor",
    "importar_separados": "Importar separados",
    "bem_vindo_ao_veredas_reader": "Bem-vindo ao Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "A sua biblioteca de leitura, inteiramente no seu dispositivo.",
    "buscar": "Procurar",
    "importar_livro": "Importar livro",
    "buscar_titulo_autor_tag": "Procurar título, autor, etiqueta...",
    "fechar_busca": "Fechar procura",
    "navegacao_da_biblioteca": "Navegação da biblioteca",
    "fechar_menu": "Fechar menu",
    "agrupar_livros": "Agrupar livros",
    "voltar": "Voltar",
    "marcar_pagina": "Marcar página",
    "personalizar": "Personalizar",
    "navegacao_principal": "Navegação principal",
    "acoes_do_trecho": "Ações do trecho",
    "amarelo": "Amarelo",
    "verde": "Verde",
    "rosa": "Rosa",
    "azul": "Azul",
    "player_de_audiolivro": "Leitor de audiolivro",
    "minimizar_player": "Minimizar leitor",
    "minimizar": "Minimizar",
    "video_em_reproducao": "Vídeo em reprodução",
    "abrir_a_lista_de_capitulos": "Abrir a lista de capítulos",
    "posicao_no_audio": "Posição no áudio",
    "alternar_entre_o_progresso_do_capitulo": "Alternar entre o progresso do capítulo e do livro inteiro",
    "capitulo_anterior": "Capítulo anterior",
    "voltar_15_segundos": "Recuar 15 segundos",
    "reproduzir": "Reproduzir",
    "avancar_30_segundos": "Avançar 30 segundos",
    "proximo_capitulo": "Capítulo seguinte",
    "velocidade_de_reproducao": "Velocidade de reprodução",
    "marcar_este_ponto": "Marcar este ponto",
    "ver_marcadores": "Ver marcadores",
    "silenciar": "Silenciar",
    "volume": "Volume",
    "audiolivro_em_reproducao": "Audiolivro em reprodução",
    "abrir_o_player": "Abrir o leitor",
    "fechar_o_player": "Fechar o leitor",
    "fechar": "Fechar",
    "trecho_anterior": "Trecho anterior",
    "iniciar_leitura": "Iniciar leitura",
    "proximo_trecho": "Trecho seguinte",
    "escreva_seu_comentario_interpretacao_o": "Escreva o seu comentário, interpretação ou lembrete...",
    "cancelar_importacao": "Cancelar importação",
    "nome_do_audiolivro": "Nome do audiolivro",
    "nome_do_autor": "Nome do autor",
    "idioma": "Idioma",
    "idioma_do_aplicativo": "Idioma da aplicação",
    "o_aplicativo_segue_o_idioma_do_apare": "A aplicação segue o idioma do aparelho. Se o seu idioma ainda não existir aqui, abre em inglês.",
    "seguir_o_aparelho": "Seguir o aparelho",
    "fazer_backup": "Fazer cópia de segurança",
    "todos": "Todos",
    "lidos": "Lidos",
    "pausados": "Em pausa",
    "autores": "Autores",
    "tags": "Etiquetas",
    "grifar": "Realçar",
    "anotar": "Anotar",
    "enviar": "Enviar",
    "restaurar_padroes": "Restaurar padrões",
    "voltar_para_1": "Voltar para 1×",
    "marcar_agora": "Marcar agora",
    "escolher_pasta": "Escolher pasta",
    "juntar_em_um_audiolivro": "Juntar num audiolivro",
    "sobre": "Sobre",
    "licencas_de_codigo_aberto": "Licenças de código aberto",
    "configuracoes": "Configurações",
    "temas_e_idioma": "Temas e idioma"
  },
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "Marcador eliminado.",
    "excluir_marcador": "Eliminar marcador",
    "o_marcador_sera_removido_permanentemen": "O marcador será removido permanentemente.",
    "excluir_marcador_2": "Eliminar marcador?",
    "pagina_salva": "Página guardada",
    "anotacoes": "Anotações",
    "citacoes": "Citações",
    "item_excluido": "Item eliminado.",
    "este_registro_sera_removido_permanente": "Este registo será removido permanentemente da biblioteca.",
    "configuracoes_padrao_restauradas": "Configurações padrão restauradas.",
    "leitura_da_esquerda_para_a_direita": "Leitura da esquerda para a direita.",
    "leitura_da_direita_para_a_esquerda_man": "Leitura da direita para a esquerda (mangá).",
    "a_pagina_inteira_passa_a_caber_na_tela": "A página inteira passa a caber no ecrã.",
    "a_pagina_passa_a_ocupar_toda_a_largura": "A página passa a ocupar toda a largura do ecrã.",
    "virada_sem_animacao_ativada": "Viragem sem animação ativada.",
    "virada_deslizante_ativada": "Viragem deslizante ativada.",
    "virada_em_folha_real_ativada": "Viragem em folha real ativada.",
    "padrao_automatico_cada_formato_abre_no": "Padrão automático: cada formato abre no sentido natural dele.",
    "mudando_durante_a_leitura_o_ajuste_fic": "Se alterar durante a leitura, o ajuste fica guardado apenas nesse livro.",
    "automatico_usa_rolagem_horizontal_para": "O modo automático usa deslocamento horizontal para EPUB, MOBI, TXT, MD e banda desenhada, e vertical para PDF e DOCX.",
    "este_livro": "este livro",
    "armazenamento_local_indisponivel_neste": "Armazenamento local indisponível neste navegador.",
    "o_aplicativo_pode_procurar_os_livros_q": "A aplicação pode procurar os livros que já estão no seu aparelho.",
    "vamos_montar_sua_estante": "Vamos montar a sua estante?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "Sem a aceitação, a aplicação não pode ser utilizada.",
    "precisamos_do_seu_aceite": "Precisamos da sua aceitação",
    "antes_de_comecar_leia_e_aceite_os_docu": "Antes de começar, leia e aceite os documentos abaixo.",
    "selecionar_todos": "Selecionar todos",
    "limpar_selecao": "Limpar seleção",
    "todos_parecem_ja_estar_na_sua_estante": "Parecem já estar todos na sua estante.",
    "lendo_a_pasta_escolhida": "A ler a pasta escolhida…",
    "procurando_livros": "A procurar livros",
    "nao_foi_possivel_concluir_a_busca_no_d": "Não foi possível concluir a procura no dispositivo.",
    "tente_outra_pasta_do_aparelho": "Tente outra pasta do aparelho.",
    "nenhum_livro_encontrado": "Nenhum livro encontrado",
    "use_o_botao_para_escolher_os_arquivos": "Use o botão + para escolher os ficheiros manualmente. Em telemóveis Android, o Chrome costuma permitir escolher uma pasta inteira.",
    "seu_navegador_nao_permite_ler_pastas": "O seu navegador não permite ler pastas",
    "busca_automatica_indisponivel": "Procura automática indisponível",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR e M4B",
    "termos_de_uso": "Termos de utilização",
    "politica_de_privacidade": "Política de privacidade",
    "um_minuto_agora_evita_perder_o_progres": "Um minuto agora evita perder o progresso e as marcações depois.",
    "ver_estante": "Ver estante",
    "modo_juntar": "Modo juntar",
    "modo_substituir": "Modo substituir",
    "restauracao_concluida": "Restauro concluído",
    "tente_de_novo_com_o_arquivo_original": "Tente novamente com o ficheiro original.",
    "a_restauracao_nao_pode_ser_concluida": "Não foi possível concluir o restauro",
    "devolvendo_o_seu_progresso_e_as_suas_m": "A devolver o seu progresso e as suas marcações...",
    "restaurar_este_backup": "Restaurar esta cópia de segurança?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Escolha o .zip guardado pelo Veredas ou o .txt recebido por partilha.",
    "nao_foi_possivel_ler_este_arquivo": "Não foi possível ler este ficheiro",
    "lendo_o_backup": "A ler a cópia de segurança",
    "backup_do_veredas_reader": "Cópia de segurança do Veredas Reader",
    "arquivo_de_transporte_txt_contendo_os": "cópia de segurança em formato .txt, com o mesmo conteúdo do ZIP",
    "nao_foi_possivel_montar_o_arquivo_de_b": "Não foi possível criar o ficheiro de cópia de segurança.",
    "escolher_o_app": "Escolher a aplicação",
    "vale_conferir_o_que_vai_no_arquivo": "Vale a pena verificar o que vai no ficheiro",
    "enviar_para_outro_app": "Enviar para outra aplicação",
    "salvar_o_arquivo": "Guardar o ficheiro",
    "o_navegador_aqui_nao_oferece_o_compart": "O navegador aqui não oferece partilha direta. Pode guardar o ficheiro e enviá-lo depois pela aplicação que quiser.",
    "este_aparelho_nao_abre_a_lista_de_apli": "Este aparelho não abre a lista de aplicações",
    "importe_pelo_menos_um_livro_antes_de_f": "Importe pelo menos um livro antes de fazer uma cópia de segurança.",
    "estante_vazia": "Estante vazia",
    "nao_deu_para_copiar": "Não foi possível copiar",
    "copiar_detalhes": "Copiar detalhes",
    "o_backup_foi_salvo_assim_mesmo": "A cópia de segurança foi guardada mesmo assim",
    "o_aparelho_recusou_abrir_a_lista": "Não foi possível abrir a lista de partilha",
    "sem_detalhes_do_navegador": "sem detalhes do navegador",
    "o_sistema_nao_aceitou_receber_o_arquiv": "O sistema do aparelho não conseguiu receber o ficheiro.",
    "o_navegador_considerou_a_situacao_inse": "O navegador bloqueou a partilha por uma regra de segurança própria. Guarde o ficheiro e envie-o pela aplicação que preferir.",
    "o_compartilhamento_so_funciona_em_ende": "A partilha só funciona em endereços seguros. Esta aplicação está a ser aberta por um endereço http:// comum, e nesse caso o navegador bloqueia o envio para outras aplicações.",
    "este_navegador_nao_conseguiu_iniciar_o": "Este navegador não conseguiu abrir a partilha. Guarde o ficheiro e envie-o pela aplicação que preferir.",
    "o_navegador_recebeu_um_arquivo_em_form": "O navegador não abriu a lista de aplicações para partilhar. Toque novamente no botão ou guarde o ficheiro e envie-o pela aplicação que preferir.",
    "nao_foi_possivel_gerar_o_backup": "Não foi possível gerar a cópia de segurança.",
    "reunindo_a_sua_estante": "A reunir a sua estante...",
    "preparando_o_backup": "A preparar a cópia de segurança",
    "pronto_nada_mais_esta_esperando": "Pronto, já não está nada à espera.",
    "o_progresso_e_as_marcacoes_desses_livr": "O progresso e as marcações desses livros serão apagados. Se importar os ficheiros depois, voltarão em branco.",
    "descartar_o_que_esta_esperando": "Eliminar os dados em espera?",
    "lembretes_de_backup_religados": "Lembretes de cópia de segurança voltaram a ser ativados.",
    "sem_titulo": "Sem título",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "Lembretes desativados.",
    "manter_ligado": "Manter ligado",
    "desligar_assim_mesmo": "Desativar mesmo assim",
    "o_botao_de_salvar_continua_onde_sempre": "O botão de guardar continua onde sempre esteve, em Cópia de segurança e restauro.",
    "o_lembrete_e_o_unico_aviso_que_existe": "O lembrete é o único aviso que existe. Sem ele, será preciso lembrar-se de fazer cópia de segurança por conta própria.\n\n",
    "limpar_os_dados_do_navegador_desinstal": "Se os dados do navegador forem limpos, a aplicação for desinstalada, mudar de telemóvel ou o aparelho avariar, não será possível recuperar o progresso, os realces, as citações, as notas e os marcadores.\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "A sua estante existe só neste aparelho. Não há cópia em servidor nenhum, e por isso não há como recuperá-la para si.\n\n",
    "leia_antes_de_confirmar": "Leia antes de confirmar",
    "desligar_os_lembretes_de_backup": "Desativar os lembretes de cópia de segurança?",
    "progresso_de_leitura_restaurado_neste": "Progresso de leitura restaurado neste livro.",
    "pronto": "Pronto.",
    "aplicando_as_suas_preferencias": "A aplicar as suas preferências...",
    "atualize_o_veredas_reader_e_tente_de_n": "Atualize o Veredas Reader e tente novamente.",
    "este_backup_foi_feito_numa_versao_mais": "Esta cópia de segurança foi feita numa versão mais recente da aplicação.",
    "este_arquivo_nao_e_um_backup_de_biblio": "Este ficheiro não é uma cópia de segurança de biblioteca do Veredas.",
    "o_conteudo_interno_nao_pode_ser_lido": "O conteúdo interno não pôde ser lido.",
    "o_backup_esta_corrompido": "A cópia de segurança está corrompida.",
    "falta_o_arquivo_biblioteca_json_la_den": "Falta o ficheiro biblioteca.json lá dentro.",
    "este_arquivo_nao_parece_ser_um_backup": "Este ficheiro não parece ser uma cópia de segurança do Veredas.",
    "compactando": "A comprimir...",
    "para_restaurar_menu_lateral_backup_e_r": "Para restaurar: menu lateral > Cópia de segurança e restauro > Restaurar cópia de segurança.",
    "o_veredas_devolve_sozinho_as_marcacoes": "o Veredas restaura automaticamente as marcações e o ponto onde parou.",
    "importe_os_livros_normalmente_no_aplic": "importe os livros normalmente na aplicação: ao reconhecer cada ficheiro,",
    "ele_nao_contem_os_arquivos_dos_livros": "NÃO contém os ficheiros dos livros. Para restaurar por completo,",
    "as_notas_os_marcadores_e_a_organizacao": "as notas, os marcadores e a organização da sua estante.",
    "este_arquivo_guarda_o_seu_progresso_de": "Este ficheiro guarda o seu progresso de leitura, os realces, as citações,",
    "verificando_se_sao_partes_do_mesmo_aud": "A verificar se são partes do mesmo audiolivro...",
    "analisando_os_arquivos": "A analisar os ficheiros",
    "nao_foi_possivel_salvar_o_audiolivro": "Não foi possível guardar o audiolivro.",
    "audiolivros_grandes_podem_levar_alguns": "Audiolivros grandes podem demorar alguns instantes...",
    "salvando_na_sua_estante": "A guardar na sua estante",
    "falha_ao_processar_os_arquivos": "Falha ao processar os ficheiros.",
    "falha_ao_processar_o_arquivo": "Falha ao processar o ficheiro.",
    "nao_foi_possivel_salvar_o_quadrinho": "Não foi possível guardar a banda desenhada.",
    "quase_la": "Quase lá...",
    "falha_ao_processar_o_quadrinho": "Falha ao processar a banda desenhada.",
    "autor_desconhecido": "Autor desconhecido",
    "lendo_o_quadrinho": "A ler a banda desenhada...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "Não foi possível guardar o livro na biblioteca.",
    "nao_foi_possivel_ler_o_pdf": "Não foi possível ler o PDF.",
    "lendo_o_pdf": "A ler o PDF...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "Se for um .doc antigo, abra-o no Word e guarde como .docx antes de importar.",
    "este_arquivo_nao_e_um_docx_valido": "Este ficheiro não é um .docx válido.",
    "livros_com_protecao_da_amazon_nao_pode": "Livros com proteção da Amazon não podem ser abertos aqui. Use uma cópia sem DRM ou converta o livro para EPUB.",
    "este_arquivo_esta_protegido_por_drm": "Este ficheiro está protegido por DRM.",
    "confira_se_a_extensao_corresponde_ao_c": "Verifique se a extensão corresponde ao conteúdo ou converta o livro para EPUB.",
    "este_arquivo_nao_e_um_mobi_valido": "Este ficheiro não é um MOBI válido.",
    "nao_foi_possivel_ler_o_arquivo": "Não foi possível ler o ficheiro.",
    "formato_nao_suportado": "Formato não suportado.",
    "falha_ao_salvar_o_livro_na_biblioteca": "Falha ao guardar o livro na biblioteca.",
    "livro_importado_e_salvo_no_dispositivo": "Livro importado e guardado no dispositivo.",
    "audiolivro_importado_e_salvo_no_dispos": "Audiolivro importado e guardado no dispositivo.",
    "quadrinho_importado_e_salvo_no_disposi": "Banda desenhada importada e guardada no dispositivo.",
    "salvando_na_sua_estante_2": "A guardar na sua estante...",
    "importando_livro": "A importar livro",
    "importar_mesmo_assim": "Importar mesmo assim",
    "parece_que_este_livro_ja_esta_na_estan": "Parece que este livro já está na estante",
    "este_livro_ja_esta_na_estante": "Este livro já está na estante",
    "video_importado_e_salvo_no_dispositivo": "Vídeo importado e guardado no dispositivo.",
    "importacao_cancelada": "Importação cancelada.",
    "preparando_o_arquivo": "A preparar o ficheiro",
    "importando_audiolivro": "A importar audiolivro",
    "importacao_concluida": "Importação concluída",
    "importacao_interrompida": "Importação interrompida",
    "a_importacao_foi_interrompida_o_que_ja": "A importação foi interrompida; o que já tinha entrado continua na estante.",
    "finalizando": "A finalizar…",
    "nao_foi_possivel_ler_o_arquivo_2": "não foi possível ler o ficheiro",
    "importando_livros": "A importar livros",
    "livros_quadrinhos_documentos_audiolivr": "Livros, banda desenhada, documentos, audiolivros e vídeos",
    "series": "Séries",
    "colecoes": "Coleções",
    "organizacao_salva": "Organização guardada.",
    "informe_um_nome_para_o_livro_antes_de": "Indique um nome para o livro antes de guardar.",
    "nome_do_livro_obrigatorio": "Nome do livro obrigatório",
    "importe_um_livro_primeiro": "Importe um livro primeiro.",
    "citacao": "citação",
    "anotacao": "anotação",
    "citacao_2": "Citação",
    "anotacao_2": "Anotação",
    "uma_citacao": "uma citação",
    "uma_anotacao": "uma anotação",
    "o_marcador_sera_removido_da_biblioteca": "O marcador será removido da biblioteca, mas o ficheiro do livro permanecerá intacto.",
    "marcador_de_audio": "Marcador de áudio",
    "marcador_de_video": "Marcador de vídeo",
    "nao_foi_possivel_excluir_o_livro": "Não foi possível eliminar o livro.",
    "livro_excluido_da_biblioteca": "Livro eliminado da biblioteca.",
    "excluir_livro": "Eliminar livro",
    "isso_remove_apenas_a_copia_armazenada": "Isto remove apenas a cópia armazenada pela biblioteca, além do progresso, marcadores e anotações. O ficheiro original na sua pasta não será apagado.",
    "excluir_livro_2": "Eliminar livro?",
    "ordem_personalizada_salva": "Ordem personalizada guardada.",
    "ordem_manual_da_sua_estante": "Ordem manual da sua estante.",
    "agrupamento_alterado_para_minha_ordem": "Agrupamento alterado para A Minha Ordem.",
    "nova_ordem_salva": "Nova ordem guardada.",
    "nao_foi_possivel_salvar_a_nova_ordem": "Não foi possível guardar a nova ordem.",
    "baixar_automaticamente": "Transferir automaticamente",
    "escolha_livremente_onde_o_arquivo_sera": "Escolha livremente onde o ficheiro será gravado.",
    "salvar_epub": "Guardar EPUB",
    "livro_epub": "Livro EPUB",
    "erro_desconhecido": "erro desconhecido",
    "a_permissao_para_salvar_o_arquivo_foi": "A permissão para guardar o ficheiro foi cancelada. Nenhum item da biblioteca foi alterado.",
    "conversao_cancelada_o_pdf_original_per": "Conversão cancelada. O PDF original permanece na biblioteca.",
    "preparando_salvamento": "A preparar gravação…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "A cópia do PDF não está disponível na biblioteca.",
    "reconstruindo_o_livro_localmente": "A reconstruir o livro localmente.",
    "convertendo_pdf": "A converter PDF",
    "nao_foi_possivel_compartilhar_o_livro": "Não foi possível partilhar o livro.",
    "o_arquivo_foi_preparado_para_voce_comp": "O ficheiro foi preparado para partilhar noutra aplicação.",
    "livro_compartilhado": "Livro partilhado.",
    "a_copia_deste_livro_nao_esta_disponive": "A cópia deste livro não está disponível na biblioteca.",
    "para_manter_a_politica_de_compartilham": "Para manter a política de partilha da biblioteca, ficheiros EPUB e MOBI não podem ser partilhados por esta aplicação.",
    "quadrinhos_ficam_guardados_somente_no": "A banda desenhada fica guardada apenas no seu aparelho e não pode ser partilhada por esta aplicação.",
    "audiolivros_e_videos_ficam_guardados_s": "Audiolivros e vídeos ficam guardados apenas no seu aparelho e não podem ser partilhados por esta aplicação.",
    "formato_protegido": "Formato protegido",
    "compartilhamento_indisponivel": "Partilha indisponível",
    "concluido": "Concluído",
    "ainda_nao_comecado": "Ainda não começado",
    "continue_lendo": "Continuar a ler",
    "continue_ouvindo": "Continuar a ouvir",
    "continue_assistindo": "Continuar a ver",
    "comece_por_aqui": "Comece por aqui",
    "comece_a_ouvir": "Comece a ouvir",
    "comece_a_assistir": "Comece a ver",
    "no_total": "no total",
    "para_ler": "para ler",
    "sua_estante": "A sua estante",
    "livros_organizados_pela_opcao_selecion": "Livros organizados pela opção selecionada.",
    "uma_prateleira_para_cada_tipo_de_arqui": "Uma prateleira para cada tipo de ficheiro.",
    "autores_agrupados_em_ordem_alfabetica": "Autores agrupados por ordem alfabética.",
    "toque_para_continuar_de_onde_parou": "Toque para continuar de onde parou.",
    "para_ler_2": "Para ler",
    "lendo_agora": "A ler agora",
    "audio_e_video": "Áudio e vídeo",
    "trechos_salvos_separadamente_dos_marca": "Trechos guardados separadamente dos marcadores.",
    "comentarios_vinculados_a_trechos_selec": "Comentários ligados a trechos selecionados.",
    "paginas_salvas_para_voltar_rapidamente": "Páginas guardadas para voltar rapidamente.",
    "do_maior_para_o_menor_progresso_de_lei": "Do maior para o menor progresso de leitura.",
    "livros_adicionados_ou_lidos_mais_recen": "Livros adicionados ou lidos mais recentemente.",
    "ordem_alfabetica_pelo_titulo": "Ordem alfabética pelo título.",
    "separa_em_prateleiras_de_epub_pdf_docx": "Separa em prateleiras de EPUB, PDF, DOCX, audiolivros, vídeos…",
    "tipo_de_arquivo": "Tipo de ficheiro",
    "organiza_e_separa_os_livros_por_autor": "Organiza e separa os livros por autor.",
    "agrupar_por_autor": "Agrupar por Autor",
    "pressione_o_livro_e_mova_o": "Prima o livro e mova-o.",
    "minha_ordem": "A Minha Ordem",
    "epub_pronto": "EPUB pronto",
    "conversao_concluida": "Conversão concluída",
    "necessario_para_salvar_o_epub_ao_lado": "Necessário para guardar o EPUB ao lado do original",
    "escolha_a_pasta_do_pdf": "Escolha a pasta do PDF",
    "processando": "A processar…",
    "processamento_local_no_navegador": "Processamento local no navegador",
    "convertendo_livro": "A converter livro",
    "livro_em_pdf": "Livro em PDF",
    "recalculando_paginas": "A recalcular páginas...",
    "ajustando_leitura": "A ajustar leitura",
    "abrir_comentario": "Abrir comentário",
    "anotacao_salva": "Anotação guardada.",
    "anotacao_atualizada": "Anotação atualizada.",
    "escreva_uma_nota_antes_de_salvar": "Escreva uma nota antes de guardar.",
    "nao_foi_possivel_compartilhar": "Não foi possível partilhar.",
    "compartilhamento_indisponivel_2": "Partilha indisponível.",
    "trecho_copiado": "Trecho copiado.",
    "trecho_compartilhado": "Trecho partilhado.",
    "citacao_salva": "Citação guardada.",
    "trecho_grifado": "Trecho realçado.",
    "grifo_removido": "Realce removido.",
    "comentario_apagado": "Comentário apagado.",
    "remover_grifo": "Remover realce",
    "apagar_comentario": "Apagar comentário",
    "remover_grifo_2": "Remover realce?",
    "apagar_comentario_2": "Apagar comentário?",
    "remover_este_grifo": "Remover este realce?",
    "apagar_este_comentario": "Apagar este comentário?",
    "sem_comentario": "Sem comentário",
    "comentario": "Comentário",
    "marcador_removido_desta_pagina": "Marcador removido desta página.",
    "pagina_adicionada_aos_marcadores": "Página adicionada aos marcadores.",
    "este_e_o_inicio_do_livro": "Este é o início do livro.",
    "esta_e_a_primeira_pagina": "Esta é a primeira página.",
    "voce_chegou_ao_fim_do_livro": "Chegou ao fim do livro.",
    "voce_chegou_ao_fim_do_quadrinho": "Chegou ao fim da banda desenhada.",
    "agora_em_revista_aberta_duas_paginas_l": "Agora em revista aberta: duas páginas lado a lado, com a capa sozinha.",
    "leitura_horizontal_ativada_neste_livro": "Leitura horizontal ativada neste livro.",
    "rolagem_vertical_ativada_neste_livro": "Deslocamento vertical ativado neste livro.",
    "leitura_pagina_a_pagina_ativada_neste": "Leitura página a página ativada nesta banda desenhada.",
    "rolagem_continua_ativada_neste_quadrin": "Deslocamento contínuo ativado nesta banda desenhada.",
    "mudar_para_rolagem_vertical": "Mudar para deslocamento vertical",
    "mudar_para_leitura_horizontal": "Mudar para leitura horizontal",
    "rolagem_continua_estilo_webtoon": "Deslocamento contínuo (estilo webtoon)",
    "voltar_para_pagina_a_pagina": "Voltar para página a página",
    "separando_os_capitulos": "A separar os capítulos...",
    "lendo_o_livro": "A ler o livro",
    "lendo_o_markdown": "A ler o Markdown",
    "lendo_o_documento": "A ler o documento",
    "pagina_indisponivel": "Página indisponível.",
    "isto_acontece_so_desta_vez": "Isto acontece só desta vez.",
    "preparando_o_quadrinho": "A preparar a banda desenhada",
    "abrindo_o_quadrinho": "A abrir a banda desenhada...",
    "montando_as_paginas": "A montar as páginas...",
    "nao_foi_possivel_abrir_este_livro": "Não foi possível abrir este livro.",
    "abertura_cancelada": "Abertura cancelada.",
    "o_livro_demorou_demais_para_abrir_e_fo": "O livro demorou demasiado a abrir e foi interrompido.",
    "importe_o_arquivo_novamente_para_conti": "Importe o ficheiro novamente para continuar a leitura.",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "O ficheiro deste livro já não está guardado no aparelho.",
    "preparando_sua_leitura": "A preparar a sua leitura...",
    "abrindo_livro": "A abrir livro",
    "leitura_concluida": "Leitura concluída.",
    "a_voz_foi_interrompida_pelo_navegador": "A voz foi interrompida pelo navegador.",
    "nao_foi_possivel_preparar_este_trecho": "Não foi possível preparar este trecho para áudio.",
    "a_leitura_em_voz_alta_nao_e_suportada": "A leitura em voz alta não é suportada neste navegador.",
    "pausar_leitura": "Pausar leitura",
    "em_pausa": "Em pausa",
    "leitura_em_voz_alta_nao_disponivel_nes": "Leitura em voz alta não disponível neste navegador",
    "nome_do_marcador": "Nome do marcador",
    "o_marcador_sera_removido_deste_audioli": "O marcador será removido deste audiolivro.",
    "nao_foi_possivel_salvar_o_marcador": "Não foi possível guardar o marcador.",
    "ja_existe_um_marcador_neste_ponto": "Já existe um marcador neste ponto.",
    "timer_de_sono_encerrado": "Temporizador de sono terminado.",
    "fim_do_cap": "Fim do cap.",
    "timer_desativado": "Temporizador desativado.",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "O áudio vai pausar no fim do capítulo.",
    "este_audiolivro_nao_tem_capitulos": "Este audiolivro não tem capítulos.",
    "ao_fim_do_capitulo": "No fim do capítulo",
    "desativar_timer": "Desativar temporizador",
    "mais_10_minutos_no_timer": "Mais 10 minutos no temporizador.",
    "somar_10_minutos": "Adicionar 10 minutos",
    "pausa_ao_fim_do_capitulo": "Pausa no fim do capítulo",
    "no_livro_todo": "No livro todo",
    "video": "Vídeo",
    "audiolivro_concluido": "Audiolivro concluído.",
    "video_concluido": "Vídeo concluído.",
    "video_2": "vídeo",
    "audio": "áudio",
    "toque_em_reproduzir_para_comecar": "Toque em reproduzir para começar.",
    "falha_ao_carregar_o_audio": "Falha ao carregar o áudio.",
    "exclua_o_da_biblioteca_e_importe_o_arq": "Elimine-o da biblioteca e importe o ficheiro novamente.",
    "os_nomes_dos_arquivos_seguem_uma_seque": "Os nomes dos ficheiros seguem uma sequência, por isso parecem ser capítulos do mesmo audiolivro.",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "Os ficheiros têm o mesmo álbum nas etiquetas, por isso parecem ser capítulos do mesmo audiolivro.",
    "libere_espaco_ou_exclua_livros_da_bibl": "Liberte espaço ou elimine livros da biblioteca e tente novamente.",
    "o_armazenamento_do_aparelho_esta_cheio": "O armazenamento do aparelho está cheio.",
    "preparando_a_capa": "A preparar a capa...",
    "remova_esse_arquivo_da_selecao_e_tente": "Remova esse ficheiro da seleção e tente novamente.",
    "sequencia": "sequência",
    "o_arquivo_pode_estar_incompleto_tente": "O ficheiro pode estar incompleto. Tente transferi-lo novamente.",
    "conferindo_se_o_audio_pode_ser_reprodu": "A verificar se o áudio pode ser reproduzido...",
    "conferindo_se_o_video_pode_ser_reprodu": "A verificar se o vídeo pode ser reproduzido...",
    "lendo_titulo_capitulos_e_capa": "A ler título, capítulos e capa...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "O ficheiro pode estar danificado ou num formato de áudio que o navegador não reproduz. Experimente convertê-lo para MP3 ou M4B (AAC).",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "O ficheiro pode estar danificado ou num formato de vídeo que o navegador não reproduz. Experimente convertê-lo para MP4 com vídeo H.264 e áudio AAC.",
    "converta_o_audiolivro_para_m4b_com_aud": "Converta o audiolivro para M4B com áudio AAC (ou para MP3) e importe novamente.",
    "converta_o_video_para_mp4_com_audio_aa": "Converta o vídeo para MP4 com áudio AAC e vídeo H.264 e importe novamente.",
    "o_navegador_nao_reproduz_o_formato_de": "O navegador não reproduz o formato de áudio deste ficheiro.",
    "arquivos_com_protecao_nao_podem_ser_re": "Ficheiros com proteção não podem ser reproduzidos aqui. Use uma cópia sem DRM.",
    "nao_ha_espaco_suficiente_no_aparelho_p": "Não há espaço suficiente no aparelho para este audiolivro.",
    "confira_se_a_extensao_corresponde_ao_c_2": "Verifique se a extensão corresponde ao conteúdo ou converta o áudio para MP3 ou M4B (AAC).",
    "imagem_invalida": "imagem inválida",
    "imagem_demorou_demais": "a imagem demorou demasiado a carregar",
    "imagem_vazia": "imagem vazia",
    "inicio": "Início",
    "mp4_moov_nao_encontrado": "O vídeo parece estar incompleto ou danificado.",
    "pagina": "Página",
    "esta_pagina_nao_esta_disponivel": "Esta página não está disponível.",
    "esta_pagina_nao_pode_ser_descompactada": "Esta página não pôde ser descomprimida.",
    "quadrinho_fechado": "Banda desenhada fechada.",
    "ele_pode_estar_incompleto_dividido_em": "Pode estar incompleta, dividida em várias partes ou numa variante de RAR que a aplicação não reconhece. Converter para CBZ resolve.",
    "remova_a_senha_do_arquivo_e_importe_de": "Remova a palavra-passe do ficheiro e importe novamente.",
    "nao_foi_possivel_ler_este_arquivo_de_q": "Não foi possível ler este ficheiro de banda desenhada.",
    "este_quadrinho_esta_protegido_por_senh": "Esta banda desenhada está protegida por palavra-passe.",
    "lendo_o_indice_do_quadrinho": "A ler o índice da banda desenhada...",
    "o_arquivo_pode_ser_grande_demais_para": "O ficheiro pode ser demasiado grande para a memória deste aparelho. Dividir a banda desenhada em partes menores costuma resolver.",
    "nao_foi_possivel_abrir_este_quadrinho": "Não foi possível abrir esta banda desenhada.",
    "lendo_o_arquivo": "A ler o ficheiro...",
    "preparando_o_leitor_de_cbr": "A preparar o leitor de CBR...",
    "o_arquivo_pode_estar_incompleto_proteg": "O ficheiro pode estar incompleto, protegido por palavra-passe ou corrompido.",
    "nao_foi_possivel_ler_este_quadrinho": "Não foi possível ler esta banda desenhada.",
    "o_arquivo_precisa_conter_imagens_jpg_p": "O ficheiro precisa de conter imagens (JPG, PNG, WEBP ou GIF).",
    "nao_encontramos_paginas_dentro_deste_q": "Não encontrámos páginas dentro desta banda desenhada.",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "Não há espaço suficiente no aparelho para esta banda desenhada.",
    "cabecalho_de_item_invalido": "Parte do ficheiro está danificada.",
    "a_pasta_vendor_libarchive_precisa_esta": "Falta um componente da aplicação para abrir esta banda desenhada. Converta-a para CBZ ou reinstale a aplicação.",
    "o_leitor_de_cbr_nao_foi_encontrado": "O leitor de CBR não foi encontrado.",
    "converta_o_quadrinho_para_cbz_zip_e_im": "Converta a banda desenhada para CBZ (ZIP) e importe novamente.",
    "este_navegador_nao_consegue_abrir_arqu": "Este navegador não consegue abrir ficheiros CBR.",
    "convertendo_o_markdown": "A converter o Markdown",
    "lendo_o_texto": "A ler o texto",
    "pdf_indisponivel": "PDF indisponível.",
    "epub_invalido_nenhum_capitulo_no_spine": "Este EPUB está danificado: não foi possível encontrar os capítulos do livro.",
    "livro_sem_titulo": "Livro sem título",
    "epub_invalido_arquivo_opf_nao_encontra": "Este EPUB está incompleto ou danificado e não pode ser aberto.",
    "epub_invalido_container_xml_nao_encont": "Este EPUB está incompleto ou danificado e não pode ser aberto.",
    "organizando_o_texto": "A organizar o texto",
    "descompactando_o_livro": "A descomprimir o livro",
    "nao_encontramos_conteudo_para_exibir_n": "Não encontrámos conteúdo para mostrar neste ficheiro.",
    "livro_sem_texto_legivel": "Livro sem texto legível",
    "o_arquivo_pode_estar_corrompido_tente": "O ficheiro pode estar corrompido. Tente convertê-lo para EPUB.",
    "nao_foi_possivel_extrair_o_texto_deste": "Não foi possível extrair o texto deste MOBI.",
    "nenhum_registro_de_conteudo_foi_encont": "Não foi possível encontrar o texto do livro neste ficheiro.",
    "arquivo_mobi_sem_texto": "Ficheiro MOBI sem texto.",
    "o_dicionario_de_compressao_esta_vazio": "Falta parte do conteúdo deste MOBI.",
    "arquivo_mobi_incompleto": "Ficheiro MOBI incompleto.",
    "as_tabelas_de_compressao_nao_foram_enc": "Falta parte do conteúdo deste MOBI.",
    "converta_o_arquivo_para_epub_em_um_pro": "Converta o ficheiro para EPUB num programa como o Calibre e importe novamente.",
    "compressao_mobi_nao_reconhecida": "Este MOBI usa um formato interno que a aplicação não reconhece.",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "O cabeçalho do livro não pôde ser lido.",
    "arquivo_mobi_corrompido": "Ficheiro MOBI corrompido.",
    "a_lista_interna_de_registros_esta_inco": "O ficheiro está incompleto. Experimente transferi-lo ou convertê-lo novamente.",
    "o_download_parece_ter_sido_interrompid": "A transferência parece ter sido interrompida. Transfira o ficheiro novamente.",
    "tabela_de_compressao_mobi_corrompida": "Parte deste ficheiro MOBI está danificada.",
    "tabela_de_compressao_mobi_incompleta": "Este ficheiro MOBI está incompleto.",
    "tabela_de_compressao_mobi_invalida": "Parte deste ficheiro MOBI está danificada.",
    "este_arquivo_docx_nao_tem_conteudo_de": "Este ficheiro .docx não tem conteúdo de texto que possa ser apresentado.",
    "documento_sem_texto": "Documento sem texto",
    "o_arquivo_pode_estar_corrompido_proteg": "O ficheiro pode estar corrompido, protegido por palavra-passe ou ser um .doc antigo. Guarde-o novamente como .docx e importe outra vez.",
    "nao_foi_possivel_ler_este_arquivo_docx": "Não foi possível ler este ficheiro DOCX.",
    "convertendo_o_documento": "A converter o documento",
    "conecte_se_a_internet_uma_vez_para_bai": "Ligue-se à internet uma vez para transferir o componente e abra o livro novamente.",
    "o_conversor_de_docx_nao_carregou": "O conversor de DOCX não carregou.",
    "video_mp4": "Vídeo (MP4)",
    "audiolivro_m4b": "Audiolivro (M4B)",
    "audiolivro_mp3": "Audiolivro (MP3)",
    "quadrinho_cbt": "Banda desenhada (CBT)",
    "quadrinho_cb7": "Banda desenhada (CB7)",
    "quadrinho_cbr": "Banda desenhada (CBR)",
    "quadrinho_cbz": "Banda desenhada (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "Texto (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "Gravação cancelada.",
    "o_arquivo_esta_vindo_do_armazenamento": "O ficheiro está a vir do armazenamento na nuvem para o seu aparelho.",
    "baixando_o_arquivo": "A transferir o ficheiro",
    "cancelando": "A cancelar...",
    "use_grifar_citacao_anotar_ou_marcador": "Use Realçar, Citação, Anotar ou Marcador durante a leitura.",
    "nenhuma_marcacao_ainda": "Ainda não há marcações",
    "trecho_original": "Trecho original",
    "procurar_meus_livros": "Procurar os meus livros",
    "a_busca_fica_sempre_disponivel_no_menu": "A procura está sempre disponível no menu lateral, em Sistema.",
    "da_para_fazer_depois": "Pode fazer depois",
    "nada_entra_na_estante_sem_a_sua_confir": "Nada entra na estante sem a sua confirmação: pode ver a lista e marcar o que quer importar.",
    "voce_revisa_antes": "Pode rever antes",
    "escolha_uma_pasta_downloads_e_um_bom_c": "Escolha uma pasta (Transferências é um bom começo) e a aplicação procura nela e em todas as subpastas.",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "Procura por EPUB, MOBI, CBZ, CBR e M4B",
    "voltar_e_revisar": "Voltar e rever",
    "ler_os_termos": "Ler os termos",
    "ler_a_politica": "Ler a política",
    "os_dois_documentos_ficam_sempre_dispon": "Os dois documentos estão sempre disponíveis no menu lateral, em Sobre.",
    "leia_com_calma": "Leia com calma",
    "a_politica_e_os_termos_explicam_como_o": "A política e os termos explicam como a aplicação guarda os seus livros e o que pode fazer com eles. Para usar a biblioteca, é preciso concordar com eles.",
    "nada_acontece_sem_o_aceite": "Para começar, é preciso aceitar os termos",
    "aceitar_e_continuar": "Aceitar e continuar",
    "nao_aceito": "Não aceito",
    "termos_de_uso_2": "Termos de Utilização",
    "politica_de_privacidade_2": "Política de Privacidade",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "A aplicação só acede aos ficheiros e pastas que escolher, quando escolher.",
    "voce_no_controle": "O controlo é seu",
    "depois_de_importar_um_livro_voce_le_se": "Depois de importar um livro, pode lê-lo sem internet.",
    "funciona_offline": "Funciona offline",
    "livros_marcacoes_e_progresso_sao_guard": "Livros, marcações e progresso são guardados localmente. Nada é enviado para servidores nossos.",
    "tudo_fica_no_seu_aparelho": "Tudo fica no seu aparelho",
    "escolha_o_que_deseja_adicionar_a_bibli": "Escolha o que deseja adicionar à biblioteca. Ficheiros idênticos aos que já estão na estante são ignorados automaticamente.",
    "voce_pode_tentar_outra_pasta_ou_import": "Pode tentar outra pasta ou importar os ficheiros pelo botão +.",
    "a_leitura_acontece_so_no_seu_dispositi": "A leitura acontece apenas no seu dispositivo.",
    "voce_escolhe_a_pasta": "A escolha da pasta é sua",
    "tema_tipografia_margens_modo_de_virada": "Tema, tipografia, margens, modo de viragem e ajustes de áudio.",
    "restaurar_minhas_preferencias": "Restaurar as minhas preferências",
    "o_backup_manda_as_marcacoes_atuais_dos": "A cópia de segurança manda. As marcações atuais dos livros que estiverem no ficheiro serão trocadas pelas da cópia de segurança.",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "Nada é apagado. As marcações dos dois lados somam-se e o progresso mais recente prevalece.",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "O que fazer com o que já está na estante",
    "grifos_citacoes_e_notas": "realces, citações e notas",
    "preparando_o_arquivo_2": "A preparar o ficheiro...",
    "os_livros_em_si_nem_as_capas_por_isso": "Nem os livros em si, nem as capas — por isso o ficheiro tem só alguns KB. Quem o receber precisa de ter os ficheiros dos livros para que as marcações voltem ao sítio certo, e as capas reaparecem automaticamente na importação.",
    "nao_vai_no_arquivo": "Não vai no ficheiro",
    "o_seu_progresso_de_leitura_os_grifos_a": "O seu progresso de leitura, os realces, as citações, as notas, os marcadores e a organização da estante — estado, favoritos, coleções, séries e etiquetas.",
    "vai_no_arquivo": "Vai no ficheiro",
    "descartar_o_que_esta_esperando_2": "Eliminar dados em espera",
    "esperando_o_arquivo": "À espera do ficheiro",
    "avisar_quando_fizer_tempo_sem_backup": "Avisar quando fizer tempo sem cópia de segurança",
    "livros_que_ainda_nao_estiverem_na_esta": "Livros que ainda não estiverem na estante ficam em espera: quando importar o ficheiro deles, as marcações voltam automaticamente.",
    "restaurar_backup": "Restaurar cópia de segurança",
    "salvar_backup": "Guardar cópia de segurança",
    "ainda_nao_ha_itens": "Ainda não há itens",
    "arraste_um_livro_para_outra_posicao_na": "Arraste um livro para outra posição na estante para guardar uma ordem manual. A ordem manual passa a ter prioridade sobre o agrupamento por autor.",
    "separe_por_virgulas": "Separe por vírgulas",
    "ex_estudos_ficcao": "Ex.: Estudos, Ficção...",
    "pasta_estante": "Pasta / estante",
    "ex_trilogia": "Ex.: Trilogia...",
    "serie": "Série",
    "aparece_em_favoritos": "Aparece em Favoritos.",
    "nome_do_livro": "Nome do livro",
    "nenhum_registro_ainda": "Ainda não há registos",
    "no_leitor_toque_no_icone_de_marcador_p": "No leitor, toque no ícone de marcador para guardar a página.",
    "nenhum_marcador_ainda": "Ainda não há marcadores",
    "a_gravacao_e_independente_da_localizac": "A gravação é independente da localização do PDF e não altera o ficheiro original.",
    "o_pdf_original_nao_precisa_estar_nessa": "O PDF original não precisa de estar nessa pasta",
    "excluir_da_biblioteca": "Eliminar da biblioteca",
    "adicionar_livro": "Adicionar livro",
    "adicione_livros_e_acompanhe_o_que_esta": "Adicione livros e acompanhe o que está para ler, o que está em curso e o seu progresso.",
    "tudo_pronto_para_a_proxima_leitura": "Tudo pronto para a próxima leitura.",
    "sua_biblioteca": "A sua biblioteca",
    "arraste_um_livro_para_reposiciona_lo_a": "Arraste um livro para o reposicionar: a estante passa para A Minha Ordem e guarda a sequência.",
    "importe_um_livro_ou_ajuste_seus_filtro": "Importe um livro ou ajuste os seus filtros de organização.",
    "nada_por_aqui_ainda": "Ainda não há nada por aqui",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "Toque em + e escolha ficheiros MP3, M4B ou MP4. Vários MP3 de capítulos podem tornar-se um único audiolivro.",
    "nada_para_ouvir_ou_assistir_ainda": "Ainda não há nada para ouvir ou ver",
    "o_pdf_original_permanece_intacto_na_pa": "O PDF original permanece intacto na sua pasta.",
    "paginas_como_imagem": "Páginas como imagem",
    "paginas_do_pdf": "Páginas do PDF",
    "em_navegadores_sem_suporte_a_acesso_di": "Em navegadores sem suporte para acesso direto ao sistema de ficheiros, o EPUB será transferido como alternativa.",
    "essa_permissao_e_dada_somente_a_esta_a": "Essa permissão é dada somente a esta aplicação e evita que o ficheiro original seja alterado.",
    "selecione_a_pasta_que_contem_o_pdf": "Selecione a pasta que contém o PDF",
    "preparando": "A preparar…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "O ficheiro está a ser lido e reconstruído. Livros grandes podem demorar alguns instantes.",
    "revistas_apostilas_complexas_formulari": "Revistas, apostilas complexas, formulários, documentos com muitas tabelas ou PDFs digitalizados podem perder parte do layout original.",
    "funcionalidade_indicada_apenas_para_li": "Funcionalidade indicada apenas para livros",
    "o_epub_e_melhor_para_livros_com_texto": "O EPUB é melhor para livros com texto selecionável, porque permite ajustar tipo de letra, tamanho, margens e modo de leitura.",
    "trecho_selecionado": "Trecho selecionado",
    "trecho_comentado": "Trecho comentado",
    "aplicando_zoom": "A aplicar zoom...",
    "nao_foi_possivel_carregar_esta_pagina": "Não foi possível carregar esta página.",
    "nomear_marcador": "Nomear marcador",
    "toque_em_marcar_agora_para_guardar_est": "Toque em «Marcar agora» para guardar este ponto e voltar a ele quando quiser.",
    "timer_ativo": "Temporizador ativo",
    "trecho_ausente_ou_corrompido_no_arquiv": "[Trecho ausente ou corrompido no ficheiro original]",
    "novos_livros_vao_abrir_em_leitura_v": "Os novos livros vão abrir em leitura {v}.",
    "leitura_efetivo_aplicada_a_este_livro": "Leitura {efetivo} aplicada a este livro.",
    "automatico_neste_livro_leitura_efetivo": "Automático neste livro: leitura {efetivo}.",
    "agora_esta_em_efetivo_no_automatico_fo": "Agora está em {efetivo}; no automático, {format} abre em {padrao}.",
    "esta_escolha_vale_so_para_v_cada_livro": "Esta escolha vale só para «{v}». Cada livro guarda o seu sentido de deslocamento.",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} ainda não estão na sua estante.",
    "escolha_uma_pasta_para_procurar_label": "Escolha uma pasta para procurar {label}.",
    "subtitle_versao_build": "{subtitle} · versão {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "Não foi possível ler {path}; a usar o texto incorporado.",
    "seu_ultimo_backup_foi_ha_dias_dias": "A sua última cópia de segurança foi há {dias} dias",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "{aguardando} livro da cópia de segurança ainda não está aqui. O progresso e as marcações dele ficaram guardados: assim que importar o ficheiro, tudo volta automaticamente ao lugar.",
      "other": "{aguardando} livros da cópia de segurança ainda não estão aqui. O progresso e as marcações deles ficaram guardados: assim que importar cada ficheiro, tudo volta automaticamente ao lugar."
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "{atualizados} livro da sua estante foi atualizado.",
      "other": "{atualizados} livros da sua estante foram atualizados."
    },
    "criado_em_quando": "Criado em {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "Cópia de segurança pronta: {livros} livro(s) e {marcacoes} marcação(ões).",
    "endereco_seguro_seguro": "endereço seguro: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "Progresso e {marcas} marcação restaurados neste livro.",
      "other": "Progresso e {marcas} marcações restaurados neste livro."
    },
    "restaurando_v_de_length": "A restaurar ({v} de {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} livro(s) · {marcacoes} marcação(ões)",
    "criado_em_v": "Criado em {v}",
    "reunindo_a_sua_estante_v_de_length": "A reunir a sua estante ({v} de {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "«{titulo}» já foi importado antes e continua disponível na sua biblioteca. Não foi criada nenhuma cópia nova.",
    "length_arquivos_de_audio": "{length} ficheiros de áudio...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "{falhas} ficheiro não pôde ser lido.",
      "other": "{falhas} ficheiros não puderam ser lidos."
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} já estavam na biblioteca e foram ignorados.",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "{importados} livro adicionado à estante.",
      "other": "{importados} livros adicionados à estante."
    },
    "epub_salvo_em_filename": "EPUB guardado em {fileName}.",
    "falha_ao_converter_o_pdf_v": "Falha ao converter o PDF: {v}",
    "pagina_page_de_totalpages": "Página {page} de {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} página",
      "other": "{totalPages} páginas"
    },
    "length_resultado_s_para_search": {
      "one": "{length} resultado para «{search}»",
      "other": "{length} resultados para «{search}»"
    },
    "capitulo_v": "Capítulo {v}",
    "organizando_capitulo_v_de_totalchapter": "A organizar capítulo {v} de {totalChapters}",
    "pagina_v": "Página {v}",
    "paginas_v_v2": "Páginas {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} página pronta",
      "other": "{length} páginas prontas"
    },
    "montando_as_paginas_pagessofar_prontas": "A montar as páginas — {pagesSoFar} prontas",
    "lendo_pagina_v_de_length": "A ler página {v} de {length}",
    "marcador_salvo_em_t": "Marcador guardado em {t}.",
    "o_audio_vai_pausar_em_minutes_minutos": "O áudio vai pausar em {minutes} minutos.",
    "length_capitulos_toque_para_ir_direto": "{length} capítulos · toque para ir diretamente ao ponto.",
    "narrado_por_narrator": "Narrado por {narrator}",
    "velocidade_de_reproducao_rate": "Velocidade de reprodução: {rate}",
    "avancar_f_segundos": "Avançar {f} segundos",
    "nao_foi_possivel_abrir_este_v": "Não foi possível abrir este {v}.",
    "nao_foi_possivel_ler_o_arquivo_de_v": "Não foi possível ler o ficheiro de {v}.",
    "o_v_esta_danificado_neste_ponto": "O {v} está danificado neste ponto.",
    "o_navegador_nao_consegue_reproduzir_es": "O navegador não consegue reproduzir este ficheiro de {v}.",
    "nao_foi_possivel_reproduzir_este_v": "Não foi possível reproduzir este {v}.",
    "os_dados_deste_noun_estao_incompletos": "Os dados deste {noun} estão incompletos.",
    "importe_o_arquivo_novamente_para_conti_2": "Importe o ficheiro novamente para continuar {v}.",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "O ficheiro deste {noun} já não está guardado no aparelho.",
    "nao_foi_possivel_descobrir_a_duracao_d": "Não foi possível descobrir a duração de «{name}».",
    "lendo_faixa_v_de_length": "A ler faixa {v} de {length}...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "Não foi possível descobrir a duração deste {v}.",
    "este_format_nao_pode_ser_reproduzido_n": "Este {format} não pode ser reproduzido neste navegador.",
    "este_format_esta_protegido_por_drm": "Este {format} está protegido por DRM.",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "O ficheiro tem {bytes} e restam cerca de {v}. Liberte espaço ou elimine livros da biblioteca.",
    "este_arquivo_nao_e_um_format_valido": "Este ficheiro não é um {format} válido.",
    "preparando_as_paginas_vistas_de_total": "A preparar as páginas ({vistas} de {total})...",
    "preparando_total_pagina_s": {
      "one": "A preparar {total} página...",
      "other": "A preparar {total} páginas..."
    },
    "preparando_as_paginas_v_de_total": "A preparar as páginas ({v} de {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "Ocupa cerca de {bytes} e restam por volta de {v}. Liberte espaço ou elimine livros da biblioteca.",
    "envio_direto_exige_endereco_seguro": "O envio direto para outra aplicação não está disponível porque esta página não foi aberta a partir de um endereço seguro. Guarde o ficheiro e envie-o pela aplicação que preferir.",
    "na_estante": "na estante",
    "nao_foi_possivel_montar_o_arquivo": "Não foi possível criar o ficheiro.",
    "este_navegador_nao_oferece_o_envio_dir": "Este navegador não oferece o envio direto para outra aplicação. Guarde o ficheiro e anexe-o pela aplicação que preferir.",
    "voce_ainda_nao_fez_nenhum_backup": "Ainda não fez nenhuma cópia de segurança.",
    "converter_para_epub": "Converter para EPUB",
    "esta_pagina_nao_pode_ser_exibida": "Esta página não pôde ser apresentada.",
    "na_ordem_em_que_serao_tocados": "Na ordem em que serão reproduzidos",
    "este_capitulo_nao_pode_ser_exibido": "Este capítulo não pôde ser apresentado.",
    "livro": "Livro",
    "restantes": " restantes",
    "como_seus_dados_sao_tratados": "Como os seus dados são tratados",
    "condicoes_de_uso_do_aplicativo": "Condições de utilização da aplicação",
    "audiolivro": "audiolivro",
    "sobre_o_aplicativo": "Sobre a aplicação",
    "o_que_e_o_veredas_reader": "O que é o Veredas Reader",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(este aparelho não permite partilhar este tipo de ficheiro)",
    "livros": "livros",
    "lendo": "a ler",
    "lidos": "lidos",
    "compartilhar_livro": "Partilhar livro",
    "n_livros": {
      "one": "{n} livro",
      "other": "{n} livros"
    },
    "livros_unidade": {
      "one": "livro",
      "other": "livros"
    },
    "uma_faixa_discreta_depois_de_n_dias": "Uma faixa discreta na estante depois de {n} dias sem cópia de segurança. Nunca interrompe a leitura.",
    "scanned_arquivos_verificados_livros_enc": "{scanned} ficheiro(s) verificado(s) · {encontrados} livro(s) encontrado(s)",
    "v_de_total": "{v} de {total}",
    "voltar_n_segundos": "Recuar {n} segundos",
    "grifos": "Realces",
    "excluir": "Eliminar",
    "entendi": "Entendi",
    "restaurando": "A restaurar",
    "restaurar": "Restaurar",
    "copiado": "Copiado",
    "descartar": "Apagar",
    "aviso": "Aviso",
    "cancelado": "Cancelado",
    "audiolivro_2": "Audiolivro",
    "progresso": "Progresso",
    "recentes": "Recentes",
    "concluir": "Concluir",
    "apagar": "Apagar",
    "editar": "Editar",
    "grifo": "Realce",
    "leitura": "Leitura",
    "marcador": "Marcador",
    "pausar": "Pausar",
    "outros": "Outros",
    "outro": "Outro",
    "arquivo": "Ficheiro",
    "arquivo_vazio": "Ficheiro vazio.",
    "e_mais_n_arquivos": {
      "one": "e mais {n} ficheiro, na ordem em que serão reproduzidos",
      "other": "e mais {n} ficheiros, na ordem em que serão reproduzidos"
    },
    "n_arquivos_mp3": {
      "one": "{n} ficheiro MP3",
      "other": "{n} ficheiros MP3"
    },
    "pct_restam": "{pct}% · restam {tempo}",
    "n_minutos": {
      "one": "{n} minuto",
      "other": "{n} minutos"
    },
    "ir_para_tempo": "Ir para {tempo}",
    "nomear": "Nomear",
    "parte_n": "Parte {n}",
    "carregando_pagina_n": "A carregar página {n}...",
    "selecionar_pasta_e_continuar": "Selecionar pasta e continuar",
    "ler_agora": "Ler agora",
    "agrupamento_v": "Agrupamento: {v}.",
    "tempo_restante": "{tempo} restantes",
    "abrir_titulo": "Abrir {titulo}",
    "continuar_lendo_titulo": "Continuar a ler {titulo}",
    "continuar_ouvindo_titulo": "Continuar a ouvir {titulo}",
    "continuar_assistindo_titulo": "Continuar a ver {titulo}",
    "lido": "Lido",
    "pausado": "Em pausa",
    "status": "Estado",
    "favorito": "Favorito",
    "escolher_local": "Escolher local",
    "epub_baixado_como": "EPUB transferido como {nome}.",
    "ouvir_a_partir_de": "ouvir a partir de {tempo}",
    "assistir_a_partir_de": "ver a partir de {tempo}",
    "pagina_n_minuscula": "página {n}",
    "selecione_trecho_para_criar": "Selecione um trecho durante a leitura para criar {oque}.",
    "excluir_oque_pergunta": "Eliminar {oque}?",
    "excluir_oque": "Eliminar {oque}",
    "excluir_item_pergunta": "Eliminar este item?",
    "use_organizar_para_criar": "Use «{botao}» num livro para criar {oque}.",
    "n_arquivos_processados": {
      "one": "{n} ficheiro processado",
      "other": "{n} ficheiros processados"
    },
    "voce_ja_tem_titulo_de_autor": "Já tem «{titulo}» de {autor} na biblioteca, embora o ficheiro seja diferente. Deseja importar mesmo assim?",
    "voce_ja_tem_titulo": "Já tem «{titulo}» na biblioteca, embora o ficheiro seja diferente. Deseja importar mesmo assim?",
    "marcadores_unidade": {
      "one": "marcador",
      "other": "marcadores"
    },
    "ultimo_backup_em": "Última cópia de segurança em <strong>{data}</strong>.",
    "guardar": "Guardar",
    "lembretes": "Lembretes",
    "juntar": "Juntar",
    "recomendado": "recomendado",
    "substituir": "Substituir",
    "n_capas_recuperadas": {
      "one": "{n} capa recuperada.",
      "other": "{n} capas recuperadas."
    },
    "nao_encontramos_arquivos_tipo": "Não encontrámos ficheiros {tipo} nessa pasta.",
    "tentar_outra_pasta": "Tentar outra pasta",
    "n_livros_encontrados": {
      "one": "{n} livro encontrado",
      "other": "{n} livros encontrados"
    },
    "n_de_total_selecionados": {
      "one": "{n} de {total} selecionado",
      "other": "{n} de {total} selecionados"
    },
    "importar": "Importar",
    "importar_n": "Importar {n}",
    "aceite_frase": "Li e aceito a {politica} e os {termos} do Veredas Reader.",
    "pdf_preservado": "O PDF original <strong>não será apagado da sua pasta</strong>. Apenas a cópia deste PDF será retirada da biblioteca depois de o EPUB ser guardado com sucesso.",
    "gravar_epub_mesma_pasta": "Para gravar o EPUB <strong>na mesma pasta do PDF</strong>, o navegador precisa de permissão para aceder a essa pasta.",
    "epub_pronto_qualquer_pasta": "O EPUB já foi convertido. Agora pode escolher <strong>qualquer pasta do computador</strong> para guardar o ficheiro.",
    "backup_explicacao": "A cópia de segurança original é um ZIP ou TXT. Ao recebê-la noutro dispositivo, faça a importação através de <strong>Restaurar cópia de segurança</strong>: o próprio Veredas reconhece o conteúdo e restaura normalmente. O ficheiro guarda o seu progresso, os realces, as citações, as notas, os marcadores e a organização da estante — <strong>não os livros em si</strong>, nem as capas.",
    "lembretes_desligados_frase": "Os lembretes estão <strong>desativados</strong>. Lembre-se de fazer uma cópia de segurança de vez em quando.",
    "backup_salvo_nos_downloads": "<strong>O ficheiro de cópia de segurança foi guardado neste aparelho</strong>, nas suas transferências. Pode enviá-lo agora mesmo: abra o WhatsApp, o email, o Drive ou o que preferir, toque em anexar e escolha o ficheiro.",
    "arquivo_pronto_tamanho": "Ficheiro pronto — <strong>{tamanho}</strong>.",
    "scan_intro_frase": "A aplicação pode procurar livros em <strong>EPUB</strong> e <strong>MOBI</strong>, banda desenhada em <strong>CBZ</strong> e <strong>CBR</strong> e audiolivros em <strong>M4B</strong> dentro de uma pasta do seu aparelho, incluindo as subpastas.",
    "scan_intro_auto_frase": "Para montar a sua estante rapidamente, a aplicação pode procurar livros em <strong>EPUB</strong> e <strong>MOBI</strong>, banda desenhada em <strong>CBZ</strong> e <strong>CBR</strong> e audiolivros em <strong>M4B</strong> dentro de uma pasta do seu aparelho, incluindo as subpastas.",
    "n_livros_aguardando": {
      "one": "<strong>{n} livro</strong> com progresso e marcações guardados, à espera de ser importado novamente.",
      "other": "<strong>{n} livros</strong> com progresso e marcações guardados, à espera de serem importados novamente."
    },
    "fora_da_busca_titulo": "Não importamos automaticamente ficheiros PDF, TXT, DOCX (Word), MD, MP3 e MP4",
    "fora_da_busca_texto": "Estes formatos são usados para todo o tipo de documentos, não só para livros. Deixá-los de fora mantém a estante organizada. <strong>Pode importar cada um manualmente com o botão +.</strong>"
  },
  "aviso": {
    "idioma_trocado": "Idioma alterado."
  },
  "vn": {
    "quem_le": "Quem lê",
    "natural": "Natural",
    "do_sistema": "Do sistema",
    "nota_sistema": "Usa as vozes instaladas no aparelho. Para uma leitura mais humana, escolha Natural.",
    "nota_sistema_com_natural": "A voz natural continua transferida. Volte a Natural quando quiser.",
    "voz_natural": "Voz natural",
    "gerada_no_aparelho": "Uma voz muito mais humana, criada no próprio aparelho.",
    "progresso_download": "Progresso da transferência",
    "x_de_y": "{x} de {y}",
    "aviso_arquivo": "A voz natural precisa que o Veredas seja aberto pelo endereço da aplicação, e não como ficheiro no computador. Até lá, a leitura usa a voz do sistema.",
    "aviso_navegador": "Este navegador não tem os recursos de que a voz natural precisa. A leitura continua com a voz do sistema.",
    "verificando": "A verificar a voz natural…",
    "fato_download": "Transferência única de {tamanho}. Depois, funciona sem internet.",
    "fato_wifi": "De preferência, use Wi-Fi. Pode pausar e continuar mais tarde.",
    "fato_privacidade": "O texto do livro nunca sai do aparelho.",
    "fato_idiomas": "Fala 31 idiomas, entre eles português, inglês e espanhol. Os restantes continuam com a voz do sistema.",
    "baixar_voz_natural": "Transferir voz natural ({tamanho})",
    "licenca_curta": "Modelo Supertonic 3, da Supertone, sob a licença OpenRAIL-M. Detalhes em Sobre > Licenças de código aberto.",
    "pode_continuar_usando": "Pode continuar a ler durante a transferência. Se a ligação falhar, a transferência retoma onde parou.",
    "pausar_download": "Pausar transferência",
    "erro_espaco": "Não há espaço suficiente no aparelho para concluir a transferência. Liberte espaço e tente novamente.",
    "erro_offline": "Sem internet de momento. O que já foi transferido fica guardado.",
    "erro_rede": "A ligação falhou a meio da transferência. O que já foi transferido fica guardado.",
    "download_pausado": "Transferência em pausa. O que já foi transferido fica guardado.",
    "continuar_download": "Continuar",
    "descartar": "Descartar",
    "voz_feminina": "Feminina",
    "voz_feminina_desc": "Suave e calma",
    "voz_masculina": "Masculina",
    "voz_masculina_desc": "Calorosa e serena",
    "parar_amostra": "Parar amostra",
    "ouvir_amostra_de": "Ouvir amostra: {voz}",
    "escolha_a_voz": "Escolha a voz",
    "qualidade": "Qualidade",
    "q_auto": "Automática",
    "q_rapida": "Rápida",
    "q_maxima": "Máxima",
    "q_auto_desc": "Ajusta-se automaticamente ao desempenho do aparelho, para a leitura não ter pausas.",
    "q_rapida_desc": "Gera a voz mais depressa. Boa para aparelhos mais simples.",
    "q_maxima_desc": "Som mais cuidado. Em aparelhos simples, pode causar pausas entre as frases.",
    "ocupa": "Ocupa {tamanho} neste aparelho",
    "remover": "Remover",
    "baixar_pelos_dados": "Transferir com dados móveis?",
    "baixar_pelos_dados_msg": "Parece que o aparelho não está ligado a uma rede Wi-Fi. A transferência tem {tamanho} e pode gastar o seu plano de dados.",
    "baixar_agora": "Transferir mesmo assim",
    "pronta": "A voz natural está pronta.",
    "download_interrompido": "A transferência parou. Toque em Continuar quando quiser.",
    "remover_titulo": "Remover a voz natural?",
    "descartar_titulo": "Descartar a transferência?",
    "remover_msg": "Isto liberta {tamanho}. A leitura volta à voz do sistema, e pode transferi-la novamente quando quiser.",
    "descartar_msg": "O que já foi transferido será apagado.",
    "removida": "Voz natural removida deste aparelho.",
    "amostra_falhou": "Não foi possível reproduzir a amostra neste aparelho.",
    "amostra": "Olá! É assim que os seus livros vão soar com a voz natural.",
    "gerando_voz": "A preparar a voz…",
    "automatico_idioma": "Automático ({idioma})",
    "automatico": "Automático",
    "so_voz_do_sistema": "voz do sistema",
    "aviso_idioma": "Idioma do texto: {idioma}. A voz natural ainda não fala este idioma, por isso o livro será lido pela voz do sistema.",
    "aviso_idioma_desconhecido": "Não foi possível reconhecer o idioma deste texto. Escolha o idioma abaixo para usar a voz natural.",
    "aviso_falha": "De momento, a voz natural não consegue funcionar neste aparelho. A leitura continua com a voz do sistema.",
    "nao_carregou_usando_sistema": "A voz natural não carregou neste aparelho. A leitura segue com a voz do sistema.",
    "parou_usando_sistema": "A voz natural parou. A leitura continua com a voz do sistema.",
    "aparelho_lento": "Este aparelho está a gerar a voz devagar. Escolha a qualidade Rápida para evitar pausas.",
    "idioma_do_texto": "Idioma do texto",
    "idioma_do_texto_dica": "Reconhecido a partir do próprio texto. Altere-o se a pronúncia não soar bem.",
    "leitura_em_voz_alta": "Leitura em voz alta",
    "lento_usando_sistema": "A voz natural ficou demasiado lenta neste aparelho. A leitura continua com a voz do sistema.",
    "aviso_lento": "Este aparelho não consegue gerar a voz natural à velocidade da leitura, por isso a voz do sistema assumiu por agora.",
    "sem_memoria_usando_sistema": "A voz natural não coube na memória deste aparelho. A leitura segue com a voz do sistema.",
    "aviso_falha_memoria": "Não houve memória suficiente para a voz natural neste aparelho. Fechar outras aplicações e tentar de novo costuma resolver; entretanto, a leitura usa a voz do sistema.",
    "copiar_detalhe": "Copiar detalhe",
    "copiado": "Detalhe copiado.",
    "falhou_titulo": "A voz natural não carregou neste aparelho.",
    "falhou_texto": "O aparelho não conseguiu montar a voz natural. A leitura segue com a voz do sistema. Se quiser ajudar a resolver, copie o detalhe abaixo e envie para o suporte.",
    "falhou_memoria_texto": "Faltou memória para a voz natural neste aparelho. Fechar outras aplicações e tentar de novo costuma resolver.",
    "tentar_de_novo": "Tentar de novo",
    "tentando": "A carregar…",
    "aviso_aparelho_justo": "Este aparelho tem pouca memória para a voz natural. Pode não carregar; nesse caso, basta removê-la e recuperar o espaço.",
    "preparando_demora": "A preparar a voz. Isto pode demorar alguns minutos.",
    "incompativel_titulo": "A voz natural não funciona neste aparelho.",
    "incompativel_memoria": "Não houve memória suficiente para a montar. A leitura fica com a voz do sistema, e as opções dela aparecem abaixo.",
    "incompativel_lento": "Ficou demasiado lenta para acompanhar a leitura. A leitura fica com a voz do sistema, e as opções dela aparecem abaixo.",
    "incompativel_queda": "A aplicação foi encerrada enquanto ela carregava. A leitura fica com a voz do sistema, e as opções dela aparecem abaixo.",
    "incompativel_falha": "Não conseguiu carregar aqui. A leitura fica com a voz do sistema, e as opções dela aparecem abaixo.",
    "testar_de_novo": "Testar de novo",
    "remover_e_liberar": "Remover e libertar {tamanho}",
    "tela_durante_a_leitura": "Ecrã durante a leitura",
    "manter_tela_ligada": "Manter o ecrã ligado",
    "manter_tela_ligada_dica": "Enquanto um livro estiver aberto, o ecrã não se desliga sozinho. Ao fechar o livro, tudo volta ao normal."
  }
});