/* ============================================================
   RUSSIAN — complete translation
   ------------------------------------------------------------
   This file contains the complete Russian translation and keeps
   the same keys, structure, plural blocks and placeholders as
   the English base file.
   ============================================================ */
Idiomas.registrar('ru', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "Закладка удалена.",
    "excluir_marcador": "Удалить закладку",
    "o_marcador_sera_removido_permanentemen": "Закладка будет удалена окончательно.",
    "excluir_marcador_2": "Удалить закладку?",
    "pagina_salva": "Страница сохранена",
    "anotacoes": "Заметки",
    "citacoes": "Цитаты",
    "item_excluido": "Элемент удалён.",
    "este_registro_sera_removido_permanente": "Эта запись будет навсегда удалена из библиотеки.",
    "configuracoes_padrao_restauradas": "Настройки по умолчанию восстановлены.",
    "leitura_da_esquerda_para_a_direita": "Чтение слева направо.",
    "leitura_da_direita_para_a_esquerda_man": "Чтение справа налево (манга).",
    "a_pagina_inteira_passa_a_caber_na_tela": "Теперь вся страница помещается на экране.",
    "a_pagina_passa_a_ocupar_toda_a_largura": "Теперь страница заполняет всю ширину экрана.",
    "virada_sem_animacao_ativada": "Теперь страницы перелистываются без анимации.",
    "virada_deslizante_ativada": "Включено плавное перелистывание.",
    "virada_em_folha_real_ativada": "Включено реалистичное перелистывание страниц.",
    "padrao_automatico_cada_formato_abre_no": "Автоматически: каждый формат открывается наиболее подходящим способом.",
    "mudando_durante_a_leitura_o_ajuste_fic": "Если изменить это во время чтения, изменение сохранится только для этой книги.",
    "automatico_usa_rolagem_horizontal_para": "Автоматически используется горизонтальное перелистывание для EPUB, MOBI, TXT, MD и комиксов и вертикальная прокрутка для PDF и DOCX.",
    "este_livro": "эту книгу",
    "armazenamento_local_indisponivel_neste": "Локальное хранилище недоступно в этом браузере.",
    "o_aplicativo_pode_procurar_os_livros_q": "Приложение может найти книги, уже сохранённые на вашем устройстве.",
    "vamos_montar_sua_estante": "Заполнить вашу полку?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "Без вашего согласия приложение нельзя использовать.",
    "precisamos_do_seu_aceite": "Нам нужно ваше согласие",
    "antes_de_comecar_leia_e_aceite_os_docu": "Перед началом прочитайте и примите документы ниже.",
    "selecionar_todos": "Выбрать всё",
    "limpar_selecao": "Снять выделение",
    "todos_parecem_ja_estar_na_sua_estante": "Похоже, все они уже есть на вашей полке.",
    "lendo_a_pasta_escolhida": "Читаем выбранную вами папку…",
    "procurando_livros": "Поиск книг",
    "nao_foi_possivel_concluir_a_busca_no_d": "Не удалось завершить поиск на этом устройстве.",
    "tente_outra_pasta_do_aparelho": "Попробуйте другую папку на устройстве.",
    "nenhum_livro_encontrado": "Книги не найдены",
    "use_o_botao_para_escolher_os_arquivos": "Используйте кнопку +, чтобы выбрать файлы вручную. На телефонах Android Chrome обычно позволяет выбрать целую папку.",
    "seu_navegador_nao_permite_ler_pastas": "Ваш браузер не сможет читать папки",
    "busca_automatica_indisponivel": "Автоматический поиск недоступен",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR и M4B",
    "termos_de_uso": "Условия использования",
    "politica_de_privacidade": "Политика конфиденциальности",
    "um_minuto_agora_evita_perder_o_progres": "Минута сейчас поможет не потерять прогресс и отметки позже.",
    "ver_estante": "Открыть полку",
    "modo_juntar": "Режим объединения",
    "modo_substituir": "Режим замены",
    "restauracao_concluida": "Восстановление завершено",
    "tente_de_novo_com_o_arquivo_original": "Попробуйте ещё раз с исходным файлом.",
    "a_restauracao_nao_pode_ser_concluida": "Не удалось завершить восстановление",
    "devolvendo_o_seu_progresso_e_as_suas_m": "Восстанавливаем ваш прогресс и отметки...",
    "restaurar_este_backup": "Восстановить эту резервную копию?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "Выберите сохранённый Veredas файл .zip или полученный через отправку файл .txt.",
    "nao_foi_possivel_ler_este_arquivo": "Не удалось прочитать этот файл",
    "lendo_o_backup": "Читаем резервную копию",
    "backup_do_veredas_reader": "Резервная копия Veredas Reader",
    "arquivo_de_transporte_txt_contendo_os": "резервная копия в формате .txt с тем же содержимым, что и ZIP",
    "nao_foi_possivel_montar_o_arquivo_de_b": "Не удалось создать файл резервной копии.",
    "escolher_o_app": "Выберите приложение",
    "vale_conferir_o_que_vai_no_arquivo": "Проверьте, что будет записано в файл",
    "enviar_para_outro_app": "Отправить в другое приложение",
    "salvar_o_arquivo": "Сохранить файл",
    "o_navegador_aqui_nao_oferece_o_compart": "Этот браузер не поддерживает прямую отправку. Вы можете сохранить файл и отправить его позже через любое удобное приложение.",
    "este_aparelho_nao_abre_a_lista_de_apli": "Это устройство не открывает список приложений",
    "importe_pelo_menos_um_livro_antes_de_f": "Перед созданием резервной копии импортируйте хотя бы одну книгу.",
    "estante_vazia": "Пустая полка",
    "nao_deu_para_copiar": "Не удалось скопировать",
    "copiar_detalhes": "Копировать сведения",
    "o_backup_foi_salvo_assim_mesmo": "Резервная копия всё равно была сохранена",
    "o_aparelho_recusou_abrir_a_lista": "Не удалось открыть список для отправки",
    "sem_detalhes_do_navegador": "нет сведений от браузера",
    "o_sistema_nao_aceitou_receber_o_arquiv": "Системе устройства не удалось получить файл.",
    "o_navegador_considerou_a_situacao_inse": "Браузер заблокировал отправку из-за собственных правил безопасности. Сохраните файл и отправьте его через любое удобное приложение.",
    "o_compartilhamento_so_funciona_em_ende": "Отправка работает только по защищённым адресам. Это приложение открыто по обычному адресу http://, поэтому браузер блокирует отправку в другие приложения.",
    "este_navegador_nao_conseguiu_iniciar_o": "Этому браузеру не удалось открыть отправку. Сохраните файл и отправьте его через любое удобное приложение.",
    "o_navegador_recebeu_um_arquivo_em_form": "Браузер не открыл список приложений для отправки. Нажмите кнопку ещё раз или сохраните файл и отправьте его через любое удобное приложение.",
    "nao_foi_possivel_gerar_o_backup": "Не удалось создать резервную копию.",
    "reunindo_a_sua_estante": "Собираем вашу полку...",
    "preparando_o_backup": "Подготавливаем резервную копию",
    "pronto_nada_mais_esta_esperando": "Готово — больше ничего не ожидает.",
    "o_progresso_e_as_marcacoes_desses_livr": "Прогресс и отметки этих книг будут удалены. Если позже импортировать файлы снова, книги появятся без прогресса и отметок.",
    "descartar_o_que_esta_esperando": "Удалить ожидающие данные?",
    "lembretes_de_backup_religados": "Напоминания о резервном копировании снова включены.",
    "sem_titulo": "Без названия",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "Напоминания отключены.",
    "manter_ligado": "Оставить включёнными",
    "desligar_assim_mesmo": "Всё равно отключить",
    "o_botao_de_salvar_continua_onde_sempre": "Кнопка сохранения остаётся там же, где и раньше, в разделе «Резервное копирование и восстановление».",
    "o_lembrete_e_o_unico_aviso_que_existe": "Напоминание — единственное предупреждение. Без него о резервном копировании придётся помнить самостоятельно.\n\n",
    "limpar_os_dados_do_navegador_desinstal": "Если данные браузера будут очищены, приложение удалено, вы смените телефон или устройство выйдет из строя, восстановить прогресс, выделения, цитаты, заметки и закладки не получится.\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "Ваша полка существует только на этом устройстве. Копии на серверах нет, поэтому восстановить её для вас невозможно.\n\n",
    "leia_antes_de_confirmar": "Прочитайте перед подтверждением",
    "desligar_os_lembretes_de_backup": "Отключить напоминания о резервном копировании?",
    "progresso_de_leitura_restaurado_neste": "Прогресс чтения для этой книги восстановлен.",
    "pronto": "Готово.",
    "aplicando_as_suas_preferencias": "Применяем ваши настройки...",
    "atualize_o_veredas_reader_e_tente_de_n": "Обновите Veredas Reader и попробуйте снова.",
    "este_backup_foi_feito_numa_versao_mais": "Эта резервная копия была создана в более новой версии приложения.",
    "este_arquivo_nao_e_um_backup_de_biblio": "Этот файл не является резервной копией библиотеки Veredas.",
    "o_conteudo_interno_nao_pode_ser_lido": "Не удалось прочитать содержимое внутри.",
    "o_backup_esta_corrompido": "Резервная копия повреждена.",
    "falta_o_arquivo_biblioteca_json_la_den": "Внутри отсутствует файл biblioteca.json.",
    "este_arquivo_nao_parece_ser_um_backup": "Этот файл не похож на резервную копию Veredas.",
    "compactando": "Сжимаем...",
    "para_restaurar_menu_lateral_backup_e_r": "Для восстановления: боковое меню > Резервное копирование и восстановление > Восстановить резервную копию.",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas автоматически восстанавливает отметки и место, на котором вы остановились.",
    "importe_os_livros_normalmente_no_aplic": "импортируйте книги обычным способом в приложение: как только оно распознает каждый файл,",
    "ele_nao_contem_os_arquivos_dos_livros": "Он НЕ содержит файлы книг. Для полного восстановления,",
    "as_notas_os_marcadores_e_a_organizacao": "ваши заметки, закладки и порядок вашей полки.",
    "este_arquivo_guarda_o_seu_progresso_de": "В этом файле хранятся ваш прогресс чтения, выделения, цитаты,",
    "verificando_se_sao_partes_do_mesmo_aud": "Проверяем, являются ли эти файлы частями одной аудиокниги...",
    "analisando_os_arquivos": "Читаем файлы",
    "nao_foi_possivel_salvar_o_audiolivro": "Не удалось сохранить аудиокнигу.",
    "audiolivros_grandes_podem_levar_alguns": "Большим аудиокнигам может понадобиться немного времени...",
    "salvando_na_sua_estante": "Сохраняем на вашу полку",
    "falha_ao_processar_os_arquivos": "Не удалось обработать файлы.",
    "falha_ao_processar_o_arquivo": "Не удалось обработать файл.",
    "nao_foi_possivel_salvar_o_quadrinho": "Не удалось сохранить комикс.",
    "quase_la": "Почти готово...",
    "falha_ao_processar_o_quadrinho": "Не удалось обработать комикс.",
    "autor_desconhecido": "Неизвестный автор",
    "lendo_o_quadrinho": "Читаем комикс...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "Не удалось сохранить книгу в библиотеке.",
    "nao_foi_possivel_ler_o_pdf": "Не удалось прочитать PDF.",
    "lendo_o_pdf": "Читаем PDF...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "Если это старый .doc, откройте его в Word и сохраните как .docx перед импортом.",
    "este_arquivo_nao_e_um_docx_valido": "Этот файл не является корректным .docx.",
    "livros_com_protecao_da_amazon_nao_pode": "Книги с защитой Amazon здесь не открываются. Используйте копию без DRM или преобразуйте книгу в EPUB.",
    "este_arquivo_esta_protegido_por_drm": "Этот файл защищён DRM.",
    "confira_se_a_extensao_corresponde_ao_c": "Проверьте, соответствует ли расширение содержимому, или преобразуйте книгу в EPUB.",
    "este_arquivo_nao_e_um_mobi_valido": "Этот файл не является корректным MOBI.",
    "nao_foi_possivel_ler_o_arquivo": "Не удалось прочитать файл.",
    "formato_nao_suportado": "Формат не поддерживается.",
    "falha_ao_salvar_o_livro_na_biblioteca": "Не удалось сохранить книгу в библиотеке.",
    "livro_importado_e_salvo_no_dispositivo": "Книга импортирована и сохранена на этом устройстве.",
    "audiolivro_importado_e_salvo_no_dispos": "Аудиокнига импортирована и сохранена на этом устройстве.",
    "quadrinho_importado_e_salvo_no_disposi": "Комикс импортирован и сохранён на этом устройстве.",
    "salvando_na_sua_estante_2": "Сохраняем на вашу полку...",
    "importando_livro": "Импорт книги",
    "importar_mesmo_assim": "Всё равно импортировать",
    "parece_que_este_livro_ja_esta_na_estan": "Похоже, эта книга уже есть на вашей полке",
    "este_livro_ja_esta_na_estante": "Эта книга уже на вашей полке",
    "video_importado_e_salvo_no_dispositivo": "Видео импортировано и сохранено на этом устройстве.",
    "importacao_cancelada": "Импорт отменён.",
    "preparando_o_arquivo": "Подготавливаем файл",
    "importando_audiolivro": "Импортируем аудиокнигу",
    "importacao_concluida": "Импорт завершён",
    "importacao_interrompida": "Импорт остановлен",
    "a_importacao_foi_interrompida_o_que_ja": "Импорт был остановлен; всё, что уже было добавлено, остаётся на вашей полке.",
    "finalizando": "Завершаем…",
    "nao_foi_possivel_ler_o_arquivo_2": "не удалось прочитать файл",
    "importando_livros": "Импортируем книги",
    "livros_quadrinhos_documentos_audiolivr": "Книги, комиксы, документы, аудиокниги и видео",
    "series": "Серии",
    "colecoes": "Коллекции",
    "organizacao_salva": "Организация сохранена.",
    "informe_um_nome_para_o_livro_antes_de": "Перед сохранением укажите название книги.",
    "nome_do_livro_obrigatorio": "Книге нужно название",
    "importe_um_livro_primeiro": "Сначала импортируйте книгу.",
    "citacao": "цитата",
    "anotacao": "заметка",
    "citacao_2": "Цитата",
    "anotacao_2": "Заметка",
    "uma_citacao": "цитата",
    "uma_anotacao": "заметка",
    "o_marcador_sera_removido_da_biblioteca": "Закладка будет удалена из библиотеки, но файл книги останется нетронутым.",
    "marcador_de_audio": "Закладка в аудио",
    "marcador_de_video": "Закладка в видео",
    "nao_foi_possivel_excluir_o_livro": "Не удалось удалить книгу.",
    "livro_excluido_da_biblioteca": "Книга удалена из библиотеки.",
    "excluir_livro": "Удалить книгу",
    "isso_remove_apenas_a_copia_armazenada": "Будет удалена только копия, которую хранит библиотека, вместе с прогрессом, закладками и заметками. Исходный файл в вашей папке удалён не будет.",
    "excluir_livro_2": "Удалить книгу?",
    "ordem_personalizada_salva": "Пользовательский порядок сохранён.",
    "ordem_manual_da_sua_estante": "Ваша полка в установленном вами порядке.",
    "agrupamento_alterado_para_minha_ordem": "Группировка переключена на «Мой порядок».",
    "nova_ordem_salva": "Новый порядок сохранён.",
    "nao_foi_possivel_salvar_a_nova_ordem": "Не удалось сохранить новый порядок.",
    "baixar_automaticamente": "Скачивать автоматически",
    "escolha_livremente_onde_o_arquivo_sera": "Свободно выберите место сохранения файла.",
    "salvar_epub": "Сохранить EPUB",
    "livro_epub": "Книга EPUB",
    "erro_desconhecido": "неизвестная ошибка",
    "a_permissao_para_salvar_o_arquivo_foi": "Разрешение на сохранение файла отменено. В библиотеке ничего не изменилось.",
    "conversao_cancelada_o_pdf_original_per": "Преобразование отменено. Исходный PDF остаётся в библиотеке.",
    "preparando_salvamento": "Подготавливаем сохранение…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "Копия PDF недоступна в библиотеке.",
    "reconstruindo_o_livro_localmente": "Восстанавливаем книгу на вашем устройстве.",
    "convertendo_pdf": "Преобразование PDF",
    "nao_foi_possivel_compartilhar_o_livro": "Не удалось поделиться книгой.",
    "o_arquivo_foi_preparado_para_voce_comp": "Файл готов для отправки в другое приложение.",
    "livro_compartilhado": "Книга отправлена.",
    "a_copia_deste_livro_nao_esta_disponive": "Копия этой книги недоступна в библиотеке.",
    "para_manter_a_politica_de_compartilham": "Чтобы соблюдать политику совместного использования библиотеки, файлы EPUB и MOBI нельзя отправлять через это приложение.",
    "quadrinhos_ficam_guardados_somente_no": "Комиксы хранятся только на вашем устройстве и не могут быть отправлены через это приложение.",
    "audiolivros_e_videos_ficam_guardados_s": "Аудиокниги и видео хранятся только на вашем устройстве и не могут быть отправлены через это приложение.",
    "formato_protegido": "Защищённый формат",
    "compartilhamento_indisponivel": "Отправка недоступна",
    "concluido": "Завершено",
    "ainda_nao_comecado": "Ещё не начато",
    "continue_lendo": "Продолжить чтение",
    "continue_ouvindo": "Продолжить слушать",
    "continue_assistindo": "Продолжить просмотр",
    "comece_por_aqui": "Начните отсюда",
    "comece_a_ouvir": "Начать слушать",
    "comece_a_assistir": "Начать просмотр",
    "no_total": "всего",
    "para_ler": "для чтения",
    "sua_estante": "Ваша полка",
    "livros_organizados_pela_opcao_selecion": "Книги расположены согласно выбранному вами варианту.",
    "uma_prateleira_para_cada_tipo_de_arqui": "Отдельная полка для каждого типа файла.",
    "autores_agrupados_em_ordem_alfabetica": "Авторы сгруппированы в алфавитном порядке.",
    "toque_para_continuar_de_onde_parou": "Нажмите, чтобы продолжить с места, где вы остановились.",
    "para_ler_2": "К чтению",
    "lendo_agora": "Сейчас читается",
    "audio_e_video": "Аудио и видео",
    "trechos_salvos_separadamente_dos_marca": "Фрагменты, сохранённые отдельно от закладок.",
    "comentarios_vinculados_a_trechos_selec": "Комментарии, привязанные к выбранным фрагментам.",
    "paginas_salvas_para_voltar_rapidamente": "Страницы, сохранённые для быстрого возврата.",
    "do_maior_para_o_menor_progresso_de_lei": "От большего прогресса чтения к меньшему.",
    "livros_adicionados_ou_lidos_mais_recen": "Книги, добавленные или прочитанные недавно.",
    "ordem_alfabetica_pelo_titulo": "В алфавитном порядке по названию.",
    "separa_em_prateleiras_de_epub_pdf_docx": "Разделяет на полки EPUB, PDF, DOCX, аудиокниги, видео…",
    "tipo_de_arquivo": "Тип файла",
    "organiza_e_separa_os_livros_por_autor": "Располагает и разделяет книги по автору.",
    "agrupar_por_autor": "Группировать по автору",
    "pressione_o_livro_e_mova_o": "Нажмите и удерживайте книгу, затем переместите её.",
    "minha_ordem": "Мой порядок",
    "epub_pronto": "EPUB готов",
    "conversao_concluida": "Преобразование завершено",
    "necessario_para_salvar_o_epub_ao_lado": "Нужно, чтобы сохранить EPUB рядом с оригиналом",
    "escolha_a_pasta_do_pdf": "Выберите папку PDF",
    "processando": "Обработка…",
    "processamento_local_no_navegador": "Обработано на вашем устройстве, в браузере",
    "convertendo_livro": "Преобразование книги",
    "livro_em_pdf": "Книга PDF",
    "recalculando_paginas": "Пересчитываем страницы...",
    "ajustando_leitura": "Настраиваем макет",
    "abrir_comentario": "Открыть комментарий",
    "anotacao_salva": "Заметка сохранена.",
    "anotacao_atualizada": "Заметка обновлена.",
    "escreva_uma_nota_antes_de_salvar": "Напишите заметку перед сохранением.",
    "nao_foi_possivel_compartilhar": "Не удалось поделиться.",
    "compartilhamento_indisponivel_2": "Отправка недоступна.",
    "credito_do_trecho": "— {obra}, {autor}",
    "credito_do_trecho_sem_autor": "— {obra}",
    "trecho_copiado": "Фрагмент скопирован.",
    "trecho_compartilhado": "Фрагмент отправлен.",
    "citacao_salva": "Цитата сохранена.",
    "trecho_grifado": "Фрагмент выделен.",
    "grifo_removido": "Выделение удалено.",
    "comentario_apagado": "Комментарий удалён.",
    "remover_grifo": "Убрать выделение",
    "apagar_comentario": "Удалить комментарий",
    "remover_grifo_2": "Убрать выделение?",
    "apagar_comentario_2": "Удалить комментарий?",
    "remover_este_grifo": "Убрать это выделение?",
    "apagar_este_comentario": "Удалить этот комментарий?",
    "sem_comentario": "Без комментария",
    "comentario": "Комментарий",
    "marcador_removido_desta_pagina": "Закладка удалена с этой страницы.",
    "pagina_adicionada_aos_marcadores": "Страница добавлена в ваши закладки.",
    "este_e_o_inicio_do_livro": "Это начало книги.",
    "esta_e_a_primeira_pagina": "Это первая страница.",
    "voce_chegou_ao_fim_do_livro": "Вы достигли конца книги.",
    "voce_chegou_ao_fim_do_quadrinho": "Вы достигли конца комикса.",
    "agora_em_revista_aberta_duas_paginas_l": "Теперь отображается разворот: две страницы рядом, а обложка отдельно.",
    "leitura_horizontal_ativada_neste_livro": "Горизонтальное чтение включено для этой книги.",
    "rolagem_vertical_ativada_neste_livro": "Вертикальная прокрутка включена для этой книги.",
    "leitura_pagina_a_pagina_ativada_neste": "Постраничное чтение включено для этого комикса.",
    "rolagem_continua_ativada_neste_quadrin": "Непрерывная прокрутка включена для этого комикса.",
    "mudar_para_rolagem_vertical": "Переключить на вертикальную прокрутку",
    "mudar_para_leitura_horizontal": "Переключить на горизонтальное чтение",
    "rolagem_continua_estilo_webtoon": "Непрерывная прокрутка (стиль вебтуна)",
    "voltar_para_pagina_a_pagina": "Вернуться к постраничному чтению",
    "separando_os_capitulos": "Разделяем главы...",
    "lendo_o_livro": "Читаем книгу",
    "lendo_o_markdown": "Читаем Markdown",
    "lendo_o_documento": "Читаем документ",
    "pagina_indisponivel": "Страница недоступна.",
    "isto_acontece_so_desta_vez": "Это происходит только в первый раз.",
    "preparando_o_quadrinho": "Подготавливаем комикс",
    "abrindo_o_quadrinho": "Открываем комикс...",
    "montando_as_paginas": "Создаём страницы...",
    "nao_foi_possivel_abrir_este_livro": "Не удалось открыть эту книгу.",
    "abertura_cancelada": "Открытие отменено.",
    "o_livro_demorou_demais_para_abrir_e_fo": "Книга открывалась слишком долго, поэтому процесс был остановлен.",
    "importe_o_arquivo_novamente_para_conti": "Импортируйте файл снова, чтобы продолжить чтение.",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "Файл этой книги больше не сохранён на вашем устройстве.",
    "preparando_sua_leitura": "Готовим книгу к чтению...",
    "abrindo_livro": "Открываем книгу",
    "leitura_concluida": "Чтение завершено.",
    "a_voz_foi_interrompida_pelo_navegador": "Браузер остановил воспроизведение голоса.",
    "nao_foi_possivel_preparar_este_trecho": "Не удалось подготовить этот фрагмент для озвучивания.",
    "a_leitura_em_voz_alta_nao_e_suportada": "В этом браузере не поддерживается чтение вслух.",
    "pausar_leitura": "Приостановить чтение",
    "em_pausa": "Приостановлено",
    "leitura_em_voz_alta_nao_disponivel_nes": "Чтение вслух недоступно в этом браузере",
    "nome_do_marcador": "Название закладки",
    "o_marcador_sera_removido_deste_audioli": "Закладка будет удалена из этой аудиокниги.",
    "nao_foi_possivel_salvar_o_marcador": "Не удалось сохранить закладку.",
    "ja_existe_um_marcador_neste_ponto": "В этом месте уже есть закладка.",
    "timer_de_sono_encerrado": "Таймер сна завершён.",
    "fim_do_cap": "Конец гл.",
    "timer_desativado": "Таймер отключён.",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "Аудио будет приостановлено в конце главы.",
    "este_audiolivro_nao_tem_capitulos": "В этой аудиокниге нет глав.",
    "ao_fim_do_capitulo": "В конце главы",
    "desativar_timer": "Отключить таймер",
    "mais_10_minutos_no_timer": "Ещё 10 минут по таймеру.",
    "somar_10_minutos": "Добавить 10 минут",
    "pausa_ao_fim_do_capitulo": "Пауза в конце главы",
    "no_livro_todo": "По всей книге",
    "video": "Видео",
    "audiolivro_concluido": "Аудиокнига завершена.",
    "video_concluido": "Видео завершено.",
    "video_2": "видео",
    "audio": "аудио",
    "toque_em_reproduzir_para_comecar": "Нажмите «Воспроизвести», чтобы начать.",
    "falha_ao_carregar_o_audio": "Не удалось загрузить аудио.",
    "exclua_o_da_biblioteca_e_importe_o_arq": "Удалите его из библиотеки и импортируйте файл снова.",
    "os_nomes_dos_arquivos_seguem_uma_seque": "Имена файлов образуют последовательность, поэтому они похожи на главы одной аудиокниги.",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "В тегах файлов указан один и тот же альбом, поэтому они похожи на главы одной аудиокниги.",
    "libere_espaco_ou_exclua_livros_da_bibl": "Освободите место или удалите книги из библиотеки и попробуйте снова.",
    "o_armazenamento_do_aparelho_esta_cheio": "Хранилище устройства заполнено.",
    "preparando_a_capa": "Подготавливаем обложку...",
    "remova_esse_arquivo_da_selecao_e_tente": "Удалите этот файл из выбранных и попробуйте снова.",
    "sequencia": "последовательность",
    "o_arquivo_pode_estar_incompleto_tente": "Файл может быть неполным. Попробуйте скачать его ещё раз.",
    "conferindo_se_o_audio_pode_ser_reprodu": "Проверяем, можно ли воспроизвести аудио...",
    "conferindo_se_o_video_pode_ser_reprodu": "Проверяем, можно ли воспроизвести видео...",
    "lendo_titulo_capitulos_e_capa": "Читаем название, главы и обложку...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "Файл может быть повреждён или записан в аудиоформате, который браузер не воспроизводит. Попробуйте преобразовать его в MP3 или M4B (AAC).",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "Файл может быть повреждён или записан в видеоформате, который браузер не воспроизводит. Попробуйте преобразовать его в MP4 с видео H.264 и звуком AAC.",
    "converta_o_audiolivro_para_m4b_com_aud": "Преобразуйте аудиокнигу в M4B с аудио AAC (или в MP3) и импортируйте её снова.",
    "converta_o_video_para_mp4_com_audio_aa": "Преобразуйте видео в MP4 с аудио AAC и видео H.264 и импортируйте его снова.",
    "o_navegador_nao_reproduz_o_formato_de": "Браузер не воспроизводит аудиоформат этого файла.",
    "arquivos_com_protecao_nao_podem_ser_re": "Защищённые файлы здесь воспроизвести нельзя. Используйте копию без DRM.",
    "nao_ha_espaco_suficiente_no_aparelho_p": "На устройстве недостаточно места для этой аудиокниги.",
    "confira_se_a_extensao_corresponde_ao_c_2": "Проверьте, соответствует ли расширение содержимому, или преобразуйте аудио в MP3 или M4B (AAC).",
    "imagem_invalida": "недопустимое изображение",
    "imagem_demorou_demais": "изображение загружалось слишком долго",
    "imagem_vazia": "пустое изображение",
    "inicio": "Начало",
    "mp4_moov_nao_encontrado": "Похоже, видео неполное или повреждено.",
    "pagina": "Страница",
    "esta_pagina_nao_esta_disponivel": "Эта страница недоступна.",
    "esta_pagina_nao_pode_ser_descompactada": "Не удалось распаковать эту страницу.",
    "quadrinho_fechado": "Комикс закрыт.",
    "ele_pode_estar_incompleto_dividido_em": "Он может быть неполным, разделённым на несколько частей или записанным в варианте RAR, который приложение не распознаёт. Обычно преобразование в CBZ решает проблему.",
    "remova_a_senha_do_arquivo_e_importe_de": "Удалите пароль с файла и импортируйте его снова.",
    "nao_foi_possivel_ler_este_arquivo_de_q": "Не удалось прочитать этот файл комикса.",
    "este_quadrinho_esta_protegido_por_senh": "Этот комикс защищён паролем.",
    "lendo_o_indice_do_quadrinho": "Читаем индекс комикса...",
    "o_arquivo_pode_ser_grande_demais_para": "Файл может быть слишком большим для памяти этого устройства. Обычно помогает разделить комикс на несколько частей.",
    "nao_foi_possivel_abrir_este_quadrinho": "Не удалось открыть этот комикс.",
    "lendo_o_arquivo": "Читаем файл...",
    "preparando_o_leitor_de_cbr": "Подготавливаем средство чтения CBR...",
    "o_arquivo_pode_estar_incompleto_proteg": "Файл может быть неполным, защищённым паролем или повреждённым.",
    "nao_foi_possivel_ler_este_quadrinho": "Не удалось прочитать этот комикс.",
    "o_arquivo_precisa_conter_imagens_jpg_p": "Файл должен содержать изображения (JPG, PNG, WEBP или GIF).",
    "nao_encontramos_paginas_dentro_deste_q": "В этом комиксе не найдено страниц.",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "На устройстве недостаточно места для этого комикса.",
    "cabecalho_de_item_invalido": "Часть файла повреждена.",
    "a_pasta_vendor_libarchive_precisa_esta": "Приложению не хватает компонента, чтобы открыть этот комикс. Преобразуйте его в CBZ или переустановите приложение.",
    "o_leitor_de_cbr_nao_foi_encontrado": "Средство чтения CBR не найдено.",
    "converta_o_quadrinho_para_cbz_zip_e_im": "Преобразуйте комикс в CBZ (ZIP) и импортируйте его снова.",
    "este_navegador_nao_consegue_abrir_arqu": "Этот браузер не может открывать файлы CBR.",
    "convertendo_o_markdown": "Преобразуем Markdown",
    "lendo_o_texto": "Читаем текст",
    "pdf_indisponivel": "PDF недоступен.",
    "epub_invalido_nenhum_capitulo_no_spine": "Этот EPUB повреждён: не удалось найти главы книги.",
    "livro_sem_titulo": "Книга без названия",
    "epub_invalido_arquivo_opf_nao_encontra": "Этот EPUB неполный или повреждён, поэтому его не удаётся открыть.",
    "epub_invalido_container_xml_nao_encont": "Этот EPUB неполный или повреждён, поэтому его не удаётся открыть.",
    "organizando_o_texto": "Размещаем текст",
    "descompactando_o_livro": "Распаковываем книгу",
    "nao_encontramos_conteudo_para_exibir_n": "В этом файле нечего показать.",
    "livro_sem_texto_legivel": "Книга без читаемого текста",
    "o_arquivo_pode_estar_corrompido_tente": "Файл может быть повреждён. Попробуйте преобразовать его в EPUB.",
    "nao_foi_possivel_extrair_o_texto_deste": "Не удалось извлечь текст из этого MOBI.",
    "nenhum_registro_de_conteudo_foi_encont": "В этом файле не удалось найти текст книги.",
    "arquivo_mobi_sem_texto": "Файл MOBI без текста.",
    "o_dicionario_de_compressao_esta_vazio": "Часть содержимого этого MOBI отсутствует.",
    "arquivo_mobi_incompleto": "Неполный файл MOBI.",
    "as_tabelas_de_compressao_nao_foram_enc": "Часть содержимого этого MOBI отсутствует.",
    "converta_o_arquivo_para_epub_em_um_pro": "Преобразуйте файл в EPUB с помощью программы вроде Calibre и импортируйте его снова.",
    "compressao_mobi_nao_reconhecida": "Этот MOBI использует внутренний формат, который приложение не распознаёт.",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "Не удалось прочитать заголовок книги.",
    "arquivo_mobi_corrompido": "Повреждённый файл MOBI.",
    "a_lista_interna_de_registros_esta_inco": "Файл неполный. Попробуйте скачать или преобразовать его заново.",
    "o_download_parece_ter_sido_interrompid": "Похоже, загрузка была прервана. Скачайте файл ещё раз.",
    "tabela_de_compressao_mobi_corrompida": "Часть этого файла MOBI повреждена.",
    "tabela_de_compressao_mobi_incompleta": "Этот файл MOBI неполный.",
    "tabela_de_compressao_mobi_invalida": "Часть этого файла MOBI повреждена.",
    "este_arquivo_docx_nao_tem_conteudo_de": "Этот файл .docx не содержит отображаемого текстового содержимого.",
    "documento_sem_texto": "Документ без текста",
    "o_arquivo_pode_estar_corrompido_proteg": "Файл может быть повреждён, защищён паролем или быть старым .doc. Снова сохраните его как .docx и импортируйте ещё раз.",
    "nao_foi_possivel_ler_este_arquivo_docx": "Не удалось прочитать этот файл DOCX.",
    "convertendo_o_documento": "Преобразуем документ",
    "conecte_se_a_internet_uma_vez_para_bai": "Подключитесь к интернету один раз, чтобы скачать компонент, затем снова откройте книгу.",
    "o_conversor_de_docx_nao_carregou": "Конвертер DOCX не загрузился.",
    "video_mp4": "Видео (MP4)",
    "audiolivro_m4b": "Аудиокнига (M4B)",
    "audiolivro_mp3": "Аудиокнига (MP3)",
    "quadrinho_cbt": "Комикс (CBT)",
    "quadrinho_cb7": "Комикс (CB7)",
    "quadrinho_cbr": "Комикс (CBR)",
    "quadrinho_cbz": "Комикс (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "Текст (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "Сохранение отменено.",
    "o_arquivo_esta_vindo_do_armazenamento": "Файл загружается из облачного хранилища на ваше устройство.",
    "baixando_o_arquivo": "Скачиваем файл",
    "cancelando": "Отменяем...",
    "use_grifar_citacao_anotar_ou_marcador": "Во время чтения используйте «Выделить», «Цитата», «Заметка» или «Закладка».",
    "nenhuma_marcacao_ainda": "Пока нет отметок",
    "trecho_original": "Исходный фрагмент",
    "procurar_meus_livros": "Найти мои книги",
    "a_busca_fica_sempre_disponivel_no_menu": "Поиск всегда доступен в боковом меню, в разделе «Система».",
    "da_para_fazer_depois": "Вы можете сделать это позже",
    "nada_entra_na_estante_sem_a_sua_confir": "Ничего не попадёт на вашу полку без вашего согласия: вы увидите список и отметите то, что хотите импортировать.",
    "voce_revisa_antes": "Сначала вы проверяете",
    "escolha_uma_pasta_downloads_e_um_bom_c": "Выберите папку — приложение просмотрит её и все вложенные папки.",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "Ищет EPUB, MOBI, CBZ, CBR и M4B",
    "voltar_e_revisar": "Вернуться и проверить",
    "ler_os_termos": "Прочитать условия",
    "ler_a_politica": "Прочитать политику",
    "os_dois_documentos_ficam_sempre_dispon": "Оба документа всегда доступны в боковом меню, в разделе «О приложении».",
    "leia_com_calma": "Не спешите",
    "a_politica_e_os_termos_explicam_como_o": "Политика и условия объясняют, как приложение хранит ваши книги и что вы можете с ними делать. Чтобы пользоваться библиотекой, нужно согласиться с ними.",
    "nada_acontece_sem_o_aceite": "Чтобы начать, нужно принять условия",
    "aceitar_e_continuar": "Принять и продолжить",
    "nao_aceito": "Я не принимаю",
    "termos_de_uso_2": "Условия использования",
    "politica_de_privacidade_2": "Политика конфиденциальности",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "Приложение получает доступ только к выбранным вами файлам и папкам и только тогда, когда вы это разрешаете.",
    "voce_no_controle": "Вы всё контролируете",
    "depois_de_importar_um_livro_voce_le_se": "После импорта книги вы можете читать её без интернета.",
    "funciona_offline": "Работает офлайн",
    "livros_marcacoes_e_progresso_sao_guard": "Книги, отметки и прогресс хранятся на вашем устройстве. Ничего не отправляется на наши серверы.",
    "tudo_fica_no_seu_aparelho": "Всё остаётся на вашем устройстве",
    "escolha_o_que_deseja_adicionar_a_bibli": "Выберите, что хотите добавить в библиотеку. Файлы, идентичные уже находящимся на вашей полке, будут пропущены автоматически.",
    "voce_pode_tentar_outra_pasta_ou_import": "Вы можете попробовать другую папку или импортировать файлы с помощью кнопки +.",
    "a_leitura_acontece_so_no_seu_dispositi": "Чтение происходит только на вашем устройстве.",
    "voce_escolhe_a_pasta": "Вы выбираете папку",
    "tema_tipografia_margens_modo_de_virada": "Тема, шрифт, поля, стиль перелистывания и настройки аудио.",
    "restaurar_minhas_preferencias": "Восстановить мои настройки",
    "o_backup_manda_as_marcacoes_atuais_dos": "Резервная копия имеет приоритет. Текущие отметки любой книги из файла будут заменены отметками из резервной копии.",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "Ничего не удаляется. Отметки с обеих сторон объединяются, а более свежий прогресс имеет приоритет.",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "Что делать с тем, что уже есть на вашей полке",
    "grifos_citacoes_e_notas": "выделения, цитаты и заметки",
    "preparando_o_arquivo_2": "Подготавливаем файл...",
    "os_livros_em_si_nem_as_capas_por_isso": "Ни сами книги, ни обложки в него не входят — поэтому файл весит всего несколько КБ. Получателю понадобятся файлы книг, чтобы отметки вернулись на свои места, а обложки появятся автоматически при импорте книг.",
    "nao_vai_no_arquivo": "Не входит в файл",
    "o_seu_progresso_de_leitura_os_grifos_a": "Ваш прогресс чтения, выделения, цитаты, заметки, закладки и организация полки — статусы, избранное, коллекции, серии и теги.",
    "vai_no_arquivo": "В файле",
    "descartar_o_que_esta_esperando_2": "Удалить ожидающие данные",
    "esperando_o_arquivo": "Ожидаем файл",
    "avisar_quando_fizer_tempo_sem_backup": "Напоминать мне, когда резервная копия давно не создавалась",
    "livros_que_ainda_nao_estiverem_na_esta": "Книги, которых ещё нет на вашей полке, остаются в ожидании: как только вы импортируете их файлы, отметки вернутся автоматически.",
    "restaurar_backup": "Восстановить резервную копию",
    "salvar_backup": "Сохранить резервную копию",
    "ainda_nao_ha_itens": "Здесь пока ничего нет",
    "arraste_um_livro_para_outra_posicao_na": "Перетащите книгу в другое место на полке, чтобы сохранить собственный порядок. После этого ручной порядок имеет приоритет над группировкой по автору.",
    "separe_por_virgulas": "Разделяйте запятыми",
    "ex_estudos_ficcao": "например, Исследования, Художественная литература...",
    "pasta_estante": "Папка / полка",
    "ex_trilogia": "например, Трилогия...",
    "serie": "Серия",
    "aparece_em_favoritos": "Показывается в «Избранном».",
    "nome_do_livro": "Название книги",
    "nenhum_registro_ainda": "Пока ничего не записано",
    "no_leitor_toque_no_icone_de_marcador_p": "В средстве чтения нажмите значок закладки, чтобы сохранить страницу.",
    "nenhum_marcador_ainda": "Пока нет закладок",
    "a_gravacao_e_independente_da_localizac": "Сохранение не зависит от расположения PDF и не изменяет исходный файл.",
    "o_pdf_original_nao_precisa_estar_nessa": "Исходный PDF не обязательно должен находиться в этой папке",
    "excluir_da_biblioteca": "Удалить из библиотеки",
    "adicionar_livro": "Добавить книгу",
    "adicione_livros_e_acompanhe_o_que_esta": "Добавляйте книги и следите за тем, что ещё предстоит прочитать, что вы читаете сейчас и как далеко продвинулись.",
    "tudo_pronto_para_a_proxima_leitura": "Всё готово для следующего чтения.",
    "sua_biblioteca": "Ваша библиотека",
    "arraste_um_livro_para_reposiciona_lo_a": "Перетащите книгу, чтобы переместить её: полка переключится на «Мой порядок» и сохранит последовательность.",
    "importe_um_livro_ou_ajuste_seus_filtro": "Импортируйте книгу или настройте фильтры.",
    "nada_por_aqui_ainda": "Здесь пока ничего нет",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "Нажмите + и выберите файлы MP3, M4B или MP4. Несколько MP3-файлов глав можно объединить в одну аудиокнигу.",
    "nada_para_ouvir_ou_assistir_ainda": "Пока нечего слушать или смотреть",
    "o_pdf_original_permanece_intacto_na_pa": "Исходный PDF останется нетронутым в вашей собственной папке.",
    "paginas_como_imagem": "Страницы как изображения",
    "paginas_do_pdf": "Страницы PDF",
    "em_navegadores_sem_suporte_a_acesso_di": "В браузерах без прямого доступа к файловой системе EPUB вместо этого будет скачан.",
    "essa_permissao_e_dada_somente_a_esta_a": "Это разрешение предоставляется только этому приложению и не позволяет изменять исходный файл.",
    "selecione_a_pasta_que_contem_o_pdf": "Выберите папку, в которой находится PDF",
    "preparando": "Готовимся…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "Файл читается и восстанавливается. Большим книгам может понадобиться немного времени.",
    "revistas_apostilas_complexas_formulari": "Журналы, сложные рабочие тетради, формы, документы с большим количеством таблиц и отсканированные PDF-файлы могут частично потерять исходную разметку.",
    "funcionalidade_indicada_apenas_para_li": "Предназначено для книг",
    "o_epub_e_melhor_para_livros_com_texto": "EPUB лучше подходит для книг с выделяемым текстом, поскольку позволяет настраивать шрифт, размер, поля и режим чтения.",
    "trecho_selecionado": "Выбранный фрагмент",
    "trecho_comentado": "Фрагмент с комментарием",
    "aplicando_zoom": "Масштабирование...",
    "nao_foi_possivel_carregar_esta_pagina": "Не удалось загрузить эту страницу.",
    "nomear_marcador": "Назвать закладку",
    "toque_em_marcar_agora_para_guardar_est": "Нажмите «Отметить сейчас», чтобы сохранить это место и вернуться к нему в любое удобное время.",
    "timer_ativo": "Таймер включён",
    "trecho_ausente_ou_corrompido_no_arquiv": "[Фрагмент отсутствует или повреждён в исходном файле]",
    "novos_livros_vao_abrir_em_leitura_v": "Новые книги будут открываться в режиме чтения {v}.",
    "leitura_efetivo_aplicada_a_este_livro": "Для этой книги применено чтение {efetivo}.",
    "automatico_neste_livro_leitura_efetivo": "Для этой книги автоматически используется чтение {efetivo}.",
    "agora_esta_em_efetivo_no_automatico_fo": "Теперь установлено значение {efetivo}; в автоматическом режиме {format} открывается в режиме {padrao}.",
    "esta_escolha_vale_so_para_v_cada_livro": "Этот выбор относится только к «{v}». Для каждой книги направление прокрутки сохраняется отдельно.",
    "novos_ainda_nao_estao_na_sua_estante": "Ещё не на вашей полке: {novos}.",
    "escolha_uma_pasta_para_procurar_label": "Выберите папку для поиска {label}.",
    "subtitle_versao_build": "{subtitle} · версия {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "Не удалось прочитать {path}; используется встроенный текст.",
    "seu_ultimo_backup_foi_ha_dias_dias": "Последняя резервная копия была {dias} дн. назад",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "{aguardando} книга из резервной копии ещё не добавлена. Её прогресс и отметки сохранены: как только вы импортируете файл, всё автоматически вернётся на место.",
      "few": "{aguardando} книги из резервной копии ещё не добавлены. Их прогресс и отметки сохранены: как только вы импортируете каждый файл, всё автоматически вернётся на место.",
      "many": "{aguardando} книг из резервной копии ещё не добавлено. Их прогресс и отметки сохранены: как только вы импортируете каждый файл, всё автоматически вернётся на место.",
      "other": "{aguardando} книги из резервной копии ещё не добавлены. Их прогресс и отметки сохранены: как только вы импортируете каждый файл, всё автоматически вернётся на место."
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "На вашей полке обновлена {atualizados} книга.",
      "other": "На вашей полке обновлено {atualizados} книг.",
      "few": "На вашей полке обновлены {atualizados} книги.",
      "many": "На вашей полке обновлено {atualizados} книг."
    },
    "criado_em_quando": "Создано {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "Резервная копия готова. Книг: {livros}, отметок: {marcacoes}.",
    "endereco_seguro_seguro": "защищённый адрес: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "Прогресс и {marcas} отметка восстановлены для этой книги.",
      "other": "Прогресс и {marcas} отметок восстановлены для этой книги.",
      "few": "Прогресс и {marcas} отметки восстановлены для этой книги.",
      "many": "Прогресс и {marcas} отметок восстановлены для этой книги."
    },
    "restaurando_v_de_length": "Восстановление ({v} из {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "Книг: {livros} · отметок: {marcacoes}",
    "criado_em_v": "Создано {v}",
    "reunindo_a_sua_estante_v_de_length": "Собираем вашу полку ({v} из {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "«{titulo}» уже импортировалась и по-прежнему находится в вашей библиотеке. Новая копия не создана.",
    "length_arquivos_de_audio": "Аудиофайлов: {length}...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "Не удалось прочитать {falhas} файл.",
      "other": "Не удалось прочитать {falhas} файлов.",
      "few": "Не удалось прочитать {falhas} файла.",
      "many": "Не удалось прочитать {falhas} файлов."
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} уже были в библиотеке и были пропущены.",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "На вашу полку добавлена {importados} книга.",
      "other": "На вашу полку добавлено {importados} книг.",
      "few": "На вашу полку добавлены {importados} книги.",
      "many": "На вашу полку добавлено {importados} книг."
    },
    "epub_salvo_em_filename": "EPUB сохранён в {fileName}.",
    "falha_ao_converter_o_pdf_v": "Не удалось преобразовать PDF: {v}",
    "pagina_page_de_totalpages": "Страница {page} из {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} страница",
      "other": "{totalPages} страниц",
      "few": "{totalPages} страницы",
      "many": "{totalPages} страниц"
    },
    "length_resultado_s_para_search": {
      "one": "{length} результат для «{search}»",
      "other": "{length} результатов для «{search}»",
      "few": "{length} результата для «{search}»",
      "many": "{length} результатов для «{search}»"
    },
    "capitulo_v": "Глава {v}",
    "organizando_capitulo_v_de_totalchapter": "Размещаем главу {v} из {totalChapters}",
    "pagina_v": "Страница {v}",
    "paginas_v_v2": "Страницы {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} страница готова",
      "other": "{length} страниц готово",
      "few": "{length} страницы готовы",
      "many": "{length} страниц готово"
    },
    "montando_as_paginas_pagessofar_prontas": "Создаём страницы — выполнено {pagesSoFar}",
    "lendo_pagina_v_de_length": "Читаем страницу {v} из {length}",
    "marcador_salvo_em_t": "Закладка сохранена в {t}.",
    "o_audio_vai_pausar_em_minutes_minutos": "Аудио будет приостановлено через {minutes} мин.",
    "length_capitulos_toque_para_ir_direto": "{length} глав · нажмите, чтобы перейти прямо к нужной.",
    "narrado_por_narrator": "Читает: {narrator}",
    "velocidade_de_reproducao_rate": "Скорость воспроизведения: {rate}",
    "avancar_f_segundos": "Вперёд на {f} секунд",
    "nao_foi_possivel_abrir_este_v": "Не удалось открыть файл: {v}.",
    "nao_foi_possivel_ler_o_arquivo_de_v": "Не удалось прочитать файл {v}.",
    "o_v_esta_danificado_neste_ponto": "Файл ({v}) повреждён в этом месте.",
    "o_navegador_nao_consegue_reproduzir_es": "Браузер не может воспроизводить этот файл {v}.",
    "nao_foi_possivel_reproduzir_este_v": "Не удалось воспроизвести файл: {v}.",
    "os_dados_deste_noun_estao_incompletos": "Данные неполные ({noun}).",
    "importe_o_arquivo_novamente_para_conti_2": "Импортируйте файл снова, чтобы продолжить {v}.",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "Файл ({noun}) больше не сохранён на вашем устройстве.",
    "nao_foi_possivel_descobrir_a_duracao_d": "Не удалось определить продолжительность «{name}».",
    "lendo_faixa_v_de_length": "Читаем дорожку {v} из {length}...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "Не удалось определить продолжительность файла ({v}).",
    "este_format_nao_pode_ser_reproduzido_n": "Этот {format} нельзя воспроизвести в этом браузере.",
    "este_format_esta_protegido_por_drm": "Этот {format} защищён DRM.",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "Файл имеет размер {bytes}, осталось примерно {v}. Освободите место или удалите книги из библиотеки.",
    "este_arquivo_nao_e_um_format_valido": "Этот файл не является корректным {format}.",
    "preparando_as_paginas_vistas_de_total": "Подготавливаем страницы ({vistas} из {total})...",
    "preparando_total_pagina_s": {
      "one": "Подготавливаем {total} страницу...",
      "other": "Подготавливаем {total} страниц...",
      "few": "Подготавливаем {total} страницы...",
      "many": "Подготавливаем {total} страниц..."
    },
    "preparando_as_paginas_v_de_total": "Подготавливаем страницы ({v} из {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "Он занимает около {bytes}, и осталось примерно {v}. Освободите место или удалите книги из библиотеки.",
    "envio_direto_exige_endereco_seguro": "Прямая отправка в другое приложение недоступна, потому что эта страница открыта не по защищённому адресу. Сохраните файл и отправьте его через любое удобное приложение.",
    "na_estante": "на полке",
    "nao_foi_possivel_montar_o_arquivo": "Не удалось создать файл.",
    "este_navegador_nao_oferece_o_envio_dir": "Этот браузер не поддерживает прямую отправку в другое приложение. Сохраните файл и прикрепите его через любое удобное приложение.",
    "voce_ainda_nao_fez_nenhum_backup": "Вы ещё не создали резервную копию.",
    "converter_para_epub": "Преобразовать в EPUB",
    "esta_pagina_nao_pode_ser_exibida": "Не удалось показать эту страницу.",
    "na_ordem_em_que_serao_tocados": "В порядке воспроизведения",
    "este_capitulo_nao_pode_ser_exibido": "Эту главу нельзя показать.",
    "livro": "Книга",
    "restantes": " осталось",
    "como_seus_dados_sao_tratados": "Как обрабатываются ваши данные",
    "condicoes_de_uso_do_aplicativo": "Условия использования приложения",
    "audiolivro": "аудиокнига",
    "sobre_o_aplicativo": "О приложении",
    "o_que_e_o_veredas_reader": "Что такое Veredas Reader",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(это устройство не поддерживает отправку файлов этого типа)",
    "livros": "книги",
    "lendo": "чтение",
    "lidos": "завершено",
    "compartilhar_livro": "Поделиться книгой",
    "n_livros": {
      "one": "{n} книга",
      "other": "{n} книг",
      "few": "{n} книги",
      "many": "{n} книг"
    },
    "livros_unidade": {
      "one": "книга",
      "other": "книги",
      "few": "книги",
      "many": "книг"
    },
    "uma_faixa_discreta_depois_de_n_dias": "Тихая полоска на полке появляется после {n} дней без резервной копии. Она никогда не прерывает чтение.",
    "scanned_arquivos_verificados_livros_enc": "Проверено файлов: {scanned} · найдено книг: {encontrados}",
    "v_de_total": "{v} из {total}",
    "voltar_n_segundos": "Назад на {n} секунд",
    "cancelado": "Отменено",
    "arquivo": "Файл",
    "outro": "Другое",
    "outros": "Другие",
    "audiolivro_2": "Аудиокнига",
    "pausar": "Пауза",
    "marcador": "Закладка",
    "leitura": "Чтение",
    "grifo": "Выделение",
    "editar": "Изменить",
    "apagar": "Удалить",
    "concluir": "Завершить",
    "recentes": "Недавние",
    "progresso": "Прогресс",
    "entendi": "Понятно",
    "aviso": "Уведомление",
    "descartar": "Удалить",
    "copiado": "Скопировано",
    "restaurar": "Восстановить",
    "restaurando": "Восстанавливаем",
    "excluir": "Удалить",
    "grifos": "Выделения",
    "arquivo_vazio": "Пустой файл.",
    "e_mais_n_arquivos": {
      "one": "и ещё {n} файл, в порядке воспроизведения",
      "other": "и ещё {n} файлов, в порядке воспроизведения",
      "few": "и ещё {n} файла, в порядке воспроизведения",
      "many": "и ещё {n} файлов, в порядке воспроизведения"
    },
    "n_arquivos_mp3": {
      "one": "{n} файл MP3",
      "other": "{n} файлов MP3",
      "few": "{n} файла MP3",
      "many": "{n} файлов MP3"
    },
    "pct_restam": "{pct}% · осталось {tempo}",
    "n_minutos": {
      "one": "{n} минута",
      "other": "{n} минут",
      "few": "{n} минуты",
      "many": "{n} минут"
    },
    "ir_para_tempo": "Перейти к {tempo}",
    "nomear": "Переименовать",
    "parte_n": "Часть {n}",
    "carregando_pagina_n": "Загрузка страницы {n}...",
    "selecionar_pasta_e_continuar": "Выбрать папку и продолжить",
    "ler_agora": "Читать сейчас",
    "agrupamento_v": "Группировка: {v}.",
    "tempo_restante": "Осталось {tempo}",
    "abrir_titulo": "Открыть {titulo}",
    "continuar_lendo_titulo": "Продолжить чтение {titulo}",
    "continuar_ouvindo_titulo": "Продолжить слушать {titulo}",
    "continuar_assistindo_titulo": "Продолжить просмотр {titulo}",
    "lido": "Прочитано",
    "pausado": "Приостановлено",
    "status": "Статус",
    "favorito": "Избранное",
    "escolher_local": "Выбрать место",
    "epub_baixado_como": "EPUB скачан как {nome}.",
    "ouvir_a_partir_de": "слушать с {tempo}",
    "assistir_a_partir_de": "смотреть с {tempo}",
    "pagina_n_minuscula": "страница {n}",
    "selecione_trecho_para_criar": "Выберите фрагмент во время чтения, чтобы создать {oque}.",
    "excluir_oque_pergunta": "Удалить {oque}?",
    "excluir_oque": "Удалить {oque}",
    "excluir_item_pergunta": "Удалить этот элемент?",
    "use_organizar_para_criar": "Используйте «{botao}» на книге, чтобы создать {oque}.",
    "n_arquivos_processados": {
      "one": "Обработан {n} файл",
      "other": "Обработано {n} файлов",
      "few": "Обработано {n} файла",
      "many": "Обработано {n} файлов"
    },
    "voce_ja_tem_titulo_de_autor": "В вашей библиотеке уже есть «{titulo}» автора {autor}, хотя файл отличается. Всё равно импортировать?",
    "voce_ja_tem_titulo": "В вашей библиотеке уже есть «{titulo}», хотя файл отличается. Всё равно импортировать?",
    "marcadores_unidade": {
      "one": "закладка",
      "other": "закладки",
      "few": "закладки",
      "many": "закладок"
    },
    "ultimo_backup_em": "Последняя резервная копия: <strong>{data}</strong>.",
    "guardar": "Сохранить",
    "lembretes": "Напоминания",
    "juntar": "Объединить",
    "recomendado": "рекомендуется",
    "substituir": "Заменить",
    "n_capas_recuperadas": {
      "one": "Восстановлена {n} обложка.",
      "other": "Восстановлено {n} обложек.",
      "few": "Восстановлено {n} обложки.",
      "many": "Восстановлено {n} обложек."
    },
    "nao_encontramos_arquivos_tipo": "В этой папке не найдено файлов {tipo}.",
    "tentar_outra_pasta": "Попробовать другую папку",
    "n_livros_encontrados": {
      "one": "Найдена {n} книга",
      "other": "Найдено {n} книг",
      "few": "Найдено {n} книги",
      "many": "Найдено {n} книг"
    },
    "n_de_total_selecionados": {
      "one": "Выбрано {n} из {total}",
      "other": "Выбрано {n} из {total}",
      "few": "Выбрано {n} из {total}",
      "many": "Выбрано {n} из {total}"
    },
    "importar": "Импортировать",
    "importar_n": "Импортировать {n}",
    "aceite_frase": "Я прочитал(а) и принимаю {politica} и {termos} Veredas Reader.",
    "pdf_preservado": "Исходный PDF <strong>не будет удалён из вашей папки</strong>. Из библиотеки будет удалена только копия этого PDF, и только после успешного сохранения EPUB.",
    "gravar_epub_mesma_pasta": "Чтобы сохранить EPUB <strong>в той же папке, что и PDF</strong>, браузеру нужно разрешение на доступ к этой папке.",
    "epub_pronto_qualquer_pasta": "EPUB преобразован. Теперь вы можете выбрать <strong>любую папку на компьютере</strong> для сохранения файла.",
    "backup_explicacao": "Исходная резервная копия — это файл ZIP или TXT. Получив её на другом устройстве, импортируйте её через <strong>Восстановить резервную копию</strong>: Veredas распознает содержимое и восстановит его как обычно. В файле хранятся ваш прогресс, выделения, цитаты, заметки, закладки и организация полки — <strong>но не сами книги</strong> и не обложки.",
    "lembretes_desligados_frase": "Напоминания <strong>отключены</strong>. Не забывайте время от времени создавать резервную копию.",
    "backup_salvo_nos_downloads": "<strong>Файл резервной копии сохранён на этом устройстве</strong>, в папке «Загрузки». Вы можете отправить его прямо сейчас: откройте WhatsApp, почту, Drive или любое другое приложение, нажмите «Прикрепить» и выберите файл.",
    "arquivo_pronto_tamanho": "Файл готов — <strong>{tamanho}</strong>.",
    "scan_intro_frase": "Приложение может искать книги в форматах <strong>EPUB</strong> и <strong>MOBI</strong>, комиксы в <strong>CBZ</strong> и <strong>CBR</strong> и аудиокниги в <strong>M4B</strong> в папке на вашем устройстве, включая подпапки.",
    "scan_intro_auto_frase": "Чтобы быстро заполнить полку, приложение может искать книги в форматах <strong>EPUB</strong> и <strong>MOBI</strong>, комиксы в <strong>CBZ</strong> и <strong>CBR</strong> и аудиокниги в <strong>M4B</strong> в папке на вашем устройстве, включая подпапки.",
    "n_livros_aguardando": {
      "one": "<strong>{n} книга</strong> с сохранёнными прогрессом и отметками ждёт повторного импорта.",
      "few": "<strong>{n} книги</strong> с сохранёнными прогрессом и отметками ждут повторного импорта.",
      "many": "<strong>{n} книг</strong> с сохранёнными прогрессом и отметками ждут повторного импорта.",
      "other": "<strong>{n} книги</strong> с сохранёнными прогрессом и отметками ждут повторного импорта."
    },
    "fora_da_busca_titulo": "Мы не импортируем автоматически файлы PDF, TXT, DOCX (Word), MD, MP3 и MP4",
    "fora_da_busca_texto": "Эти форматы используются для самых разных документов, а не только для книг. Если их не включать, полка остаётся упорядоченной. <strong>Каждый такой файл можно импортировать вручную кнопкой +.</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "Ваша локальная библиотека",
    "biblioteca": "Библиотека",
    "organizacao": "Организация",
    "minhas_marcacoes": "Мои отметки",
    "sistema": "Система",
    "sua_biblioteca": "Ваша библиотека",
    "toque_em_um_livro_para_comecar_a_ler": "Нажмите на книгу, чтобы начать чтение.",
    "agrupar": "Группировать",
    "sua_estante_nao_tem_copia_de_seguranca": "На вашей полке нет резервной копии",
    "se_este_aparelho_se_perder_o_progresso": "Если с этим устройством что-то случится, прогресс и отметки могут быть потеряны.",
    "agora_nao": "Не сейчас",
    "nao_avisar_mais": "Больше не напоминать",
    "carregando": "Загрузка...",
    "estante": "Полка",
    "lendo": "Чтение",
    "favoritos": "Избранное",
    "marcas": "Отметки",
    "mais": "Ещё",
    "neste_capitulo": "Эта глава",
    "velocidade": "Скорость",
    "timer": "Таймер",
    "marcar": "Отметить",
    "marcadores": "Закладки",
    "personalizar_leitura": "Настройки чтения",
    "as_preferencias_ficam_salvas_para_as_p": "Ваши настройки сохраняются для будущих сеансов чтения.",
    "tema": "Тема",
    "claro": "Светлая",
    "sepia": "Сепия",
    "escuro": "Тёмная",
    "oceano": "Океан",
    "tipografia": "Шрифт",
    "texto": "Текст",
    "tamanho": "Размер",
    "espacamento": "Межстрочный интервал",
    "margens": "Поля",
    "cores_personalizadas_opcional": "Пользовательские цвета (необязательно)",
    "fundo": "Фон",
    "fonte": "Цвет текста",
    "brilho": "Яркость",
    "orientacao": "Ориентация",
    "auto": "Авто",
    "retrato": "Книжная",
    "paisagem": "Альбомная",
    "modo_de_leitura": "Режим чтения",
    "automatico": "Автоматически",
    "horizontal": "Горизонтально",
    "vertical": "Вертикально",
    "automatico_usa_rolagem_horizontal_para": "Автоматически используется горизонтальное перелистывание для EPUB, MOBI, TXT и MD и вертикальная прокрутка для PDF и DOCX. Если изменить это во время чтения, изменение сохранится только для этой книги.",
    "quadrinhos": "Комиксы",
    "como_a_pagina_aparece": "Как размещается страница",
    "pagina_inteira": "Вся страница",
    "largura_da_tela": "Ширина экрана",
    "sentido_da_leitura": "Направление чтения",
    "normal": "Обычный →",
    "manga": "← Манга",
    "revista_aberta_na_horizontal": "Разворот из двух страниц в альбомной ориентации",
    "com_o_aparelho_deitado_mostra_duas_pag": "В горизонтальном положении устройство показывает две страницы рядом — обложка остаётся отдельно, как при открытии настоящего комикса.",
    "normal_vira_da_esquerda_para_a_direita": "В обычном режиме страницы перелистываются слева направо. Манга меняет всё: жесты, нажатия у краёв и порядок двух страниц в развороте.",
    "gire_o_aparelho_para_a_horizontal_para": "Поверните устройство горизонтально, чтобы видеть две страницы одновременно.",
    "dois_toques_ampliam_no_ponto_tocado_co": "Дважды коснитесь, чтобы увеличить место касания; после увеличения перетаскивайте страницу для перемещения. Масштабирование двумя пальцами тоже работает.",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "Кнопка прокрутки вверху средства чтения переключает постраничную и непрерывную прокрутку (стиль вебтуна). При непрерывной прокрутке страницы идут одна за другой, а увеличение расширяет страницу: перемещайтесь по ней горизонтальной прокруткой.",
    "virada_de_pagina": "Перелистывание страницы",
    "folha_real": "Настоящая бумага",
    "deslizar": "Скольжение",
    "sem_animacao": "Без анимации",
    "na_leitura_horizontal_arraste_a_pagina": "При горизонтальном чтении перетаскивайте страницу за край, чтобы перелистнуть её пальцем. Отпустите на полпути, чтобы отменить перелистывание.",
    "ouvir_leitura": "Слушать",
    "continue_de_onde_parou_no_seu_ritmo": "Продолжите с места, где остановились, в удобном для вас темпе.",
    "livro": "Книга",
    "pronto_para_comecar": "Готово к началу",
    "voz": "Голос",
    "escolha_uma_voz_disponivel_no_disposit": "Выберите голос, доступный на этом устройстве",
    "voz_padrao_do_sistema": "Системный голос по умолчанию",
    "durante_a_reproducao": "Во время воспроизведения",
    "a_leitura_avanca_pagina_a_pagina_os_co": "Чтение идёт постранично. Системные элементы управления появляются, если браузер их поддерживает.",
    "organizar_livro": "Организовать книгу",
    "estantes_colecoes_tags_e_status": "Полки, коллекции, теги и статус.",
    "cancelar": "Отмена",
    "salvar": "Сохранить",
    "grifos_citacoes_notas_e_marcadores_des": "Выделения, цитаты, заметки и закладки из этой книги.",
    "sumario": "Содержание",
    "toque_em_um_capitulo_para_ir_direto_ao": "Нажмите на главу, чтобы перейти прямо к ней.",
    "sua_anotacao": "Ваша заметка",
    "edite_ou_adicione_comentarios_ao_seu_t": "Редактируйте или добавляйте комментарии к своему фрагменту.",
    "trecho": "Фрагмент",
    "sua_nota": "Ваша заметка",
    "salvar_nota": "Сохранить заметку",
    "agrupar_biblioteca": "Группировать библиотеку",
    "escolha_como_os_livros_serao_organizad": "Выберите, как книги будут расположены на полке.",
    "ao_arrastar_um_livro_para_outra_posica": "Когда вы перетаскиваете книгу в другое место, полка автоматически переключается на «Мой порядок» и сохраняет созданную вами последовательность.",
    "backup_e_restauracao": "Резервное копирование и восстановление",
    "sua_estante_seu_progresso_e_suas_marca": "Ваша полка, прогресс и отметки в одном файле.",
    "escolha_uma_dimensao_para_explorar_sua": "Выберите способ просмотра библиотеки.",
    "capitulos": "Главы",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "Голос сохраняет высоту тона. Это относится к этой книге и следующим.",
    "ajuste_fino": "Точная настройка",
    "timer_de_sono": "Таймер сна",
    "o_audio_diminui_de_volume_aos_poucos_e": "Громкость аудио постепенно снижается, после чего воспроизведение автоматически приостанавливается.",
    "pontos_que_voce_guardou_neste_audioliv": "Места, сохранённые вами в этой аудиокниге.",
    "ajustes_do_audio": "Настройки аудио",
    "as_preferencias_ficam_salvas_para_todo": "Эти настройки сохраняются для каждой аудиокниги.",
    "botao_de_voltar": "Кнопка перемотки назад",
    "botao_de_avancar": "Кнопка перемотки вперёд",
    "recuar_ao_retomar": "Перемотка при возобновлении",
    "depois_de_uma_pausa_longa_volta_alguns": "После долгой паузы воспроизведение возвращается на несколько секунд назад, чтобы было легче продолжить.",
    "tocar_ao_abrir": "Воспроизводить при открытии",
    "ao_tocar_em_um_audiolivro_na_estante_a": "Нажатие на аудиокнигу на полке сразу начинает воспроизведение.",
    "no_computador_espaco_toca_e_pausa_pula": "На компьютере: пробел — воспроизведение и пауза · ← → — перемотка · Shift + ← → — смена главы · ↑ ↓ — громкость · B — закладки · [ ] — скорость.",
    "converter_pdf_para_epub": "Преобразовать PDF в EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "Подготовьте книгу для плавного чтения с возможностью настройки.",
    "confirmacao": "Подтвердить",
    "confirmar": "Подтвердить",
    "processando": "Обработка",
    "documento": "Документ",
    "buscar_livros_no_dispositivo": "Найти книги на этом устройстве",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "Найдите уже сохранённые на устройстве файлы EPUB, MOBI, CBZ, CBR и M4B.",
    "juntar_em_um_unico_audiolivro": "Объединить в одну аудиокнигу?",
    "titulo": "Название",
    "autor": "Автор",
    "importar_separados": "Импортировать отдельно",
    "bem_vindo_ao_veredas_reader": "Добро пожаловать в Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "Ваша библиотека для чтения целиком находится на вашем устройстве.",
    "buscar": "Поиск",
    "importar_livro": "Импортировать книгу",
    "buscar_titulo_autor_tag": "Поиск по названию, автору, тегу...",
    "fechar_busca": "Закрыть поиск",
    "navegacao_da_biblioteca": "Навигация по библиотеке",
    "fechar_menu": "Закрыть меню",
    "agrupar_livros": "Группировать книги",
    "voltar": "Назад",
    "marcar_pagina": "Добавить страницу в закладки",
    "personalizar": "Настройки",
    "navegacao_principal": "Основная навигация",
    "acoes_do_trecho": "Действия с фрагментом",
    "amarelo": "Жёлтый",
    "verde": "Зелёный",
    "rosa": "Розовый",
    "azul": "Синий",
    "player_de_audiolivro": "Проигрыватель аудиокниги",
    "minimizar_player": "Свернуть проигрыватель",
    "minimizar": "Свернуть",
    "video_em_reproducao": "Видео воспроизводится",
    "abrir_a_lista_de_capitulos": "Открыть список глав",
    "posicao_no_audio": "Позиция в аудио",
    "alternar_entre_o_progresso_do_capitulo": "Переключить между прогрессом главы и прогрессом всей книги",
    "capitulo_anterior": "Предыдущая глава",
    "voltar_15_segundos": "Назад на 15 секунд",
    "reproduzir": "Воспроизвести",
    "avancar_30_segundos": "Вперёд на 30 секунд",
    "proximo_capitulo": "Следующая глава",
    "velocidade_de_reproducao": "Скорость воспроизведения",
    "marcar_este_ponto": "Добавить закладку в это место",
    "ver_marcadores": "Посмотреть закладки",
    "silenciar": "Без звука",
    "volume": "Громкость",
    "audiolivro_em_reproducao": "Аудиокнига воспроизводится",
    "abrir_o_player": "Открыть проигрыватель",
    "fechar_o_player": "Закрыть проигрыватель",
    "fechar": "Закрыть",
    "trecho_anterior": "Предыдущий фрагмент",
    "iniciar_leitura": "Начать чтение вслух",
    "proximo_trecho": "Следующий фрагмент",
    "escreva_seu_comentario_interpretacao_o": "Напишите комментарий, размышление или напоминание...",
    "cancelar_importacao": "Отменить импорт",
    "nome_do_audiolivro": "Название аудиокниги",
    "nome_do_autor": "Имя автора",
    "idioma": "Язык",
    "idioma_do_aplicativo": "Язык приложения",
    "o_aplicativo_segue_o_idioma_do_apare": "Приложение использует язык вашего устройства. Если вашего языка здесь ещё нет, оно откроется на английском.",
    "seguir_o_aparelho": "Следовать языку устройства",
    "fazer_backup": "Создать резервную копию сейчас",
    "todos": "Все",
    "lidos": "Завершённые",
    "pausados": "Приостановленные",
    "autores": "Авторы",
    "tags": "Теги",
    "grifar": "Выделить",
    "anotar": "Заметка",
    "enviar": "Отправить",
    "restaurar_padroes": "Восстановить настройки по умолчанию",
    "voltar_para_1": "Вернуться к 1×",
    "marcar_agora": "Отметить сейчас",
    "escolher_pasta": "Выбрать папку",
    "juntar_em_um_audiolivro": "Объединить в одну аудиокнигу",
    "sobre": "О приложении",
    "licencas_de_codigo_aberto": "Лицензии открытого исходного кода",
    "configuracoes": "Настройки",
    "temas_e_idioma": "Темы и язык"
  },
  "aviso": {
    "idioma_trocado": "Язык изменён."
  },
  "guia": {
      "pular": "Пропустить",
      "voltar": "Назад",
      "proximo": "Далее",
      "concluir": "Понятно",
      "secao": "Подсказки",
      "rever_titulo": "Показать подсказки снова",
      "rever_dica": "Подсказки появляются один раз, там, где происходит само действие. Это вернёт их все с начала.",
      "rever_botao": "Повторить",
      "voltaram": "Подсказки вернулись.",
      "primeiro_t": "Начните отсюда",
      "primeiro_p": "Нажмите +, чтобы добавить книгу с устройства. Подходят EPUB, PDF, MOBI, DOCX, TXT, комиксы и аудиокниги.",
      "card_t": "Нажмите, чтобы читать; удерживайте, чтобы переставить",
      "card_p": "Одно нажатие открывает книгу. Удерживайте и перетащите, чтобы поставить её на полке куда захотите.",
      "agrupar_t": "Наведите свой порядок",
      "agrupar_p": "Сгруппируйте полку по автору, серии, подборке или метке — и вернитесь к простому списку, когда захотите.",
      "mais_t": "Всё остальное здесь",
      "mais_p": "Поиск на устройстве, резервная копия, настройки и документы — в этом меню.",
      "pdf_epub_t": "Этот PDF стоит преобразовать",
      "pdf_epub_p": "В EPUB текст подстраивается под экран, можно менять размер шрифта, а чтение вслух работает намного лучше. Нажмите здесь — исходный PDF останется на полке.",
      "virar_t": "Проведите пальцем, чтобы перевернуть",
      "virar_p": "Проведите в сторону или коснитесь у правого и левого края. Касание по центру показывает и скрывает кнопки.",
      "rolar_t": "Прокручивайте, чтобы читать",
      "rolar_p": "Эта книга открывается со сплошной прокруткой: ведите вверх, чтобы продолжить. Касание по центру показывает и скрывает кнопки.",
      "voltar_t": "Назад на полку",
      "voltar_p": "Эта кнопка закрывает книгу и возвращает вас назад. Место, где вы остановились, сохраняется само.",
      "ouvir_t": "Слушать вместо чтения",
      "ouvir_p": "Приложение читает книгу вслух. Можно использовать голос устройства или загрузить естественный голос — он звучит гораздо живее и работает без интернета.",
      "sentido_t": "По страницам или прокруткой",
      "sentido_p": "Меняйте направление чтения когда угодно. Выбор действует только для этой книги.",
      "personalizar_t": "Настройте под себя",
      "personalizar_p": "Здесь тема, шрифт, размер текста, поля и яркость.",
      "pdf_sentido_t": "PDF открывается прокруткой",
      "pdf_sentido_p": "У страниц PDF фиксированный размер, поэтому он начинается со сплошной прокрутки. Отсюда переключается на постраничный режим.",
      "pdf_volte_t": "Если текст кажется мелким",
      "pdf_volte_p": "Разведите пальцы, чтобы приблизить. И помните: после преобразования в EPUB текст сам подстроится под экран.",
      "hq_zoom_t": "Приближайте двумя пальцами",
      "hq_zoom_p": "Разведите пальцы, чтобы увеличить кадр, и тяните, чтобы двигаться по странице. Двойное касание вернёт обычный размер.",
      "hq_ajustes_t": "Настройки комикса",
      "hq_ajustes_p": "Выберите, как страница вписывается в экран, направление чтения и нужны ли две страницы рядом при повороте устройства.",
      "tema_t": "Выберите тему",
      "tema_p": "Светлая, сепия или тёмная. Сепия меньше утомляет глаза при долгом чтении, а тёмная спокойнее ночью.",
      "fonte_t": "Размер текста",
      "fonte_p": "Тяните, чтобы увеличить или уменьшить. Чуть ниже — межстрочный интервал и поля.",
      "modo_t": "Направление чтения",
      "modo_p": "Автоматически — горизонтальная прокрутка для EPUB и вертикальная для PDF. Если менять при открытой книге, настройка действует только для неё.",
      "audio_cap_t": "Переходите между главами",
      "audio_cap_p": "Нажмите, чтобы увидеть список глав и сразу перейти к нужной.",
      "audio_ajustes_t": "Скорость и таймер сна",
      "audio_ajustes_p": "Здесь можно ускорить или замедлить чтение и задать, чтобы звук сам остановился через время.",
      "audio_min_t": "Продолжайте листать",
      "audio_min_p": "Сверните плеер и слушайте дальше, пока пользуетесь полкой. Нажмите полосу внизу, чтобы вернуться."
  },
  "vn": {
    "quem_le": "Кто читает",
    "natural": "Естественный",
    "do_sistema": "Системный",
    "nota_sistema": "Используются голоса, установленные на устройстве. Для более живого чтения выберите «Естественный».",
    "nota_sistema_com_natural": "Естественный голос по-прежнему загружен. Вернуться к нему можно в любой момент.",
    "voz_do_sistema": "Системный голос",
    "lendo_com_a_voz_do_sistema": "Читает системный голос.",
    "voz_natural": "Естественный голос",
    "gerada_no_aparelho": "Гораздо более живой голос, который создаётся прямо на вашем устройстве.",
    "progresso_download": "Ход загрузки",
    "x_de_y": "{x} из {y}",
    "aviso_arquivo": "Для естественного голоса Veredas нужно открыть по адресу приложения, а не как файл на компьютере. А пока для чтения используется системный голос.",
    "aviso_navegador": "В этом браузере нет возможностей, нужных естественному голосу. Чтение продолжится системным голосом.",
    "verificando": "Проверяем естественный голос…",
    "fato_download": "Однократная загрузка: {tamanho}. После этого всё работает без интернета.",
    "fato_wifi": "Лучше через Wi-Fi. Загрузку можно приостановить и продолжить позже.",
    "fato_privacidade": "Текст книги никогда не покидает ваше устройство.",
    "fato_idiomas": "Говорит на 31 языке, в том числе на русском, английском и португальском. Для остальных языков по-прежнему используется системный голос.",
    "baixar_voz_natural": "Скачать естественный голос ({tamanho})",
    "licenca_curta": "Модель Supertonic 3 от Supertone, лицензия OpenRAIL-M. Подробнее: О приложении > Лицензии открытого исходного кода.",
    "pode_continuar_usando": "Можно продолжать читать, пока идёт загрузка. Если связь прервётся, загрузка продолжится с того же места.",
    "pausar_download": "Приостановить загрузку",
    "erro_espaco": "На устройстве недостаточно места, чтобы завершить загрузку. Освободите место и попробуйте снова.",
    "erro_offline": "Сейчас нет подключения к интернету. Уже загруженное сохранено.",
    "erro_rede": "Связь прервалась во время загрузки. Уже загруженное сохранено.",
    "download_pausado": "Загрузка приостановлена. Уже загруженное сохранено.",
    "continuar_download": "Продолжить",
    "descartar": "Удалить",
    "voz_feminina": "Женский",
    "voz_feminina_desc": "Мягкий и спокойный",
    "voz_masculina": "Мужской",
    "voz_masculina_desc": "Тёплый и уравновешенный",
    "parar_amostra": "Остановить образец",
    "ouvir_amostra_de": "Прослушать образец: {voz}",
    "escolha_a_voz": "Выберите голос",
    "qualidade": "Качество",
    "q_auto": "Автоматическое",
    "q_rapida": "Быстрое",
    "q_maxima": "Наилучшее",
    "q_auto_desc": "Подстраивается под производительность устройства, чтобы чтение шло без пауз.",
    "q_rapida_desc": "Создаёт голос быстрее. Подходит для простых устройств.",
    "q_maxima_desc": "Самое качественное звучание. На простых устройствах возможны паузы между предложениями.",
    "ocupa": "Занимает {tamanho} на этом устройстве",
    "remover": "Удалить",
    "baixar_pelos_dados": "Скачать через мобильный интернет?",
    "baixar_pelos_dados_msg": "Похоже, устройство не подключено к Wi-Fi. Размер загрузки — {tamanho}, это может расходовать трафик вашего тарифа.",
    "baixar_agora": "Всё равно скачать",
    "pronta": "Естественный голос готов.",
    "download_interrompido": "Загрузка остановилась. Нажмите «Продолжить», когда будет удобно.",
    "remover_titulo": "Удалить естественный голос?",
    "descartar_titulo": "Удалить загрузку?",
    "remover_msg": "Освободится {tamanho}. Чтение вернётся к системному голосу, а скачать естественный голос снова можно в любой момент.",
    "descartar_msg": "Уже загруженное будет удалено.",
    "removida": "Естественный голос удалён с этого устройства.",
    "amostra_falhou": "Не удалось воспроизвести образец на этом устройстве.",
    "amostra": "Здравствуйте! Вот так ваши книги будут звучать естественным голосом.",
    "pode_demorar_um_minuto": "Это может занять минуту.",
    "gerando_voz": "Готовим голос…",
    "automatico_idioma": "Автоматически ({idioma})",
    "automatico": "Автоматически",
    "so_voz_do_sistema": "системный голос",
    "aviso_idioma": "Язык текста: {idioma}. Естественный голос пока не говорит на этом языке, поэтому книгу прочитает системный голос.",
    "aviso_idioma_desconhecido": "Не удалось определить язык этого текста. Выберите язык ниже, чтобы использовать естественный голос.",
    "aviso_falha": "Естественный голос сейчас не удалось запустить на этом устройстве. Чтение продолжится системным голосом.",
    "nao_carregou_usando_sistema": "Естественный голос не загрузился на этом устройстве. Читаем системным голосом.",
    "parou_usando_sistema": "Естественный голос остановился. Продолжаем системным голосом.",
    "aparelho_lento": "Устройство создаёт голос медленно. Выберите качество «Быстрое», чтобы избежать пауз.",
    "idioma_do_texto": "Язык текста",
    "idioma_do_texto_dica": "Определён по самому тексту. Измените его, если произношение звучит неправильно.",
    "leitura_em_voz_alta": "Чтение вслух",
    "lento_usando_sistema": "Естественный голос работает на этом устройстве слишком медленно. Чтение продолжится системным голосом.",
    "aviso_lento": "Это устройство не успевает создавать естественный голос в темпе чтения, поэтому пока читает системный голос.",
    "sem_memoria_usando_sistema": "Естественному голосу не хватило памяти на этом устройстве. Читает системный голос.",
    "aviso_falha_memoria": "На этом устройстве не хватило памяти для естественного голоса. Обычно помогает закрыть другие приложения и попробовать снова; пока читает системный голос.",
    "copiar_detalhe": "Скопировать подробности",
    "copiado": "Подробности скопированы.",
    "falhou_titulo": "Естественный голос не загрузился на этом устройстве.",
    "falhou_texto": "Устройству не удалось подготовить естественный голос. Чтение продолжается системным голосом. Чтобы помочь разобраться, скопируйте подробности ниже и отправьте в поддержку.",
    "falhou_memoria_texto": "На этом устройстве не хватило памяти для естественного голоса. Обычно помогает закрыть другие приложения и попробовать снова.",
    "tentar_de_novo": "Повторить",
    "tentando": "Загрузка…",
    "sondando": "Проверка памяти этого устройства…",
    "sonda_explica": "Проверка на несколько секунд занимает память, которая понадобится естественному голосу, и сразу её освобождает. Так вы узнаете результат сейчас, а не после загрузки.",
    "so_aparelhos_compativeis": "Работает только на совместимых устройствах. Работа на всех моделях телефонов и планшетов не гарантируется.",
    "aviso_aparelho_justo": "У этого устройства мало памяти для естественного голоса. Он может не загрузиться; тогда достаточно удалить его и вернуть место.",
    "preparando_demora": "Голос готовится. Это может занять несколько минут.",
    "incompativel_titulo": "Естественный голос не работает на этом устройстве.",
    "incompativel_memoria": "Для его подготовки не хватило памяти. Чтение остаётся с системным голосом, его настройки — ниже. Если хотите, закройте другие приложения и нажмите «Проверить снова».",
    "incompativel_lento": "Он оказался слишком медленным для чтения. Чтение остаётся с системным голосом, его настройки — ниже.",
    "incompativel_queda": "Приложение закрылось во время загрузки. Чтение остаётся с системным голосом, его настройки — ниже.",
    "incompativel_falha": "Здесь он не смог загрузиться. Чтение остаётся с системным голосом, его настройки — ниже.",
    "testar_de_novo": "Проверить снова",
    "remover_e_liberar": "Удалить и освободить {tamanho}",
    "tela_durante_a_leitura": "Экран во время чтения",
    "manter_tela_ligada": "Не гасить экран",
    "manter_tela_ligada_dica": "Пока книга открыта, экран не гаснет сам. После закрытия книги всё возвращается как было."
  }
});
