/* ============================================================
   THAI — th.js
   ============================================================ */
Idiomas.registrar('th', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "ลบที่คั่นหนังสือแล้ว",
    "excluir_marcador": "ลบที่คั่นหนังสือ",
    "o_marcador_sera_removido_permanentemen": "ที่คั่นหนังสือจะถูกลบอย่างถาวร",
    "excluir_marcador_2": "ลบที่คั่นหนังสือ?",
    "pagina_salva": "บันทึกหน้าแล้ว",
    "anotacoes": "บันทึก",
    "citacoes": "ข้อความอ้างอิง",
    "item_excluido": "ลบรายการแล้ว",
    "este_registro_sera_removido_permanente": "รายการนี้จะถูกลบออกจากคลังอย่างถาวร",
    "configuracoes_padrao_restauradas": "คืนค่าการตั้งค่าเริ่มต้นแล้ว",
    "leitura_da_esquerda_para_a_direita": "อ่านจากซ้ายไปขวา",
    "leitura_da_direita_para_a_esquerda_man": "อ่านจากขวาไปซ้าย (มังงะ)",
    "a_pagina_inteira_passa_a_caber_na_tela": "ทั้งหน้าจะพอดีกับหน้าจอแล้ว",
    "a_pagina_passa_a_ocupar_toda_a_largura": "หน้าจะเต็มความกว้างของหน้าจอแล้ว",
    "virada_sem_animacao_ativada": "เปลี่ยนหน้าโดยไม่มีการเคลื่อนไหว",
    "virada_deslizante_ativada": "เปิดการเลื่อนเปลี่ยนหน้า",
    "virada_em_folha_real_ativada": "เปิดการเปลี่ยนหน้าแบบกระดาษจริง",
    "padrao_automatico_cada_formato_abre_no": "อัตโนมัติ: แต่ละรูปแบบเปิดในแบบที่เหมาะกับมัน",
    "mudando_durante_a_leitura_o_ajuste_fic": "หากเปลี่ยนขณะอ่าน การเปลี่ยนแปลงจะถูกบันทึกไว้สำหรับหนังสือเล่มนั้นเท่านั้น",
    "automatico_usa_rolagem_horizontal_para": "อัตโนมัติใช้การเปลี่ยนหน้าแนวนอนสำหรับ EPUB, MOBI, TXT, MD และการ์ตูน และเลื่อนแนวตั้งสำหรับ PDF และ DOCX",
    "este_livro": "หนังสือเล่มนี้",
    "armazenamento_local_indisponivel_neste": "ที่จัดเก็บในเครื่องไม่พร้อมใช้งานในเบราว์เซอร์นี้",
    "o_aplicativo_pode_procurar_os_livros_q": "แอปสามารถค้นหาหนังสือที่มีอยู่แล้วในอุปกรณ์ของคุณ",
    "vamos_montar_sua_estante": "มาเติมชั้นหนังสือของคุณกันไหม?",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "หากไม่ยอมรับ แอปจะใช้งานไม่ได้",
    "precisamos_do_seu_aceite": "เราต้องการความยินยอมของคุณ",
    "antes_de_comecar_leia_e_aceite_os_docu": "ก่อนเริ่ม โปรดอ่านและยอมรับเอกสารด้านล่าง",
    "selecionar_todos": "เลือกทั้งหมด",
    "limpar_selecao": "ล้างการเลือก",
    "todos_parecem_ja_estar_na_sua_estante": "ดูเหมือนทั้งหมดอยู่ในชั้นของคุณแล้ว",
    "lendo_a_pasta_escolhida": "กำลังอ่านโฟลเดอร์ที่คุณเลือก…",
    "procurando_livros": "กำลังค้นหาหนังสือ",
    "nao_foi_possivel_concluir_a_busca_no_d": "ไม่สามารถค้นหาในอุปกรณ์นี้ได้เสร็จ",
    "tente_outra_pasta_do_aparelho": "ลองโฟลเดอร์อื่นในอุปกรณ์ของคุณ",
    "nenhum_livro_encontrado": "ไม่พบหนังสือ",
    "use_o_botao_para_escolher_os_arquivos": "ใช้ปุ่ม + เพื่อเลือกไฟล์ด้วยตนเอง บน Android Chrome มักให้เลือกทั้งโฟลเดอร์",
    "seu_navegador_nao_permite_ler_pastas": "เบราว์เซอร์ของคุณอ่านโฟลเดอร์ไม่ได้",
    "busca_automatica_indisponivel": "การค้นหาอัตโนมัติไม่พร้อมใช้งาน",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB, MOBI, CBZ, CBR และ M4B",
    "termos_de_uso": "ข้อกำหนดการใช้งาน",
    "politica_de_privacidade": "นโยบายความเป็นส่วนตัว",
    "um_minuto_agora_evita_perder_o_progres": "ใช้เวลาเพียงหนึ่งนาทีตอนนี้ ช่วยไม่ให้ความคืบหน้าและเครื่องหมายหายไปในภายหลัง",
    "ver_estante": "ดูชั้นหนังสือ",
    "modo_juntar": "โหมดรวม",
    "modo_substituir": "โหมดแทนที่",
    "restauracao_concluida": "กู้คืนเสร็จสิ้น",
    "tente_de_novo_com_o_arquivo_original": "ลองอีกครั้งกับไฟล์ต้นฉบับ",
    "a_restauracao_nao_pode_ser_concluida": "ไม่สามารถกู้คืนได้",
    "devolvendo_o_seu_progresso_e_as_suas_m": "กำลังนำความคืบหน้าและเครื่องหมายของคุณกลับมา...",
    "restaurar_este_backup": "กู้คืนสำรองนี้?",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "เลือก .zip ที่ Veredas บันทึกไว้ หรือ .txt ที่ได้รับผ่านการแชร์",
    "nao_foi_possivel_ler_este_arquivo": "ไม่สามารถอ่านไฟล์นี้ได้",
    "lendo_o_backup": "กำลังอ่านข้อมูลสำรอง",
    "backup_do_veredas_reader": "สำรอง Veredas Reader",
    "arquivo_de_transporte_txt_contendo_os": "สำเนาข้อมูลสำรองในรูปแบบ .txt ซึ่งมีเนื้อหาเดียวกับไฟล์ ZIP",
    "nao_foi_possivel_montar_o_arquivo_de_b": "ไม่สามารถสร้างไฟล์สำรองได้",
    "escolher_o_app": "เลือกแอป",
    "vale_conferir_o_que_vai_no_arquivo": "ควรตรวจสอบว่าไฟล์มีอะไร",
    "enviar_para_outro_app": "ส่งไปยังแอปอื่น",
    "salvar_o_arquivo": "บันทึกไฟล์",
    "o_navegador_aqui_nao_oferece_o_compart": "เบราว์เซอร์ที่นี่ไม่ให้การแชร์โดยตรง คุณสามารถบันทึกไฟล์และส่งภายหลังผ่านแอปที่ต้องการ",
    "este_aparelho_nao_abre_a_lista_de_apli": "อุปกรณ์นี้ไม่เปิดรายการแอป",
    "importe_pelo_menos_um_livro_antes_de_f": "นำเข้าอย่างน้อยหนึ่งเล่มก่อนสร้างสำรอง",
    "estante_vazia": "ชั้นว่างเปล่า",
    "nao_deu_para_copiar": "คัดลอกไม่ได้",
    "copiar_detalhes": "คัดลอกรายละเอียด",
    "o_backup_foi_salvo_assim_mesmo": "บันทึกสำรองไว้แล้ว",
    "o_aparelho_recusou_abrir_a_lista": "ไม่สามารถเปิดรายการแชร์ได้",
    "sem_detalhes_do_navegador": "ไม่มีรายละเอียดจากเบราว์เซอร์",
    "o_sistema_nao_aceitou_receber_o_arquiv": "ระบบของอุปกรณ์ไม่สามารถรับไฟล์ได้",
    "o_navegador_considerou_a_situacao_inse": "เบราว์เซอร์บล็อกการแชร์ตามกฎความปลอดภัยของตัวเอง บันทึกไฟล์แล้วส่งผ่านแอปที่คุณต้องการ",
    "o_compartilhamento_so_funciona_em_ende": "การแชร์ทำงานเฉพาะบนที่อยู่ที่ปลอดภัย แอปนี้เปิดจาก http:// ธรรมดา ซึ่งเบราว์เซอร์จะบล็อกการส่งไปแอปอื่น",
    "este_navegador_nao_conseguiu_iniciar_o": "เบราว์เซอร์นี้ไม่สามารถเปิดการแชร์ได้ บันทึกไฟล์แล้วส่งผ่านแอปที่คุณต้องการ",
    "o_navegador_recebeu_um_arquivo_em_form": "เบราว์เซอร์ไม่ได้เปิดรายการแอปสำหรับแชร์ แตะปุ่มอีกครั้ง หรือบันทึกไฟล์แล้วส่งผ่านแอปที่คุณต้องการ",
    "nao_foi_possivel_gerar_o_backup": "ไม่สามารถสร้างสำรองได้",
    "reunindo_a_sua_estante": "กำลังรวบรวมชั้นหนังสือของคุณ...",
    "preparando_o_backup": "กำลังเตรียมสำรอง",
    "pronto_nada_mais_esta_esperando": "เสร็จแล้ว — ไม่มีอะไรค้างอยู่อีก",
    "o_progresso_e_as_marcacoes_desses_livr": "ความคืบหน้าและเครื่องหมายของหนังสือเหล่านี้จะถูกลบ หากนำเข้าไฟล์ภายหลังจะกลับมาเปล่า",
    "descartar_o_que_esta_esperando": "ลบข้อมูลที่รออยู่หรือไม่?",
    "lembretes_de_backup_religados": "เปิดการเตือนสำรองอีกครั้ง",
    "sem_titulo": "ไม่มีชื่อ",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "ปิดการเตือนแล้ว",
    "manter_ligado": "เปิดไว้",
    "desligar_assim_mesmo": "ปิดเลย",
    "o_botao_de_salvar_continua_onde_sempre": "ปุ่มบันทึกยังอยู่ที่เดิม ในสำรองและกู้คืน",
    "o_lembrete_e_o_unico_aviso_que_existe": "การเตือนคือคำเตือนเดียวที่มี หากไม่มีการเตือน คุณจะต้องจำเองว่าต้องสำรอง\n\n",
    "limpar_os_dados_do_navegador_desinstal": "หากล้างข้อมูลเบราว์เซอร์ ถอนการติดตั้งแอป เปลี่ยนโทรศัพท์ หรืออุปกรณ์เสีย จะไม่สามารถกู้คืนความคืบหน้า ไฮไลต์ ข้อความอ้างอิง บันทึก และที่คั่นได้\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "ชั้นหนังสือของคุณอยู่เฉพาะในอุปกรณ์นี้ ไม่มีสำเนาบนเซิร์ฟเวอร์ใด ๆ จึงไม่มีทางกู้คืนให้คุณได้\n\n",
    "leia_antes_de_confirmar": "อ่านก่อนยืนยัน",
    "desligar_os_lembretes_de_backup": "ปิดการเตือนสำรอง?",
    "progresso_de_leitura_restaurado_neste": "กู้คืนความคืบหน้าการอ่านสำหรับหนังสือเล่มนี้แล้ว",
    "pronto": "เสร็จ",
    "aplicando_as_suas_preferencias": "กำลังใช้การตั้งค่าของคุณ...",
    "atualize_o_veredas_reader_e_tente_de_n": "อัปเดต Veredas Reader แล้วลองอีกครั้ง",
    "este_backup_foi_feito_numa_versao_mais": "สำรองนี้สร้างด้วยแอปเวอร์ชันใหม่กว่า",
    "este_arquivo_nao_e_um_backup_de_biblio": "ไฟล์นี้ไม่ใช่สำรองคลังของ Veredas",
    "o_conteudo_interno_nao_pode_ser_lido": "ไม่สามารถอ่านเนื้อหาภายในได้",
    "o_backup_esta_corrompido": "สำรองเสียหาย",
    "falta_o_arquivo_biblioteca_json_la_den": "ไม่มีไฟล์ biblioteca.json อยู่ข้างใน",
    "este_arquivo_nao_parece_ser_um_backup": "ไฟล์นี้ดูไม่เหมือนสำรองของ Veredas",
    "compactando": "กำลังบีบอัด...",
    "para_restaurar_menu_lateral_backup_e_r": "กู้คืน: เมนูด้านข้าง > สำรองและกู้คืน > กู้คืนสำรอง",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas จะกู้คืนเครื่องหมายและจุดที่คุณหยุดอ่านไว้โดยอัตโนมัติ",
    "importe_os_livros_normalmente_no_aplic": "นำเข้าหนังสือตามปกติในแอป: เมื่อรับรู้ไฟล์",
    "ele_nao_contem_os_arquivos_dos_livros": "ไม่มีไฟล์หนังสืออยู่ข้างใน สำหรับการกู้คืนแบบเต็ม",
    "as_notas_os_marcadores_e_a_organizacao": "บันทึก ที่คั่น และการจัดชั้นของคุณ",
    "este_arquivo_guarda_o_seu_progresso_de": "ไฟล์นี้เก็บความคืบหน้าการอ่าน ไฮไลต์ ข้อความอ้างอิง",
    "verificando_se_sao_partes_do_mesmo_aud": "กำลังตรวจว่าส่วนเหล่านี้เป็นของหนังสือเสียงเดียวกัน...",
    "analisando_os_arquivos": "กำลังอ่านไฟล์",
    "nao_foi_possivel_salvar_o_audiolivro": "ไม่สามารถบันทึกหนังสือเสียงได้",
    "audiolivros_grandes_podem_levar_alguns": "หนังสือเสียงขนาดใหญ่อาจใช้เวลาสักครู่...",
    "salvando_na_sua_estante": "กำลังบันทึกในชั้นของคุณ",
    "falha_ao_processar_os_arquivos": "ไม่สามารถประมวลผลไฟล์ได้",
    "falha_ao_processar_o_arquivo": "ไม่สามารถประมวลผลไฟล์ได้",
    "nao_foi_possivel_salvar_o_quadrinho": "ไม่สามารถบันทึกการ์ตูนได้",
    "quase_la": "เกือบเสร็จ...",
    "falha_ao_processar_o_quadrinho": "ไม่สามารถประมวลผลการ์ตูนได้",
    "autor_desconhecido": "ไม่ทราบผู้เขียน",
    "lendo_o_quadrinho": "กำลังอ่านการ์ตูน...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "ไม่สามารถบันทึกหนังสือในคลังได้",
    "nao_foi_possivel_ler_o_pdf": "ไม่สามารถอ่าน PDF ได้",
    "lendo_o_pdf": "กำลังอ่าน PDF...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "ถ้าเป็น .doc เก่า เปิดใน Word และบันทึกเป็น .docx ก่อนนำเข้า",
    "este_arquivo_nao_e_um_docx_valido": "ไฟล์นี้ไม่ใช่ .docx ที่ถูกต้อง",
    "livros_com_protecao_da_amazon_nao_pode": "หนังสือที่มีการป้องกันของ Amazon ไม่สามารถเปิดที่นี่ได้ ใช้สำเนาที่ไม่มี DRM หรือแปลงเป็น EPUB",
    "este_arquivo_esta_protegido_por_drm": "ไฟล์นี้ได้รับการป้องกันด้วย DRM",
    "confira_se_a_extensao_corresponde_ao_c": "ตรวจสอบว่านามสกุลตรงกับเนื้อหา หรือแปลงเป็น EPUB",
    "este_arquivo_nao_e_um_mobi_valido": "ไฟล์นี้ไม่ใช่ MOBI ที่ถูกต้อง",
    "nao_foi_possivel_ler_o_arquivo": "ไม่สามารถอ่านไฟล์ได้",
    "formato_nao_suportado": "ไม่รองรับรูปแบบ",
    "falha_ao_salvar_o_livro_na_biblioteca": "ไม่สามารถบันทึกหนังสือในคลังได้",
    "livro_importado_e_salvo_no_dispositivo": "นำเข้าและบันทึกหนังสือในอุปกรณ์แล้ว",
    "audiolivro_importado_e_salvo_no_dispos": "นำเข้าและบันทึกหนังสือเสียงในอุปกรณ์แล้ว",
    "quadrinho_importado_e_salvo_no_disposi": "นำเข้าและบันทึกการ์ตูนในอุปกรณ์แล้ว",
    "salvando_na_sua_estante_2": "กำลังบันทึกในชั้นของคุณ...",
    "importando_livro": "กำลังนำเข้าหนังสือ",
    "importar_mesmo_assim": "นำเข้าอยู่ดี",
    "parece_que_este_livro_ja_esta_na_estan": "ดูเหมือนหนังสือเล่มนี้อยู่ในชั้นของคุณแล้ว",
    "este_livro_ja_esta_na_estante": "หนังสือเล่มนี้อยู่ในชั้นแล้ว",
    "video_importado_e_salvo_no_dispositivo": "นำเข้าและบันทึกวิดีโอในอุปกรณ์แล้ว",
    "importacao_cancelada": "ยกเลิกการนำเข้าแล้ว",
    "preparando_o_arquivo": "กำลังเตรียมไฟล์",
    "importando_audiolivro": "กำลังนำเข้าหนังสือเสียง",
    "importacao_concluida": "นำเข้าเสร็จ",
    "importacao_interrompida": "การนำเข้าถูกหยุด",
    "a_importacao_foi_interrompida_o_que_ja": "การนำเข้าถูกหยุด สิ่งที่เข้ามาแล้วจะอยู่ในชั้นของคุณ",
    "finalizando": "กำลังทำให้เสร็จ…",
    "nao_foi_possivel_ler_o_arquivo_2": "ไม่สามารถอ่านไฟล์ได้",
    "importando_livros": "กำลังนำเข้าหนังสือ",
    "livros_quadrinhos_documentos_audiolivr": "หนังสือ การ์ตูน เอกสาร หนังสือเสียง และวิดีโอ",
    "series": "ชุด",
    "colecoes": "คอลเลกชัน",
    "organizacao_salva": "บันทึกการจัดเรียงแล้ว",
    "informe_um_nome_para_o_livro_antes_de": "ตั้งชื่อหนังสือก่อนบันทึก",
    "nome_do_livro_obrigatorio": "ต้องมีชื่อหนังสือ",
    "importe_um_livro_primeiro": "นำเข้าหนังสือก่อน",
    "citacao": "ข้อความอ้างอิง",
    "anotacao": "บันทึก",
    "citacao_2": "ข้อความอ้างอิง",
    "anotacao_2": "บันทึก",
    "uma_citacao": "ข้อความอ้างอิง",
    "uma_anotacao": "บันทึก",
    "o_marcador_sera_removido_da_biblioteca": "ที่คั่นจะถูกลบออกจากคลัง แต่ไฟล์หนังสือจะไม่ถูกแตะต้อง",
    "marcador_de_audio": "ที่คั่นเสียง",
    "marcador_de_video": "ที่คั่นวิดีโอ",
    "nao_foi_possivel_excluir_o_livro": "ไม่สามารถลบหนังสือได้",
    "livro_excluido_da_biblioteca": "ลบหนังสือออกจากคลังแล้ว",
    "excluir_livro": "ลบหนังสือ",
    "isso_remove_apenas_a_copia_armazenada": "การลบนี้จะลบเฉพาะสำเนาที่คลังเก็บไว้ ความคืบหน้า ที่คั่น และบันทึกเท่านั้น ไฟล์ต้นฉบับในโฟลเดอร์ของคุณจะไม่ถูกลบ",
    "excluir_livro_2": "ลบหนังสือ?",
    "ordem_personalizada_salva": "บันทึกลำดับที่กำหนดเองแล้ว",
    "ordem_manual_da_sua_estante": "ชั้นของคุณ ตามลำดับที่คุณตั้ง",
    "agrupamento_alterado_para_minha_ordem": "เปลี่ยนการจัดกลุ่มเป็นลำดับของฉัน",
    "nova_ordem_salva": "บันทึกลำดับใหม่แล้ว",
    "nao_foi_possivel_salvar_a_nova_ordem": "ไม่สามารถบันทึกลำดับใหม่ได้",
    "baixar_automaticamente": "ดาวน์โหลดอัตโนมัติ",
    "escolha_livremente_onde_o_arquivo_sera": "เลือกได้อย่างอิสระว่าไฟล์จะถูกเขียนที่ไหน",
    "salvar_epub": "บันทึก EPUB",
    "livro_epub": "หนังสือ EPUB",
    "erro_desconhecido": "ข้อผิดพลาดที่ไม่รู้จัก",
    "a_permissao_para_salvar_o_arquivo_foi": "ยกเลิกการอนุญาตให้บันทึกไฟล์แล้ว ไม่มีอะไรในคลังเปลี่ยนแปลง",
    "conversao_cancelada_o_pdf_original_per": "ยกเลิกการแปลง PDF ต้นฉบับยังอยู่ในคลัง",
    "preparando_salvamento": "กำลังเตรียมบันทึก…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "สำเนา PDF ไม่พร้อมใช้งานในคลัง",
    "reconstruindo_o_livro_localmente": "กำลังสร้างหนังสือใหม่บนอุปกรณ์ของคุณ",
    "convertendo_pdf": "กำลังแปลง PDF",
    "nao_foi_possivel_compartilhar_o_livro": "ไม่สามารถแชร์หนังสือได้",
    "o_arquivo_foi_preparado_para_voce_comp": "ไฟล์พร้อมให้คุณแชร์ในแอปอื่น",
    "livro_compartilhado": "แชร์หนังสือแล้ว",
    "a_copia_deste_livro_nao_esta_disponive": "สำเนาของหนังสือเล่มนี้ไม่พร้อมในคลัง",
    "para_manter_a_politica_de_compartilham": "เพื่อรักษานโยบายการแชร์ของคลัง ไฟล์ EPUB และ MOBI ไม่สามารถแชร์ผ่านแอปนี้ได้",
    "quadrinhos_ficam_guardados_somente_no": "การ์ตูนถูกเก็บไว้เฉพาะในอุปกรณ์ของคุณและไม่สามารถแชร์ผ่านแอปนี้ได้",
    "audiolivros_e_videos_ficam_guardados_s": "หนังสือเสียงและวิดีโอถูกเก็บไว้เฉพาะในอุปกรณ์ของคุณและไม่สามารถแชร์ผ่านแอปนี้ได้",
    "formato_protegido": "รูปแบบที่ได้รับการป้องกัน",
    "compartilhamento_indisponivel": "การแชร์ไม่พร้อมใช้งาน",
    "concluido": "เสร็จ",
    "ainda_nao_comecado": "ยังไม่เริ่ม",
    "continue_lendo": "อ่านต่อ",
    "continue_ouvindo": "ฟังต่อ",
    "continue_assistindo": "ดูต่อ",
    "comece_por_aqui": "เริ่มที่นี่",
    "comece_a_ouvir": "เริ่มฟัง",
    "comece_a_assistir": "เริ่มดู",
    "no_total": "ทั้งหมด",
    "para_ler": "ที่จะอ่าน",
    "sua_estante": "ชั้นของคุณ",
    "livros_organizados_pela_opcao_selecion": "หนังสือจัดเรียงตามตัวเลือกที่เลือก",
    "uma_prateleira_para_cada_tipo_de_arqui": "หนึ่งชั้นสำหรับไฟล์แต่ละประเภท",
    "autores_agrupados_em_ordem_alfabetica": "ผู้เขียนจัดกลุ่มตามตัวอักษร",
    "toque_para_continuar_de_onde_parou": "แตะเพื่ออ่านต่อจากที่ค้างไว้",
    "para_ler_2": "ที่จะอ่าน",
    "lendo_agora": "กำลังอ่าน",
    "audio_e_video": "เสียงและวิดีโอ",
    "trechos_salvos_separadamente_dos_marca": "ข้อความที่บันทึกแยกจากที่คั่น",
    "comentarios_vinculados_a_trechos_selec": "ความคิดเห็นที่ผูกกับข้อความที่เลือก",
    "paginas_salvas_para_voltar_rapidamente": "หน้าที่บันทึกไว้เพื่อกลับมาอย่างรวดเร็ว",
    "do_maior_para_o_menor_progresso_de_lei": "จากความคืบหน้ามากไปน้อย",
    "livros_adicionados_ou_lidos_mais_recen": "หนังสือที่เพิ่มหรืออ่านล่าสุด",
    "ordem_alfabetica_pelo_titulo": "ตามตัวอักษรตามชื่อเรื่อง",
    "separa_em_prateleiras_de_epub_pdf_docx": "แบ่งเป็นชั้นของ EPUB, PDF, DOCX, หนังสือเสียง, วิดีโอ…",
    "tipo_de_arquivo": "ประเภทไฟล์",
    "organiza_e_separa_os_livros_por_autor": "จัดและแยกหนังสือตามผู้เขียน",
    "agrupar_por_autor": "จัดกลุ่มตามผู้เขียน",
    "pressione_o_livro_e_mova_o": "กดค้างที่หนังสือแล้วเลื่อน",
    "minha_ordem": "ลำดับของฉัน",
    "epub_pronto": "EPUB พร้อม",
    "conversao_concluida": "การแปลงเสร็จ",
    "necessario_para_salvar_o_epub_ao_lado": "จำเป็นเพื่อบันทึก EPUB ข้างต้นฉบับ",
    "escolha_a_pasta_do_pdf": "เลือกโฟลเดอร์ของ PDF",
    "processando": "กำลังทำงาน…",
    "processamento_local_no_navegador": "ประมวลผลบนอุปกรณ์ของคุณ ในเบราว์เซอร์",
    "convertendo_livro": "กำลังแปลงหนังสือ",
    "livro_em_pdf": "หนังสือ PDF",
    "recalculando_paginas": "กำลังคำนวณหน้าใหม่...",
    "ajustando_leitura": "กำลังปรับเลย์เอาต์",
    "abrir_comentario": "เปิดความคิดเห็น",
    "anotacao_salva": "บันทึกแล้ว",
    "anotacao_atualizada": "อัปเดตบันทึกแล้ว",
    "escreva_uma_nota_antes_de_salvar": "เขียนโน้ตก่อนกดบันทึก",
    "nao_foi_possivel_compartilhar": "ไม่สามารถแชร์ได้",
    "compartilhamento_indisponivel_2": "การแชร์ไม่พร้อมใช้งาน",
    "credito_do_trecho": "— {obra}, {autor}",
    "credito_do_trecho_sem_autor": "— {obra}",
    "trecho_copiado": "คัดลอกข้อความแล้ว",
    "trecho_compartilhado": "แชร์ข้อความแล้ว",
    "citacao_salva": "บันทึกข้อความอ้างอิงแล้ว",
    "trecho_grifado": "ไฮไลต์ข้อความแล้ว",
    "grifo_removido": "ลบไฮไลต์แล้ว",
    "comentario_apagado": "ลบความคิดเห็นแล้ว",
    "remover_grifo": "ลบไฮไลต์",
    "apagar_comentario": "ลบความคิดเห็น",
    "remover_grifo_2": "ลบไฮไลต์?",
    "apagar_comentario_2": "ลบความคิดเห็น?",
    "remover_este_grifo": "ลบไฮไลต์นี้?",
    "apagar_este_comentario": "ลบความคิดเห็นนี้?",
    "sem_comentario": "ไม่มีความคิดเห็น",
    "comentario": "ความคิดเห็น",
    "marcador_removido_desta_pagina": "ลบที่คั่นออกจากหน้านี้แล้ว",
    "pagina_adicionada_aos_marcadores": "เพิ่มหน้าในที่คั่นแล้ว",
    "este_e_o_inicio_do_livro": "นี่คือจุดเริ่มต้นของหนังสือ",
    "esta_e_a_primeira_pagina": "นี่คือหน้าแรก",
    "voce_chegou_ao_fim_do_livro": "คุณมาถึงจุดสิ้นสุดของหนังสือแล้ว",
    "voce_chegou_ao_fim_do_quadrinho": "คุณมาถึงจุดสิ้นสุดของการ์ตูนแล้ว",
    "agora_em_revista_aberta_duas_paginas_l": "ตอนนี้ในมุมมองสองหน้า: สองหน้าติดกัน ปกแยก",
    "leitura_horizontal_ativada_neste_livro": "เปิดการอ่านแนวนอนสำหรับหนังสือเล่มนี้",
    "rolagem_vertical_ativada_neste_livro": "เปิดการเลื่อนแนวตั้งสำหรับหนังสือเล่มนี้",
    "leitura_pagina_a_pagina_ativada_neste": "เปิดการอ่านทีละหน้าสำหรับการ์ตูนนี้",
    "rolagem_continua_ativada_neste_quadrin": "เปิดการเลื่อนต่อเนื่องสำหรับการ์ตูนนี้",
    "mudar_para_rolagem_vertical": "เปลี่ยนเป็นการเลื่อนแนวตั้ง",
    "mudar_para_leitura_horizontal": "เปลี่ยนเป็นการอ่านแนวนอน",
    "rolagem_continua_estilo_webtoon": "การเลื่อนต่อเนื่อง (สไตล์เว็บตูน)",
    "voltar_para_pagina_a_pagina": "กลับไปทีละหน้า",
    "separando_os_capitulos": "กำลังแยกบท...",
    "lendo_o_livro": "กำลังอ่านหนังสือ",
    "lendo_o_markdown": "กำลังอ่าน Markdown",
    "lendo_o_documento": "กำลังอ่านเอกสาร",
    "pagina_indisponivel": "หน้าไม่พร้อมใช้งาน",
    "isto_acontece_so_desta_vez": "สิ่งนี้เกิดขึ้นครั้งนี้เท่านั้น",
    "preparando_o_quadrinho": "กำลังเตรียมการ์ตูน",
    "abrindo_o_quadrinho": "กำลังเปิดการ์ตูน...",
    "montando_as_paginas": "กำลังสร้างหน้า...",
    "nao_foi_possivel_abrir_este_livro": "ไม่สามารถเปิดหนังสือเล่มนี้ได้",
    "abertura_cancelada": "ยกเลิกการเปิดแล้ว",
    "o_livro_demorou_demais_para_abrir_e_fo": "หนังสือใช้เวลาเปิดนานเกินไปและถูกหยุด",
    "importe_o_arquivo_novamente_para_conti": "นำเข้าไฟล์อีกครั้งเพื่ออ่านต่อ",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "ไฟล์ของหนังสือเล่มนี้ไม่ได้บันทึกในอุปกรณ์อีกต่อไป",
    "preparando_sua_leitura": "กำลังเตรียมการอ่านของคุณ...",
    "abrindo_livro": "กำลังเปิดหนังสือ",
    "leitura_concluida": "อ่านเสร็จ",
    "a_voz_foi_interrompida_pelo_navegador": "เบราว์เซอร์หยุดเสียง",
    "nao_foi_possivel_preparar_este_trecho": "ไม่สามารถเตรียมข้อความนี้สำหรับเสียงได้",
    "a_leitura_em_voz_alta_nao_e_suportada": "เบราว์เซอร์นี้ไม่รองรับการอ่านออกเสียง",
    "pausar_leitura": "หยุดการอ่านชั่วคราว",
    "em_pausa": "หยุดชั่วคราว",
    "leitura_em_voz_alta_nao_disponivel_nes": "การอ่านออกเสียงไม่พร้อมในเบราว์เซอร์นี้",
    "nome_do_marcador": "ชื่อที่คั่น",
    "o_marcador_sera_removido_deste_audioli": "ที่คั่นจะถูกลบออกจากหนังสือเสียงนี้",
    "nao_foi_possivel_salvar_o_marcador": "ไม่สามารถบันทึกที่คั่นได้",
    "ja_existe_um_marcador_neste_ponto": "มีที่คั่น ณ จุดนี้อยู่แล้ว",
    "timer_de_sono_encerrado": "หมดเวลาตั้งเวลาหลับ",
    "fim_do_cap": "จบบท",
    "timer_desativado": "ปิดตัวจับเวลาแล้ว",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "เสียงจะหยุดเมื่อสิ้นสุดบท",
    "este_audiolivro_nao_tem_capitulos": "หนังสือเสียงนี้ไม่มีบท",
    "ao_fim_do_capitulo": "เมื่อสิ้นสุดบท",
    "desativar_timer": "ปิดตัวจับเวลา",
    "mais_10_minutos_no_timer": "เพิ่ม 10 นาทีในตัวจับเวลา",
    "somar_10_minutos": "เพิ่ม 10 นาที",
    "pausa_ao_fim_do_capitulo": "หยุดเมื่อสิ้นสุดบท",
    "no_livro_todo": "ทั่วทั้งเล่ม",
    "video": "วิดีโอ",
    "audiolivro_concluido": "หนังสือเสียงเสร็จ",
    "video_concluido": "วิดีโอเสร็จ",
    "video_2": "วิดีโอ",
    "audio": "เสียง",
    "toque_em_reproduzir_para_comecar": "แตะเล่นเพื่อเริ่ม",
    "falha_ao_carregar_o_audio": "โหลดเสียงไม่สำเร็จ",
    "exclua_o_da_biblioteca_e_importe_o_arq": "ลบออกจากคลังและนำเข้าไฟล์อีกครั้ง",
    "os_nomes_dos_arquivos_seguem_uma_seque": "ชื่อไฟล์เรียงตามลำดับ จึงดูเหมือนเป็นบทของหนังสือเสียงเดียวกัน",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "ไฟล์มีอัลบั้มเดียวกันในแท็ก จึงดูเหมือนเป็นบทของหนังสือเสียงเดียวกัน",
    "libere_espaco_ou_exclua_livros_da_bibl": "เพิ่มพื้นที่ว่างหรือลบหนังสือออกจากคลังแล้วลองอีกครั้ง",
    "o_armazenamento_do_aparelho_esta_cheio": "ที่จัดเก็บของอุปกรณ์เต็ม",
    "preparando_a_capa": "กำลังเตรียมปก...",
    "remova_esse_arquivo_da_selecao_e_tente": "ลบไฟล์นั้นออกจากการเลือกแล้วลองอีกครั้ง",
    "sequencia": "ลำดับ",
    "o_arquivo_pode_estar_incompleto_tente": "ไฟล์อาจไม่สมบูรณ์ ลองดาวน์โหลดอีกครั้ง",
    "conferindo_se_o_audio_pode_ser_reprodu": "กำลังตรวจว่าเสียงเล่นได้หรือไม่...",
    "conferindo_se_o_video_pode_ser_reprodu": "กำลังตรวจว่าวิดีโอเล่นได้หรือไม่...",
    "lendo_titulo_capitulos_e_capa": "กำลังอ่านชื่อเรื่อง บทและปก...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "ไฟล์อาจเสียหาย หรืออยู่ในรูปแบบเสียงที่เบราว์เซอร์เล่นไม่ได้ ลองแปลงเป็น MP3 หรือ M4B (AAC)",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "ไฟล์อาจเสียหาย หรืออยู่ในรูปแบบวิดีโอที่เบราว์เซอร์เล่นไม่ได้ ลองแปลงเป็น MP4 ที่ใช้วิดีโอ H.264 และเสียง AAC",
    "converta_o_audiolivro_para_m4b_com_aud": "แปลงหนังสือเสียงเป็น M4B ด้วยเสียง AAC (หรือ MP3) แล้วนำเข้าใหม่",
    "converta_o_video_para_mp4_com_audio_aa": "แปลงวิดีโอเป็น MP4 ด้วยเสียง AAC และวิดีโอ H.264 แล้วนำเข้าใหม่",
    "o_navegador_nao_reproduz_o_formato_de": "เบราว์เซอร์ไม่เล่นรูปแบบเสียงของไฟล์นี้",
    "arquivos_com_protecao_nao_podem_ser_re": "ไฟล์ที่มีการป้องกันไม่สามารถเล่นที่นี่ได้ ใช้สำเนาที่ไม่มี DRM",
    "nao_ha_espaco_suficiente_no_aparelho_p": "ไม่มีที่พอในอุปกรณ์สำหรับหนังสือเสียงนี้",
    "confira_se_a_extensao_corresponde_ao_c_2": "ตรวจสอบว่านามสกุลตรงกับเนื้อหา หรือแปลงเสียงเป็น MP3 หรือ M4B (AAC)",
    "imagem_invalida": "รูปภาพไม่ถูกต้อง",
    "imagem_demorou_demais": "รูปภาพใช้เวลาโหลดนานเกินไป",
    "imagem_vazia": "รูปภาพว่างเปล่า",
    "inicio": "เริ่ม",
    "mp4_moov_nao_encontrado": "วิดีโอดูเหมือนจะไม่สมบูรณ์หรือเสียหาย",
    "pagina": "หน้า",
    "esta_pagina_nao_esta_disponivel": "หน้านี้ไม่พร้อมใช้งาน",
    "esta_pagina_nao_pode_ser_descompactada": "ไม่สามารถแตกหน้านี้ได้",
    "quadrinho_fechado": "ปิดการ์ตูนแล้ว",
    "ele_pode_estar_incompleto_dividido_em": "อาจไม่สมบูรณ์ แบ่งเป็นหลายส่วน หรือเป็น RAR แบบที่แอปไม่รู้จัก การแปลงเป็น CBZ มักแก้ได้",
    "remova_a_senha_do_arquivo_e_importe_de": "ลบรหัสผ่านออกจากไฟล์แล้วนำเข้าใหม่",
    "nao_foi_possivel_ler_este_arquivo_de_q": "ไม่สามารถอ่านไฟล์การ์ตูนนี้ได้",
    "este_quadrinho_esta_protegido_por_senh": "การ์ตูนนี้ได้รับการป้องกันด้วยรหัสผ่าน",
    "lendo_o_indice_do_quadrinho": "กำลังอ่านสารบัญการ์ตูน...",
    "o_arquivo_pode_ser_grande_demais_para": "ไฟล์อาจใหญ่เกินไปสำหรับหน่วยความจำของอุปกรณ์นี้ การแบ่งการ์ตูนเป็นส่วนเล็ก ๆ มักแก้ได้",
    "nao_foi_possivel_abrir_este_quadrinho": "ไม่สามารถเปิดการ์ตูนนี้ได้",
    "lendo_o_arquivo": "กำลังอ่านไฟล์...",
    "preparando_o_leitor_de_cbr": "กำลังเตรียมเครื่องอ่าน CBR...",
    "o_arquivo_pode_estar_incompleto_proteg": "ไฟล์อาจไม่สมบูรณ์ ได้รับการป้องกันด้วยรหัสผ่านหรือเสียหาย",
    "nao_foi_possivel_ler_este_quadrinho": "ไม่สามารถอ่านการ์ตูนนี้ได้",
    "o_arquivo_precisa_conter_imagens_jpg_p": "ไฟล์ต้องมีรูปภาพ (JPG, PNG, WEBP หรือ GIF)",
    "nao_encontramos_paginas_dentro_deste_q": "ไม่พบหน้าใด ๆ ในการ์ตูนนี้",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "ไม่มีที่พอในอุปกรณ์สำหรับการ์ตูนนี้",
    "cabecalho_de_item_invalido": "ไฟล์เสียหายบางส่วน",
    "a_pasta_vendor_libarchive_precisa_esta": "แอปขาดส่วนประกอบที่ใช้เปิดการ์ตูนเล่มนี้ แปลงเป็น CBZ หรือติดตั้งแอปใหม่",
    "o_leitor_de_cbr_nao_foi_encontrado": "ไม่พบเครื่องอ่าน CBR",
    "converta_o_quadrinho_para_cbz_zip_e_im": "แปลงการ์ตูนเป็น CBZ (ZIP) แล้วนำเข้าใหม่",
    "este_navegador_nao_consegue_abrir_arqu": "เบราว์เซอร์นี้ไม่สามารถเปิดไฟล์ CBR ได้",
    "convertendo_o_markdown": "กำลังแปลง Markdown",
    "lendo_o_texto": "กำลังอ่านข้อความ",
    "pdf_indisponivel": "PDF ไม่พร้อมใช้งาน",
    "epub_invalido_nenhum_capitulo_no_spine": "EPUB นี้เสียหาย: ไม่พบบทของหนังสือ",
    "livro_sem_titulo": "หนังสือไม่มีชื่อ",
    "epub_invalido_arquivo_opf_nao_encontra": "EPUB นี้ไม่สมบูรณ์หรือเสียหาย จึงเปิดไม่ได้",
    "epub_invalido_container_xml_nao_encont": "EPUB นี้ไม่สมบูรณ์หรือเสียหาย จึงเปิดไม่ได้",
    "organizando_o_texto": "กำลังจัดเรียงข้อความ",
    "descompactando_o_livro": "กำลังแตกหนังสือ",
    "nao_encontramos_conteudo_para_exibir_n": "ไม่พบเนื้อหาที่จะแสดงในไฟล์นี้",
    "livro_sem_texto_legivel": "หนังสือที่ไม่มีข้อความที่อ่านได้",
    "o_arquivo_pode_estar_corrompido_tente": "ไฟล์อาจเสียหาย ลองแปลงเป็น EPUB",
    "nao_foi_possivel_extrair_o_texto_deste": "ไม่สามารถดึงข้อความจาก MOBI นี้ได้",
    "nenhum_registro_de_conteudo_foi_encont": "ไม่พบเนื้อหาของหนังสือในไฟล์นี้",
    "arquivo_mobi_sem_texto": "ไฟล์ MOBI ไม่มีข้อความ",
    "o_dicionario_de_compressao_esta_vazio": "เนื้อหาบางส่วนของ MOBI นี้หายไป",
    "arquivo_mobi_incompleto": "ไฟล์ MOBI ไม่สมบูรณ์",
    "as_tabelas_de_compressao_nao_foram_enc": "เนื้อหาบางส่วนของ MOBI นี้หายไป",
    "converta_o_arquivo_para_epub_em_um_pro": "แปลงไฟล์เป็น EPUB ในโปรแกรมเช่น Calibre แล้วนำเข้าใหม่",
    "compressao_mobi_nao_reconhecida": "MOBI นี้ใช้รูปแบบภายในที่แอปไม่รู้จัก",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "ไม่สามารถอ่านส่วนหัวของหนังสือได้",
    "arquivo_mobi_corrompido": "ไฟล์ MOBI เสียหาย",
    "a_lista_interna_de_registros_esta_inco": "ไฟล์ไม่สมบูรณ์ ลองดาวน์โหลดหรือแปลงใหม่อีกครั้ง",
    "o_download_parece_ter_sido_interrompid": "การดาวน์โหลดดูเหมือนถูกขัดจังหวะ ดาวน์โหลดไฟล์อีกครั้ง",
    "tabela_de_compressao_mobi_corrompida": "ไฟล์ MOBI นี้เสียหายบางส่วน",
    "tabela_de_compressao_mobi_incompleta": "ไฟล์ MOBI นี้ไม่สมบูรณ์",
    "tabela_de_compressao_mobi_invalida": "ไฟล์ MOBI นี้เสียหายบางส่วน",
    "este_arquivo_docx_nao_tem_conteudo_de": "ไฟล์ .docx นี้ไม่มีเนื้อหาข้อความที่จะแสดง",
    "documento_sem_texto": "เอกสารไม่มีข้อความ",
    "o_arquivo_pode_estar_corrompido_proteg": "ไฟล์อาจเสียหาย ได้รับการป้องกันด้วยรหัสผ่าน หรือเป็น .doc เก่า บันทึกใหม่เป็น .docx แล้วนำเข้าอีกครั้ง",
    "nao_foi_possivel_ler_este_arquivo_docx": "ไม่สามารถอ่านไฟล์ DOCX นี้ได้",
    "convertendo_o_documento": "กำลังแปลงเอกสาร",
    "conecte_se_a_internet_uma_vez_para_bai": "เชื่อมต่ออินเทอร์เน็ตหนึ่งครั้งเพื่อดาวน์โหลดส่วนประกอบ แล้วเปิดหนังสืออีกครั้ง",
    "o_conversor_de_docx_nao_carregou": "ตัวแปลง DOCX ไม่โหลด",
    "video_mp4": "วิดีโอ (MP4)",
    "audiolivro_m4b": "หนังสือเสียง (M4B)",
    "audiolivro_mp3": "หนังสือเสียง (MP3)",
    "quadrinho_cbt": "การ์ตูน (CBT)",
    "quadrinho_cb7": "การ์ตูน (CB7)",
    "quadrinho_cbr": "การ์ตูน (CBR)",
    "quadrinho_cbz": "การ์ตูน (CBZ)",
    "markdown_md": "Markdown (MD)",
    "texto_txt": "ข้อความ (TXT)",
    "word_docx": "Word (DOCX)",
    "gravacao_cancelada": "ยกเลิกการบันทึกแล้ว",
    "o_arquivo_esta_vindo_do_armazenamento": "ไฟล์กำลังมาจากที่จัดเก็บบนคลาวด์มายังอุปกรณ์ของคุณ",
    "baixando_o_arquivo": "กำลังดาวน์โหลดไฟล์",
    "cancelando": "กำลังยกเลิก...",
    "use_grifar_citacao_anotar_ou_marcador": "ใช้ไฮไลต์ ข้อความอ้างอิง บันทึก หรือที่คั่นขณะอ่าน",
    "nenhuma_marcacao_ainda": "ยังไม่มีเครื่องหมาย",
    "trecho_original": "ข้อความต้นฉบับ",
    "procurar_meus_livros": "ค้นหาหนังสือของฉัน",
    "a_busca_fica_sempre_disponivel_no_menu": "การค้นหาอยู่ในเมนูด้านข้างเสมอ ใต้ระบบ",
    "da_para_fazer_depois": "ทำภายหลังได้",
    "nada_entra_na_estante_sem_a_sua_confir": "ไม่มีอะไรเข้าชั้นโดยไม่ได้รับการยืนยันจากคุณ: คุณเห็นรายการและเลือกที่จะนำเข้า",
    "voce_revisa_antes": "คุณตรวจสอบก่อน",
    "escolha_uma_pasta_downloads_e_um_bom_c": "เลือกโฟลเดอร์ แล้วแอปจะค้นหาในโฟลเดอร์นั้นและโฟลเดอร์ย่อยทั้งหมด",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "ค้นหา EPUB, MOBI, CBZ, CBR และ M4B",
    "voltar_e_revisar": "กลับไปตรวจสอบ",
    "ler_os_termos": "อ่านข้อกำหนด",
    "ler_a_politica": "อ่านนโยบาย",
    "os_dois_documentos_ficam_sempre_dispon": "เอกสารทั้งสองอยู่ในเมนูด้านข้างเสมอ ใต้เกี่ยวกับ",
    "leia_com_calma": "อ่านอย่างใจเย็น",
    "a_politica_e_os_termos_explicam_como_o": "นโยบายและข้อกำหนดอธิบายว่าแอปเก็บหนังสือของคุณอย่างไร และคุณทำอะไรกับหนังสือได้บ้าง หากต้องการใช้คลัง จำเป็นต้องยอมรับเอกสารเหล่านี้",
    "nada_acontece_sem_o_aceite": "เพื่อเริ่มต้นใช้งาน โปรดยอมรับข้อกำหนด",
    "aceitar_e_continuar": "ยอมรับและดำเนินการต่อ",
    "nao_aceito": "ไม่ยอมรับ",
    "termos_de_uso_2": "ข้อกำหนดการใช้งาน",
    "politica_de_privacidade_2": "นโยบายความเป็นส่วนตัว",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "แอปเข้าถึงเฉพาะไฟล์และโฟลเดอร์ที่คุณเลือก เมื่อคุณเลือก",
    "voce_no_controle": "คุณควบคุม",
    "depois_de_importar_um_livro_voce_le_se": "เมื่อนำเข้าหนังสือแล้ว คุณอ่านได้โดยไม่ต้องต่ออินเทอร์เน็ต",
    "funciona_offline": "ทำงานออฟไลน์",
    "livros_marcacoes_e_progresso_sao_guard": "หนังสือ เครื่องหมาย และความคืบหน้าถูกเก็บไว้ในอุปกรณ์ของคุณ ไม่มีอะไรส่งไปยังเซิร์ฟเวอร์ของเรา",
    "tudo_fica_no_seu_aparelho": "ทุกอย่างอยู่ในอุปกรณ์ของคุณ",
    "escolha_o_que_deseja_adicionar_a_bibli": "เลือกสิ่งที่ต้องการเพิ่มในคลัง ไฟล์ที่เหมือนกับที่มีอยู่แล้วในชั้นจะถูกข้ามโดยอัตโนมัติ",
    "voce_pode_tentar_outra_pasta_ou_import": "คุณสามารถลองโฟลเดอร์อื่น หรือนำเข้าไฟล์ด้วยปุ่ม +",
    "a_leitura_acontece_so_no_seu_dispositi": "การอ่านเกิดขึ้นบนอุปกรณ์ของคุณเท่านั้น",
    "voce_escolhe_a_pasta": "คุณเลือกโฟลเดอร์",
    "tema_tipografia_margens_modo_de_virada": "ธีม แบบอักษร ระยะขอบ โหมดเปลี่ยนหน้า และการตั้งค่าเสียง",
    "restaurar_minhas_preferencias": "คืนค่าการตั้งค่าของฉัน",
    "o_backup_manda_as_marcacoes_atuais_dos": "สำรองชนะ เครื่องหมายปัจจุบันของหนังสือในไฟล์จะถูกแทนที่ด้วยของสำรอง",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "ไม่มีอะไรถูกลบ เครื่องหมายจากทั้งสองฝั่งรวมกันและความคืบหน้าที่ใหม่กว่าชนะ",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "จะทำอย่างไรกับสิ่งที่มีอยู่ในชั้นแล้ว",
    "grifos_citacoes_e_notas": "ไฮไลต์ ข้อความอ้างอิง และบันทึก",
    "preparando_o_arquivo_2": "กำลังเตรียมไฟล์...",
    "os_livros_em_si_nem_as_capas_por_isso": "ไม่รวมทั้งตัวหนังสือและปก — ไฟล์จึงมีขนาดเพียงไม่กี่ KB ผู้รับต้องมีไฟล์หนังสือเพื่อให้เครื่องหมายกลับไปอยู่ที่เดิม ส่วนปกจะกลับมาโดยอัตโนมัติเมื่อนำเข้าหนังสือ",
    "nao_vai_no_arquivo": "ไม่มีในไฟล์",
    "o_seu_progresso_de_leitura_os_grifos_a": "ความคืบหน้าการอ่าน ไฮไลต์ ข้อความอ้างอิง บันทึก ที่คั่น และการจัดชั้นของคุณ — สถานะ รายการโปรด คอลเลกชัน ชุด และแท็ก",
    "vai_no_arquivo": "อยู่ในไฟล์",
    "descartar_o_que_esta_esperando_2": "ลบข้อมูลที่รออยู่",
    "esperando_o_arquivo": "กำลังรอไฟล์",
    "avisar_quando_fizer_tempo_sem_backup": "เตือนเมื่อไม่ได้สำรองนาน",
    "livros_que_ainda_nao_estiverem_na_esta": "หนังสือที่ยังไม่อยู่ในชั้นจะอยู่ในสถานะรอ: เมื่อคุณนำเข้าไฟล์ของหนังสือเหล่านั้น เครื่องหมายจะกลับมาโดยอัตโนมัติ",
    "restaurar_backup": "กู้คืนสำรอง",
    "salvar_backup": "บันทึกสำรอง",
    "ainda_nao_ha_itens": "ยังไม่มีอะไรที่นี่",
    "arraste_um_livro_para_outra_posicao_na": "ลากหนังสือไปที่อื่นในชั้นเพื่อบันทึกลำดับของคุณเอง ลำดับที่ตั้งเองจะมีความสำคัญเหนือการจัดกลุ่มตามผู้เขียน",
    "separe_por_virgulas": "คั่นด้วยจุลภาค",
    "ex_estudos_ficcao": "เช่น การศึกษา นิยาย...",
    "pasta_estante": "โฟลเดอร์ / ชั้น",
    "ex_trilogia": "เช่น ไตรภาค...",
    "serie": "ชุด",
    "aparece_em_favoritos": "ปรากฏในรายการโปรด",
    "nome_do_livro": "ชื่อหนังสือ",
    "nenhum_registro_ainda": "ยังไม่มีการบันทึก",
    "no_leitor_toque_no_icone_de_marcador_p": "ในเครื่องอ่าน แตะไอคอนที่คั่นเพื่อบันทึกหน้า",
    "nenhum_marcador_ainda": "ยังไม่มีที่คั่น",
    "a_gravacao_e_independente_da_localizac": "การบันทึกไม่ขึ้นกับตำแหน่งของ PDF และไม่เปลี่ยนไฟล์ต้นฉบับ",
    "o_pdf_original_nao_precisa_estar_nessa": "PDF ต้นฉบับไม่จำเป็นต้องอยู่ในโฟลเดอร์นั้น",
    "excluir_da_biblioteca": "ลบออกจากคลัง",
    "adicionar_livro": "เพิ่มหนังสือ",
    "adicione_livros_e_acompanhe_o_que_esta": "เพิ่มหนังสือและติดตามสิ่งที่รออยู่ กำลังดำเนินการ และคุณไปได้ไกลแค่ไหน",
    "tudo_pronto_para_a_proxima_leitura": "เตรียมพร้อมสำหรับการอ่านครั้งต่อไป",
    "sua_biblioteca": "คลังของคุณ",
    "arraste_um_livro_para_reposiciona_lo_a": "ลากหนังสือเพื่อย้าย: ชั้นจะเปลี่ยนเป็นลำดับของฉันและรักษาลำดับไว้",
    "importe_um_livro_ou_ajuste_seus_filtro": "นำเข้าหนังสือ หรือปรับตัวกรองของคุณ",
    "nada_por_aqui_ainda": "ยังไม่มีอะไรที่นี่",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "แตะ + และเลือกไฟล์ MP3, M4B หรือ MP4 ไฟล์ MP3 หลายบทสามารถรวมเป็นหนังสือเสียงเล่มเดียวได้",
    "nada_para_ouvir_ou_assistir_ainda": "ยังไม่มีอะไรให้ฟังหรือดู",
    "o_pdf_original_permanece_intacto_na_pa": "PDF ต้นฉบับยังคงอยู่ไม่ถูกแตะต้องในโฟลเดอร์ของคุณ",
    "paginas_como_imagem": "หน้าเป็นรูปภาพ",
    "paginas_do_pdf": "หน้าของ PDF",
    "em_navegadores_sem_suporte_a_acesso_di": "ในเบราว์เซอร์ที่ไม่รองรับการเข้าถึงระบบไฟล์โดยตรง EPUB จะถูกดาวน์โหลดแทน",
    "essa_permissao_e_dada_somente_a_esta_a": "การอนุญาตนี้ให้เฉพาะแอปนี้และป้องกันไม่ให้ไฟล์ต้นฉบับถูกเปลี่ยนแปลง",
    "selecione_a_pasta_que_contem_o_pdf": "เลือกโฟลเดอร์ที่มี PDF",
    "preparando": "กำลังเตรียม…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "ไฟล์กำลังถูกอ่านและสร้างใหม่ หนังสือขนาดใหญ่อาจใช้เวลาสักครู่",
    "revistas_apostilas_complexas_formulari": "นิตยสาร หนังสือเรียนที่ซับซ้อน แบบฟอร์ม เอกสารที่มีตารางมาก หรือ PDF ที่สแกนอาจสูญเสียเค้าโครงต้นฉบับบางส่วน",
    "funcionalidade_indicada_apenas_para_li": "เหมาะสำหรับหนังสือเท่านั้น",
    "o_epub_e_melhor_para_livros_com_texto": "EPUB เหมาะกับหนังสือที่มีข้อความเลือกได้ เพราะปรับแบบอักษร ขนาด ระยะขอบ และโหมดการอ่านได้",
    "trecho_selecionado": "ข้อความที่เลือก",
    "trecho_comentado": "ข้อความที่มีความคิดเห็น",
    "aplicando_zoom": "กำลังซูม...",
    "nao_foi_possivel_carregar_esta_pagina": "ไม่สามารถโหลดหน้านี้ได้",
    "nomear_marcador": "ตั้งชื่อที่คั่น",
    "toque_em_marcar_agora_para_guardar_est": "แตะ “ทำเครื่องหมายตอนนี้” เพื่อบันทึกจุดนี้และกลับมาเมื่อต้องการ",
    "timer_ativo": "เปิดตัวจับเวลา",
    "trecho_ausente_ou_corrompido_no_arquiv": "[ข้อความหายหรือเสียหายในไฟล์ต้นฉบับ]",
    "novos_livros_vao_abrir_em_leitura_v": "หนังสือใหม่จะเปิดในการอ่าน {v}",
    "leitura_efetivo_aplicada_a_este_livro": "ใช้การอ่าน {efetivo} กับหนังสือเล่มนี้",
    "automatico_neste_livro_leitura_efetivo": "อัตโนมัติในเล่มนี้: การอ่าน {efetivo}",
    "agora_esta_em_efetivo_no_automatico_fo": "ตอนนี้ตั้งเป็น {efetivo}; ในอัตโนมัติ {format} เปิดใน {padrao}",
    "esta_escolha_vale_so_para_v_cada_livro": "ตัวเลือกนี้ใช้เฉพาะกับ “{v}” แต่ละเล่มเก็บทิศทางการเลื่อนของตัวเอง",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} ยังไม่อยู่ในชั้นของคุณ",
    "escolha_uma_pasta_para_procurar_label": "เลือกโฟลเดอร์เพื่อค้นหา {label}",
    "subtitle_versao_build": "{subtitle} · เวอร์ชัน {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "ไม่สามารถอ่าน {path}; ใช้ข้อความในตัว",
    "seu_ultimo_backup_foi_ha_dias_dias": "สำรองครั้งสุดท้ายของคุณเมื่อ {dias} วันก่อน",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "หนังสือ {aguardando} เล่มจากข้อมูลสำรองยังไม่อยู่ที่นี่ ความคืบหน้าและเครื่องหมายของหนังสือเล่มนั้นถูกเก็บไว้แล้ว: เมื่อคุณนำเข้าไฟล์ ทุกอย่างจะกลับเข้าที่โดยอัตโนมัติ",
      "other": "หนังสือ {aguardando} เล่มจากข้อมูลสำรองยังไม่อยู่ที่นี่ ความคืบหน้าและเครื่องหมายของหนังสือเหล่านั้นถูกเก็บไว้แล้ว: เมื่อคุณนำเข้าแต่ละไฟล์ ทุกอย่างจะกลับเข้าที่โดยอัตโนมัติ"
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "หนังสือ {atualizados} เล่มในชั้นของคุณถูกอัปเดต",
      "other": "หนังสือ {atualizados} เล่มในชั้นของคุณถูกอัปเดต"
    },
    "criado_em_quando": "สร้างเมื่อ {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "สำรองพร้อม: {livros} เล่มและ {marcacoes} เครื่องหมาย",
    "endereco_seguro_seguro": "ที่อยู่ปลอดภัย: {seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "กู้คืนความคืบหน้าและ {marcas} เครื่องหมายสำหรับหนังสือเล่มนี้แล้ว",
      "other": "กู้คืนความคืบหน้าและ {marcas} เครื่องหมายสำหรับหนังสือเล่มนี้แล้ว"
    },
    "restaurando_v_de_length": "กำลังกู้คืน ({v} จาก {length})...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} เล่ม · {marcacoes} เครื่องหมาย",
    "criado_em_v": "สร้างเมื่อ {v}",
    "reunindo_a_sua_estante_v_de_length": "กำลังรวบรวมชั้นของคุณ ({v} จาก {length})...",
    "titulo_ja_foi_importado_antes_e_contin": "“{titulo}” ถูกนำเข้ามาก่อนและยังอยู่ในคลังของคุณ ไม่มีการสร้างสำเนาใหม่",
    "length_arquivos_de_audio": "{length} ไฟล์เสียง...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "ไฟล์ {falhas} ไฟล์อ่านไม่ได้",
      "other": "ไฟล์ {falhas} ไฟล์อ่านไม่ได้"
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} อยู่ในคลังแล้วและถูกข้าม",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "เพิ่มหนังสือ {importados} เล่มในชั้นของคุณแล้ว",
      "other": "เพิ่มหนังสือ {importados} เล่มในชั้นของคุณแล้ว"
    },
    "epub_salvo_em_filename": "บันทึก EPUB ใน {fileName}",
    "falha_ao_converter_o_pdf_v": "แปลง PDF ไม่สำเร็จ: {v}",
    "pagina_page_de_totalpages": "หน้า {page} จาก {totalPages}",
    "totalpages_paginas": {
      "one": "{totalPages} หน้า",
      "other": "{totalPages} หน้า"
    },
    "length_resultado_s_para_search": {
      "one": "{length} ผลลัพธ์สำหรับ “{search}”",
      "other": "{length} ผลลัพธ์สำหรับ “{search}”"
    },
    "capitulo_v": "บท {v}",
    "organizando_capitulo_v_de_totalchapter": "กำลังจัดบท {v} จาก {totalChapters}",
    "pagina_v": "หน้า {v}",
    "paginas_v_v2": "หน้า {v}–{v2}",
    "length_pagina_s_prontas": {
      "one": "{length} หน้าพร้อม",
      "other": "{length} หน้าพร้อม"
    },
    "montando_as_paginas_pagessofar_prontas": "กำลังสร้างหน้า — {pagesSoFar} เสร็จ",
    "lendo_pagina_v_de_length": "กำลังอ่านหน้า {v} จาก {length}",
    "marcador_salvo_em_t": "บันทึกที่คั่นที่ {t}",
    "o_audio_vai_pausar_em_minutes_minutos": "เสียงจะหยุดใน {minutes} นาที",
    "length_capitulos_toque_para_ir_direto": "{length} บท · แตะเพื่อไปตรงนั้น",
    "narrado_por_narrator": "บรรยายโดย {narrator}",
    "velocidade_de_reproducao_rate": "ความเร็วเล่น: {rate}",
    "avancar_f_segundos": "ไปข้างหน้า {f} วินาที",
    "nao_foi_possivel_abrir_este_v": "ไม่สามารถเปิด {v} นี้ได้",
    "nao_foi_possivel_ler_o_arquivo_de_v": "ไม่สามารถอ่านไฟล์ {v} ได้",
    "o_v_esta_danificado_neste_ponto": "{v} เสียหาย ณ จุดนี้",
    "o_navegador_nao_consegue_reproduzir_es": "เบราว์เซอร์ไม่สามารถเล่นไฟล์ {v} นี้ได้",
    "nao_foi_possivel_reproduzir_este_v": "ไม่สามารถเล่น {v} นี้ได้",
    "os_dados_deste_noun_estao_incompletos": "ข้อมูลของ {noun} นี้ไม่สมบูรณ์",
    "importe_o_arquivo_novamente_para_conti_2": "นำเข้าไฟล์อีกครั้งเพื่อ{v}ต่อ",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "ไฟล์ของ {noun} นี้ไม่ได้บันทึกในอุปกรณ์อีกต่อไป",
    "nao_foi_possivel_descobrir_a_duracao_d": "ไม่สามารถทราบความยาวของ “{name}”",
    "lendo_faixa_v_de_length": "กำลังอ่านแทร็ก {v} จาก {length}...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "ไม่สามารถทราบความยาวของ {v} นี้",
    "este_format_nao_pode_ser_reproduzido_n": "{format} นี้ไม่สามารถเล่นในเบราว์เซอร์นี้ได้",
    "este_format_esta_protegido_por_drm": "{format} นี้ได้รับการป้องกันด้วย DRM",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "ไฟล์มี {bytes} และเหลือประมาณ {v} เพิ่มพื้นที่หรือลบหนังสือออกจากคลัง",
    "este_arquivo_nao_e_um_format_valido": "ไฟล์นี้ไม่ใช่ {format} ที่ถูกต้อง",
    "preparando_as_paginas_vistas_de_total": "กำลังเตรียมหน้า ({vistas} จาก {total})...",
    "preparando_total_pagina_s": {
      "one": "กำลังเตรียม {total} หน้า...",
      "other": "กำลังเตรียม {total} หน้า..."
    },
    "preparando_as_paginas_v_de_total": "กำลังเตรียมหน้า ({v} จาก {total})...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "ใช้ประมาณ {bytes} และเหลือประมาณ {v} เพิ่มพื้นที่หรือลบหนังสือออกจากคลัง",
    "envio_direto_exige_endereco_seguro": "ส่งไปยังแอปอื่นโดยตรงไม่ได้ เพราะหน้านี้ไม่ได้เปิดจากที่อยู่ที่ปลอดภัย บันทึกไฟล์แล้วส่งผ่านแอปที่คุณต้องการ",
    "na_estante": "บนชั้น",
    "nao_foi_possivel_montar_o_arquivo": "ไม่สามารถสร้างไฟล์ได้",
    "este_navegador_nao_oferece_o_envio_dir": "เบราว์เซอร์นี้ไม่ให้การส่งตรงไปยังแอปอื่น บันทึกไฟล์และแนบผ่านแอปที่คุณต้องการ",
    "voce_ainda_nao_fez_nenhum_backup": "คุณยังไม่ได้สร้างสำรอง",
    "converter_para_epub": "แปลงเป็น EPUB",
    "esta_pagina_nao_pode_ser_exibida": "ไม่สามารถแสดงหน้านี้ได้",
    "na_ordem_em_que_serao_tocados": "ตามลำดับที่จะเล่น",
    "este_capitulo_nao_pode_ser_exibido": "ไม่สามารถแสดงบทนี้ได้",
    "livro": "หนังสือ",
    "restantes": " เหลือ",
    "como_seus_dados_sao_tratados": "ข้อมูลของคุณถูกจัดการอย่างไร",
    "condicoes_de_uso_do_aplicativo": "เงื่อนไขการใช้แอป",
    "audiolivro": "หนังสือเสียง",
    "sobre_o_aplicativo": "เกี่ยวกับแอป",
    "o_que_e_o_veredas_reader": "Veredas Reader คืออะไร",
    "o_aparelho_recusou_o_tipo_do_arquivo": "(อุปกรณ์นี้ไม่รองรับการแชร์ไฟล์ประเภทนี้)",
    "livros": "หนังสือ",
    "lendo": "กำลังอ่าน",
    "lidos": "อ่านแล้ว",
    "compartilhar_livro": "แชร์หนังสือ",
    "n_livros": {
      "one": "{n} เล่ม",
      "other": "{n} เล่ม"
    },
    "livros_unidade": {
      "one": "เล่ม",
      "other": "เล่ม"
    },
    "uma_faixa_discreta_depois_de_n_dias": "แถบเงียบ ๆ บนชั้นหลังจาก {n} วันโดยไม่สำรอง ไม่รบกวนการอ่านของคุณ",
    "scanned_arquivos_verificados_livros_enc": "ตรวจ {scanned} ไฟล์ · พบ {encontrados} เล่ม",
    "v_de_total": "{v} จาก {total}",
    "voltar_n_segundos": "ย้อน {n} วินาที",
    "cancelado": "ยกเลิกแล้ว",
    "arquivo": "ไฟล์",
    "outro": "อื่น ๆ",
    "outros": "อื่น ๆ",
    "audiolivro_2": "หนังสือเสียง",
    "pausar": "หยุด",
    "marcador": "ที่คั่น",
    "leitura": "การอ่าน",
    "grifo": "ไฮไลต์",
    "editar": "แก้ไข",
    "apagar": "ลบ",
    "concluir": "เสร็จสิ้น",
    "recentes": "ล่าสุด",
    "progresso": "ความคืบหน้า",
    "entendi": "เข้าใจแล้ว",
    "aviso": "แจ้งเตือน",
    "descartar": "ลบ",
    "copiado": "คัดลอกแล้ว",
    "restaurar": "กู้คืน",
    "restaurando": "กำลังกู้คืน",
    "excluir": "ลบ",
    "grifos": "ไฮไลต์",
    "arquivo_vazio": "ไฟล์ว่างเปล่า",
    "e_mais_n_arquivos": {
      "one": "และอีก {n} ไฟล์ ตามลำดับที่จะเล่น",
      "other": "และอีก {n} ไฟล์ ตามลำดับที่จะเล่น"
    },
    "n_arquivos_mp3": {
      "one": "MP3 {n} ไฟล์",
      "other": "MP3 {n} ไฟล์"
    },
    "pct_restam": "{pct}% · เหลือ {tempo}",
    "n_minutos": {
      "one": "{n} นาที",
      "other": "{n} นาที"
    },
    "ir_para_tempo": "ไปที่ {tempo}",
    "nomear": "ตั้งชื่อ",
    "parte_n": "ส่วนที่ {n}",
    "carregando_pagina_n": "กำลังโหลดหน้า {n}...",
    "selecionar_pasta_e_continuar": "เลือกโฟลเดอร์แล้วดำเนินการต่อ",
    "ler_agora": "อ่านเลย",
    "agrupamento_v": "การจัดกลุ่ม: {v}",
    "tempo_restante": "เหลือ {tempo}",
    "abrir_titulo": "เปิด {titulo}",
    "continuar_lendo_titulo": "อ่าน {titulo} ต่อ",
    "continuar_ouvindo_titulo": "ฟัง {titulo} ต่อ",
    "continuar_assistindo_titulo": "ดู {titulo} ต่อ",
    "lido": "อ่านแล้ว",
    "pausado": "หยุดชั่วคราว",
    "status": "สถานะ",
    "favorito": "รายการโปรด",
    "escolher_local": "เลือกตำแหน่ง",
    "epub_baixado_como": "ดาวน์โหลด EPUB เป็น {nome} แล้ว",
    "ouvir_a_partir_de": "ฟังตั้งแต่ {tempo}",
    "assistir_a_partir_de": "ดูตั้งแต่ {tempo}",
    "pagina_n_minuscula": "หน้า {n}",
    "selecione_trecho_para_criar": "เลือกข้อความระหว่างอ่านเพื่อสร้าง{oque}",
    "excluir_oque_pergunta": "ลบ{oque}หรือไม่",
    "excluir_oque": "ลบ{oque}",
    "excluir_item_pergunta": "ลบรายการนี้หรือไม่",
    "use_organizar_para_criar": "ใช้ “{botao}” กับหนังสือเพื่อสร้าง{oque}",
    "n_arquivos_processados": {
      "one": "ประมวลผล {n} ไฟล์",
      "other": "ประมวลผล {n} ไฟล์"
    },
    "voce_ja_tem_titulo_de_autor": "คุณมี “{titulo}” ของ {autor} ในคลังอยู่แล้ว แม้ไฟล์จะต่างกัน ต้องการนำเข้าอยู่ดีหรือไม่",
    "voce_ja_tem_titulo": "คุณมี “{titulo}” ในคลังอยู่แล้ว แม้ไฟล์จะต่างกัน ต้องการนำเข้าอยู่ดีหรือไม่",
    "marcadores_unidade": {
      "one": "ที่คั่น",
      "other": "ที่คั่น"
    },
    "ultimo_backup_em": "สำรองล่าสุดเมื่อ <strong>{data}</strong>",
    "guardar": "บันทึก",
    "lembretes": "การแจ้งเตือน",
    "juntar": "รวม",
    "recomendado": "แนะนำ",
    "substituir": "แทนที่",
    "n_capas_recuperadas": {
      "one": "กู้คืนปกได้ {n} รายการ",
      "other": "กู้คืนปกได้ {n} รายการ"
    },
    "nao_encontramos_arquivos_tipo": "ไม่พบไฟล์ {tipo} ในโฟลเดอร์นี้",
    "tentar_outra_pasta": "ลองโฟลเดอร์อื่น",
    "n_livros_encontrados": {
      "one": "พบหนังสือ {n} เล่ม",
      "other": "พบหนังสือ {n} เล่ม"
    },
    "n_de_total_selecionados": {
      "one": "เลือก {n} จาก {total}",
      "other": "เลือก {n} จาก {total}"
    },
    "importar": "นำเข้า",
    "importar_n": "นำเข้า {n}",
    "aceite_frase": "ฉันได้อ่านและยอมรับ{politica}และ{termos}ของ Veredas Reader แล้ว",
    "pdf_preservado": "PDF ต้นฉบับ<strong>จะไม่ถูกลบออกจากโฟลเดอร์ของคุณ</strong> จะนำเฉพาะสำเนา PDF นี้ออกจากคลังหลังจากบันทึก EPUB สำเร็จแล้วเท่านั้น",
    "gravar_epub_mesma_pasta": "หากต้องการบันทึก EPUB <strong>ในโฟลเดอร์เดียวกับ PDF</strong> เบราว์เซอร์ต้องได้รับอนุญาตให้เข้าถึงโฟลเดอร์นั้น",
    "epub_pronto_qualquer_pasta": "แปลง EPUB แล้ว ตอนนี้คุณสามารถเลือก<strong>โฟลเดอร์ใดก็ได้ในคอมพิวเตอร์</strong>เพื่อบันทึกไฟล์",
    "backup_explicacao": "ข้อมูลสำรองต้นฉบับเป็นไฟล์ ZIP หรือ TXT เมื่อได้รับบนอุปกรณ์อื่น ให้นำเข้าผ่าน <strong>กู้คืนสำรอง</strong> แล้ว Veredas จะรู้จักเนื้อหาและกู้คืนตามปกติ ไฟล์นี้เก็บความคืบหน้า ไฮไลต์ ข้อความอ้างอิง บันทึก ที่คั่น และการจัดชั้นของคุณ — <strong>ไม่รวมไฟล์หนังสือ</strong> และไม่รวมปก",
    "lembretes_desligados_frase": "การเตือน<strong>ปิดอยู่</strong> อย่าลืมสำรองเป็นระยะ ๆ",
    "backup_salvo_nos_downloads": "<strong>บันทึกไฟล์สำรองในอุปกรณ์นี้แล้ว</strong> ในโฟลเดอร์ดาวน์โหลดของคุณ ส่งได้เลย: เปิด WhatsApp อีเมล Drive หรือแอปใดก็ได้ แตะแนบแล้วเลือกไฟล์",
    "arquivo_pronto_tamanho": "ไฟล์พร้อมแล้ว — <strong>{tamanho}</strong>",
    "scan_intro_frase": "แอปสามารถค้นหาหนังสือ <strong>EPUB</strong> และ <strong>MOBI</strong> การ์ตูน <strong>CBZ</strong> และ <strong>CBR</strong> และหนังสือเสียง <strong>M4B</strong> ภายในโฟลเดอร์หนึ่งในอุปกรณ์ของคุณ รวมถึงโฟลเดอร์ย่อย",
    "scan_intro_auto_frase": "เพื่อจัดชั้นหนังสืออย่างรวดเร็ว แอปสามารถค้นหาหนังสือ <strong>EPUB</strong> และ <strong>MOBI</strong> การ์ตูน <strong>CBZ</strong> และ <strong>CBR</strong> และหนังสือเสียง <strong>M4B</strong> ภายในโฟลเดอร์หนึ่งในอุปกรณ์ของคุณ รวมถึงโฟลเดอร์ย่อย",
    "n_livros_aguardando": {
      "one": "หนังสือ <strong>{n} เล่ม</strong> ที่เก็บความคืบหน้าและเครื่องหมายไว้ กำลังรอการนำเข้าอีกครั้ง",
      "other": "หนังสือ <strong>{n} เล่ม</strong> ที่เก็บความคืบหน้าและเครื่องหมายไว้ กำลังรอการนำเข้าอีกครั้ง"
    },
    "fora_da_busca_titulo": "เราไม่นำเข้าไฟล์ PDF, TXT, DOCX (Word), MD, MP3 และ MP4 โดยอัตโนมัติ",
    "fora_da_busca_texto": "รูปแบบเหล่านี้ใช้กับเอกสารทุกประเภท ไม่ได้ใช้กับหนังสือเท่านั้น การไม่รวมไว้ช่วยให้ชั้นหนังสือเป็นระเบียบ <strong>คุณนำเข้าแต่ละไฟล์เองได้ด้วยปุ่ม +</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "คลังในเครื่องของคุณ",
    "biblioteca": "คลัง",
    "organizacao": "การจัดเรียง",
    "minhas_marcacoes": "เครื่องหมายของฉัน",
    "sistema": "ระบบ",
    "sua_biblioteca": "คลังของคุณ",
    "toque_em_um_livro_para_comecar_a_ler": "แตะหนังสือเพื่อเริ่มอ่าน",
    "agrupar": "จัดกลุ่ม",
    "sua_estante_nao_tem_copia_de_seguranca": "ชั้นของคุณไม่มีสำรอง",
    "se_este_aparelho_se_perder_o_progresso": "หากเกิดอะไรขึ้นกับอุปกรณ์นี้ ความคืบหน้าและเครื่องหมายอาจสูญหายได้",
    "agora_nao": "ไม่ใช่ตอนนี้",
    "nao_avisar_mais": "หยุดเตือน",
    "carregando": "กำลังโหลด...",
    "estante": "ชั้น",
    "lendo": "กำลังอ่าน",
    "favoritos": "รายการโปรด",
    "marcas": "เครื่องหมาย",
    "mais": "เพิ่มเติม",
    "neste_capitulo": "ในบทนี้",
    "velocidade": "ความเร็ว",
    "timer": "ตัวจับเวลา",
    "marcar": "ทำเครื่องหมาย",
    "marcadores": "ที่คั่น",
    "personalizar_leitura": "ปรับการอ่าน",
    "as_preferencias_ficam_salvas_para_as_p": "การตั้งค่าถูกเก็บไว้สำหรับการอ่านครั้งต่อไป",
    "tema": "ธีม",
    "claro": "สว่าง",
    "sepia": "ซีเปีย",
    "escuro": "มืด",
    "oceano": "มหาสมุทร",
    "tipografia": "แบบอักษร",
    "texto": "ข้อความ",
    "tamanho": "ขนาด",
    "espacamento": "ระยะบรรทัด",
    "margens": "ระยะขอบ",
    "cores_personalizadas_opcional": "สีที่กำหนดเอง (ไม่บังคับ)",
    "fundo": "พื้นหลัง",
    "fonte": "สีข้อความ",
    "brilho": "ความสว่าง",
    "orientacao": "การวางแนว",
    "auto": "อัตโนมัติ",
    "retrato": "แนวตั้ง",
    "paisagem": "แนวนอน",
    "modo_de_leitura": "โหมดการอ่าน",
    "automatico": "อัตโนมัติ",
    "horizontal": "แนวนอน",
    "vertical": "แนวตั้ง",
    "automatico_usa_rolagem_horizontal_para": "อัตโนมัติใช้การเปลี่ยนหน้าแนวนอนสำหรับ EPUB, MOBI, TXT และ MD และเลื่อนแนวตั้งสำหรับ PDF และ DOCX หากเปลี่ยนขณะอ่าน การเปลี่ยนแปลงจะถูกเก็บเฉพาะเล่มนั้น",
    "quadrinhos": "การ์ตูน",
    "como_a_pagina_aparece": "การปรับหน้าให้พอดีจอ",
    "pagina_inteira": "ทั้งหน้า",
    "largura_da_tela": "ความกว้างหน้าจอ",
    "sentido_da_leitura": "ทิศทางการอ่าน",
    "normal": "ปกติ →",
    "manga": "← มังงะ",
    "revista_aberta_na_horizontal": "มุมมองสองหน้าในแนวนอน",
    "com_o_aparelho_deitado_mostra_duas_pag": "เมื่อถือด้านข้าง จะแสดงสองหน้าติดกัน — ปกแยกอยู่ เหมือนการ์ตูนจริงที่เปิดออก",
    "normal_vira_da_esquerda_para_a_direita": "ปกติจะพลิกซ้ายไปขวา มังงะกลับทุกอย่าง: การปัด การแตะขอบ และลำดับของสองหน้าในมุมมองคู่",
    "gire_o_aparelho_para_a_horizontal_para": "หมุนอุปกรณ์ไปด้านข้างเพื่อดูสองหน้าพร้อมกัน",
    "dois_toques_ampliam_no_ponto_tocado_co": "แตะสองครั้งเพื่อซูมที่จุดที่แตะ เมื่อซูมแล้ว ลากเพื่อเลื่อนดูหน้า การบีบด้วยสองนิ้วก็ใช้ได้",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "ปุ่มเลื่อนที่ด้านบนของเครื่องอ่านสลับระหว่างทีละหน้าและการเลื่อนต่อเนื่อง (สไตล์เว็บตูน) ในการเลื่อนต่อเนื่องหน้าจะไหลเข้าหากัน และการซูมจะทำให้หน้ากว้างขึ้น: คุณเคลื่อนผ่านด้วยการเลื่อนด้านข้าง",
    "virada_de_pagina": "การเปลี่ยนหน้า",
    "folha_real": "กระดาษจริง",
    "deslizar": "เลื่อน",
    "sem_animacao": "ไม่มีการเคลื่อนไหว",
    "na_leitura_horizontal_arraste_a_pagina": "ในการอ่านแนวนอน ลากหน้าจากขอบเพื่อพับด้วยนิ้ว ปล่อยกลางทางเพื่อยกเลิกการเปลี่ยน",
    "ouvir_leitura": "ฟัง",
    "continue_de_onde_parou_no_seu_ritmo": "อ่านต่อจากที่ค้างไว้ ในจังหวะของคุณ",
    "livro": "หนังสือ",
    "pronto_para_comecar": "พร้อมเริ่ม",
    "voz": "เสียง",
    "escolha_uma_voz_disponivel_no_disposit": "เลือกเสียงที่มีในอุปกรณ์นี้",
    "voz_padrao_do_sistema": "เสียงเริ่มต้นของระบบ",
    "durante_a_reproducao": "ขณะเล่น",
    "a_leitura_avanca_pagina_a_pagina_os_co": "การอ่านเดินทีละหน้า ตัวควบคุมระบบจะปรากฏเมื่อเบราว์เซอร์รองรับ",
    "organizar_livro": "จัดหนังสือ",
    "estantes_colecoes_tags_e_status": "ชั้น คอลเลกชัน แท็ก และสถานะ",
    "cancelar": "ยกเลิก",
    "salvar": "บันทึก",
    "grifos_citacoes_notas_e_marcadores_des": "ไฮไลต์ ข้อความอ้างอิง บันทึก และที่คั่นของหนังสือเล่มนี้",
    "sumario": "สารบัญ",
    "toque_em_um_capitulo_para_ir_direto_ao": "แตะบทเพื่อไปตรงนั้น",
    "sua_anotacao": "บันทึกของคุณ",
    "edite_ou_adicione_comentarios_ao_seu_t": "แก้ไขหรือเพิ่มความคิดเห็นในข้อความของคุณ",
    "trecho": "ข้อความ",
    "sua_nota": "บันทึกของคุณ",
    "salvar_nota": "บันทึกโน้ต",
    "agrupar_biblioteca": "จัดกลุ่มคลัง",
    "escolha_como_os_livros_serao_organizad": "เลือกวิธีจัดหนังสือบนชั้น",
    "ao_arrastar_um_livro_para_outra_posica": "เมื่อลากหนังสือไปยังตำแหน่งอื่น ชั้นจะเปลี่ยนเป็นลำดับของฉันโดยอัตโนมัติ และรักษาลำดับที่คุณจัดไว้",
    "backup_e_restauracao": "สำรองและกู้คืน",
    "sua_estante_seu_progresso_e_suas_marca": "ชั้น ความคืบหน้า และเครื่องหมายของคุณในไฟล์เดียว",
    "escolha_uma_dimensao_para_explorar_sua": "เลือกวิธีสำรวจคลังของคุณ",
    "capitulos": "บท",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "เสียงไม่สูงหรือต่ำลง สิ่งนี้ใช้กับเล่มนี้และเล่มต่อไป",
    "ajuste_fino": "ปรับละเอียด",
    "timer_de_sono": "ตัวจับเวลาหลับ",
    "o_audio_diminui_de_volume_aos_poucos_e": "เสียงจะค่อย ๆ เบาลงและหยุดชั่วคราวโดยอัตโนมัติ",
    "pontos_que_voce_guardou_neste_audioliv": "จุดที่คุณบันทึกในหนังสือเสียงนี้",
    "ajustes_do_audio": "การตั้งค่าเสียง",
    "as_preferencias_ficam_salvas_para_todo": "การตั้งค่าเหล่านี้ถูกเก็บสำหรับหนังสือเสียงทุกเล่ม",
    "botao_de_voltar": "ปุ่มย้อน",
    "botao_de_avancar": "ปุ่มเดินหน้า",
    "recuar_ao_retomar": "ย้อนเมื่อกลับมาเล่น",
    "depois_de_uma_pausa_longa_volta_alguns": "หลังหยุดนาน จะย้อนกลับไม่กี่วินาทีเพื่อให้คุณกลับมาเข้าเรื่อง",
    "tocar_ao_abrir": "เล่นเมื่อเปิด",
    "ao_tocar_em_um_audiolivro_na_estante_a": "แตะหนังสือเสียงบนชั้นแล้วเริ่มเล่นทันที",
    "no_computador_espaco_toca_e_pausa_pula": "บนคอมพิวเตอร์: space เล่นและหยุด · ← → ข้าม · Shift + ← → เปลี่ยนบท · ↑ ↓ เสียง · B ที่คั่น · [ ] ความเร็ว",
    "converter_pdf_para_epub": "แปลง PDF เป็น EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "เตรียมหนังสือสำหรับการอ่านที่ลื่นไหลและปรับได้",
    "confirmacao": "ยืนยัน",
    "confirmar": "ยืนยัน",
    "processando": "กำลังทำงาน",
    "documento": "เอกสาร",
    "buscar_livros_no_dispositivo": "ค้นหาหนังสือในอุปกรณ์นี้",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "ค้นหาไฟล์ EPUB, MOBI, CBZ, CBR และ M4B ที่บันทึกไว้แล้วในอุปกรณ์",
    "juntar_em_um_unico_audiolivro": "รวมเป็นหนังสือเสียงเล่มเดียว?",
    "titulo": "ชื่อเรื่อง",
    "autor": "ผู้เขียน",
    "importar_separados": "นำเข้าแยกกัน",
    "bem_vindo_ao_veredas_reader": "ยินดีต้อนรับสู่ Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "คลังการอ่านของคุณ ทั้งหมดบนอุปกรณ์ของคุณ",
    "buscar": "ค้นหา",
    "importar_livro": "นำเข้าหนังสือ",
    "buscar_titulo_autor_tag": "ค้นหาชื่อเรื่อง ผู้เขียน แท็ก...",
    "fechar_busca": "ปิดการค้นหา",
    "navegacao_da_biblioteca": "การนำทางคลัง",
    "fechar_menu": "ปิดเมนู",
    "agrupar_livros": "จัดกลุ่มหนังสือ",
    "voltar": "กลับ",
    "marcar_pagina": "ทำเครื่องหมายหน้า",
    "personalizar": "ปรับแต่ง",
    "navegacao_principal": "การนำทางหลัก",
    "acoes_do_trecho": "การดำเนินการกับข้อความ",
    "amarelo": "เหลือง",
    "verde": "เขียว",
    "rosa": "ชมพู",
    "azul": "น้ำเงิน",
    "player_de_audiolivro": "เครื่องเล่นหนังสือเสียง",
    "minimizar_player": "ย่อเครื่องเล่น",
    "minimizar": "ย่อ",
    "video_em_reproducao": "กำลังเล่นวิดีโอ",
    "abrir_a_lista_de_capitulos": "เปิดรายการบท",
    "posicao_no_audio": "ตำแหน่งในเสียง",
    "alternar_entre_o_progresso_do_capitulo": "สลับระหว่างความคืบหน้าของบทและของทั้งเล่ม",
    "capitulo_anterior": "บทก่อนหน้า",
    "voltar_15_segundos": "ย้อน 15 วินาที",
    "reproduzir": "เล่น",
    "avancar_30_segundos": "ไปข้างหน้า 30 วินาที",
    "proximo_capitulo": "บทถัดไป",
    "velocidade_de_reproducao": "ความเร็วเล่น",
    "marcar_este_ponto": "ทำเครื่องหมายจุดนี้",
    "ver_marcadores": "ดูที่คั่น",
    "silenciar": "ปิดเสียง",
    "volume": "ระดับเสียง",
    "audiolivro_em_reproducao": "กำลังเล่นหนังสือเสียง",
    "abrir_o_player": "เปิดเครื่องเล่น",
    "fechar_o_player": "ปิดเครื่องเล่น",
    "fechar": "ปิด",
    "trecho_anterior": "ข้อความก่อนหน้า",
    "iniciar_leitura": "เริ่มอ่านออกเสียง",
    "proximo_trecho": "ข้อความถัดไป",
    "escreva_seu_comentario_interpretacao_o": "เขียนความคิดเห็น การตีความ หรือการเตือนของคุณ...",
    "cancelar_importacao": "ยกเลิกการนำเข้า",
    "nome_do_audiolivro": "ชื่อหนังสือเสียง",
    "nome_do_autor": "ชื่อผู้เขียน",
    "idioma": "ภาษา",
    "idioma_do_aplicativo": "ภาษาของแอป",
    "o_aplicativo_segue_o_idioma_do_apare": "แอปตามภาษาของอุปกรณ์ของคุณ หากภาษาของคุณยังไม่มีที่นี่ จะเปิดเป็นภาษาอังกฤษ",
    "seguir_o_aparelho": "ตามอุปกรณ์",
    "fazer_backup": "สำรองเดี๋ยวนี้",
    "todos": "ทั้งหมด",
    "lidos": "อ่านแล้ว",
    "pausados": "หยุดชั่วคราว",
    "autores": "ผู้เขียน",
    "tags": "แท็ก",
    "grifar": "ไฮไลต์",
    "anotar": "จดโน้ต",
    "enviar": "ส่ง",
    "restaurar_padroes": "คืนค่าเริ่มต้น",
    "voltar_para_1": "กลับไป 1×",
    "marcar_agora": "ทำเครื่องหมายตอนนี้",
    "escolher_pasta": "เลือกโฟลเดอร์",
    "juntar_em_um_audiolivro": "รวมเป็นหนังสือเสียงเล่มเดียว",
    "sobre": "เกี่ยวกับ",
    "licencas_de_codigo_aberto": "สัญญาอนุญาตโอเพนซอร์ส",
    "configuracoes": "การตั้งค่า",
    "temas_e_idioma": "ธีมและภาษา"
  },
  "aviso": {
    "idioma_trocado": "เปลี่ยนภาษาแล้ว"
  },
  "guia": {
      "pular": "ข้าม",
      "voltar": "ย้อนกลับ",
      "proximo": "ถัดไป",
      "concluir": "เข้าใจแล้ว",
      "secao": "เคล็ดลับการใช้งาน",
      "rever_titulo": "ดูเคล็ดลับอีกครั้ง",
      "rever_dica": "เคล็ดลับจะขึ้นครั้งเดียว ตรงจุดที่แต่ละอย่างเกิดขึ้น กดตรงนี้เพื่อให้ทั้งหมดกลับมาตั้งแต่ต้น",
      "rever_botao": "ดูใหม่",
      "voltaram": "เคล็ดลับกลับมาแล้ว",
      "primeiro_t": "เริ่มจากตรงนี้",
      "primeiro_p": "แตะ + เพื่อนำหนังสือจากเครื่องเข้ามา รองรับ EPUB, PDF, MOBI, DOCX, TXT, การ์ตูน และหนังสือเสียง",
      "card_t": "แตะเพื่ออ่าน กดค้างเพื่อย้าย",
      "card_p": "แตะหนึ่งครั้งเพื่อเปิดหนังสือ กดค้างแล้วลากเพื่อวางไว้ตรงไหนก็ได้บนชั้น",
      "agrupar_t": "จัดระเบียบตามใจคุณ",
      "agrupar_p": "จัดกลุ่มชั้นหนังสือตามผู้เขียน ชุด คอลเลกชัน หรือแท็ก และกลับไปเป็นรายการธรรมดาได้ทุกเมื่อ",
      "mais_t": "ที่เหลืออยู่ตรงนี้",
      "mais_p": "การค้นหาในเครื่อง การสำรองข้อมูล การตั้งค่า และนโยบายต่าง ๆ อยู่ในเมนูนี้",
      "pdf_epub_t": "PDF นี้คุ้มที่จะแปลง",
      "pdf_epub_p": "เมื่อเป็น EPUB ข้อความจะจัดให้พอดีกับหน้าจอ เปลี่ยนขนาดตัวอักษรได้ และการอ่านออกเสียงจะดีขึ้นมาก แตะตรงนี้เพื่อแปลง ไฟล์ PDF เดิมยังอยู่บนชั้น",
      "virar_t": "ปัดนิ้วเพื่อเปลี่ยนหน้า",
      "virar_p": "ลากไปด้านข้าง หรือแตะใกล้ขอบขวาและขอบซ้าย แตะตรงกลางเพื่อแสดงและซ่อนปุ่มควบคุม",
      "rolar_t": "เลื่อนเพื่ออ่าน",
      "rolar_p": "หนังสือเล่มนี้เปิดแบบเลื่อนต่อเนื่อง ปัดขึ้นเพื่ออ่านต่อ แตะตรงกลางเพื่อแสดงและซ่อนปุ่มควบคุม",
      "voltar_t": "กลับไปที่ชั้นหนังสือ",
      "voltar_p": "ปุ่มนี้ปิดหนังสือและพาคุณกลับไป ตำแหน่งที่อ่านค้างไว้จะถูกบันทึกเอง",
      "ouvir_t": "ฟังแทนการอ่าน",
      "ouvir_p": "แอปจะอ่านหนังสือออกเสียงให้ ใช้เสียงของเครื่องก็ได้ หรือดาวน์โหลดเสียงธรรมชาติที่ฟังเหมือนคนมากกว่าและใช้ได้โดยไม่ต้องต่อเน็ต",
      "sentido_t": "ทีละหน้า หรือเลื่อนต่อเนื่อง",
      "sentido_p": "เปลี่ยนทิศทางการอ่านได้ทุกเมื่อ ตัวเลือกนี้ใช้กับหนังสือเล่มนี้เท่านั้น",
      "personalizar_t": "ปรับให้เป็นของคุณ",
      "personalizar_p": "ธีม แบบอักษร ขนาดตัวอักษร ระยะขอบ และความสว่าง อยู่ตรงนี้",
      "pdf_sentido_t": "PDF เปิดแบบเลื่อน",
      "pdf_sentido_p": "หน้าของ PDF มีขนาดตายตัว จึงเริ่มด้วยการเลื่อนต่อเนื่อง ตรงนี้เปลี่ยนเป็นทีละหน้าได้",
      "pdf_volte_t": "ถ้าตัวอักษรดูเล็ก",
      "pdf_volte_p": "ใช้สองนิ้วถ่างเพื่อขยาย และอย่าลืมว่าถ้าแปลงเป็น EPUB ข้อความจะจัดให้พอดีกับหน้าจอเอง",
      "hq_zoom_t": "ขยายด้วยสองนิ้ว",
      "hq_zoom_p": "ถ่างนิ้วเพื่อขยายช่องภาพ และลากเพื่อเลื่อนดูทั้งหน้า แตะสองครั้งเพื่อกลับสู่ขนาดปกติ",
      "hq_ajustes_t": "การตั้งค่าการ์ตูน",
      "hq_ajustes_p": "เลือกว่าหน้าจะพอดีกับหน้าจออย่างไร ทิศทางการอ่าน และจะให้แสดงสองหน้าคู่กันเมื่อหมุนเครื่องหรือไม่",
      "tema_t": "เลือกธีม",
      "tema_p": "สว่าง ซีเปีย หรือมืด ซีเปียสบายตากว่าเมื่ออ่านนาน ๆ และธีมมืดรบกวนสายตาน้อยกว่าในตอนกลางคืน",
      "fonte_t": "ขนาดตัวอักษร",
      "fonte_p": "ลากเพื่อเพิ่มหรือลดขนาด ถัดลงไปคือความสูงบรรทัดและระยะขอบ",
      "modo_t": "ทิศทางการอ่าน",
      "modo_p": "อัตโนมัติจะใช้การเลื่อนแนวนอนกับ EPUB และแนวตั้งกับ PDF ถ้าเปลี่ยนขณะเปิดหนังสืออยู่ จะมีผลกับเล่มนั้นเท่านั้น",
      "audio_cap_t": "ข้ามระหว่างบท",
      "audio_cap_p": "แตะเพื่อดูรายการบทและไปยังบทที่ต้องการได้ทันที",
      "audio_ajustes_t": "ความเร็วและตั้งเวลาปิด",
      "audio_ajustes_p": "ตรงนี้เร่งหรือลดความเร็วการอ่าน และตั้งให้เสียงหยุดเองหลังผ่านไปสักพัก",
      "audio_min_t": "เลือกดูต่อได้",
      "audio_min_p": "ย่อเครื่องเล่นลงแล้วฟังต่อขณะใช้ชั้นหนังสือ แตะแถบด้านล่างเพื่อกลับมา"
  },
  "vn": {
    "quem_le": "ผู้อ่าน",
    "natural": "ธรรมชาติ",
    "do_sistema": "ระบบ",
    "nota_sistema": "ใช้เสียงที่ติดตั้งไว้ในอุปกรณ์ หากต้องการเสียงอ่านที่เหมือนคนมากขึ้น ให้เลือก ธรรมชาติ",
    "nota_sistema_com_natural": "เสียงธรรมชาติยังดาวน์โหลดไว้อยู่ กลับไปใช้ ธรรมชาติ ได้ทุกเมื่อ",
    "voz_do_sistema": "เสียงของระบบ",
    "lendo_com_a_voz_do_sistema": "กำลังอ่านด้วยเสียงของระบบ",
    "voz_natural": "เสียงธรรมชาติ",
    "gerada_no_aparelho": "เสียงที่เหมือนคนมากกว่าเดิมมาก สร้างขึ้นบนอุปกรณ์ของคุณเอง",
    "progresso_download": "ความคืบหน้าการดาวน์โหลด",
    "x_de_y": "{x} จาก {y}",
    "aviso_arquivo": "เสียงธรรมชาติต้องเปิด Veredas จากที่อยู่ของแอป ไม่ใช่เปิดเป็นไฟล์ในคอมพิวเตอร์ ระหว่างนี้การอ่านจะใช้เสียงของระบบ",
    "aviso_navegador": "เบราว์เซอร์นี้ไม่มีความสามารถที่เสียงธรรมชาติต้องใช้ การอ่านจะใช้เสียงของระบบต่อไป",
    "verificando": "กำลังตรวจสอบเสียงธรรมชาติ…",
    "fato_download": "ดาวน์โหลดครั้งเดียว {tamanho} หลังจากนั้นใช้งานได้โดยไม่ต้องมีอินเทอร์เน็ต",
    "fato_wifi": "แนะนำให้ใช้ Wi-Fi หยุดไว้แล้วดาวน์โหลดต่อภายหลังได้",
    "fato_privacidade": "ข้อความในหนังสือไม่ออกจากอุปกรณ์ของคุณเลย",
    "fato_idiomas": "พูดได้ 31 ภาษา รวมถึงภาษาอังกฤษ โปรตุเกส และสเปน แต่ยังไม่รองรับภาษาไทย ภาษาที่ไม่รองรับจะใช้เสียงของระบบ",
    "baixar_voz_natural": "ดาวน์โหลดเสียงธรรมชาติ ({tamanho})",
    "licenca_curta": "โมเดล Supertonic 3 จาก Supertone ภายใต้สัญญาอนุญาต OpenRAIL-M ดูรายละเอียดที่ เกี่ยวกับ > สัญญาอนุญาตโอเพนซอร์ส",
    "pode_continuar_usando": "คุณอ่านต่อได้ระหว่างดาวน์โหลด หากการเชื่อมต่อหลุด การดาวน์โหลดจะทำต่อจากจุดที่ค้างไว้",
    "pausar_download": "หยุดดาวน์โหลดชั่วคราว",
    "erro_espaco": "พื้นที่ในอุปกรณ์ไม่พอสำหรับดาวน์โหลดให้เสร็จ เพิ่มพื้นที่ว่างแล้วลองอีกครั้ง",
    "erro_offline": "ขณะนี้ไม่มีอินเทอร์เน็ต ส่วนที่ดาวน์โหลดแล้วยังเก็บไว้อยู่",
    "erro_rede": "การเชื่อมต่อหลุดระหว่างดาวน์โหลด ส่วนที่ดาวน์โหลดแล้วยังเก็บไว้อยู่",
    "download_pausado": "หยุดดาวน์โหลดชั่วคราวแล้ว ส่วนที่ดาวน์โหลดแล้วยังเก็บไว้อยู่",
    "continuar_download": "ดาวน์โหลดต่อ",
    "descartar": "ยกเลิก",
    "voz_feminina": "ผู้หญิง",
    "voz_feminina_desc": "นุ่มนวลและสงบ",
    "voz_masculina": "ผู้ชาย",
    "voz_masculina_desc": "อบอุ่นและเยือกเย็น",
    "parar_amostra": "หยุดเสียงตัวอย่าง",
    "ouvir_amostra_de": "ฟังเสียงตัวอย่าง: {voz}",
    "escolha_a_voz": "เลือกเสียง",
    "qualidade": "คุณภาพ",
    "q_auto": "อัตโนมัติ",
    "q_rapida": "เร็ว",
    "q_maxima": "ดีที่สุด",
    "q_auto_desc": "ปรับตามประสิทธิภาพของอุปกรณ์เอง เพื่อให้การอ่านลื่นไหลไม่สะดุด",
    "q_rapida_desc": "สร้างเสียงได้เร็วขึ้น เหมาะกับอุปกรณ์สเปกไม่สูง",
    "q_maxima_desc": "เสียงประณีตที่สุด ในอุปกรณ์สเปกไม่สูงอาจมีช่วงหยุดระหว่างประโยค",
    "ocupa": "ใช้พื้นที่ {tamanho} ในอุปกรณ์นี้",
    "remover": "ลบ",
    "baixar_pelos_dados": "ดาวน์โหลดผ่านเน็ตมือถือไหม",
    "baixar_pelos_dados_msg": "ดูเหมือนอุปกรณ์ไม่ได้เชื่อมต่อ Wi-Fi ไฟล์ดาวน์โหลดมีขนาด {tamanho} และอาจใช้ปริมาณเน็ตในแพ็กเกจของคุณ",
    "baixar_agora": "ดาวน์โหลดเลย",
    "pronta": "เสียงธรรมชาติพร้อมใช้งานแล้ว",
    "download_interrompido": "การดาวน์โหลดหยุดไป แตะ ดาวน์โหลดต่อ ได้ทุกเมื่อ",
    "remover_titulo": "ลบเสียงธรรมชาติไหม",
    "descartar_titulo": "ยกเลิกการดาวน์โหลดไหม",
    "remover_msg": "จะได้พื้นที่คืน {tamanho} การอ่านจะกลับไปใช้เสียงของระบบ และดาวน์โหลดใหม่ได้ทุกเมื่อ",
    "descartar_msg": "ส่วนที่ดาวน์โหลดแล้วจะถูกลบ",
    "removida": "ลบเสียงธรรมชาติออกจากอุปกรณ์นี้แล้ว",
    "amostra_falhou": "เล่นเสียงตัวอย่างในอุปกรณ์นี้ไม่ได้",
    "amostra": "สวัสดี! หนังสือของคุณจะมีเสียงแบบนี้เมื่อใช้เสียงธรรมชาติ",
    "pode_demorar_um_minuto": "อาจใช้เวลาสักครู่",
    "gerando_voz": "กำลังเตรียมเสียง…",
    "automatico_idioma": "อัตโนมัติ ({idioma})",
    "automatico": "อัตโนมัติ",
    "so_voz_do_sistema": "เสียงของระบบ",
    "aviso_idioma": "ภาษาของข้อความ: {idioma} เสียงธรรมชาติยังพูดภาษานี้ไม่ได้ หนังสือจึงจะอ่านด้วยเสียงของระบบ",
    "aviso_idioma_desconhecido": "ไม่สามารถระบุภาษาของข้อความนี้ได้ เลือกภาษาด้านล่างเพื่อใช้เสียงธรรมชาติ",
    "aviso_falha": "เสียงธรรมชาติทำงานในอุปกรณ์นี้ไม่ได้ในขณะนี้ การอ่านจะใช้เสียงของระบบต่อไป",
    "nao_carregou_usando_sistema": "เสียงธรรมชาติโหลดในอุปกรณ์นี้ไม่สำเร็จ กำลังอ่านด้วยเสียงของระบบ",
    "parou_usando_sistema": "เสียงธรรมชาติหยุดทำงาน กำลังอ่านต่อด้วยเสียงของระบบ",
    "aparelho_lento": "อุปกรณ์นี้สร้างเสียงได้ช้า เลือกคุณภาพ เร็ว เพื่อไม่ให้มีช่วงหยุด",
    "idioma_do_texto": "ภาษาของข้อความ",
    "idioma_do_texto_dica": "ระบุจากตัวข้อความเอง เปลี่ยนได้หากการออกเสียงไม่ถูกต้อง",
    "leitura_em_voz_alta": "อ่านออกเสียง",
    "lento_usando_sistema": "เสียงธรรมชาติช้าเกินไปบนอุปกรณ์นี้ จะอ่านต่อด้วยเสียงของระบบ",
    "aviso_lento": "อุปกรณ์นี้สร้างเสียงธรรมชาติได้ไม่ทันความเร็วในการอ่าน จึงใช้เสียงของระบบไปก่อน",
    "sem_memoria_usando_sistema": "หน่วยความจำของอุปกรณ์นี้ไม่พอสำหรับเสียงธรรมชาติ จะอ่านด้วยเสียงของระบบ",
    "aviso_falha_memoria": "อุปกรณ์นี้มีหน่วยความจำไม่พอสำหรับเสียงธรรมชาติ การปิดแอปอื่นแล้วลองใหม่มักช่วยได้ ระหว่างนี้จะใช้เสียงของระบบ",
    "copiar_detalhe": "คัดลอกรายละเอียด",
    "copiado": "คัดลอกรายละเอียดแล้ว",
    "falhou_titulo": "เสียงธรรมชาติโหลดไม่สำเร็จบนอุปกรณ์นี้",
    "falhou_texto": "อุปกรณ์เตรียมเสียงธรรมชาติไม่สำเร็จ จะอ่านต่อด้วยเสียงของระบบ หากต้องการช่วยแก้ปัญหา ให้คัดลอกรายละเอียดด้านล่างแล้วส่งให้ฝ่ายสนับสนุน",
    "falhou_memoria_texto": "หน่วยความจำไม่พอสำหรับเสียงธรรมชาติบนอุปกรณ์นี้ การปิดแอปอื่นแล้วลองใหม่มักช่วยได้",
    "tentar_de_novo": "ลองอีกครั้ง",
    "tentando": "กำลังโหลด…",
    "sondando": "กำลังทดสอบหน่วยความจำของเครื่องนี้…",
    "sonda_explica": "การทดสอบจะจองหน่วยความจำเท่าที่เสียงธรรมชาติต้องใช้ไว้ไม่กี่วินาที แล้วคืนให้ทันที คุณจึงรู้ผลตอนนี้ ไม่ใช่หลังดาวน์โหลด",
    "so_aparelhos_compativeis": "ใช้ได้เฉพาะกับอุปกรณ์ที่รองรับ ไม่รับประกันว่าจะทำงานได้กับโทรศัพท์และแท็บเล็ตทุกรุ่น",
    "aviso_aparelho_justo": "อุปกรณ์นี้มีหน่วยความจำน้อยสำหรับเสียงธรรมชาติ อาจโหลดไม่สำเร็จ หากเป็นเช่นนั้นก็ลบออกเพื่อคืนพื้นที่ได้",
    "preparando_demora": "กำลังเตรียมเสียง อาจใช้เวลาสองสามนาที",
    "incompativel_titulo": "เสียงธรรมชาติใช้งานไม่ได้บนอุปกรณ์นี้",
    "incompativel_memoria": "หน่วยความจำไม่พอสำหรับเตรียมเสียงนี้ การอ่านจะใช้เสียงของระบบ และตัวเลือกอยู่ด้านล่าง หากต้องการ ให้ปิดแอปอื่นแล้วแตะ “ทดสอบอีกครั้ง”",
    "incompativel_lento": "เสียงนี้ช้าเกินกว่าจะตามการอ่านทัน การอ่านจะใช้เสียงของระบบ และตัวเลือกอยู่ด้านล่าง",
    "incompativel_queda": "แอปปิดตัวลงระหว่างโหลด การอ่านจะใช้เสียงของระบบ และตัวเลือกอยู่ด้านล่าง",
    "incompativel_falha": "โหลดไม่สำเร็จบนอุปกรณ์นี้ การอ่านจะใช้เสียงของระบบ และตัวเลือกอยู่ด้านล่าง",
    "testar_de_novo": "ทดสอบอีกครั้ง",
    "remover_e_liberar": "ลบเพื่อคืนพื้นที่ {tamanho}",
    "tela_durante_a_leitura": "หน้าจอขณะอ่าน",
    "manter_tela_ligada": "เปิดหน้าจอค้างไว้",
    "manter_tela_ligada_dica": "ขณะที่เปิดหนังสืออยู่ หน้าจอจะไม่ดับเอง เมื่อปิดหนังสือทุกอย่างจะกลับเป็นปกติ"
  }
});