/* ============================================================
   CHINÊS TRADICIONAL (zh-TW)
   ============================================================ */
Idiomas.registrar('zh-TW', {
  "ui": {
    "sua_biblioteca_local": "您的本機書庫",
    "biblioteca": "書庫",
    "organizacao": "整理",
    "minhas_marcacoes": "我的標記",
    "sistema": "系統",
    "sua_biblioteca": "您的書庫",
    "toque_em_um_livro_para_comecar_a_ler": "輕觸一本書開始閱讀。",
    "agrupar": "分組",
    "sua_estante_nao_tem_copia_de_seguranca": "您的書架沒有備份",
    "se_este_aparelho_se_perder_o_progresso": "如果這台裝置發生問題，您的進度和標記可能會遺失。",
    "agora_nao": "稍後再說",
    "nao_avisar_mais": "不再提醒",
    "carregando": "載入中…",
    "estante": "書架",
    "lendo": "閱讀中",
    "favoritos": "我的最愛",
    "marcas": "標記",
    "mais": "更多",
    "neste_capitulo": "本章",
    "velocidade": "速度",
    "timer": "計時器",
    "marcar": "標記",
    "marcadores": "書籤",
    "personalizar_leitura": "閱讀偏好設定",
    "as_preferencias_ficam_salvas_para_as_p": "偏好設定會保留到之後的閱讀。",
    "tema": "主題",
    "claro": "淺色",
    "sepia": "褐色",
    "escuro": "深色",
    "oceano": "海洋",
    "tipografia": "字型",
    "texto": "文字",
    "tamanho": "大小",
    "espacamento": "行距",
    "margens": "邊界",
    "cores_personalizadas_opcional": "自訂顏色（選填）",
    "fundo": "背景",
    "fonte": "文字顏色",
    "brilho": "亮度",
    "orientacao": "方向",
    "auto": "自動",
    "retrato": "直向",
    "paisagem": "橫向",
    "modo_de_leitura": "閱讀模式",
    "automatico": "自動",
    "horizontal": "水平",
    "vertical": "垂直",
    "automatico_usa_rolagem_horizontal_para": "自動模式對 EPUB、MOBI、TXT 和 MD 使用水平翻頁，對 PDF 和 DOCX 使用垂直捲動。閱讀中變更的話，設定只會保留在那一本書。",
    "quadrinhos": "漫畫",
    "como_a_pagina_aparece": "頁面顯示方式",
    "pagina_inteira": "整頁",
    "largura_da_tela": "螢幕寬度",
    "sentido_da_leitura": "閱讀方向",
    "normal": "正常 →",
    "manga": "← 由右至左",
    "revista_aberta_na_horizontal": "橫向雙頁顯示",
    "com_o_aparelho_deitado_mostra_duas_pag": "裝置橫放時會並排顯示兩頁——封面單獨一頁，就像真正的雜誌。",
    "normal_vira_da_esquerda_para_a_direita": "正常模式由左往右翻。漫畫模式全部相反：滑動方向、邊緣輕觸，還有雙頁顯示時的頁面順序。",
    "gire_o_aparelho_para_a_horizontal_para": "將裝置轉為橫向即可並排顯示兩頁。",
    "dois_toques_ampliam_no_ponto_tocado_co": "連點兩下可在輕觸處放大；放大後拖曳即可瀏覽頁面。雙指捏合也可以。",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "閱讀器上方的捲動按鈕可在逐頁與連續捲動（網路漫畫風格）之間切換。連續捲動時頁面會彼此銜接，放大則會加寬頁面：您可以左右捲動瀏覽。",
    "virada_de_pagina": "翻頁",
    "folha_real": "真實紙張",
    "deslizar": "滑動",
    "sem_animacao": "無動畫",
    "na_leitura_horizontal_arraste_a_pagina": "在水平閱讀中，從邊緣拖曳頁面即可用手指折頁。中途放開即取消翻頁。",
    "ouvir_leitura": "聆聽朗讀",
    "continue_de_onde_parou_no_seu_ritmo": "從中斷處繼續，依您的步調。",
    "livro": "書",
    "pronto_para_comecar": "準備開始",
    "voz": "語音",
    "escolha_uma_voz_disponivel_no_disposit": "選擇此裝置上可用的語音",
    "voz_padrao_do_sistema": "系統預設語音",
    "durante_a_reproducao": "播放期間",
    "a_leitura_avanca_pagina_a_pagina_os_co": "朗讀會逐頁進行。瀏覽器支援時會顯示系統控制項。",
    "organizar_livro": "整理書籍",
    "estantes_colecoes_tags_e_status": "書架、收藏、標籤與狀態。",
    "cancelar": "取消",
    "salvar": "儲存",
    "grifos_citacoes_notas_e_marcadores_des": "這本書的螢光標記、引用、註記與書籤。",
    "sumario": "目錄",
    "toque_em_um_capitulo_para_ir_direto_ao": "輕觸章節即可直接前往。",
    "sua_anotacao": "您的註記",
    "edite_ou_adicione_comentarios_ao_seu_t": "編輯或新增您對這段文字的評論。",
    "trecho": "段落",
    "sua_nota": "您的註記",
    "salvar_nota": "儲存註記",
    "agrupar_biblioteca": "書庫分組",
    "escolha_como_os_livros_serao_organizad": "選擇書架上書籍的排列方式。",
    "ao_arrastar_um_livro_para_outra_posica": "將書拖曳到其他位置時，書架會自動切換為「我的排序」，並保留您排好的順序。",
    "backup_e_restauracao": "備份與還原",
    "sua_estante_seu_progresso_e_suas_marca": "您的書架、進度和標記，全部收在一個檔案裡。",
    "escolha_uma_dimensao_para_explorar_sua": "選擇一種方式來探索您的書庫。",
    "capitulos": "章節",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "語音不會變得低沉或尖銳。此設定適用於這本書及之後的書。",
    "ajuste_fino": "微調",
    "timer_de_sono": "睡眠計時器",
    "o_audio_diminui_de_volume_aos_poucos_e": "音訊會逐漸降低音量，然後自動暫停。",
    "pontos_que_voce_guardou_neste_audioliv": "您在這本有聲書中保存的位置。",
    "ajustes_do_audio": "音訊設定",
    "as_preferencias_ficam_salvas_para_todo": "偏好設定會保留到所有有聲書。",
    "botao_de_voltar": "倒轉按鈕",
    "botao_de_avancar": "快轉按鈕",
    "recuar_ao_retomar": "繼續時倒轉",
    "depois_de_uma_pausa_longa_volta_alguns": "長時間暫停後會倒轉幾秒，讓您重新接上故事。",
    "tocar_ao_abrir": "開啟時播放",
    "ao_tocar_em_um_audiolivro_na_estante_a": "在書架上輕觸有聲書時會立即開始播放。",
    "no_computador_espaco_toca_e_pausa_pula": "在電腦上：空白鍵播放與暫停 · ← → 跳轉 · Shift + ← → 切換章節 · ↑ ↓ 音量 · B 標記 · [ ] 速度。",
    "converter_pdf_para_epub": "將 PDF 轉換為 EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "讓這本書有流暢且可調整的閱讀體驗。",
    "confirmacao": "確認",
    "confirmar": "確認",
    "processando": "處理中",
    "documento": "文件",
    "buscar_livros_no_dispositivo": "在裝置上尋找書籍",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "尋找已儲存在裝置上的 EPUB、MOBI、CBZ、CBR 和 M4B 檔案。",
    "juntar_em_um_unico_audiolivro": "合併成一本有聲書？",
    "titulo": "標題",
    "autor": "作者",
    "importar_separados": "分開匯入",
    "bem_vindo_ao_veredas_reader": "歡迎使用 Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "您的閱讀書庫，完全在您的裝置上。",
    "buscar": "搜尋",
    "importar_livro": "匯入書籍",
    "buscar_titulo_autor_tag": "搜尋標題、作者、標籤…",
    "fechar_busca": "關閉搜尋",
    "navegacao_da_biblioteca": "書庫導覽",
    "fechar_menu": "關閉選單",
    "agrupar_livros": "書籍分組",
    "voltar": "返回",
    "marcar_pagina": "標記頁面",
    "personalizar": "個人化",
    "navegacao_principal": "主導覽",
    "acoes_do_trecho": "段落操作",
    "amarelo": "黃色",
    "verde": "綠色",
    "rosa": "粉紅色",
    "azul": "藍色",
    "player_de_audiolivro": "有聲書播放器",
    "minimizar_player": "最小化播放器",
    "minimizar": "最小化",
    "video_em_reproducao": "影片播放中",
    "abrir_a_lista_de_capitulos": "開啟章節清單",
    "posicao_no_audio": "音訊位置",
    "alternar_entre_o_progresso_do_capitulo": "在章節進度與全書進度之間切換",
    "capitulo_anterior": "上一章",
    "voltar_15_segundos": "倒轉 15 秒",
    "reproduzir": "播放",
    "avancar_30_segundos": "快轉 30 秒",
    "proximo_capitulo": "下一章",
    "velocidade_de_reproducao": "播放速度",
    "marcar_este_ponto": "標記此處",
    "ver_marcadores": "查看書籤",
    "silenciar": "靜音",
    "volume": "音量",
    "audiolivro_em_reproducao": "有聲書播放中",
    "abrir_o_player": "開啟播放器",
    "fechar_o_player": "關閉播放器",
    "fechar": "關閉",
    "trecho_anterior": "上一段",
    "iniciar_leitura": "開始朗讀",
    "proximo_trecho": "下一段",
    "escreva_seu_comentario_interpretacao_o": "寫下您的評論、解讀或提醒…",
    "cancelar_importacao": "取消匯入",
    "nome_do_audiolivro": "有聲書名稱",
    "nome_do_autor": "作者名稱",
    "idioma": "語言",
    "idioma_do_aplicativo": "應用程式語言",
    "o_aplicativo_segue_o_idioma_do_apare": "應用程式會跟隨裝置的語言。若您的語言尚未支援，會以英文開啟。",
    "seguir_o_aparelho": "跟隨裝置",
    "fazer_backup": "立即備份",
    "todos": "全部",
    "lidos": "已讀",
    "pausados": "已暫停",
    "autores": "作者",
    "tags": "標籤",
    "grifar": "螢光標記",
    "anotar": "註記",
    "enviar": "傳送",
    "restaurar_padroes": "還原預設值",
    "voltar_para_1": "返回 1×",
    "marcar_agora": "立即標記",
    "escolher_pasta": "選擇資料夾",
    "juntar_em_um_audiolivro": "合併成一本有聲書",
    "sobre": "關於",
    "licencas_de_codigo_aberto": "開源授權",
    "configuracoes": "設定",
    "temas_e_idioma": "主題與語言"
  },
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "已刪除書籤。",
    "excluir_marcador": "刪除書籤",
    "o_marcador_sera_removido_permanentemen": "書籤將被永久移除。",
    "excluir_marcador_2": "刪除書籤？",
    "pagina_salva": "已儲存頁面",
    "anotacoes": "註記",
    "citacoes": "引用",
    "item_excluido": "已刪除項目。",
    "este_registro_sera_removido_permanente": "此項目將從書庫中永久移除。",
    "configuracoes_padrao_restauradas": "已還原預設設定。",
    "leitura_da_esquerda_para_a_direita": "由左至右閱讀。",
    "leitura_da_direita_para_a_esquerda_man": "由右至左閱讀（漫畫）。",
    "a_pagina_inteira_passa_a_caber_na_tela": "整頁現在可以完整顯示在螢幕上。",
    "a_pagina_passa_a_ocupar_toda_a_largura": "頁面現在佔滿整個螢幕寬度。",
    "virada_sem_animacao_ativada": "已開啟無動畫翻頁。",
    "virada_deslizante_ativada": "已開啟滑動翻頁。",
    "virada_em_folha_real_ativada": "已開啟真實紙張翻頁。",
    "padrao_automatico_cada_formato_abre_no": "自動模式：每種格式以最適合的方式開啟。",
    "mudando_durante_a_leitura_o_ajuste_fic": "閱讀中變更的話，設定只會保留在那一本書。",
    "automatico_usa_rolagem_horizontal_para": "自動模式對 EPUB、MOBI、TXT、MD 和漫畫使用水平翻頁，對 PDF 和 DOCX 使用垂直捲動。",
    "este_livro": "這本書",
    "armazenamento_local_indisponivel_neste": "此瀏覽器不支援本機儲存。",
    "o_aplicativo_pode_procurar_os_livros_q": "應用程式可以尋找您裝置上已有的書籍。",
    "vamos_montar_sua_estante": "要開始充實您的書架嗎？",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "若不同意，將無法使用此應用程式。",
    "precisamos_do_seu_aceite": "我們需要您的同意",
    "antes_de_comecar_leia_e_aceite_os_docu": "開始前，請閱讀並同意以下文件。",
    "selecionar_todos": "全選",
    "limpar_selecao": "清除選取",
    "todos_parecem_ja_estar_na_sua_estante": "它們似乎都已經在您的書架上了。",
    "lendo_a_pasta_escolhida": "正在讀取您選擇的資料夾…",
    "procurando_livros": "正在尋找書籍",
    "nao_foi_possivel_concluir_a_busca_no_d": "無法完成裝置上的搜尋。",
    "tente_outra_pasta_do_aparelho": "請嘗試裝置上的其他資料夾。",
    "nenhum_livro_encontrado": "找不到書籍",
    "use_o_botao_para_escolher_os_arquivos": "使用 + 按鈕手動選擇檔案。在 Android 手機上，Chrome 通常可以讓您選擇整個資料夾。",
    "seu_navegador_nao_permite_ler_pastas": "您的瀏覽器不允許讀取資料夾",
    "busca_automatica_indisponivel": "無法使用自動搜尋",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB、MOBI、CBZ、CBR 和 M4B",
    "termos_de_uso": "使用條款",
    "politica_de_privacidade": "隱私權政策",
    "um_minuto_agora_evita_perder_o_progres": "現在花一分鐘，日後就不會遺失進度和標記。",
    "ver_estante": "查看書架",
    "modo_juntar": "合併模式",
    "modo_substituir": "取代模式",
    "restauracao_concluida": "還原完成",
    "tente_de_novo_com_o_arquivo_original": "請使用原始檔案再試一次。",
    "a_restauracao_nao_pode_ser_concluida": "無法完成還原",
    "devolvendo_o_seu_progresso_e_as_suas_m": "正在還原您的進度和標記…",
    "restaurar_este_backup": "要還原此備份嗎？",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "選擇 Veredas 儲存的 .zip，或透過分享收到的 .txt。",
    "nao_foi_possivel_ler_este_arquivo": "無法讀取此檔案",
    "lendo_o_backup": "正在讀取備份",
    "backup_do_veredas_reader": "Veredas Reader 備份",
    "arquivo_de_transporte_txt_contendo_os": "備份的 .txt 格式副本，內容與 ZIP 相同",
    "nao_foi_possivel_montar_o_arquivo_de_b": "無法建立備份檔案。",
    "escolher_o_app": "選擇應用程式",
    "vale_conferir_o_que_vai_no_arquivo": "值得確認一下檔案裡有什麼",
    "enviar_para_outro_app": "傳送到其他應用程式",
    "salvar_o_arquivo": "儲存檔案",
    "o_navegador_aqui_nao_oferece_o_compart": "這裡的瀏覽器不支援直接分享。您可以儲存檔案，之後再透過您想要的應用程式傳送。",
    "este_aparelho_nao_abre_a_lista_de_apli": "此裝置無法開啟應用程式清單",
    "importe_pelo_menos_um_livro_antes_de_f": "請先匯入至少一本書再進行備份。",
    "estante_vazia": "書架是空的",
    "nao_deu_para_copiar": "無法複製",
    "copiar_detalhes": "複製詳細資料",
    "o_backup_foi_salvo_assim_mesmo": "備份仍已儲存",
    "o_aparelho_recusou_abrir_a_lista": "無法開啟分享清單",
    "sem_detalhes_do_navegador": "沒有瀏覽器詳細資料",
    "o_sistema_nao_aceitou_receber_o_arquiv": "裝置系統無法接收此檔案。",
    "o_navegador_considerou_a_situacao_inse": "瀏覽器依據本身的安全性規則封鎖了分享。請儲存檔案，再透過您想要的應用程式傳送。",
    "o_compartilhamento_so_funciona_em_ende": "分享只能在安全位址上運作。此應用程式正透過一般的 http:// 位址開啟，在這種情況下瀏覽器會封鎖傳送到其他應用程式。",
    "este_navegador_nao_conseguiu_iniciar_o": "此瀏覽器無法開啟分享。請儲存檔案，再透過您想要的應用程式傳送。",
    "o_navegador_recebeu_um_arquivo_em_form": "瀏覽器沒有開啟可分享的應用程式清單。請再輕觸一次按鈕，或儲存檔案後透過您想要的應用程式傳送。",
    "nao_foi_possivel_gerar_o_backup": "無法產生備份。",
    "reunindo_a_sua_estante": "正在整理您的書架…",
    "preparando_o_backup": "正在準備備份",
    "pronto_nada_mais_esta_esperando": "完成，沒有東西在等待了。",
    "o_progresso_e_as_marcacoes_desses_livr": "這些書的進度和標記將被刪除。若您之後匯入檔案，它們會以空白狀態回來。",
    "descartar_o_que_esta_esperando": "要刪除等待中的資料嗎？",
    "lembretes_de_backup_religados": "已重新開啟備份提醒。",
    "sem_titulo": "無標題",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "已關閉提醒。",
    "manter_ligado": "保持開啟",
    "desligar_assim_mesmo": "仍要關閉",
    "o_botao_de_salvar_continua_onde_sempre": "儲存按鈕仍在原來的位置，於「備份與還原」。",
    "o_lembrete_e_o_unico_aviso_que_existe": "提醒是唯一的通知。關閉之後，您需要自己記得備份。\n\n",
    "limpar_os_dados_do_navegador_desinstal": "如果清除了瀏覽器資料、解除安裝應用程式、換了手機或裝置故障，您的進度、螢光標記、引用、註記和書籤將無法復原。\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "您的書架只存在於此裝置上。沒有任何伺服器備份，因此我們無法為您找回。\n\n",
    "leia_antes_de_confirmar": "確認前請先閱讀",
    "desligar_os_lembretes_de_backup": "要關閉備份提醒嗎？",
    "progresso_de_leitura_restaurado_neste": "已還原這本書的閱讀進度。",
    "pronto": "完成。",
    "aplicando_as_suas_preferencias": "正在套用您的偏好設定…",
    "atualize_o_veredas_reader_e_tente_de_n": "請更新 Veredas Reader 後再試一次。",
    "este_backup_foi_feito_numa_versao_mais": "此備份是在較新版本的應用程式中建立的。",
    "este_arquivo_nao_e_um_backup_de_biblio": "此檔案不是 Veredas 的書庫備份。",
    "o_conteudo_interno_nao_pode_ser_lido": "無法讀取內部內容。",
    "o_backup_esta_corrompido": "備份已損毀。",
    "falta_o_arquivo_biblioteca_json_la_den": "裡面缺少 biblioteca.json 檔案。",
    "este_arquivo_nao_parece_ser_um_backup": "此檔案看起來不像 Veredas 的備份。",
    "compactando": "正在壓縮…",
    "para_restaurar_menu_lateral_backup_e_r": "若要還原：側邊選單 > 備份與還原 > 還原備份。",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas 會自動還原標記和您上次停下的位置。",
    "importe_os_livros_normalmente_no_aplic": "在應用程式中正常匯入書籍：當它辨識出每個檔案時，",
    "ele_nao_contem_os_arquivos_dos_livros": "它不包含書籍檔案。若要完整還原，",
    "as_notas_os_marcadores_e_a_organizacao": "您的註記、書籤和書架的整理方式。",
    "este_arquivo_guarda_o_seu_progresso_de": "此檔案保存您的閱讀進度、螢光標記、引用、",
    "verificando_se_sao_partes_do_mesmo_aud": "正在確認這些是否為同一本有聲書的部分…",
    "analisando_os_arquivos": "正在分析檔案",
    "nao_foi_possivel_salvar_o_audiolivro": "無法儲存有聲書。",
    "audiolivros_grandes_podem_levar_alguns": "較大的有聲書可能需要一些時間…",
    "salvando_na_sua_estante": "正在儲存到您的書架",
    "falha_ao_processar_os_arquivos": "處理檔案失敗。",
    "falha_ao_processar_o_arquivo": "處理檔案失敗。",
    "nao_foi_possivel_salvar_o_quadrinho": "無法儲存漫畫。",
    "quase_la": "快好了…",
    "falha_ao_processar_o_quadrinho": "處理漫畫失敗。",
    "autor_desconhecido": "未知作者",
    "lendo_o_quadrinho": "正在讀取漫畫…",
    "nao_foi_possivel_salvar_o_livro_na_bib": "無法將書籍儲存到書庫。",
    "nao_foi_possivel_ler_o_pdf": "無法讀取 PDF。",
    "lendo_o_pdf": "正在讀取 PDF…",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "若是舊版 .doc，請在 Word 中開啟並另存為 .docx 後再匯入。",
    "este_arquivo_nao_e_um_docx_valido": "此檔案不是有效的 .docx。",
    "livros_com_protecao_da_amazon_nao_pode": "受 Amazon 保護的書籍無法在此開啟。請使用無 DRM 的副本，或將書籍轉換為 EPUB。",
    "este_arquivo_esta_protegido_por_drm": "此檔案受 DRM 保護。",
    "confira_se_a_extensao_corresponde_ao_c": "請確認副檔名與內容相符，或將書籍轉換為 EPUB。",
    "este_arquivo_nao_e_um_mobi_valido": "此檔案不是有效的 MOBI。",
    "nao_foi_possivel_ler_o_arquivo": "無法讀取檔案。",
    "formato_nao_suportado": "不支援的格式。",
    "falha_ao_salvar_o_livro_na_biblioteca": "無法將書籍儲存到書庫。",
    "livro_importado_e_salvo_no_dispositivo": "書籍已匯入並儲存到此裝置。",
    "audiolivro_importado_e_salvo_no_dispos": "有聲書已匯入並儲存到此裝置。",
    "quadrinho_importado_e_salvo_no_disposi": "漫畫已匯入並儲存到此裝置。",
    "salvando_na_sua_estante_2": "正在儲存到您的書架…",
    "importando_livro": "正在匯入書籍",
    "importar_mesmo_assim": "仍要匯入",
    "parece_que_este_livro_ja_esta_na_estan": "這本書似乎已經在您的書架上了",
    "este_livro_ja_esta_na_estante": "這本書已經在您的書架上",
    "video_importado_e_salvo_no_dispositivo": "影片已匯入並儲存到此裝置。",
    "importacao_cancelada": "已取消匯入。",
    "preparando_o_arquivo": "正在準備檔案",
    "importando_audiolivro": "正在匯入有聲書",
    "importacao_concluida": "匯入完成",
    "importacao_interrompida": "匯入中斷",
    "a_importacao_foi_interrompida_o_que_ja": "匯入已中斷；已經進來的內容會留在書架上。",
    "finalizando": "正在完成…",
    "nao_foi_possivel_ler_o_arquivo_2": "無法讀取檔案",
    "importando_livros": "正在匯入書籍",
    "livros_quadrinhos_documentos_audiolivr": "書籍、漫畫、文件、有聲書和影片",
    "series": "系列",
    "colecoes": "收藏",
    "organizacao_salva": "已儲存整理。",
    "informe_um_nome_para_o_livro_antes_de": "儲存前請先為書籍命名。",
    "nome_do_livro_obrigatorio": "書名為必填",
    "importe_um_livro_primeiro": "請先匯入一本書。",
    "citacao": "引用",
    "anotacao": "註記",
    "citacao_2": "引用",
    "anotacao_2": "註記",
    "uma_citacao": "一則引用",
    "uma_anotacao": "一則註記",
    "o_marcador_sera_removido_da_biblioteca": "書籤將從書庫中移除，但書籍檔案會保持不變。",
    "marcador_de_audio": "音訊書籤",
    "marcador_de_video": "影片書籤",
    "nao_foi_possivel_excluir_o_livro": "無法刪除書籍。",
    "livro_excluido_da_biblioteca": "已從書庫刪除書籍。",
    "excluir_livro": "刪除書籍",
    "isso_remove_apenas_a_copia_armazenada": "這只會移除書庫儲存的副本，連同進度、書籤和註記。您自己資料夾中的原始檔案不會被刪除。",
    "excluir_livro_2": "刪除書籍？",
    "ordem_personalizada_salva": "已儲存自訂排序。",
    "ordem_manual_da_sua_estante": "您手動排列的書架順序。",
    "agrupamento_alterado_para_minha_ordem": "已將分組變更為「我的排序」。",
    "nova_ordem_salva": "已儲存新排序。",
    "nao_foi_possivel_salvar_a_nova_ordem": "無法儲存新排序。",
    "baixar_automaticamente": "自動下載",
    "escolha_livremente_onde_o_arquivo_sera": "自由選擇檔案的儲存位置。",
    "salvar_epub": "儲存 EPUB",
    "livro_epub": "EPUB 書籍",
    "erro_desconhecido": "未知錯誤",
    "a_permissao_para_salvar_o_arquivo_foi": "儲存檔案的權限已取消。書庫中沒有任何項目被變更。",
    "conversao_cancelada_o_pdf_original_per": "已取消轉換。原始 PDF 仍留在書庫中。",
    "preparando_salvamento": "正在準備儲存…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "書庫中沒有此 PDF 的副本。",
    "reconstruindo_o_livro_localmente": "正在本機重建書籍。",
    "convertendo_pdf": "正在轉換 PDF",
    "nao_foi_possivel_compartilhar_o_livro": "無法分享書籍。",
    "o_arquivo_foi_preparado_para_voce_comp": "檔案已備妥，可在其他應用程式中分享。",
    "livro_compartilhado": "已分享書籍。",
    "a_copia_deste_livro_nao_esta_disponive": "書庫中沒有此書的副本。",
    "para_manter_a_politica_de_compartilham": "為維持書庫的分享政策，此應用程式無法分享 EPUB 和 MOBI 檔案。",
    "quadrinhos_ficam_guardados_somente_no": "漫畫只保存在您的裝置上，無法透過此應用程式分享。",
    "audiolivros_e_videos_ficam_guardados_s": "有聲書和影片只保存在您的裝置上，無法透過此應用程式分享。",
    "formato_protegido": "受保護的格式",
    "compartilhamento_indisponivel": "無法分享",
    "concluido": "已完成",
    "ainda_nao_comecado": "尚未開始",
    "continue_lendo": "繼續閱讀",
    "continue_ouvindo": "繼續聆聽",
    "continue_assistindo": "繼續觀看",
    "comece_por_aqui": "從這裡開始",
    "comece_a_ouvir": "開始聆聽",
    "comece_a_assistir": "開始觀看",
    "no_total": "總計",
    "para_ler": "待閱讀",
    "sua_estante": "您的書架",
    "livros_organizados_pela_opcao_selecion": "書籍依您選擇的選項排列。",
    "uma_prateleira_para_cada_tipo_de_arqui": "每種檔案類型各有一個書架。",
    "autores_agrupados_em_ordem_alfabetica": "作者依字母順序分組。",
    "toque_para_continuar_de_onde_parou": "輕觸以從中斷處繼續。",
    "para_ler_2": "待閱讀",
    "lendo_agora": "正在閱讀",
    "audio_e_video": "音訊與影片",
    "trechos_salvos_separadamente_dos_marca": "與書籤分開儲存的段落。",
    "comentarios_vinculados_a_trechos_selec": "與您選取段落相關的評論。",
    "paginas_salvas_para_voltar_rapidamente": "儲存的頁面，方便快速返回。",
    "do_maior_para_o_menor_progresso_de_lei": "依閱讀進度由多到寡。",
    "livros_adicionados_ou_lidos_mais_recen": "最近新增或閱讀的書籍。",
    "ordem_alfabetica_pelo_titulo": "依標題字母順序。",
    "separa_em_prateleiras_de_epub_pdf_docx": "分成 EPUB、PDF、DOCX、有聲書、影片等書架。",
    "tipo_de_arquivo": "檔案類型",
    "organiza_e_separa_os_livros_por_autor": "依作者整理及區分書籍。",
    "agrupar_por_autor": "依作者分組",
    "pressione_o_livro_e_mova_o": "按住書籍，然後移動。",
    "minha_ordem": "我的排序",
    "epub_pronto": "EPUB 已備妥",
    "conversao_concluida": "轉換完成",
    "necessario_para_salvar_o_epub_ao_lado": "需要將 EPUB 儲存在原始檔旁邊",
    "escolha_a_pasta_do_pdf": "選擇 PDF 的資料夾",
    "processando": "處理中…",
    "processamento_local_no_navegador": "在瀏覽器本機處理",
    "convertendo_livro": "正在轉換書籍",
    "livro_em_pdf": "PDF 書籍",
    "recalculando_paginas": "正在重新計算頁面…",
    "ajustando_leitura": "正在調整閱讀版面",
    "abrir_comentario": "開啟評論",
    "anotacao_salva": "已儲存註記。",
    "anotacao_atualizada": "已更新註記。",
    "escreva_uma_nota_antes_de_salvar": "儲存前請先寫下註記。",
    "nao_foi_possivel_compartilhar": "無法分享。",
    "compartilhamento_indisponivel_2": "無法分享。",
    "trecho_copiado": "已複製段落。",
    "trecho_compartilhado": "已分享段落。",
    "citacao_salva": "已儲存引用。",
    "trecho_grifado": "已標記段落。",
    "grifo_removido": "已移除螢光標記。",
    "comentario_apagado": "已刪除評論。",
    "remover_grifo": "移除螢光標記",
    "apagar_comentario": "刪除評論",
    "remover_grifo_2": "移除螢光標記？",
    "apagar_comentario_2": "刪除評論？",
    "remover_este_grifo": "移除這個螢光標記？",
    "apagar_este_comentario": "刪除這則評論？",
    "sem_comentario": "沒有評論",
    "comentario": "評論",
    "marcador_removido_desta_pagina": "已從此頁面移除書籤。",
    "pagina_adicionada_aos_marcadores": "已將頁面加入書籤。",
    "este_e_o_inicio_do_livro": "這是書的開頭。",
    "esta_e_a_primeira_pagina": "這是第一頁。",
    "voce_chegou_ao_fim_do_livro": "您已到達書的結尾。",
    "voce_chegou_ao_fim_do_quadrinho": "您已到達漫畫的結尾。",
    "agora_em_revista_aberta_duas_paginas_l": "現在是雙頁顯示：兩頁並排，封面單獨一頁。",
    "leitura_horizontal_ativada_neste_livro": "此書已啟用水平閱讀。",
    "rolagem_vertical_ativada_neste_livro": "此書已啟用垂直捲動。",
    "leitura_pagina_a_pagina_ativada_neste": "此漫畫已啟用逐頁閱讀。",
    "rolagem_continua_ativada_neste_quadrin": "此漫畫已啟用連續捲動。",
    "mudar_para_rolagem_vertical": "切換為垂直捲動",
    "mudar_para_leitura_horizontal": "切換為水平閱讀",
    "rolagem_continua_estilo_webtoon": "連續捲動（網路漫畫風格）",
    "voltar_para_pagina_a_pagina": "返回逐頁閱讀",
    "separando_os_capitulos": "正在分割章節…",
    "lendo_o_livro": "正在讀取書本",
    "lendo_o_markdown": "正在讀取 Markdown",
    "lendo_o_documento": "正在讀取文件",
    "pagina_indisponivel": "頁面無法使用。",
    "isto_acontece_so_desta_vez": "這只會發生這一次。",
    "preparando_o_quadrinho": "正在準備漫畫",
    "abrindo_o_quadrinho": "正在開啟漫畫…",
    "montando_as_paginas": "正在建立頁面…",
    "nao_foi_possivel_abrir_este_livro": "無法開啟這本書。",
    "abertura_cancelada": "已取消開啟。",
    "o_livro_demorou_demais_para_abrir_e_fo": "書本開啟時間過長，已中止。",
    "importe_o_arquivo_novamente_para_conti": "請重新匯入檔案以繼續閱讀。",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "這本書的檔案已不再儲存於裝置上。",
    "preparando_sua_leitura": "正在準備您的閱讀…",
    "abrindo_livro": "正在開啟書本",
    "leitura_concluida": "閱讀完成。",
    "a_voz_foi_interrompida_pelo_navegador": "語音被瀏覽器中斷。",
    "nao_foi_possivel_preparar_este_trecho": "無法準備此段落進行語音朗讀。",
    "a_leitura_em_voz_alta_nao_e_suportada": "此瀏覽器不支援朗讀。",
    "pausar_leitura": "暫停朗讀",
    "em_pausa": "已暫停",
    "leitura_em_voz_alta_nao_disponivel_nes": "此瀏覽器無法使用朗讀",
    "nome_do_marcador": "書籤名稱",
    "o_marcador_sera_removido_deste_audioli": "書籤將從這本有聲書中移除。",
    "nao_foi_possivel_salvar_o_marcador": "無法儲存書籤。",
    "ja_existe_um_marcador_neste_ponto": "此處已有書籤。",
    "timer_de_sono_encerrado": "睡眠計時器已結束。",
    "fim_do_cap": "章節結束",
    "timer_desativado": "已關閉計時器。",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "音訊將在章節結束時暫停。",
    "este_audiolivro_nao_tem_capitulos": "這本有聲書沒有章節。",
    "ao_fim_do_capitulo": "在章節結束時",
    "desativar_timer": "關閉計時器",
    "mais_10_minutos_no_timer": "計時器增加 10 分鐘。",
    "somar_10_minutos": "增加 10 分鐘",
    "pausa_ao_fim_do_capitulo": "章節結束時暫停",
    "no_livro_todo": "全書",
    "video": "影片",
    "audiolivro_concluido": "有聲書已播放完畢。",
    "video_concluido": "影片已播放完畢。",
    "video_2": "影片",
    "audio": "音訊",
    "toque_em_reproduzir_para_comecar": "輕觸播放以開始。",
    "falha_ao_carregar_o_audio": "載入音訊失敗。",
    "exclua_o_da_biblioteca_e_importe_o_arq": "請從書庫中刪除，然後重新匯入檔案。",
    "os_nomes_dos_arquivos_seguem_uma_seque": "檔案名稱依序排列，因此看起來是同一本有聲書的章節。",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "這些檔案的標籤中有相同的專輯名稱，因此看起來是同一本有聲書的章節。",
    "libere_espaco_ou_exclua_livros_da_bibl": "請釋放空間或從書庫刪除書籍，然後再試一次。",
    "o_armazenamento_do_aparelho_esta_cheio": "裝置儲存空間已滿。",
    "preparando_a_capa": "正在準備封面…",
    "remova_esse_arquivo_da_selecao_e_tente": "請從選取範圍中移除該檔案，然後再試一次。",
    "sequencia": "順序",
    "o_arquivo_pode_estar_incompleto_tente": "檔案可能不完整。請嘗試重新下載。",
    "conferindo_se_o_audio_pode_ser_reprodu": "正在確認音訊是否可以播放…",
    "conferindo_se_o_video_pode_ser_reprodu": "正在確認影片是否可以播放…",
    "lendo_titulo_capitulos_e_capa": "正在讀取標題、章節和封面…",
    "o_arquivo_pode_estar_corrompido_ou_usa": "檔案可能已損毀，或使用了瀏覽器無法播放的音訊格式。請試著將其轉換為 MP3 或 M4B（AAC）。",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "檔案可能已損毀，或使用了瀏覽器無法播放的影片格式。請試著將其轉換為使用 H.264 影片和 AAC 音訊的 MP4。",
    "converta_o_audiolivro_para_m4b_com_aud": "請將有聲書轉換為 M4B（AAC 音訊）或 MP3，然後重新匯入。",
    "converta_o_video_para_mp4_com_audio_aa": "請將影片轉換為 MP4（AAC 音訊與 H.264 視訊）後重新匯入。",
    "o_navegador_nao_reproduz_o_formato_de": "瀏覽器無法播放此檔案的音訊格式。",
    "arquivos_com_protecao_nao_podem_ser_re": "受保護的檔案無法在此播放。請使用無 DRM 的副本。",
    "nao_ha_espaco_suficiente_no_aparelho_p": "裝置上沒有足夠空間容納這本有聲書。",
    "confira_se_a_extensao_corresponde_ao_c_2": "請確認副檔名與內容相符，或將音訊轉換為 MP3 或 M4B（AAC）。",
    "imagem_invalida": "無效的圖片",
    "imagem_demorou_demais": "圖片載入時間過長",
    "imagem_vazia": "空白圖片",
    "inicio": "開頭",
    "mp4_moov_nao_encontrado": "這部影片似乎不完整或已損毀。",
    "pagina": "頁面",
    "esta_pagina_nao_esta_disponivel": "此頁面無法使用。",
    "esta_pagina_nao_pode_ser_descompactada": "無法解壓縮此頁面。",
    "quadrinho_fechado": "已關閉漫畫。",
    "ele_pode_estar_incompleto_dividido_em": "它可能不完整、分成多個部分，或是應用程式無法辨識的 RAR 變體。轉換為 CBZ 通常可以解決。",
    "remova_a_senha_do_arquivo_e_importe_de": "請移除檔案的密碼後重新匯入。",
    "nao_foi_possivel_ler_este_arquivo_de_q": "無法讀取此漫畫檔案。",
    "este_quadrinho_esta_protegido_por_senh": "此漫畫受密碼保護。",
    "lendo_o_indice_do_quadrinho": "正在讀取漫畫索引…",
    "o_arquivo_pode_ser_grande_demais_para": "檔案可能對這台裝置的記憶體來說太大。將漫畫分成較小的部分通常可以解決。",
    "nao_foi_possivel_abrir_este_quadrinho": "無法開啟此漫畫。",
    "lendo_o_arquivo": "正在讀取檔案…",
    "preparando_o_leitor_de_cbr": "正在準備 CBR 閱讀器…",
    "o_arquivo_pode_estar_incompleto_proteg": "檔案可能不完整、受密碼保護或損毀。",
    "nao_foi_possivel_ler_este_quadrinho": "無法讀取此漫畫。",
    "o_arquivo_precisa_conter_imagens_jpg_p": "檔案必須包含圖片（JPG、PNG、WEBP 或 GIF）。",
    "nao_encontramos_paginas_dentro_deste_q": "我們在此漫畫中找不到任何頁面。",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "裝置上沒有足夠空間容納這本漫畫。",
    "cabecalho_de_item_invalido": "檔案的一部分已損毀。",
    "a_pasta_vendor_libarchive_precisa_esta": "缺少開啟此漫畫所需的應用程式元件。請將其轉換為 CBZ，或重新安裝應用程式。",
    "o_leitor_de_cbr_nao_foi_encontrado": "找不到 CBR 閱讀器。",
    "converta_o_quadrinho_para_cbz_zip_e_im": "請將漫畫轉換為 CBZ（ZIP）後重新匯入。",
    "este_navegador_nao_consegue_abrir_arqu": "此瀏覽器無法開啟 CBR 檔案。",
    "convertendo_o_markdown": "正在轉換 Markdown",
    "lendo_o_texto": "正在讀取文字",
    "pdf_indisponivel": "PDF 無法使用。",
    "epub_invalido_nenhum_capitulo_no_spine": "此 EPUB 已損毀：找不到書籍的章節。",
    "livro_sem_titulo": "無標題書籍",
    "epub_invalido_arquivo_opf_nao_encontra": "此 EPUB 不完整或已損毀，無法開啟。",
    "epub_invalido_container_xml_nao_encont": "此 EPUB 不完整或已損毀，無法開啟。",
    "organizando_o_texto": "正在編排文字",
    "descompactando_o_livro": "正在解壓縮書本",
    "nao_encontramos_conteudo_para_exibir_n": "我們在此檔案中找不到可顯示的內容。",
    "livro_sem_texto_legivel": "沒有可讀文字的書",
    "o_arquivo_pode_estar_corrompido_tente": "檔案可能損毀。請嘗試轉換為 EPUB。",
    "nao_foi_possivel_extrair_o_texto_deste": "無法從此 MOBI 擷取文字。",
    "nenhum_registro_de_conteudo_foi_encont": "在此檔案中找不到書籍的內文。",
    "arquivo_mobi_sem_texto": "沒有文字的 MOBI 檔案。",
    "o_dicionario_de_compressao_esta_vazio": "此 MOBI 的部分內容遺失。",
    "arquivo_mobi_incompleto": "MOBI 檔案不完整。",
    "as_tabelas_de_compressao_nao_foram_enc": "此 MOBI 的部分內容遺失。",
    "converta_o_arquivo_para_epub_em_um_pro": "請使用 Calibre 等程式將檔案轉換為 EPUB 後重新匯入。",
    "compressao_mobi_nao_reconhecida": "此 MOBI 使用了本應用程式無法辨識的內部格式。",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "無法讀取書本標頭。",
    "arquivo_mobi_corrompido": "MOBI 檔案損毀。",
    "a_lista_interna_de_registros_esta_inco": "檔案不完整。請試著重新下載或重新轉換。",
    "o_download_parece_ter_sido_interrompid": "下載似乎被中斷。請重新下載檔案。",
    "tabela_de_compressao_mobi_corrompida": "此 MOBI 檔案的一部分已損毀。",
    "tabela_de_compressao_mobi_incompleta": "此 MOBI 檔案不完整。",
    "tabela_de_compressao_mobi_invalida": "此 MOBI 檔案的一部分已損毀。",
    "este_arquivo_docx_nao_tem_conteudo_de": "此 .docx 檔案沒有可顯示的文字內容。",
    "documento_sem_texto": "沒有文字的文件",
    "o_arquivo_pode_estar_corrompido_proteg": "檔案可能損毀、受密碼保護，或是舊版 .doc。請重新儲存為 .docx 後再匯入一次。",
    "nao_foi_possivel_ler_este_arquivo_docx": "無法讀取此 DOCX 檔案。",
    "convertendo_o_documento": "正在轉換文件",
    "conecte_se_a_internet_uma_vez_para_bai": "請連線至網際網路一次以下載元件，然後再次開啟書本。",
    "o_conversor_de_docx_nao_carregou": "DOCX 轉換器未載入。",
    "video_mp4": "影片（MP4）",
    "audiolivro_m4b": "有聲書（M4B）",
    "audiolivro_mp3": "有聲書（MP3）",
    "quadrinho_cbt": "漫畫（CBT）",
    "quadrinho_cb7": "漫畫（CB7）",
    "quadrinho_cbr": "漫畫（CBR）",
    "quadrinho_cbz": "漫畫（CBZ）",
    "markdown_md": "Markdown（MD）",
    "texto_txt": "文字（TXT）",
    "word_docx": "Word（DOCX）",
    "gravacao_cancelada": "已取消儲存。",
    "o_arquivo_esta_vindo_do_armazenamento": "檔案正從雲端儲存空間下載到您的裝置。",
    "baixando_o_arquivo": "正在下載檔案",
    "cancelando": "正在取消…",
    "use_grifar_citacao_anotar_ou_marcador": "閱讀時使用「螢光標記」、「引用」、「註記」或「書籤」。",
    "nenhuma_marcacao_ainda": "尚無標記",
    "trecho_original": "原始段落",
    "procurar_meus_livros": "尋找我的書籍",
    "a_busca_fica_sempre_disponivel_no_menu": "搜尋功能隨時可在側邊選單的「系統」中找到。",
    "da_para_fazer_depois": "可以稍後再做",
    "nada_entra_na_estante_sem_a_sua_confir": "未經您確認，任何東西都不會進入書架：您會看到清單並勾選想匯入的項目。",
    "voce_revisa_antes": "您會先檢視",
    "escolha_uma_pasta_downloads_e_um_bom_c": "選擇一個資料夾（建議從「下載」開始），應用程式會搜尋該資料夾及所有子資料夾。",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "搜尋 EPUB、MOBI、CBZ、CBR 和 M4B",
    "voltar_e_revisar": "返回並檢視",
    "ler_os_termos": "閱讀條款",
    "ler_a_politica": "閱讀政策",
    "os_dois_documentos_ficam_sempre_dispon": "兩份文件隨時可在側邊選單的「關於」中找到。",
    "leia_com_calma": "慢慢閱讀",
    "a_politica_e_os_termos_explicam_como_o": "政策與條款說明了應用程式如何保存您的書籍，以及您可以如何使用它們。若要使用書庫，需要您同意這些內容。",
    "nada_acontece_sem_o_aceite": "開始使用前，請先接受條款",
    "aceitar_e_continuar": "同意並繼續",
    "nao_aceito": "我不同意",
    "termos_de_uso_2": "使用條款",
    "politica_de_privacidade_2": "隱私權政策",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "應用程式只會存取您選擇的檔案和資料夾，而且只在您選擇時。",
    "voce_no_controle": "由您掌控",
    "depois_de_importar_um_livro_voce_le_se": "匯入書籍後，您不需要網路就能閱讀。",
    "funciona_offline": "離線運作",
    "livros_marcacoes_e_progresso_sao_guard": "書籍、標記和進度都儲存在本機。不會傳送到我們的伺服器。",
    "tudo_fica_no_seu_aparelho": "一切都在您的裝置上",
    "escolha_o_que_deseja_adicionar_a_bibli": "選擇您想加入書庫的內容。與書架上現有項目相同的檔案會自動略過。",
    "voce_pode_tentar_outra_pasta_ou_import": "您可以嘗試其他資料夾，或使用 + 按鈕匯入檔案。",
    "a_leitura_acontece_so_no_seu_dispositi": "讀取只會在您的裝置上進行。",
    "voce_escolhe_a_pasta": "您選擇資料夾",
    "tema_tipografia_margens_modo_de_virada": "主題、字型、邊界、翻頁模式及音訊設定。",
    "restaurar_minhas_preferencias": "還原我的偏好設定",
    "o_backup_manda_as_marcacoes_atuais_dos": "備份優先。檔案中書籍目前的標記將被備份中的標記取代。",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "不會刪除任何東西。兩邊的標記會合併，較新的進度優先。",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "如何處理書架上已有的內容",
    "grifos_citacoes_e_notas": "螢光標記、引用和註記",
    "preparando_o_arquivo_2": "正在準備檔案…",
    "os_livros_em_si_nem_as_capas_por_isso": "既不包含書籍檔案本身，也不包含封面——所以這個檔案只有幾 KB。接收的人需要有這些書籍檔案，標記才能回到原本的位置；封面會在匯入書籍時自動重新出現。",
    "nao_vai_no_arquivo": "不包含在檔案中",
    "o_seu_progresso_de_leitura_os_grifos_a": "您的閱讀進度、螢光標記、引用、註記、書籤，以及書架的整理方式——狀態、我的最愛、收藏、系列和標籤。",
    "vai_no_arquivo": "包含在檔案中",
    "descartar_o_que_esta_esperando_2": "刪除等待中的資料",
    "esperando_o_arquivo": "正在等待檔案",
    "avisar_quando_fizer_tempo_sem_backup": "一段時間未備份時提醒我",
    "livros_que_ainda_nao_estiverem_na_esta": "尚未在書架上的書籍會先保留等待：當您匯入其檔案時，標記會自動恢復。",
    "restaurar_backup": "還原備份",
    "salvar_backup": "儲存備份",
    "ainda_nao_ha_itens": "尚無項目",
    "arraste_um_livro_para_outra_posicao_na": "將書拖曳到書架上的其他位置即可儲存手動排序。手動排序會優先於依作者分組。",
    "separe_por_virgulas": "以逗號分隔",
    "ex_estudos_ficcao": "例：研究、小說…",
    "pasta_estante": "資料夾／書架",
    "ex_trilogia": "例：三部曲…",
    "serie": "系列",
    "aparece_em_favoritos": "顯示於「我的最愛」。",
    "nome_do_livro": "書名",
    "nenhum_registro_ainda": "尚無紀錄",
    "no_leitor_toque_no_icone_de_marcador_p": "在閱讀器中，輕觸書籤圖示即可儲存頁面。",
    "nenhum_marcador_ainda": "尚無書籤",
    "a_gravacao_e_independente_da_localizac": "儲存作業與 PDF 的位置無關，也不會變更原始檔案。",
    "o_pdf_original_nao_precisa_estar_nessa": "原始 PDF 不必在那個資料夾中",
    "excluir_da_biblioteca": "從書庫刪除",
    "adicionar_livro": "新增書籍",
    "adicione_livros_e_acompanhe_o_que_esta": "新增書籍並追蹤哪些待閱讀、哪些正在進行，以及您的進度。",
    "tudo_pronto_para_a_proxima_leitura": "一切都準備好迎接下一次閱讀。",
    "sua_biblioteca": "您的書庫",
    "arraste_um_livro_para_reposiciona_lo_a": "拖曳書籍即可重新排列：書架會切換為「我的排序」並保留順序。",
    "importe_um_livro_ou_ajuste_seus_filtro": "匯入書籍，或調整您的整理篩選條件。",
    "nada_por_aqui_ainda": "這裡還沒有東西",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "輕觸 + 並選擇 MP3、M4B 或 MP4 檔案。多個章節 MP3 可以合併成一本有聲書。",
    "nada_para_ouvir_ou_assistir_ainda": "尚無可聆聽或觀看的內容",
    "o_pdf_original_permanece_intacto_na_pa": "原始 PDF 會保持原樣留在您的資料夾中。",
    "paginas_como_imagem": "頁面轉為圖片",
    "paginas_do_pdf": "PDF 頁面",
    "em_navegadores_sem_suporte_a_acesso_di": "在不支援直接存取檔案系統的瀏覽器中，EPUB 將改為下載。",
    "essa_permissao_e_dada_somente_a_esta_a": "此權限只授予這個應用程式，並可避免原始檔案被變更。",
    "selecione_a_pasta_que_contem_o_pdf": "選取包含 PDF 的資料夾",
    "preparando": "正在準備…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "正在讀取並重建檔案。較大的書籍可能需要一些時間。",
    "revistas_apostilas_complexas_formulari": "雜誌、複雜的教材、表單、含大量表格的文件或掃描的 PDF 可能會遺失部分原始版面。",
    "funcionalidade_indicada_apenas_para_li": "僅適用於書籍",
    "o_epub_e_melhor_para_livros_com_texto": "EPUB 較適合有可選取文字的書籍，因為它可讓您調整字型、大小、邊界和閱讀模式。",
    "trecho_selecionado": "已選取的段落",
    "trecho_comentado": "已加註的段落",
    "aplicando_zoom": "正在套用縮放…",
    "nao_foi_possivel_carregar_esta_pagina": "無法載入此頁面。",
    "nomear_marcador": "命名書籤",
    "toque_em_marcar_agora_para_guardar_est": "輕觸「立即標記」即可保存此位置，隨時回來。",
    "timer_ativo": "計時器已開啟",
    "trecho_ausente_ou_corrompido_no_arquiv": "〔原始檔案中的段落遺失或損毀〕",
    "novos_livros_vao_abrir_em_leitura_v": "新書將以{v}閱讀模式開啟。",
    "leitura_efetivo_aplicada_a_este_livro": "已將{efetivo}閱讀模式套用至這本書。",
    "automatico_neste_livro_leitura_efetivo": "此書為自動：{efetivo}閱讀模式。",
    "agora_esta_em_efetivo_no_automatico_fo": "目前已設為{efetivo}；在自動模式下，{format}以{padrao}開啟。",
    "esta_escolha_vale_so_para_v_cada_livro": "此選擇只適用於「{v}」。每本書會保留自己的捲動方向。",
    "novos_ainda_nao_estao_na_sua_estante": "{novos}還不在您的書架上。",
    "escolha_uma_pasta_para_procurar_label": "選擇資料夾以搜尋{label}。",
    "subtitle_versao_build": "{subtitle} · 版本 {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "無法讀取{path}；使用內建文字。",
    "seu_ultimo_backup_foi_ha_dias_dias": "您上次備份是在{dias}天前",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "備份中有 {aguardando} 本書還不在這裡。它的進度和標記已保存：只要您匯入檔案，一切就會自動回到原位。",
      "other": "備份中有 {aguardando} 本書還不在這裡。它們的進度和標記已保存：只要您匯入每個檔案，一切就會自動回到原位。"
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "已更新您書架上的{atualizados}本書。",
      "other": "已更新您書架上的{atualizados}本書。"
    },
    "criado_em_quando": "建立於{quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "備份完成：{livros}本書和{marcacoes}個標記。",
    "endereco_seguro_seguro": "安全位址：{seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "已還原這本書的進度和{marcas}個標記。",
      "other": "已還原這本書的進度和{marcas}個標記。"
    },
    "restaurando_v_de_length": "正在還原（{v}/{length}）…",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros}本書 · {marcacoes}個標記",
    "criado_em_v": "建立於{v}",
    "reunindo_a_sua_estante_v_de_length": "正在整理您的書架（{v}/{length}）…",
    "titulo_ja_foi_importado_antes_e_contin": "「{titulo}」之前已匯入，仍在您的書庫中。未建立新副本。",
    "length_arquivos_de_audio": "{length}個音訊檔案…",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "{falhas}個檔案無法讀取。",
      "other": "{falhas}個檔案無法讀取。"
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos}已在書庫中，已略過。",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "已將{importados}本書加入書架。",
      "other": "已將{importados}本書加入書架。"
    },
    "epub_salvo_em_filename": "EPUB 已儲存至{fileName}。",
    "falha_ao_converter_o_pdf_v": "無法轉換 PDF：{v}",
    "pagina_page_de_totalpages": "第{page}頁，共{totalPages}頁",
    "totalpages_paginas": {
      "one": "{totalPages}頁",
      "other": "{totalPages}頁"
    },
    "length_resultado_s_para_search": {
      "one": "「{search}」有{length}個結果",
      "other": "「{search}」有{length}個結果"
    },
    "capitulo_v": "第{v}章",
    "organizando_capitulo_v_de_totalchapter": "正在編排第{v}章，共{totalChapters}章",
    "pagina_v": "第{v}頁",
    "paginas_v_v2": "第{v}–{v2}頁",
    "length_pagina_s_prontas": {
      "one": "{length}頁已備妥",
      "other": "{length}頁已備妥"
    },
    "montando_as_paginas_pagessofar_prontas": "正在建立頁面——已完成{pagesSoFar}頁",
    "lendo_pagina_v_de_length": "正在讀取第{v}頁，共{length}頁",
    "marcador_salvo_em_t": "書籤已儲存於{t}。",
    "o_audio_vai_pausar_em_minutes_minutos": "音訊將在{minutes}分鐘後暫停。",
    "length_capitulos_toque_para_ir_direto": "{length}章 · 輕觸即可直接前往。",
    "narrado_por_narrator": "由{narrator}朗讀",
    "velocidade_de_reproducao_rate": "播放速度：{rate}",
    "avancar_f_segundos": "快轉{f}秒",
    "nao_foi_possivel_abrir_este_v": "無法開啟此{v}。",
    "nao_foi_possivel_ler_o_arquivo_de_v": "無法讀取{v}檔案。",
    "o_v_esta_danificado_neste_ponto": "{v}在此處損毀。",
    "o_navegador_nao_consegue_reproduzir_es": "瀏覽器無法播放此{v}檔案。",
    "nao_foi_possivel_reproduzir_este_v": "無法播放此{v}。",
    "os_dados_deste_noun_estao_incompletos": "此{noun}的資料不完整。",
    "importe_o_arquivo_novamente_para_conti_2": "請重新匯入檔案以繼續{v}。",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "此{noun}的檔案已不再儲存於裝置上。",
    "nao_foi_possivel_descobrir_a_duracao_d": "無法得知「{name}」的長度。",
    "lendo_faixa_v_de_length": "正在讀取第{v}軌，共{length}軌…",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "無法得知此{v}的長度。",
    "este_format_nao_pode_ser_reproduzido_n": "此{format}無法在此瀏覽器中播放。",
    "este_format_esta_protegido_por_drm": "此{format}受 DRM 保護。",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "檔案大小為{bytes}，剩餘約{v}。請釋放空間或從書庫刪除書籍。",
    "este_arquivo_nao_e_um_format_valido": "此檔案不是有效的{format}。",
    "preparando_as_paginas_vistas_de_total": "正在準備頁面（{vistas}/{total}）…",
    "preparando_total_pagina_s": {
      "one": "正在準備{total}頁…",
      "other": "正在準備{total}頁…"
    },
    "preparando_as_paginas_v_de_total": "正在準備頁面（{v}/{total}）…",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "它佔約{bytes}，剩餘約{v}。請釋放空間或從書庫刪除書籍。",
    "envio_direto_exige_endereco_seguro": "此頁面並非透過安全位址開啟，因此無法直接傳送到其他應用程式。請儲存檔案，再透過您想要的應用程式傳送。",
    "na_estante": "在書架上",
    "nao_foi_possivel_montar_o_arquivo": "無法建立檔案。",
    "este_navegador_nao_oferece_o_envio_dir": "此瀏覽器不支援直接傳送到其他應用程式。請儲存檔案，再透過您偏好的應用程式附加。",
    "voce_ainda_nao_fez_nenhum_backup": "您尚未進行任何備份。",
    "converter_para_epub": "轉換為 EPUB",
    "esta_pagina_nao_pode_ser_exibida": "無法顯示此頁面。",
    "na_ordem_em_que_serao_tocados": "依播放順序",
    "este_capitulo_nao_pode_ser_exibido": "無法顯示此章節。",
    "livro": "書",
    "restantes": "剩餘",
    "como_seus_dados_sao_tratados": "您的資料如何處理",
    "condicoes_de_uso_do_aplicativo": "應用程式使用條件",
    "audiolivro": "有聲書",
    "sobre_o_aplicativo": "關於應用程式",
    "o_que_e_o_veredas_reader": "什麼是 Veredas Reader",
    "o_aparelho_recusou_o_tipo_do_arquivo": "（此裝置不支援分享這種類型的檔案）",
    "livros": "書籍",
    "lendo": "閱讀中",
    "lidos": "已讀",
    "compartilhar_livro": "分享書籍",
    "n_livros": {
      "one": "{n}本書",
      "other": "{n}本書"
    },
    "livros_unidade": {
      "one": "本書",
      "other": "本書"
    },
    "uma_faixa_discreta_depois_de_n_dias": "在{n}天沒有備份後，於書架上顯示一條低調的提示。絕不會中斷您的閱讀。",
    "scanned_arquivos_verificados_livros_enc": "已檢查{scanned}個檔案 · 找到{encontrados}本書",
    "v_de_total": "{v}/{total}",
    "voltar_n_segundos": "倒轉{n}秒",
    "grifos": "螢光標記",
    "excluir": "刪除",
    "entendi": "了解",
    "restaurando": "正在還原",
    "restaurar": "還原",
    "copiado": "已複製",
    "descartar": "刪除",
    "aviso": "通知",
    "cancelado": "已取消",
    "audiolivro_2": "有聲書",
    "progresso": "進度",
    "recentes": "最近",
    "concluir": "完成",
    "apagar": "刪除",
    "editar": "編輯",
    "grifo": "螢光標記",
    "leitura": "閱讀",
    "marcador": "書籤",
    "pausar": "暫停",
    "outros": "其他",
    "outro": "其他",
    "arquivo": "檔案",
    "arquivo_vazio": "檔案是空的。",
    "e_mais_n_arquivos": {
      "one": "以及另外{n}個檔案，依播放順序",
      "other": "以及另外{n}個檔案，依播放順序"
    },
    "n_arquivos_mp3": {
      "one": "{n}個 MP3 檔案",
      "other": "{n}個 MP3 檔案"
    },
    "pct_restam": "{pct}% · 剩餘{tempo}",
    "n_minutos": {
      "one": "{n}分鐘",
      "other": "{n}分鐘"
    },
    "ir_para_tempo": "前往{tempo}",
    "nomear": "命名",
    "parte_n": "第{n}部分",
    "carregando_pagina_n": "正在載入第{n}頁…",
    "selecionar_pasta_e_continuar": "選取資料夾並繼續",
    "ler_agora": "立即閱讀",
    "agrupamento_v": "分組：{v}。",
    "tempo_restante": "剩餘{tempo}",
    "abrir_titulo": "開啟{titulo}",
    "continuar_lendo_titulo": "繼續閱讀{titulo}",
    "continuar_ouvindo_titulo": "繼續聆聽{titulo}",
    "continuar_assistindo_titulo": "繼續觀看{titulo}",
    "lido": "已讀",
    "pausado": "已暫停",
    "status": "狀態",
    "favorito": "我的最愛",
    "escolher_local": "選擇位置",
    "epub_baixado_como": "EPUB 已下載為{nome}。",
    "ouvir_a_partir_de": "從{tempo}開始聆聽",
    "assistir_a_partir_de": "從{tempo}開始觀看",
    "pagina_n_minuscula": "第{n}頁",
    "selecione_trecho_para_criar": "閱讀時選取一段文字即可建立{oque}。",
    "excluir_oque_pergunta": "刪除{oque}？",
    "excluir_oque": "刪除{oque}",
    "excluir_item_pergunta": "刪除此項目？",
    "use_organizar_para_criar": "在書籍上使用「{botao}」即可建立{oque}。",
    "n_arquivos_processados": {
      "one": "已處理{n}個檔案",
      "other": "已處理{n}個檔案"
    },
    "voce_ja_tem_titulo_de_autor": "您的書庫中已有{autor}的「{titulo}」，雖然檔案不同。仍要匯入嗎？",
    "voce_ja_tem_titulo": "您的書庫中已有「{titulo}」，雖然檔案不同。仍要匯入嗎？",
    "marcadores_unidade": {
      "one": "個書籤",
      "other": "個書籤"
    },
    "ultimo_backup_em": "上次備份於<strong>{data}</strong>。",
    "guardar": "儲存",
    "lembretes": "提醒",
    "juntar": "合併",
    "recomendado": "建議",
    "substituir": "取代",
    "n_capas_recuperadas": {
      "one": "已復原{n}個封面。",
      "other": "已復原{n}個封面。"
    },
    "nao_encontramos_arquivos_tipo": "我們在此資料夾中找不到{tipo}檔案。",
    "tentar_outra_pasta": "嘗試其他資料夾",
    "n_livros_encontrados": {
      "one": "找到{n}本書",
      "other": "找到{n}本書"
    },
    "n_de_total_selecionados": {
      "one": "已選取{total}中的{n}個",
      "other": "已選取{total}中的{n}個"
    },
    "importar": "匯入",
    "importar_n": "匯入{n}個",
    "aceite_frase": "我已閱讀並同意 Veredas Reader 的{politica}和{termos}。",
    "pdf_preservado": "原始 PDF <strong>不會從您的資料夾中刪除</strong>。只有在 EPUB 成功儲存後，才會從書庫中移除此 PDF 的副本。",
    "gravar_epub_mesma_pasta": "若要將 EPUB 儲存<strong>在與 PDF 相同的資料夾中</strong>，瀏覽器需要存取該資料夾的權限。",
    "epub_pronto_qualquer_pasta": "EPUB 已轉換完成。現在您可以選擇<strong>電腦上的任何資料夾</strong>來儲存檔案。",
    "backup_explicacao": "原始備份是 ZIP 或 TXT 檔案。在其他裝置上收到後，請透過<strong>還原備份</strong>匯入，Veredas 會辨識內容並正常還原。檔案保存您的進度、螢光標記、引用、註記、書籤及書架整理方式——<strong>不含書籍本身</strong>，也不含封面。",
    "lembretes_desligados_frase": "提醒已<strong>關閉</strong>。請記得不時備份一下。",
    "backup_salvo_nos_downloads": "<strong>備份檔案已儲存到此裝置</strong>的下載資料夾中。您現在就可以傳送：開啟 WhatsApp、電子郵件、雲端硬碟或任何您想要的應用程式，輕觸附加並選擇檔案。",
    "arquivo_pronto_tamanho": "檔案已備妥 — <strong>{tamanho}</strong>",
    "scan_intro_frase": "應用程式可以在您裝置上的資料夾（包括子資料夾）中尋找 <strong>EPUB</strong> 和 <strong>MOBI</strong> 格式的書籍、<strong>CBZ</strong> 和 <strong>CBR</strong> 格式的漫畫，以及 <strong>M4B</strong> 格式的有聲書。",
    "scan_intro_auto_frase": "為了快速充實您的書架，應用程式可以在您裝置上的資料夾（包括子資料夾）中尋找 <strong>EPUB</strong> 和 <strong>MOBI</strong> 格式的書籍、<strong>CBZ</strong> 和 <strong>CBR</strong> 格式的漫畫，以及 <strong>M4B</strong> 格式的有聲書。",
    "n_livros_aguardando": {
      "one": "<strong>{n} 本書</strong>的進度和標記已保存，正在等待再次匯入。",
      "other": "<strong>{n} 本書</strong>的進度和標記已保存，正在等待再次匯入。"
    },
    "fora_da_busca_titulo": "我們不會自動匯入 PDF、TXT、DOCX（Word）、MD、MP3 和 MP4 檔案",
    "fora_da_busca_texto": "這些格式適用於各種文件，而不只是書籍。不自動匯入它們，能讓書架保持整齊。<strong>您可以透過 + 按鈕逐一手動匯入。</strong>"
  },
  "aviso": {
    "idioma_trocado": "語言已變更。"
  },
  "vn": {
    "quem_le": "朗讀語音",
    "natural": "自然",
    "do_sistema": "系統",
    "nota_sistema": "使用裝置上已安裝的語音。想要更像真人的朗讀，請選擇「自然」。",
    "nota_sistema_com_natural": "自然語音仍保留在裝置上。隨時都能切換回「自然」。",
    "voz_natural": "自然語音",
    "gerada_no_aparelho": "更像真人的語音，直接在裝置上產生。",
    "progresso_download": "下載進度",
    "x_de_y": "{x} / {y}",
    "aviso_arquivo": "自然語音需要透過應用程式的網址開啟 Veredas，而不是以電腦上的檔案開啟。在此之前，將使用系統語音朗讀。",
    "aviso_navegador": "這個瀏覽器缺少自然語音所需的功能。將繼續使用系統語音朗讀。",
    "verificando": "正在檢查自然語音…",
    "fato_download": "只需下載一次，大小 {tamanho}。之後不需網路也能使用。",
    "fato_wifi": "建議使用 Wi-Fi。可以暫停，稍後再繼續。",
    "fato_privacidade": "書中的文字不會離開裝置。",
    "fato_idiomas": "支援英語、葡萄牙語、西班牙語等 31 種語言，暫不支援中文。不支援的語言會繼續使用系統語音。",
    "baixar_voz_natural": "下載自然語音（{tamanho}）",
    "licenca_curta": "Supertone 的 Supertonic 3 模型，採用 OpenRAIL-M 授權。詳情請見「關於 > 開源授權」。",
    "pode_continuar_usando": "下載時可以繼續閱讀。如果連線中斷，下載會從中斷處繼續。",
    "pausar_download": "暫停下載",
    "erro_espaco": "裝置空間不足，無法完成下載。請釋放一些空間後再試一次。",
    "erro_offline": "目前沒有網路連線。已下載的部分都已保存。",
    "erro_rede": "下載途中連線中斷。已下載的部分都已保存。",
    "download_pausado": "下載已暫停。已下載的部分都已保存。",
    "continuar_download": "繼續",
    "descartar": "捨棄",
    "voz_feminina": "女聲",
    "voz_feminina_desc": "柔和平靜",
    "voz_masculina": "男聲",
    "voz_masculina_desc": "溫暖沉穩",
    "parar_amostra": "停止試聽",
    "ouvir_amostra_de": "試聽：{voz}",
    "escolha_a_voz": "選擇語音",
    "qualidade": "品質",
    "q_auto": "自動",
    "q_rapida": "快速",
    "q_maxima": "最佳",
    "q_auto_desc": "依裝置效能自動調整，讓朗讀流暢不停頓。",
    "q_rapida_desc": "更快產生語音。適合規格較簡單的裝置。",
    "q_maxima_desc": "音質最細緻。在規格較簡單的裝置上，句子之間可能會停頓。",
    "ocupa": "在此裝置上占用 {tamanho}",
    "remover": "移除",
    "baixar_pelos_dados": "要使用行動數據下載嗎？",
    "baixar_pelos_dados_msg": "裝置似乎沒有連上 Wi-Fi。下載大小為 {tamanho}，可能會用掉行動數據方案的流量。",
    "baixar_agora": "仍要下載",
    "pronta": "自然語音已準備就緒。",
    "download_interrompido": "下載已停止。方便時輕觸「繼續」即可。",
    "remover_titulo": "要移除自然語音嗎？",
    "descartar_titulo": "要捨棄這次下載嗎？",
    "remover_msg": "將釋放 {tamanho}。朗讀會改回系統語音，之後隨時可以重新下載。",
    "descartar_msg": "已下載的部分將會刪除。",
    "removida": "已從此裝置移除自然語音。",
    "amostra_falhou": "無法在此裝置上播放試聽。",
    "amostra": "哈囉！用自然語音朗讀，書聽起來就是這樣。",
    "gerando_voz": "正在準備語音…",
    "automatico_idioma": "自動（{idioma}）",
    "automatico": "自動",
    "so_voz_do_sistema": "系統語音",
    "aviso_idioma": "文字語言：{idioma}。自然語音尚不支援此語言，因此將以系統語音朗讀本書。",
    "aviso_idioma_desconhecido": "無法辨識這段文字的語言。請在下方選擇語言，以使用自然語音。",
    "aviso_falha": "自然語音目前無法在此裝置上執行。將繼續使用系統語音朗讀。",
    "nao_carregou_usando_sistema": "自然語音未能在此裝置上載入。正在使用系統語音朗讀。",
    "parou_usando_sistema": "自然語音已停止。繼續使用系統語音。",
    "aparelho_lento": "此裝置產生語音的速度較慢。選擇「快速」品質可避免停頓。",
    "idioma_do_texto": "文字語言",
    "idioma_do_texto_dica": "根據文字內容辨識。如果發音不正確，可以更改。",
    "leitura_em_voz_alta": "朗讀",
    "lento_usando_sistema": "自然語音在這台裝置上太慢，將繼續使用系統語音朗讀。",
    "aviso_lento": "這台裝置無法以朗讀的速度產生自然語音，因此暫時改用系統語音。",
    "sem_memoria_usando_sistema": "這台裝置的記憶體放不下自然語音，將使用系統語音朗讀。",
    "aviso_falha_memoria": "這台裝置沒有足夠的記憶體執行自然語音。關閉其他應用程式後再試通常可以解決；在此之前會使用系統語音朗讀。",
    "copiar_detalhe": "複製詳細資訊",
    "copiado": "已複製詳細資訊。",
    "falhou_titulo": "自然語音未能在這台裝置上載入。",
    "falhou_texto": "裝置無法準備自然語音，將繼續使用系統語音朗讀。如需協助排查，請複製下方的詳細資訊並傳送給支援人員。",
    "falhou_memoria_texto": "這台裝置沒有足夠的記憶體執行自然語音。關閉其他應用程式後再試通常可以解決。",
    "tentar_de_novo": "重試",
    "tentando": "載入中…",
    "sondando": "正在檢測這台裝置的記憶體…",
    "sonda_explica": "測試會用幾秒鐘佔用自然語音將要用到的記憶體，隨後立即釋放。這樣你現在就知道結果，而不用等下載完成。",
    "aviso_aparelho_justo": "這台裝置可用於自然語音的記憶體較少，可能無法載入；若是如此，移除即可收回空間。",
    "preparando_demora": "正在準備語音，可能需要幾分鐘。",
    "incompativel_titulo": "自然語音在這台裝置上無法使用。",
    "incompativel_memoria": "記憶體不足，無法完成準備。朗讀將使用系統語音，其選項在下方。如果需要，可以關閉其他應用程式後點按「重新檢測」。",
    "incompativel_lento": "產生速度跟不上朗讀。朗讀將使用系統語音，其選項在下方。",
    "incompativel_queda": "載入過程中應用程式被關閉。朗讀將使用系統語音，其選項在下方。",
    "incompativel_falha": "在這台裝置上無法載入。朗讀將使用系統語音，其選項在下方。",
    "testar_de_novo": "重新測試",
    "remover_e_liberar": "移除並釋出 {tamanho}",
    "tela_durante_a_leitura": "閱讀時的螢幕",
    "manter_tela_ligada": "保持螢幕開啟",
    "manter_tela_ligada_dica": "開著書籍時螢幕不會自動熄滅。關閉書籍後一切恢復正常。"
  }
});