/* ============================================================
   CHINESE (SIMPLIFIED) — zh.js
   ============================================================ */
Idiomas.registrar('zh', {
  "app": {
    "nome": "Veredas Reader",
    "marcador_excluido": "书签已删除。",
    "excluir_marcador": "删除书签",
    "o_marcador_sera_removido_permanentemen": "书签将被永久删除。",
    "excluir_marcador_2": "删除书签？",
    "pagina_salva": "页面已保存",
    "anotacoes": "笔记",
    "citacoes": "引用",
    "item_excluido": "项目已删除。",
    "este_registro_sera_removido_permanente": "此条目将从书库中永久删除。",
    "configuracoes_padrao_restauradas": "已恢复默认设置。",
    "leitura_da_esquerda_para_a_direita": "从左到右阅读。",
    "leitura_da_direita_para_a_esquerda_man": "从右到左阅读（漫画）。",
    "a_pagina_inteira_passa_a_caber_na_tela": "现在整页都能在屏幕上显示。",
    "a_pagina_passa_a_ocupar_toda_a_largura": "现在页面占满整个屏幕宽度。",
    "virada_sem_animacao_ativada": "现在翻页时无动画。",
    "virada_deslizante_ativada": "滑动翻页已开启。",
    "virada_em_folha_real_ativada": "真实纸张翻页已开启。",
    "padrao_automatico_cada_formato_abre_no": "自动：每种格式按适合它的方式打开。",
    "mudando_durante_a_leitura_o_ajuste_fic": "如果在阅读时更改，该更改只对那本书生效。",
    "automatico_usa_rolagem_horizontal_para": "自动对 EPUB、MOBI、TXT、MD 和漫画使用横向翻页，对 PDF 和 DOCX 使用纵向滚动。",
    "este_livro": "这本书",
    "armazenamento_local_indisponivel_neste": "此浏览器不支持本地存储。",
    "o_aplicativo_pode_procurar_os_livros_q": "应用可以查找您设备上已有的书。",
    "vamos_montar_sua_estante": "来填满您的书架吧？",
    "sem_a_aceitacao_o_aplicativo_nao_pode": "未同意则无法使用该应用。",
    "precisamos_do_seu_aceite": "我们需要您的同意",
    "antes_de_comecar_leia_e_aceite_os_docu": "开始前，请阅读并同意以下文件。",
    "selecionar_todos": "全选",
    "limpar_selecao": "清除选择",
    "todos_parecem_ja_estar_na_sua_estante": "它们看起来都已经在您的书架上了。",
    "lendo_a_pasta_escolhida": "正在读取您选择的文件夹…",
    "procurando_livros": "正在查找书籍",
    "nao_foi_possivel_concluir_a_busca_no_d": "无法在此设备上完成搜索。",
    "tente_outra_pasta_do_aparelho": "请尝试设备上的另一个文件夹。",
    "nenhum_livro_encontrado": "未找到书籍",
    "use_o_botao_para_escolher_os_arquivos": "使用 + 按钮手动选择文件。在 Android 手机上，Chrome 通常允许选择整个文件夹。",
    "seu_navegador_nao_permite_ler_pastas": "您的浏览器无法读取文件夹",
    "busca_automatica_indisponivel": "自动搜索不可用",
    "epub_mobi_cbz_cbr_e_m4b": "EPUB、MOBI、CBZ、CBR 和 M4B",
    "termos_de_uso": "使用条款",
    "politica_de_privacidade": "隐私政策",
    "um_minuto_agora_evita_perder_o_progres": "现在一分钟，避免之后丢失进度和标记。",
    "ver_estante": "查看书架",
    "modo_juntar": "合并模式",
    "modo_substituir": "替换模式",
    "restauracao_concluida": "恢复完成",
    "tente_de_novo_com_o_arquivo_original": "请用原始文件再试一次。",
    "a_restauracao_nao_pode_ser_concluida": "无法完成恢复",
    "devolvendo_o_seu_progresso_e_as_suas_m": "正在恢复您的进度和标记...",
    "restaurar_este_backup": "恢复此备份？",
    "escolha_o_zip_salvo_pelo_veredas_ou_o": "选择 Veredas 保存的 .zip，或通过分享收到的 .txt。",
    "nao_foi_possivel_ler_este_arquivo": "无法读取此文件",
    "lendo_o_backup": "正在读取备份",
    "backup_do_veredas_reader": "Veredas Reader 备份",
    "arquivo_de_transporte_txt_contendo_os": "备份的 .txt 格式副本，内容与 ZIP 相同",
    "nao_foi_possivel_montar_o_arquivo_de_b": "无法生成备份文件。",
    "escolher_o_app": "选择应用",
    "vale_conferir_o_que_vai_no_arquivo": "值得检查文件里有什么",
    "enviar_para_outro_app": "发送到其他应用",
    "salvar_o_arquivo": "保存文件",
    "o_navegador_aqui_nao_oferece_o_compart": "这里的浏览器不提供直接分享。您可以保存文件，之后通过任意应用发送。",
    "este_aparelho_nao_abre_a_lista_de_apli": "此设备不会打开应用列表",
    "importe_pelo_menos_um_livro_antes_de_f": "制作备份前至少导入一本书。",
    "estante_vazia": "空书架",
    "nao_deu_para_copiar": "无法复制",
    "copiar_detalhes": "复制详细信息",
    "o_backup_foi_salvo_assim_mesmo": "备份仍然已保存",
    "o_aparelho_recusou_abrir_a_lista": "无法打开分享列表",
    "sem_detalhes_do_navegador": "没有浏览器的详细信息",
    "o_sistema_nao_aceitou_receber_o_arquiv": "设备系统无法接收该文件。",
    "o_navegador_considerou_a_situacao_inse": "浏览器根据自身的安全规则阻止了分享。请保存文件，然后通过您喜欢的应用发送。",
    "o_compartilhamento_so_funciona_em_ende": "分享只在安全地址上有效。此应用是从普通 http:// 地址打开的，这种情况下浏览器会阻止发送到其他应用。",
    "este_navegador_nao_conseguiu_iniciar_o": "此浏览器无法打开分享。请保存文件，然后通过您喜欢的应用发送。",
    "o_navegador_recebeu_um_arquivo_em_form": "浏览器没有打开可分享的应用列表。请再轻触一次按钮，或保存文件后通过您喜欢的应用发送。",
    "nao_foi_possivel_gerar_o_backup": "无法生成备份。",
    "reunindo_a_sua_estante": "正在收集您的书架...",
    "preparando_o_backup": "正在准备备份",
    "pronto_nada_mais_esta_esperando": "完成 — 不再有任何待处理。",
    "o_progresso_e_as_marcacoes_desses_livr": "这些书的进度和标记将被清除。如果之后导入这些文件，它们会以空白状态回来。",
    "descartar_o_que_esta_esperando": "删除等待中的数据？",
    "lembretes_de_backup_religados": "备份提醒已重新开启。",
    "sem_titulo": "无标题",
    "veredas_reader_backup_zip": "Veredas Reader - backup.zip",
    "lembretes_desligados": "提醒已关闭。",
    "manter_ligado": "保持开启",
    "desligar_assim_mesmo": "仍然关闭",
    "o_botao_de_salvar_continua_onde_sempre": "保存按钮还在老地方，备份与恢复中。",
    "o_lembrete_e_o_unico_aviso_que_existe": "提醒是唯一的通知。关闭后，您需要自己记得备份。\n\n",
    "limpar_os_dados_do_navegador_desinstal": "如果清除了浏览器数据、卸载了应用、更换了手机或设备出现故障，您的进度、高亮、引用、笔记和书签将无法恢复。\n\n",
    "a_sua_estante_existe_so_neste_aparelho": "您的书架只在这台设备上。任何服务器上都没有副本，所以我们无法帮您恢复。\n\n",
    "leia_antes_de_confirmar": "确认前请阅读",
    "desligar_os_lembretes_de_backup": "关闭备份提醒？",
    "progresso_de_leitura_restaurado_neste": "已恢复此书的阅读进度。",
    "pronto": "完成。",
    "aplicando_as_suas_preferencias": "正在应用您的偏好...",
    "atualize_o_veredas_reader_e_tente_de_n": "请更新 Veredas Reader 后再试。",
    "este_backup_foi_feito_numa_versao_mais": "此备份是用更新版本的应用生成的。",
    "este_arquivo_nao_e_um_backup_de_biblio": "此文件不是 Veredas 书库备份。",
    "o_conteudo_interno_nao_pode_ser_lido": "无法读取内部内容。",
    "o_backup_esta_corrompido": "备份已损坏。",
    "falta_o_arquivo_biblioteca_json_la_den": "里面缺少 biblioteca.json 文件。",
    "este_arquivo_nao_parece_ser_um_backup": "此文件不像 Veredas 备份。",
    "compactando": "正在压缩...",
    "para_restaurar_menu_lateral_backup_e_r": "恢复：侧边菜单 > 备份与恢复 > 恢复备份。",
    "o_veredas_devolve_sozinho_as_marcacoes": "Veredas 会自动恢复标记和您上次停下的位置。",
    "importe_os_livros_normalmente_no_aplic": "在应用中正常导入书籍：识别每个文件后，",
    "ele_nao_contem_os_arquivos_dos_livros": "它不包含书籍文件。要完整恢复，",
    "as_notas_os_marcadores_e_a_organizacao": "您的笔记、书签和书架的组织方式。",
    "este_arquivo_guarda_o_seu_progresso_de": "此文件保存您的阅读进度、高亮、引用、",
    "verificando_se_sao_partes_do_mesmo_aud": "正在检查这些是否是同一本有声书的部分...",
    "analisando_os_arquivos": "正在读取文件",
    "nao_foi_possivel_salvar_o_audiolivro": "无法保存有声书。",
    "audiolivros_grandes_podem_levar_alguns": "大有声书可能需要一点时间...",
    "salvando_na_sua_estante": "正在保存到您的书架",
    "falha_ao_processar_os_arquivos": "无法处理这些文件。",
    "falha_ao_processar_o_arquivo": "无法处理该文件。",
    "nao_foi_possivel_salvar_o_quadrinho": "无法保存漫画。",
    "quase_la": "快好了...",
    "falha_ao_processar_o_quadrinho": "无法处理该漫画。",
    "autor_desconhecido": "未知作者",
    "lendo_o_quadrinho": "正在读取漫画...",
    "nao_foi_possivel_salvar_o_livro_na_bib": "无法将书保存到书库。",
    "nao_foi_possivel_ler_o_pdf": "无法读取 PDF。",
    "lendo_o_pdf": "正在读取 PDF...",
    "se_for_um_doc_antigo_abra_no_word_e_sa": "如果是旧的 .doc，请在 Word 中打开并保存为 .docx 后再导入。",
    "este_arquivo_nao_e_um_docx_valido": "此文件不是有效的 .docx。",
    "livros_com_protecao_da_amazon_nao_pode": "带 Amazon 保护的书无法在此打开。请使用无 DRM 的副本或将书转换为 EPUB。",
    "este_arquivo_esta_protegido_por_drm": "此文件受 DRM 保护。",
    "confira_se_a_extensao_corresponde_ao_c": "请检查扩展名是否与内容匹配，或将书转换为 EPUB。",
    "este_arquivo_nao_e_um_mobi_valido": "此文件不是有效的 MOBI。",
    "nao_foi_possivel_ler_o_arquivo": "无法读取该文件。",
    "formato_nao_suportado": "不支持的格式。",
    "falha_ao_salvar_o_livro_na_biblioteca": "无法将书保存到书库。",
    "livro_importado_e_salvo_no_dispositivo": "书已导入并保存到此设备。",
    "audiolivro_importado_e_salvo_no_dispos": "有声书已导入并保存到此设备。",
    "quadrinho_importado_e_salvo_no_disposi": "漫画已导入并保存到此设备。",
    "salvando_na_sua_estante_2": "正在保存到您的书架...",
    "importando_livro": "正在导入书籍",
    "importar_mesmo_assim": "仍然导入",
    "parece_que_este_livro_ja_esta_na_estan": "这本书看起来已经在您的书架上了",
    "este_livro_ja_esta_na_estante": "这本书已经在书架上",
    "video_importado_e_salvo_no_dispositivo": "视频已导入并保存到此设备。",
    "importacao_cancelada": "已取消导入。",
    "preparando_o_arquivo": "正在准备文件",
    "importando_audiolivro": "正在导入有声书",
    "importacao_concluida": "导入完成",
    "importacao_interrompida": "导入已中断",
    "a_importacao_foi_interrompida_o_que_ja": "导入被中断；已经进来的部分仍留在您的书架上。",
    "finalizando": "正在收尾…",
    "nao_foi_possivel_ler_o_arquivo_2": "无法读取该文件",
    "importando_livros": "正在导入书籍",
    "livros_quadrinhos_documentos_audiolivr": "书籍、漫画、文档、有声书和视频",
    "series": "系列",
    "colecoes": "合集",
    "organizacao_salva": "组织方式已保存。",
    "informe_um_nome_para_o_livro_antes_de": "保存前请先给书起个名字。",
    "nome_do_livro_obrigatorio": "需要书籍名称",
    "importe_um_livro_primeiro": "请先导入一本书。",
    "citacao": "引用",
    "anotacao": "笔记",
    "citacao_2": "引用",
    "anotacao_2": "笔记",
    "uma_citacao": "一段引用",
    "uma_anotacao": "一条笔记",
    "o_marcador_sera_removido_da_biblioteca": "书签将从书库中移除，但书籍文件保持原样。",
    "marcador_de_audio": "音频书签",
    "marcador_de_video": "视频书签",
    "nao_foi_possivel_excluir_o_livro": "无法删除该书。",
    "livro_excluido_da_biblioteca": "书已从书库中删除。",
    "excluir_livro": "删除书籍",
    "isso_remove_apenas_a_copia_armazenada": "这只会删除书库保存的副本，以及进度、书签和笔记。您自己文件夹中的原始文件不会被删除。",
    "excluir_livro_2": "删除书籍？",
    "ordem_personalizada_salva": "自定义顺序已保存。",
    "ordem_manual_da_sua_estante": "您的书架，按您设定的顺序。",
    "agrupamento_alterado_para_minha_ordem": "分组已切换到我的顺序。",
    "nova_ordem_salva": "新顺序已保存。",
    "nao_foi_possivel_salvar_a_nova_ordem": "无法保存新顺序。",
    "baixar_automaticamente": "自动下载",
    "escolha_livremente_onde_o_arquivo_sera": "自由选择文件写入的位置。",
    "salvar_epub": "保存 EPUB",
    "livro_epub": "EPUB 书籍",
    "erro_desconhecido": "未知错误",
    "a_permissao_para_salvar_o_arquivo_foi": "保存文件的权限被取消。书库中没有任何更改。",
    "conversao_cancelada_o_pdf_original_per": "转换已取消。原始 PDF 留在书库中。",
    "preparando_salvamento": "正在准备保存…",
    "a_copia_do_pdf_nao_esta_disponivel_na": "书库中没有此 PDF 的副本。",
    "reconstruindo_o_livro_localmente": "正在您的设备上重建这本书。",
    "convertendo_pdf": "正在转换 PDF",
    "nao_foi_possivel_compartilhar_o_livro": "无法分享该书。",
    "o_arquivo_foi_preparado_para_voce_comp": "文件已准备好，可在其他应用中分享。",
    "livro_compartilhado": "书已分享。",
    "a_copia_deste_livro_nao_esta_disponive": "书库中没有这本书的副本。",
    "para_manter_a_politica_de_compartilham": "为遵守书库的分享政策，EPUB 和 MOBI 文件不能通过此应用分享。",
    "quadrinhos_ficam_guardados_somente_no": "漫画只保存在您的设备上，无法通过此应用分享。",
    "audiolivros_e_videos_ficam_guardados_s": "有声书和视频只保存在您的设备上，无法通过此应用分享。",
    "formato_protegido": "受保护的格式",
    "compartilhamento_indisponivel": "分享不可用",
    "concluido": "已完成",
    "ainda_nao_comecado": "尚未开始",
    "continue_lendo": "继续阅读",
    "continue_ouvindo": "继续收听",
    "continue_assistindo": "继续观看",
    "comece_por_aqui": "从这里开始",
    "comece_a_ouvir": "开始收听",
    "comece_a_assistir": "开始观看",
    "no_total": "总体",
    "para_ler": "待读",
    "sua_estante": "您的书架",
    "livros_organizados_pela_opcao_selecion": "按所选选项排列的书籍。",
    "uma_prateleira_para_cada_tipo_de_arqui": "每种文件类型一个书架。",
    "autores_agrupados_em_ordem_alfabetica": "作者按字母顺序分组。",
    "toque_para_continuar_de_onde_parou": "轻触以从上次停下的地方继续。",
    "para_ler_2": "待读",
    "lendo_agora": "正在阅读",
    "audio_e_video": "音频和视频",
    "trechos_salvos_separadamente_dos_marca": "与书签分开保存的段落。",
    "comentarios_vinculados_a_trechos_selec": "与所选段落关联的评论。",
    "paginas_salvas_para_voltar_rapidamente": "为快速返回而保存的页面。",
    "do_maior_para_o_menor_progresso_de_lei": "按阅读进度从多到少。",
    "livros_adicionados_ou_lidos_mais_recen": "最近添加或阅读的书籍。",
    "ordem_alfabetica_pelo_titulo": "按标题字母顺序。",
    "separa_em_prateleiras_de_epub_pdf_docx": "拆分为 EPUB、PDF、DOCX、有声书、视频…的书架。",
    "tipo_de_arquivo": "文件类型",
    "organiza_e_separa_os_livros_por_autor": "按作者整理和分开书籍。",
    "agrupar_por_autor": "按作者分组",
    "pressione_o_livro_e_mova_o": "长按书籍并移动。",
    "minha_ordem": "我的顺序",
    "epub_pronto": "EPUB 就绪",
    "conversao_concluida": "转换完成",
    "necessario_para_salvar_o_epub_ao_lado": "需要在原文件旁保存 EPUB",
    "escolha_a_pasta_do_pdf": "选择 PDF 的文件夹",
    "processando": "处理中…",
    "processamento_local_no_navegador": "在您的设备上、在浏览器中处理",
    "convertendo_livro": "正在转换书籍",
    "livro_em_pdf": "PDF 书籍",
    "recalculando_paginas": "正在重新计算页面...",
    "ajustando_leitura": "正在调整布局",
    "abrir_comentario": "打开评论",
    "anotacao_salva": "笔记已保存。",
    "anotacao_atualizada": "笔记已更新。",
    "escreva_uma_nota_antes_de_salvar": "保存前请先写一条笔记。",
    "nao_foi_possivel_compartilhar": "无法分享。",
    "compartilhamento_indisponivel_2": "分享不可用。",
    "trecho_copiado": "段落已复制。",
    "trecho_compartilhado": "段落已分享。",
    "citacao_salva": "引用已保存。",
    "trecho_grifado": "段落已高亮。",
    "grifo_removido": "高亮已移除。",
    "comentario_apagado": "评论已删除。",
    "remover_grifo": "移除高亮",
    "apagar_comentario": "删除评论",
    "remover_grifo_2": "移除高亮？",
    "apagar_comentario_2": "删除评论？",
    "remover_este_grifo": "移除此高亮？",
    "apagar_este_comentario": "删除此评论？",
    "sem_comentario": "无评论",
    "comentario": "评论",
    "marcador_removido_desta_pagina": "已从此页移除书签。",
    "pagina_adicionada_aos_marcadores": "页面已添加到书签。",
    "este_e_o_inicio_do_livro": "这是书的开始。",
    "esta_e_a_primeira_pagina": "这是第一页。",
    "voce_chegou_ao_fim_do_livro": "您已到达书的末尾。",
    "voce_chegou_ao_fim_do_quadrinho": "您已到达漫画的末尾。",
    "agora_em_revista_aberta_duas_paginas_l": "现在为跨页：两页并排，封面单独。",
    "leitura_horizontal_ativada_neste_livro": "本书已开启横向阅读。",
    "rolagem_vertical_ativada_neste_livro": "本书已开启纵向滚动。",
    "leitura_pagina_a_pagina_ativada_neste": "此漫画已开启逐页阅读。",
    "rolagem_continua_ativada_neste_quadrin": "此漫画已开启连续滚动。",
    "mudar_para_rolagem_vertical": "切换到纵向滚动",
    "mudar_para_leitura_horizontal": "切换到横向阅读",
    "rolagem_continua_estilo_webtoon": "连续滚动（条漫风格）",
    "voltar_para_pagina_a_pagina": "回到逐页",
    "separando_os_capitulos": "正在分离章节...",
    "lendo_o_livro": "正在读取书籍",
    "lendo_o_markdown": "正在读取 Markdown",
    "lendo_o_documento": "正在读取文档",
    "pagina_indisponivel": "页面不可用。",
    "isto_acontece_so_desta_vez": "这只是这一次。",
    "preparando_o_quadrinho": "正在准备漫画",
    "abrindo_o_quadrinho": "正在打开漫画...",
    "montando_as_paginas": "正在构建页面...",
    "nao_foi_possivel_abrir_este_livro": "无法打开这本书。",
    "abertura_cancelada": "打开已取消。",
    "o_livro_demorou_demais_para_abrir_e_fo": "书打开的时间过长，已被停止。",
    "importe_o_arquivo_novamente_para_conti": "重新导入文件以继续阅读。",
    "o_arquivo_deste_livro_nao_esta_mais_sa": "这本书的文件不再保存在您的设备上。",
    "preparando_sua_leitura": "正在准备您的书...",
    "abrindo_livro": "正在打开书籍",
    "leitura_concluida": "阅读完成。",
    "a_voz_foi_interrompida_pelo_navegador": "浏览器中断了语音。",
    "nao_foi_possivel_preparar_este_trecho": "无法为音频准备此段落。",
    "a_leitura_em_voz_alta_nao_e_suportada": "此浏览器不支持朗读。",
    "pausar_leitura": "暂停朗读",
    "em_pausa": "已暂停",
    "leitura_em_voz_alta_nao_disponivel_nes": "此浏览器中朗读不可用",
    "nome_do_marcador": "书签名称",
    "o_marcador_sera_removido_deste_audioli": "书签将从此有声书中移除。",
    "nao_foi_possivel_salvar_o_marcador": "无法保存书签。",
    "ja_existe_um_marcador_neste_ponto": "此位置已有书签。",
    "timer_de_sono_encerrado": "睡眠定时器已结束。",
    "fim_do_cap": "章末",
    "timer_desativado": "定时器已关闭。",
    "o_audio_vai_pausar_ao_fim_do_capitulo": "音频将在章节结束时暂停。",
    "este_audiolivro_nao_tem_capitulos": "此有声书没有章节。",
    "ao_fim_do_capitulo": "在章节结束时",
    "desativar_timer": "关闭定时器",
    "mais_10_minutos_no_timer": "定时器再加 10 分钟。",
    "somar_10_minutos": "加 10 分钟",
    "pausa_ao_fim_do_capitulo": "在章节结束时暂停",
    "no_livro_todo": "在整本书中",
    "video": "视频",
    "audiolivro_concluido": "有声书已完成。",
    "video_concluido": "视频已完成。",
    "video_2": "视频",
    "audio": "音频",
    "toque_em_reproduzir_para_comecar": "轻触播放以开始。",
    "falha_ao_carregar_o_audio": "无法加载音频。",
    "exclua_o_da_biblioteca_e_importe_o_arq": "从书库中删除并重新导入文件。",
    "os_nomes_dos_arquivos_seguem_uma_seque": "文件名按顺序，所以看起来像同一本有声书的章节。",
    "os_arquivos_tem_o_mesmo_album_nas_etiq": "文件在标签中有相同的专辑，所以看起来像同一本有声书的章节。",
    "libere_espaco_ou_exclua_livros_da_bibl": "腾出空间或从书库中删除书籍，然后再试一次。",
    "o_armazenamento_do_aparelho_esta_cheio": "您设备的存储空间已满。",
    "preparando_a_capa": "正在准备封面...",
    "remova_esse_arquivo_da_selecao_e_tente": "把那个文件从选择中移除，然后重试。",
    "sequencia": "顺序",
    "o_arquivo_pode_estar_incompleto_tente": "文件可能不完整。请重新下载。",
    "conferindo_se_o_audio_pode_ser_reprodu": "正在检查音频是否可以播放...",
    "conferindo_se_o_video_pode_ser_reprodu": "正在检查视频是否可以播放...",
    "lendo_titulo_capitulos_e_capa": "正在读取标题、章节和封面...",
    "o_arquivo_pode_estar_corrompido_ou_usa": "文件可能已损坏，或采用了浏览器无法播放的音频格式。请尝试将其转换为 MP3 或 M4B（AAC）。",
    "o_arquivo_pode_estar_corrompido_ou_usa_2": "文件可能已损坏，或采用了浏览器无法播放的视频格式。请尝试将其转换为使用 H.264 视频和 AAC 音频的 MP4。",
    "converta_o_audiolivro_para_m4b_com_aud": "将有声书转换为带 AAC 音频的 M4B（或 MP3），然后重新导入。",
    "converta_o_video_para_mp4_com_audio_aa": "将视频转换为带 AAC 音频和 H.264 视频的 MP4，然后重新导入。",
    "o_navegador_nao_reproduz_o_formato_de": "浏览器无法播放此文件的音频格式。",
    "arquivos_com_protecao_nao_podem_ser_re": "受保护的文件无法在此播放。请使用无 DRM 的副本。",
    "nao_ha_espaco_suficiente_no_aparelho_p": "您的设备上没有足够的空间容纳此有声书。",
    "confira_se_a_extensao_corresponde_ao_c_2": "请检查扩展名是否与内容匹配，或将音频转换为 MP3 或 M4B（AAC）。",
    "imagem_invalida": "无效图像",
    "imagem_demorou_demais": "图像加载时间过长",
    "imagem_vazia": "空图像",
    "inicio": "开始",
    "mp4_moov_nao_encontrado": "该视频似乎不完整或已损坏。",
    "pagina": "页",
    "esta_pagina_nao_esta_disponivel": "此页不可用。",
    "esta_pagina_nao_pode_ser_descompactada": "无法解压此页。",
    "quadrinho_fechado": "漫画已关闭。",
    "ele_pode_estar_incompleto_dividido_em": "它可能不完整、分成多个部分，或是一种应用不认识的 RAR 变体。转换成 CBZ 通常能解决。",
    "remova_a_senha_do_arquivo_e_importe_de": "移除文件密码后重新导入。",
    "nao_foi_possivel_ler_este_arquivo_de_q": "无法读取此漫画文件。",
    "este_quadrinho_esta_protegido_por_senh": "此漫画受密码保护。",
    "lendo_o_indice_do_quadrinho": "正在读取漫画的目录...",
    "o_arquivo_pode_ser_grande_demais_para": "文件对此设备的内存来说可能太大。将漫画分成更小的部分通常能解决。",
    "nao_foi_possivel_abrir_este_quadrinho": "无法打开此漫画。",
    "lendo_o_arquivo": "正在读取文件...",
    "preparando_o_leitor_de_cbr": "正在准备 CBR 阅读器...",
    "o_arquivo_pode_estar_incompleto_proteg": "文件可能不完整、受密码保护或已损坏。",
    "nao_foi_possivel_ler_este_quadrinho": "无法读取此漫画。",
    "o_arquivo_precisa_conter_imagens_jpg_p": "文件需要包含图像（JPG、PNG、WEBP 或 GIF）。",
    "nao_encontramos_paginas_dentro_deste_q": "此漫画中没有找到页面。",
    "nao_ha_espaco_suficiente_no_aparelho_p_2": "您的设备上没有足够的空间容纳此漫画。",
    "cabecalho_de_item_invalido": "文件的一部分已损坏。",
    "a_pasta_vendor_libarchive_precisa_esta": "缺少打开此漫画所需的应用组件。请将其转换为 CBZ，或重新安装应用。",
    "o_leitor_de_cbr_nao_foi_encontrado": "未找到 CBR 阅读器。",
    "converta_o_quadrinho_para_cbz_zip_e_im": "将漫画转换为 CBZ（ZIP）并重新导入。",
    "este_navegador_nao_consegue_abrir_arqu": "此浏览器无法打开 CBR 文件。",
    "convertendo_o_markdown": "正在转换 Markdown",
    "lendo_o_texto": "正在读取文本",
    "pdf_indisponivel": "PDF 不可用。",
    "epub_invalido_nenhum_capitulo_no_spine": "此 EPUB 已损坏：找不到书的章节。",
    "livro_sem_titulo": "无标题书籍",
    "epub_invalido_arquivo_opf_nao_encontra": "此 EPUB 不完整或已损坏，无法打开。",
    "epub_invalido_container_xml_nao_encont": "此 EPUB 不完整或已损坏，无法打开。",
    "organizando_o_texto": "正在排版文本",
    "descompactando_o_livro": "正在解压书籍",
    "nao_encontramos_conteudo_para_exibir_n": "在此文件中没有找到可显示的内容。",
    "livro_sem_texto_legivel": "没有可读文本的书籍",
    "o_arquivo_pode_estar_corrompido_tente": "文件可能已损坏。请尝试将其转换为 EPUB。",
    "nao_foi_possivel_extrair_o_texto_deste": "无法从此 MOBI 中提取文本。",
    "nenhum_registro_de_conteudo_foi_encont": "在此文件中找不到书的正文。",
    "arquivo_mobi_sem_texto": "无文本的 MOBI 文件。",
    "o_dicionario_de_compressao_esta_vazio": "此 MOBI 的部分内容缺失。",
    "arquivo_mobi_incompleto": "不完整的 MOBI 文件。",
    "as_tabelas_de_compressao_nao_foram_enc": "此 MOBI 的部分内容缺失。",
    "converta_o_arquivo_para_epub_em_um_pro": "用 Calibre 之类的程序将文件转换为 EPUB 并重新导入。",
    "compressao_mobi_nao_reconhecida": "此 MOBI 使用了本应用无法识别的内部格式。",
    "o_cabecalho_do_livro_nao_pode_ser_lido": "无法读取书的头部。",
    "arquivo_mobi_corrompido": "损坏的 MOBI 文件。",
    "a_lista_interna_de_registros_esta_inco": "文件不完整。请尝试重新下载或重新转换。",
    "o_download_parece_ter_sido_interrompid": "下载看起来被中断了。请重新下载文件。",
    "tabela_de_compressao_mobi_corrompida": "此 MOBI 文件的一部分已损坏。",
    "tabela_de_compressao_mobi_incompleta": "此 MOBI 文件不完整。",
    "tabela_de_compressao_mobi_invalida": "此 MOBI 文件的一部分已损坏。",
    "este_arquivo_docx_nao_tem_conteudo_de": "此 .docx 文件没有可显示的文本内容。",
    "documento_sem_texto": "无文本的文档",
    "o_arquivo_pode_estar_corrompido_proteg": "文件可能已损坏、受密码保护，或是旧的 .doc。请另存为 .docx 并再次导入。",
    "nao_foi_possivel_ler_este_arquivo_docx": "无法读取此 DOCX 文件。",
    "convertendo_o_documento": "正在转换文档",
    "conecte_se_a_internet_uma_vez_para_bai": "联网一次以下载组件，然后再次打开书。",
    "o_conversor_de_docx_nao_carregou": "DOCX 转换器未加载。",
    "video_mp4": "视频（MP4）",
    "audiolivro_m4b": "有声书（M4B）",
    "audiolivro_mp3": "有声书（MP3）",
    "quadrinho_cbt": "漫画（CBT）",
    "quadrinho_cb7": "漫画（CB7）",
    "quadrinho_cbr": "漫画（CBR）",
    "quadrinho_cbz": "漫画（CBZ）",
    "markdown_md": "Markdown（MD）",
    "texto_txt": "文本（TXT）",
    "word_docx": "Word（DOCX）",
    "gravacao_cancelada": "保存已取消。",
    "o_arquivo_esta_vindo_do_armazenamento": "文件正从云存储下载到您的设备。",
    "baixando_o_arquivo": "正在下载文件",
    "cancelando": "正在取消...",
    "use_grifar_citacao_anotar_ou_marcador": "阅读时使用高亮、引用、笔记或书签。",
    "nenhuma_marcacao_ainda": "还没有标记",
    "trecho_original": "原始段落",
    "procurar_meus_livros": "查找我的书",
    "a_busca_fica_sempre_disponivel_no_menu": "搜索始终在侧边菜单的系统下。",
    "da_para_fazer_depois": "可以稍后做",
    "nada_entra_na_estante_sem_a_sua_confir": "没有您的确认，什么都不会进入书架：您看到列表并勾选要导入的。",
    "voce_revisa_antes": "您先审阅",
    "escolha_uma_pasta_downloads_e_um_bom_c": "选择一个文件夹（Downloads 是个好的开始），应用会搜索它和所有子文件夹。",
    "busca_por_epub_mobi_cbz_cbr_e_m4b": "搜索 EPUB、MOBI、CBZ、CBR 和 M4B",
    "voltar_e_revisar": "返回并检查",
    "ler_os_termos": "阅读条款",
    "ler_a_politica": "阅读政策",
    "os_dois_documentos_ficam_sempre_dispon": "两份文件始终在侧边菜单的关于下。",
    "leia_com_calma": "慢慢读",
    "a_politica_e_os_termos_explicam_como_o": "政策和条款说明了应用如何保存您的书，以及您可以如何使用它们。要使用书库，需要您同意这些内容。",
    "nada_acontece_sem_o_aceite": "开始使用前，请先接受条款",
    "aceitar_e_continuar": "同意并继续",
    "nao_aceito": "我不同意",
    "termos_de_uso_2": "使用条款",
    "politica_de_privacidade_2": "隐私政策",
    "o_aplicativo_so_acessa_os_arquivos_e_p": "应用只会在您选择时，访问您所选的文件和文件夹。",
    "voce_no_controle": "由您掌控",
    "depois_de_importar_um_livro_voce_le_se": "导入书后，您无需联网即可阅读。",
    "funciona_offline": "离线可用",
    "livros_marcacoes_e_progresso_sao_guard": "书籍、标记和进度保存在您的设备上。不会发送到我们的服务器。",
    "tudo_fica_no_seu_aparelho": "一切都留在您的设备上",
    "escolha_o_que_deseja_adicionar_a_bibli": "选择要添加到书库的内容。与书架上已有的相同文件会被自动跳过。",
    "voce_pode_tentar_outra_pasta_ou_import": "您可以尝试另一个文件夹，或用 + 按钮导入文件。",
    "a_leitura_acontece_so_no_seu_dispositi": "读取只在您的设备上进行。",
    "voce_escolhe_a_pasta": "您选择文件夹",
    "tema_tipografia_margens_modo_de_virada": "主题、字体、边距、翻页方式和音频设置。",
    "restaurar_minhas_preferencias": "恢复我的偏好",
    "o_backup_manda_as_marcacoes_atuais_dos": "备份优先。文件中任何书的当前标记将被备份中的替换。",
    "nada_e_apagado_as_marcacoes_dos_dois_l": "什么都不会被删除。两侧的标记相加，更新的进度胜出。",
    "o_que_fazer_com_o_que_ja_esta_na_estan": "对书架上已有的内容怎么办",
    "grifos_citacoes_e_notas": "高亮、引用和笔记",
    "preparando_o_arquivo_2": "正在准备文件...",
    "os_livros_em_si_nem_as_capas_por_isso": "既不包含书籍文件本身，也不包含封面——所以这个文件只有几 KB。接收的人需要有这些书籍文件，标记才能回到原来的位置；封面会在导入书籍时自动重新出现。",
    "nao_vai_no_arquivo": "不在文件中",
    "o_seu_progresso_de_leitura_os_grifos_a": "您的阅读进度、高亮、引用、笔记、书签和书架的组织方式 — 状态、收藏、合集、系列和标签。",
    "vai_no_arquivo": "在文件中",
    "descartar_o_que_esta_esperando_2": "删除等待中的数据",
    "esperando_o_arquivo": "等待文件",
    "avisar_quando_fizer_tempo_sem_backup": "很久没备份时提醒我",
    "livros_que_ainda_nao_estiverem_na_esta": "还不在书架上的书会先保留等待：导入它们的文件后，标记会自动恢复。",
    "restaurar_backup": "恢复备份",
    "salvar_backup": "保存备份",
    "ainda_nao_ha_itens": "这里还没有内容",
    "arraste_um_livro_para_outra_posicao_na": "把书拖到书架上的其他位置以保存您自己的顺序。此手动顺序会优先于按作者分组。",
    "separe_por_virgulas": "用逗号分隔",
    "ex_estudos_ficcao": "例如 学习、小说...",
    "pasta_estante": "文件夹 / 书架",
    "ex_trilogia": "例如 三部曲...",
    "serie": "系列",
    "aparece_em_favoritos": "显示在收藏中。",
    "nome_do_livro": "书籍名称",
    "nenhum_registro_ainda": "还没有记录",
    "no_leitor_toque_no_icone_de_marcador_p": "在阅读器中，轻触书签图标保存页面。",
    "nenhum_marcador_ainda": "还没有书签",
    "a_gravacao_e_independente_da_localizac": "保存与 PDF 所在位置无关，不会更改原始文件。",
    "o_pdf_original_nao_precisa_estar_nessa": "原始 PDF 不必在那个文件夹中",
    "excluir_da_biblioteca": "从书库中删除",
    "adicionar_livro": "添加书籍",
    "adicione_livros_e_acompanhe_o_que_esta": "添加书籍，追踪什么在等待、什么在进行以及您走了多远。",
    "tudo_pronto_para_a_proxima_leitura": "下次阅读的一切都准备好了。",
    "sua_biblioteca": "您的书库",
    "arraste_um_livro_para_reposiciona_lo_a": "拖动书籍以移动它：书架切换到我的顺序并保持顺序。",
    "importe_um_livro_ou_ajuste_seus_filtro": "导入一本书，或调整您的过滤器。",
    "nada_por_aqui_ainda": "这里还没有内容",
    "toque_em_e_escolha_arquivos_mp3_m4b_ou": "轻触 + 并选择 MP3、M4B 或 MP4 文件。多个章节的 MP3 可以变成一本有声书。",
    "nada_para_ouvir_ou_assistir_ainda": "还没有可收听或观看的内容",
    "o_pdf_original_permanece_intacto_na_pa": "原始 PDF 原封不动地留在您的文件夹中。",
    "paginas_como_imagem": "以图像呈现的页面",
    "paginas_do_pdf": "PDF 页面",
    "em_navegadores_sem_suporte_a_acesso_di": "在不支持直接访问文件系统的浏览器中，EPUB 会被下载。",
    "essa_permissao_e_dada_somente_a_esta_a": "该权限只授予此应用，并防止原始文件被更改。",
    "selecione_a_pasta_que_contem_o_pdf": "选择包含 PDF 的文件夹",
    "preparando": "准备中…",
    "o_arquivo_esta_sendo_lido_e_reconstrui": "文件正在被读取和重建。大书可能需要一点时间。",
    "revistas_apostilas_complexas_formulari": "杂志、复杂教材、表单、表格很多的文档或扫描的 PDF 可能会丢失部分原始布局。",
    "funcionalidade_indicada_apenas_para_li": "仅适用于书籍的功能",
    "o_epub_e_melhor_para_livros_com_texto": "EPUB 更适合有可选文本的书籍，因为它允许调整字体、大小、边距和阅读方式。",
    "trecho_selecionado": "所选段落",
    "trecho_comentado": "带评论的段落",
    "aplicando_zoom": "正在缩放...",
    "nao_foi_possivel_carregar_esta_pagina": "无法加载此页面。",
    "nomear_marcador": "命名书签",
    "toque_em_marcar_agora_para_guardar_est": "轻触“现在标记”以保存此位置，随时回来。",
    "timer_ativo": "定时器已开启",
    "trecho_ausente_ou_corrompido_no_arquiv": "[原始文件中段落缺失或损坏]",
    "novos_livros_vao_abrir_em_leitura_v": "新书将以 {v} 阅读方式打开。",
    "leitura_efetivo_aplicada_a_este_livro": "{efetivo} 阅读已应用于此书。",
    "automatico_neste_livro_leitura_efetivo": "本书中自动：{efetivo} 阅读。",
    "agora_esta_em_efetivo_no_automatico_fo": "现在设置为 {efetivo}；在自动模式下，{format} 以 {padrao} 打开。",
    "esta_escolha_vale_so_para_v_cada_livro": "此选择仅适用于“{v}”。每本书保留自己的滚动方向。",
    "novos_ainda_nao_estao_na_sua_estante": "{novos} 还不在您的书架上。",
    "escolha_uma_pasta_para_procurar_label": "选择文件夹以查找 {label}。",
    "subtitle_versao_build": "{subtitle} · 版本 {BUILD}",
    "nao_foi_possivel_ler_path_usando_o_tex": "无法读取 {path}；使用内置文本。",
    "seu_ultimo_backup_foi_ha_dias_dias": "您上次备份是在 {dias} 天前",
    "aguardando_livro_s_do_backup_ainda_nao": {
      "one": "备份中有 {aguardando} 本书还不在这里。它的进度和标记已保留：导入文件后，一切都会自动回到原位。",
      "other": "备份中有 {aguardando} 本书还不在这里。它们的进度和标记已保留：导入每个文件后，一切都会自动回到原位。"
    },
    "atualizados_livro_s_da_sua_estante_for": {
      "one": "书架上的 {atualizados} 本书已更新。",
      "other": "书架上的 {atualizados} 本书已更新。"
    },
    "criado_em_quando": "创建于 {quando}",
    "backup_pronto_livros_livro_s_e_marcaco": "备份就绪：{livros} 本书和 {marcacoes} 个标记。",
    "endereco_seguro_seguro": "安全地址：{seguro}",
    "progresso_e_marcas_marcacao_oes_restau": {
      "one": "已恢复此书的进度和 {marcas} 个标记。",
      "other": "已恢复此书的进度和 {marcas} 个标记。"
    },
    "restaurando_v_de_length": "正在恢复（{v} / {length}）...",
    "livros_livro_s_marcacoes_marcacao_oes": "{livros} 本书 · {marcacoes} 个标记",
    "criado_em_v": "创建于 {v}",
    "reunindo_a_sua_estante_v_de_length": "正在收集您的书架（{v} / {length}）...",
    "titulo_ja_foi_importado_antes_e_contin": "“{titulo}”之前已导入，仍在您的书库中。未生成新副本。",
    "length_arquivos_de_audio": "{length} 个音频文件...",
    "falhas_arquivo_s_nao_puderam_ser_lidos": {
      "one": "{falhas} 个文件无法读取。",
      "other": "{falhas} 个文件无法读取。"
    },
    "repetidos_ja_estavam_na_biblioteca_e_f": "{repetidos} 已在书库中，已跳过。",
    "importados_livro_s_adicionado_s_a_esta": {
      "one": "{importados} 本书已添加到您的书架。",
      "other": "{importados} 本书已添加到您的书架。"
    },
    "epub_salvo_em_filename": "EPUB 已保存到 {fileName}。",
    "falha_ao_converter_o_pdf_v": "转换 PDF 失败：{v}",
    "pagina_page_de_totalpages": "第 {page} 页，共 {totalPages} 页",
    "totalpages_paginas": {
      "one": "{totalPages} 页",
      "other": "{totalPages} 页"
    },
    "length_resultado_s_para_search": {
      "one": "“{search}”的 {length} 个结果",
      "other": "“{search}”的 {length} 个结果"
    },
    "capitulo_v": "第 {v} 章",
    "organizando_capitulo_v_de_totalchapter": "正在排版第 {v} / {totalChapters} 章",
    "pagina_v": "第 {v} 页",
    "paginas_v_v2": "第 {v}–{v2} 页",
    "length_pagina_s_prontas": {
      "one": "{length} 页就绪",
      "other": "{length} 页就绪"
    },
    "montando_as_paginas_pagessofar_prontas": "正在构建页面 — 已完成 {pagesSoFar}",
    "lendo_pagina_v_de_length": "正在读取第 {v} / {length} 页",
    "marcador_salvo_em_t": "书签已保存于 {t}。",
    "o_audio_vai_pausar_em_minutes_minutos": "音频将在 {minutes} 分钟后暂停。",
    "length_capitulos_toque_para_ir_direto": "{length} 章 · 轻触直接前往。",
    "narrado_por_narrator": "由 {narrator} 朗读",
    "velocidade_de_reproducao_rate": "播放速度：{rate}",
    "avancar_f_segundos": "快进 {f} 秒",
    "nao_foi_possivel_abrir_este_v": "无法打开此 {v}。",
    "nao_foi_possivel_ler_o_arquivo_de_v": "无法读取 {v} 文件。",
    "o_v_esta_danificado_neste_ponto": "{v} 在此处已损坏。",
    "o_navegador_nao_consegue_reproduzir_es": "浏览器无法播放此 {v} 文件。",
    "nao_foi_possivel_reproduzir_este_v": "无法播放此 {v}。",
    "os_dados_deste_noun_estao_incompletos": "此 {noun} 的数据不完整。",
    "importe_o_arquivo_novamente_para_conti_2": "重新导入文件以继续 {v}。",
    "o_arquivo_deste_noun_nao_esta_mais_sal": "此 {noun} 的文件不再保存在您的设备上。",
    "nao_foi_possivel_descobrir_a_duracao_d": "无法确定“{name}”的长度。",
    "lendo_faixa_v_de_length": "正在读取第 {v} / {length} 个音轨...",
    "nao_foi_possivel_descobrir_a_duracao_d_2": "无法确定此 {v} 的长度。",
    "este_format_nao_pode_ser_reproduzido_n": "此 {format} 无法在此浏览器中播放。",
    "este_format_esta_protegido_por_drm": "此 {format} 受 DRM 保护。",
    "o_arquivo_tem_bytes_e_restam_cerca_de": "文件为 {bytes}，还剩大约 {v}。请腾出空间或从书库中删除书籍。",
    "este_arquivo_nao_e_um_format_valido": "此文件不是有效的 {format}。",
    "preparando_as_paginas_vistas_de_total": "正在准备页面（{vistas} / {total}）...",
    "preparando_total_pagina_s": {
      "one": "正在准备 {total} 页...",
      "other": "正在准备 {total} 页..."
    },
    "preparando_as_paginas_v_de_total": "正在准备页面（{v} / {total}）...",
    "ele_ocupa_cerca_de_bytes_e_restam_por": "它约占 {bytes}，还剩大约 {v}。请腾出空间或从书库中删除书籍。",
    "envio_direto_exige_endereco_seguro": "此页面不是通过安全地址打开的，因此无法直接发送到其他应用。请保存文件，然后通过您喜欢的应用发送。",
    "na_estante": "在书架上",
    "nao_foi_possivel_montar_o_arquivo": "无法生成文件。",
    "este_navegador_nao_oferece_o_envio_dir": "此浏览器不提供直接发送到其他应用。请保存文件并通过您喜欢的应用附加。",
    "voce_ainda_nao_fez_nenhum_backup": "您还没有做任何备份。",
    "converter_para_epub": "转换为 EPUB",
    "esta_pagina_nao_pode_ser_exibida": "无法显示此页面。",
    "na_ordem_em_que_serao_tocados": "按播放顺序",
    "este_capitulo_nao_pode_ser_exibido": "无法显示此章节。",
    "livro": "书",
    "restantes": " 剩余",
    "como_seus_dados_sao_tratados": "您的数据如何处理",
    "condicoes_de_uso_do_aplicativo": "应用的使用条件",
    "audiolivro": "有声书",
    "sobre_o_aplicativo": "关于应用",
    "o_que_e_o_veredas_reader": "Veredas Reader 是什么",
    "o_aparelho_recusou_o_tipo_do_arquivo": "（此设备不支持分享这种类型的文件）",
    "livros": "本",
    "lendo": "在读",
    "lidos": "已读完",
    "compartilhar_livro": "分享书籍",
    "n_livros": {
      "one": "{n} 本书",
      "other": "{n} 本书"
    },
    "livros_unidade": {
      "one": "本",
      "other": "本"
    },
    "uma_faixa_discreta_depois_de_n_dias": "连续 {n} 天未备份时，书架上会显示一条不显眼的提示。它不会打断您的阅读。",
    "scanned_arquivos_verificados_livros_enc": "已检查 {scanned} 个文件 · 发现 {encontrados} 本书",
    "v_de_total": "{v} / {total}",
    "voltar_n_segundos": "后退 {n} 秒",
    "cancelado": "已取消",
    "arquivo": "文件",
    "outro": "其他",
    "outros": "其他",
    "audiolivro_2": "有声书",
    "pausar": "暂停",
    "marcador": "书签",
    "leitura": "阅读",
    "grifo": "高亮",
    "editar": "编辑",
    "apagar": "删除",
    "concluir": "完成",
    "recentes": "最近",
    "progresso": "进度",
    "entendi": "明白了",
    "aviso": "通知",
    "descartar": "删除",
    "copiado": "已复制",
    "restaurar": "恢复",
    "restaurando": "恢复中",
    "excluir": "删除",
    "grifos": "高亮",
    "arquivo_vazio": "空文件。",
    "e_mais_n_arquivos": {
      "one": "以及另外 {n} 个文件，按播放顺序",
      "other": "以及另外 {n} 个文件，按播放顺序"
    },
    "n_arquivos_mp3": {
      "one": "{n} 个 MP3 文件",
      "other": "{n} 个 MP3 文件"
    },
    "pct_restam": "{pct}% · 剩余 {tempo}",
    "n_minutos": {
      "one": "{n} 分钟",
      "other": "{n} 分钟"
    },
    "ir_para_tempo": "跳到 {tempo}",
    "nomear": "命名",
    "parte_n": "第 {n} 部分",
    "carregando_pagina_n": "正在加载第 {n} 页...",
    "selecionar_pasta_e_continuar": "选择文件夹并继续",
    "ler_agora": "立即阅读",
    "agrupamento_v": "分组：{v}",
    "tempo_restante": "剩余 {tempo}",
    "abrir_titulo": "打开 {titulo}",
    "continuar_lendo_titulo": "继续阅读 {titulo}",
    "continuar_ouvindo_titulo": "继续收听 {titulo}",
    "continuar_assistindo_titulo": "继续观看 {titulo}",
    "lido": "已读",
    "pausado": "已暂停",
    "status": "状态",
    "favorito": "收藏",
    "escolher_local": "选择位置",
    "epub_baixado_como": "EPUB 已下载为 {nome}。",
    "ouvir_a_partir_de": "从 {tempo} 开始收听",
    "assistir_a_partir_de": "从 {tempo} 开始观看",
    "pagina_n_minuscula": "第 {n} 页",
    "selecione_trecho_para_criar": "阅读时选中一段文字即可创建{oque}。",
    "excluir_oque_pergunta": "删除{oque}？",
    "excluir_oque": "删除{oque}",
    "excluir_item_pergunta": "删除此项？",
    "use_organizar_para_criar": "在书籍上使用“{botao}”来创建{oque}。",
    "n_arquivos_processados": {
      "one": "已处理 {n} 个文件",
      "other": "已处理 {n} 个文件"
    },
    "voce_ja_tem_titulo_de_autor": "书库中已有 {autor} 的《{titulo}》，但文件不同。仍要导入吗？",
    "voce_ja_tem_titulo": "书库中已有《{titulo}》，但文件不同。仍要导入吗？",
    "marcadores_unidade": {
      "one": "书签",
      "other": "书签"
    },
    "ultimo_backup_em": "上次备份：<strong>{data}</strong>",
    "guardar": "保存",
    "lembretes": "提醒",
    "juntar": "合并",
    "recomendado": "推荐",
    "substituir": "替换",
    "n_capas_recuperadas": {
      "one": "已恢复 {n} 个封面。",
      "other": "已恢复 {n} 个封面。"
    },
    "nao_encontramos_arquivos_tipo": "此文件夹中没有找到 {tipo} 文件。",
    "tentar_outra_pasta": "换个文件夹",
    "n_livros_encontrados": {
      "one": "找到 {n} 本书",
      "other": "找到 {n} 本书"
    },
    "n_de_total_selecionados": {
      "one": "已选择 {n}/{total}",
      "other": "已选择 {n}/{total}"
    },
    "importar": "导入",
    "importar_n": "导入 {n} 项",
    "aceite_frase": "我已阅读并同意 Veredas Reader 的{politica}和{termos}。",
    "pdf_preservado": "原始 PDF <strong>不会从您的文件夹中删除</strong>。EPUB 成功保存后，只会从书库中移除这个 PDF 的副本。",
    "gravar_epub_mesma_pasta": "要将 EPUB 保存<strong>在与 PDF 相同的文件夹中</strong>，浏览器需要访问该文件夹的权限。",
    "epub_pronto_qualquer_pasta": "EPUB 已转换完成。现在您可以选择<strong>计算机上的任意文件夹</strong>来保存文件。",
    "backup_explicacao": "原始备份是 ZIP 或 TXT 文件。在另一台设备上收到后，请通过<strong>恢复备份</strong>导入，Veredas 会识别内容并正常恢复。文件保存您的进度、高亮、引用、笔记、书签和书架的整理方式——<strong>不包括书籍本身</strong>，也不包括封面。",
    "lembretes_desligados_frase": "提醒已<strong>关闭</strong>。请记得不时备份一下。",
    "backup_salvo_nos_downloads": "<strong>备份文件已保存到此设备</strong>的下载文件夹中。可以立即发送：打开 WhatsApp、邮件、Drive 或任何您喜欢的应用，点击附件并选择文件。",
    "arquivo_pronto_tamanho": "文件已就绪 — <strong>{tamanho}</strong>",
    "scan_intro_frase": "应用可以在您设备的一个文件夹（包括子文件夹）中查找 <strong>EPUB</strong> 和 <strong>MOBI</strong> 格式的书籍、<strong>CBZ</strong> 和 <strong>CBR</strong> 格式的漫画，以及 <strong>M4B</strong> 格式的有声书。",
    "scan_intro_auto_frase": "为了快速充实书架，应用可以在您设备的一个文件夹（包括子文件夹）中查找 <strong>EPUB</strong> 和 <strong>MOBI</strong> 格式的书籍、<strong>CBZ</strong> 和 <strong>CBR</strong> 格式的漫画，以及 <strong>M4B</strong> 格式的有声书。",
    "n_livros_aguardando": {
      "one": "<strong>{n} 本书</strong>的进度和标记已保留，正在等待再次导入。",
      "other": "<strong>{n} 本书</strong>的进度和标记已保留，正在等待再次导入。"
    },
    "fora_da_busca_titulo": "我们不会自动导入 PDF、TXT、DOCX（Word）、MD、MP3 和 MP4 文件",
    "fora_da_busca_texto": "这些格式适用于各种文档，而不只是书籍。不自动导入它们，可以让书架保持整洁。<strong>您可以通过 + 按钮逐个手动导入。</strong>"
  },
  "ui": {
    "sua_biblioteca_local": "您的本地书库",
    "biblioteca": "书库",
    "organizacao": "整理",
    "minhas_marcacoes": "我的标记",
    "sistema": "系统",
    "sua_biblioteca": "您的书库",
    "toque_em_um_livro_para_comecar_a_ler": "轻触一本书开始阅读。",
    "agrupar": "分组",
    "sua_estante_nao_tem_copia_de_seguranca": "您的书架没有备份",
    "se_este_aparelho_se_perder_o_progresso": "如果这台设备出现问题，您的进度和标记可能会丢失。",
    "agora_nao": "以后再说",
    "nao_avisar_mais": "不再提醒",
    "carregando": "加载中...",
    "estante": "书架",
    "lendo": "在读",
    "favoritos": "收藏",
    "marcas": "标记",
    "mais": "更多",
    "neste_capitulo": "本章",
    "velocidade": "速度",
    "timer": "定时器",
    "marcar": "标记",
    "marcadores": "书签",
    "personalizar_leitura": "自定义阅读",
    "as_preferencias_ficam_salvas_para_as_p": "偏好会为将来的阅读保存。",
    "tema": "主题",
    "claro": "浅色",
    "sepia": "棕褐",
    "escuro": "深色",
    "oceano": "海洋",
    "tipografia": "字体",
    "texto": "文本",
    "tamanho": "大小",
    "espacamento": "行距",
    "margens": "边距",
    "cores_personalizadas_opcional": "自定义颜色（可选）",
    "fundo": "背景",
    "fonte": "文字颜色",
    "brilho": "亮度",
    "orientacao": "方向",
    "auto": "自动",
    "retrato": "竖屏",
    "paisagem": "横屏",
    "modo_de_leitura": "阅读方式",
    "automatico": "自动",
    "horizontal": "横向",
    "vertical": "纵向",
    "automatico_usa_rolagem_horizontal_para": "自动对 EPUB、MOBI、TXT 和 MD 使用横向翻页，对 PDF 和 DOCX 使用纵向滚动。如果在阅读时更改，该更改只对那本书生效。",
    "quadrinhos": "漫画",
    "como_a_pagina_aparece": "页面如何适配",
    "pagina_inteira": "整页",
    "largura_da_tela": "屏幕宽度",
    "sentido_da_leitura": "阅读方向",
    "normal": "正常 →",
    "manga": "← 从右到左",
    "revista_aberta_na_horizontal": "横向的跨页",
    "com_o_aparelho_deitado_mostra_duas_pag": "横过来时显示两页并排 — 封面单独，就像真实漫画打开的样子。",
    "normal_vira_da_esquerda_para_a_direita": "正常模式从左往右翻。从右到左模式会反转所有操作：滑动方向、边缘轻触，以及跨页中两页的顺序。",
    "gire_o_aparelho_para_a_horizontal_para": "把设备横过来以一次看到两页。",
    "dois_toques_ampliam_no_ponto_tocado_co": "双击放大您轻触的位置；放大后，拖动以在页面上移动。双指捏合也可以。",
    "o_botao_de_rolagem_no_topo_do_leitor_a": "阅读器顶部的滚动按钮在逐页和连续滚动（条漫风格）之间切换。在连续滚动中页面相互连接，放大使页面变宽：您通过横向滚动在页面上移动。",
    "virada_de_pagina": "翻页",
    "folha_real": "真实纸张",
    "deslizar": "滑动",
    "sem_animacao": "无动画",
    "na_leitura_horizontal_arraste_a_pagina": "在横向阅读中，从边缘拖动页面以用手指折起。中途松手可取消翻页。",
    "ouvir_leitura": "收听",
    "continue_de_onde_parou_no_seu_ritmo": "从上次停下的地方，以您自己的节奏。",
    "livro": "书",
    "pronto_para_comecar": "准备好开始",
    "voz": "声音",
    "escolha_uma_voz_disponivel_no_disposit": "选择此设备上可用的声音",
    "voz_padrao_do_sistema": "系统默认声音",
    "durante_a_reproducao": "播放中",
    "a_leitura_avanca_pagina_a_pagina_os_co": "朗读逐页前进。浏览器支持时会出现系统控件。",
    "organizar_livro": "整理书籍",
    "estantes_colecoes_tags_e_status": "书架、合集、标签和状态。",
    "cancelar": "取消",
    "salvar": "保存",
    "grifos_citacoes_notas_e_marcadores_des": "此书的高亮、引用、笔记和书签。",
    "sumario": "目录",
    "toque_em_um_capitulo_para_ir_direto_ao": "轻触章节直接前往。",
    "sua_anotacao": "您的笔记",
    "edite_ou_adicione_comentarios_ao_seu_t": "编辑或添加对您段落的评论。",
    "trecho": "段落",
    "sua_nota": "您的笔记",
    "salvar_nota": "保存笔记",
    "agrupar_biblioteca": "分组书库",
    "escolha_como_os_livros_serao_organizad": "选择书籍在书架上如何排列。",
    "ao_arrastar_um_livro_para_outra_posica": "当您把书拖到别处时，书架会自动切换到我的顺序，并保持您排好的顺序。",
    "backup_e_restauracao": "备份与恢复",
    "sua_estante_seu_progresso_e_suas_marca": "您的书架、进度和标记在一个文件里。",
    "escolha_uma_dimensao_para_explorar_sua": "选择一种方式探索您的书库。",
    "capitulos": "章节",
    "a_voz_nao_fica_mais_grave_nem_mais_agu": "声音不会变得更低沉或更尖细。此设置适用于本书和之后的书。",
    "ajuste_fino": "微调",
    "timer_de_sono": "睡眠定时器",
    "o_audio_diminui_de_volume_aos_poucos_e": "音频音量逐渐减小，然后自动暂停。",
    "pontos_que_voce_guardou_neste_audioliv": "您在此有声书中保存的位置。",
    "ajustes_do_audio": "音频设置",
    "as_preferencias_ficam_salvas_para_todo": "这些偏好会为每本有声书保存。",
    "botao_de_voltar": "后退按钮",
    "botao_de_avancar": "前进按钮",
    "recuar_ao_retomar": "恢复时后退",
    "depois_de_uma_pausa_longa_volta_alguns": "长时间暂停后，退回几秒钟以便您重新找到线索。",
    "tocar_ao_abrir": "打开时播放",
    "ao_tocar_em_um_audiolivro_na_estante_a": "在书架上轻触有声书会立即开始播放。",
    "no_computador_espaco_toca_e_pausa_pula": "在电脑上：space 播放和暂停 · ← → 跳过 · Shift + ← → 切换章节 · ↑ ↓ 音量 · B 书签 · [ ] 速度。",
    "converter_pdf_para_epub": "将 PDF 转换为 EPUB",
    "prepare_o_livro_para_leitura_fluida_e": "将书准备为流畅、可调整的阅读。",
    "confirmacao": "确认",
    "confirmar": "确认",
    "processando": "处理中",
    "documento": "文档",
    "buscar_livros_no_dispositivo": "在此设备上查找书籍",
    "encontre_arquivos_epub_mobi_cbz_cbr_e": "查找设备上已保存的 EPUB、MOBI、CBZ、CBR 和 M4B 文件。",
    "juntar_em_um_unico_audiolivro": "合并为一本有声书？",
    "titulo": "标题",
    "autor": "作者",
    "importar_separados": "分开导入",
    "bem_vindo_ao_veredas_reader": "欢迎来到 Veredas Reader",
    "sua_biblioteca_de_leitura_inteiramente": "您的阅读书库，完全在您自己的设备上。",
    "buscar": "搜索",
    "importar_livro": "导入书籍",
    "buscar_titulo_autor_tag": "搜索标题、作者、标签...",
    "fechar_busca": "关闭搜索",
    "navegacao_da_biblioteca": "书库导航",
    "fechar_menu": "关闭菜单",
    "agrupar_livros": "分组书籍",
    "voltar": "返回",
    "marcar_pagina": "标记页面",
    "personalizar": "自定义",
    "navegacao_principal": "主导航",
    "acoes_do_trecho": "段落操作",
    "amarelo": "黄色",
    "verde": "绿色",
    "rosa": "粉色",
    "azul": "蓝色",
    "player_de_audiolivro": "有声书播放器",
    "minimizar_player": "最小化播放器",
    "minimizar": "最小化",
    "video_em_reproducao": "视频播放中",
    "abrir_a_lista_de_capitulos": "打开章节列表",
    "posicao_no_audio": "音频中的位置",
    "alternar_entre_o_progresso_do_capitulo": "在章节进度和整本书进度之间切换",
    "capitulo_anterior": "上一章",
    "voltar_15_segundos": "后退 15 秒",
    "reproduzir": "播放",
    "avancar_30_segundos": "前进 30 秒",
    "proximo_capitulo": "下一章",
    "velocidade_de_reproducao": "播放速度",
    "marcar_este_ponto": "标记此位置",
    "ver_marcadores": "查看书签",
    "silenciar": "静音",
    "volume": "音量",
    "audiolivro_em_reproducao": "有声书播放中",
    "abrir_o_player": "打开播放器",
    "fechar_o_player": "关闭播放器",
    "fechar": "关闭",
    "trecho_anterior": "上一段",
    "iniciar_leitura": "开始朗读",
    "proximo_trecho": "下一段",
    "escreva_seu_comentario_interpretacao_o": "写下您的评论、解读或提醒...",
    "cancelar_importacao": "取消导入",
    "nome_do_audiolivro": "有声书名称",
    "nome_do_autor": "作者名称",
    "idioma": "语言",
    "idioma_do_aplicativo": "应用语言",
    "o_aplicativo_segue_o_idioma_do_apare": "应用跟随您设备的语言。如果您的语言还不在这里，它会以英语打开。",
    "seguir_o_aparelho": "跟随设备",
    "fazer_backup": "立即备份",
    "todos": "全部",
    "lidos": "已读完",
    "pausados": "已暂停",
    "autores": "作者",
    "tags": "标签",
    "grifar": "高亮",
    "anotar": "记笔记",
    "enviar": "发送",
    "restaurar_padroes": "恢复默认",
    "voltar_para_1": "回到 1×",
    "marcar_agora": "现在标记",
    "escolher_pasta": "选择文件夹",
    "juntar_em_um_audiolivro": "合并为一本有声书",
    "sobre": "关于",
    "licencas_de_codigo_aberto": "开源许可",
    "configuracoes": "设置",
    "temas_e_idioma": "主题和语言"
  },
  "aviso": {
    "idioma_trocado": "语言已更改。"
  },
  "vn": {
    "quem_le": "朗读声音",
    "natural": "自然",
    "do_sistema": "系统",
    "nota_sistema": "使用设备上已安装的声音。想要更接近真人的朗读，请选择“自然”。",
    "nota_sistema_com_natural": "自然声音仍保留在设备上。随时可以切换回“自然”。",
    "voz_natural": "自然声音",
    "gerada_no_aparelho": "更接近真人的声音，直接在设备上生成。",
    "progresso_download": "下载进度",
    "x_de_y": "{x} / {y}",
    "aviso_arquivo": "自然声音需要通过应用的网址打开 Veredas，而不是作为电脑上的文件打开。在此之前，将使用系统声音朗读。",
    "aviso_navegador": "此浏览器缺少自然声音所需的功能。将继续使用系统声音朗读。",
    "verificando": "正在检查自然声音…",
    "fato_download": "只需下载一次，大小 {tamanho}。之后无需联网即可使用。",
    "fato_wifi": "建议使用 Wi-Fi。可以暂停，稍后继续。",
    "fato_privacidade": "书中的文字不会离开设备。",
    "fato_idiomas": "支持英语、葡萄牙语、西班牙语等 31 种语言，暂不支持中文。不支持的语言继续使用系统声音。",
    "baixar_voz_natural": "下载自然声音（{tamanho}）",
    "licenca_curta": "Supertone 的 Supertonic 3 模型，采用 OpenRAIL-M 许可。详情见“关于 > 开源许可”。",
    "pode_continuar_usando": "下载时可以继续阅读。如果连接中断，下载会从中断处继续。",
    "pausar_download": "暂停下载",
    "erro_espaco": "设备空间不足，无法完成下载。请释放一些空间后重试。",
    "erro_offline": "当前未连接互联网。已下载的部分已保存。",
    "erro_rede": "下载过程中连接中断。已下载的部分已保存。",
    "download_pausado": "下载已暂停。已下载的部分已保存。",
    "continuar_download": "继续",
    "descartar": "舍弃",
    "voz_feminina": "女声",
    "voz_feminina_desc": "柔和平静",
    "voz_masculina": "男声",
    "voz_masculina_desc": "温暖沉稳",
    "parar_amostra": "停止试听",
    "ouvir_amostra_de": "试听：{voz}",
    "escolha_a_voz": "选择声音",
    "qualidade": "质量",
    "q_auto": "自动",
    "q_rapida": "快速",
    "q_maxima": "最佳",
    "q_auto_desc": "根据设备性能自动调整，让朗读流畅不停顿。",
    "q_rapida_desc": "更快地生成声音。适合配置较低的设备。",
    "q_maxima_desc": "音质最精致。在配置较低的设备上，句子之间可能会有停顿。",
    "ocupa": "在此设备上占用 {tamanho}",
    "remover": "移除",
    "baixar_pelos_dados": "使用移动数据下载？",
    "baixar_pelos_dados_msg": "设备似乎未连接 Wi-Fi。下载大小为 {tamanho}，可能会消耗流量套餐。",
    "baixar_agora": "仍然下载",
    "pronta": "自然声音已准备就绪。",
    "download_interrompido": "下载已停止。方便时轻触“继续”即可。",
    "remover_titulo": "移除自然声音？",
    "descartar_titulo": "舍弃此下载？",
    "remover_msg": "将释放 {tamanho}。朗读会改回系统声音，之后随时可以重新下载。",
    "descartar_msg": "已下载的部分将被删除。",
    "removida": "已从此设备移除自然声音。",
    "amostra_falhou": "无法在此设备上播放试听。",
    "amostra": "你好！用自然声音朗读，书听起来就是这样。",
    "gerando_voz": "正在准备声音…",
    "automatico_idioma": "自动（{idioma}）",
    "automatico": "自动",
    "so_voz_do_sistema": "系统声音",
    "aviso_idioma": "文本语言：{idioma}。自然声音暂不支持此语言，因此将使用系统声音朗读本书。",
    "aviso_idioma_desconhecido": "无法识别此文本的语言。请在下方选择语言以使用自然声音。",
    "aviso_falha": "自然声音目前无法在此设备上运行。将继续使用系统声音朗读。",
    "nao_carregou_usando_sistema": "自然声音未能在此设备上加载。正在使用系统声音朗读。",
    "parou_usando_sistema": "自然声音已停止。继续使用系统声音。",
    "aparelho_lento": "此设备生成声音较慢。选择“快速”质量可避免停顿。",
    "idioma_do_texto": "文本语言",
    "idioma_do_texto_dica": "根据文本内容识别。如果发音不对，可以更改。",
    "leitura_em_voz_alta": "朗读",
    "lento_usando_sistema": "自然声音在此设备上太慢，将继续使用系统声音朗读。",
    "aviso_lento": "此设备无法以朗读的速度生成自然声音，因此暂时改用系统声音。"
  }
});